### ISSUE TITLE
Powerpoint/Keynote Remote control request

### ISSUE THREAD

**Issue by Deanbau** [bitfocus/companion#10]
Would be great to have a companion for the companion app to be able to control the following functions for keynote and powerpont

- Next slide
- Previous Slide
- Black
- Go to top (slide 1) 
- Go to x slide

And receive the following data back

- Current slide number
- Total number of slides in deck

**Comment by willosof** [comment]
Humm.. Maybe this can be solved with running a applescript service on the ppt/keynote machines. It's no other direct way of controlling powerpoint/keynote i think?

**Comment by PerRoine** [comment]
I'm taking the liberty of closing this as we now support Octopus listener and this is both windows and mac and do support custom Powerpoint and Keynote 
We also support PPT Remote Show Control by Irisdown.com which is a plugin for PPT for Windows 

There will be additional support coming with Apple Script and other listeners on the remote machine
