### ISSUE TITLE
Module Request: Remote Show Control (PowerPoint)

### ISSUE THREAD

**Issue by willosof** [bitfocus/companion#100]
Remote Show Control
http://www.irisdown.co.uk/rsc.html

For controlling powerpoint on windows

**Comment by PerRoine** [comment]
Module is made but it needs to be tested on another machine my Office 365 crashes when i try to close a file and i have problem with maintaining connection to the plugin

**Comment by JeffreyDavidsz** [comment]
Hi Per, can you upload to git? I can try to test it for you

**Comment by JeffreyDavidsz** [comment]
check it had fallen of the page... needed to zoom out

**Comment by DaveShep** [comment]
The TCP listener will drop connection after a command, to permit multiple controllers. Also it was initially written for Spyder, which drops connection immediately after command. I would go with UDP if this causes you a problem.

I will take a look at the close method.

**Comment by DaveShep** [comment]
Cos I write bad code?

**Comment by JeffreyDavidsz** [comment]
UDP leaves the connection open? This is no problem in the module right? Just change to UDP then. OctopusListener is also working for powerpoint and mac, still some issues but main stuff is working

**Comment by willosof** [comment]
UDP has no connection state nor retransmission if a packet is lost.

TCP is the best way to go, and yes, you can have multiple clients connected at once ;)

**Comment by haakonnessjoen** [comment]
We could rewrite the module to open TCP  connection only when issuing commands. And maybe use ping to check if the device is still available. Let’s not make it a bigger issue than it is.

**Comment by haakonnessjoen** [comment]
I have now rewritten the module to better suit Remote show control. Could anyone please test it a bit?

**Comment by DaveShep** [comment]
I've redone the network code for TCP connections so that it behaves as you would expect. Will be able to release in a day or two.

**Comment by DaveShep** [comment]
Version 1.2 available here. New network code allowing multiple tcp and udp connections. TCP connections should now be maintained.

Can you reproduce the Close error? Specifically, was the file unchanged or would it need saving before closing?

**Comment by haakonnessjoen** [comment]
Has been proven to work.

**Comment by q2000drum** [comment]
Running Bitfocus Companion from a Raspberry PI 4B. Created a button using the "RUN" command with the slide deck open. When pressed it starts the slide show, yippie. I have another button with the "NEXT" command, when pressed it closes the slide show and also closes the file. Using HTTP Generic and the command is http://192.1689.1.23:61001/NEXT

2/19/2021 3:44 PM	TCP new client connected 192.168.1.66:46750
2/19/2021 3:44 PM	192.168.1.66 Command: RUN - done - lone
2/19/2021 3:46 PM	TCP new client connected 192.168.1.66:46752
2/19/2021 3:46 PM	192.168.1.66 Command: CLOSE - done [C:\Users\User\Google Drive\WesleyServices\2021\02 - February 2021\02-21-21 - Lent 1\Feb 21 2021-QRL.pptx]
