### ISSUE TITLE
[BUG] cant ad new buttons

### ISSUE THREAD

**Issue by soundpartner** [bitfocus/companion#1000]
**Describe the bug**
i cant create new buttons in companion. i have addet a lot of buttons by copy paste and by exporting paged and importing them and editing them but i cant create new buttons with new action

**To Reproduce**
a have a complete export of my show here https://www.dropbox.com/s/y5kkgvdhl8zrnrl/CompanionPi_full-config_20200221-1618.companionconfig?dl=0
when i try to ad a new normal button it could be qlab -15 panic it wont ad the action
i have made a small video https://www.dropbox.com/s/cs882wa6p027mg3/Sk%C3%A6rmoptagelse%202020-02-21%20kl.%2023.24.06.mov?dl=0

**Expected behavior**
i would expect it to ad the buttons

**Screenshots**
i have uploadet videos look at links above
**Desktop (please complete the following information):**
 - OS: its running on a raspberry pi 4b with 4 gb of ram
 - Browser chrome
 - Companion Version 2.0

**Additional context**
its running on pipanion, the raspberry pi image with companion preinstaled

**Comment by haakonnessjoen** [comment]
What happens if you first click "Erase", on the button, and then create a regular button again?

**Comment by josephdadams** [comment]
@soundpartner did you try what @haakonnessjoen suggested?

**Comment by josephdadams** [comment]
@soundpartner any update?

**Comment by soundpartner** [comment]
exactly the same

**Comment by josephdadams** [comment]
@soundpartner is this still happening for you in the latest release?

**Comment by Julusian** [comment]
This sounds like a bug I cant find which I know was fixed.

Closing as it looks rather stale and has likely been fixed
