### ISSUE TITLE
Suggestion: Developer branch

### ISSUE THREAD

**Issue by thargy** [bitfocus/companion#1004]
Would it be possible to create a `development` branch which includes a single 'template' module demonstrating best practice for module creation?

This branch could be kept automatically updated from master on successful release builds, with the sole difference being the lack of modules, except the template.  Though, there would be the future ability to add 'development-only' features.

Developer instructions could then be encouraged to fork from the `development` branch rather than master, and to use it for developing new or existing modules.

A new script could be created for copying the template module to create a new module.

We could also have a script for pulling down a single companion module's repo.

The main benefit of this is it would allow much quicker development set up, as you wouldn't have to pull the 177 (currently!) companion modules down, update, etc. every time you set up a build.

It would also allow you to maintain a single 'recommended' template module, for people to copy best practice from, rather than scanning through and potentially picking an 'out of date' or 'bad example' module.  This would make it much easier to maintain a standard.

**Comment by Julusian** [comment]
With the changes coming in 3.0, this `development` branch will no longer be beneficial
