### ISSUE TITLE
RaspberryPi Image: [BUG] Cannot run shell scripts

### ISSUE THREAD

**Issue by macflo1508** [bitfocus/companion#1007]
After installing companionPi from the newly released image, I can not run shell scripts anymore, for example:

Action: Internal: run shell path(local)
Options(Path): /sbin/reboot

or

Action: Internal: run shell path(local)
Options(Path): /sbin/shutdown

With my previous self made pi installation this was working fine.

**Comment by haakonnessjoen** [comment]
I havent used this image myself, but try sudo in front of these commands, as they require root elevation

**Comment by macflo1508** [comment]
> I havent used this image myself, but try sudo in front of these commands, as they require root elevation

I am running it from a button „ Action: Internal: run shell path(local)“
How do i run ist root from there?

**Comment by haakonnessjoen** [comment]
In "Options(Path):" try: `sudo /sbin/shutdown`
I guess since it expects a path, it might not work. But it's worth a try.

**Comment by JeffreyDavidsz** [comment]
I think the image uses different folders then the manunual installs. Read the RaspberryPi on Wiki here. and try to do `shutdown now` without the /sbin/

**Comment by macflo1508** [comment]
The path is correct and it does work on my previous, selfbuilt Pi install.
This is the error message I get, which is the same for any script I try to run:

27. 08:43:32 instance(internal): Shell command failed. Guru meditation: {"killed":true,"code":null,"signal":"SIGTERM","cmd":"/sbin/shutdown"}


> I think the image uses different folders then the manunual installs. Read the RaspberryPi on Wiki here. and try to do `shutdown now` without the /sbin/

How do I initiate `shutdown now`from a button any other way?

**Comment by JeffreyDavidsz** [comment]
in the `./tools` directory is a file called `shutdownpi.sh`  it has a simple command `sudo shutdown -h now`. Try to execute that file: `./tools/shutdownpi.sh`

**Comment by macflo1508** [comment]
> in the `./tools` directory is a file called `shutdownpi.sh` it has a simple command `sudo shutdown -h now`. Try to execute that file: `./tools/shutdownpi.sh`

Doesn't work. Gives me this error message:

> 27. 09:25:45 instance(internal): Shell command failed. Guru meditation: {"killed":false,"code":126,"signal":null,"cmd":"./tools/shutdownpi.sh"}

**Comment by jarodwsams** [comment]
I've got shell command buttons running on mine at my venue. For shutdown, try this:
```sudo poweroff```

Also, do you get any feedback when you try to run `shutdown now` from an SSH terminal?

**Comment by macflo1508** [comment]
> I've got shell command buttons running on mine at my venue. For shutdown, try this:
> `sudo poweroff`
sudo poweroff and sudo reboot actually works, but poweroff will not turn off the raspberry completely. The LED is still on until i press the power button for 3 secs to turn it off (GPIO controlled)

> Also, do you get any feedback when you try to run `shutdown now` from an SSH terminal?
sudo shutdown now works, but also doesn't turn off the Raspberry completely

**Comment by macflo1508** [comment]
> I've got shell command buttons running on mine at my venue. For shutdown, try this:
> `sudo poweroff`
> 
> Also, do you get any feedback when you try to run `shutdown now` from an SSH terminal?

`sudo poweroff` and `sudo reboot` actualy work, but `sudo poweroff` will not turn off the Raspberry completely. The LED indicator is still on.

`sudo shutdown now` will work via Terminal
`shutdown now` will give permission denied error

**Comment by jarodwsams** [comment]
> `shutdown now` will give permission denied error

try setting your button as
```sudo /path/to/shutdown_script.sh```

**Comment by millsemillse** [comment]
i wrote a shutdown.sh in home dir

#! /bin/sh
sudo /sbin/shutdown -h now

chmod as you need it, and execute     /home/pi/shutdown.sh   via companion

#! /bin/sh
sudo /sbin/reboot                       for reboot.sh

**Comment by josephdadams** [comment]
@macflo1508 let us know if the workarounds provided do not work and we can revisit this.
