### ISSUE TITLE
[BUG] Companion app closes over time

### ISSUE THREAD

**Issue by tfling98** [bitfocus/companion#1012]
I was working on our Mac and noticed that after a few hours the Companion app had closed and caused the stream deck to lock up.

Mac OS Mojave
Safari 
Stream Deck 15

**Comment by josephdadams** [comment]
What version of Companion?

**Comment by tfling98** [comment]
Sorry, 2.0

**Comment by josephdadams** [comment]
What modules/instances are you using? Do you get any error messages?

**Comment by tfling98** [comment]
Im using blackmagic atem, sony ptz, and aja kumi instances. No error message the app just closes after a few hours.

**Comment by bryce-seifert** [comment]
If you're using the ATEM module, possibly related to this? https://github.com/bitfocus/companion-module-atem/issues/50

**Comment by josephdadams** [comment]
@tfling98 did updating after the ATEM fix help your issue?

**Comment by tfling98** [comment]
Yes. Thank you!
