### ISSUE TITLE
Stream Deck XL Connects to Streamdeck software but doesnt show up in Companion

### ISSUE THREAD

**Issue by noahsargent** [bitfocus/companion#1017]
Hi, 

I just bought a streamdeck XL and can see/program keys from the streamdeck software, but the deck doesn't show up in the surfaces list in companion. I ran the companion v1.4.0 software and am not sure if I set up the program correctly. 

Here are the current settings;
Gui Interface 
localhost / 127.0.0.1
8000 

I honestly don't know what "8000" does. Within companion, I can see my ATEM 2/ME, but the only controller I see is the Virtual Controller. 

Thank you ahead of time for any help,
Noah

**Comment by noahsargent** [comment]
Apparently there's a post on the facebook page that states the 1.4 version of the software doesn't support Streamdeck XL (Common issue). So there's a developer version, but I've yet to find it. If anyone has a link, please post it here :)

**Comment by noahsargent** [comment]
https://bitfocus.io/companion/download/builds/

**Comment by josephdadams** [comment]
You can access the developer builds from the same page as you would download the official release. Look for the small text in the bottom right-hand side of the box. As you stated, 2.0 is the only version compatible with the XL.

**Comment by paukenist** [comment]
I used the 2.0 on the OSX but the rows where mixed up, cam6 apears on the first row as suspected, but  also on the second row  How can i use the xl with my atem 2m/e
