### ISSUE TITLE
companion no connect with Streamdesk XL

### ISSUE THREAD

**Issue by addiel365** [bitfocus/companion#1025]
Hi I bought a new Streamdesk today and is not connecting work perfect with streamdesk software but no with companion
my email is addiel_perera@yahoo.es

**Comment by CrazySimz** [comment]
Witch version? The XL is only working with the 2.0.

**Comment by josephdadams** [comment]
@addiel365 for XL support, please use the latest version of Companion 2.0. It is not officially released yet but easily available. Thanks!

**Comment by addiel365** [comment]
Thanks very mucho now work perfect 

Addiel Photography and Videography 
Phone: (561) 324-7448
addielphotovideo@gmail.com
www.addielphotography.com
