### ISSUE TITLE
[BUG] Unable to get 15 Button Stream Deck to work -Pi Version-

### ISSUE THREAD

**Issue by Red7Hunter** [bitfocus/companion#1026]
Hello!

I have a recently purchased the a new 15 button stream deck.. I am unable to get it to work.. I am replacing my 6 button which works fine..

I even purchased a second one thinking it was an issue.. The device doesn't show up in on controllers.. usb scan doesn't help..  I just has the large stream deck logo on it.

I've just upgraded the version and it continues
 Pi Version 2.0.0 (669ce2-1751)[BUG]

I've been unable to get it to work.... If i reboot with my 6 button plugged in it starts up just fine.. Reboot again this time with the 15 button plugged in nothing.. Even after usb controller scan.. I am unable to get it to show up on list.

I've tried dev mode.. no difference..

Any ideas?

Red7Hunter

**Comment by Red7Hunter** [comment]
Did some testing with windows stream deck software... Older version of stream deck software also doesn't recognize this unit i purchased.

Its model is a: 20GAA9902

There's been some update in the model or firmware that is making it not compatible any more.

Red

**Comment by josephdadams** [comment]
Yes, all 9902 units do not work with Companion 1.4. You must use Companion 2.0.

**Comment by Red7Hunter** [comment]
Josephdadams,

I am running 2.0.0  i provided the build info in the post?

![image](https://user-images.githubusercontent.com/61927809/76559829-441ea900-6476-11ea-97f3-64ae6f3d50bc.png)

Red

**Comment by JeffreyDavidsz** [comment]
Please update to a newer build

**Comment by Red7Hunter** [comment]
@JeffreyDavidsz 

So I updated to this version this morning:
![image](https://user-images.githubusercontent.com/61927809/76785298-953adf80-678b-11ea-8b82-e22a51a572d5.png)

And I still get an error and it still doesn't work and get this error in the log:

![image](https://user-images.githubusercontent.com/61927809/76785366-b26fae00-678b-11ea-98e9-d40f58742413.png)

And nothing shows up under connected devices and rescan usb doesnt help.

Any ideas?
Red

**Comment by haakonnessjoen** [comment]
Make sure you have followed the /etc/udev/rules.d/50-companion.rules part of https://github.com/bitfocus/companion/wiki/Manual-Install-on-Raspberry-Pi and that the full list is included in your file if you have upgraded from an earlier version.

**Comment by Red7Hunter** [comment]
I can confirm I started this image from the 2.0 and followed those instructions.

Red

**Comment by josephdadams** [comment]
Can you start over?

**Comment by Red7Hunter** [comment]
@josephdadams 

I have another PI unit I can test with maybe tonight.  Just follow all the instructions form @haakonnessjoen post?  Anything else?

Red

**Comment by jarodwsams** [comment]
@Red7Hunter The issue you're seeing is a known issue with the current CompanionPi build. The first version of the CompanionPi image doesn't include hardware rules for the newer 15-button deck. The fix is simple:

1. In an SSH terminal window, `sudo nano /etc/udev/rules.d/50-companion.rules`
2. Delete all current contents of that file and replace with the following (copy/paste is your best friend)  
```SUBSYSTEM=="input", GROUP="input", MODE="0666"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", MODE:="666", GROUP="plugdev"
KERNEL=="hidraw", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", MODE:="666", GROUP="plugdev"
SUBSYSTEM=="usb", ATTRS{idVendor}=="ffff", ATTRS{idProduct}=="1f40", MODE:="666", GROUP="plugdev"
KERNEL=="hidraw", ATTRS{idVendor}=="ffff", ATTRS{idProduct}=="1f40", MODE:="666", GROUP="plugdev"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0063", MODE:="666", GROUP="plugdev"
KERNEL=="hidraw", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0063", MODE:="666", GROUP="plugdev"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006c", MODE:="666", GROUP="plugdev"
KERNEL=="hidraw", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006c", MODE:="666", GROUP="plugdev"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006d", MODE:="666", GROUP="plugdev"
KERNEL=="hidraw", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006d", MODE:="666", GROUP="plugdev"
SUBSYSTEM=="usb", ATTRS{idVendor}=="ffff", ATTRS{idProduct}=="1f41", MODE:="666", GROUP="plugdev"
KERNEL=="hidraw", ATTRS{idVendor}=="ffff", ATTRS{idProduct}=="1f41", MODE:="666", GROUP="plugdev"
```

3. Reboot your Pi and you should be good to go

**Comment by Red7Hunter** [comment]
I was able to get the button to work with doing a fresh install and following the directions.  Those directions must have the updated hardware rules.  

I can still test my old install with the code @jarodwsams provided later today and report back if it resolves it.

Red

**Comment by jarodwsams** [comment]
The manual installation instructions do have the updated rules. The CompanionPi image does not, yet. I'll fix that when I refresh the image when v2 moves out of beta.

**Comment by Red7Hunter** [comment]
All,

I updated the code in the .rules folder and got a different error from the manual installation that @haakonnessjoen  linked and that fixed my issues with usb device.

It be helpful to know when that file needs to be updated as it appears not to be updated when you update companion??

Red

**Comment by jarodwsams** [comment]
No, the file is not updated when you update companion. It is a system file, rather than an application file.

**Comment by CrazySimz** [comment]
I see the new image of the Companion Pi!! Do we need to flash the SD card again with
 the new file or an update willd do the thing?

**Comment by jarodwsams** [comment]
If everything is working for you, then all you would really need to do is run:
```sudo companion-update
sudo apt update && sudo apt upgrade -y```
This should get you to parity with the new image. If things _aren't_ working, then I would flash the new image.
You can always backup your config, flash the new image, then import your config backup. That whole process would probably take, 15-20 minutes, give or take.

**Comment by jarodwsams** [comment]
@Red7Hunter Have you had any more recurrence of this issue, or can we close the ticket back up?

**Comment by Red7Hunter** [comment]
You can close it back up..  Thanks again for the help

**Comment by jarodwsams** [comment]
@josephdadams or @haakonnessjoen can one of you gents close this ticket back up per Red's confirmation above? Thank you.
