### ISSUE TITLE
[BUG] Dropdown selection not saved when only single result available

### ISSUE THREAD

**Issue by geoffhouse** [bitfocus/companion#1029]
**Describe the bug**
When there's only a single value available in a dropdown list, it's not saved to the options when a button is created

**To Reproduce**
1. Use a module with a single result in a dropdown!
2. Add a button with a dropdown
3. Click on the dropdown to see the options

**Expected behavior**
The selected (and only) dropdown should be saved

**Screenshots**
![Screenshot 2020-03-09 at 22 40 17](https://user-images.githubusercontent.com/6639674/76263604-3939fd80-6257-11ea-8f7d-ea34fc218fc9.png)

**Desktop**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: 2.0.0 (2.0.0-b08a1fd-2093)

**Comment by krocheck** [comment]
This could be an issue with the module itself ... which module is this action for?

**Comment by geoffhouse** [comment]
It's certainly possible - I'm writing the module at the moment. 
I don't have access to other devices which would give me a single result in a dropdown, but if you're telling me it works elsewhere then I'll happily close the bug. 
Thanks! :)

**Comment by krocheck** [comment]
I'd have to look at the code to wager a guess.  Its rare there's a dropdown with a single option, so I need to dig deeper.

**Comment by JeffreyDavidsz** [comment]
I don't think this is an issue with the module, have had the same problem with eventmaster. I believe it's also the case with config. Need to apply first. It's probably in the default value that shows but doesn't store

**Comment by josephdadams** [comment]
I can confirm that this happens; I had an action dropdown that only had 1 value (the values are pulled dynamically upon module init), and it sends null.

**Comment by MarcHagen** [comment]
Maybe bit old topic, but it's still relevant now. Could we get sometime into this?
I manage the pearl module but it's worse now than before somehow.

I originally sended just a option list like this:
```javascript
[
  {
    id: '4-1',
    label: 'CameraTrackingRegie - Web+Barco+Cams',
    channelLabel: 'CameraTrackingRegie',
    layoutLabel: 'Web+Barco+Cams'
  },
  {
    id: '4-2',
    label: 'CameraTrackingRegie - Barco+Cams',
    channelLabel: 'CameraTrackingRegie',
    layoutLabel: 'Barco+Cams'
  },
  {
    id: '4-3',
    label: 'CameraTrackingRegie - Cams',
    channelLabel: 'CameraTrackingRegie',
    layoutLabel: 'Cams'
  }
]
```
And the first option in the dropbox would be automatically assigned to the button.
Now (as of master branch companion) the returning result is null 
```javascript
{
  id: 'DCq1C-hBt',
  label: 'WtTSK6Th_:channelChangeLayout',
  instance: 'WtTSK6Th_',
  action: 'channelChangeLayout',
  options: { channelIdlayoutId: null }
} 
```

To get around this i have added a "dummy do select something" to get the dropdown field updated so it will populate the right ids to the actions.

```javascript
[
  { id: '0-0', label: '---' },
  {
    id: '4-1',
    label: 'CameraTrackingRegie - Web+Barco+Cams',
    channelLabel: 'CameraTrackingRegie',
    layoutLabel: 'Web+Barco+Cams'
  },
  {
    id: '4-2',
    label: 'CameraTrackingRegie - Barco+Cams',
    channelLabel: 'CameraTrackingRegie',
    layoutLabel: 'Barco+Cams'
  },
  {
    id: '4-3',
    label: 'CameraTrackingRegie - Cams',
    channelLabel: 'CameraTrackingRegie',
    layoutLabel: 'Cams'
  }
]
```

**Comment by JeffreyDavidsz** [comment]
Try to put a `default: ID`

**Comment by MarcHagen** [comment]
Well yeah, but I can cause the whole input selection is dynamic. 
i could just grab the first ID in that array sure.

**Comment by josephdadams** [comment]
I started putting an entry at the beginning like `(select an option)` with a value that would be outside the range of my ID structure.

**Comment by Julusian** [comment]
I believe that the new ui changed this behaviour and it will now work correctly. Let me know if not and I shall reopen
