### ISSUE TITLE
Request: Authentication for GUI

### ISSUE THREAD

**Issue by Deanbau** [bitfocus/companion#103]
**Describe the feature**
Simple password required for access to web GUI. Password is set in the application window.

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
None required

**Usecases**
Running Companion on a open network, it would be advisable to have a password on the app controlling your show

**Comment by willosof** [comment]
This is in theory something I wanted to fix for 1.2.0, but after thinking about it, I find a couple of issues with this whole thing.

Running companion on an open network will:
1) Expose OSC triggering
2) Expose ArtNet triggering 
3) Expose the AdminGUI
4) Expose the webserver HTTP /press/page/bank URL's

Should ONLY option 3 be password protected, but 1,2 and 4 be accessible from everyone? The closest thing to a solution here would be to make a IP filter, telling companion which IPs to allow remote communication from. Would that be an option? With that we could block 1,2,3,4 all together.

**Comment by PerRoine** [comment]
I think the IP Blocking is a good way to increase security. and as you state that will increase the security for all exposed ports not only Gui and HTTP wich leaves some gaping holes or reduced functionality for companion of course I do want a enable disable the whole blocking function.

**Comment by hadphild** [comment]
Companion for the install market would be great for just stopping a person changing buttons.

**Comment by mschoeffmann** [comment]
> Should ONLY option 3 be password protected, but 1,2 and 4 be accessible from everyone? The closest thing to a solution here would be to make a IP filter, telling companion which IPs to allow remote communication from. Would that be an option? With that we could block 1,2,3,4 all together.

I think #573 is what it's about here.
I do not think that there is a problem with unencrypted/unprotected osc/artnet/http servers (for triggering) since control networks are normally closed networks.

But a really important thing would be a protection for the admin GUI to prevent unauthorized changes to configuration (for fixed installations).

**Comment by danielatsavweb** [comment]
Has this feature been implemented yet? I don't see it. Thanks.

**Comment by olliraa** [comment]
> Has this feature been implemented yet? I don't see it. Thanks.

Also interested. has this been implemented? Running 2.1.4.
