### ISSUE TITLE
[BUG] Action dropdown always starts at beginning

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#1039]
**Describe the bug**
Not sure if this is truly a bug, or just an unimplemented function...
When you add an action to a button, after adding it, the action dropdown shows the last action added. However, when you click the dropdown, the list is back at the start. It would be great if the list would start at the last action, as is shown in the UI.

**To Reproduce**
Add an action to a button. Note that the action you just added is the one shown in the unexpanded dropdown UNTIL you click the dropdown. Then the list starts at the beginning, instead of at the last action, which would be handy.

**Expected behavior**
Action list has last action added highlighted.

**Screenshots**
Not necessary.

**Desktop (please complete the following information):**
 Companion 2.0 beta

**Additional context**
In modules like mine or people with multiple instances, it would save time to have the last action be the one that the dropdown list is at. I know you can use search, but this would make things even better.

**Comment by Julusian** [comment]
Things have changed a bit since this was reported, but it is still the case that it starts from the beginning each time.
It should be possible for the ui to remember the last time you added each action and provide a 'recently used' section at the top of the list

**Comment by Julusian** [comment]
Possibly solved by https://github.com/bitfocus/companion/pull/2014, or some of the implementation from that could be reused if it doesnt get merged
