### ISSUE TITLE
[BUG] 15 button Stream Deck

### ISSUE THREAD

**Issue by spproduction7224** [bitfocus/companion#1041]
**Describe the bug**
Updated to Companion 2.0 to fix one issue it made another one. we have the 15 button Stream Deck. After the update to 2.0 it tries to format the companion buttons to a XL Deck and none of the Buttons line up right with the 15 button Deck

**Expected behavior**
Buttons to be laid out in 15 button format not XL format

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Companion Version 2.0

**Comment by josephdadams** [comment]
Pretty sure this can happen when you upgrade from 1.4 to 2.0. Just rearrange them and make sure at this time you are not also running the native Stream Deck application.

**Comment by spproduction7224** [comment]
If i close the native Stream Deck App it gives me the error that "Stream Deck Plugin Disconnected" and then i cant flip pages on the actual device (Physical Stream Deck)

**Comment by josephdadams** [comment]
Close out Companion. Close out the native app. Open just Companion.

**Comment by josephdadams** [comment]
@spproduction7224 did that work for you?

**Comment by spproduction7224** [comment]
No, but i just moved the commands around so they line up with the buttons on the stream deck

**Comment by spproduction7224** [comment]
If i close stream deck at all it cant function because i have other commands not thru companion i use

**Comment by spproduction7224** [comment]
@josephdadams

**Comment by josephdadams** [comment]
Well, the plugin for the native app and Companion 2.0 aren’t compatible right now. So that’s just how it’s going to be unless you close out the native app or downgrade to Companion 1.4 (not recommended).
