### ISSUE TITLE
[BUG] Dragging Preset to buttons is visually confusing

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#1043]
**Describe the bug**
When you successfully drag a preset to a button, it "flies back" which in any other program would mean that the item did not drop successfully. A successful drop should "land" on the button and not fly back when the mouse is released. Only if the drop were unsuccessful for some reason should the preset "fly back" to it's start.

**To Reproduce**
Drag a preset to a button. When release your mouse button where you want to drop the preset.

**Expected behavior**
If the drop is successful, the dragging preset image should disappear. It doesn't. It "flies back" as though the drop was unsuccessful.

**Screenshots**
Looks like screen recording can't capture a dragging preset

**Desktop (please complete the following information):**
 - OS: MacOS Mojave, Windows 7
 - Browser: Safari, Firefox
 - Companion Version: 2.0

**Comment by krocheck** [comment]
@SteveTherrien is there any quick fix you can think of for this?

**Comment by SteveTherrien** [comment]
Sure, I'll take a look.

**Comment by krocheck** [comment]
Thanks @SteveTherrien !

**Comment by MeestorX** [comment]
Wow! That was fast! Yay @SteveTherrien!
