### ISSUE TITLE
[BUG] image.js crashes if text is undefined

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#1048]
**Describe the bug**
image.js, line 480:
`var displayText = text.trim(); // remove leading and trailing spaces for display`
This line will crash companion if text is undefined. This can happen in the case of feedback, if the text property is accidentally set to undefined.

`var displayText = (text !== undefined) ? text.trim() : '';`
or
`var displayText = (text !== undefined) ? text.trim() : '~NA~';` // some sort of error indication?

Would likely fix the problem.

**To Reproduce**
Add a feedback that changes the text property to undefined.
**Expected behavior**
Not crashing companion

**Comment by Julusian** [comment]
Fixed
