### ISSUE TITLE
[BUG] yarn windist wipes out the electron-output folder

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#1050]
**Describe the bug**
When you run `yarn dist` or `yarn windist`, it clears out the companion/electron-output folder. I like to build for MacOS AND Windows, so if I try to run one after the other, I have to make sure I have grabbed the one and copied it elsewhere first.

**To Reproduce**
In terminal on a Mac, in the companion folder, type `yarn dist`. It creates the MacOS companion build in companion/electron-output/mac
Now type `yarn windist` and it creates the Windows companion build. But first it wipes out the companion/electron-output folder.

**Expected behavior**
Add a companion/electron-output/win folder without wiping out the folder

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Companion Version 2.0

**Comment by maxymapp** [comment]
remove ```rm -rf electron-output``` from package.json "scripts"

**Comment by Julusian** [comment]
I have made this change in develop for 3.0
Without knowing why it was added originally, I am hesitant to remove it in the beta branch
