### ISSUE TITLE
Companion can't connect to StreamDeck XL

### ISSUE THREAD

**Issue by GlobalHD** [bitfocus/companion#1054]
Hello. Hoping these days find you and yours safe and sound!

Simply, Companion cannot find my Stream Deck XL. The Deck is connected to a new 16" MacBook Pro, running Mac OS Catalina 10.15.4, via an Apple USB-C Digital AV Multiport Adapter ( https://www.apple.com/shop/product/MUF82AM/A/usb-c-digital-av-multiport-adapter?fnode=4686f116f7aefbdc1f3f483d8022156e2a4c5acdfda200331d68f72ec5ff181c521675054bb57e86e3e780a2a950aa27b46aeb91492c9bdb466d9ad8384f8eda0b33c79e66ca0dfca800af2a6a22da008ee273c07849e7c4870cebf01afd2e5e ).

Stream Deck is NOT running.

I get no connection.

Kindly advise if you will please.

Thank you!

**Comment by JeffreyDavidsz** [comment]
Which version of Companion are you running? Did you try to connect it directly (without the apple dongle)?

**Comment by GlobalHD** [comment]
Thank you for your reply.
I reinstalled BETA 2.0 and it worked.
Unfortunately, however, it erased all profiles that I’d made already.
Is there a way to incorporate Companion profiles into my profiles without erasing everything?

Thank you for your support. Keep up the good work.

STAY SAFE!

Rob

**Comment by JeffreyDavidsz** [comment]
XL Will only work correctly on the 2.0 beta. Depending on the version you came from, it will mess up your button config. Remember you cannot use it together with the Streamdeck app, yet

**Comment by GlobalHD** [comment]
Understood. Thank you.

Is there a way for me to save my configuration, so I can switch back and forth between Companion sets and Stream Deck Setups?

Novice question, I know, but I’m just getting started

Hoping so.

And thanks again for the support.

Regards,

**Comment by JeffreyDavidsz** [comment]
You can do a backup for each version, but I would stick to 2.0 now

**Comment by GlobalHD** [comment]
You are appreciated. Thank you!

Stay safe!

Rob
