### ISSUE TITLE
Naming Fixtures in Artnet

### ISSUE THREAD

**Issue by lightslayder** [bitfocus/companion#1055]
It would be useful and helpful if we could have the option of giving a fixture in artnet a descriptive name such as "Stage Right Wash" or "Foyer Lights." This would make it easier than only having the DMX Address to go by when changes need to be made. Since this would only be modifying an already existing module it isn't platform specific. Everything else in the module works perfectly and is fine the way it is.

**Comment by josephdadams** [comment]
Are you asking for something like this: https://github.com/bitfocus/companion/issues/760

**Comment by josephdadams** [comment]
Closing since it’s already been requested in the issue referenced.
