### ISSUE TITLE
Request: DSM web interface

### ISSUE THREAD

**Issue by Deanbau** [bitfocus/companion#106]
**Describe the feature**
A customisable, adaptive interface for downstage monitors, run via HTTP server on a different port

Featuring

- Custom timers
- Timer presets 
- Conditional formatting for timer (orange/red/red blinking depending on timer value)
- Time warp (speed up by x% and or target end time
- Current real time
- Slides data (Slide x of y)
- Slides notes
- Video data from feedback from various modules (Next video title, duration)
- Video countdown replaces main countdown when a video is playing (optional)
- Ability to pass on messages to monitor / flash interface

Actions

- Set timer to X
- Pause timer
- Reset timer
- Stop timer

Some how the timer is displayed on a button?

- Switch ppt/keynote machine (to tell companion where to get the correct data for slide data)
- Show/Hide notes

- Pass on canned messages (Wrap up!) etc

Reactions

- Perform certain actions when timer reaches X

**Comment by willosof** [comment]
I guess this is another product. But, we'll make it ;) The ticket doesn't belong in companion anymore though.
