### ISSUE TITLE
[BUG] STATUS_UNKNOWN (or STATE_UNKNOWN) is not referenced in instance.js

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#1060]
**Describe the bug**
If you try
 `this.status(STATUS_UNKNOWN, 'message'); `
You'll just get a blank box in the status on the instances page

**To Reproduce**
Try it!

**Expected behavior**
The message should be shown with some appropriate color behind it.

**Screenshots**

**Additional context**
Lines 52 on in public/instance.js

Need to add something like:
```
// unknown

else if (s[0] === null) {
	$("#instance_status_"+x).html(""+s[1]).attr('title', s[1]).removeClass('instance-status-ok').removeClass('instance-status-error').removeClass('instance-status-disabled').addClass('instance-status-warn')
}
```

But likely a bit more is required!

**Comment by MeestorX** [comment]
PR: https://github.com/bitfocus/companion/pull/1063

**Comment by Julusian** [comment]
@MeestorX can this be closed as the pr is merged?
