### ISSUE TITLE
Error when sending OSC as a UDP-message from Ross Dashboard

### ISSUE THREAD

**Issue by Kimmern1210** [bitfocus/companion#1064]
![image](https://user-images.githubusercontent.com/8957978/78355345-d44f9a00-75ad-11ea-9da0-9742d6d9b0f4.png)
I get this error when I try to send '/style/text/1/1 TEST' to port 12321 to change the text of a button.

![image](https://user-images.githubusercontent.com/8957978/78355500-137deb00-75ae-11ea-9545-3dd519d979c5.png)

**Comment by josephdadams** [comment]
That's because you're not sending it properly from Dashboard. If you want to send OSC from Dashboard, you have to send the OSC as UDP Bytes and build your byte array based on the OSC command and value. I wrote a basic Dashboard custom panel for you to see how it works.
[osc_send.grid.zip](https://github.com/bitfocus/companion/files/4427114/osc_send.grid.zip)

**Comment by Kimmern1210** [comment]
Thanks alot!

**Comment by krocheck** [comment]
@haakonnessjoen we should probably catch this exception tho ... thoughts?

**Comment by Kimmern1210** [comment]
It doesn work when I try the '/style/bgcolor/1/9 255 0 0'-command..

**Comment by josephdadams** [comment]
I’d have to see a screenshot of your dashboard panel but the example I provided does not support multiple arguments.

**Comment by Kimmern1210** [comment]
Ah, I'm just using the panel you sent me to test things out

**Comment by josephdadams** [comment]
Well, that’s why it doesn’t work then. You’re sending 3 integer arguments. You’ll have to modify the dashboard function to support multiple arguments.

**Comment by Kimmern1210** [comment]
Alright. I'm new to OSC-messages so how should I proceed to do so? Check if the value-variable consists of several arguments, loop through those and do the 'if (varType == 'int)' on every argument?

**Comment by josephdadams** [comment]
Yes you will need to loop through each argument and determine the type, however I suggest reading up on the OSC protocol as you will have to structure the byte array very specifically.
