### ISSUE TITLE
How to detect Stream Deck

### ISSUE THREAD

**Issue by jedenpes** [bitfocus/companion#1066]
Hello, 

Im using StreamDeck XL and older drivers  4.5 (because new not work with Vmix) and in Companion I cant find StreamDeck. I closed Streamdeck app, but still cant find.

**Comment by josephdadams** [comment]
What version of Companion?

**Comment by iantech** [comment]
Working with the same issue with someone else - they uninstalled streamdeck's software and it worked

**Comment by josephdadams** [comment]
If you want to use the XL, right now you must use Companion 2.0 and you can’t have the native stream deck app open.

**Comment by jedenpes** [comment]
I have normal StreamDeck and pc where isnt original software and never was.

**Comment by jedenpes** [comment]
I instaled 2.0 and all works!
