### ISSUE TITLE
Allen Heath qu16 [Module Request]

### ISSUE THREAD

**Issue by Colemanguy** [bitfocus/companion#1067]
**PLEASE USE THE FOLLOWING PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE OR SOFTWARE PROGRAM**: https://github.com/bitfocus/companion-module-requests/issues/new
Remote control the allen heath qu series mixers would be super awesome.

**Comment by josephdadams** [comment]
Closing because this has already been requested. https://github.com/bitfocus/companion-module-requests/issues/91

Also you made this request in the wrong place.
