### ISSUE TITLE
companion app / Stream deck

### ISSUE THREAD

**Issue by tedzstonz2000** [bitfocus/companion#1068]
When i start button on Next page ie 1 then go to page to - the button from page one follows - i notice when i push the same buttons the icons will appear from page one and run the command...

**Comment by josephdadams** [comment]
We need more information. What version of Companion? What type of stream deck? Are you also running the native stream deck app?

**Comment by josephdadams** [comment]
Closing due to lack of response from @tedzstonz2000

**Comment by tedzstonz2000** [comment]
i figured it out thanks guys sorry for the late response --- covid 19
