### ISSUE TITLE
infinitton not appearing properly in companion - win 8

### ISSUE THREAD

**Issue by gnomatron** [bitfocus/companion#1072]
On my windows 8.1 laptop my infinitton doesn't show up properly in the surfaces tab of the GUI.

Companion v1.4.0, backport-b402e70-1559

A blank line appears under the streamdeck emulator when the infinitton is connected.

I've tried with the smart editor both running and NOT running, neither helps.

The same companion software version on my macbook pro running 10.14.6 works just fine.

**Comment by willosof** [comment]
Duplicates #1070 and uses 1.4, not valid.
