### ISSUE TITLE
[BUG] [GUI] Importing a .companionconfig from 1.4. adds commands wich was not included in the export

### ISSUE THREAD

**Issue by TreborKutscher** [bitfocus/companion#1074]
After importing a .companionconfig to 2.0 wich was created in version 1.4. commands appear wich was not part of the exported .companionconfig

Also each page gets on butten xx.27 the "page Down label" and on button xx.13 the "current page display"

**Comment by haakonnessjoen** [comment]
Could you please zip the companionconfig, and upload it here? (just drag it to the text field here)

**Comment by TreborKutscher** [comment]
[STUDIO_BERLIN.zip](https://github.com/bitfocus/companion/files/4486252/STUDIO_BERLIN.zip)

**Comment by Julusian** [comment]
This does not appear to be an issue anymore
