### ISSUE TITLE
[BUG] Stream deck plugin does not support Companion 2.0

### ISSUE THREAD

**Issue by spadrille2** [bitfocus/companion#1075]
I have a stream deck XL. I use companion 2.0. I have install the companion button on the stream deck app. As i understand, when i drag and drop a Companion button on the button in the interface, it create a button which should be at the same place that the button in companion. It works for buttons 1 to 8 but then, every other rows are wrong.
Row 2 is buttons 6-7-8-9-10-1-13
Row 3 is buttons 11-12-13-14-15-16-17-18
Row 3 is buttons 16-17-18-19-20-21-22-23
So, some buttons are in double, the buttons are not in the right places and i can't use the button 24 to 32.
Any idea?

**Comment by haakonnessjoen** [comment]
Hi,

The plugin does not yet support companion 2.0. So the best way is to quit the stream deck application, and let companion control the stream deck directly.

But if you need to use the stream deck application as well as companion, there is a beta plugin that you can try out. Please download this and report back any problems with this new stream deck plugin.


[io.bitfocus.companion-plugin.streamDeckPlugin.zip](https://github.com/bitfocus/companion/files/4485888/io.bitfocus.companion-plugin.streamDeckPlugin.zip)

**Comment by spadrille2** [comment]
Thank you very much. The plugin works great !
Have a good day.


Patrick Spadrille
0496 95 51 21
www.patrickspadrille.be

**Comment by josephdadams** [comment]
Closing because the beta plugin fixes the problem.
