### ISSUE TITLE
OSC listener does not respond if extra arguments are sent

### ISSUE THREAD

**Issue by booguiseb** [bitfocus/companion#1076]
Hi,

I'm playing with COMPANION and a smarthub router, everything's fine except that i can't control it from OSC command.
I tested my OSC with osculator, all OK, but Companion doesn't respond.

thanks for your help

**Comment by josephdadams** [comment]
Can you recreate this on another computer? Do you get an error message? Are you sure you are using the correct OSC commands? Please provide more detail.

**Comment by booguiseb** [comment]
Hi Joseph,

I install Companion on a PC, same problem.  There’s no error anywhere. I can see my osc message on OSCULATOR,  from one phone to tablet …

But Companion never react, unless I create a mapping thru osculator., so my command seemed to be OK

Is there a way to monitor incoming message in COMPANION ?

Thanks for your help

**Comment by booguiseb** [comment]
One more thing
From this capture, I can see that osculator is removing some arguments before sending to companion (this command is working)

Is it compulsory ?

**Comment by booguiseb** [comment]
Hi
after some more test, COMPANION doesn't work with TOUCH OSC.
My guess is because of the extra arguments that TOUCH OSC add after the command. can be O or 1 in case of a button or a float. I tried with PROCESSING and it's working right away, if i don't had any INT after my message.
Can it be fixed from COMPANION side ?

Thanks a lot

**Comment by josephdadams** [comment]
@willosof your thoughts on this?

**Comment by rainier1782** [comment]
same here. am trying with touch osc and lemur as well and its not triggering the comapnion

**Comment by millsemillse** [comment]
pls fix :) @josephdadams, anyone reacted to your suggestion?

**Comment by dszoka** [comment]
Is it possible to just add that companion see's the 0 add to the command as correct, Both Touch OSC and Lemur you can set what is sent, so 0 could be default ... Or will that cause problems for other programs 

Would really like to work with people to get this fixed 
 
![Screen Shot 2021-02-18 at 9 40 06 am](https://user-images.githubusercontent.com/42435862/108278382-11754880-71cf-11eb-97ef-9a738b9de775.png)

**Comment by Julusian** [comment]
I have made the osc handling be more forgiving on this.
An int of 1 will trigger a press and an int of 0 will trigger a release (both the same as before)
Anything else will trigger the press and release, it used to be that no parameters were required for this
