### ISSUE TITLE
Problem connecting original Streamdeck to Companion

### ISSUE THREAD

**Issue by setman2** [bitfocus/companion#1077]
I'm having what may be a newbie issue with Companion and Streamdeck.  Running Companion v2.0 with a new 15key Streamdeck that I just bought.  The streamdeck seems to work on it's own with its app, but companion only shows me the Emulator in the Surfaces page.  

![image](https://user-images.githubusercontent.com/63798209/79467556-e0832080-7fcb-11ea-8a4f-d9a02934d0ee.png)

![image](https://user-images.githubusercontent.com/63798209/79467645-fee91c00-7fcb-11ea-8b7f-fb482616b9c3.png)

![image](https://user-images.githubusercontent.com/63798209/79467788-2d66f700-7fcc-11ea-8d3b-853c114ce4cf.png)

There is no link in the Streamdeck settings page to update firmware and the "check for updates" link only gives me an error (reported to Elgato).  I have downloaded the latest Streamdeck software since I just installed this yesterday. 

Rescanning the USB does not help.  Powered everything down and started again with no improvement.  Originally started with v1.4 of Companion then went to beta version to see if that would help.

Running Win10 home 64bit, build 1903 on an Acer laptop. Running Chrome browser.
Connecting to ATEM Mini switcher.  Companion does see the switcher and will control it.

What am I missing?

**Comment by setman2** [comment]
Update on this issue - I've tried this on three Windows machines now with the same results.  Companion does not see the Stream Deck.  I feel like there is a simple setting that I'm missing that will leave me red faced.....

**Comment by krocheck** [comment]
Have you tried quitting the streamdeck software completely before launching Companion?

**Comment by setman2** [comment]
Yes.  I made sure that Companion was running first and tried without ever
launching the sd software or even connecting the SD.

**Comment by setman2** [comment]
Well, red faced am I!  As expected, it was something stupid.  While I did not launch the "Stream Deck" software, there is an app that runs automatically in the background that was visible in the "hidden icons" section of my windows screen.  Once I disabled that, BAM!  Companion now talks to Stream Deck.  Little bugger....

**Comment by setman2** [comment]
Closed this since I found my problem....

**Comment by haakonnessjoen** [comment]
Could you tell us what program it was in case anyone else experiences the same?

**Comment by setman2** [comment]
Here's the deal.
If you turn on the PC with the StreamDeck plugged in, it launches a
background app.  See it here in my hidden Icons tray:
[image: image.png]

And here it is in my background apps:
[image: image.png]

I never actually started the Stream Deck software by clicking on the
program, so it is an automatic start as long as the hardware is plugged
in.  This drove me nuts since I did not realize that if you don't
explicitly start it, the software is still running (maybe this is a change
in the newest version?) and must be manually disabled.

Hope this helps!
Al

**Comment by setman2** [comment]
I've now disabled it in the startup menu as well.  That should fix the
issue.
