### ISSUE TITLE
don't find the surface[BUG]

### ISSUE THREAD

**Issue by Synech** [bitfocus/companion#1081]
**Describe the bug**
I connected the stream deck to my laptop, and companion doesn't recognize it.

**Desktop (please complete the following information):**
 - Windows 10
 - Browser : chrome
 - Companion Version 1.4.0

**Comment by MeestorX** [comment]
I assume you have an XL? Use version 2.0. Same download page.

**Comment by Synech** [comment]
Thanks for your answer.
The stream Desck is the 15 buttons, not the xl, 
but I gonna download the version 2.0
