### ISSUE TITLE
[BUG] StreamDeck Doesn't connect, gives error messages when companion starting

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#1082]
**Describe the bug**
Whenever I re-start companion (building from source), I get this error in the log:
```
USB(undefined): Found device, but no access. Please quit any other applications using the device, and try again.
```

I also get this error in terminal when I disconnect the SD's USB cable:
```
Error: could not read from HID device
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at process.target.send (internal/child_process.js:578:16)
    at eventhandler.emit (/Users/andyb/Dropbox/Documents/companion/companion/lib/usb/handler.js:45:10)
    at process.<anonymous> (/Users/andyb/Dropbox/Documents/companion/companion/lib/usb/elgato-base.js:34:10)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:391:26)
```
**To Reproduce**
Have SD connected by USB.
Start companion. SD is not recognized, and you'll receive the above error in the log. Re-scanning does not fix the issue.
Disconnecting the USB will produce the 2nd error in terminal.

**Expected behavior**
No errors, SD recognized automatically.

**Screenshots**
Copy/Pasted the errors and logs

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Safari
 - Companion Version 2.0

**Additional context**
If you press a SD button before/during Companion startup, low and behold, no errors!
(Suggested by Håkon Nessjøen)

**Comment by MeestorX** [comment]
I had no other applications running, e.g. Elgato StreamDeck app, or anything that would conflict AFAIK.

**Comment by josephdadams** [comment]
@MeestorX are you still getting this error?

**Comment by MeestorX** [comment]
> are you still getting this error?
Last time I checked, yes. Anything been done recently to fix this? I can update and check again if this has been worked on recently.

**Comment by MeestorX** [comment]
You are not getting this bug yourself? I had the impression is was a common and "known" bug that wasn't easy to resolve.

**Comment by josephdadams** [comment]
Meaning when I run it from source, like `yarn dev`? No, I don't recall seeing it.

**Comment by MeestorX** [comment]
Ok, @Håkon Nessjøen seemed to indicate it was a known issue. I'll test again.

**Comment by MeestorX** [comment]
Not seeing the error today in MacOS, however, the SD isn't being detected at all on the Windows build.
I'll check a little more, and if I don't see this error again, I can close this.

I'll open a new ticket for the Windows issue.

**Comment by JohanNiklasson** [comment]
I had the same problem and here is how I could solve it.

I downloaded the Stream Deck application Uninstaller from Elgato, uninstalled that app and then had no more issues.

I have yet to reinstall it to see if the conflict appears again.

Best Regards
Johan Niklasson
