### ISSUE TITLE
[BUG] Duplicate buttons on stream deck XL using the "Companion Button" addon

### ISSUE THREAD

**Issue by ZeAntwan** [bitfocus/companion#1083]
**Describe the bug**
(Sorry if this is not the right repo, I couldn't find the correct one)
When using the Stream Deck XL and the "Companion button" addon on the stream deck software, button assignement on the stream deck does not follow the grid and duplicates buttons.

**To Reproduce**
In Stream Deck software
1. Install "Companion Button addon"
2. Fill an entire page/screen with "Companion button"
3. Open Companion
In Companion
4. If not already configured, fill a page with buttons and settings
5. See error

**Expected behavior**
The Companion grid should match on the stream deck

(I suppose this is because of the XL size, and button count)

**Screenshots**
Stream Deck
![image](https://user-images.githubusercontent.com/11023019/79957127-6e09b900-8481-11ea-9a12-016a0578a73f.png)

Companion
![image](https://user-images.githubusercontent.com/11023019/79957248-91ccff00-8481-11ea-9239-10a1dbd43310.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Firefox 75.0
 - Companion Version 2.0.0-fabff94-2288

**Additional context**

**Comment by haakonnessjoen** [comment]
Hi,

The stream deck plugin in the stream deck application is not compatible with companion 2.0 yet.

You could either exit the stream deck application to let companion control your stream deck directly. Or you could test out our beta version of the new plugin:

https://s3.bitfocus.io/builds/plugin/io.bitfocus.companion-plugin.streamDeckPlugin
