### ISSUE TITLE
Multiple instances throws 2nd error

### ISSUE THREAD

**Issue by DaveShep** [bitfocus/companion#109]
Trying to start a second instance of Companion under Win64, a warning error occurs, but then another exception is thrown immediately after:

Error
A JavaScript error occured in the main process
Uncaught Exception:
Error: ENOENT, BUILD not found in
C:\Users\users\AppData\Local\Programs\companion\resources\app.asar
at notFoundError (ELECTRON_ASAR.js:114:19)
at Object.fs.readFileSync (ELECTRON_ASAR.js:516:9)
at App.createWindow

1. Start companion
2. Start companion
3. Click OK to clear first warning

**Expected behavior**
Not this

**Desktop (please complete the following information):**
 Win10 64
 v1.1.0-patch1

**Comment by haakonnessjoen** [comment]
Fixed and tested in 027d662
