### ISSUE TITLE
OBS Source Show/Hide

### ISSUE THREAD

**Issue by zacaustin** [bitfocus/companion#1099]
Would it be possible to add the ability to show and hide individual sources in OBS scenes?

**Comment by josephdadams** [comment]
@zacaustin what version of Companion are you using? Isn’t this already a feature?

**Comment by zacaustin** [comment]
I'm using the latest stable version off their site. That is 1.4.0 and I don't see that option.
________________________________

**Comment by haakonnessjoen** [comment]
Download Companion 2.0 Beta. It is right below the 1.4.0 download button.

**Comment by zacaustin** [comment]
Okay, I'm not confident using a beta version of any software in a production environment, so when could the next release of Companion then be expected?

**Comment by McHauge** [comment]
@zacaustin hi, at the moment, V2.0 is way more stable than V1.4, and has been very close to release, but is mainly being held back by the fact that the app for streamdecks software isn't ready yet. the only way to update modules individually is to recompile companion with the module in a dev environment either by yourself or if you get someone to do it for you.

**Comment by zacaustin** [comment]
Thanks @McHauge! I've just got it downloading at the moment, I'll give it a go and run a few test streams with it. I very much appreciate everyone's help here!
