### ISSUE TITLE
Projector control request

### ISSUE THREAD

**Issue by Deanbau** [bitfocus/companion#11]
Control for Barco, Christie and Panasonic Projectors for the following functions

- Lamp on
- Lamp off (with a confirmation? maybe you need to hold this one down for 3 seconds)
- Shutter in
- Shutter out

Feedback:

- Projector status (lamp on/hours?)
- Shutter status

**Comment by willosof** [comment]
Planned! Feedback not yet though. But it's coming :)

**Comment by willosof** [comment]
One vendor per ticket, and we already have this in README.md :)
