### ISSUE TITLE
Function to revert RGB conversion

### ISSUE THREAD

**Issue by BB21B** [bitfocus/companion#1104]
**PLEASE USE THE FOLLOWING PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE OR SOFTWARE PROGRAM**: https://github.com/bitfocus/companion-module-requests/issues/new

**Describe the feature**
In /lib/bank.js the rgb(r,g,b) function converts R G B to 3 bytes all together. I was recently looking for a function to convert back but noticed there wasn't one.   
I'm not sure about pull requests yet so something similar to what I've listed below.

`
function rgbRev(dec) {	
return (
r: (dec & 0xff0000) >> 16,
g: (dec & 0x00ff00) >> 8,
b: (dec & 0x0000ff)
);
}
`

**Is this platform dependent (windows, mac, ..)?**
No.

**If documentation is required to implement, do you know where to find it?**

**Usecases**
When reading colour picker data from an action.

Let me know your thoughts.

**Comment by krocheck** [comment]
@BB21B you'll want to fork this companion repo.  Once that's setup create a branch and commit your change in there like normal.  Then in The GitHub website when browsing that branch you should see a yellow popup giving you option to submit a PR for the branch.  If not you can manually setup the PR with the "New Pull Request" link then on that page enabling "compare across forks".
