### ISSUE TITLE
Text change and Image Change

### ISSUE THREAD

**Issue by G-Hansen** [bitfocus/companion#1107]
Have the text of a button and/or have the image of a button change as an action for a button press.
Thanks

**Comment by cramaboule** [comment]
Yes, that would be nice, especially on a latch/toggle button

**Comment by josephdadams** [comment]
For right now, you can at least change background or foreground color using the internal "Button Background Color" and "Button Text Color" actions.

**Comment by RobbieBott** [comment]
+1 

Definitely would open up possibilities!!!

**Comment by istnv** [comment]
This didn't show up when I submitted #1205

**Comment by Julusian** [comment]
This is solved in #1205
