### ISSUE TITLE
Streamdeck imports Companion profile buttons in wrong locations

### ISSUE THREAD

**Issue by godzich** [bitfocus/companion#1108]
Hi,

I have to run the Companion 2.0 version since the stable version 1.4 does not recognize my new Stream Deck keypad (with the serial number AL10J2C00967). This seems to be - by itself - a recognized problem in  Companion 1.4.

Companion 2.0 together with the 15-key Stream Deck (SW: 4.7.0.12981, FW: 1.02.005) works erroneously when importin buttons. When using the Companion profile, the buttons line up in the wrong locations. See the attached picture. The left side shows the correct button layout in Companion 2.0, the right side shows how they import into the Stream Deck application when using the Companion profile.

![error](https://user-images.githubusercontent.com/65565684/82252749-3f83de80-9958-11ea-8b92-8367374194bf.jpg)

The Companion's  Streamdeck emulation button layout has extra buttons compared to the physical device. These seem to mix up the import. As it is, Companion 2.0 is useless together with Stream Deck, and Stream Deck is useless with Companion 1.4.

Sorry for the somewhat fuzzy description, hope you get the point.

Please fix this asap, it prevents the use of this the hardware as it was intended.

Cheers,

Christian

**Comment by josephdadams** [comment]
@godzich If you’re using Companion 2.0 (which is required for the later revisions of the 15 key models as these are not supported in 1.4), alongside the native Elgato app, then you must use the updated plugin. You can find it here: https://s3.bitfocus.io/builds/plugin/io.bitfocus.companion-plugin.streamDeckPlugin

**Comment by godzich** [comment]
Joseph, I thank you very much for your knowledge and kind help. This did the trick. Highly appreciated!!!

Christian
