### ISSUE TITLE
Streamdeck Plug-in - Multi Action Mode

### ISSUE THREAD

**Issue by CucumberKid** [bitfocus/companion#1109]
When creating a Multi Action button in StreamDeck, the Companion plug-in is missing from the available buttons to include in the multi-action.

The companion button appears under available buttons in the "Custom" section of Streamdeck when the profile 1.01 17/01/2019 is installed but doesn't appear when a Streamdeck multi-action button is being created.

**To Reproduce**
1. Place a Multi-Action button in StreamDeck
2. Companion no longer appears as a usable button

**Expected behavior**
Would expect to see the option to use a companion button as part of a StreamDeck multiaction.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.2
 - Browser Chrome 81x
 - Companion Version 1.4

**Additional context**
This would be useful to use Streamdeck to control both hardware and software. For example, the stream deck multi-action takes the following actions.
1. Use companion to switch ATEM switcher cameras and apply keying
2. Use eCamm Live to switch scenes and apply overlays, audio settings and camera adjustments
<img width="842" alt="Screenshot 2020-05-19 at 09 20 22" src="https://user-images.githubusercontent.com/65592561/82302828-05472b00-99b2-11ea-9cac-7d8e9b2fd2a4.png">
<img width="852" alt="Screenshot 2020-05-19 at 09 21 25" src="https://user-images.githubusercontent.com/65592561/82302901-2445bd00-99b2-11ea-81b5-1d4a38d63f67.png">

**Comment by josephdadams** [comment]
This is a feature request, so I'm re classifying it.

**Comment by CucumberKid** [comment]
Thanks Joseph!

**Comment by haakonnessjoen** [comment]
Hi,

Could you try with this one? And report back any success/problems?

[io.bitfocus.companion-plugin.streamDeckPlugin.zip](https://github.com/bitfocus/companion/files/4671824/io.bitfocus.companion-plugin.streamDeckPlugin.zip)

**Comment by CucumberKid** [comment]
Hi,

Thanks for the update. Run a few tests and feedback as follows:-

Plug-in installed ok
Companion appears within custom section of Streamdeck
Companion now appears within custom section of Streamdeck for Multi-Action (which it didn’t before)
Options for selecting button x.1-32 appears within multi-action configuration within stream deck (which it didn’t before)
Error message within Stream Deck configuration “You need to install companion 2.0 or newer to use this plug in”
Buttons not switching on my basic ATEM switcher test
I tried to install companion 2.0 but received the error message “Companion 2.app cannot be opened because the developer cannot be verified”

Thanks very much and hope this is helpful. Kind regards,

A

**Comment by haakonnessjoen** [comment]
Please try to right click the Companion.app file, and choose Open. It should let you accept the unverified developer warning

**Comment by CucumberKid** [comment]
Yes I’ve run a full end-to-end test of the multi-action plug-in feature for StreamDeck using Companion version 2 and can confirm that Companion runs in multi-action as I would expect.

The button operates with other actions within the Multi-Action in the right sequence and performs the programmed action without any errors.

Really useful feature – thanks very much!
