### ISSUE TITLE
Request: Hotkey over network

### ISSUE THREAD

**Issue by AlgemeneBuurman** [bitfocus/companion#111]
**Describe the feature**
Listener wich virtually press hotkey/keycombo on a host computer.

**Is this platform dependent (windows, mac, ..)?**
Windows

**If documentation is required to implement, do you know where to find it?**
https://autohotkey.com/
https://autohotkey.com/board/topic/54408-remoteahk-execute-ahk-scripts-on-remote-computers-tcpip/

**Usecases**
Send hotkeys/keycombo's to a listner on a computer over ip. The listner "presses" the hotkey. I'm known with autohotkey, so from there i can "program" my own actions on the computer. Like starting Kronos 2017 timers, or open specific powerpoint presentations and integrate other programs.

**Comment by willosof** [comment]
@haakonnessjoen could we use this instead on companion-listener ? 
https://www.npmjs.com/package/node-key-sender

**Comment by PerRoine** [comment]
I'm taking the liberty of closing this as we now support Octopus listener and this is both windows and mac and do support custom keypresses
