### ISSUE TITLE
Behringer XR/MR incremental fader increase/decrease

### ISSUE THREAD

**Issue by perrydegennaro** [bitfocus/companion#1110]
Currently, I can only set up a button to snap a fader to a certain level. I'd like to be able to set a button up to increase or decrease the fader level by a chosen db level. 

Companion also only currently controls the level of a channel in the main mix. We really need to be able to specify which channel and in which bus. Very important for bands using monitor mixes.

**Comment by istnv** [comment]
Companion has a 'Set ch send' action, which will change the channel level on the specified bus.
The mixer protocol only has absolute fader settings, like "set to -6db".
It does not have a relative/incremental change command, like add 1db.

**Comment by perrydegennaro** [comment]
> Companion has a 'Set ch send' action, which will change the channel level on the specified bus.
> The mixer protocol only has absolute fader settings, like "set to -6db".
> It does not have a relative/incremental change command, like add 1db.

Thanks for the quick reply. I can't find 'Set Ch Send' anywhere... Can you point me in the right direction?

**Comment by istnv** [comment]
Which version of Companion are you using?

![Channel Sends](https://user-images.githubusercontent.com/51003420/82521114-a3361500-9ada-11ea-991a-99b1a0baecc0.png)

**Comment by perrydegennaro** [comment]
I'm using 1.4.0... do I need to be using the 2.0 Beta?

**Comment by istnv** [comment]
You will need to use 2.0 to access the new features. There has been quite a few things added.

**Comment by perrydegennaro** [comment]
Thank you so much! This is excellent!
