### ISSUE TITLE
[BUG] Companion version not displaying - in Firefox/Safari

### ISSUE THREAD

**Issue by peppertechie** [bitfocus/companion#1112]
RaspberryPi 4 4GB 
CompanionPi Image - 2.0.0 (62b280c-2271)
updated with the sudo companion-update script last night so should be most recent

In the web gui their is a ? where the version number should be in Firefox and Safari. Downloaded Chrome and it is showing in Chrome. 

`Bitfocus Companion   ?`

Hover over text says "Version Number"

Viewing in MAC OS 10.13.6 in Firefox 76.0.1 and Safari

**Comment by Julusian** [comment]
Im assuming this has been resolved since then, as I have not seen this happen in a long time
