### ISSUE TITLE
linux platform support

### ISSUE THREAD

**Issue by dewiweb** [bitfocus/companion#1113]
It seems you don't publish new  releases for linux platform anymore?
If it's true, could you say why?

**Comment by haakonnessjoen** [comment]
Linux is now present in the latest releases. But when trying to start companion, this error message pops up:

Something went wrong installing the "sharp" module
libvips-cpp.so.42: cannot open shared object file: No such file or directory

**Comment by Julusian** [comment]
I have pushed a fix for this 01facfa63bae46a33c7544afe40d58848dae47e4. Its not the prettiest.
I am warming to the idea of finding/writing/building an alternative to sharp to give image scaling with a simpler dependency tree..
