### ISSUE TITLE
Livestream Studio 6

### ISSUE THREAD

**Issue by FBCMoyock** [bitfocus/companion#1118]
**PLEASE USE THE FOLLOWING PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE OR SOFTWARE PROGRAM**: https://github.com/bitfocus/companion-module-requests/issues/new

**Describe the feature**
A clear and concise description of what the feature does

**Is this platform dependent (windows, mac, ..)?**
Explain.

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along.

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by josephdadams** [comment]
Closing. (1) this is a module request and you’ve requested it in the wrong place. (2) this request has already been made. Follow along here: https://github.com/bitfocus/companion-module-requests/issues/119
