### ISSUE TITLE
Decimator DMON mulitview controls

### ISSUE THREAD

**Issue by aneeta96** [bitfocus/companion#1120]
**PLEASE USE THE FOLLOWING PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE OR SOFTWARE PROGRAM**: https://github.com/bitfocus/companion-module-requests/issues/new

**Describe the feature**
Looking for controls for the Decimator DMON multiviewer, specifically the DMON-6S. I would like to switch between preset looks and individual inputs using stream deck.

**Is this platform dependent (windows, mac, ..)?**
Should work for both windows and mac

**If documentation is required to implement, do you know where to find it?**
Decimator's Control Panel software can be downloaded [here](http://decimator.com/DOWNLOADS/DOWNLOADS.html).

**Usecases**
This will be used to switch between multiview presets and individual inputs using the streamdeck so I do not need to leave the recording/streaming software (Qtake) that I am using. I am going to be incorporating on-set cameras into one of the channels of my Qtake stream. I will need to occasionally highlight single cameras for producers and clients to view details or make-up and wardrobe looks.

**Comment by josephdadams** [comment]
Closing. (1) this is a module request and you’ve requested it in the core repository. (2) the request has already been made. You can read up here: https://github.com/bitfocus/companion-module-requests/issues/83
