### ISSUE TITLE
[BUG]Companion won't save streamdeck page settings.  When I close and re-open my second streamdeck always reverts back to default settings.

### ISSUE THREAD

**Issue by Kylesimmons21** [bitfocus/companion#1126]
**To Reproduce**
1. Go to 'Surfaces'
2. Click on 'Settings' next to stream deck
3. Set Page Number to desired number.
4. Close and reopen to find page number has been reset to default of 1

 - OS: Windows 10 64bit
 - Browser Chrome
 - Companion Version 2.0

**Comment by Kylesimmons21** [comment]
When I close and re-open my second stream deck always reverts back to default settings.

**Comment by dnmeid** [comment]
Is this problem still there? What type of streamdecks do you use and how many? Are the streamdecks on the latest firmware?

**Comment by Julusian** [comment]
closing due to no response from the author
