### ISSUE TITLE
Full size button in "user mode"

### ISSUE THREAD

**Issue by Brennan-Dan** [bitfocus/companion#1133]
**Describe the feature**
To disable the yellow header icons and make the button icons full size.
I’ve read from previous requests of this feature that it would be too difficult to programme without them (which is absolutely true) but my suggestion would be to have a “developer” toggle “on/off” tick box that disables the button id overlay ready for use once programming is completed.

**Is this platform dependent (windows, mac, ..)?**
no

**If documentation is required to implement, do you know where to find it?**

**Usecases**
The Elgato Stream Deck allows full size buttons and images. With the power of Bitfocus Companion behind the buttons, a Stream Deck can be really powerful and look so classy with customised full size buttons with nice images and clear text. The companion ID makes the size of button characters smaller and harder to read and seems to be a popular request and addition to the operation.

Any user who has finished building the buttons on their Stream Deck can benefit from larger/clearer buttons with more character/image space. Once you’re using the stream Deck, you don’t care what button name it is or if it is “playing” a function or feature as long as it works. If you want to see this, leave the “developer” tick box enabled and continue to use it as it is.

**Comment by josephdadams** [comment]
Nice idea. Please add your thoughts to #981 .
