### ISSUE TITLE
[BUG] Old actions don't clear when setActions() called

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#1135]
**Describe the bug**
If you call setActions(), the old actions stay in the dropdown. e.g. if you change the settings of Module, and call setActions() again, the old actions are still there. Restarting companion resets them.

**To Reproduce**
After an initial setActions(), call it again with a different set of actions or a subset. All the actions are still listed.

**Expected behavior**
Only the new actions should show up. A restart of companion is required to clear the action list properly.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 - Companion Version 2.0

**Additional context**

**Comment by josephdadams** [comment]
Fixed in https://github.com/bitfocus/companion/commit/e7c672647127f4470733f6cfcf54b75fbdaa9bff?branch=e7c672647127f4470733f6cfcf54b75fbdaa9bff&diff=unified
