### ISSUE TITLE
Pi Won't Pull down lastest Update[BUG]

### ISSUE THREAD

**Issue by dszoka** [bitfocus/companion#1137]
**Describe the bug**
I run Sudo companion Update but it doesn't pull down the lastest version.
Version on pi: 2.0.0 (62b280c-2271)
Version on Mac: 2.0.0 (d20a286-2401) 

Copy of terminal attached for view 
[Updating Pi 15th June.pdf](https://github.com/bitfocus/companion/files/4777380/Updating.Pi.15th.June.pdf)
 
there does seem to be some errors

**Comment by Julusian** [comment]
Run `sudo git checkout -f lib/instance_skel.d.ts lib/instance_skel_types.d.ts` before `sudo companion-update`

**Comment by dszoka** [comment]
That seem to worked, I need to change the Directory to run it, but now running that latest version ..

Will I need to do this every time, or just an error with my setup

**Comment by jarodwsams** [comment]
@dszoka I've just published the new image for CompanionPi that should resolve this issue. Links are in the wiki (https://github.com/bitfocus/companion/wiki/CompanionPi-Documentation). Please let me know if you still experience this issue.
