### ISSUE TITLE
Companion v2.0.0 only for Streamdeck XL?

### ISSUE THREAD

**Issue by chq1976** [bitfocus/companion#1140]
Hi,

when i do my button layout in v2.0.0, there always appears the gui of a Streamdeck XL, altough i have connected a Streamdeck. Is this a bug, or is v2.0.0 only for the Streamdeck XL?

Greetz Chris

**Comment by haakonnessjoen** [comment]
You can have multiple stream decks connected and might want to show the same layout on some of them. Therefore the editor gives you the option to design the buttons for a Stream Deck XL in case you would connect one some day.

If you have a 15 button, you only need to use the "first" 15 buttons in the button grid, you will see different backgrounds behind the buttons as to show you where the buttons for a 6 key, and 15 key stream deck would find it's keys.

It's not a bug, its a designed feature :) You can also use the ful 32 buttons in the "emulator" in companion if you want.
