### ISSUE TITLE
Companion does not save commands on exported buttons

### ISSUE THREAD

**Issue by CDTTechteam** [bitfocus/companion#1145]
I am trying to export a profile, and when I do, it only exports the buttons, not what the button commands are. Is there a setting to change this, or is this just what the exporting does?

**Comment by josephdadams** [comment]
What version of Companion?

**Comment by CDTTechteam** [comment]
Version 1.4.0

**Comment by josephdadams** [comment]
I was thinking this got fixed in 2.0 if you want to try it.

**Comment by DouggleCode** [comment]
I have exported and import on version 1.4 but here is what I found. I export like normal. But the import is weird. I import ALL settings and then go back and import the pages from the same file. 
Problem I'm dealing with right now is that import of the page works but will not save. If I close Companion and re-open, I have to import the Pages again. I might have to try 2.0

**Comment by Julusian** [comment]
This is no longer an issue
