### ISSUE TITLE
Add instance dropdown does not scroll with window, Win 10 Chrome browser 

### ISSUE THREAD

**Issue by PerRoine** [bitfocus/companion#115]
**Describe the bug**
The "Add instance " Dropdown does not scroll with the window you have to zoom out to see alle the alternatives if you are in a stdandard zoom on 1368x768 screen (small laptop) 
**To Reproduce**
1. open admin and try to add an instance 
2. zoom inn so that the dropdown list fills more than your screen area and try to scroll up and down, the page scrolls but the list is stuck
**Expected behavior**

I expect the list to scroll with the end of the page so that all alternatives is available in all zoom levels / Reselutions

**Desktop (please complete the following information):**
 - OS: [win 10]
 - Browser [Chrome]
 - Version [67.0.3396.87]

**Comment by cxselph** [comment]
This is also happening in OS X Safari 11.1, Chrome 67.0.3396.87, and Firefox 60.0.2 with current version this morning. I have to zoom out in my browser to see all instances.

**Comment by willosof** [comment]
Closed in 004fa45
