### ISSUE TITLE
Dynamic variables for (the streamdeck) page names

### ISSUE THREAD

**Issue by leovangaal** [bitfocus/companion#1150]
**Describe the feature**
I want to create a regular button with key down action: Set surface to page.
The text on the button (on my streamdeck) should display the page name as dynamic content (with the page name I entered as page name on the button layout tab. There should be a string for this?? $(Current surface:pageblabla-1) or something like that?
All the possible dynamic variables from instances are available in the config, but I'm looking for the dynamic variables for the streamdeck itself...

**Is this platform dependent (windows, mac, ..)?**
No,

**If documentation is required to implement, do you know where to find it?**
Not applicable. I think the programmers and the long term users allready know how to fix it.

**Usecases**
When I want to make a homepage with buttons as shortcuts to other pages, I would like the buttons to show the (dynamic) text of the page. 
So if I rename the page on the button layout tab, the text in all the buttons on the homepage also change.

**Comment by Julusian** [comment]
`$(internal:page_number_xx_name)` variables have existed for a few releases now
