### ISSUE TITLE
Help with controlling BirdDog Eyes P100 PTZ camera

### ISSUE THREAD

**Issue by pjbisset** [bitfocus/companion#1154]
I am new to sending POST requests via the generic http module and would appreciate some help with controlling my new P100. Their [REST API](https://www.bird-dog.tv/extra/BirdDog_RESTful_API_1.0.pdf) supports retrieving saved presets. I can do it from curl, thanks to google:

curl -H "application/json" -d '{"Preset":"Preset-1"}' http://192.168.1.122:8080/recall

It supports 9 presets, numbered 1 - 9.

Can someone help me with how to put this into Companion - I have got the base URL as http://192.168.1.122:8080/recall and tried Preset=Preset-1 for the button POST Option value. I tried putting the recall method in the POST option instead. I don't understand how to make it work, so any help appreciated. I am happy to help test use of the BirdDog API if someone wants to guide me through the process. 

Recalling the presets works fine over NDI as well.

Thanks

**Comment by josephdadams** [comment]
Make sure for the JSON data you are typing it as actual JSON:
`{"Preset":"Preset-1"}`

The braces are important.

**Comment by pjbisset** [comment]
Will and test in a few hours and reply. Thanks.

**Comment by pjbisset** [comment]
Must still be missing something. I am using the generic http module and am using this as the base URL:

![image](https://user-images.githubusercontent.com/14287920/86526757-400e0f80-bedb-11ea-8a4c-d0b05b88c7d9.png)

http://192.168.1.122:8080/recall/

For the action on the button I chose the POST one and pasted in the sting as above. Does not do anything.

![image](https://user-images.githubusercontent.com/14287920/86526772-6469ec00-bedb-11ea-8fec-1aeed8a5a299.png)

I have tried one of the other presets that are defined (Preset-2) and it also does not work. The presets work fine if using the remote control, the web console or an NDI monitor.

Are there any other characters that need to be entered anywhere so that the JSON data gets sent properly?

**Comment by pjbisset** [comment]
And just to confirm it works I installed a REST API Client extension in Chrome and it works with that. I am running Chrome on Windows 10 on the machine with Companion installed.

![image](https://user-images.githubusercontent.com/14287920/86527003-f5da5d80-bedd-11ea-9b0e-b2a930975576.png)

Appreciate any help - I have to travel to the site where the camera is installed, so can't test and respond instantly to suggestions.

**Comment by josephdadams** [comment]
This is good troubleshooting. Good job. Two things to try:

1. Remove the trailing slash so the path is not /recall/ but just /recall

2. Leave the base URL blank and put it in the button action instead

**Comment by pjbisset** [comment]
For item 2 can you write exactly what the URL will be for the action button then please. Will be tomorrow night before can let you know how it goes. Thanks for helping.

**Comment by josephdadams** [comment]
http://192.168.1.122:8080/recall

With
`{"Preset":"Preset-1"}` in the JSON field.

**Comment by pjbisset** [comment]
Sorry - maybe I misread your #2 above. That reads like "don't put anything in the base URL field for the instance and put the full URL in the button option field". I didn't get to test that tonight - hopefully tomorrow. I am going to capture the traffic with Wireshark and see what content-type value is sent with the POST call. Will report back once done.

However, I have a workaround.

The BirdDog P100 supports VISCA over IP. The PTZOptics module doesn't work - won't connect. However, the Sony VISCA module works perfectly and it has all sorts of predefined button actions. I just tested the preset recalls and they worked! So perhaps ditch BirdDog's REST API and just use Sony's VISCA module is the way to go. It is a much cleaner way of controlling the camera than writing my own calls, assuming it works.

**Comment by josephdadams** [comment]
Great! We should update the Sony VISCA module documentation to include that it works with Birddog cameras.

**Comment by pjbisset** [comment]
For completeness here is what WireShark saw for the post call from Companion and then from the REST API client I mentioned above. There seems to be something very wrong with sending a JSON payload via Companion, but not my area. Hope this helps someone trackdown what is wrong, but my focus will be on using VISCA not the generic http module going forward. First, here is Companion:

![image](https://user-images.githubusercontent.com/14287920/86871656-0f69e800-c11e-11ea-8313-068ecb7a2f3b.png)

Now the REST client:

![image](https://user-images.githubusercontent.com/14287920/86871694-21e42180-c11e-11ea-86bd-8515999ae8e7.png)

**Comment by danielhmclean** [comment]
I found the solution. (taken from https://www.baeldung.com/curl-rest)

Here is the command for those looking:
curl -d "{\"Preset\":\"Preset-1\"}"  -H "Content-Type: application/json" http://192.168.1.122:8080/recall

The problems:
1) You cant use single quotes, so escape the double quotes in the json.
2) -H feild needs "Content-Type: " before "application/json"
