### ISSUE TITLE
Strange char added in serial number on "surface" tab

### ISSUE THREAD

**Issue by DeeJayMX** [bitfocus/companion#1157]
Strange char on the surface tab

the last streamdeck serial char change on every restart of companion app.

![image](https://user-images.githubusercontent.com/36418772/86936943-f1f94600-c13e-11ea-9b65-496c5017d75c.png)

 - OS: Windows
 - Browser Chrome
 - Companion Version 2.0.0 (cc685d2-2445)

So It create an other problem when I want to assign a page on a specific deck from an action:
![image](https://user-images.githubusercontent.com/36418772/86937193-3d135900-c13f-11ea-9db8-ff5bd6d6f7d9.png)

**Comment by DeeJayMX** [comment]
I updated just now every streamdeck with the Elgato app, so last firmware is installed

**Comment by Julusian** [comment]
Which models is this affecting?
Could you check the serial number on the bottom of one of them (or in the elgato software), so we can make sure that the end is the only thing wrong (and not length or start)

**Comment by DeeJayMX** [comment]
Here is the rogue character:
![image](https://user-images.githubusercontent.com/36418772/86939044-646b2580-c141-11ea-8b17-9950af170dc1.png)

**Comment by DeeJayMX** [comment]
And that char is not written on the back label of the decks

**Comment by Julusian** [comment]
I was not able to reproduce this, but as all the serial numbers are supposed to be 12 characters long, the easy fix was to trim them to be at most that length
