### ISSUE TITLE
Internal Function to Toggle whether Instance is Enabled

### ISSUE THREAD

**Issue by jpooley-hearst** [bitfocus/companion#1160]
Some Instances, such as Vicreo hotkey, will throw errors when not connected. Please add an internal button function to disable and enable a certain device so that these errors are not logged when that device is turned off. 

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
Internal function

**Usecases**
Before the operator logs into their computer, errors will be continuously logged in the Companion log.

**Comment by josephdadams** [comment]
It’s there. Button actions - internal - enable or disable instance.
