### ISSUE TITLE
Sending character strings over a selected COM port

### ISSUE THREAD

**Issue by godzich** [bitfocus/companion#1172]
I have an external big LEDmatrix display that I can control by sending various text strings to it via a COMx port (over USB). It would be very convenient to be able to program the Stream Deck to send a predetermined string to a dedicated COM port on the computer. Naturally, there should be a possibility to select the USART parameters, such as baud rate, start, stop, parity bits.

Pressing various keys on the StreamDeck console could thus show a predetermined text either to the audience or the performers. To be able to do this from the same stream deck that controls the rest of the equipment would be very handy.

I believe this function (sending characters to a selected COM port) would come in handy in numerous other situations. Ideally, it would be great if this function also could receive text data over the COM port so that it could be displayed in the controlling button(s). This is, however, not a must.

I am running on windows, but this function would probably be easy to implement on all supported platforms.

Cheers,

Christian

**Comment by josephdadams** [comment]
@haakonnessjoen could we use node serialport library for this?

**Comment by godzich** [comment]
Hi,

Thanks for commenting! This should not be a big thing since there should be serial port libraries available?! Do I get it right that the status of this is "Enhancement"? Does it mean that someone is considering implementation? Sorry, as a hobby programmer I am not very familiar with this GitHub innards...

Cheers,

Christian

**Comment by josephdadams** [comment]
Our label bot added that label automatically. The biggest concern I have to implement something like this is that it must be fully cross platform compatible and work on all our supported OS’s, and generally things like this need lower level system access which requires compiling. From a strictly Companion standpoint, if someone developed a middle-man app that did all the serial stuff but communicated to Companion over an ethernet protocol, it would probably be better.

**Comment by istnv** [comment]
This may be possible with the `generic-tcp-serial` module.
Use `generic-tcp-udp` to send strings to `generic-tcp-serial` attached to the serial port.

**Comment by godzich** [comment]
Hi John,

Thanx for the tip. The only problem is that I don't have a clue how to achieve this. Being a hobby programmer mostly writing assembly code I don't have enough experience to code this. I believe that this would have some broader interest and therefore ask kindly you for assistance. Or anyone. 

Cheers

Christian

**Comment by josephdadams** [comment]
Step 1: add an instance of the generic serial module and configure it for your serial connection. 

Step 2:’add an instance of the generic tcp module and configure it with the local IP 127.0.0.1 and the default listening port of the serial module. 32100 or something like that.

Step 3: add new button actions to send commands with the generic tcp module that contain the strings you want. They will send locally back to the generic serial module.

Step 4: Profit

**Comment by mark-epstein** [comment]
> Step 1: add an instance of the generic serial module and configure it for your serial connection.
generic serial module?

**Comment by istnv** [comment]
@mark-epstein Look for the module `generic-tcp-serial`. 
It creates a small (4-client) TCP server attached to a USB/Serial port on the same computer.
You can then use the `generic-tcp-udp` module to send data/characters to the serial module. 
The tcp sending module can even be on another computer.

**Comment by mark-epstein** [comment]
Sorry I was confused because I'm running a different (v2.1.2, I think?) version in my production system and did not recall seeing such a module. At home I'm running 2.2.0 and see what you are talking about.

**Comment by Julusian** [comment]
It sounds like this is possible with the `generic-tcp-serial` module
