### ISSUE TITLE
[BUG] Streamdeck serial numbers change after replug/rescan

### ISSUE THREAD

**Issue by elratt0r** [bitfocus/companion#1173]
**Describe the bug**
When the Streamdeck looses USB Connection and gets reconnected, the serial number changes / get's some glibberish added to the end. This prevents made settings from being loaded (page, rotation, ... )

**To Reproduce**
Run Companion
Verify the serial number valid and 12 characters long
Unplug Streamdeck
Replug Streamdeck
Wait for it to light up
Rescan USB
Look again at the serial number
Should have now some glibberish character at the end (13 character)

Maybe need to repeat a few times, depending on memleak also unprintable characters arrive from underlying lib.
Those are visible in the internal database/json storage on disk.

**Solution**
Has been fixed upstream in node-elgato-stream-deck. Please bump elgato-stream-deck version to 3.3.1 in package.json.
(See https://github.com/Lange/node-elgato-stream-deck/commit/d371654df32f7e7bf07e9ce1c0fc14c7876799b4)

**Comment by Julusian** [comment]
This was fixed, but looks to have been accidentally reverted.
https://github.com/bitfocus/companion/commit/bb6c14b036faad56056bcc4b972fe69561299eaf https://github.com/bitfocus/companion/commit/24822ac00cf7254c117c336065fcc73cf2f645b3

@willosof I assume this was accidental and can be safely reapplied in the next module update release?
