### ISSUE TITLE
Request: Categrise modules

### ISSUE THREAD

**Issue by Deanbau** [bitfocus/companion#118]
**Describe the feature**
The list of modules is becoming quiet large, a category picker then a sub picker would be swell.

Suggested categories:

Transport (Playback/Recording?) 
Switcher
Lighting
Audio
Presentation
Display (Projectors etc)
Other

**Comment by dnmeid** [comment]
This has been implemented with 8b2609c4ef9dea233793e8a1651c420ebacd1c4f
