### ISSUE TITLE
Companion Not working with Multi Action[BUG]

### ISSUE THREAD

**Issue by JamesAnderson2** [bitfocus/companion#1180]
After upgrade to 2.1.0 companion button can now be added to Multi Action buttons on stream deck. The companion action is not triggered.

**To Reproduce**
1. Create a Multi Action button
2. Add non-companion button eg, open website
3. Add companion button eg run macro
4. Run Multiaction

**Expected behavior**
Expect companion action to be triggered

**Desktop (please complete the following information):**
 - OS: Cantalina
 - Browser Chrome
 - Companion Version 2.1.0

**Comment by krocheck** [comment]
@haakonnessjoen this appears to be plugin related.  Seems like the user is stacking within Stream Deck a Companion action with a native action.  Have we ever tested that?

**Comment by JamesAnderson2** [comment]
Yep, that's exactly what I'm trying to do.

**Comment by Kixel** [comment]
This is still broken. Using a multi-action with a single companion button works fine, but stops working if anything else is added.
Any ideas?

**Comment by Julusian** [comment]
I can't reproduce any issues here with 2.1 and 2.2.
In the elgato software my action is this:
![image](https://user-images.githubusercontent.com/1327476/149664408-7ffb2f8d-6f9a-4761-a6d3-d046dc2a3046.png)
Both companion buttons get fired as expected.
Could someone provide an example of exactly what actions they have defined in both the elgato software and the corresponding buttons in companion?

**Comment by Julusian** [comment]
@Kixel can you provide the information I need on this?

**Comment by joeyfatstat** [comment]
I really would love to use Multi Action in stream deck ;/

**Comment by Julusian** [comment]
@joeyfatstat I closed this as I had no luck in reproducing the issue.
If you can provide some more details to help reproduce the issue then I can take another lookkkkkkk

**Comment by thechrisguerra** [comment]
I’m experiencing the exact same issue. I’ll be happy to provide whatever details and information may be needed to help fix this. I’ve noticed that when I try to add the companion button within a multi-action, it doesn’t populate the button info from companion like it does when I add the button to the main screen and not with a multi-action.

**Comment by thechrisguerra** [comment]
Here’s a video of the issue

**Comment by thechrisguerra** [comment]
@Julusian Is there anything I can provide to help this one be re-opened?
