### ISSUE TITLE
[Request] Brightness

### ISSUE THREAD

**Issue by MarauderSeeker** [bitfocus/companion#1181]
**PLEASE USE THE FOLLOWING PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE OR SOFTWARE PROGRAM**: https://github.com/bitfocus/companion-module-requests/issues/new

**Describe the feature**
The ability to adjust the streamdecks brightness. This feature is available in the native StreamDeck App.

**Is this platform dependent (windows, mac, ..)?**
StreamDeck

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along.

**Usecases**
Turning down the brightness in a dark room so it doesn't light the room up.

**Comment by MeestorX** [comment]
It’s adjustable in the settings.

**Comment by josephdadams** [comment]
@MarauderSeeker, in the Companion web GUI, go to the Surfaces tab, click Settings next to the surface you want to control, and you can adjust brightness there.
