### ISSUE TITLE
Add multiple Emulators

### ISSUE THREAD

**Issue by stevespaw** [bitfocus/companion#1184]
**Describe the feature**
The ability to add multiple emulators.
To be able to add them as devices. As you may have several streamdecks.

as in http://192.168.x.x:8000/emulator2.html, http://192.168.x.x:8000/emulator3.html  -  etc.

**Usecases**
We would like a single Companion project to be used by several operators in "EmulationMode".
We would make for more universal experience for the users and one place for programming

**Comment by josephdadams** [comment]
#1071 is related

**Comment by Julusian** [comment]
This will be possible in 3.0

**Comment by Julusian** [comment]
This is in the 3.0 betas
