### ISSUE TITLE
StreamDeck ID change when restarting Companion

### ISSUE THREAD

**Issue by Yerb0ti** [bitfocus/companion#1185]
Hi!

I've tried this on bleeding edge and Stable 2.1.0 as well. Both versions see the same issue when on Windows. When I tried this on Stable 2.1.0 on MacOS the issue in **NOT** there.

Whenever I restart Companion software (any StreamDeck with old hardware revision) adds a symbol, number or letter after the ID. This changes every time I restart and thus if I have a lot af buttons in a config that "Set Surface Page" to a specific StreamDeck I need to manually set which StreamDeck on every button once again after restart. 

This does not happen with Streamdecks recently bought with new hardware revision and it does not happen when using MacOS with old revisions or new revisions.

Iv'e tested on 2 different PC:s and the problem consist on both.

Here's a picture of first starting Companion:

<img width="1048" alt="sd1" src="https://user-images.githubusercontent.com/42773793/88820873-2f8f4300-d1c2-11ea-99d2-110484b87ea7.png">

And here's a picture when restarted:

<img width="1051" alt="sd2" src="https://user-images.githubusercontent.com/42773793/88820923-42097c80-d1c2-11ea-9070-1493f56e59a3.png">

**Comment by Yerb0ti** [comment]
👍

**Comment by haakonnessjoen** [comment]
Duplicate of #1173

It is fixed, and we will do a 2.1.1 patch. But until then, you can download the current beta version, where it is fixed.
