### ISSUE TITLE
Variable number of buttons, rows and columns in webbuttons/mobil buttins

### ISSUE THREAD

**Issue by fbosman** [bitfocus/companion#1191]
**Describe the feature**
I think a lot users (well, we do...) are using companion without a streamdeck as a very sophisticated macro processor.
We are running a live stream from our church and control the ptz-camera's, the x18 daw, obs and youtube-connection from Companion and are in need of more then 32 buttons on one screen.

**Is this platform dependent (windows, mac, ..)?**
no

**If documentation is required to implement, do you know where to find it?**

**Usecases**
see the descriptions

**Comment by bmeredyk** [comment]
Assuming that your screen has a high enough resolution, the newer mobile buttons page should be able to fit two banks of 32 buttons at once, esp if it is in portrait orientation.

**Comment by Julusian** [comment]
Some of the newer mobile/web buttons pages will show more than one page at a time, so I think this is resolved
