### ISSUE TITLE
Elgato Control Center

### ISSUE THREAD

**Issue by tango2310** [bitfocus/companion#1192]
**PLEASE USE THE FOLLOWING PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE OR SOFTWARE PROGRAM**: https://github.com/bitfocus/companion-module-requests/issues/new

**Describe the feature**
Elgato Control Center manages the control of Elgato Lights.

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
https://help.elgato.com/hc/en-us/sections/360004115951-Elgato-Control-Center-Software

**Usecases**
Control Center enable full management of Elgato Lights. Turning on or off, changing brightness and color.
Use cases tie closely in with other programs already supported by Companion.
eg a streamer would use Companion to start a stream via say Atem Mini & could also turn their lights on

**Comment by josephdadams** [comment]
Closing:
1. Wrong repo as clearly stated in issue instructions.
2. No documentation provided.
3. Duplicate request. A module for Elgato Key Light has already been made.
