### ISSUE TITLE
[BUG] Flip counting direction on page up/down doesn't affect mobile buttons

### ISSUE THREAD

**Issue by KonkaBass** [bitfocus/companion#1194]
**Describe the bug**
Noticing that "Flip counting direction on page up/down" only applies to Emulator, and not mobile buttons. Which is unfortunate, because I'd argue it's _the most_ important to have that setting work in "Mobile Buttons" due to how pages cascade downwards. Having "Page Down" go Up goes against the visual logic of the "Mobile Buttons" layout.
"Web Buttons" is not applicable as page buttons are disabled, but I would like to note that "Previous" & "Next" buttons above each page function and make logical sense.

**To Reproduce**
Toggle on "Flip counting direction on page up/down"
Go to Emulator, click down, 1 leads to 2, ect. (good)
Go to Mobile Buttons, click down, 1 leads to 99, ect. (bad)

**Expected behavior**
Toggle on "Flip counting direction on page up/down"
Go to Emulator, click down, 1 leads to 2, ect.
Go to Mobile Buttons, click down, 1 leads to 2, ect.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: tested and replicated in Windows: Firefox & Chrome and also Android: Firefox & Chrome
 - Companion Version : tested on v.2.1.0 (latest official build) and v2.1.1-1ab77d5-2522

**Additional context**

**Comment by krocheck** [comment]
@bmeredyk can you look into this?  I see the fix you made in #1129, but I think that should extend to swapping the up/down button numbers below to satisfy this bug report.
![image](https://user-images.githubusercontent.com/749812/92020429-17ad6080-ed26-11ea-893a-16f231b9d5dd.png)

**Comment by bmeredyk** [comment]
I'll try to look into this in the next couple days. I'll need to get my dev environment setup again and then figure out how to get the config settings via the websocket in order to see what the flipped config is currently set to.

**Comment by Julusian** [comment]
looks like this was fixed
