### ISSUE TITLE
X-keys support

### ISSUE THREAD

**Issue by ataylor-orcsd-org** [bitfocus/companion#1196]
Hello,

Would it be possible to use a X-keys device as an input to companion?  I have a few currently in my setup, including the rack mount one.

Thanks,
Alexander

**Comment by haakonnessjoen** [comment]
@JeffreyDavidsz: We have heard from a company that they have a problem that the latest builds of Companion now steal their X-keys. We should have an option where Companion lets the x-keys alone if they use it for other purposes.

**Comment by JeffreyDavidsz** [comment]
Mmm it checks for available and accessable xkeys. I wasn't aware of stealing. It like streamdeck and streamdeck app right? Need to figure out how to do that. Or would you purpose to create a global setting for it?

**Comment by Julusian** [comment]
I think an setting in the surfaces tab would make sense. I have been thinking for a while that one for streamdecks would be a good idea too, for those who prefer to run via the streamdeck app and plugin

**Comment by haakonnessjoen** [comment]
If we add a setting to ignore stream decks, then we could add support for auto-detecting stream decks I think. The reason we don't have auto-detect of anyone plugging in a new stream deck is that we want people to be able to choose between using the stream deck application or not.

**Comment by JeffreyDavidsz** [comment]
@ataylor-orcsd-org xkeys is now supported in a very basic way, more development will come
