### ISSUE TITLE
TSL Module

### ISSUE THREAD

**Issue by Keksstar** [bitfocus/companion#120]
**Describe the feature**
The TSL protocol is used in many UMD (under monitor displays, e.g. TSL, BTS), multiviewers (e.g. Decimator, Kaleido, etc.) and Monitors (e.g. TVlogic, Marshall, Ikan, etc.)

**Is this platform dependent (windows, mac, ..)?**
Independant. Just needs an Com-Port for serial connection. (how can this be done? I´m no programmer... I have no idea)

**If documentation is required to implement, do you know where to find it?**
https://tslproducts.com/media/1959/tsl-umd-protocol.pdf

**Usecases**
Would be great to have the ability to change UMDs corresponding to the switching of an Video Matrix. (like BMD Videohub, etc)

**Comment by cxselph** [comment]
This could do it. It has a clear api for control. I use it to control an old kramer switcher. https://www.globalcache.com/products/itach/ip2sl-pspecs/

**Comment by Keksstar** [comment]
Yes, I´m aware of Virtual Com Ports and using them all the time... But this would then need to be adressed as TCP/UDP in Companion. (that´s what I meant.... I don´t know if Companion can handle Com-Ports or "just" network connections)
I mostly use the Tibbo DS1102. Has some nice features :)
http://tibbo.com/store/controllers/ds1102.html - And for sure I also would use it in this case :)

**Comment by willosof** [comment]
What should this module do? I know very well what TSL-UMD is, but I don't understand what you want to do. Do you want companion to send out UMD-messages, or receive them?

**Comment by Keksstar** [comment]
Send out TSL in the first step would be great. Both versions, TSL 3.1 and 5 would be awesome (but I´m personally more in the 3.1 world for now)
So with this you could build something like: Switch your Videohub and also send out TSL to your display, so the source name is displayed on the monitor.
TSL receive could be mapped to buttons and act as an TSL display as well.... but for this I´m actually have no example.

**Comment by Keksstar** [comment]
Hi Richard, I´m highly interested in your simulator. Any chance to get the hands on this?

**Comment by Keksstar** [comment]
Thanks for that! I will check it out :)

**Comment by videojedi** [comment]
sorry, try this version... might work better! :)
https://aws-website-videowalrus-h569u.s3.amazonaws.com/TSL%20UMD/Builds%20-%20TSL%20UMD.xojo_project.zip

**Comment by JeffreyDavidsz** [comment]
Hi guys, I could make a module for this based on UDP. Problem is I'm not familiar with the commands that needs to be send. Maybe you can provide some example commands here?

**Comment by haakonnessjoen** [comment]
Look at the link from Richard Burford. We should support several of the TSL protocols at a later time, in the same module, so don't call the module tsl4.0 or anything ;)

@willosof did a quick tsl-umd parser at one time, you could use it as inspiration if you want.

https://github.com/willosof/tsl-umd

The same function parsing data could be used to generate a compatible packet, as far as I can remember. Don't remember which tsl-umd protocol version he went for. But you could compare with the one mentioned. Or just search google for tsl umd protocol, you will find a lot of documents for different versions :)

**Comment by Keksstar** [comment]
There‘s exactly only one document for all versions. You have to read it correctly 😉

**Comment by JeffreyDavidsz** [comment]
Ok, so I finally wrote the module. It's not perfect yet, but could someone test this for version 3.1? I've tested version 4.0 against the simulator from @videojedi (tnx that by the way!)
@videojedi the last bytes of the protocol are unclear for me, can you explain what happens here?

XDATA consists of 2 bytes: 
 Xbyte 1 has 6 tally bits for Display L, 
Xbyte 2 has 6 tally bits for display R. 

The 6 bits consist of 2 bits each for the LH tally, text, and RH tally as follows:
Bit 7 0 
Bit 6 Reserved (ignore (RX) or set to 0 (TX)) 
Bit 5: LH MSB 
Bit 4: LH LSB 
Bit 3: Txt MSB 
Bit 2: Txt LSB 
Bit 1: RH MSB 
Bit 0: RH LSB

**Comment by Keksstar** [comment]
Looked into it. Sadly TSL 3.1 isn´t working.

Example for: TSL address: 0, Text: "CAM 1", with Tally off
What you are sending: 803043414d20312020202020202020202000
   What it needs to be: 803043414d20310000000000000000000000
I generated the second one in "Universe" - it´s working. Checked it with an Decimator DMON-16S.
