### ISSUE TITLE
[BUG] Ports closed or already in use or unable to connect

### ISSUE THREAD

**Issue by dlamon1** [bitfocus/companion#1201]
*Running the latest version of Companion

Upon startup I get these two JavaScript errors:

<img width="421" alt="Screen Shot 2020-08-18 at 9 03 32 AM" src="https://user-images.githubusercontent.com/43188519/90538365-13891c80-e144-11ea-93ba-b3ac7ea94ecb.png">
<img width="422" alt="Screen Shot 2020-08-18 at 9 03 52 AM" src="https://user-images.githubusercontent.com/43188519/90538371-1552e000-e144-11ea-839c-fc007cecead9.png">

I am unable to send TCP/UDP/OSC commands to Companion.

**Comment by josephdadams** [comment]
Something else on your system is using those ports.
