### ISSUE TITLE
Livestream Studio 6

### ISSUE THREAD

**Issue by AVKILLS** [bitfocus/companion#1211]
Livestream Studio 6

The ability to:

Take
Select input on preview
Push/Pull Key 1-3
Mute/UnMute inputs - would be nice, not essential.

We are utilizing a multitude of Blackmagic switching along with Millumin playback and X32 audio control to manage virtual programs, all pushed out via Livestream Studio. Currently using 7 Studios, all operators are using Companion for control on the other devices and would truly benefit from some basic control of Livestream Studio.

Thanks
Mike Skilton
Alchemedia
avkills@gmail.com
+1 610-496-3374

**Comment by AVKILLS** [comment]
Livestream Studio wouldn't be an enhancement, I believe it would be a new device as there is no current support

**Comment by josephdadams** [comment]
A few things:
* the auto label bot picked enhancement.
* this is the wrong repo for module requests. The issue request points this out.
* no documentation or protocol information was included.
* there is already a module request for this software.

Closing.
