### ISSUE TITLE
Virtual Device for Feedback

### ISSUE THREAD

**Issue by Jonhug82** [bitfocus/companion#1212]
Would it be possible to great a Virtual device that could be used to generate feedback for buttons ? 

Use case would be when pushing a button it could run a variety of actions on real devices and then set a value for a virtual device that could then be used to provide feedback on a button. This way if you have the button on multiple pages all buttons could show the same feedback without having to programme a colour change for each page the button is on. 

It would also mean if a button is moved between pages no changes would be required to still get feedback.

Many Thanks

Jonathan

**Comment by josephdadams** [comment]
It could be nice to have an internal action to set a variable value to `x` and then have a feedback status of `when variable === 'x'`

**Comment by Jonhug82** [comment]
Hi @josephdadams yes that would be perfect. If the variable was built directly into Companion could this also be used as a dynamic variable for the button text eg $(variable_x) ?

**Comment by josephdadams** [comment]
Yes

**Comment by dnmeid** [comment]
@Jonhug82 if I got you right I think we are talking about different things. "Feedback" in terms of companion is provided by a module. The module gets some status information from a device and provides a way to switch the look of a button accordingly. You can use this feedback on as many buttons as you like and don't have to program a color change, you just have to add the feedback.
An intermediate virtual module wouldn't make any sense in this aspect.

**Comment by Julusian** [comment]
Solved with custom variables?
