### ISSUE TITLE
[BUG] Bind EADDRINUSE 0.0.0.051235 at object._errnoException 

### ISSUE THREAD

**Issue by Darthkevino** [bitfocus/companion#1215]
**Make sure you're on the latest bleeding edge build** (remove this section from the bug report)
*Before you report a bug, make sure you're not reporting something that have been fixed in the master branch by downloading a "latest" build from https://builds.bitfocus.io/companion/*

**This form is only for bugs related to the Companion software itself. If you are reporting a bug that you feel is limited to a specific Companion module, please make the bug report directly in that module's repository.** Most Repositories can be located within the Bitfocus Github account with the following naming convention: companion-module-*manufacturer*-*product*

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Companion Version [e.g. 2.0]

**Additional context**

**Comment by Darthkevino** [comment]
![Companion Error Message](https://user-images.githubusercontent.com/70769092/92262806-aa2a3d00-eea9-11ea-98ca-84a525362cf8.jpg)

**Comment by Darthkevino** [comment]
How can I know what else is using that port as a server and close it?

**Comment by josephdadams** [comment]
Close out all other software and try to open them one at a time.

**Comment by istnv** [comment]
Trying to start companion twice will do that on the second run.
Companion uses 51235 to listen for UDP commands.

**Comment by aral** [comment]
@istnv I just ran into this on Linux when trying to run companion after quiting. Is there a separate issue to track this bug that you know of? Not sure why this was closed.
