### ISSUE TITLE
[BUG] OSC Core Module does not ignore arguments when sent by the OSC sender (TouchOSC e.g.)

### ISSUE THREAD

**Issue by millsemillse** [bitfocus/companion#1220]
If i try to use TouchOSC on IOS - Companion does not execute commands. 
Please update Core module to ignore not needed arguments that are beeing sent automatically by any software

Joseph knows bout the issue

Millse

**Comment by josephdadams** [comment]
I would suggest this line:
https://github.com/bitfocus/companion/blob/2de15492ab69d849e1da35b631cb80b6d4d230e3/lib/osc.js#L43

Be modified to include `|| (message.args[0].type !== 'i')`.

**Comment by josephdadams** [comment]
@millsemillse I forgot this was already requested, see #1076
