### ISSUE TITLE
Simplify - Button background color

### ISSUE THREAD

**Issue by Wajasful** [bitfocus/companion#1223]
It would be great if we can select multiple bank with the internal function : button background color.

It's really hard to use when you whant to give a feedback of what you're doing with this features. 

![Capture](https://user-images.githubusercontent.com/70446704/93263712-705d0e80-f7a6-11ea-82ee-1ff997653f41.PNG)

**Comment by josephdadams** [comment]
This is essentially what #792 is asking for, yes?

**Comment by Wajasful** [comment]
Yeah, the idea is the same. It could be great for switcher or different sources.
Sorry I didn't check before posting this idea

**Comment by josephdadams** [comment]
No problem. I just like to do my best to keep us from having duplicates.
