### ISSUE TITLE
Question about Centralized Companion Server

### ISSUE THREAD

**Issue by ThatGuySittin** [bitfocus/companion#1225]
This may already be a thing, but I am having a hard time finding it in terms I can understand maybe. But, is there a way to run multiple companion sessions on multiple computers off of the same instance/connection pool, and the same buttons? I don't know the device limit on one computer, and so I am trying to figure out how to have a centralized Companion Repository almost, and everyone must add buttoms or create instances on that server. But people can still use Companion in other parts of the building or across campus through the network. Is this a thing? Sorry if it is!

**Comment by willosof** [comment]
You might want to use Bitfocus Buttons instead of companion. We're in closed beta right now, but we'll enter public beta within 1-2 months :) please email me at william@bitfocus.io, and I'll let you know when public beta is available!
