### ISSUE TITLE
TSL and Smarthub text feedback from UDP or HTTP

### ISSUE THREAD

**Issue by booguiseb** [bitfocus/companion#1227]
I would like to get a text from http for exemple and send it to the smarthub source name and/or to the TSL instances, or from smarthub to TSL.

Not platform dependant

documentations are already there

usecase:

Sometime i need to change the UMD very quickly and i would love them to change with the router 's name from outside of companion , like UDP or HTTP.
if TSL is linked to smarthub's , may be we can get the tally follow the routing of one destination.

thank a lot

**Comment by josephdadams** [comment]
Can you explain what it is you would like to be able to do within Companion to accomplish your goal? If the goal is to make a videohub route change and also send a TSL UMD message when you press a button, you can do this in Companion already. Both modules are there.

**Comment by josephdadams** [comment]
@booguiseb any thoughts to my question?
