### ISSUE TITLE
I use Stream Deck with Bitfocus Companion to control my BlackMagic Design ATEM Mini Pro. On a 2nd computer (same network) I want to advance PowerPoint graphics. Can it be done with StreamDeck with Companion running? Thanks. 

### ISSUE THREAD

**Issue by franklyray** [bitfocus/companion#1229]
**PLEASE USE THE FOLLOWING PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE OR SOFTWARE PROGRAM**: https://github.com/bitfocus/companion-module-requests/issues/new

**Describe the feature**
A clear and concise description of what the feature does

**Is this platform dependent (windows, mac, ..)?**
Explain.

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along.

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by josephdadams** [comment]
Yes. There are several ways to do this. Vicreo Listener can send keystrokes to the 2nd computer. Another way is to use Irisdown Remote Show Control. Both methods will involve installing software on the 2nd machine that receives commands from Companion on the first.
