### ISSUE TITLE
[BUG] Developing on windows 10

### ISSUE THREAD

**Issue by brianteeman** [bitfocus/companion#1230]
I am attempting to complete the steps in the documentation https://github.com/bitfocus/companion/wiki/Developing-on-Windows-10

The installation process ends with 
```
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The engine "node" is incompatible with this module. Expected version "^8.16.0 || ^10.6.0 || >=11.0.0". Got "8.15.1"
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ yarn build
yarn run v1.22.5
$ trash dist && yarn build:main
$ tsc -p tsconfig.build.json
Done in 24.39s.
Done in 82.08s.
```

Then when `yarn headless` is run it crashes as follows

```
yarn run v1.22.5
$ nodemon headless.js
[nodemon] 2.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node headless.js`
Starting
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\htdocs\companion\BUILD'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (C:\htdocs\companion\headless.js:17:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by JeffreyDavidsz** [comment]
Looks like ./tools/update.sh did not run completely? In that script is a call for the buildwritefile script

**Comment by brianteeman** [comment]
I am looking and I can see the buildwritefile  script but I dont see where it is ever called

re-running update.sh shows no errors or failures.

**Comment by JeffreyDavidsz** [comment]
Strange I'm sure it runs in one of the steps, also the output of `yarn headless` command is different. You can run the script by hand `./tools/build_writefile.sh`. But most likely something else is missing. What happens when you manualy run that script?

**Comment by brianteeman** [comment]
Running that script manually returns with no feedback
```
brian@DESKTOP-5A2A1UB MINGW64 /c/htdocs/companion (master)
$ ./tools/build_writefile.sh
brian@DESKTOP-5A2A1UB MINGW64 /c/htdocs/companion (master)
```
but it must have done something as yarn headless now works

**Comment by JeffreyDavidsz** [comment]
Check your default settings for .sh files switch it to git bash. You might be missing scripts as it loads in an editor (and therefore not running). So the script you are calling will be fired,but a script call in that script not. Glad that it worked for you
