### ISSUE TITLE
Genereic Request

### ISSUE THREAD

**Issue by moedeveloper** [bitfocus/companion#1233]
I Am trying to use the HTTP generic  for Wowza server so I can enable and disbale stream target.  to use the POST request I require authentication so the question is how can i do that? is it possible to do so ? or this is something that should be implemented? 

this is how the documentation for a  post request from wowza looks like 
![image](https://user-images.githubusercontent.com/16238332/94010675-8a9a7c00-fda6-11ea-8935-55b55e8f586f.png)

![image](https://user-images.githubusercontent.com/16238332/94010867-cd5c5400-fda6-11ea-95f8-fa24c5002f4e.png)

Regards,

**Comment by josephdadams** [comment]
The generic HTTP module does not support authentication at this time.

**Comment by JeffreyDavidsz** [comment]
So the question is, create a new module request for wowza
