### ISSUE TITLE
"Add key down/on action" does not work

### ISSUE THREAD

**Issue by videochris** [bitfocus/companion#1235]
For some time now I have had the problem that I can create a new button but no actions can be assigned to it. In the field "Add key down/on action" I can see the commands of the instances that have been set up, but these are not taken over with a left click. I cannot insert commands. I only have the possibility to take over premade buttons via the "Presets", but I cannot add any further commands. This behavior can be observed since build "2555" "Added newtek-ndistudiomonitor".
Deleting the folder "C:\User\%Username%\AppData\Roaming\Companion" and reinstalling it did not help. I could work with an earlier build, but I would like to use the NDI function. 
Is there a solution for this?

**Comment by josephdadams** [comment]
@videochris are you still experiencing this issue?

**Comment by videochris** [comment]
Hello Joseph,
unfortunately no. I have installed version 2623, but I cannot add commands from vMix or NDI.
To add new vMix commands I have to go back to version 2536.
I assume that this problem occurs with the introduction of NDI with 2537.
I have attached a screenshot. With the V2623 via <Presets><NDI><Sources> I added the corresponding command. Then updated back to V2536. Added the vMix command <Send Input to Program>.
Back to V2623 again. But it does not work. The vMix Program Output 4 does not change.
Greetings, Christian


Translated with www.DeepL.com/Translator (free version)

 

 

 

Gesendet: Freitag, 23. Oktober 2020 um 02:21 Uhr
Von: "Joseph Adams" <notifications@github.com>
An: "bitfocus/companion" <companion@noreply.github.com>
Cc: "videochris" <chrboe@web.de>, "Mention" <mention@noreply.github.com>
Betreff: Re: [bitfocus/companion] "Add key down/on action" does not work (#1235)


 

@videochris are you still experiencing this issue?

**Comment by josephdadams** [comment]
Screenshots didn’t come through. Use the github page directly.

**Comment by videochris** [comment]
I have edited my contribution and uploaded the screenshot.
 

Gesendet: Samstag, 24. Oktober 2020 um 15:04 Uhr
Von: "Joseph Adams" <notifications@github.com>
An: "bitfocus/companion" <companion@noreply.github.com>
Cc: "videochris" <chrboe@web.de>, "Mention" <mention@noreply.github.com>
Betreff: Re: [bitfocus/companion] "Add key down/on action" does not work (#1235)


 

Screenshots didn’t come through. Use the github page directly.

**Comment by thenoisyorange** [comment]
I believe I am also experiencing this issue as well.

Basically the only way I can add commands currently is to copy, move or export other existing keys.

**Comment by albertorighetto** [comment]
It also affects Barco Event Master module (on which some parts of NDI Studio Monitor module are based).
It seems that if you keep open the button Add-action menu and meanwhile the actions are updated by the module (to refresh NDI sources or EM preset names), the action will not be added as it has been "overwritten"

**Comment by Julusian** [comment]
I've given this a quick test, and the log is showing `add + Add key down/on action` instead of what was selected. 
This is not an issue with #1402, so unless that gets delayed I dont think it is worth doing anything more on the ui side

**Comment by albertorighetto** [comment]
In last commit I reduced action updates to a minimum (i.e. only if a source change is detected).
This bug will still be there (with "old" admin UI) but only if a NDI source change happens while the user has the add-action dropdown menu open.

**Comment by Julusian** [comment]
I believe this is working as expected in the new ui, which is now the default
