### ISSUE TITLE
Lockout feature on R-Pi 4 Broke my whole Companion build[BUG]

### ISSUE THREAD

**Issue by jjbutler83** [bitfocus/companion#1236]
**Describe the bug**
Enabled lockout/pin feature. Companion/Stream Deck freaks out when loading/booting. Was working initially, now my whole build is just rebooting over and over and looks like it's going to have to be completely blown away and redone. (WHY?!) Luckily after multiple attempts I was able to export my whole config, of which I just spent ALL DAY working on and modifying.

**To Reproduce**
Happens EVERY TIME I boot up my Companion Pi system.

**Expected behavior**
Boot up and work as usual, as always.

**Screenshots**
Have a video of Stream Deck erratic button skip/flash/jumble but this site will not let me upload it.

**Desktop (please complete the following information):**
 - OS: Companion Pi (latest updates)
 - Browser Chrome on control Computer

 control computer (Win 10)
 - Companion Version [e.g. 2.0] 
2.1.1 (238f21c-2605)

**Additional context**
Did a new Companion Pi build on a different SD card and completed my whole setup again. Imported my complete export from the other problematic build and everything came back. Testing through now, but issue seems to be related to the lockout feature. As you are probably aware, the lockout feature is important for those of us in the live event production world to help keep our tech areas secure when we step away from the area. If this could be fixed that would be great. Thanks!

**Comment by Julusian** [comment]
I believe this was a case of the pin value being undefined and companion was expecting it to be defined (even just an empty string).
Lockout looks to be behaving itself to me now, so I am considering this fixed unless someone reports it is still an issue in 2.2
