### ISSUE TITLE
Crash Streamdeck XL

### ISSUE THREAD

**Issue by yguerdat** [bitfocus/companion#1240]
My Stream Deck XL crash after a few minutes and then I need to restart my entire computer to make it stable again for a few minutes before the next crash. 

Here is the error message : 
30. 18:38:06 device(CL24J1A00013): Clear deck failed: Error: Cannot write to HID device
30. 18:38:06 device(CL24J1A00013): Elgato Streamdeck XL device disconnected
30. 18:37:57 device(CL24J1A00013): Elgato Streamdeck XL detected

Can I somehow give you more details to debug it ? 

Just to inform you that I have a 20 meters USB3 cable between my computer and my stream deck device. Not sure if it's can be the reason. I have try with the default software of Stream Deck and I have no issue with USB and it's working pretty fine.

**Comment by josephdadams** [comment]
What OS and version of Companion?

**Comment by yguerdat** [comment]
Windows 10 Pro (installed in french)
Bitfocus Companion 2.1.0 (47823d0-2493)

**Comment by yguerdat** [comment]
I have by the way try to install the 2606 by the way, but it was exactly the same result.

**Comment by yguerdat** [comment]
I made a quick video who represent the issue : https://photos.app.goo.gl/739hTvjKyhHU88iz8

**Comment by Julusian** [comment]
This doesnt feel like a companion issue to me, it looks more like a windows/usb/streamdeck issue.

So you are saying it works fine with the elgato software in the same setup?
How does it behave if you dont use the 20m extension?

I'm not sure where to start on debugging in companion yet, it could be that the hid library is throwing some errors that should be handled properly and not simply treated as 'disconnected'. But its probably not going to be quick to handle those errors

**Comment by jaredsmith** [comment]
I would tend to agree -- this sounds like a USB communications issue to me.  The fact that the StreakDeck is resetting would also suggest that maybe it's not getting enough power over the 20m extension, as there will obviously be a voltage drop over a connection of that length.

**Comment by yguerdat** [comment]
Oh yes @Julusian @jaredsmith you have right ! It was the USB 20 meters who generate the issue. When I connect directly it's working pretty fine. Thanks for your support guys 👍
