### ISSUE TITLE
Streamdeck XL

### ISSUE THREAD

**Issue by mjsanders400** [bitfocus/companion#1241]
Hi All.

Ive got an ATEM switcher and an Streamdeck XL all set up but the stream deck is controlling the emulator not the switcher.

Help!

**Comment by McHauge** [comment]
What is the problem? Like what are you asking 😅

**Comment by mjsanders400** [comment]
I've got an ATEM switcher connected to Connections and that says its OK and connected.
I've got a stream deck XL connected to Connections - and that says its OK. (shows up in the buttons page)
I've assigned buttons to the Streamdeck and if I press one it changes on the emulator page but doesn't switch the ATEM

**Comment by mjsanders400** [comment]
Actually it is controlling the Atem, but the ATEM buttons aren't following

**Comment by McHauge** [comment]
Are you sure you have the right ip and port setup in companion. Showing connected is not the same as it will work, sometimes connected is just that the ip I valid and a device responds to a ping. 

But if you check the config tab all the names of your inputs should load into the variables, another thing check the version of your firmware on the atem is up-to-date, there has been a few updates during 2020

**Comment by McHauge** [comment]
Well that's probably your feedbacks not being set up correctly on the buttons in companion

**Comment by mjsanders400** [comment]
Its changing in the ATEM software as well - I'll check the ATEMs firmware (using the buttons from the presets!)

**Comment by josephdadams** [comment]
It sounds like you don't have the feedbacks set up properly for each ATEM button. Remember you have to change the specific device/input for each feedback type on each button.
