### ISSUE TITLE
Animated .gif support as buttons

### ISSUE THREAD

**Issue by r2tincan** [bitfocus/companion#1243]
**Describe the feature**
Ability to use animated gifs as buttons!

**Is this platform dependent (windows, mac, ..)?**
No.

**If documentation is required to implement, do you know where to find it?**
Not sure.

**Usecases**
This is just a really cool and nice to have feature of the original streamdeck.

**Comment by josephdadams** [comment]
duplicate of #262

**Comment by markmagoo** [comment]
Just curious if APNGs would make a difference here? Since we're already using PNGs, is that too far a reach?
