### ISSUE TITLE
db.temp -> db failed [BUG]

### ISSUE THREAD

**Issue by marclos** [bitfocus/companion#1244]
I installed companion on my new desktop (Dell Precision 2630, Windows 10, Google Chome) and it worked great for two weeks. However, over the weekend, I get an error in the log after lunching the GUI:

07. 09:35:10 CORE(cb): db.tmp->db failed: Error: UNKNOWN: unknown error, rename '\\WellsGM\Fac-staff$\mwl04747\Application Data\companion\db.tmp' -> '\\WellsGM\Fac-staff$\mwl04747\Application Data\companion\db'

All of my instances and buttons have disappeared. Although the Elgato StreamDeck is still found in the devices.

I am guessing the roaming profile is the problem (although why it worked flawlessly for two weeks, I am unsure). I am wonder if I can install the db pointer to a specific location in the set up that is not on a virtual / roaming profile?

**Comment by josephdadams** [comment]
I could be wrong, but I think that's the location available to us when using Electron to package an app like this to run directly on the OS without node installed.

**Comment by Julusian** [comment]
Fixed in 2.2
