### ISSUE TITLE
Pass dynamic variable values through key action options

### ISSUE THREAD

**Issue by krzyzz** [bitfocus/companion#1248]
**Describe the feature**
Apparently dynamic variables' only purpose is to be displayed as text on Streamdeck's buttons. I haven't found a way to view actual values in other fields, notably in the URl post/get actions in the generic HTTP module.
The feature would allow to store dynamic variable values in fields other than the button text.

![image](https://user-images.githubusercontent.com/71986307/95691574-4c171500-0c20-11eb-922a-1d79f35b5967.png)
is interpretted literally as written:
![image](https://user-images.githubusercontent.com/71986307/95691577-5507e680-0c20-11eb-8d6b-912e667a871c.png)

**Is this platform dependent (windows, mac, ..)?**
Independent

**If documentation is required to implement, do you know where to find it?**
Does not apply, I think?

**Usecases**
This would allow to pass variables outside the Companion and, in my usecase, serve as a tally server/proxy/distributor to GPI and networked devices that support tally lights. Maybe even display current mixer input, router input name etc. outside of Companion itself.

**Comment by josephdadams** [comment]
Seems related to #960 although not a true duplicate

**Comment by krocheck** [comment]
This is supported but developers have to implement it on a per-field basis. `this.parseVariables(string, cb);`

**Comment by McHauge** [comment]
> This is supported but developers have to implement it on a per-field basis. `this.parseVariables(string, cb);`

how would this be done, just for future reference if needed? is it something that need to be added to the variable or to the specific field/textbox.

**Comment by JeffreyDavidsz** [comment]
Closing this, as @krocheck said, this is a per module thing. In a module you can choose what you would like to do with the received message

**Comment by 4ndrw** [comment]
it would be awesome to implement this in @josephdadams Midi-Relay module...

I'm writing out a lot of strings of sysex commands for a multitimbral synth. 
It would be great to set some variables and access them for some of the bytes inside a sysex string.

eg. Midi channel for the selected part.
a parameter's identifier number
or desired value for that parameter to be set to

example Sysex "240,00,32,51,01,16,114,00,29,$(internal:custom_SelectedPart),247"
with custom_SelectedPart set to 02

**Comment by josephdadams** [comment]
@4ndrw not something I have time for right now but feel free to submit a pull request that does what you want!

**Comment by HippoSlayer** [comment]
I'm hoping to get custom or dynamic variables in the internal module to pass them to a shell path action, right now I just get the actual text, at least on windows.

**Comment by josephdadams** [comment]
@ChachiElBandido I just implemented this for you in the shell path action, in https://github.com/bitfocus/companion/commit/9e7d5708f15acf6f40ee301c7a4917b23909daf6 so go download the latest.
