### ISSUE TITLE
CompanionPi and Node-RED on same Rpi4B-4G

### ISSUE THREAD

**Issue by DeeJayMX** [bitfocus/companion#1251]
Hi, I'm trying to install Node-RED on a CompanionPi "OS",

Node-RED is working good but Companion not

I can't use the stream deck, it stay with the Elgato logo, even if I press Rescan.

I tryed all the port on the pi.

I tryed to stop node-RED and I launch companion-update.

Do you have any clue ? thanks for all the great works !!!

( I installed Node-RED to make use of the GPO/GPI on the pi itself and use them in Companion )

**Comment by Pierremck** [comment]
Same here...
The Stream Deck stay with the Elgato logo even if Bitfocus say that it's should work with a Pi4 ...
What can we do ?

**Comment by Pierremck** [comment]
More info : 
-Works great with the Companion Pi OS with 2.0 build.
-As soon as i install NodeRed, Companion stop working (unreachable web page)
-An update of companion make it work again but the 2.1.1 installed does not see the StreamDeck mini !

Is there any possibilities to go back to the 2.0 build ?

**Comment by DeeJayMX** [comment]
> More info :
> -Works great with the Companion Pi OS with 2.0 build.
> -As soon as i install NodeRed, Companion stop working (unreachable web page)
> -An update of companion make it work again but the 2.1.1 installed does not see the StreamDeck mini !
> 
> Is there any possibilities to go back to the 2.0 build ?

Same Here.

Companion is working good through the emulator, and can trig the local host NodeRed

**Comment by DeeJayMX** [comment]
> > More info :
> > -Works great with the Companion Pi OS with 2.0 build.
> > -As soon as i install NodeRed, Companion stop working (unreachable web page)
> > -An update of companion make it work again but the 2.1.1 installed does not see the StreamDeck mini !
> > Is there any possibilities to go back to the 2.0 build ?
> 
> Same Here.
> 
> Companion is working good through the emulator, and can trig the local host NodeRed

But the Streamdeck stay with the logo.

In the surface page of companion, the Streamdeck surfac is not displayed and the Scan button has a strange behavior. Like it does nothing...

The Logs are free from error..

**Comment by DeeJayMX** [comment]
No idea ?

**Comment by Pierremck** [comment]
I actually achieved it but I don't really know how ^^ I used the companion pi image and I did the manual install on it after installing nodered and Companion being reinstalled it's now working.
I saved my sd card with this version of companion and node red working together and I don't try to re install everything because it's was a mess to make it works...

So my only advice it's to make the manual install on the companion pi image and that may works

**Comment by DeeJayMX** [comment]
So to sum up,
You built an SD Card with the CompanionPi image. after that you installed node red. and after that you reinstalled Companion on it.
is it correct ?

Can you share the img of your working SD Card ?

Are you sure that Node-RED is fully functionning ? Can you use the GPO in Node-RED ?

**Comment by Pierremck** [comment]
Yes it's correct !
I could share it but I can't go to my office because of the lockdown... 
I didn't try the gpio but I just used some UDP listener and SNMP sender's

**Comment by Julusian** [comment]
Im assuming that either this is working or you have moved on from the idea.
