### ISSUE TITLE
Button press by HTTP GET from IFTTT

### ISSUE THREAD

**Issue by alferca4** [bitfocus/companion#1257]
**PLEASE USE THE FOLLOWING PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE OR SOFTWARE PROGRAM**: https://github.com/bitfocus/companion-module-requests/issues/new

**Describe the feature**
I want to integrate companion in a IFTTT applet, using webhoooks can send HTTP get and post commands.

**Is this platform dependent (windows, mac, ..)?**
No.

**If documentation is required to implement, do you know where to find it?**
IFTTT, services, webhooks

**Usecases**
For example, trigger a button when google calendar have an entry.

**Comment by josephdadams** [comment]
You need to make some network modifications in order to do this. Either by opening the GUI port (default is 8000) at the firewall to your companion instance IP, or by using a tool like ngrok. We can’t really do anything within Companion to facilitate an IFTTT to Companion integration without that.
