### ISSUE TITLE
Flashing buttons

### ISSUE THREAD

**Issue by DachsbauTV** [bitfocus/companion#1258]
**Describe the feature**
Instead of having a button change to a certain colour for feedback reasons, for some applications it would be really useful to have the button flash.
Best case would have the option to choose the two colours and the frequency the button is flashing, but also just a simple white slow strobe would be enough.

**Is this platform dependent (windows, mac, ..)?**
Independet

**Usecases**
Examples:
- a muted microfon (never forget to unmute a commentator again after a break)
- a timer went to 0:00
- callback from an other position or device
- Battery level feedback
- on buttons with a lot of delayed steps it could be a great addition to see when it reached the last step

**Comment by josephdadams** [comment]
#674

**Comment by DachsbauTV** [comment]
Sorry my bad....
