### ISSUE TITLE
Dynamically/Temporarily Setting Page as Default Home, and having "Jump/Return to Home" function

### ISSUE THREAD

**Issue by arigolan** [bitfocus/companion#1263]
**PLEASE USE THE FOLLOWING PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE OR SOFTWARE PROGRAM**: https://github.com/bitfocus/companion-module-requests/issues/new

**Describe the feature**
I'd like to be able to temporarily set different pages as "Home", then have various buttons on various pages be set (often as a second action) to go "Home", without hard coding a particular page.

**Is this platform dependent (windows, mac, ..)?**
No.

**If documentation is required to implement, do you know where to find it?**
n/a

**Usecases**
We have a main "home" page with a bunch of macros for ATEM swtichers with multiple Super Source & DVE configurations for multi-person panel discussions (high-end zoom mtgs). We also have some buttons on the page that jump to sub-pages, like Timer Clock configuration, IFB/Audio Mixer Configuration, Playback via mimoLive Config, etc.

Each of these sub-pages have multiple config buttons, but at least one or more that are a finite action, that has a second action of going back to the main page. For example, after adding some minutes to a speaker timer, then pressing the "GO" button to start the timer, the second action on the "GO" button takes us to the main "Home" page.

However, I would like to have several variations of the main page, depending on how many panelists are participating, as each # requires an entirely different set of Macros. So rather than having to duplicate all the other Sub-Pages for each instance of the main page, so the corresponding buttons (like Timer "GO") jump to the correct page, I would like to be able to assign the "Home" page for each recording session, and all the sub-page buttons performing a "jump back to page" would go to whatever the current "Home" page is set to.

**Comment by Julusian** [comment]
I think this is possible now. The 'set surface to page' action can go to the startup page of the surface, which could be used for this. Or that same action can accept variables, so this 'home' page could be stored in a custom variable
