### ISSUE TITLE
[Plugin Support] Plugin written to read stream deck keypad comm, but doesn't work for latest stream deck software

### ISSUE THREAD

**Issue by shesh108** [bitfocus/companion#1264]
**PLEASE USE THE FOLLOWING PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE OR SOFTWARE PROGRAM**: https://github.com/bitfocus/companion-module-requests/issues/new
C# Plugin written to read stream deck keypad communication. keypad listen from plugin and change profile. Each keypad action is read by plugin and is then transferred to required application. Basically plugin works 2 ways with keypad.

Plugin was initially developed and tested with 4.3.2 stream deck software. Recently when stream deck updated to 4.9, seems to be issue in reading plugin and see breakage in working setup.

Just to check from when the breakage started, installed various versions of stream deck. I see 4.3.2, 4.4.2 and 4.5.1 are working fine but from 4.6.4 onwards plugin reading is broken.

Any help on this will be accepted.

Thanks,
Sheshappa

**Comment by shesh108** [comment]
On Stream deck 4.6.4 onwards plugin install, keypad actions are failing and profiles change leading to issue, say profile pictures are missing and keypad becomes unresponsive.

**Comment by shesh108** [comment]
Stream deck keypad with 20GAA9901 and 20GAA9902 are being used. But I see keypad of model 20GAA9901 is working for stream deck till 4.5.1 version but failing from 4.6.4 version onwards.

**Comment by josephdadams** [comment]
@haakonnessjoen

**Comment by Julusian** [comment]
This sounds like @shesh108 is having an issue with a custom plugin for the elgato software. None of what they said sounds like it is to do with companion. 
The companion plugin does work in recent versions of the streamdeck software
