### ISSUE TITLE
A JavaScript error occurred in the main process - Uncaught Exception - Error: Spawn cmd ENOENT

### ISSUE THREAD

**Issue by willsc123** [bitfocus/companion#1271]
Hi, I've just fresh installed Companion in order to try it with an Elgato Streamdeck XL and an Atem Mini Pro ISO

I get this error when starting the application
![Bitfocus-error](https://user-images.githubusercontent.com/38422333/98008802-2af7ad80-1df5-11eb-97b5-0af776fd6b0a.jpg)

Here is the information about the Windows build
![Bitfocus-windows](https://user-images.githubusercontent.com/38422333/98008865-3f3baa80-1df5-11eb-9953-46712fb9d5d5.jpg)

I can open up the GUI and select the ATEM via IP but no buttons show up on the Streamdeck. When I hit "Rescan USB", the same error popup appears.

I need some help fixing this issue.

Thanks

**Comment by JeffreyDavidsz** [comment]
closing this, if you still have issues let us know
