### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jameshardy01** [bitfocus/companion#1272]
Streamdeck XL on Mac Mini OS 10.15.7

Companion was running well, then one day it would not load. Now it is doing this error every-time it loads. Any Ideas?

Uncaught Exception:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at new db (/Applications/Companion.app/Contents/Resources/app.asar/lib/db.js:53:18)
    at exports (/Applications/Companion.app/Contents/Resources/app.asar/lib/db.js:41:9)
    at EventEmitter.<anonymous> (/Applications/Companion.app/Contents/Resources/app.asar/app.js:159:38)
    at emitNone (events.js:106:13)
    at EventEmitter.emit (events.js:208:7)
    at /Applications/Companion.app/Contents/Resources/app.asar/bitfocus-skeleton/main.js:138:10
    at Server.requestMessageHandler (/Applications/Companion.app/Contents/Resources/app.asar/bitfocus-skeleton/node_modules/electron-rpc/server.js:46:5)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)

**Comment by jameshardy01** [comment]
Deleted all versions of companion and deleted streamdeck from computer and redownloaded a fresh copy.

**Comment by josephdadams** [comment]
This could be a corrupted database. Can you try deleting that and opening it again? 
Delete the `~/Library/Application Support/companion` folder.

**Comment by onfire4g05** [comment]
Has there been any thought into moving the internal database to something more durable (like sqlite)? It could potentially be a "split system" of sorts where individual buttons are in a row with their json data to prevent any major overhauls of the backend. Either way, it should prevent a lot of the corrupted databases that seems to happen fairly consistently.

**Comment by jameshardy01** [comment]
Doing that fixed my app.

James Hardy[/var/folders/70/sgvtg_wx0kgf50bst49k57kc0000gn/T/com.microsoft.Outlook/Content.MSO/D2F077D7.tmp]
Technical Media Director  |  Community of Faith
t: (937) 583-5205<tel:(937)%C2%A0583-5205>
e: james@cofchurches.com<mailto:james@cofchurches.com>

400 N. Commerce St. <x-apple-data-detectors://13>
Lewisburg, OH 45338<x-apple-data-detectors://13>

On Nov 5, 2020, at 09:57, Joseph Adams <notifications@github.com> wrote:

﻿

This could be a corrupted database. Can you try deleting that and opening it again?
Delete the ~/Library/Application Support/companion folder.

**Comment by Julusian** [comment]
> Has there been any thought into moving the internal database to something more durable (like sqlite)? It could potentially be a "split system" of sorts where individual buttons are in a row with their json data to prevent any major overhauls of the backend. That'd also be better where if one particular feature fails, it doesn't corrupt the entire system. Either way, it should prevent a lot of the corrupted databases that seems to happen fairly consistently.

This is on my list of things to improve in 3.0, but that doesnt have a timeframe yet.
I think it will be tricky to do in 2.x, due to some of the architecture and lack of defined database schema. But depending on how far off 3.0 ends up being, it could be worth trying sooner.
