### ISSUE TITLE
[BUG]  Frequency polling of API REST vMix

### ISSUE THREAD

**Issue by Federico-Catelotti** [bitfocus/companion#1273]
The option to change ms of the frequency polling of API REST vMix is not shown in the instance config.
What could be the problem?

![Cattura](https://user-images.githubusercontent.com/74017757/98294713-b23d5080-1fb0-11eb-83f9-6d5d3072f562.PNG)

**Comment by McHauge** [comment]
@Federico-Catelotti no that's just because you're not on one of the newest beta builds

**Comment by Federico-Catelotti** [comment]
Where can I download the beta version? I thought 2.1 was already the latest released ...

**Comment by McHauge** [comment]
Yes 2.1 is the latest release, but there are daily beta builds where all the new stuff are, like the option to adjust the pooling rate.
You can find them here: [https://bitfocus.io/companion/download/builds/](https://bitfocus.io/companion/download/builds/)
![image](https://user-images.githubusercontent.com/31018035/98297967-87093000-1fb5-11eb-85ca-2159a407b3e7.png)

**Comment by Federico-Catelotti** [comment]
Ah ok, I hadn't seen it! Thanks
