### ISSUE TITLE
Rescan USB - Keyboard Shortcut?

### ISSUE THREAD

**Issue by DanDiamond** [bitfocus/companion#1274]
It would be very helpful to have a keyboard shortcut to have Companion rescan USB so I don't have to reopen the GUI everytime I switch locations.

**Comment by josephdadams** [comment]
I'm not sure a global hotkey will be possible across all platforms to perform a rescan, or if this would really be desired by everyone. Can you elaborate more on what it looks like when you switch locations? Are you physically disconnecting your deck via USB and then reconnecting it?

What if a button was added to the system tray popup to rescan?

**Comment by DanDiamond** [comment]
I'm changing locations and networks. When I come back to the studio I often need to rescan to connect. A system tray popup button would be great.

Thanks,

Dan

*( http://www.dandiamondmd.com )
*

*EMAIL:* dan@dandiamondmd.com ( dan@dandiamondmd.com )

*WEBSITE:* www.dandiamondmd.com ( https://www.dandiamondmd.com/ )

*PODCAST:* www.trenchtested.com ( http://www.trenchtested.com )

*PHONE:* 1–360-620-5000

( https://player.vimeo.com/video/279736043 )

People perform best when they believe they have the power to make a difference and a conviction to put other people first.

~ Dan Diamond MD

**Comment by Dalesjo** [comment]
Would it not make more sense to make Companion do this automatically. Either rescan after "system(power): Resuming" or try to rescan if it detects that a usb device has disappeared? I have the same issue when starting up my computer (Windows 10) from hibernation. Pressing "Rescan USB" detects the streamdeck again.

Looking into the logs, Companion detect both returning from hibernation and that the streamdeck disconnected

```
22. 15:01:32 device(AL37G1A03428<): Clear deck failed: Error: Cannot write to HID device
22. 15:01:32 device(AL37G1A03428<): Elgato Streamdeck device disconnected
22. 17:08:39 system(power): Resuming
```

After pressing "Rescan USB"
```
22. 15:08:58 device(AL37G1A03428): Elgato Streamdeck detected
```

**Comment by DanDiamond** [comment]
Samuel, I agree. Automating it is a great idea!

*( http://www.dandiamondmd.com )
*

*EMAIL:* dan@dandiamondmd.com ( dan@dandiamondmd.com )

*WEBSITE:* www.dandiamondmd.com ( https://www.dandiamondmd.com/ )

*PODCAST:* www.trenchtested.com ( http://www.trenchtested.com )

*PHONE:* 1–360-620-5000

( https://player.vimeo.com/video/279736043 )

People perform best when they believe they have the power to make a difference and a conviction to put other people first.

~ Dan Diamond MD

**Comment by Julusian** [comment]
There is now a context (right click) menu on the tray icon that has an option to rescan for devices.

**Comment by DanDiamond** [comment]
Julian,

Thanks but I'm not seeing it in Mac OS. Is this a Windows only improvement?

With gratitude,

Dan

*( http://www.dandiamondmd.com )
*

*EMAIL:* dan@dandiamondmd.com ( dan@dandiamondmd.com )

*WEBSITE:* www.dandiamondmd.com ( https://www.dandiamondmd.com/ )

*PODCAST:* www.trenchtested.com ( http://www.trenchtested.com )

*PHONE:* 1–360-620-5000

( https://player.vimeo.com/video/279736043 )

People perform best when they believe they have the power to make a difference and a conviction to put other people first.

~ Dan Diamond MD

**Comment by Julusian** [comment]
@DanDiamond are you running the most recent 2.2.0 build?
I've only tested it on windows and linux as I dont have easy access to a mac

**Comment by DanDiamond** [comment]
Julian,

Sorry. I've only got the most recent released version. I'm using it in the studio and want to be sure that it is stable. :) Any idea when the 2.2.0 version will be released for general consumption?

Thanks!!

Dan

*( http://www.dandiamondmd.com )
*

*EMAIL:* dan@dandiamondmd.com ( dan@dandiamondmd.com )

*WEBSITE:* www.dandiamondmd.com ( https://www.dandiamondmd.com/ )

*PODCAST:* www.trenchtested.com ( http://www.trenchtested.com )

*PHONE:* 1–360-620-5000

( https://player.vimeo.com/video/279736043 )

People perform best when they believe they have the power to make a difference and a conviction to put other people first.

~ Dan Diamond MD

**Comment by Julusian** [comment]
I don't think this is something we are going to do. As stated above, handling global keypresses cross-platform will be a challenge, and this would be better suited for another tool to capture and forward a command to one of the many apis which support triggering a rescan

And with #481 likely to be done in the next version after 2.2, this will be less important.
