### ISSUE TITLE
Internal button SELF

### ISSUE THREAD

**Issue by alferca4** [bitfocus/companion#1276]
**PLEASE USE THE FOLLOWING PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE OR SOFTWARE PROGRAM**: https://github.com/bitfocus/companion-module-requests/issues/new

**Describe the feature**
A variable that have the button self, so if I program a button to change background color itself, when copy and change location in the same page or another page, the variable gets the bank and the page numbers and modify the internal instance.

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along.

**Usecases**
For easy to use, when I program several pages with diferent purposes maybe I export the full page and import in another one and I have to change all the internal settings.

Give information about button state, for example when press a button can tell the instance if this other button is unpress, press it, if not do nothing

**Comment by high-solutions** [comment]
+1 very much, it's very time consuming to program and even more time consuming to move buttons.
also the risk of making a mistake when moving buttons is big....

**Comment by Julusian** [comment]
This is available for any relevant 'internal' action since companion-2.2.0-d3464b0-2811

**Comment by high-solutions** [comment]
then how do i use this "self command" i can only find the manual select page and bank to (for example) change the backgound color, if i move the button the background change stays at the manual inputted place.

**Comment by BasilChessman** [comment]
Choose "This Page" and "This Button" in the drop down menu.

**Comment by high-solutions** [comment]
sorry, i got confused because i grabbed the latest release this morning, but from the release section that is 2.1.2 and not 2.2.0
