### ISSUE TITLE
Streamdeck 1.2 key not working.

### ISSUE THREAD

**Issue by ctl-tx** [bitfocus/companion#1280]
The key 1.2 (and 2.2, 3.2, 4.2..... so on) is not illuminating. The Companion GUI shows that it is programmed and running but the physical stream desk remains dark. Any suggestions?

**Comment by josephdadams** [comment]
Are you running the Elgato app at the same time and don't have that button configured as a Companion button?

**Comment by ctl-tx** [comment]
I was running both at the same time. I was able to figure it out by quitting the Streamdeck app and rescanning for USB devices. When I quite the Streamdeck app it disconnected the device entirely. But it is working now. Thanks!
