### ISSUE TITLE
etc-eos module current and next cue feedback

### ISSUE THREAD

**Issue by thingyt** [bitfocus/companion#1281]
Feature: 
We would love to be able to show the current cue and next cue label on a Companion button.

Not platform dependent

Current and next slide labels are already visible in the Eos family variables in the instance setup screen. 

Usecases: 
So we can run lights from a remote location and know where we are in the show. 
The Go and Stop/Back are great but barring creating buttons for every cue on a companion page (which is impossible when you have 40 cues) and having to change it all the time when your show changes, you have no way of knowing where you are, especially in cases where multiple people have access and you need to make sure you don't advance when someone else has already done it. 
Having a button that shows current cue and next cue label will let you see what is going on without needing to use their glitchy phone app to know where you are. 
You can see in the instance info that next and current labels are already available so the only thing missing is displaying them.

**Comment by istnv** [comment]
All companion instance variables can already be displayed on buttons. When entering the text for a button, type in `$(` then you will have a drop-down list of all variables available

**Comment by thingyt** [comment]
I did not know that.

Thanks!
