### ISSUE TITLE
Sort added instances by (name, module, status, enabled?)

### ISSUE THREAD

**Issue by DachsbauTV** [bitfocus/companion#1283]
**Describe the feature**
Just some sorting options for the active/included instances, would be great.
Classic options could contain: name, date added, active/disabled, etc

**Is this platform dependent (windows, mac, ..)?**
No

**Usecases**
As this is a insanely versatile app, someone might end up with a lot of instances running at the same time. Some organizing options for this self-created mess would be amazing :)

**Comment by josephdadams** [comment]
This would definitely be great. Just like we can re-arrange button action items, the ability to move instances around would be real nice.

**Comment by krocheck** [comment]
Yeah, I looked into this since we have sorting code elsewhere and there was an architectural reason it was going to be difficult.  Doable, but not the simple port I was hoping for.

**Comment by dnmeid** [comment]
At the moment sorting is done alphabetical. It is not a big deal to have different output sorting, but we would need a way to input the sorting criteria. The one big list with gazillion actions is indeed a design mishap from the early days. So far the solution is to use the search functionality instead of sort.

**Comment by DachsbauTV** [comment]
@dnmeid I didn't mean the list to choose from, I am talking about the active instances.

sorry I wasn't clear enough

**Comment by Julusian** [comment]
I think there are two approaches that could be taken to this:

1) have the order defined manually, and leave it up to the user to sort them as they like
1) put them into a table that allows for sorting by different column on the fly

And perhaps it would work with either strategy, is to be able to group/categorise the connections in some way. This would work nicely with manual ordering, and would need some work to figure out how/if that would work with the auto sorting.

Being able to filter the list by status would be nice too (disabled/ok/warning/error)

Anyone have any preference?

**Comment by MeestorX** [comment]
#2. 
Could that not just be a visual thing within the html (and a small json setting to save the order) so that the underlying database order doesn't need to be messed with?

**Comment by istnv** [comment]
For me, sorting Enabled/Disabled would be helpful. I have a lot of modules disabled when I am not actively using certain items. Removing the module also destroys any buttons that reference them.

**Comment by Julusian** [comment]
@MeestorX yes, that is what 2 would end up being, stored completely client side. 

@istnv sorting, or hiding? I dont know where to put the buttons, but this is a quick prototype of filtering based on status (I stole a lot of it from the log tab) 
![image](https://user-images.githubusercontent.com/1327476/193475894-32c3e5bc-e6c5-4cc9-898c-a5c64e4c283b.png)
I think this would be nice to have whichever way we decide to go

**Comment by DachsbauTV** [comment]
Imo an easy solution could be an additional sort column where a user can give the instances a personal ranking by just giving it numbers.
then you can just sort by name, status label or your personal order

**Comment by istnv** [comment]
@Julusian For me, sorted by status is more important than hiding. I re-enable the modules when necessary.
Filter by status would work.

**Comment by josephdadams** [comment]
The filtering similar to the Log page would be great, with the ability to custom sort them like Actions.

**Comment by Julusian** [comment]
I'm playing with this in the 3.0/develop branch, and I am pretty happy with the result.  
The architectural issues stopping the manual sorting aren't a problem anymore, so this was fairly straightforward.

I still need to figure out where to put those filter buttons, but other than that I am happy with it

![image](https://user-images.githubusercontent.com/1327476/196040791-11c5d49c-7ec4-4b46-8895-acdae62abcde.png)

**Comment by Velikyi** [comment]
Could we get these arrows/handles for triggers too? Maybe even grouping where multiple triggers are needed for certain multi-functions?

**Comment by Julusian** [comment]
@Velikyi https://github.com/bitfocus/companion/issues/2035 will likely also be done in 3.0

**Comment by Julusian** [comment]
This is in the 3.0 betas
