### ISSUE TITLE
[REQUEST] Custom variables

### ISSUE THREAD

**Issue by WyzzyMoon** [bitfocus/companion#1286]
**Describe the feature**
I would love to be able to make and use custom variables. 
Have a list in companion where you can add variables names. And have a button function where you set one of those variables to a desired value/string.
Those variables would than be usable everywhere there is a text field, not just in titles like dynamic variables are now

**Is this platform dependent (windows, mac, ..)?**
Non platform dependent.

**Usecases**
Usecase 1: Lets stay I have 4 lover thirds in OBS called "LT1", "LT2", "LT3" and "LT4". But I have only one set of names, some appear more than once in different lowerthirds. Right now I would have to make 4 copies of the same sets of names, one set for each lowerthird because you can't change which lower third the button affects. With variables I could use one button called "edit LT1"  which sets a custom variables to "LT1" and than a name button which sets a preconfigured name to whichever lower thirds the custom variable says. 
So I would just need 1 set of name buttons, and 4 "edit" buttons. instead of 4 whole sets of the same names. 

Usecase 2: Button combinations would suddenly be MUCH easier. One button could effect a later result because you can "set" states which impact different buttons. 
Let's say you have 2 output displays and 8 inputs. With custom variables you could just hit a button to select one of your output displays, and than hit one of your inputs to link them. 
So hitting button "Output 1" would set a variables named "output" to "1".
And than hitting "input 8" would set "_$(output)_" to "input 8".

**Comment by McHauge** [comment]
Feel like this could be achieved with a generic variables module where you can select a number of variables you want or something like that, but not to sure it that would work with other modules in general, with out changing/updating them

**Comment by WyzzyMoon** [comment]
> 
> 
> Feel like this could be achieved with a generic variables module where you can select a number of variables you want or something like that, but not to sure it that would work with other modules in general, with out changing/updating them
Exactly!
Companion is already able to deal with Dynamic Variables from different instances. So if we can define general variables we could reference them by  something like "$(general:MyVariable)".
The only thing we would need if the ability to use "$(something)" in other places that titles.

**Comment by McHauge** [comment]
"The only thing we would need if the ability to use "$(something)" in other places that titles"

Yes and that is the part I'm not to sure about, i know at least one or two modules can use variables like that, but i don't expect it to work in all modules, as i think it needs to be programmed in manually as in case by case

**Comment by josephdadams** [comment]
#1266
