### ISSUE TITLE
fsevents module error on linux platform

### ISSUE THREAD

**Issue by dszoka** [bitfocus/companion#1294]
Just update my Pi 4 to the latest version 

saw this error -- Doesn't affect me but thought I would share it  
<img width="994" alt="Screen Shot 2020-11-30 at 9 02 51 am" src="https://user-images.githubusercontent.com/42435862/100558056-bdaa4000-3300-11eb-9e9e-574f2c83822d.png">

**Comment by Julusian** [comment]
With master now requiring node12, this should no longer be a problem
