### ISSUE TITLE
Dropdown for sources in "Toggle visibility scene item"

### ISSUE THREAD

**Issue by DachsbauTV** [bitfocus/companion#1295]
**Describe the feature**
Just a dropdown menu for "Toggle visibility scene item" to choose the source item and make everyones life a lot easier :) 
Apart from the workflow improvement it would also eliminate a possible typo problem, which would then not trigger the source.

**Is this platform dependent (windows, mac, ..)?**
No.

**If documentation is required to implement, do you know where to find it?**
The feedback instance "Change colours when source visible" already has the dropdown menu

**Bonus**
Also I think the naming of the action item is kind of confusing because it says "scene item" for what is usually referred to as "source"

**Comment by Julusian** [comment]
What module is this for?

**Comment by DachsbauTV** [comment]
ah damn my bad: for the OBS module. I'll move it
