### ISSUE TITLE
Instances OK button

### ISSUE THREAD

**Issue by nikb72** [bitfocus/companion#13]
the OK button to build a new instance feels like its in the wrong place, it doesn't seem to be associated with completing the add new instance flow

**Comment by willosof** [comment]
The OK button is a status symbol for the instances. The plan is that it will turn to WARN or ERROR if any of the instances have a problem connecting etc. This will also be indicated with a red dot in the top right corner on the elgato buttons that has actions associated with the instance with problems. :)

**Comment by McHauge** [comment]
Please check the open alfa for the module rewrite, there is currently testing ongoing with ALL panasonic PTC's, the changes can be seen in the development branch on the panasonic ptc module

Here is a link to the facebook post about it: https://m.facebook.com/groups/companion/permalink/2786070918277907/?sfnsn=mo
