### ISSUE TITLE
Request: add "reset" command to Watchout Module

### ISSUE THREAD

**Issue by Fishymobile** [bitfocus/companion#130]
**Describe the feature**
The reset command kills all auxiliary timelines and sends the main timeline to time 0:00

**If documentation is required to implement, do you know where to find it?**
![reset-command](https://user-images.githubusercontent.com/40611054/41936093-e2291428-7940-11e8-94d8-5c06c60886d1.png)

**Usecases**
When controlling multiple watchout production machines (primary & backup) the reset command ensures that both systems are at the same starting point so that both machines act predictably. to get this effect without this command you'd need to update the button to add another kill action every time you add an auxiliary timeline in watchout.

**Comment by haakonnessjoen** [comment]
Will be included after v1.1.1 release.
