### ISSUE TITLE
After adding NewTek NDI Studio Monitor unable to add actions to buttons

### ISSUE THREAD

**Issue by trombe** [bitfocus/companion#1302]
Using Win10
Add any instance, for us it's usually vMix, and then later add Studio Monitor.
After adding studio montior when you go to create a "regular button" and then proceed to add a function to that button it will 'click' but the function will not be assigned to the button. You can get around this by disabling studio monitor temporarily. I've also found that if you try again immediately it will work but not consistently. 
A few of us at our branch have run into this issue now as we use Studio Monitor to sub-switch downstage monitors. All comps have been using 2.1.1 and Win10.

**Comment by albertorighetto** [comment]
Possibly related to issue #1235

Steps to reproduce (from a blank configuration):
- add an NDI Studio Monitor instance
- configure the right IP (and obtain a valid connection, including Dynamic Variables)
- create a standard button
- try to add an action from the drop down menu (no scroll, no search), sometimes it will fail.

I can reproduce the bug only if the actions are added from the drop-down; scrolling or searching the command seems to work every time.
When it fails, usually NDIMonitor actions are listed as the last ones in the drop-down menu.

Will investigate further in the next days

**Comment by Julusian** [comment]
I agree that this is a duplicate
