### ISSUE TITLE
Button Unlatch Without Action

### ISSUE THREAD

**Issue by Jehar** [bitfocus/companion#1304]
**Describe the feature**
Add an action to button configuration that would allow for unlatching/resetting of the button state without it taking any of the actions assigned to it.

**Is this platform dependent (windows, mac, ..)?**
Negative

**Usecases**
There may be times when we are live that a button gets latched in a bad state (through user error or weird show flow), but will be needed again shortly for button down actions.

**Comment by davidjoshuaford** [comment]
I second this Enhancement Request! I want to be able to assign separate functions to a Short-Press and Long-Press. Use case in point: I have a row of ATEM Preview buttons where a Long-Press will change the Upstream Key to that corresponding input. However, it also unavoidably selects the Preview Input as well (the Short-Press). While I can then re-select another Preview input, it gets messy when setting up a Key. I could move the Preview Input to the UP/OFF action, but while there are "abort delayed action" functions, there doesn't seem to be any sort of "skip release" function internally within Companion, therefore it's unavoidable that the Preview input always gets pressed whether it's a short or long press. Would love to see this feature implemented.

<img width="602" alt="Companion -  Skip Release  request" src="https://user-images.githubusercontent.com/76959770/103551770-d7e3ba80-4e78-11eb-9f30-168aebe3ad4b.png">

**Comment by syberjedi1999** [comment]
I have needed this option many times. Would be nice if it had 3 options: 
-Global
-By page
-By Button

**Comment by Julusian** [comment]
This is now possible with the 'unlatch' option to the 'internal: Abort actions on button' action
