### ISSUE TITLE
Panasonic projector

### ISSUE THREAD

**Issue by alcrowell** [bitfocus/companion#1305]
need control for Panasonic projectors.  primary need is off/on but other features would be useful
**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along.

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by josephdadams** [comment]
@alcrowell you need to make module requests in the module requests repository. Please include model information as well as protocol information that shows how to control the projector over the network. Do a search before you request to make sure that projector module hasn’t already been requested.
