### ISSUE TITLE
Allow me to hide the menubar application

### ISSUE THREAD

**Issue by tsvoronos** [bitfocus/companion#1306]
**PLEASE USE THE FOLLOWING PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE OR SOFTWARE PROGRAM**: https://github.com/bitfocus/companion-module-requests/issues/new

**Describe the feature**
Please allow us to hide the Companion menubar app even if it's running.

**Is this platform dependent (windows, mac, ..)?**
macOS only, especially Big Sur (where menu bar spacing is so wide).

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along.

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by Julusian** [comment]
@tsvoronos could you attach a screenshot showing it in the menubar? Im curious how the spacing looks in Big Sur.

I suspect that electron may not be able to disappear completely like you want, and if it can then that could make it hard to determine that it is running and to stop it. I could well be wrong on that though, and there are other ways this could be achieved

**Comment by tsvoronos** [comment]
Here's what mine looks like right now - much more spaced out than before:

<img width="721" alt="4D836CDD-82E2-4217-A943-20CC819EDEEE" src="https://user-images.githubusercontent.com/1614152/101545128-ccce6500-3974-11eb-9283-553f24c842a1.png">

**Comment by Julusian** [comment]
I don't think this is something we are going to do.
Removing the menu bar icon will make it very hard to cleanly exit companion, without a reasonable chunk of work to make some other way to exit it
