### ISSUE TITLE
Run companion as a daemon outside of electron

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion#1307]
This is another in my series of ideas for v3

**Describe the feature**
There is currently quite a bit of fighting going on to get companion to play nice inside of electron. It is becoming quite painful to get all of the native modules to play nicely together because of c++ libraries and not being able to load multiple versions of them at a time.
This idea came to me when I read #1306, as a way of doing that, but I think it would be better suited for companion as a whole.

Instead of running companion inside of electron, we could run it as a daemon with https://github.com/foreversd/forever-monitor (or similar).
Electron then can simply be the config/management tool, that launches the companion process running.
The build process will become a lot more complex, as we will probably need to manually download and bundle a specific version of node inside the installer, and we will probably want to wrap all the code up in an asar file like it currently is. 

As a bonus of this, we will be free to keep electron up to date as it will be doing very little. And we will be free to use whatever version of node we choose.

Another benefit is that we can more easily handle crashes nicely. If instead of showing a dialog we store the error to disk for the webui to consume and then simply exit, then companion will restart and be available for use again

@haakonnessjoen what are your thoughts on this idea? I am tempted to try and do it for 2.2

**Comment by krocheck** [comment]
I'm not opposed to seeing how this plays out while building into 2.2.  There's clear benefits, just unclear what the potential downsides are.

**Comment by josephdadams** [comment]
I love this idea.

**Comment by Julusian** [comment]
I am currently using https://github.com/foreversd/forever-monitor due to its license, but I would rather pm2. Maybe it would be ok for the launcher (as I am currently calling it in code) to be gpl licensed as it and the rest of companion will be independent blobs of code, and are pretty isolate?
But thats a bit off topic.

I don't see how I can make forever-monitor run something truely in the background currently, but Im going to ignore this for now, as this isnt a requirement of this just yet.

I have `yarn dev` (when run inside the launcher folder) which works currently https://github.com/bitfocus/companion/compare/feat/run-as-daemon I shall look at packaging it next

**Comment by Julusian** [comment]
I think I am a bit blocked on this for now.
I am wanting to keep the asar or similar bundling for application code, to reduce the number of files especially as windows is horrifically slow with that many files. But I haven't been able to find a good way of doing it.
* https://www.npmjs.com/package/asar-node - doesn't handle native libraries well, so it isnt possible to make something that bundles and works properly.
* https://github.com/nexe/nexe - would be preferable as it bundles node and is being maintained. But worker_threads and code signing don't work, so it doesn't look viable right now.
* @yarnpkg/fslib might work, but looks like a lot of work to get it hooked up. nexe is working on supporting it, so it would be easier to wait for that https://github.com/nexe/nexe/pull/741
* webpack - maybe this is a valid option to condense core and each module down to single js files? then there is less need to bundle it in an asar/zip. but that would probably require work in each module to make it work.

**Comment by Julusian** [comment]
I have this working in develop for 3.0
Companion is bundled to a few files with webpack (a couple of libs have to be set as 'external' meaning they end up outside of the bundle.
With the new module api written for 3.0, it is possible to webpack them up too, so they will reside as their own folder on disk.

In total, I end up with ~5000 files on disk (decreasing this will be possible with additional work), with the total size of companion, all the modules and an electron 'launcher' ending up to be only a few mb larger than the all in electron builds.

This also means we could build a bundle without the electron component, which companionpi or other headless installations could use, instead of having to build from source. That would make updates for companion-pi many times quicker, and less likely to fail and leave the user with a broken installation
