### ISSUE TITLE
Multiaction button appears invisible on every page

### ISSUE THREAD

**Issue by randomizeguy** [bitfocus/companion#1308]
Hey guys,

**Describe the bug**

I created a multi action command in the Stream Deck software itself and put it into my Companion profile on an empty key. The button does not appear in the Companion software neither appear the Companion buttons in my Stream Deck software. The multi action works but the button is on my Stream Deck keypad invisible until I push the button. When I switch the page on the Stream Deck the button is invisible again and additionally overwrites the keys on the other pages at the same position as the multi action.

**To Reproduce**
1. Go to Stream Deck, generate a multi action, put It on your Keypad in your Companion Profile
2. The button does not appear but works, only visible after pushing and invisible after switching pages, overwrites buttons on the same position on other pages
3. Button does not appear in Companion software

**Expected behavior**
I wanted to create a multi action which contains commands from the Stream Deck software and customized buttons from my Companion. The multi action is working but not the positioning on my Stream Deck.

**Desktop (please complete the following information):**
latest Companion build, Windows 10, ATEM Mini Pro ISO, ATEM Software Control, latest Stream Deck software

**Comment by Julusian** [comment]
It sounds like both companion and the streamdeck software are connected to the streamdeck, which will give weird behaviour like this.
Either stop using the streamdeck software, or make sure that companion doesnt have the streamdeck listed in the devices tab
