### ISSUE TITLE
[BUG] Module-development; action options get cached

### ISSUE THREAD

**Issue by depili** [bitfocus/companion#1309]
Doing some module development with my clock-8001 module. Running with git head 9352ad97589487ae5aada9902f6455d5f3937549  on OSX catalina

Currently, if I update a registered instance action in my module, restart companion with `yarn run dev` the companion still uses the old options and title data for said action. Only if I change the id of the said action to be registered in the module does the fields update.

So for instance trying to change the label or the options in the action registration bellow doesn't yield an updated action in the GUI on companion restart.

But if I change the 'start_countdown_v4' id to anything else the new action appears in the GUI.

So something somewhere is caching the actions even in dev mode and I haven't been able to figure out which or where and how to reset that cache, which makes developing a module a real PITA

```
	self.system.emit('instance_actions', self.id, {
		'start_countdown_v4': {
			label: 'Start a countdown timer V4',
			options: [
				{
					type: 'textinput',
					label: 'Timer number',
					id: 'timer',
					default: 1,
					regex: self.REGEX_UNSIGNED_NUMBER
				},
				{
					type: 'textinput',
					label: 'Timer (seconds)',
					id: 'secs',
					default: 0,
					regex: self.REGEX_UNSIGNED_NUMBER
				},
				{
					type: 'textinput',
					label: 'Timer (minutes)',
					id: 'mins',
					default: 1,
					regex: self.REGEX_UNSIGNED_NUMBER
				},
				{
					type: 'textinput',
					label: 'Timer (hours)',
					id: 'hours',
					default: 0,
					regex: self.REGEX_UNSIGNED_NUMBER
				}
			]
		});
```

**Comment by depili** [comment]
And due to cache the above still gives me my old action with missing option field inside companion:
```
{
  id: 'GW9aDZvgE',
  label: '5HEbynJto:start_countdown_v4',
  instance: '5HEbynJto',
  action: 'start_countdown_v4',
  options: { secs: 0, mins: 1, hours: 0 }
}
```
Notice the missing timer field value

**Comment by krocheck** [comment]
To be clear ... adding a field where there are existing actions (even if a default is assigned) will not populate the default to existing actions.   That would require an upgrade script.  Now, if you're saying the new field doesn't show up at all, such as when adding a new action of that type, then we need to figure that out,  I haven't seen this, but I also can't test against Mac.

**Comment by depili** [comment]
I mean that that if I for example change the top label: key contents to for example "foobar" on my modules .js file, save it, restart companion and then go and add a action to a complete new button the dropdown still only has the old label. Same goes for the field id keys, their default values etc.

I this case I first had a copy-paste error and a duplicate id values for two of the option fields, and only way I got the gui to use the new stuff is to also change the action id string, which will get picked up nicely on next restart. After that changing the action id string back to the original returns everything to the original cached version with wrong data.

Even nuking Library/Application Support/companion directory has no effect on this. Neither does changing the browser. Nor bumping the module version string in it's package.json (but the new version number is picked up on the yarn run dev output)

And no, I don't expect existing buttons to change at all, but I would expect a new action picked on a new button from the dropdown to use the new option fields and their ID's

**Comment by thedist** [comment]
Have you tried logging the object emitted by your instance for the `instance_actions` event, and ensured that it is correctly registering the actions you expect it to be sending?

**Comment by depili** [comment]
This is a quick video showcasing this, showing that the action label isn't updating unless I also change the action ID on the dropdown: https://kissa.depili.fi/companion.mov

**Comment by depili** [comment]
And yes, if I remove that id from the list of the actions, the cached version is no longer offered in the dropdown

> Have you tried logging the object emitted by your instance for the `instance_actions` event, and ensured that it is correctly registering the actions you expect it to be sending?

And we have a winner... aka a duplicate key at the bottom of the array... :facepalm:
