### ISSUE TITLE
Module Request: Horae 

### ISSUE THREAD

**Issue by Deanbau** [bitfocus/companion#131]
**Describe the feature**
Control of Horae - a LTC timecode generator

**Is this platform dependent (windows, mac, ..)?**

Mac only

**If documentation is required to implement, do you know where to find it?**
https://sononum.net/horae/osc-specs

(It could also be used to trigger actions - it can send OSC out ;) )

**Comment by haakonnessjoen** [comment]
Implemented in https://github.com/bitfocus/companion-module-horae

**Comment by Deanbau** [comment]
A few more commands would be fantastic - ie to reset to zero / jump around

`

/horae/marker/goto | f | Goto next marker when parameter is 1.0 , previous when parameter is -1.0
-- | -- | --
/horae/marker/jump | f | Goto marker with specified index (first has index 1)


`
