### ISSUE TITLE
Loupedeck Live support

### ISSUE THREAD

**Issue by GarthDB** [bitfocus/companion#1311]
The [Loupedeck Live](https://loupedeck.com/en/products/loupedeck-live) is a device that's trying to fill a similar role as the Stream Deck. I have no idea if anyone has tried to bypass the official software or not, but it seems like it could be a good fit for Companion.
![image](https://user-images.githubusercontent.com/125516/101966494-377ddb80-3bd5-11eb-824b-790ef91cd5f7.png)

**Comment by josephdadams** [comment]
Pretty sure @willosof can chime in here... :)

**Comment by willosof** [comment]
Not a good fit for companion in this major release, but maybe a later. We're in the testing stages on another software called Buttons. It's like companion, with the same modules as companion, just with a more flexible way of programming and robust core. If a module crashes, it's contained in it's own process. Networked button surfaces, and supporting buttons, knobs, faders, joysticks, different types of displays and indicators, etc. :) We'll make sure to make a big deal out of it when it's ready for the masses to beta-test :)

**Comment by fbosman** [comment]
Can you tell me more about Buttons?

Met vriendelijke groet,

Frans Bosman


Verstuurd vanaf mijn iPhone

Op 12 dec. 2020 om 16:09 heeft William Viker <notifications@github.com> het volgende geschreven:

﻿
Not a good fit for companion in this major release, but maybe a later. We're in the testing stages on another software called Buttons. It's like companion, with the same modules as companion, just with a more flexible way of programming and robust core. If a module crashes, it's contained in it's own process. Networked button surfaces, and supporting buttons, knobs, faders, joysticks, different types of displays and indicators, etc. :) We'll make sure to make a big deal out of it when it's ready for the masses to beta-test :)

**Comment by willosof** [comment]
https://bitfocusio.slack.com/archives/CFG7HAN5N/p1607800696479300

**Comment by jaoustin** [comment]
Sorry to resurrect but can we have some kind of ETA in regards to Buttons? For some reason I can't access Slack.

**Comment by houtacheng** [comment]
News:
Loupedeck Live S
https://www.indiegogo.com/projects/loupedeck-live-s-customizable-streaming-console#/

**Comment by 33Fraise33** [comment]
https://www.razer.com/streaming-accessories/razer-stream-controller 

Razer announced the "Stream Controller" which is a rebranded Loupedeck Live, so possible the market for this product will increase a lot with a more commercial brand behind it.

**Comment by Julusian** [comment]
I am working on getting the loupedeck live (and once released the live-s) supported in companion with a crude mapping.
I don't yet know if it will be in 2.3 or 3.0.

I expect the razer version to need a small change to be supported, but it should hopefully just be a case of a couple of new ids and nothing more.

**Comment by latenitefilms** [comment]
AFAIK the Razer version is identical hardware, just re-branded.

**Comment by oddbear** [comment]
I have started playing around with the `Elgato Plugin for StreamDeck access` to make a plugin for Loupedeck, using the official Loupedeck SDK.

This approach seems to work, however with the same limitations as the Stream Deck plugin.

![image](https://user-images.githubusercontent.com/2109782/184024003-c307ff04-6b08-44e8-96a9-c9adac9c6ead.png)

**Comment by Julusian** [comment]
I should have said, I have done a very crude prototype implementation in companion-satellite. https://github.com/bitfocus/companion-satellite/commit/0e9ccbfafa2baaa064d882cda88ee696d36b54f5

I haven't had time to give it much of a test or polish since then, but I shall when I can. Once I have it working in satellite I shall look at porting that into companion itself too.

**Comment by Julusian** [comment]
I have this working nicely in companion-satellite now with a loupedeck live.

Could someone with a razer one give it a try? It should work but I do not have one to verify myself.
https://s3.bitfocus.io/builds/companion-satellite/companion-satellite-x64-158-705f954.exe
https://s3.bitfocus.io/builds/companion-satellite/companion-satellite-x64-158-705f954.dmg

I am halfway to supporting them in companion directly too, I will post back here when it can be tested

**Comment by latenitefilms** [comment]
I haven't tested your work yet, but just FYI - the Razer Stream Controller does work slightly differently from the Loupedeck Live, as it only has a single screen object.

See: https://github.com/CommandPost/CommandPost/commit/0468eaf8d680f47e76411f5d3bd92538e5db8add#diff-6c7cc51cb377445347d9f414947a4b711c89309cc76ce987845f52e5959c9095R1356

**Comment by Julusian** [comment]
@latenitefilms thanks, I have already rummaged around your code over there to do my implementation :)

**Comment by Julusian** [comment]
The loupedeck version of this will work in the beta builds now.

The razer version will not work yet, waiting for confirmation on it working in companion-satellite before doing the same here

**Comment by blakekrone** [comment]
What information can I get you to help with getting it ready for the Live S? I have one sitting on my desk and just downloaded the latest beta build but it isn't detected.

  Product ID:	0x0006
  Vendor ID:	0x2ec2

**Comment by Julusian** [comment]
@blakekrone I'm curious how you got one so early? I have one on order, waiting for them to start shipping.

In theory we already have the knowledge about how to talk to the device, it just needs some code to match that up with how companion needs it to be. I can try and find time to do a blind attempt at this, I was hoping to do it once I had received mine so I could test it myself

**Comment by blakekrone** [comment]
@Julusian I make custom mounts for streamers, sim rigs, etc, so they sent me one a couple of months ago to update my mounts to fit it.

**Comment by stevealexandre** [comment]
Hi @Julusian ,

Any news to manage the left and right screen on loupedeck live like below to display at least text or icons ?
![image](https://user-images.githubusercontent.com/21204359/210059798-5162d55f-2506-4ebf-ad60-ff4323a76be2.png)

Thanks for your work, really great on 2.4.1

**Comment by Julusian** [comment]
@stevealexandre no plans yet. I intend to start thinking about it once companion is able to show a proper loupedeck view in the button editing tab

**Comment by alterNERDtive** [comment]
Any progress on either of those two fronts? :)

**Comment by isaacdantzler** [comment]
Seconding this - I think it would be nice if that side view could show what button is attached to the dials or the buttons in column two (even if they aren't press-able)

**Comment by dragon788** [comment]
https://github.com/bitfocus/companion-surface-loupedeck/issues/15#issuecomment-2954289212
So awesome.

**Comment by alterNERDtive** [comment]
All I’m seeing in 4.2.0 is touch support for using the strips as a fader (and saving the value to a variable). Is the “slimmer buttons” thing not in yet?
