### ISSUE TITLE
Presonus StudioLive Rack Mixers

### ISSUE THREAD

**Issue by kjvisual** [bitfocus/companion#1315]
**PLEASE USE THE FOLLOWING PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE OR SOFTWARE PROGRAM**: https://github.com/bitfocus/companion-module-requests/issues/new

**Describe the feature**
A clear and concise description of what the feature does

**Is this platform dependent (windows, mac, ..)?**
Explain.

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along.

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

Thank you for all you do to help us work efficiently.

I don't know what is possible, but the Presonus StudioLive Rack Audio Mixer products need HELP. I mean operators need help using them. Initially it would help to use Companion to mute channels. It would also help to apply scene files to the mixer.

Here is a link to the device I use:
https://www.presonus.com/products/StudioLive-16R

The Universal Control app is what controls the device. Scenes (interface setups) can be exported as SCN files (they are readable). 

There is also a mobile app, Universal Surface. Both Universal Control & Surface send commands via IP. Both apps have a demo mode, so maybe you can reverse engineer without needing to purchase the gear. I am willing to beta test and record my screen.
My email: kenneth.jones@ucsf.edu

The Universal Control app does not seem to provide any automation help. The app is multi platform. When recording my Universal Control us with Apple's Automator Automator only seems to log the window being active. 

Thanks, I hope there is something that can be developed.

**Comment by josephdadams** [comment]
Has already been requested here: https://github.com/bitfocus/companion-module-requests/issues/52
