### ISSUE TITLE
Hide List of Dynamic Variables when they're all programmatically removed

### ISSUE THREAD

**Issue by estilles** [bitfocus/companion#1319]
**Describe the feature**
Automatically hide the List of Dynamic Variables if/when they're all programmatically removed

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
No documentation required. I'll be submitting a pull request for this issue.

**Usecases**
I'm adding a user configurable polling feature to the elgato-keylight module (see example below). There will be a checkbox that will allow the user to turn polling on or off. When polling is on several dynamic variables will be populated. If the user turns polling off, the dynamic variables will no longer be available and will programmatically removed.

I would like to hide the List of Dynamic Variables once they no longer exist.

**EXAMPLE**
> When polling is enabled and variables exist
![image](https://user-images.githubusercontent.com/5514878/102217560-b9447080-3f17-11eb-8549-b5150639c47a.png)

>When polling is disabled, variables are programmatically removed and they automatically be hidden
![image](https://user-images.githubusercontent.com/5514878/102217814-16d8bd00-3f18-11eb-9d65-8e4756e5f76d.png)

**Comment by krocheck** [comment]
I don't know.  I'd prefer the table be emptied rather then hidden.
