### ISSUE TITLE
Request: able to put added instances on pause modus

### ISSUE THREAD

**Issue by JeffreyDavidsz** [bitfocus/companion#132]
**Describe the feature**
When programming different instances not each instance is used on every job. Trying to reconnect to a machine that's not there, gives errors. Deleting the instance results in removing the commands at the buttons -which is not nice because the next job we need to program again-

**Is this platform dependent (windows, mac, ..)?**
Nope

**Comment by willosof** [comment]
This is a really good idea! Will implement this! :)

**Comment by willosof** [comment]
Closed in 55797e8 and 7016ef1 - Here you go @JeffreyDavidsz :)

**Comment by JeffreyDavidsz** [comment]
Tnx man!
