### ISSUE TITLE
Move from Slack and Facebook to Discord and Reddit

### ISSUE THREAD

**Issue by yurividal** [bitfocus/companion#1322]
I guys. This project is indeed very amazing.
I would like to suggest that you move the general group discussion from Facebook to something where moderation, indexing and search is a bit easier, and more private, such as Reddit.

I also noticed that the Slack account is a free one, and is almost out of space. Why not move the dev discussion to discord?

**Comment by JeffreyDavidsz** [comment]
Lot of the users have Facebook, and is an easy way to ask questions. My guess is that that account won't be deleted ;-) Slack is being used by us, it works for me. Are there any issues you are having?
