### ISSUE TITLE
Live image in Emulator

### ISSUE THREAD

**Issue by fkmobile** [bitfocus/companion#1324]
**PLEASE USE THE FOLLOWING PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE OR SOFTWARE PROGRAM**: https://github.com/bitfocus/companion-module-requests/issues/new

**Describe the feature**
Can we get the option of adding a live image from the ATEM on the emulator web page.

**Is this platform dependent (windows, mac, ..)?**
Any platform

**If documentation is required to implement, do you know where to find it?**
No documentation

**Usecases**
We use the emulator page to access the keypad from tablets and phones.  It would be good to see a LIVE program view on the same emulator page.

**Comment by josephdadams** [comment]
It's a great idea, but not possible given the limitations of all the architectures and platforms involved.
