### ISSUE TITLE
Allow Setting Number of Pages in Emulator

### ISSUE THREAD

**Issue by yurividal** [bitfocus/companion#1326]
**Describe the feature**
Allow the user to pick the number of pages to show on the emulator. Currently, pressing the up button from page 1 will take the user to page 99. It would be nice if the emulator would also take arguments like "?pages=1,2". 

An even better sollutuion would be for the user to pick how many pages he wants the entire system to have, or, to always ignore empty pages.

This makes it a lot easier to cycle between pages. 

**Is this platform dependent (windows, mac, ..)?**
No

**Comment by JeffreyDavidsz** [comment]
The emulator will show what you have programmed. So page filtering is not possible. Tabled page is made for that. On page1, delete the button that will bring you to page99. If you only need 1 page, just delete both buttons
