### ISSUE TITLE
Request: OSC Feedback to Streamdeck

### ISSUE THREAD

**Issue by Keksstar** [bitfocus/companion#133]
**Describe the feature**
Would be great if it´s possible to give feedback to Streamdeck via OSC commands to change the background of buttons, etc.
It´s a little bit related to #43 - but OSC wasn´t an idea there. OSC should be a simple one for the first attempt? That would make it possible to give Feedback from Qlab, CasparCG, etc. in the first stage.

**Comment by willosof** [comment]
Please check if there's similar tickets before filing new ones. Duplicates #78 and #43

**Comment by jpooley-hearst** [comment]
> Please check if there's similar tickets before filing new ones. Duplicates #78 and #43

Hey willosof, 

Both of these tickets have no mention of OSC and are closed. Could we please reopen this request for feedback via OSC? This would provide a seamless experience for users of QLC+, a lighting control software.

**Comment by estilles** [comment]
> Both of these tickets have no mention of OSC and are closed. Could we please reopen this request for feedback via OSC? 

@jpooley-hearst, like @willosof already mentioned, Companion already has a feedback system. This feedback system is protocol agnostic. It's up to module developers to implement feedback within their modules. Module developers are free to implement their feedbacks using whatever protocols the target device/software implements, including OSC.

> This would provide a seamless experience for users of QLC+, a lighting control software.

The best way to get specific support for QLC+ would be for someone to create module for it. Module requests should be done by creating an issue in the [module requests](https://github.com/bitfocus/companion-module-requests) repo. Coincidentally there's already a request for a QLC+ module. Here's the issue: bitfocus/companion-module-requests#612.

**Comment by ivan-ef** [comment]
You can try a workaround with conversion of one osc command to another. Companion can receive it’s own osc commands. You can try to convert your osc command to companion format with osculator on Mac or other 3rd party software.
