### ISSUE TITLE
"Go Back" to previous page

### ISSUE THREAD

**Issue by lee-moore** [bitfocus/companion#1330]
**Describe the feature**
To allow the user to Return or Go Back to the previous page.

I see this as an internal action to be added to a button that simply returns the user to the last page they were on.

**Is this platform dependent (windows, mac, ..)?**
All platforms

**If documentation is required to implement, do you know where to find it?**
Internal

**Usecases**
I'm a Barco Event Master (E2) user and also these days I am responsible for VT playback and Countdown clock.
I would like to be able to have multiple pages of E2 presets, and on each page have a "Set Surface To Page' button linking to my Countdown Clock and/or VT pages. After going to these pages, I need to return to the E2 preset page I was on previously. With multiple preset pages, I currently would have to return to a "Menu" page with all my preset pages on to get back to where I was or link every preset page back from the Coundown/VT Page.

Another example could be a sound engineer working with Yamaha CL desk and doing Sting playback with Qlab.
From his CL control pages, he would have a "Set Surface To Page" button to get to his Qlab page; after playing the sting he want to return to CL page he was on previously before playing the sting.

Could appear in the internal actions as "internal: Set Surface To Previous Page"

**Comment by lee-moore** [comment]
This is amazing, thank you so much! 

Sorry for being stupid, but how do I download the build with these additions, from builds?

Many thanks, and have a great Christmas / New Year.

Regards,
Lee Moore.




On 19 Dec 2020, at 01:36, Keith Rocheck <notifications@github.com> wrote:


Closed #1330 <https://github.com/bitfocus/companion/issues/1330> via bitfocus/companion-module-bitfocus-companion#23 <https://github.com/bitfocus/companion-module-bitfocus-companion/pull/23>.

**Comment by thedist** [comment]
The module that I added the forward/back option to the set page action hasn't yet been integrated with the main Companion build, so right now it's not currently available as a build unless you were to make your own custom build of Companion.

When Companion gets updated with the next set of module updates a build will be available on the build page https://bitfocus.io/companion/download/builds/ but I don't have an ETA for you as to when this may be due it being close to Christmas.

**Comment by lee-moore** [comment]
No problem Jeff, thanks for the reply, and have a good xmas.

Regards,
Lee.

**Comment by robertl87** [comment]
Hi, I'm looking for the exact same thing, but can't figure out how to use this 'go back' or 'page history' thing. Where can I find out if it's available or how to add it to the latest version myself?

**Comment by thedist** [comment]
You can use either of the following Actions `internal: Set surface with s/n to page` or `internal: Set surface with index to page`, then in the 'Page' option, scroll to the top of the dropdown and there'll be Forward and Back options.

I don't recall if this was included in the current 2.1.x releases, but if you don't see those options there in the Page dropdown you may need to download one of the latest beta builds (or wait till the end of this month when the plan is to make 2.2.0 an official release)

**Comment by robertl87** [comment]
Hm, it doesn't seem to be in v2.1.4, so I'll wait till 2.2.0 to come out. Thanks!
