### ISSUE TITLE
[BUG] [MINOR] "Close" should be renamed to "QUIT" or "EXIT"

### ISSUE THREAD

**Issue by yurividal** [bitfocus/companion#1331]
The "close" action button on the electron window can be a little bit confusing. I suggest "exit" or "quit", as it is more usually adopted when a button terminates the program.

Maybe, the "Hide" could also be renamed to "Minimize" or "Minimize to Tray".

**Comment by josephdadams** [comment]
I agree. I still sometimes click Close thinking it's Hide. :)

**Comment by JeffreyDavidsz** [comment]
done

**Comment by yurividal** [comment]
Hey @JeffreyDavidsz thanks for this.
Considering that the toggle right above it says "Start Minimized", don't you think the "hide" button should also be renamed to "Minimize" ?
It can be a bit confusing to a first-time user, specially because we already use the term minimize on that same window to refer to the same functionality.

**Comment by JeffreyDavidsz** [comment]
Minimize and hide are actually two different things. Hide is the right term in this case. The minimize button should minimize instead of hide

**Comment by yurividal** [comment]
> Minimize and hide are actually two different things. Hide is the right term in this case. The minimize button should minimize instead of hide

So, perhaps change the Checkbox to "start hidden"?
Also, many other apps call it "minimize to tray" but I understand that's a bit too long
