### ISSUE TITLE
Companion is using massive resources in Big Sur 11.1

### ISSUE THREAD

**Issue by DanDiamond** [bitfocus/companion#1335]
Running Mac Big Sur 11.1 on a MacBook Pro with 2.4 GHz 8-Core Intel Core i9 and 32 GB 2667 MHz DDR4. Companion is using about 40+% of my energy and keeps my fan spinning. Rebooting doesn't fix it. There are multiple versions of Companion Helper Running. There was one that wasn't responding and I killed it before doing this screen shot. Any suggestions? Is this a common issue? Thanks!

<img width="854" alt="Companion Resources0" src="https://user-images.githubusercontent.com/34456817/102415759-9369ab00-3fad-11eb-85f6-c42aa7bcacfc.png">

**Comment by DavidTNguyen** [comment]
What are the integrated components into your Companion? StreamDeck, ATEM (with or without macros), et....The more info about your ecosystems, the better it helps replicate the issue.

**Comment by Julusian** [comment]
I don't think there is enough information here to work from.
It is most likely to be caused by a module/instance so without knowing what is being used I do not know where to start looking
