### ISSUE TITLE
set button type

### ISSUE THREAD

**Issue by fdebeer** [bitfocus/companion#1338]
when i select a button to program, i have to select a button type first. but in 99% of the cases i want a regular button.
can it be made that if i select a button it gives me right away the page for the regular button. this wil save a lot of time.
there is still the choice for the page up page number and page down on the page

**Describe the feature**
when selecting a button, start with the regular button page

**Is this platform dependent (windows, mac, ..)?**
no

**Usecases**
ease of operation

**Comment by Julusian** [comment]
I'm not sure about this. There is a difference between an empty button and a regular button which hasnt been filled in, and this will make it too easy to accidentally convert an empty button into a regular one.

Perhaps the solution here is to change the 'Set button type' dropdown to set it to a regular button when clicked, with the others still in the dropdown?
It will still be a click, but it will be an easy click

**Comment by fdebeer** [comment]
> I'm not sure about this. There is a difference between an empty button and a regular button which hasnt been filled in, and this will make it too easy to accidentally convert an empty button into a regular one.
> 
> Perhaps the solution here is to change the 'Set button type' dropdown to set it to a regular button when clicked, with the others still in the dropdown?
> It will still be a click, but it will be an easy click

English is not my nativ language, and maybe i was not exactly clear what i mean, but your comment here is the same as what i mean. thans for making it a bit more clear :-)

**Comment by JeffreyDavidsz** [comment]
Implemented
