### ISSUE TITLE
We need a general form generation system.

### ISSUE THREAD

**Issue by haakonnessjoen** [bitfocus/companion#134]
**Description**
We have a lot of dynamic forms in companion. Instance config, bank editor, action options, user configuration, and soon feedbacks. Instead of creating a new generator for each of them, we should create one general for all of them. That supports text, dropdown, colors, etc.

**Comment by krocheck** [comment]
@Julusian can we consider this closed with the React UI?

**Comment by Julusian** [comment]
Yes I think so
