### ISSUE TITLE
Allow user to pick the folder for database and settings

### ISSUE THREAD

**Issue by yurividal** [bitfocus/companion#1347]
It would be nice if the user could select where they want to store the settings and database files. This would make it easy for us to sync the settings between different computers using tools such as google drive sync.

**Comment by josephdadams** [comment]
This location is determined by electron and your OS. But I could see this changing in v3. @Julusian

**Comment by krocheck** [comment]
If you run `headless` it is possible to set an environment variable called `COMPANION_CONFIG_BASEDIR` to set a directory for config and database files.  But yes, I can see this being a helpful feature across the board.

**Comment by Julusian** [comment]
This is rather tricky in the current architecture, but I can see the value in it.

**Comment by Julusian** [comment]
This is possible to do by setting the environment variable 'COMPANION_CONFIG_BASEDIR' in the script/shortcut companion is launched with.
