### ISSUE TITLE
Companion support for Faithlife Proclaim 

### ISSUE THREAD

**Issue by dherr0912** [bitfocus/companion#1348]
**PLEASE USE THE FOLLOWING PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE OR SOFTWARE PROGRAM**: https://github.com/bitfocus/companion-module-requests/issues/new

**Describe the feature**
Proclaim is very similar to Propresenter. I just need basic function for next slide hotkey 

**Is this platform dependent (windows, mac, ..)?**
Proclaim is a cross platform software. I am currently running on Windows 10

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along.

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by josephdadams** [comment]
@dherr0912 I closed your module requests for a few reasons.
- This is the wrong place for module requests.
- Proclaim does not have an API.
- It only has midi control.

If it helps, here’s a link to my personal blog that shows how you can control Proclaim with Companion using the midi relay module and program: https://techministry.blog/2020/06/25/walkthrough-using-a-streamdeck-and-midi-relay-to-control-faithlife-proclaim/

**Comment by dherr0912** [comment]
My apologies for posting the wrong section. This is helpful thank you. Would the program loopMidi https://www.tobias-erichsen.de/software/loopmidi.html  work for a Windows machine to start listening for midi cues from companion on the same lan 

Damien Herrington

**Comment by josephdadams** [comment]
Yes I use that all the time on Windows for this.

**Comment by dherr0912** [comment]
Thank you so much. And sorry again for posting in the wrong place.

Damien Herrington

**Comment by dherr0912** [comment]
I don’t know if I use the midi relay instance or not. what would be the instance in companion to talk to loopMidi over a lan on a different computer ?

Damien Herrington

**Comment by josephdadams** [comment]
Use the midi-relay instance/module in Companion to send messages to midi-relay running on the Proclaim computer. You’ll target the loopMidi port with the midi voice messages you send. Proclaim will pick up on those and act accordingly.
