### ISSUE TITLE
[BUG] New macOS tray menu causes window to flash on/off when clicked

### ISSUE THREAD

**Issue by bryce-seifert** [bitfocus/companion#1356]
**Describe the bug**
New tray menu causes main window to flash when clicking on the companion icon.

**To Reproduce**
1. Click on the Companion in macOS tray.
2. Main window will flash on and off

**Expected behavior**
Wait until show/hide window is selected for action.

**Screenshots**

https://user-images.githubusercontent.com/50299051/103463491-5a8e3d80-4cf2-11eb-9378-4a6c2ae7123e.mov

**Desktop (please complete the following information):**
 - OS: macOS 11.1
 - Browser n/a
 - Companion Version 2.2.0

**Comment by Julusian** [comment]
It is supposed to be that a normal click on the icon will show/hide the window, and a right click will open the menu.
I havent test it on mac, so maybe some default behaviour needs supressing. Or maybe it should just always show the menu instead

**Comment by bryce-seifert** [comment]
Yes the default on macOS seems to always show the context menu and that seems to be conflicting somehow with the toggleWindow. I was able to get around this be removing setContext menu, and using popUpContextMenu in the click actions.

But I think, to me at least, always showing the menu and not toggling the window makes the most sense, since the menu has the "Show/Hide Window" option in it. My guess it most of the time, people will be intending to access one of the options in the context menu and not to see the window.

Removing the following in electron. js makes this behavior happen in macOS, not sure about windows.
```
	tray.on('double-click', toggleWindow);
	tray.on('click', toggleWindow);
```

**Comment by bryce-seifert** [comment]
Looks like this is fixed with https://github.com/bitfocus/companion/commit/b2528f545006c418629c8fc9338330c44cdbeaaf thanks!
