### ISSUE TITLE
Add ability to clear a button's PNG

### ISSUE THREAD

**Issue by estilles** [bitfocus/companion#1358]
**Describe the feature**
Add the ability to clear/remove an image that has been added to a button/bank

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
N/A

**Usecases**
When editing a button that has an existing image, one may want to remove the image and just add text. At the moment, the only two options are (a) remove and re-add the button or (b) to use a completely transparent PNG.

**Comment by estilles** [comment]
The idea is for it to look something like this:

![image](https://user-images.githubusercontent.com/5514878/103643879-60a14a00-4f90-11eb-90f1-49d670e3557c.png)

I can submit a PR if the feature is approved.

**Comment by josephdadams** [comment]
Great idea!

**Comment by Julusian** [comment]
I think the clear should be below the '72x58 png' heading, to the right of 'Browse'.
Having it above doesnt explain very well what it will do.

But yes, I think having this is a good idea

**Comment by istnv** [comment]
I found this a few days ago:
If you re-select 'Regular button' on the 'Set Button Type' dropdown, the PNG and Text get cleared. 
The actions and feedback remain.

**Comment by istnv** [comment]
It would be better to have an obvious way to clear the image.

**Comment by yurividal** [comment]
Would be cool it clear was also an action that could be assigned to a button.
Even more, if we could change tk a  different png on the press of a button.

**Comment by estilles** [comment]
> Would be cool it clear was also an action that could be assigned to a button.
> Even more, if we could change tk a different png on the press of a button.

I would actually like to be able to choose/chance the image based on state, but that's a totally different feature request (which I intend to work on soon). :-)

**Comment by estilles** [comment]
> I think the clear should be below the '72x58 png' heading, to the right of 'Browse'.
> Having it above doesnt explain very well what it will do.
You're right. It made sense when I initially did it, but coming back with fresh eyes it's really not clear.

So is the consensus, the "Clear" button should be on the right of the "Browse" button? Will submit a PR for review today.

**Comment by estilles** [comment]
A full size button with a "Clear" label next to the "Browse" button used a little too much real estate for my taste, so I opted for an icon if type `fa-trash`, in a button of size `btn-sm`. What do you all think?

![image](https://user-images.githubusercontent.com/5514878/103768936-5e0d2600-505e-11eb-93c7-9bef836d0661.png)

**Comment by McHauge** [comment]
I like it, but would probably scale It to be the same height as the browse, in order to keep it consistent

**Comment by estilles** [comment]
> I like it, but would probably scale It to be the same height as the browse, in order to keep it consistent

@McHauge Agreed.

![image](https://user-images.githubusercontent.com/5514878/103770030-4a62bf00-5060-11eb-86a2-23cba3f2229c.png)

I'll submit a PR shortly.

**Comment by istnv** [comment]
@estilles 
> I would actually like to be able to choose/chance the image based on state, but that's a totally different feature request (which I intend to work on soon). :-)
Feature request #1205

**Comment by Julusian** [comment]
> > Would be cool it clear was also an action that could be assigned to a button.
> > Even more, if we could change tk a different png on the press of a button.
> 
> I would actually like to be able to choose/chance the image based on state, but that's a totally different feature request (which I intend to work on soon). :-)

This is quite a large task to do properly because the module feedbacks define the colour pickers, so something would probably need to be changed with them to make something more generic.
I did have a look at doing this, but quickly got lost in the code trying to follow the flow of logic.
If you do start anything, it would be good to discuss how you intend to make it work

**Comment by Julusian** [comment]
The PR for this has been merged

**Comment by estilles** [comment]
> > > Would be cool it clear was also an action that could be assigned to a button.
> > > Even more, if we could change tk a different png on the press of a button.
> > 
> > 
> > I would actually like to be able to choose/chance the image based on state, but that's a totally different feature request (which I intend to work on soon). :-)
> 
> This is quite a large task to do properly because the module feedbacks define the colour pickers, so something would probably need to be changed with them to make something more generic.
> I did have a look at doing this, but quickly got lost in the code trying to follow the flow of logic.
> If you do start anything, it would be good to discuss how you intend to make it work

@Julusian Yeah ... I took a look at it a last year as well , but decided to put it on the side burner due to the complexity. I want to resume work on it soon though. I'll create a new issue and share my notes/thoughts on how to approach this.
