### ISSUE TITLE
[BUG] Companion not working on 3rd generation Ipad

### ISSUE THREAD

**Issue by 11mb** [bitfocus/companion#1359]
**Describe the bug**
On an Ipad running IOS 9.3.6 (newer versions not supported on 3rd Ipad generation) it is not possible to see or use the buttons

**To Reproduce**
1. On an Ipad running IOS 9.3.6 open the companion app
2. Either: Click on 'Emulator' or 'Web buttons' or 'Mobile buttons'

**Expected behavior**
I would expect to see a grid of buttons that I can use.

**Acutual behavior**
There are no buttons displayed

**Additional context**
Probably due to the fact that newer javascript versions are not supported, companion will not work.

**Comment by yurividal** [comment]
Latest version is working for me on iPad, but there are some issues, like the one reported [here](https://github.com/bitfocus/companion/issues/1391)

**Comment by Julusian** [comment]
I dont think this is something that we have the time to fix ourselves. Supporting every old browser is not an easy task.

If you can either narrow down the cause of it not working, or can open a pr which fixes it then we shall consider including it, but I think it will depend on the impact of the fix on other browsers. For example, the newer tablet view relies on fairly modern features to have reasonable performance
