### ISSUE TITLE
[BUG] module categories

### ISSUE THREAD

**Issue by amoyer1974** [bitfocus/companion#1360]
**Describe the bug**
The issue is a bunch of modules that appear in the wrong category, which makes it difficult to search for them. These extra categories make it difficult to search by category when you can't scroll down the list too. Especially when viewing under Firefox.

When adding instances by "Category" the following items show up in the wrong category...
1 - Category "dLive" shouldn't exist - modules should be in category "Audio"
2 - Category "ilive" shouldn't exist - modules should be in category "Audio"
3 - Category "Hardware" shouldn't exist - all Digico modules should appear under category "Audio"
4 - Category "Novastar" shouldn't exist - modules should be in category "LED Processing"
5 - Category "Roku" shouldn't exist - modules should be in category "TV"
6 - Category "Sony" shouldn't exist - modules should be in category "TV"
7 - Module "ChristiePj" should exist in category "Projectors

**Comment by josephdadams** [comment]
Ok, I've gone through and fixed these that you have listed. Once each module has been updated in the core, you'll see those updates in a beta build.

**Comment by amoyer1974** [comment]
Thanks!


-------- Original message --------
