### ISSUE TITLE
Companion starts with all modules unresponsive[BUG]

### ISSUE THREAD

**Issue by shaunar2006** [bitfocus/companion#1365]
Whenever Companion (2.1.2 (f4bcaf3-2679)) is first started, ALL modules are unresponsive. The "status" box is blank. In order to use companion, I have to disable then enable each module one by one after each restart of the program. 

Computer specs:  <img width="228" alt="Screen Shot 2021-01-08 at 2 24 37 PM" src="https://user-images.githubusercontent.com/53232897/104060921-4304f800-51bd-11eb-9ff9-3b55920e09ad.png">

Video of the issue:  https://drive.google.com/file/d/1-74D3YGZKy4f3KjrNxtomQSatZO_mpbO/view?usp=sharing

**Comment by josephdadams** [comment]
@shaunar2006 can you try to repeat this on a fresh install of Companion with one of those modules? Just to rule out something with your existing config.

**Comment by shaunar2006** [comment]
Thank you Joseph.
I believe i remedied the issue. After deleting the program and reinstalling, I imported my old config, and the issue persisted. I then started looking at the Javascript error and noticed that it was a stage display error on one of the propresenter modules. 

on the edit page of the module, there is a drop down menu for "Pro7 Stage Display Screen To Monitor Layout". Since I am running Pro 6, this was left blank. On a whim, I selected the only option "Connect to Pro7 to Update" and clicked apply.

The error went away and now companion seems to startup with all modules with an "OK" status. 

So if a user is running Pro6, they may run into the same issue unless they select "Connect to Pro7 to Update".

<img width="467" alt="Screen Shot 2021-01-15 at 3 57 32 PM" src="https://user-images.githubusercontent.com/53232897/104783245-36e3e200-574b-11eb-8ca3-9befa3c45265.png">

<img width="467" alt="Screen Shot 2021-01-15 at 3 57 39 PM" src="https://user-images.githubusercontent.com/53232897/104783253-3c412c80-574b-11eb-9fa3-2e9bc78a16b4.png">

**Comment by josephdadams** [comment]
@greyshirtguy

**Comment by greyshirtguy** [comment]
So sorry!!!
I'll look into this today get ProPresenter module fixed!!!

**Comment by greyshirtguy** [comment]
Found issue, will submit fixed code soon

**Comment by greyshirtguy** [comment]
Fix has been pulled and is in current dev builds.
