### ISSUE TITLE
[BUG] Scheduler script runs but doesn't show up in the list

### ISSUE THREAD

**Issue by DachsbauTV** [bitfocus/companion#1367]
**Describe the bug**
I've added a scheduled trigger (time interval) and basically it runs fine.

However several problems occur:
1. The dialog doesn't close when pressing save. But the trigger is saved
2. The scheduled trigger doesn't show up in the list, which makes it uneditable and undeletable
3. What makes it even worse: Even an import of a full config doesn't delete the scheduled task (reinstalling companion cleared it)

**Desktop (please complete the following information):**
 - OS: Win10 64 2004
 - Browser: Opera Chrome and Firefox
 - Companion Version 2.2.0 (9f3dbc8-2793)

![Screenshot 2021-01-10 at 14 22 03](https://user-images.githubusercontent.com/70434961/104124207-c5252600-534f-11eb-9502-234994008e6c.jpg)

**Comment by empyfree** [comment]
Can corroborate this behaviour.  Triggers continued after pressing reset under the "import/export" tab and only stopped once I'd restarted companion.

Desktop (please complete the following information):

OS: MacOS 11.1
Browser: Safari & Chrome
Companion Version 2.2.0 (6b0899f-2800) (also 2.2.0-fff0ee4-2799)

**Comment by Julusian** [comment]
Can you try with c13b28a-2814?
I found an issue with the interval type that I think it the same as what you are seeing here

**Comment by empyfree** [comment]
This seems to have fixed it for me on Mac.   Works as anticipated now.   Very powerful feature.

**Comment by Julusian** [comment]
perfect :)

**Comment by DachsbauTV** [comment]
ah dann 2hours two late haha just tried it as well and it works like a charm. thanks a lot julian
