### ISSUE TITLE
[FEATURE] Dynamically generated action/feedback (dropdown) option choices

### ISSUE THREAD

**Issue by estilles** [bitfocus/companion#1371]
**Describe the feature**
At the moment, action/feedback dropdown option choices use a static array of hashes, with key/value pair for an `id` and a `label`. While that is perfectly fine for many uses cases, there are times when a dynamically generate this list of choices could be very useful. 

What I propose is adding a property to the dropdown options (maybe called `getChoices`). If this new property exists and contains a function it will be used to dynamically generate the `choices` array.

If the new property doesn't exist the `choices` array would be used, therefore maintaining backwards compatibility.

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
N/A

**Usecases**
One particular use case that comes to mind is the selection of "Inputs" in vMix, but I'm sure this can be used in any number of modules.

Certain vMix actions allow one to specify an "Input" manually, by entering the input name, number or GUID.

![image](https://user-images.githubusercontent.com/5514878/104204942-c433e780-5468-11eb-86c2-f353c35f5edd.png)

Since the vMix module maintains a list inputs, we could easily replace the `textinput` option (used to specify the input) with a `dropdown` option (with `tags` set to `true`), where the option choices would be a pre-generated list of existing inputs. This would allow the user to either manually enter an input name, number or GUID (as usual), or alternatively select the desired input from the dropdown list.

---

PR to follow ... if you guys like the idea.

**Comment by dnmeid** [comment]
This is a feature already available. The module can control all actions, feedbacks and also options at all times. The "array" actually is an object and this can be changed programatically. Afterwards the module can call an update so that all instances in the gui reflect the changes.

**Comment by estilles** [comment]
> This is a feature already available. The module can control all actions, feedbacks and also options at all times. The "array" actually is an object and this can be changed programatically. Afterwards the module can call an update so that all instances in the gui reflect the changes.

Got it! Thanks @dnmeid. I guess what I was looking for was a more "standard way" to define the code that would generates the dynamic choices within the action definition.

Thanks for to comments. I really appreciate it.
