### ISSUE TITLE
[BUG] Node.js version in develeoper.md is wrong

### ISSUE THREAD

**Issue by Scyten** [bitfocus/companion#1372]
https://github.com/bitfocus/companion/blob/master/DEVELOPER.md
states `$n 8.12.0` but >12.04.0 is needed.

**Comment by Scyten** [comment]
`npm run start ` one line after does not work, too.
`npm ERR! missing script: start`

**Comment by josephdadams** [comment]
Try using `yarn dev` to start it up.

**Comment by Scyten** [comment]
`yarn dev` works for start up. But the wrong version remains
