### ISSUE TITLE
HTTP Style Trigger

### ISSUE THREAD

**Issue by jpurdy647** [bitfocus/companion#1374]
The HTTP trigger for buttons is very useful, but what would also be good would be HTTP style changing as well, for example:

localhost:8888/style/text/1/15 HELLO WORLD

Un-encoding the URL should be pretty easy, and this would greatly improve the ability to send feedback to a particular deck. For example I have a AutoHotkey script that runs with a custom delay based on a PowerPoint slide, being able to see the delay count down on the tablet would be useful

**Comment by jpurdy647** [comment]
Looks like this could be a simple matter of adding a couple regexes and implementing code from /lib/osc.js in /lib/server_http.js, would it be this simple? I'm going to set up a Linux server and try getting my own build working and playing with things, not sure if I'll be successful with this so would definitely not discourage anyone else from attacking.

**Comment by JeffreyDavidsz** [comment]
Let us know!

**Comment by Haavard15** [comment]
These are already implemented, just not documented.

I have fixed the documentation on this PR:
https://github.com/bitfocus/companion/pull/1412
