### ISSUE TITLE
[BUG] Junk packets crashes companion via lib/osc.js

### ISSUE THREAD

**Issue by willosof** [bitfocus/companion#1378]
Incoming screenshot. I havn't been able to reproduce it myself. But it seems like messages not osc-formatted into the osc listener crashes companion.

![image](https://user-images.githubusercontent.com/426386/105107537-a7c32b00-5ab8-11eb-80d2-cbb164c0f23c.png)

We should probably add some try-catch around the parsing of incoming osc messages :) Let's log the errors.

**Comment by josephdadams** [comment]
I did the thing.
