### ISSUE TITLE
[BUG] Bitfocus logo missing from main window on macOS builds

### ISSUE THREAD

**Issue by bryce-seifert** [bitfocus/companion#1379]
**Describe the bug**
The Bitfocus logo shows a broken image link on builds for macOS.

**To Reproduce**
1. Build companion (does appear this way in develop mode)
2. Open the main window

**Expected behavior**
Bitfocus logo appears.

**Screenshots**
<img width="403" alt="Screen Shot 2021-01-19 at 7 40 34 PM" src="https://user-images.githubusercontent.com/50299051/105115876-43d83c80-5a8f-11eb-96ae-b0b9530bd3a6.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.1
 - Browser n/a
 - Companion Version 2.20

**Comment by Julusian** [comment]
Should be fixed in build 2800
