### ISSUE TITLE
Blackmagic Design Smart Videohub 20 x 20 6G-SDI

### ISSUE THREAD

**Issue by shosho27** [bitfocus/companion#1382]
**Describe the feature**
The smartswitch interface doesn't allow a robust enough way to label buttons so you can easily see what you are switching and where it is going
**Usecases**
Be able to name a stream deck button so you know what product you are switching.  Allow custom icons and a way to mark where the routing is going

**Comment by josephdadams** [comment]
@shosho27 the videohub models are already supported in Companion. What exactly are you looking to do?

**Comment by shosho27** [comment]
Great!  I am looking to assign a name to the button so that I can route a
combination of inputs to one output and label the buttong
my best,
Shane A Shornock


*"The function of man is to live, not to exist.* "

~Jack London

**Comment by josephdadams** [comment]
Can you not just edit the button text to say what you want?

**Comment by josephdadams** [comment]
@shosho27 ?
