### ISSUE TITLE
Support for xkeys

### ISSUE THREAD

**Issue by JeffreyDavidsz** [bitfocus/companion#1386]
Instead of using a streamdeck, use an xkeys device

**Comment by stevespaw** [comment]
OK, I see this support (which is awesome) Any documentation? Feedback for lights etc?
I have a 124 T-bar here which seems to work but the keys are mapped in weird way. For example 1-8 are diagonal row from page one.  I assume that this only supports one page?

Thanks for your work on this!
Steve

**Comment by JeffreyDavidsz** [comment]
Looking for a place to put docu for this. Meanwhile you can set in surfaces the number of rows and columns. Try to do that (from top to bottom minus one). When you have the correct mapping, please let me know so I can make it a fixed setting for the 128. Also please report back what the ID mentioned. (XK-128?)
number 33 on your xkey is 2.1 (page 2 button 1)

**Comment by stevespaw** [comment]
Sorry typo XK-124. That is correct
![image](https://user-images.githubusercontent.com/11045430/106168644-245aa700-6154-11eb-82d3-393c7a5a6615.png)
And the setting minus 1 works better, but some weird repeating happens and the there is no "16" button for example

**Comment by JeffreyDavidsz** [comment]
Not really helpful. In the log you'll see the original xkeys key. From left to right what are the numbers. And top left top bottom what are the numbers?

**Comment by stevespaw** [comment]
What Log and how can I help?

**Comment by stevespaw** [comment]
OK Debug- 
![image](https://user-images.githubusercontent.com/11045430/106170702-579e3580-6156-11eb-9262-0b01aa49335a.png)

![image](https://user-images.githubusercontent.com/11045430/106170751-684eab80-6156-11eb-8b04-f625a9ed1187.png)

This happens when pressing button 16 on the top row

![image](https://user-images.githubusercontent.com/11045430/106170940-9e8c2b00-6156-11eb-9fe9-2fbedea4d0b0.png)
This with button one on top row.

**Comment by stevespaw** [comment]
BTW, I have both an Stream DeckXL and the XKE-124 on the same machine.

**Comment by stevespaw** [comment]
Also if we could get the T-Bat to work (with vMIx) this could be huge :-) . Can companion accept variable numbers coming from the T-Bar?

**Comment by JeffreyDavidsz** [comment]
Getting there but I ment all keys in row and column. The second key (top left one to the right) should be 8 for example with the xk-80 and colomns set to 7. If yours has a different number the colomns are wrong.
T-bar can be used

**Comment by JeffreyDavidsz** [comment]
I think keys per row should be 16

**Comment by stevespaw** [comment]
If I set it to 16 (yes it is a 16x8 matrix) then mapping is haywire. for example buttons 1-8 are diagonal-down from the top left.
I will post the debug screens in a few minutes.

**Comment by JeffreyDavidsz** [comment]
What is the second key when you press it?

**Comment by stevespaw** [comment]
This is me pressing Buttons 1-16 in top row starting from the left.
![image](https://user-images.githubusercontent.com/11045430/106178057-eadb6900-615e-11eb-937a-36dc357fc2fd.png)

This is the current setting, which would be right for the unit.
![image](https://user-images.githubusercontent.com/11045430/106178175-0e9eaf00-615f-11eb-8278-d84496a70cad.png)

**Comment by JeffreyDavidsz** [comment]
You did not try 16 and 7?

**Comment by stevespaw** [comment]
Ok I will now

**Comment by stevespaw** [comment]
now first row is perfect, but here is the second row - where it get wierd with repeats.
![image](https://user-images.githubusercontent.com/11045430/106178951-fc714080-615f-11eb-9a9b-428a438477e6.png)

**Comment by JeffreyDavidsz** [comment]
Ok so I need to check calculating mapping. Your keys are the same as the xk-80 only wider
The 7 should be correct (it starts at 0). But I think setting 15 by 7 won't do the trick. Thanks for the testing. I'll get back on this

**Comment by JeffreyDavidsz** [comment]
I think I have it worked out, but did some other alternations to, hopefully not breaking stuff ;-) You should now do a 16 x 8.
A new build is on its way.

**Comment by JeffreyDavidsz** [comment]
#1403 Let's finish the conversation in here
