### ISSUE TITLE
Enable/Disable actions

### ISSUE THREAD

**Issue by BasilChessman** [bitfocus/companion#1388]
The ability to disable an action would be great.   Currently, one must delete the action altogether.   An option to enable and disable any action would be much appreciated.  

Some buttons end up with numerous actions stacked.  Being able to disable specific actions without having to delete them would be a tremendous time saver.  

Additionally, the ability to set the enabled/disabled state of an action by an internal action or feedback option would be even better.   An example would be, if an instance feedback is true, then enable action, if false, then disable action.   Buttons could be utilized that wouldn't function unless the system was in a specific state.  There are many possibilities.

**Comment by stevespaw** [comment]
+1
I have been think about the same thing!

**Comment by shaunzyb** [comment]
+1 here!

**Comment by Akibakki** [comment]
+1  !!!

**Comment by Julusian** [comment]
The ability to manually enable/disable actions and feedbacks on buttons will be in 3.0.

I don't think that 'automating' this via actions is viable. We don't have a good way to identify actions, or to present the list of things that could be enabled/disabled from another action. Doing so will be complex and liable to break whenever the actions on the target button are edited.
I think that this kind of functionality would be better served by https://github.com/bitfocus/companion/issues/1052

**Comment by Suenee** [comment]
More complex description on #2233

**Comment by BryanCrotaz** [comment]
> The ability to manually enable/disable actions and feedbacks on buttons will be in 3.0.

I can't see how to disable an action in 3.0.0-rc2 - where should I be looking?

**Comment by istnv** [comment]
@BryanCrotaz 
![image](https://github.com/bitfocus/companion/assets/51003420/d131a4da-af8e-47ce-b52c-415c8c1927ba)
The green rectangle is a on/off toggle.

**Comment by BryanCrotaz** [comment]
> @BryanCrotaz 
> 
> ![image](https://github.com/bitfocus/companion/assets/51003420/d131a4da-af8e-47ce-b52c-415c8c1927ba)
> 
> The green rectangle is a on/off toggle.

How do I enable/disable based on a variable? Eg you can't pause a video if it's on air.

**Comment by istnv** [comment]
For that you will need a trigger and a couple of variables.
Rough outline:
One variable to toggle between 1 and 0 for On/Off air
Another variable that toggles between 1 and 0 for Pause/Play.
Set the trigger to only send the 'pause' command when Pause=1 and OnAir=0
Your button would set Pause to 1 on press, 0 on release.

**Comment by BryanCrotaz** [comment]
Yes that's the way I used to do it. Gets very complicated very quickly. Was hoping that enable/disable could be data driven.
