### ISSUE TITLE
Control multiple ATEMs simultaneously

### ISSUE THREAD

**Issue by jasonthetford** [bitfocus/companion#139]
It would be so great to be able to have multiple instances of BMD Atems to control 2 or more from one button. Currently if we try, the second one comes up as an error under Status. Much appreciated.

**Comment by haakonnessjoen** [comment]
Are you sure you are using the correct ip, that they are on the same subnet, with different ip's, etc? 

This person is not having any problems with it: https://www.facebook.com/groups/companion/permalink/2078352942383045/

**Comment by jasonthetford** [comment]
Thanks for the follow up! Kieran (from the video) and I have been working in this together. Yes, we reset the system and it’s working now. This is an incredible advance well done! We were working on other ways to control multiple machines, this is very simple.

Jason Thetford
0421 033 349
Sent from iPhone

On 2 Jul 2018, at 16:06, Håkon Nessjøen <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you sure you are using the correct ip, that they are on the same subnet, with different ip's, etc?

This person is not having any problems with it: https://www.facebook.com/groups/companion/permalink/2078352942383045/

**Comment by haakonnessjoen** [comment]
Seems to work :)
