### ISSUE TITLE
export / import not working correctly

### ISSUE THREAD

**Issue by alstergee** [bitfocus/companion#1390]
ive been moving my configs around a lot lately and when i import an exported full backup it forgets all of my page names, instances, and button commands

it also gives me this error:

24. 20:46:33 CORE(cb): db.tmp->db failed: Error: ENOENT: no such file or directory, rename 'C:\Users\alex\AppData\Roaming\companion\db.tmp' -> 'C:\Users\alex\AppData\Roaming\companion\db'
24. 19:11:19 CORE(cb): db.tmp->db failed: Error: ENOENT: no such file or directory, rename 'C:\Users\alex\AppData\Roaming\companion\db.tmp' -> 'C:\Users\alex\AppData\Roaming\companion\db'

 
i followed the instructions at the bottom of the page and restarted companion immediately after importing but no luck i have many many pages and buttons and putting "we know this is a problem" for several months with no timeline on a fix isnt exactly reassuring / doesnt help anything for the massive showflows im running here.

**Comment by JeffreyDavidsz** [comment]
Hi @alstergee as you are running massive showflows, you might consider to put a bounty on this. As programming is mostly done in free time of everyone, these kind of issues are easily put aside. If you want I can make a request at bountysource and you can fill in the amount of money you would like to spend to solve this. Let me know!

**Comment by fdebeer** [comment]
did you 
rename 'C:\Users\alex\AppData\Roaming\companion\db.tmp' -> 'C:\Users\alex\AppData\Roaming\companion\db'
?

**Comment by Julusian** [comment]
@alstergee those log lines are not really related to your problem.
It sounds like something is failing silently when it shouldn't but without more information (an export is always helpful) I dont think anything can be done.

In my testing recently, I have been finding the import to work fine, but I am not pushing it very hard yet

**Comment by Julusian** [comment]
Needs more information or an export to be able to do anything here
