### ISSUE TITLE
Accept UDP Termination Characters

### ISSUE THREAD

**Issue by jpooley-hearst** [bitfocus/companion#1396]
**Describe the feature**
Allow the UDP interface to handle termination characters such as CR (hex 13)

**Usecases**
ETC Eos Show Control (page 36): https://www.etcconnect.com/workarea/DownloadAsset.aspx?id=10737461372

**Comment by JeffreyDavidsz** [comment]
Did you try the generic-tcp-udp module? "Command End Character",
`	{ id: '',     label: 'None' },
	{ id: '\n',   label: 'LF - \\n (Common UNIX/Mac)' },
	{ id: '\r\n', label: 'CRLF - \\r\\n (Common Windows)' },
	{ id: '\r',   label: 'CR - \\r (Old MacOS)' },
	{ id: '\x00', label: 'NULL - \\x00 (Can happen)' },
	{ id: '\n\r', label: 'LFCR - \\n\\r (Just stupid)' },`

**Comment by jpooley-hearst** [comment]
Hey @JeffreyDavidsz, sorry for the imprecision, I'm referring to UDP Remote Control on port 51235 to control Companion externally

**Comment by JeffreyDavidsz** [comment]
Check, miss-read your question, companion uses the standard datagram sockets from node. [https://nodejs.org/api/dgram.html#dgram_event_message](https://nodejs.org/api/dgram.html#dgram_event_message). I would see this should work
