### ISSUE TITLE
Companion App Crashing at Open

### ISSUE THREAD

**Issue by KerithProduction** [bitfocus/companion#1398]
We recently downloaded the latest version of the companion app V2.1.2, Each time we open the app it is showing an IP Error message. About 3 seconds later the companion app crashes and closes down.

**To Reproduce**
1. Go to 'Applications'
2. Click on 'Companion.app'

The companion app will then seemingly boot up as normal but shortly after crash.

<img width="409" alt="Screenshot 2021-01-27 at 13 46 09" src="https://user-images.githubusercontent.com/78089278/106000533-d0de4f80-60a6-11eb-94c7-a65ee65ead87.png">

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.1
 - Browser Chrome
 - Companion Version 2.1.2

The IP Error it is showing is till showing the Correct IP address that was working prior to updating the app.

**Comment by JeffreyDavidsz** [comment]
Hint: there is a message that says: "Select another IP". Change the GUI interface to a valid IP

**Comment by KerithProduction** [comment]
> Hint: there is a message that says: "Select another IP". Change the GUI interface to a valid IP

The companion app isnt't open long enough to select anything, when you click to change the GUI interface the app crashes. Sorry if that wasn't clear, the issue is less the IP message and more than app crashing after 3 seconds of being open, and crashing after a click

**Comment by JeffreyDavidsz** [comment]
Strange, you might be able to delete the database, then you'll start from blank

**Comment by KerithProduction** [comment]
Anyone know where the database file(s) are stored on mac? Im hoping by deleting any of its settings/data and opening up fresh it will then load normally.

**Comment by josephdadams** [comment]
`~/Library/Application Support/companion/`

**Comment by KerithProduction** [comment]
> `~/Library/Application Support/companion/`

hmmm...iv got no companion folder in that location - nor is a spotlight search showing anything apart from the .app file itself! Really stuck!

**Comment by KerithProduction** [comment]
Done some further testing. The application seems to perform fine on a different account on the same computer. I then tried to copy the /applicationsupport/companion folder onto my other user account, but its still crashing after 2 seconds of launching.

**Comment by steffanhalv** [comment]
We´re having the same problem, deleting db works, but exporting old configs and reimporting gives this error:

Uncaught Exception:
TypeError: Cannot read property 'replace' of undefined
at data.inputs.forEach.input (/Applications/Companion 2.app/Contents/Resources/app.asar/lib/module/studiocoast-vmix/src/api.js:250:39)
at Array.forEach (<anonymous>)
at xml2js.parseString (/Applications/Companion 2.app/Contents/Resources/app.asar/lib/module/studiocoast-vmix/src/api.js:232:16)

**Comment by Julusian** [comment]
@steffanhalv try running a recent beta build. that particular issue has likely been fixed since 2.1.2

**Comment by Julusian** [comment]
@KerithProduction did you ever get to the bottom of this? If you are willing to share a copy of your database folder then I can get some more info on the cause
