### ISSUE TITLE
Buttons need to have a default style, and be creaed/enabled on first click?

### ISSUE THREAD

**Issue by nikb72** [bitfocus/companion#14]
When creating an Elgato button the text doesn't appear until a button style is selected.  feels as though it should have a base style that can be adjusted, rather than having no style until selected.

**Comment by willosof** [comment]
Very good point! But should they all be "enabled" by default? Or should they be enabled (the line and bank number change from gray to yellow) the first time you do something with it?

**Comment by willosof** [comment]
Hmmmm, I think I'm closing this for now. We'll keep it under concideration!
