### ISSUE TITLE
Touch Portal Integration

### ISSUE THREAD

**Issue by tome5789** [bitfocus/companion#1400]
Touch Portal

**Describe the feature**
A clear and concise description of what the feature does

I'd like to use Bitfocus Companion with Touch Portal instead of an Elgato Streamdeck product

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

I specifically need a large WIRELESS option for managing my ATEM Mini and other production programs. Elgato's mobile version has a fixed limit on how many buttons fit on a screen (it's the same on both an iPad and iPhone). An iPad is far more appropriate to have on camera with me and could be set up to have 50+ buttons on one page.

**Comment by josephdadams** [comment]
@tome5789 have you tried using the Companion tablet interface? I think there's a couple different versions there you could try.

**Comment by tome5789** [comment]
@josephdadams I'm pretty green at navigating these types of tech tools at this point and couldn't immediately find any info to read up on the tablet interface. Is there someplace where I could find more info about that?

**Comment by josephdadams** [comment]
When you open the Companion GUI, there are some links on the left: `Web Buttons`, and `Mobile Buttons`. These are the "tablet interfaces". Open those URLS on your tablet/touch screen device.

**Comment by josephdadams** [comment]
@tome5789 how did the tablet interfaces built into Companion work out for you?

**Comment by Julusian** [comment]
I imagine the support would need to be done on their side.
But I dont see any benefit to us supporting this. Time would be better spent on improving the tablet ui
