### ISSUE TITLE
[BUG] Cannot scroll down list of Connections

### ISSUE THREAD

**Issue by atscomms** [bitfocus/companion#1405]
**Describe the bug**
Just starting with Companion. When I open the list of Connections /Instances /category /manufacturer, the list runs down past the bottom of the browser window. When I attempt to scroll down past the bottom of the list, it stays in place while the page behind it scrolls instead.
I've tried it in the Firefox and Chrome browsers. I tried mousing down, the mouse /scroll wheel, the down arrow, and page down, all with the cursor hovering over the list and after clicking on it.

Windows 10 V 1909, i5 64bit CPU, Firefox 85.0, Chrome  88.0.4324.104.

Thank you

**Comment by josephdadams** [comment]
I don't feel like looking up the issue numbers, but this has been reported many times.
