### ISSUE TITLE
[BUG] Actions spontaneously moving position 

### ISSUE THREAD

**Issue by PhotoJoseph** [bitfocus/companion#1406]
I'm new here, but I don't think I'm doing this wrong. I have created a few buttons and am trying to edit them, but existing actions that I move up or down return back to where they were before once I select another button and come back to this one. 

Video attached showing this in action. I'm moving an **ATEM Mini: Set fairlight audio fader gain** from position two to position one, pushing **ATEM Mini: Set fairlight audio input mix option** into position two. As soon as I click on another button, and come back to this one, they have reverted to their original positions. I've seen this with several different actions now, and it's made it impossible to continue working.

https://user-images.githubusercontent.com/78106443/106216529-2e969880-6188-11eb-9ca7-82d97cf4813d.mp4

**To Reproduce**
I have added some random actions to a new button and seen it happen again but it's not consistent. But I have seen it happen with a brand new button, adding just two commands, and repositioning them.

**Desktop**
 - OS: macOS 11.1 Big Sur on Mac Pro
 - Browser both Chrome and Safari
 - Companion Version 2.1.2 and 2.2.0beta

**Additional context**
I exported and imported the configuration to another computer, an M1 MacBook Air, and got the same issue. I also tried on an older, non Big Sur Mac… same issue. I wonder if it has anything to do with having dual ATEMs? 

<img width="657" alt="dual-ATEMs" src="https://user-images.githubusercontent.com/78106443/106217269-c052d580-6189-11eb-8aee-df07aea8ab8a.png">

This is obviously not a common bug, or it'd be all over the place. It must have something to do with my configuration.

**Comment by kraves-oz** [comment]
Yep Atem instances shouldn't matter (provided you have different IP addresses of course).  Looks like you're only interacting with the mini in this example anyway.  

If you're on FB this would be a good question to discuss on the companion users group. 

Kyle.

**Comment by PhotoJoseph** [comment]
The other ATEM is elsewhere in that string, but yes, even with just the one in place, it can happen. And yes, definitely different IP addresses. I'll head to Facebook. I also already posted in the slack group.

**Comment by Julusian** [comment]
The action ordering is completely unaware/independent of the instance type, so it shouldnt matter that they are both atems.

Could you share your config, either here or send it to git@julusian.co.uk. You can either export the whole config, or a single page might be enough. I suspect that something in your config has gotten messed up and is confusing things, in which case it will be an easy fix once I know the issue

**Comment by PhotoJoseph** [comment]
Of course… attached here. I was thinking I'd start from scratch this morning (this only has a couple of buttons; as I mentioned I just started) so it's not a big deal to have to start over, but it's a little disconcerting if the configuration broke after just a day of work.

Thank you!!

[PhotoJosephs-Mac-Pro-E_full-config_20210128-1625.companionconfig.zip](https://github.com/bitfocus/companion/files/5894356/PhotoJosephs-Mac-Pro-E_full-config_20210128-1625.companionconfig.zip)

**Comment by PhotoJoseph** [comment]
User David MacLeod in the Facebook group has noticed the same thing, and he also has multiple instances of ATEMs, so that could be a trigger? https://www.facebook.com/groups/companion/permalink/2792004851017847/

<img width="524" alt="David MacLeod Facebook" src="https://user-images.githubusercontent.com/78106443/106303644-36e5e680-620f-11eb-9a22-bf92b968a960.png">

**Comment by Julusian** [comment]
From a quick look at your config file I can see the problem.
Button 1.3 starts like this:
```
            "3": [{
                "id": "l5VFbjiji",
                "label": "+ Add key down/on action",
                "instance": "+ Add key down/on action",
                "options": {}
            }, {
                "id": "xtwO6QBQe",
                "label": "+ Add key down/on action",
                "instance": "+ Add key down/on action",
                "options": {}
            }, {
                "id": "kO8lZmopJ",
                "label": "+ Add key down/on action",
                "instance": "+ Add key down/on action",
                "options": {}
            }, {
                "id": "UphRkW5cE",
                "label": "+ Add key down/on action",
                "instance": "+ Add key down/on action",
                "options": {}
            }, {
                "id": "QvQGCpLtC",
                "label": "XXMS1cCnU:fairlightAudioMixOption",
                "instance": "XXMS1cCnU",
                "action": "fairlightAudioMixOption",
                "options": {
                    "input": "1302",
                    "source": "-65280",
                    "option": "2"
                }
            }, {
```

Those '+ Add key down/on action' should not be there, and invalid actions is what I was expecting to see.
The ui logic is being a bit to naive here, and simply ignores those actions as the instance is invalid and they should never exist.
And the reorder logic outputs number based on what gets shown in the ui. So when you drop an action after the mixOption shown above, that will tell the backend to insert at index 1, which means it will end up after the first of those invalid actions.

So there are a three things to fix here, which will all be quite quick:
* At startup do a quick scan through the all the actions and ensure they are all valid
* When adding an action, make sure it is valid
* Fix the ui logic to calculate the correct indexes

**Comment by PhotoJoseph** [comment]
@Julusian, wow…

A) This is fantastic that you were able to identify it. Thank you. It almost makes sense to me. But…
B) I have absolutely NO idea what you're telling me to do ;-) 

> At startup do a quick scan through the all the actions and ensure they are all valid

Do you mean that there's a validity scan process to run in the service, or do you mean to just visually scan (look) at the actions to ensure they are what I expect? If the later; they are. 

> When adding an action, make sure it is valid

How do I do that? I have a sense this has happened because of the other problem I noted, where quite often when I add an action, it doesn't add. So I have to search and select it again. In fact it's nearly every time, I have to add an action twice for it to show up. It doesn't matter if I select it by clicking with the mouse or arrow-keying to it and hitting Return; it's almost always the same experience.

> Fix the ui logic to calculate the correct indexes

Gesundheit. 😬 Sorry, how? 

And if my assumption of how these may have gotten there isn't right, how do you think these got there, and more importantly, how do I avoid them happening again?

**Comment by Julusian** [comment]
@PhotoJoseph dont worry, Im not expecting you to do anything here, those are notes for me for when I am fixing it (and for future reference).
I shall get onto this soon, so expect a build with a fix hopefully tonight :)

**Comment by PhotoJoseph** [comment]
oh LOL thank you @Julusian — shows you how experienced I am here ;-) Thank you again!!

**Comment by Julusian** [comment]
Itll take a few minutes for the build to appear, but build `0cf8483-2832` should resolve this

**Comment by PhotoJoseph** [comment]
Amazing, I'll jump right on it. Should it repair the damage done to the config, or will I need to start over?

**Comment by Julusian** [comment]
It will repair your existing config

**Comment by PhotoJoseph** [comment]
woohoo! I can rearrange! This is after one single test, and I will follow up again later after I've worked with it for a while, but THANK YOU. This is amazing.

**Comment by PhotoJoseph** [comment]
Looks like this is definitely addressed. I spent (far too much time LOL) on Friday working on this and didn't have a single rearrangement problem. Thank you again!!
