### ISSUE TITLE
{BUG} Module "Null" Status, cannot edit, unusable

### ISSUE THREAD

**Issue by silentt45** [bitfocus/companion#1408]
Programming companion all of yesterday. Came back on this morning and none of the buttons I programmed were working. Looked at the GUI, showed my atem module as "null". Every time I try to edit the instance, or edit a button, I get a javascript error window that says cannot read instance of null. I am version 2.2.0.

**Comment by Julusian** [comment]
This sounds like a similar to https://github.com/bitfocus/companion/issues/1406? of having invalid entries in the array of actions, so should be fixed in the same way at the same time

**Comment by Julusian** [comment]
Itll take a few minutes for the build to appear, but build `0cf8483-2832` should resolve at least the error dialog

**Comment by silentt45** [comment]
Dope. I’ll give the new build a try tomorrow morning.

**Comment by silentt45** [comment]
0cf8483-2832 fixed the issue
