### ISSUE TITLE
403 Forbidden on builds.bitfocus.io/companion/stable/

### ISSUE THREAD

**Issue by nytamin** [bitfocus/companion#141]
Currently, everything below
https://builds.bitfocus.io/companion/stable/
returns 403 Forbidden.

This includes the stable builds linked from the latest stable release:
Mac build:
https://builds.bitfocus.io/companion/stable/companion-1.1.0-7326dd1-osx.zip
Windows build
https://builds.bitfocus.io/companion/stable/companion-1.1.0-7326dd1-win64.exe
Linux build
https://builds.bitfocus.io/companion/stable/companion-1.1.0-7326dd1-linux.tar.gz

**Comment by willosof** [comment]
This should be fixded now @nytamin. Sorry abut that :)
