### ISSUE TITLE
XK-24 Issue

### ISSUE THREAD

**Issue by matt-hand** [bitfocus/companion#1410]
Just found the X-Keys support in build 2830. It looks like there may be a mapping issue. [Here is a video](https://youtu.be/0gqcoNOqCsk) to better demonstrate what may be up.

**Comment by matt-hand** [comment]
I realized I forgot to mention this is running on a Mac.

**Comment by JeffreyDavidsz** [comment]
Looks like you are running not the latest? I did a new calculation of the buttons as the previous build had one variable fixed Build 2828 and up should have this. If you have a newer build, let me know

**Comment by JeffreyDavidsz** [comment]
Mmm wait, your xkeys seems of, the log is helping me. Try 4x8. XKEYS is somehow counting top to bottom and then left to right. I see that your second button is actually 8. So xkeys is still pretending like a XK-80 or XK-60 (which has 10x8).

**Comment by JeffreyDavidsz** [comment]
If that works better could you post again a video hitting each button? That will show which button you don't have

**Comment by matt-hand** [comment]
Fixed it - [https://www.youtube.com/watch?v=XJZG6q1QDOk](url) This is pretty exciting. I am expecting that the buttons page will need to have a bit of a redesign now as there are a bunch more options for xKeys. This is pretty exciting and let me know how I can best support this development.

**Comment by JeffreyDavidsz** [comment]
Great! Well if you have a spare device and located in Europe ;-)

**Comment by matt-hand** [comment]
Alas... :(
