### ISSUE TITLE
[BUG] Linux: Elgato Stream Deck USB connection lost on suspend/resume

### ISSUE THREAD

**Issue by osbama** [bitfocus/companion#1413]
**Describe the bug**
Whenever the system goes to sleep, I need to go to companion app, and rescan the USB

**To Reproduce**
1) I am launching the headless.js using gnome's autostart. So everything runs on the user side.
2) System goes to a deep sleep (but not hibernate).
3) When the system turns back on, Stream Deck is restored with Companion screen.
4) When I reach the GUI stage, Stream Deck goes blank 
5) The companion app seems to loose connection with Stream Deck. I need to do a "rescan usb" to connect to stream deck again 

**Expected behavior**
Connection with stream deck restored automatically after a sleep/restore cycle without manual intervention. 

**Desktop (please complete the following information):**
 - Xubuntu 20.02LTS, (modified to run Gnome + Pop!_shell) 
 -  Firefox 
 - Companion experimental (pulled from git on 30/01/21)
 - AMD5600 + X570

**Additional context**
Stream Deck is connected via 1)USB switch 2) USB hub. The switch allows me to switch between two computers, however has a huge time penalty when initialising.

**Comment by TopNotchProgrammer** [comment]
I have the same issue on debian 11

**Comment by Julusian** [comment]
I think this will be best solved by #481
