### ISSUE TITLE
Warning after reboot: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by AndrewApi** [bitfocus/companion#1414]
Hi All

I am getting this warning each time after a reboot of the pi, latest build updated today any ideas to stop it?

30. 20:56:34 CORE(cb): db.tmp->db failed: Error: ENOENT: no such file or directory, rename '/home/pi/companion//db.tmp' -> '/home/pi/companion//db'

**Comment by Julusian** [comment]
This should be solved in the recent betas

**Comment by AndrewApi** [comment]
Great thank you.
