### ISSUE TITLE
[BUG] official Streamdeck extension for companion glitches.

### ISSUE THREAD

**Issue by DachsbauTV** [bitfocus/companion#1418]
**Describe the bug**
Hi guys, 
I was just trying out the new official Streamdeck extension to use companion alongside the regular app (was using just companion until now) and I am encountering glitches on my Streamdeck XL as soon as both apps are running. 

Anyone an idea what could cause this? Or who programmed the extension? 

**Screenshots**
see video https://1drv.ms/v/s!Am_KZ41SE1lKgfNh_sKEHtz1vLQIIA

**Desktop (please complete the following information):**
 - OS: WIN 10 x64 2004
- using latest Streamdeck version and Companion builds 2.2.0 2817

**Comment by Julusian** [comment]
This no longer has enough detail to work from. Please report back if it is still an issue

**Comment by DachsbauTV** [comment]
No worries, one seems to care anyways ;) I don't think many people use this extension anymore
