### ISSUE TITLE
[BUG] Preset loading often fails when web UI reconnects to restarted server process

### ISSUE THREAD

**Issue by depili** [bitfocus/companion#1419]
Tested on 53152478ac50145e75bf516e3c16133e6f32a738 and e61129312788218dd8e2f0ecb9fe427093935fbe of companion module depili-clock-8001

This one is bound to be Fun one to track down.

Currently I am running to a issue, where sometimes the presets aren't getting loaded at all when there are buttons with utf8 glyphs that aren't supported by some parts of the system. In my case this happens when I have buttons using feedback variables as labels in the preset set and on the button setup and the feedback variable contains glyphs ⏸︎ or Ⅱ that I'm using for icons to denote paused state for timers. 

The issue seems to happen if the clock state update via OSC happens before the presets get populated, which in my case seems to be about 5 out of 6 restarts of companion.

A simple way to get into this error state is to edit https://github.com/bitfocus/companion-module-depili-clock-8001/blob/v4_refactor/clock.js#L30-L33 on the module and change the initialized state to `active: true` and `icon: '⏸︎'`

The web UI log doesn't seem to contain any errors, the yarn dev output has the following which is probably relevant:
```
lib/image trying to draw a character that doesnt exist in the font: 65038 ︎ +26ms
lib/image trying to draw a character that doesnt exist in the font: 65038 ︎ +1ms
lib/image trying to draw a character that doesnt exist in the font: 65038 ︎ +0ms
lib/image trying to draw a character that doesnt exist in the font: 65038 ︎ +0ms
lib/image trying to draw a character that doesnt exist in the font: 65038 ︎ +0ms
lib/image trying to draw a character that doesnt exist in the font: 65038 ︎ +0ms
```

Weirdly ⏸︎ works both in the web UI buttons and in the streamdeck buttons, so it exists in the font and the error refers to unicode variation selector, not the pause symbol: https://www.compart.com/en/unicode/U+FE0E

**Comment by depili** [comment]
Actually digging deeper the utf8 glyph is a red herring, the real issue is that if you have a browser window already open on the admin page and restart the companion server process the presets are occasionally missing from the initial loaded in state after reconnect.

Refreshing the admin page will show the presets.

**Comment by Julusian** [comment]
I often find that the list of known modules fails to load, this should be improved on by #1402 I dont think it worth doing anything before then

**Comment by Julusian** [comment]
I think this is behaving better now. Let me know if it is not
