### ISSUE TITLE
Button links when holding 4 on the top row and 1 on the next row

### ISSUE THREAD

**Issue by Jonathan-Tech1** [bitfocus/companion#1422]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Companion Version [e.g. 2.0]

**Additional context**

**Comment by BasilChessman** [comment]
I saw this reported on FB.  Here is a link to the thread with a video demonstrating the behavior.  I was able to duplicated the behavior on my SDs also.

https://www.facebook.com/groups/streamdeckusers/permalink/2982449758642621/

**Comment by josephdadams** [comment]
It looks like this video is only viewable if you are a member of that group. Please consider re-posting the video here.

**Comment by istnv** [comment]
I took a look at this. Companion is getting 'pressed' and 'release' messages from the ghost key. I think it may be an artifact of the way the devices are built. Almost any 3 buttons will trigger the 4th in a square pattern.

**Comment by Jonathan-Tech1** [comment]
https://photos.app.goo.gl/esqUFYSMtSgDs6YAA

**Comment by istnv** [comment]
My testing shows the usb driver (or streamdeck) is _telling_ Companion that those buttons are being pushed.
It is not companion that is ghosting the buttons and there is nothing in the message from the driver that this is a 'fake' button. Try an XL, there are more combinations that will cause phantom buttons.

**Comment by dnmeid** [comment]
Confirmed, that this is the normal behaviour of the stream deck. It is an ghosting issue from matrix scanning the button presses and we can't do anything about it.
Recommendation is to carefully distribute buttons you want to be able to push at the same time.
