### ISSUE TITLE
[BUG] Page up/down buttons do not perform actions after edit on Web/Mobile buttons

### ISSUE THREAD

**Issue by yellowjaguar5** [bitfocus/companion#1431]
**Describe the bug**
After replacing a page up or down button, new actions are not performed. Instead, the page up/down action occurs. Only tested on Web/Mobile buttons.

**To Reproduce**
1. Erase the page up (x.1) and/or page down (x.17) buttons 
2. Add new key up or key down action
2. Open Web or Mobile buttons
3. Tap on edited button
--> New actions are not performed. Instead, page up or page down occurs (same action as default)

**Expected behavior**
These buttons should perform their new actions after being edited.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G95)
 - Browser: Chrome on Mac and Safari on iOS
 - Companion Version: 2.2.0.14.6 (18G95)

**Comment by Julusian** [comment]
Which tablet page type is this with?
I think only tablet2 supports the page buttons and that is done by defining which buttons are the page buttons in the config within that tablet page

**Comment by yellowjaguar5** [comment]
I just tested again and this bug is only present with `tablet2` when the up OR down button is modified, but not both.
