### ISSUE TITLE
[BUG] When using X-Keys wrong button IDs are associated with keypresses

### ISSUE THREAD

**Issue by JustAddSoftware** [bitfocus/companion#1432]
**Describe the bug**
I have an X-Keys XK-24 connected.  I assume the upper left key is 1.1.  However, when I press that key, Companion reports the press as 2.1.  When I release the key, Companion reports the release as 1.1.  The second key in the first row is reported as 1.10.  The third key is reported as 1.19.  The fourth key in the row does nothing.  All of the keys are not reporting the correct row and column as one would expect.

Here's a copy of the logs from pressing all the keys.  First press is at the bottom.  That's the upper left key which should be 1.1.  I then go across the top row.  Then down to the next row, etc.  I don't think all keys are registering.  Definitely the keys in column 4 are not.  I have companion set up for 4 buttons per row and 6 buttons per column. 

14. 16:42:18 device(XK-24): Button 1.16 released
14. 16:42:18 device(XK-24): Button 1.16 pressed
14. 16:42:17 device(XK-24): Button 1.7 released
14. 16:42:16 device(XK-24): Button 1.7 pressed
14. 16:42:16 device(XK-24): Button 1.21 released
14. 16:42:16 device(XK-24): Button 1.21 pressed
14. 16:42:14 device(XK-24): Button 1.12 released
14. 16:42:14 device(XK-24): Button 1.12 pressed
14. 16:42:13 device(XK-24): Button 1.3 released
14. 16:42:13 device(XK-24): Button 1.3 pressed
14. 16:42:12 device(XK-24): Button 1.17 released
14. 16:42:11 device(XK-24): Button 99.17 pressed
14. 16:42:09 device(XK-24): Button 1.8 released
14. 16:42:09 device(XK-24): Button 1.8 pressed
14. 16:42:09 device(XK-24): Button 1.22 released
14. 16:42:08 device(XK-24): Button 1.22 pressed
14. 16:42:08 device(XK-24): Button 1.13 released
14. 16:42:08 device(XK-24): Button 1.13 pressed
14. 16:42:06 device(XK-24): Button 1.4 released
14. 16:42:06 device(XK-24): Button 1.4 pressed
14. 16:42:06 device(XK-24): Button 1.18 released
14. 16:42:05 device(XK-24): Button 1.18 pressed
14. 16:42:05 device(XK-24): Button 1.9 released
14. 16:42:05 device(XK-24): Button 1.9 pressed
14. 16:42:03 device(XK-24): Button 1.23 released
14. 16:42:03 device(XK-24): Button 1.23 pressed
14. 16:42:03 device(XK-24): Button 1.14 released
14. 16:42:03 device(XK-24): Button 1.14 pressed
14. 16:42:02 device(XK-24): Button 1.5 released
14. 16:42:02 device(XK-24): Button 1.5 pressed
14. 16:42:01 device(XK-24): Button 1.19 released
14. 16:42:01 device(XK-24): Button 1.19 pressed
14. 16:42:00 device(XK-24): Button 1.10 released
14. 16:42:00 device(XK-24): Button 1.10 pressed
14. 16:41:59 device(XK-24): Button 1.1 released
14. 16:41:59 device(XK-24): Button 2.1 pressed
**To Reproduce**

1.) Connect an X-Keys devices
2.) Set the log in Companion to Debug
3.) Start pressing keys

**Expected behavior**
That key 1.1 is in the upper left, key 1.2 is next to that, etc.

**Screenshots**
See the log above.

**Desktop (please complete the following information):**
 - OS: OS X Big Sur
 - Browser: Safari
 - Companion Version: 2.2.0-5cf0303-2872

**Comment by JeffreyDavidsz** [comment]
Hi @JustAddSoftware Go to the settings of the xkeys (look for surfaces) and adjust the row and column settings to your xkeys. Should be 4 and 8. Looks like the model is not set correctly (standard is 10 buttons in a row). So slide the numbers to the correct position (is they are already let me know but still slide).

**Comment by JeffreyDavidsz** [comment]
Sorry missed this comment " I have companion set up for 4 buttons per row and 6 buttons per column." Try 8 buttons per column, it's the way xkeys are build

**Comment by JustAddSoftware** [comment]
But I don’t have 8 buttons. There are numerous X-Keys models. I gave you my model number. You should not force people to use a specific format. Otherwise why have the adjustments in there?  That’s a huge bug. And regardless, adding a couple extra rows per column should not cause entire columns not to work or the very first button to register one value when pressed and a different when released. It sounds like this module was written for one specific purpose and not for any kinds of use. There are X-Keys models with two rows and 16 columns. This needs to work with all models to be useful.

**Comment by JustAddSoftware** [comment]
So I have set X-Keys now to 8 buttons per column.  It does work far better, but still one very big problem.  When you press the first button, it reports Key 2-1 has been pressed.  When you release it then it say key 1-1 was released.  That is a serious problem.

This whole column issue really needs to be fixed as well.  Like I said, assuming everyone has an 8 button per column X-Keys unit is not a wise way to program.  And if you are going to put controls in a module where changing those controls breaks your functionality then probably best not to put those controls in there.  You either allow people to use it in whatever configuration they have and adjust accordingly or you don't allow anyone to adjust anything.  Sorry if this sounds harsh but as I write my software, my customers expect me to provide something that works with whatever controls I put in place.

**Comment by JeffreyDavidsz** [comment]
Hi @JustAddSoftware I feel offended by your comments. Do feel free to submit a pull request to improve things. 
I have used a 24, 64 tbar jog and 80 device to test with. I noticed that the 24 uses the same number of column's as the 80. This should be set automatically on connecting to the right settings. Did you try first or did you change it right away? 
Do not forget you are running test builds, so errors can occur and reporting them will improve it. Regarding to the keypress, that seems to be a logging issue which I did not figure out yet.
So for now when models have wrong mapping for buttons I can see at the second button from top left if there is any issue with missing buttons.

**Comment by McHauge** [comment]
@JustAddSoftware Yes what you wrote does sound very harsh, please keep in mind this is an open-source project, and most if not all work is done in the free time. Also, this is the FIRST beta with X-keys support, you should not expect it to be ready for production use before an actual RELEASE version. @JeffreyDavidsz probably doesn't have 10-20 different units to test on, so this should instead be a collaborative process with testing done by whoever wants to contribute, and who has an X-Key to test with.
I would not expect this to be used in any production set for at least 2-3 months. Only in test setups, and on verified/tested units.

If you have something to help improve it please post a pull request.

**Comment by JustAddSoftware** [comment]
I understand it’s a beta process right now.  I am happy to help report and help test anything needed.  But as this is a bug report, I’m trying to state specifically what I am seeing when using the software.  @JeffreyDavidsz reply to me seemed to indicate that you had to have it a certain way and that I was using it incorrectly.  I’m not trying to be mean when I say it doesn’t work or that if you only expect people to use it one way then you should not put in a way to adjust the rows/columns.  I’m perfectly fine with him or anyone coming back and saying, “Yeah, I get that it doesn’t work that way now.  We will fix that for the future.”  But unless I am reading Jeffrey’s response incorrectly, he says pretty matter of fact that “this is the way it is built.”

I am sorry you feel offended, Jeffrey.  However, I could have just not said anything and just decided not to test this at all.

I’m not sure what a “pull request” is.  Yes, I would like to help make this better, so how can I help?

Thanks,

Jon

-------------------------------------
Jon Ogden
Just Add Software

When you want it to work...Just Add Software!

Webpage: http://www.justaddsoftware.net

"Discovery consists of seeing what everybody has seen and thinking what nobody has thought."
                                                                                                           - Albert von Szent-Gyorgyi

**Comment by JeffreyDavidsz** [comment]
The update needs improvement. Unfortunately every model of xkeys responses different, so keeping all models in check is a thing. My initial reply was a bit sort as I was trying to help you while on the road. Within a few weeks more models will be added and functionality will be added. I'll need to look at the bugs to. 
So reporting them will help.

**Comment by JustAddSoftware** [comment]
Thank you.  Please let me know how I can help.  I only have the one XK-24 model.  But I can see uses for some of the other models with my application.  It’s exciting to see this added.  I’m not trying to make you feel bad.  And I know what beta testing is all about.  I’ve done it for some pretty big brands.  I can just come off a little bit overbearing.

-------------------------------------
Jon Ogden
Just Add Software

When you want it to work...Just Add Software!

Webpage: http://www.justaddsoftware.net

"It takes as much stress to be a success as it does to be a failure."
                                                                                        - Emilio James Trujillo

**Comment by JeffreyDavidsz** [comment]
So figured it out (I think), on your first button is a page change right? Same goes for button 17. The change is for page up so hats why 2, the other is for page down that page 99. As I don't do anything with those buttons it can be ignored. I just need to figure out how to filter the page buttons

**Comment by JustAddSoftware** [comment]
So if I look at the button layout that Companion provides, it’s 4 rows by 8 column.  It looks like the image below which I hope comes through.  Probably pretty standard.

So yeah, I guess the upper left button is “up” but I’ve not done any programming for that.  And I wouldn’t necessarily want that as I’d want to do my own layout once I need to start paging up and down.  Interestingly enough, I just changed the 1.1 button type to a “regular button” and now the button is reporting 1.1 properly.

So thank you for letting me know this.  

So is “up” the automatically programmed by companion?  

But I see a “challenge” - the layout below of 32 buttons represents a StreamDeck.  However, in the case of X-Keys the layout is different.  In your default settings, it is turned 90 degrees - 4 columns and 8 rows (mine is 4 columns and 6 rows).  So the mapping of the image below will rapidly become incorrect.  That’s not your fault, but just the way companion assumes the buttons are.  For example, in the image below, the “Page 1” button that is 1st column, second row is actually 1st column, 3rd row on the XKeys unit.  So there’s a physical mapping difference.  I just tried changing button 1.7 to a Page up button and when I do, then the log is showing button 2.7 is being pressed.  So I don’t know if it is working right or not as I do not have more than one page of buttons at this point. 

I don’t know how the mapping goes, but it seems to me that it might be best to just simply map x.1 as the upper left and then just keep adding numbers until you get to the maximum number of buttons on the particular pad.  In your case, it is 32 buttons.  In my case it is 24.  So while Companion would expect there to be buttons for 1-25 to 1-32 in my case, I wouldn’t have them.  If I programmed those buttons then they would be available only in the virtual panels and not on my XKeys.  I don’t know if that can be done or not.

I hope this feedback helps…

Thanks,

Jon



-------------------------------------
Jon Ogden
Just Add Software

When you want it to work...Just Add Software!

Webpage: http://www.justaddsoftware.net <http://www.justaddsoftware.net/>

"Your most unhappy customers are your greatest source of learning"
                                                                                           - Bill Gates

**Comment by JeffreyDavidsz** [comment]
Hi Jon,feedback always helps me to see how others think. 
1) when you use xkeys remove the standard page up/down/index keys in the GUI (yes they are standard)
2) Streamdeck having 4x8 is totally coincidentally with the XK-24 mapping of 32 buttons. Or seemingly being 90 degrees turned. Somehow while the XK-24 has 24 keys it behave s as it has 32 keys (4 columns 8 rows). I fixed this now by doing a button max/button row. But I need to be sure other models behavior is the same.
3) what you are suggesting is exactly what I made. I start from left up being x.1 going from left to right, top to bottom. But when you hit key 33 (if you have like a XK-80) x.33 does not exist in Companion world, so it translates it to nextpage.1
4) I think we are in line of understanding now, so would you have a look at the wiki on github. I've created a page with some explanation, do you have any additions there?
5) when I find the time I'll create a extra emulator for the xkeys showing which button is where.

**Comment by JustAddSoftware** [comment]
See my comments below.

> On Feb 18, 2021, at 1:17 AM, Jeffrey Davidsz <notifications@github.com> wrote:
> 
> 
> Hi Jon,feedback always helps me to see how others think.
> 
> when you use xkeys remove the standard page up/down/index keys in the GUI (yes they are standard)

Are you saying this is what should be done?  What if you want to change pages?  Right now I don’t but…

> Streamdeck having 4x8 is totally coincidentally with the XK-24 mapping of 32 buttons. Or seemingly being 90 degrees turned. Somehow while the XK-24 has 24 keys it behave s as it has 32 keys (4 columns 8 rows). I fixed this now by doing a button max/button row. But I need to be sure other models behavior is the same.

I wonder if the XK-24 vs. the XK-32 has the same internal hardware but just fewer keys.  So it looks to software like it has 32 keys but doesn’t.


Now here’s a twist that I am not sure if there’s anything that can be done or not.  XKeys has the ability to create “Large” buttons that are two or more button positions.  WIth the XK-24 that I have, I also have unused, three “large” button covers.  They give you a tool to pop off the button covers and then this large one could go down in place of two of them.  It’s not a feature I am using at this time, but it’s certainly something people may want to use.  That may be difficult to map to and maybe should be a feature request for the future.  I just wanted to let you know that there is that twist in things as well if you didn’t know already…  :)

> what you are suggesting is exactly what I made. I start from left up being x.1 going from left to right, top to bottom. But when you hit key 33 (if you have like a XK-80) x.33 does not exist in Companion world, so it translates it to nextpage.1
That’s a good idea...

> I think we are in line of understanding now, so would you have a look at the wiki on github. I've created a page with some explanation, do you have any additions there?

I will take a look at it.
> when I find the time I'll create a extra emulator for the xkeys showing which button is where.
Wow.  Cool.

**Comment by michaelhatPIengineering** [comment]
I am not sure if it is appropriate for manufacturer to comment, so if not tell me to go away.

Else we are happy to answer any questions. 

The effort you are putting into making X-keys work with Companion is much appreciated. We think the project is really great. I fully understand the difficulties. 

Companion’s original control surface interface was for the 3 StreamDeck models, and the UI for that is very well done. 

Moving from the finite number of 3 surfaces, to the more infinite number of buttons or other control levers X-keys and other broadcast controllers could have is not an easy task. 

An explanation, (not a justification) of how and why the X-keys buttons work that way they do, is that the USB messages from the X-keys are pretty fundamental. Each time a button is pressed or released the X-keys sends a new message with the current state of all buttons. This message mainly consists of a byte for each column, and each bit in that byte represents one key (row) in that column. These messages are “state based” meaning they always report the current state of all keys, this prevents “stuck” or missed keys as the next message will clear the last if it is lost. 

To further complicate things, on the actual PCB the switches are actually connected by wires in more less a row and column format. But some products, very wide short ones for example, may not have those wires connected the same pattern as the physical switches are arranged on the board. In those cases, we still report groups of bytes, and bits, and even deceptively, call them rows and columns in our descriptor. 

So while it makes perfect sense to the hardware engineer because the microprocessor has 8 pin ports, to make a 24 key device , 4 columns, and 8 rows (not using the last 2)  and the raw message is just the switch closures on those wires. This does not make sense to all normal human beings. (my wife is that hardware engineer, she thinks counting starting at 0 is natural and going from top to bottom is ok, and NO, I do not bring up this deeply controversial subject at dinner)  

The SteamDeck API is an additional layer of software that helps manage the input and output to the USB device. 

The X-keys messages are presented to the developer directly from the raw USB data. I am not really proud of the complication that this causes; it does require another layer of translation to make the button numbers logical to normal humans. 

Jeffrey, if you need some actual hardware or other ways to make sure your development is productive and easier please send me a direct email.

**Comment by JustAddSoftware** [comment]
Michael,

I loved that you jumped in here to make some comments.  That’s great!  So basically you seem to be confirming what Jeffrey pointed out that XK-24 is really reporting 32 total positions even though there’s just 24 buttons (ie: 4 x 8).

And I thought that only software engineers started counting at zero as an item.  :)

Jon

-------------------------------------
Jon Ogden
Just Add Software

When you want it to work...Just Add Software!

Webpage: http://www.justaddsoftware.net

"Discovery consists of seeing what everybody has seen and thinking what nobody has thought."
                                                                                                           - Albert von Szent-Gyorgyi

**Comment by JeffreyDavidsz** [comment]
Hi Michael, thanks for taking the time to explain a bit more! There are two things I would like to do, write the translation of the HID information myself (using a existing node library at the moment) and create a GUI like the emulator to give a representative view of the button mapping. Sending all button information is actually a smart move! especially for checking stuff.
One question for you: the translation to buttons now is calculating the right numbers of buttons in rows and columns. For the xkeys I do a max number devided by rows (32/4). Then it maps out perfectly, but will this work on a 8x1 for example? The maxnumber is a preconfigure value from the middle ware. I would like to get it out of the HID connection though.
I'm in direct contact with Maggie and she send me a device to test on, which is great!
We will keep in touch!

**Comment by michaelhatPIengineering** [comment]
@JustAddSoftware   Well, more or less, the XK-24 reports, 4 bytes of raw data, 2 of the bits in each byte are always 0.  So without further knowledge of the devices it would not be possible to know how many actual switches there are on that specific unit. Of course those 0 bits would never be triggered for a 24 key device. 

We do document all the products here:
https://xkeys.com/software/developer/developerhiddatareports.html

But I would like to also help further some projects that try to support all our products such as this one and the nodeJS  xkeys project that superflyTV is working on.

**Comment by JeffreyDavidsz** [comment]
That's the project in using now to translate the HID hex into keypresses. First problem was that the XK64jogtbar wasn't in the config, which made the xkeys not being recognized. I made a pull request for it, but I'm missing some other things also. I have the full SDK data, so it might be better to write the driver myself.

**Comment by JustAddSoftware** [comment]
So that explains then when I set the rows and columns in Jeffrey’s module to 6 x 4, why the whole thing goes nuts and values get reported very strangely.

-------------------------------------
Jon Ogden
Just Add Software

When you want it to work...Just Add Software!

Webpage: http://www.justaddsoftware.net

"Always forgive your enemies; nothing annoys them so much."
                                                                               - Oscar Wilde

**Comment by michaelhatPIengineering** [comment]
@JeffreyDavidsz, state based messaging is critical at the raw usb level, and how the keyboard and mouse work as well. It is even more important for mission critical remote control, but I will discuss more on your VICREO-Listener project. 

As far as the 1 row devices, the "stick keys" they are a bit trickier, in that case we needed to minimize the wires going down that very narrow pcd. So I think that is actually a 4 byte 4 bit message, 4x4 minimizes wires for 16 keys, but the 8 keys is just a 16 key literally cut short. So please consult the hid report page on our web, referenced above.

**Comment by Julusian** [comment]
@michaelhatPIengineering That all sounds reasonable to me. The streamdeck isnt as pretty as you make it sound there. It gives an array of bytes of the current state, and we have to know the dimensions of the device to figure out where they map. The original version of the original model reports in right to left, and every other does left to right! Luckily though there are only 4 variants to consider, so testing with them all is a much easier task, and is easily abstracted away by the connection library

@JeffreyDavidsz if you need help getting PRs merged there let me know, I work with the maintainer (and have commit rights myself) so can help chase things

**Comment by michaelhatPIengineering** [comment]
@JustAddSoftware Well, yes, when an analog byte is interpreted into a button byte, lots of fun happens when you move the lever. Even more fun when the time stamp bytes are "buttons"

**Comment by JeffreyDavidsz** [comment]
@Julusian hey Julian small world ;-) I have a PR for one model. I still feel all models need to be in so I might go through the HID files and see what's missing. I'll take a look this week.

@michaelhatPIengineering are you on slack? That would be easier than using a github issue ;-)

**Comment by michaelhatPIengineering** [comment]
@JeffreyDavidsz  I usually use email for direct communication or skype, but I guess I could join slack. Just one more way to send a message...
But yes a git hub issue is not the best way to discuss the deeper meanings state based data transfer.

**Comment by JeffreyDavidsz** [comment]
I've asked Maggie to forward my email address.
