### ISSUE TITLE
Module Request: Renewed Vision ProPresenter

### ISSUE THREAD

**Issue by cxselph** [bitfocus/companion#144]
**Describe the feature**
Remote Control of Renewed Visions ProPresenter App without the need to know midi specific commands. It would be awesome if it could have the option to change the starting note number like the image below allowing for quick adjustment when needing to control more than one system at a time.

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
<img width="697" alt="midi config" src="https://user-images.githubusercontent.com/14942903/42181509-17a2bfba-7e09-11e8-9a5a-ef81aa1e2b93.png">

https://support.renewedvision.com/article/193-midi-note-mapping

**Usecases**
This would allow remote control or remote assistance of slides, playlists, etc...

**Comment by monoxane** [comment]
I am working on a module using the TCP remote protocol (as it has password auth and stuff), it'll take a bit before I submit a pull request but works moderately well in testing (I've only implemented 2 features so far)

**Comment by cxselph** [comment]
I would love to test it with you. If you don't mind, could you add it your own repository on GitHub so I/we can get to it? Thanks!

**Comment by Deanbau** [comment]
I can also test this

**Comment by monoxane** [comment]
When it gets a little bit more functional I’ll make the repo public and ping you in a message on this issue.

**Comment by monoxane** [comment]
@cxselph @Deanbau heres my testing repo https://github.com/monoxane/companion-module-propresenter6.git

**Comment by cxselph** [comment]
@monoxane Could you possibly add Clear Background and Clear Props too? That would cover everything I currently use? Thanks for working on this!

**Comment by fusionhead** [comment]
Could you possibly also add clear audio? thanks so much for the module..

**Comment by monoxane** [comment]
Issue can be closed now...

**Comment by haakonnessjoen** [comment]
Fixed by a31998e
