### ISSUE TITLE
[BUG] JavaScript error on running Companion

### ISSUE THREAD

**Issue by NixtonM** [bitfocus/companion#1441]
**Describe the bug**
When running the software we get an error message right after loading the software. After clicking it away, it looks like everything is running normally. Already tried an un- and reinstall.

**Screenshots**
![companion_error](https://user-images.githubusercontent.com/49650019/108526743-cb54dd80-72d1-11eb-88b0-a84b10d2d390.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Companion Version 2.1.2

**Comment by istnv** [comment]
That error usually means Companion is already running, which is why everything seems to work after clicking OK. Check the taskbar for the Companion icon after reboot.

**Comment by josephdadams** [comment]
Yes, you either have Companion open twice, or something else is using the port `51235`. This is the port used for UDP listening.
