### ISSUE TITLE
ATEM 8.5 Update please!

### ISSUE THREAD

**Issue by VicAvPiano** [bitfocus/companion#1443]
I am a music teacher and companion has been SUPER USEFUL even when I have no knowledge in tech. Recently, I have been experiencing some issues with the interaction with BlackMagic ATEM. The buttons are not showing anymore at my stream deck and the buttons I had are not responding nether. I did not do anything new.

**Comment by McHauge** [comment]
@have you tried with the newest beta's, you can find them by clicking the little button "builds" below the download link on the website

**Comment by VicAvPiano** [comment]
Thanks!!!
I will do it right away!!!

Best,
Victor Avila
*Dip Perf, **Bmus, Mmus*
*Suzuki Piano Association*
*(873) 353 5896*

**Comment by VicAvPiano** [comment]
IT works! Thanks!
