### ISSUE TITLE
Add a UI element to duplicate an action on a button

### ISSUE THREAD

**Issue by thedist** [bitfocus/companion#1447]
**Describe the feature**
Within the Edit Button UI each action that is on the button should have a duplicate button that adds that same action again to the button with the same options from which it was duplicated from.

This UI element would fit appropriately in the same area where the delete action trashcan icon is.

**Usecases**
There are situations where a user wants to have one button fire the same action multiple times, either identically or with slight variations in options/delay, which currently involves having to go through the add new action dropdown. Even with searching to filter the list of actions this can be a tedious process, where as the simplicity of a an icon near the delete action icon that duplicates an action would be a quality of life improvement.

Technically this could also be applied to feedbacks too, but I'm not sure if there is a demand for duplicate feeds on a single button.

**Comment by Julusian** [comment]
I almost did this as part of https://github.com/bitfocus/companion/pull/1402, but wasn't sure how useful it would be, so left it out for now

**Comment by istnv** [comment]
@Julusian I created a button to modify 10 channels at once, copying the base action then changing one parameter would have been so much easier.

**Comment by krocheck** [comment]
Semi-related is I'd like to be able to switch the instance/connection of an action.  e.g. you're stacking main and backup actions on a button OR something like REC for multiple decks.  It would be nice if the instance in the action could be a dropdown (or a pen/edit button that turns it into one) for all of the same instance types.  That way you can duplicate the main's action, switch the duplicate to the backup instance, and dial any delay, if appropriate.

**Comment by yurividal** [comment]
+1 on this. Very useful indeed.

**Comment by Julusian** [comment]
@krocheck some risk of the action becoming 'undefined' there, but I dont think that should stop this.

It should be pretty easy to implement both of these ideas, I think its just a question of how to display it in the ui. My first thought is to make the device label in each action row always be a dropdown, and to add the duplicate button next to delete, but this area is already feeling pretty cluttered so it needs some thought before adding more stuff 
![image](https://user-images.githubusercontent.com/1327476/110115380-e897aa80-7dad-11eb-8b94-6e0f08c51bbe.png)

**Comment by krocheck** [comment]
@Julusian The dropdown would only have 'compatible' instances ... meaning those of the same manufacturer/model.  Longer term we could test the action itself to see if instances of other man/model have the same action and include them as well (think PTZs).

**Comment by Julusian** [comment]
@krocheck yeah, I want to use bmd-atem here as an example of where a module changes the actions list dynamically, but maybe it should be using the model structure. But ultimately, it becoming undefined isnt really a problem, as long as the ui still lets you change it to another instance

**Comment by krocheck** [comment]
Ohhhh.  Yeah.  I wonder if we could make a crosstab whenever there's a setActions.  Can't forget to refresh the dropdown options too.

**Comment by MixDatSalt** [comment]
+1 This would be awesome

**Comment by DachsbauTV** [comment]
+1 as this would save a lot of work

Even better would be the possibility to copy/paste actions

**Comment by Julusian** [comment]
This will be in 3.0 #2127

**Comment by Thymeauthe** [comment]
+1
An additional Idea would be to duplicate all actions on a button to applicate on the same one with an other instance.

With Blackmagic Atem for example, we could program all actions we need for differents ATEM instances. We will just have to activate or not instance to do work on the switcher we use.

I know we could duplicate all the page to an other one for an other instance. But the idea would be insteresting to save pages.
