### ISSUE TITLE
Module Request: Tascam CD Record/Playback

### ISSUE THREAD

**Issue by cxselph** [bitfocus/companion#145]
**Describe the feature**
Remote control of Tascam CD Recorders - TASCAM SS-CDR250N/SS-R250N

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**

http://www.tascam.com/content/downloads/products/923/rs-232c_protocol_sscdr250n_v1.11_e.pdf

The most helpful things would be Play/Stop/Pause/Record and the eventual feedback on the buttons to match the record deck.

Here is what I have used in applescript to get it done.

-- SSCDR250N Connection--
set theServer to "10.30.6.109" -- Set this to the IP address of the device.
set thePort to "23"

--Commands--
set pressEnter to ""
set passwd to "SS-CDR250N"
set cdRecord to "01301"
set cdPlay to "012"
set cdPause to "01401"
set cdStop to "010"

try
	do shell script "{ echo " & pressEnter & ";  sleep .250; echo " & passwd & "; sleep 0; echo " & cdRecord & " ; sleep 0; } | telnet " & theServer & " " & thePort
end try

**Usecases**
This would allow for remote control of Tascam record decks and future automation with the future implementation of feedback system in companion.

**Comment by haakonnessjoen** [comment]
This has now been implemented in [companion-module-tascamcd](https://github.com/bitfocus/companion-module-tascamcd). Which is waiting to be added to companion. But is waiting for 1.1.1 release to go through first. It is of course also waiting to be tested, as I don't have access to such device.
