### ISSUE TITLE
[BUG] Loop between two tasks corrupts companion

### ISSUE THREAD

**Issue by delgaudm** [bitfocus/companion#1452]
I implemented two tasks that create a loop. (i.e. button 1 performs a task then "internal: Button Press" button 2. Button 2 performs a task them "internal Button Press" button 1. )

It became uninterruptible. Companion crashed and then this message appears on each restart:

Uncaught Exception:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at new db (/Applications/Companion.app/Contents/Resources/app.asar/lib/db.js:53:18)
    at exports (/Applications/Companion.app/Contents/Resources/app.asar/lib/db.js:41:9)
    at EventEmitter.<anonymous> (/Applications/Companion.app/Contents/Resources/app.asar/app.js:159:44)
    at emitNone (events.js:106:13)
    at EventEmitter.emit (events.js:208:7)
    at /Applications/Companion.app/Contents/Resources/app.asar/bitfocus-skeleton/main.js:138:10
    at Server.requestMessageHandler (/Applications/Companion.app/Contents/Resources/app.asar/bitfocus-skeleton/node_modules/electron-rpc/server.js:46:5)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)

**Comment by delgaudm** [comment]
Uninstalling and Reinstalling Companion did not rectify. (Mac Catalina)

**Comment by delgaudm** [comment]
I believe I have solved it by removing to /Library/Application Support/companion and letting the app create a new folder from scratch

**Comment by delgaudm** [comment]
However, the issue remains such that if two tasks create an infinite loop, it crashed the app in an unrecoverable way and the library folder needed to be deleted.

**Comment by krocheck** [comment]
Yeah, valid point that is this an issue.  Off the top of my head there's no easy way to implement loop detection like what you encountered.  In the future we're planning to put each instance into its own process, so I think that would mitigate this case because you theoretically could 'crash' the internal module that's ping-ponging itself without killing the whole app.

**Comment by istnv** [comment]
You do not need two instances. You can also cause this with a self-repeating key too small of a delay.

**Comment by scoobiekw** [comment]
This was a design concern when I originally requested the call a button functionality. The answer was it'll work but you can crash companion because we can't check for infinite loops.

The key to successful loops is adding delays, so that you have time to cancel actions if while you are running a loop.

**Comment by Julusian** [comment]
I believe this is no longer an easy to cause problem. Companion can still get into loops which max out the cpu, but it is yielding cpu time such that a client should be able to disable the rogue trigger. During this a connected streamdeck is functioning perfectly fine, it is still drawing at a fast rate and responds to button presses normally. The ui is sluggish, but is usable

I confirmed this with the trigger:
![image](https://github.com/bitfocus/companion/assets/1327476/4b8f374f-64f3-4000-8886-7bb441e70442)
which got up to 29000 runs without crashing.

Maybe we could do more to avoid this, but that would most likely require us to limit how quickly/often triggers can be executed, and as this is not a common issue I am not convinced it is worth adding that delay. But I am open to it if others report this is still a painful problem for them.

Perhaps a rule like a trigger isn't allowed to execute more than 10 timer per second? If it tries to execute an 11th time, then that 11th call gets delayed by 100ms. That would allow these triggers to run as fast as possible for short bursts, and once they start to look 'infinite' they get slowed down significantly which should allow companion to respond well enough for them to be corrected.
