### ISSUE TITLE
Internal button-related actions (change colors/text...) should have a default page and bank of "this button" so a button copy/move works

### ISSUE THREAD

**Issue by plocher** [bitfocus/companion#1455]
This may be related to some of the requests for per-button variables...

**Describe the feature**
When using the internal actions on a button to change display details, the bank and page info is hardcoded to a particular bank/page.  When a button is copied/moved, that info isn't updated, and the wrong part of the display is modified.

This request is to add a new "value" for both bank and page that means:  "me".  Maybe this could be done by leaving both fields blank and having the implementation interpret that as (logically) "self.mybank" and "self.mypage".  If the user variables discussion takes off, maybe there could be a set of per-button context variables that encode this info...

**Usecases**
When constructing a latched on / off button, it is sometimes useful if the display of the button changes, say from dark with the word "OFF" to light with the word "ON".  

in this use case, which feels common, there is no desire to modify any OTHER button's display, but there isn't a way to say "me"...

**Example**

Current behavior: A button on page 3, bank 11 whose current display is a black background with the words "Turn Off" might have a LATCHED config that sends an OFF command somewhere and then changes the button to display a white background with the words "Turn On".

When copied to page 3, bank 12, the bank 12 button still references the bank 11 location...

```
  In the config section, there is no mention of bank or page:
		        {
                                "style": "png",
				"text": "All\\nOn",
				"size": "auto",
				"alignment": "center:center",
				"pngalignment": "center:center",
				"color": 39372,
				"bgcolor": 16777215,
				"latch": true,
				"relative_delay": false
                        }

   in the actions section, the bank and page are required:
			{
				... some action that turns a device off
			},
			{
				"id": "MIWwp8-HCz",
				"label": "bitfocus-companion:button_text",
				"instance": "bitfocus-companion",
				"action": "button_text",
				"options": {
					"label": "Turn\nOn",
					"page": "3",
					"bank": "11"
				}
			},
			{
				"id": "upcvMlyS7i",
				"label": "bitfocus-companion:bgcolor",
				"instance": "bitfocus-companion",
				"action": "bgcolor",
				"options": {
					"color": 16777215,
					"page": "3",
					"bank": "11"
				}
			}

... and in release actions, turn the devicwe back on and change the display back to the original configuration of Dark/"Turn Off" ...
			{
				... some action that turns a device on and resets the display for the next cycle
			},
			{
				"id": "8nm0PXDFs",
				"label": "bitfocus-companion:bgcolor",
				"instance": "bitfocus-companion",
				"action": "bgcolor",
				"options": {
					"color": "0",
					"page": "3",
					"bank": "11"
				}
			},
			{
				"id": "_WZCLO2uU",
				"label": "bitfocus-companion:button_text",
				"instance": "bitfocus-companion",
				"action": "button_text",
				"options": {
					"label": "Turn\nOff",
					"page": "3",
					"bank": "11"
				}
			}
```

**Comment by istnv** [comment]
Try the beta builds. 'This button' was added to all of the internal button actions a few weeks ago.

**Comment by Julusian** [comment]
This has been in the 2.2 beta builds for about a month https://github.com/bitfocus/companion-module-bitfocus-companion/pull/25
