### ISSUE TITLE
[BUG] New UI - Safari doesn't select text properly on button-page-input"

### ISSUE THREAD

**Issue by bryce-seifert** [bitfocus/companion#1458]
**Describe the bug**
When clicking the button-page-input in Safari on the new Web GUI, the text is selected but something clears the selection.

**To Reproduce**
1. Go to button tab on Safar
2. Click in the button-page-input
3. Text is not selected

**Expected behavior**
Text is selected so that you can easily type in new page without worrying about clearing current number (this is the behavior in Chrome).

**Screenshots**

https://user-images.githubusercontent.com/50299051/109434083-1c9f5400-79d9-11eb-92cd-c8a56f7e638b.mov

**Desktop (please complete the following information):**
 - OS: Big Sur
 - Browser Safari
 - Companion Version 2.2.0 (a5685300-3073)

**Comment by Julusian** [comment]
I had a quick look at this, and we are trying to select it, but for some reason it then unselects in safari. I have not looked into why that could be
