### ISSUE TITLE
[Request] Button to pop-out log into new window

### ISSUE THREAD

**Issue by bryce-seifert** [bitfocus/companion#1459]
**Describe the feature**
With the new UI moving the Log to a tab, it might be nice to have a button on the Log tab to pop open just the log in a new window. 

Maybe a button with the fa-external-link icon?

**Usecases**
I find it frequently useful to see the log side-by-side as I'm making changes in the Web UI or testing buttons.

**Comment by Julusian** [comment]
A different way to approach this would be to start using react-router (which I think is already loaded ready), so that switching tabs changes the url to reflect the current location.
It will then be possible to force the tab to open in a new browser tab via your favourite shortcut

**Comment by bryce-seifert** [comment]
That sounds like it would work as well, and save a few clicks.

**Comment by bryce-seifert** [comment]
This was fixed with https://github.com/bitfocus/companion/commit/455de83f40a98fe8cd03fe801fe744bf43493224
