### ISSUE TITLE
Manual Module Add

### ISSUE THREAD

**Issue by dszoka** [bitfocus/companion#1460]
**Describe the feature**
I'm not sure if its a 1 off but I have found out that some modules aren't part of the master build and need to be added manually. With the new UI rolling out could have a simple way to add a Module into your build... Click Add -- Type Git Address -- Click ok  

So far I have only Found the Raspberry-Gpio module isn't in the master, but that could change in the future

Just an Idea

**Comment by Julusian** [comment]
Unfortunately this is more of a backend than ui challenge to solve. I dont think that installing from git like this will be possible as it will require most of a development environment to 'prepare' the module code. We need to look into a way of packaging modules that will allow for them to be loaded like this, but that is quite a large task (see #1002)
