### ISSUE TITLE
WebUI feature request: Variables tab on Triggers page

### ISSUE THREAD

**Issue by scoobiekw** [bitfocus/companion#1462]
change new trigger to a pane setup with area on right for a Variables tab.

this gives access to variables while creating a Trigger without switching tabs to copy from the instance page

**Comment by Julusian** [comment]
With #1604, the ui has a dropdown that provides a searchable list of all known variables 
![image](https://user-images.githubusercontent.com/1327476/120043321-a7591480-c003-11eb-9666-e1043b1fce36.png)
