### ISSUE TITLE
Misunderstanding with BMD Constellation

### ISSUE THREAD

**Issue by lightyear94** [bitfocus/companion#1463]
Goodmornig
I just found something wrong with the Model of the Blackmagic Design ATEM mixers: i’m using a BMD Constellation 8K, but in order to make the Companion app run perfectly i have to choose the “Constellation” in the Model drop-down menu in Config sheet, instead of using the “Constellation 8K”. I also know that BMD is only making Constellation 8K, all of the other mixers are ATEM 1/ME , 2/ME and 4/ME.
As already said, by choosing “Constellation” instead of “Constellation 8K” in the Config menu, the physical Constellation 8K works perfectly without any problems.
Thanks you
Federico

**Comment by Julusian** [comment]
They aren't wrong as such, just named confusingly. There are 2 because the mixer presents itself very differently when in 8K mode.
They have already been renamed in the beta builds of companion to clarify the differences to `Constellation (8K Mode)` and `Constellation (HD/4K Mode)`

**Comment by lightyear94** [comment]
Thank you very much. 
I’m sorry but I haven’t thought about the “8K mode”

Thank you very much again for all your works. Appreciated very much


Federico

Sent from my iPhone X
