### ISSUE TITLE
Multiplay windows feature.

### ISSUE THREAD

**Issue by mikaaus** [bitfocus/companion#147]
**Describe the feature**
A clear and concise description of what the feature does

**Is this platform dependent (windows, mac, ..)?**
Explain

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by haakonnessjoen** [comment]
You forgot to fill in the information

**Comment by mikaaus** [comment]
Is it possible to make a file set for multiplay for windows. It is a windows version of playback similar to q lab. Also is there an app I can install on multiple computers that I can send keyboard shortcuts to. Similar to the PowerPoint system?

**Comment by haakonnessjoen** [comment]
Multiplay seems like a dead project (the developer says so himself), and I know there are a lot of good alternatives to this software. Also seems like the program has no controllable API via network/osc/midi. So we can't implement it. If it has keyboard shortcuts, you can probably control it using the octopus listener yourself.
