### ISSUE TITLE
Fade time (for devices that have faders)

### ISSUE THREAD

**Issue by jongyrocka** [bitfocus/companion#1478]
Hi Team!

Would it be possible to add some form of a fade time for devices that have faders (Any sound/lighting console) 

Eg

I utilise the Yamaha CL/QL module. Currently you can set a Fader Value and it snaps to this value.
Whilst I could program bunch of cues with delays to move this fader to give it the effect of a fade, I was wondering if you could add a function to set a Low and high value with a duration? 

Whether this is done via 2 seperate cues, or added as an extra function within the module for a device it self? This would be applicable to any sound desk module or lighting desk, perhaps even the T-bar on video mixer. 

Maybe these particular elements can be flagged as fade device, so it could become more global parameter/function inside of companion (unsure of how its written)

Just a thought :)

Keep up the good work.

**Comment by josephdadams** [comment]
It would have to be implemented on a module by module basis with timers because every protocol and implementation are different. Please consider making specific feature requests for those modules in their respective repositories.
