### ISSUE TITLE
Request: when using function remove topbar remove the yellow bar also and create a different feedback style for a button press.

### ISSUE THREAD

**Issue by JeffreyDavidsz** [bitfocus/companion#1479]

**Comment by JeffreyDavidsz** [comment]
@JeffreyDavidsz the yellow bar is being drawn underneath text and pngs. I would expect it to be drawn on top

**Comment by JeffreyDavidsz** [comment]
I haven't had the chance to try this update. Does the Red/Yellow square still show in the corner for instance issues? Otherwise, the 2px border idea would work for that

**Comment by JeffreyDavidsz** [comment]
If you are going to hard code a visual cue of a press how about something a little less asymmetrical and that wont overlay a significant portion of 72x72 image buttons. Possible alternatives would be a 2px border around the entire button, or the button graphic shrinking 4px or so to visualize a "press" type of effect.

**Comment by yurividal** [comment]
The idea of shrinking 4px on each side for feedback seems awesome

**Comment by Julusian** [comment]
Yes, the corner icons still appear
![image](https://user-images.githubusercontent.com/1327476/110205884-9076ac00-7e72-11eb-8af8-aabda6d2075b.png)

**Comment by BasilChessman** [comment]
I like the idea of a 2px red border when pressed.   That would also be great for identifying latched buttons.

**Comment by JeffreyDavidsz** [comment]
I've put the previous comments on top here so I can collect the suggestions. Initially I've changed to what was requested. It seems a good idea to look at the border suggestion.

**Comment by JeffreyDavidsz** [comment]
I've added the border (in yellow at this moment) and removed the text. I think this is a good solution. Closing this one please open a new request if needed

**Comment by lsdigi** [comment]
Hey there. The border being lit up seems like a perfect way to go around the square icon issue. Also would you consider to allow higher resolution icons to match the streamdeck icons so we don’t have to crop / reduce size and have overall nicer UI? Would be happy to contribute ££. Cheers

**Comment by JeffreyDavidsz** [comment]
@lsdigi You can upload 72x72 png's, is that what you mean?

**Comment by Julusian** [comment]
@lsdigi the internal image compositing logic is hardcoded to be 72x72. changing this is not a particularly simple task as it will require rewriting large chunks of the graphics logic
