### ISSUE TITLE
Module request. Multiplay windows.

### ISSUE THREAD

**Issue by mikaaus** [bitfocus/companion#148]
Is it possible to make a file set for multiplay for windows. It is a windows version of playback similar to q lab. It is free software and is great. 

Also is there an app I can install on multiple computers that I can send keyboard shortcuts to. Similar to the PowerPoint system?

**Comment by haakonnessjoen** [comment]
Multiplay seems like a dead project (the developer says so himself), and I know there are a lot of good alternatives to this software. Also seems like the program has no controllable API via network/osc/midi. So we can't implement it. If it has keyboard shortcuts, you can probably control it using the octopus listener yourself.

You can install octopus listener on mac and windows machines, and send keyboard shortcuts using the octopus listener module in Companion
