### ISSUE TITLE
Triggers Button Up/Down functionality

### ISSUE THREAD

**Issue by philglenny** [bitfocus/companion#1485]
**Describe the feature**
Option to specify that the trigger does KEY DOWN when variable is true and then KEY UP when variable is no longer true. 

**Usecases**
Building a tally system, where the variable is atem=cam1, and it turns a smartscope border to red (KEY DOWN), but currently there's no neat way to release the tally when the atem cuts away. If KEY UP were 'border=none' then it could turn the tally on when true, and off when no longer true.

**Comment by josephdadams** [comment]
Can you do this using the bmd-atem and bmd-smartscope modules in Companion along with the Triggers/Scheduling functions?

**Comment by fdebeer** [comment]
dit you try tally-arbiter? maybe this wil help you with your search. (free software on tallyarbiter.com)

**Comment by josephdadams** [comment]
I've heard of this software and think it's pretty great.

**Comment by Julusian** [comment]
I think this is now possible in 3.0 with the improved triggers, but I think it will require doing as two triggers.

Making it possible to do it as one trigger will be handled by #1052
