### ISSUE TITLE
Page Number Action and Separate Instance From Action

### ISSUE THREAD

**Issue by dbiser99** [bitfocus/companion#1486]
**Describe the feature**
Add limited internal functions to the Page Number button to allow directed page control without losing the current feedback, i.e. the page name if set.

Related request: ability to copy action within a button and select the instance separate from the action.

**Usecases**
My apologies for putting what ultimately turned into 2 feature requests into one. (They started as related requests.)

Maybe I'm missing something as I can find almost all the pieces separately...I'm trying to be able to take the Page Number button and put a "hidden" command on it to take me back to an assignable base page (basically the Set to Page command) effectively creating a home button. As a workaround I could alternately do this by making the page number button a regular button with the Set to Page command, but this has it's own issues making it less than desirable. The primary reason I wish to avoid that option is having to program the button on every page individually. I ultimately see this as being a universal function (rather than a page by page function) using the existing Page Number buttons (so it is part of a default page layout), set in the settings tab with an enable/disable field and a page number to switch to field. The second issue follows off that and is I can't find the variable to assign to the button title (if one exists) which will automatically change the name to the current page name (like the Page Number button currently does.) This means that not only would I need to program the button on each page, but I'd have to manually edit the title anytime I changed the title of the page it was on. Personally, while having the function be built directly into the Page Number button would be best in my opinion, I could probably live with the first part given the extensive copy/move/import/export functions if I knew and had the variable commands to make the button title follow the page name. Otherwise it is a lot of duplicate work. 

A quick second feature request speaking of duplicate work...I find I do a lot of work where I am copying actions on a button. For example starting a record across multiple record decks with a single button. It would be great to have 2 things added to facilitate that...ability to copy actions and the ability to set the instance separate from the action. First is pretty straight forward. My Start Records example typically doesn't have any parameters associated with it, but for an action which does, not only do I currently have to search through my entire list of actions for the one I want, but then I have to set all the parameters again too in order to perform the same action on multiple devices. The second follows off that but would be extremely useful for general use and current copy commands as well. Right now if I have several devices being controlled I have to search through the entire list for the device and command I want. In addition to this potentially being a large list of commands if I have multiple devices with lots of commands to control, this can become additionally confusing if I have several instances of the same device type. By adding the ability to separately select the device instance you should be able to subsequently limit the actions list to that device instead of listing everything. Additionally in the aforementioned case of copying an action on a button or the button itself, all the parameters can be left the same and I just select the new device similar to what you can do now when importing an individual page.

Thanks

**Comment by josephdadams** [comment]
@dbiser99 Can you please post this as two separate issues?

**Comment by dbiser99** [comment]
Done
