### ISSUE TITLE
[BUG] New UI - Unlatch checkbox not showing at the right place on page

### ISSUE THREAD

**Issue by LYMPIA** [bitfocus/companion#1488]
Hello everyone !

**Describe the bug**
On "Press/on actions" & "Release/off actions" the "internal: Abort actions on buttons" dosen't display a checkbox for the unlatch option. Just the text. But somehow, the checkbox is to be found while scrolling down the page after the "Feedback" and "Hint".

The error is present on all my browsers (Chrome, Edge and Firefox).

As a result of this error, Foreground and Background colors options for the Feedback options are not working correctly and colors can't be changed as the popup color selector is not appearing at all...

**Screenshots**
![01](https://user-images.githubusercontent.com/80356993/110527567-6b569780-8117-11eb-96e3-a69f2ed447c3.jpg)
Checkbox nowhere to be found...

![02](https://user-images.githubusercontent.com/80356993/110527579-6f82b500-8117-11eb-95c5-fdb8ebfda276.jpg)
But are displayed below...

**Desktop (please complete the following information):**

- OS: [Windows 10]
- Browser: [Chrome / Firefox / Edge]
- Companion Version [ 2.2.0 cdc51b48-3108 - and prior versions including the new WebUI]

**Comment by Julusian** [comment]
Odd, I am certain I had already fixed this, but the fix seems to not have applied to the correct thing..

**Comment by Julusian** [comment]
I have pushed a fix for this. please let me know if it doesnt work

**Comment by LYMPIA** [comment]
Great ! Thank you very much. It's working again within the new WebUI as expected. Many thanks for your hard work !
