### ISSUE TITLE
Module Request - Panasonic AVHS-410 (and similar switchers - all might use same command structure/syntax)

### ISSUE THREAD

**Issue by PTGitHubber** [bitfocus/companion#149]
Some simple commands - possibly the same for other Panasonic switchers in the series
--- Previews the selected XPT number ---
Preview to XPT 1 (0x02 SBUS:03:00 0x03)
Preview to XPT 2 (0x02 SBUS:03:01 0x03)
Preview to XPT 3 (0x02 SBUS:03:02 0x03)
Preview to XPT 4 (0x02 SBUS:03:03 0x03)
Preview to XPT 5 (0x02 SBUS:03:04 0x03)
Preview to XPT 6 (0x02 SBUS:03:05 0x03)
Preview to XPT 7 (0x02 SBUS:03:06 0x03)
Preview to XPT 8 (0x02 SBUS:03:07 0x03)
Preview to XPT 9 (0x02 SBUS:03:08 0x03)
Preview to XPT 10 (0x02 SBUS:03:09 0x03)
Preview to XPT 11 (0x02 SBUS:03:10 0x03)
Preview to XPT 12 (0x02 SBUS:03:11 0x03)

--- Changes the transition time for the background layer ---
BKGD TIME TO 30 FRAMES (1 SEC) (0x02 STIM:00:030 0x03)
BKGD TIME TO 15 FRAMES (1/2 SEC) (0x02 STIM:00:015 0x03)

--- Transitions to previewed XPT ---
BKGD MIX GO (0x02 SAUT:00:0:0 0x03)
BKGD CUT GO (0x02 SCUT:00 0x03)

--- Turns PIPs on/off ---
PIP1 ON (0x02 SAUT:04:0:1 0x03)
PIP1 OFF (0x02 SAUT:04:0:2 0x03)
PIP2 ON (0x02 SAUT:05:0:1 0x03)
PIP2 OFF (0x02 SAUT:05:0:2 0x03)

--- Sets transition time for PIPs ---
PIP1 TIME TO 30 FRAMES (0x02 STIM:04:030 0x03)
PIP2 TIME TO 30 FRAMES (0x02 STIM:05:030 0X03)
PIP1 TIME TO 0 FRAMES (CUT) (0X02 STIM:04:000 0X03)
PIP2 TIME TO 0 FRAMES (CUT) (0X02 STIM:05:000 0X03)

--- Changes indicated Auxilliary send to indicated XPT ---
**For the next section**(Aux1: 12; Aux2: 13; Aux3: 14; Aux4: 15)

Aux1 to XPT 1 (0X02 SBUS:12:00 0X03)
Aux1 to XPT 2 (0X02 SBUS:12:01 0X03)
Aux1 to XPT 3 (0X02 SBUS:12:02 0X03)
Aux1 to XPT 4 (0X02 SBUS:12:03 0X03)
Aux1 to XPT 6 (0X02 SBUS:12:05 0X03)
Aux1 to XPT 7 (0X02 SBUS:12:06 0X03)
Aux1 to XPT 8 (0X02 SBUS:12:07 0X03)
Aux1 to XPT 9 (0X02 SBUS:12:08 0X03)
Aux1 to XPT 10 (0X02 SBUS:12:09 0X03)
Aux1 to XPT 11 (0X02 SBUS:12:10 0X03)
Aux1 to XPT 12 (0X02 SBUS:12:11 0X03)

Must install plug-in on the actual switcher to allow for commands via TCP, otherwise any testing will be ineffective.

Above commands would be useful for remote operation of Panasonic switcher, once programming of the switcher is done.

Below is the reference for command protocols
[AV-HS410-HS410_IF-Protocol-Ver1.3EVol_1.pdf](https://github.com/bitfocus/companion/files/2163236/AV-HS410-HS410_IF-Protocol-Ver1.3EVol_1.pdf)

**Comment by haakonnessjoen** [comment]
Implemented with support for both HS410 and HS50. Will be added just after the 1.1.1 release.

**Comment by PTGitHubber** [comment]
I might have been off with the actual commands I sent you guys regarding the AVHS-410. When I tried them in Octopus (I didn’t have the switcher in front of me again until yesterday) as written, they didn’t work.

One of the guys in the Octopus user group said that he had the command working with the following changes:

I gave you 0x02 SBUS:03:00 0x03 in order to Preview XPT 1, and that is how the documentation says to write the string. That didn’t work for me, so I tried %02 SBUS:03:00 %03. That also didn’t work for me. I checked the other guy’s file for the same command, and he used %02SBUS:03:00%03 and said he had success. 

When implementing support for the AVHS-410 or the EC-50, please keep that in mind. I’m not sure if it was something that Octopus was translating a different way, or what. I have yet to get in front of the mixer with that last example of commands.

Thanks for your effort, guys!

**Comment by haakonnessjoen** [comment]
Hi,

I read the manual of both HS410 and HS50, so I did not follow your directions. And thus I did not have a space after \x02 and before \x03, since the protocol specifies that the command should immediately follow the STX (\x02) byte.

Have you tried to download the latest build from https://builds.bitfocus.io/companion/ ? It has the new module, and you can test it out. Please report back if it works for you.
