### ISSUE TITLE
Custom module import 

### ISSUE THREAD

**Issue by TheCross** [bitfocus/companion#1490]
**Describe the feature**
The feature should provide a method to add/edit one or multiple custom modules like the built in ones like for the ATEM Mini. With the feature it should be possible to add send and receive-requests that are accessible via the pull-down menu for button action assignment. It should also be possible to add a custom IP and Port setting for a module instance.

**Usecases**
- The feature can be used to provide a simple module during SW development (SW refers here to another software than companion that should be controlled via companion/streamdeck) that could be changed quickly during SW improvement.
- The feature can be used to provide easy interaction with custom SW that need not to be added in the built in module-list, because the custom SW will never be released to the public.

**Comment by Julusian** [comment]
This will be possible in 3.0 for modules which are updated to the new format. Documentation will follow when we are to start encouraging module developers to update their modules to the new format.

It will not be possible to do anything for this in 2.2
