### ISSUE TITLE
A switch profiles button 

### ISSUE THREAD

**Issue by samurai-goldfish** [bitfocus/companion#1494]
I have two different profiles that I need to run and if I had a button that i could do that with would be great. As of now, when I add a switch profile button to my companion screen, it takes on one slot on every page. 

Running on a mac and I have a windows pc that I run on also.

**Comment by Julusian** [comment]
What do you mean by profile? Companion doesnt have any concept of profiles.
Are you referring to something inside the elgato streamdeck software?

**Comment by samurai-goldfish** [comment]
> What do you mean by profile? Companion doesnt have any concept of profiles.
> Are you referring to something inside the elgato streamdeck software?

Yes in streamdeck. In the streamdeck software, I add a button to switch profiles to "Home" that is nested on the bottom right of my streamdeck while it is on my "Companion" profile. When I switch pages in Companion, that same "Home" button is on every page. Obviously that can't change. Is there a way to switch profiles with a button in Companion?

**Comment by Julusian** [comment]
no, I dont think companion is able to talk to the streamdeck software like that

**Comment by samurai-goldfish** [comment]
> no, I dont think companion is able to talk to the streamdeck software like that

Ahh, okay.. Wish that it could because that would be great. I might just have to get the xl to have more buttons.

**Comment by fdebeer** [comment]
Is it possible to do the tasks you do with the streamdeck software to do with companion? and then just forget about the streamdeck software?

**Comment by samurai-goldfish** [comment]
It would be ideal not to use streamdeck at all but I still need some of the
buttons from the software

**Comment by McHauge** [comment]
No there is currently no "Profile" setups, but it could be a cool feature, to have a way of switching between setups internally, but you could achieve the same result (except for the one-click button on the deck itself) by exporting your setups to a central folder and importing the setup for that and that location/event. that could be thought off as "profiles/setups" another way is to make smaller page loops in companion and a "menu" page, so maybe hor home you only click though page 20-30 while at work you use page 50-90 and then have the menu page on page one, to jump between, that way you can have as many loops as you can fit in 99 pages.

 I do that sometimes if I use a second streamdeck for a different role, then set it up with a master loop and a producer loop or something in that realm.
 
Hope it sparks some ideas :)

**Comment by josephdadams** [comment]
#897
