### ISSUE TITLE
Tablet3.html touch issue on Chrome for Android (Pixel2XL)

### ISSUE THREAD

**Issue by scoobiekw** [bitfocus/companion#1495]
Testing Tablet 3, built from source today

When viewing Tablet3.html in Chrome on my Android 11 Pixel2XL single taps do not work as expected.

Was testing Atem Cut and Auto-Trans when I noticed that a tap would cause the Auto trans to freeze mid transition. Hitting Cut would briefly change then change back. 

Ergo a double tap is being fired on a light press.
Hold the press longer and it fires a single time.

this doesn't happen with mouse interactions.

**Comment by Julusian** [comment]
fixed in the latest build
