### ISSUE TITLE
disable key-up action

### ISSUE THREAD

**Issue by fdebeer** [bitfocus/companion#1496]
make an internal action to disable key-up action

**Usecases**
i have a button with a delayed action on key-down. when i release the button before the delay. key-up gives a aboard all delayed action and preforms another action on key-up.  i would like the button not to do this when the action on the key-down is preformed. so when i release the button no action is taken for key-up. 
this 'internal:disable key-up' has to be put after the delay and the action in key-down
it makes it possible to make 2 commands on 1 button. 
shortpress command 1, longpress command 2

i use this now for ptz-cam. 
key-down 1000ms delay and save preset
key-up abort delayed action and recall preset
but no need for recall preset when preset is just saved. saves a bit of network action

**Comment by Julusian** [comment]
I would rather do #925 instead of this. While this will be a lot simpler to implement, it will be something that will need to be maintained going forward even once there is a better solution

**Comment by istnv** [comment]
I think the `unlatch` option for the `Abort specific button` action cancels the UP actions, too.

**Comment by fdebeer** [comment]
> I think the `unlatch` option for the `Abort specific button` action cancels the UP actions, too.

no it does not what i mean with cancel key-up

@Julusian; I would rather do #925 instead of this
this is a discussion about what i already do with save/recall preset PTZ, and it works well.
key-up recalls preset which is no problem after save preset
What i like to have is a cancel key-up so you can put 2 commands on 1 button
like key-up starts recording, key-down with 2000ms delay stops recording. in this setup you dont want key-up to go after longpress keydown

**Comment by istnv** [comment]
@fdebeer That is what `unlatch` does. It aborts the `key-up` commands.

**Comment by istnv** [comment]
@fdebeer  Try this on a button:

key-down:
1. 2000ms delay, Stop recording
2. 2010ms delay, `Abort actions on one button`:  Select `This button` and `Unlatch?`

key-up:
1. `Abort actions on one button`:  Select `This button`
2. start recording

**Comment by fdebeer** [comment]
> @fdebeer Try this on a button:
> 
> key-down:
> 
> 1. 2000ms delay, Stop recording
> 2. 2010ms delay, `Abort actions on one button`:  Select `This button` and `Unlatch?`
> 
> key-up:
> 
> 1. `Abort actions on one button`:  Select `This button`
> 2. start recording

tried it. doesn't work. still performs key-up action
did it with color background change:
key down: 2000 delay; bgcolor change red; 500 ms bgcolor black; abort action on button with unlatch
key up: abort action on button; bgcolor blue; 500 ms bgcolor black

longpress button red after release button blue
shortpress button blue
tried it with all positions with latch/unlatch

**Comment by istnv** [comment]
> aboard action on button doesn't work on key-up, only on key down. Bug maybe?
Probably. The intent of the unlatch option was to cancel any pending up actions.
It is new to recent builds and was implemented along with aborting specific buttons.

**Comment by istnv** [comment]
OK. The unlatch works if the button *is* latched but not if it is a regular press/release button.
It is a dozen lines of code to allow a regular button to respect the unlatch option.

**Comment by fdebeer** [comment]
but still no way to make a short/long press possible with 2 different instances.
so to go back to my first question; is it possible to make an 'internal; disable key-up'...

**Comment by istnv** [comment]
I plan to submit an update soon that adds the abort key-up on normal (not-latch) buttons if you check the unlatch option. I have been testing it in various configurations and it works for short/long press as you would expect.

**Comment by fdebeer** [comment]
Perfect! thanks.

**Comment by istnv** [comment]
@fdebeer This was merged today. Try the `Unlatch?` feature as described previously. If set, up-actions will be skipped on latch and non-latch buttons.

**Comment by fdebeer** [comment]
it works like a charm!! Great and many thanks
