### ISSUE TITLE
[BUG] React UI Preset Drag bug

### ISSUE THREAD

**Issue by thedist** [bitfocus/companion#1503]
**Describe the bug**
Buttons in the Preset window of the React UI are not draggable.

**To Reproduce**
1. Go to the V2 UI
2. Go to the Buttons tab and select the Preset tab on the right panel
3. Attempt to drag preset onto the buttons panel

**Expected behavior**
The preset button should be dragable

**Desktop (please complete the following information):**

- OS: Win 10
- Browser: Chrome
- Companion Version: 2.2.0 (2.2.0-b1922c21-3140)

**Additional context**
While the <img> element for the preset has the attribute `draggable="true"`, the CSS prevents this.
The issue is with `.bank img` at `_bank.scss:37`
`-webkit-user-drag: none;`

With the `-webkit-user-drag` set to auto, the buttons become draggable and work as intended, but it also makes all of the buttons on the main buttons panel draggable too. The preset panel should have CSS that overrides the `.bank img` styling.

**Comment by Julusian** [comment]
good spot :)
fixed in https://github.com/bitfocus/companion/commit/839cf7a6d67f5821f309746f49254b28c2c16c70
