### ISSUE TITLE
[BUG] No documentation on how to add modules

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [bitfocus/companion#1510]
**Describe the bug**
It is unclear how I can add modules.

**To Reproduce**

1. Install companion
2. Try to add actions to buttons, only internal actions are listed
3. Read the documentation
4. Read the part about modules: It just links to the bitfocus module page. It does not tell you how to install them.

**Expected behavior**
Some instructions on how to install modules.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Linux/Windows
- Browser: chrome
- Companion Version 2.1.2 (f4bcaf3-2679)

**Comment by McHauge** [comment]
@RudolfVonKrugstein Please take a look at the "Getting Started" guide in the left menu bar in the web interface for a guide on how to add and remove modules

And as a quick guide: you will find modules listed as "Instances" in the web GUI, and in the "Instance" tab you can add/remove/edit what instances/modules you want to use

**Comment by fdebeer** [comment]
It's not a bug, but a user-error.
all available modules are installed with companion. go to the instances tab and type what you are searching for in the search-field. 
You can type the manufacturer or the machine/software you want to control. 
there you wil find your module.
don't use the find by category or manufacturer buttons. the list is to long to fit in your browser.
this is still a bug :-)

**Comment by RudolfVonKrugstein** [comment]
Firstly, thanks for the help!

I was confused because I was looking at the "Modules" part of the documentation.
