### ISSUE TITLE
Container Image

### ISSUE THREAD

**Issue by mathias-ewald** [bitfocus/companion#1518]
**Describe the feature**
Provide a maintained OCI compatible container image and Helm chart for companion.

**Usecases**
Companion seems to eat away lot's of CPU (why?) which is why I'd prefer to run it on a separate system or server. Servers often don't use graphical user interfaces and in my case I have a Kubernetes cluster at home for this purpose.

**Comment by Julusian** [comment]
There is a docker image available https://github.com/bitfocus/companion/packages/260404.

Some help will be needed for a helm chart, I don't believe there is any knowledge among the core maintainers to write a helm chart

**Comment by mathias-ewald** [comment]
Oh nice, I didn't find that. I already created a Helm chart based on the `common` chart from [k8s-at-home](https://github.com/k8s-at-home) It's probably best to contribute it there if the maintainers here don't have that skill, what do you think?

**Comment by mathias-ewald** [comment]
I just noticed the `docker pull` requires authentication here on github. That unnecessarily complicates things, imho. Would be better to have it public.

Out of curiosity: What does the "needs beer" label mean? :D
