### ISSUE TITLE
Getting started manual

### ISSUE THREAD

**Issue by willosof** [bitfocus/companion#152]
Someone should create an english, easy to read and comprehend manual for companion beginners. Any takers? The documentation should be written in markdown. 
https://guides.github.com/features/mastering-markdown/

**Comment by danielmerchen** [comment]
If this is still a need happy to make the first pass at things.

**Comment by haakonnessjoen** [comment]
Daniel Richert has started, but you are welcome to contribute/continue, and also go through the existing english, which is not 100%. :)

https://github.com/bitfocus/companion/blob/master/documentation/

**Comment by willosof** [comment]
@danielmerchen would you like to join us at slack to discuss this?

**Comment by willosof** [comment]
https://github.com/bitfocus/companion/blob/master/documentation/gettingstarted.md solves this.
