### ISSUE TITLE
TCP/UDP set button step

### ISSUE THREAD

**Issue by mark-epstein** [bitfocus/companion#1520]
**Describe the feature**
Add option for TCP/UDP to set the current state of a button, without necessarily running the actions

**Usecases**
Specific to the hardware I have, but it could be anything: I like to use AUTO transitions in my ATEM, so my Companion buttons, instead of just changing the PGM source, change the PVW source and trigger the AUTO function.

If something outside my Stream Deck, such as a button on the ATEM itself, changes the PGM source, I want Companion to reflect that *without* also affecting the PVW source.

**Comment by Julusian** [comment]
Are you referring to the latched state?

**Comment by mark-epstein** [comment]
Yes, if I understand your question, this would apply to a latch/toggle button that has actions for both the press/on and release/off states.  The button itself has a yellow highlight to tell the user it is on or off, but this only reacts to a press of the button.

If something changes in an external system, I want to be able to change the state of that yellow highlight.  I can do that currently using (v2.1.2) a BANK-DOWN or BANK-UP but those UDP commands also trigger all the actions programmed into those buttons.  I want to change the button state without running those actions.

**Comment by fdebeer** [comment]
can it be done by a instant feedback? this only changes the buttoncolor, but not the button state.
