### ISSUE TITLE
[BUG] New GUI Tooltip/Popover Hint broken

### ISSUE THREAD

**Issue by istnv** [bitfocus/companion#1522]
When hovering over a button preset, the `label` value for a preset definition object used to show as a tooltip.
Due to some inconsistency between action, feedback, and tooltip inputs, I also tried `description` and `tooltip`.
Those do not work either. 
On further investigation I was unable to find any working tooltips.

**Comment by Julusian** [comment]
I have fixed this for presets, and added it for buttons in the main grid to show their number (eg 1.5).
Dropdown inputs in actions did not have a working tooltip, but the rest appear to be working. I dont know what module is best to test this with, but from the code it looks correct and they show when I force a value.

**Comment by istnv** [comment]
XAir has only 2 example presets. The tooltip describes the contents because their difference is feedback options.

**Comment by istnv** [comment]
I think the dropdown tooltip broke when select2 was added as default.

**Comment by Julusian** [comment]
I think all of this is done, let me know if there is something I missed and I can take another look
