### ISSUE TITLE
Companion started from Docker cannot access Stream Deck 

### ISSUE THREAD

**Issue by mathias-ewald** [bitfocus/companion#1525]
**Describe the bug**
When I start the companion application in a local instance of Docker, and pass through `/dev/bus/usb`, the companion app shows the error message `Found device, but no access. Please quit any other applications using the device, and try again.`. I am running on a fresh install of Ubuntu without any software that might potentially access the stream deck.

**To Reproduce**
1. Connect the Elgato Stream Deck to your computer
2. Run `docker run -d --name companion -p "127.0.0.1:8000:8000" -v /dev/bus/usb:/dev/bus/usb docker.pkg.github.com/bitfocus/companion/companion:latest` to deploy Companion
3. Look at the logs produced by companion in the UI

**Expected behavior**
No error message to appear and Companion to recognize the stream deck.

**Screenshots**
![2021-03-27_18-42](https://user-images.githubusercontent.com/35083480/112729397-29f22480-8f2c-11eb-9fdf-d1ad9d496266.png)

**Desktop (please complete the following information):**

```
➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 20.04 LTS
Release:	20.04
Codename:	focal
➜  ~ docker --version
Docker version 19.03.8, build afacb8b7f0
➜  ~ 
```

**Comment by Julusian** [comment]
I don't think this is a bug in companion, but an issue in the usb passthrough in docker being done wrong. If I add `--privileged` to the command then any streamdecks connected at startup will work fine. Any added after get the same issue you are seeing, which could be docker not passing through new devices properly.
I don't use usb devices in docker myself, so my knowledge of this area is very limited

**Comment by mathias-ewald** [comment]
@Julusian thanks, that did the trick. Yeah, it wasn't a problem with Companion itself but I didn't know where else to ask.
