### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lucazanutto** [bitfocus/companion#1526]
**Describe the bug**
Javascript error when starting the program
**To Reproduce**

**Screenshots**
![Immagine 2021-03-28 123247](https://user-images.githubusercontent.com/81512225/112749344-0b3e6d00-8fc2-11eb-8972-d825caf69888.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Companion Version v2.1.2

After this error appear, the application Crashed

**Comment by kraves-oz** [comment]
I'd suggest your db file has been corrupted. Deleting it in your %appdata% will probably solve it for you, and let companion rebuild it.

**Comment by lucazanutto** [comment]
i tried, deleted everything in% appdata% and reinstalled companion, but it still gives me the error on startup

**Comment by lucazanutto** [comment]
> I'd suggest your db file has been corrupted. Deleting it in your %appdata% will probably solve it for you, and let companion rebuild it.
