### ISSUE TITLE
Admin control keeps crashing

### ISSUE THREAD

**Issue by bpatel928** [bitfocus/companion#1527]
Hi,

I have noticed that the admin control keeps crashing and reloads itself every 20 seconds. I have attached an image that shows the error. I have also noticed that companion for some reason, floods my network with connections to OBS and is sending nothing but web-socket updates which seems to be causing network flooding issues and when a real trigger is actually sent, the trigger does not do all of the tasks within it. 

I noticed this this morning, where in my OBS logs, it shows these below lines every 2 seconds and then noticed that despite the trigger saying to unmute a mic, and OBS saying that the mic was muted, it did not actually mute. Now that portion is probably just a coincidence with OBS not actually un-muting the mic, but the web-socket updates are a bit concerning as that is alot of traffic to be pushing. I noticed that the below lines happened about 7:21:29 this morning, and then continued to show up in the logs until 7:42:19.... I am not sure what is causing the issue

07:22:25.035: }'
07:22:27.034: [obs-websocket] Update << '{
07:22:27.034:     "average-frame-time": 2.2665120000000001,
07:22:27.034:     "bytes-per-sec": 783805,
07:22:27.034:     "cpu-usage": 13.189216312914196,
07:22:27.034:     "fps": 30.000000300000007,
07:22:27.034:     "free-disk-space": 23180.00390625,
07:22:27.034:     "kbits-per-sec": 6123,
07:22:27.034:     "memory-usage": 846.015625,
07:22:27.034:     "num-dropped-frames": 0,
07:22:27.034:     "num-total-frames": 1733,
07:22:27.034:     "output-skipped-frames": 0,
07:22:27.034:     "output-total-frames": 1748,
07:22:27.034:     "preview-only": false,
07:22:27.034:     "rec-timecode": "00:00:57.766",
07:22:27.034:     "recording": true,
07:22:27.034:     "recording-paused": false,
07:22:27.034:     "render-missed-frames": 34,
07:22:27.034:     "render-total-frames": 3601,
07:22:27.034:     "replay-buffer-active": false,
07:22:27.034:     "strain": 0.0,
07:22:27.034:     "stream-timecode": "00:00:57.766",
07:22:27.034:     "streaming": true,
07:22:27.034:     "total-stream-time": 57,
07:22:27.034:     "update-type": "StreamStatus"
07:22:27.034: }'

![image](https://user-images.githubusercontent.com/65842482/112758787-18f1f380-8fbe-11eb-846b-d28e0cde2d08.png)

**Comment by Julusian** [comment]
For the crashing, is the ui in the current tab?
does the log in the ui show anything indicating that companion may have restarted? 

For the 'flooding' how much data is actually being sent? It is very normal to be sending a chunk of data  between companion and the software/hardware being controlled up to a couple of times a second, to be able to monitor the status of things and have the data needed for feedbacks.
Unless it is many times a second (more than 5) or the bandwidth used is many megabits then it is nothing to worry about.

As for things not working, I dont know why that would be. could be a bug

**Comment by fdebeer** [comment]
Are there instances not connecting or switched off? I had crashes of the GUI when not all instances where active. disable these instances and check if the crashes still occur.

**Comment by Julusian** [comment]
There isnt enough information here to work from, if more is provided it can be reopened
