### ISSUE TITLE
Page Change on "Current Surface"

### ISSUE THREAD

**Issue by cookdoeyl** [bitfocus/companion#1528]
When using "internal: Set surface with index to page", Surface is set to 0, and Page is set to anything (I use "Back"), the surface does not change. Setting an index works, just not the current surface 0 function.

**Comment by cookdoeyl** [comment]
I'm running 2.2.0 (2de83aa4-3196) with a StreamDeck XL

**Comment by istnv** [comment]
Surface 0 is the emulator.

**Comment by cookdoeyl** [comment]
No.... this can't be. I thought I've always used it as "current surface". If not, then it was "bugged" when I found that feature, and I really liked it that way.

Also, if we use the "internal: Set surface with s/n to page" and select "current surface", that also does not work.

**Comment by istnv** [comment]
Surface by index has always used 0 as the emulator.
I just tried surface to s/n `This surface`. It works as expected with the emulator and a 15key streamdeck.
We need more information as to why yours doesn't work.

**Comment by istnv** [comment]
Surface by Index and Surface by serial number are recent additions.
Originally a single choice, it looks like the original 'Current surface' did not properly convert.

**Comment by istnv** [comment]
The original `Set surface to page` should have appeared in the new version as `Set surface with s/n to page` which uses the same information for selecting which surface.

**Comment by cookdoeyl** [comment]
Sorry, I did forget to mention I use a StreamDeck XL.

I use a regular button to change pages to a "sub page" in my mind, then I use a regular button set to "Back". Both are s/n based internal commands with "Current Surface" as the surface. The first page change works, so it more or less seems as a problem with the "Back" function with current surface.

**Comment by istnv** [comment]
There is an issue with the 'forward' and 'back' history not working properly.

**Comment by istnv** [comment]
I tried several recent 'releases' and  I can not find any version where this worked properly, using "Current" or a specific deck. Forgive the commentary but I'm also documenting what is going on now and how it should work before trying to fix anything.

The way the page history is working now:

- 'Special' up/down page buttons do not affect page history
- Go to 'Page' adds the destination 'Page' to the history list (but not the source page)
- 'back' and 'forward' step to the previous or next page in the list

The start page with the 'Go To' is not saved so 'Back' has no record of where to go 'back' to.

**Comment by istnv** [comment]
There is a patch in to modify the page history so it responds closer to what you expect.

**Comment by Julusian** [comment]
Yep, this is correct in that #0 is the emulator. To change the current surface you can use the 'Set surface with s/n to page' action instead
