### ISSUE TITLE
[BUG] ENOENT error on load, Companion unresponsive, boot loop

### ISSUE THREAD

**Issue by YuletideMedia** [bitfocus/companion#1540]
Describe the bug:
When loading Companion and launching the GUI, an error is produced in the Warnings area. The interface loads, but neither buttons on the StreamDeck nor the emulator function when pressed. Eventually, it locks up saying "Houston we have a problem...", attempts to reload, and the cycle continues.

Steps to reproduce:
1 - Load Companion
![01](https://user-images.githubusercontent.com/81788536/113376797-2a2d5e00-9338-11eb-8643-b97dc9264240.png)
(I have tried differing port numbers and have disabled my PC's firewall - I'm on a closed network)

2 - Wait for load, error is produced in Warnings area:
![02](https://user-images.githubusercontent.com/81788536/113376844-53e68500-9338-11eb-8106-1b605855b949.png)

Text of the error is as follows:
01. 21:40:43 CORE(cb): db.tmp->db failed: Error: ENOENT: no such file or directory, rename 'C:\Users\ATEM Control\AppData\Roaming\companion\db.tmp' -> 'C:\Users\ATEM Control\AppData\Roaming\companion\db'

3 - Waiting further, the interface locks up with a "Houston we have a problem" message, eventually reloads the page, and returns to #2 above in an infinite loop.
![03](https://user-images.githubusercontent.com/81788536/113376907-7d071580-9338-11eb-8dcb-90b9f2b5b76d.png)

Expected behavior:
Load Companion, operate as normal.

OS: Windows 10
Browser: Chrome
Companion Version: 2.1.2

Additional Context:
I previously was running this on a Windows 8 laptop that was starting to die. I exported the configuration from the laptop and was able to successfully import the config to the Windows 10 machine and run it during that session. After shut down and reboot, the issues began.

Attempting to control an ATEM Mini Pro ISO with the StreamDeck/Companion.

Please forgive me if something is incorrect or incomplete. I'm relatively new to Companion. This is my first post/issue.

**Comment by kraves-oz** [comment]
I would delete either the whole C:\Users\ATEM Control\AppData\Roaming\companion folder or just the db and any tmp files and try again.  Sounds like the config files might have corrupted. Export your pages first and screenshot or remember your instances to recreate.

**Comment by Julusian** [comment]
Did you manage to resolve this?
I don't think that `ENOENT` line will be the cause here, I see that at startup in my setup.
Perhaps you could share your config at it sounds like something in it is causing the issue

**Comment by Julusian** [comment]
It looks like something is wrong with the db, but without a copy there isnt anything we can do to prevent/fix it
