### ISSUE TITLE
Feature Request: Ability to select items in drop-down menus using keyboard input

### ISSUE THREAD

**Issue by Gartom** [bitfocus/companion#1541]
**Describe the feature**
When configuring a button and selecting something in a drop-down in the GUI, it would be beneficial to get right to the selection using keyboard input.

**Usecases**
E.g. when selecting a preset for a PTZ camera, it gets tedious to scroll down to high numbers when setting up lots of presets. It would be so much easier to write e.g. 212 on the keyboard to select preset 212 instead of scrolling in the dropdown:
![bild](https://user-images.githubusercontent.com/4034632/113413240-75885080-93ba-11eb-9a91-243b13cca6e2.png)

**Comment by Julusian** [comment]
It is possible for module authors to enable searching in the dropdowns, but they need to be aware of the need. 

A simpler fix here could be to make it so that the dropdowns will always enable search mode once they reach a certain length

**Comment by Hirte666** [comment]
Got the same problem in OBS--  over 60 Sourches..   and there are  Not sorted.

**Comment by bryce-seifert** [comment]
@Hirte666 I'll work on adding sorting to the OBS module dropdowns!

Trying to find an example of a module allowing search in the drop downs as well so that can be implemented.

**Comment by Julusian** [comment]
@bryce-seifert Setting `minChoicesForSearch` to a number on the option definition will allow for searching

https://github.com/bitfocus/companion/blob/master/instance_skel_types.d.ts#L94

**Comment by Gartom** [comment]
Thanks @Julusian for pointing out the `minChoicesForSearch` property. I added that in the PTZOptics module were I wanted the functionality and it works perfectly.

**Comment by Julusian** [comment]
Any dropdown which has more than 10 options (chosen arbitrarily, please provide feedback if you feel that threshold is too high or low), will now allow for searching.
Modules can override this number to be higher or lower if they desire
