### ISSUE TITLE
with instant feedback, only change background or textcolor.

### ISSUE THREAD

**Issue by fdebeer** [bitfocus/companion#1543]
**Describe the feature**
If i program an 'instant feedback' i can for some instances select a color for text and background. 
if i want to keep the textcolor for the button and only change the background, this is not possible now.
same with keep backgroundcolor, and only change textcolor.
the feature i would like is to only select backgroundcolor or textcolor to change with instant feedback

**Usecases**
for a ptz-cam i program 8 buttons on a row for presets. when a preset is active i change the color of the text to green, and the rest to white
with tally-arbiter i change the background of this row of buttons to red when this cam is on program, but the buttontext also changes to the preset in this feedback. I would like to keep the color of the active preset-button on green.

**Comment by Julusian** [comment]
This isnt something that can be easily done currently. Those color picker fields are created by the modules for each feedback they expose, so they would have to create multiple versions of each feedback with different combinations of these colour fields (or have a way of telling them which ones to use)

I think this falls under a more general task to rework how the feedbacks work, to allow for more control over what changes from the feedbacks. perhaps #1205 or #1187 but neither quite matches what I am thinking of as a first step

**Comment by fdebeer** [comment]
> This isnt something that can be easily done currently. Those color picker fields are created by the modules for each feedback they expose, so they would have to create multiple versions of each feedback with different combinations of these colour fields (or have a way of telling them which ones to use)

in case of tallyarbiter,it could be a feedback like 
'tallyarbiter,device in preview or program-textcolor'
and
'tallyarbiter,device in preview or program-backgroundcolor'
or add a color 'none' to the colorlist? (if that is possible...)
