### ISSUE TITLE
[FEATURE] Automatically resize button images that exceed maximum dimensions

### ISSUE THREAD

**Issue by estilles** [bitfocus/companion#1545]
**Describe the feature**
At the moment, when uploading a button image that is larger than 72x72 we get an error message indicating;
`Image must have the following dimensions: 72x72`.

I propose automatically resizing such images the maximum dimensions if any of the following conditions are met:
- image width is greater than max width, or
- image height is greater than max height

**Usecases**
Not a necessity, just a time saver. I recently acquired a stream deck icon pack, but all the icons are 288x288. 

---

PR to follow, but I do have a question. Should I be submitting the PR against the new React WebUI, the legacy UI or both?

**Comment by Julusian** [comment]
Implemented in #1546

**Comment by kjetilpp** [comment]
I have a similar issue, use icons from materialdesignicons.com that are 48x48, on the Stream deck Elgato software it works fine, but migrating to Companion we have a problem with "Image dimensions must be at least 72x58"
Maybe auto resizing small icons too?

**Comment by estilles** [comment]
Hey @kjetilpp, that's an interesting use case. I never thought of upscaling smaller images/icons. Does the native Stream Deck software display icon as-is at 48x48 (padding the image to fill) or does it upscale it?

**Comment by kjetilpp** [comment]
I think it’s using 48x48 as-is, the icons
in \AppData\Roaming\Elgato\StreamDeck\ProfilesV2\XX.sdProfile\Profiles\XXX.sdProfile\X.X\CustomImages
is still at 48x48, if i change the icon directly in the folder, is changes
on the stream deck.

**Comment by estilles** [comment]
Okay. I'll look into this. This issues was closed months ago. I suggest you create a new ticket with a feature request so we can track the progress.

**Comment by kjetilpp** [comment]
Done #1774
