### ISSUE TITLE
Can not connect to ProPresenter 7.4.2[BUG]

### ISSUE THREAD

**Issue by l2r** [bitfocus/companion#1551]
When i installed the newest Version of ProPresenter (7.4.2), i can't connect Companion to ProPresenter.
In the Logs i got the Error-Message:

 instance(propresenter): Remote application protocol out of date. Update application

I think they updated the Remote-protocol of ProPresenter.

**Comment by McHauge** [comment]
@l2r please try the 2.2.0 beta's or downgrade your ProPresenter version, from what I can see this should already be fixed in the beta :)

on another note, please post module issues on the specific module :)

**Comment by l2r** [comment]
Thanks for your reply. Downgrade works fine, furthermore i'll give the 2.2.0 beta a try.
