### ISSUE TITLE
[BUG] Error on Web/Mobile Page when using mobile device with new UI

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#1553]
**Describe the bug**
"Can't find variable: IntersectionObserver" when looking at Web/Mobile Page on iPhone

**To Reproduce**

1. Open WebUI on mobile browser (only tested on iPhone so far)
2. Select New UI then Web/Mobile
3. See error

**Expected behavior**
No error! (Works fine on desktop)

**Screenshots**
![IMG_4EDF0620DD93-1](https://user-images.githubusercontent.com/29129658/113935697-0fce0700-97b4-11eb-9ec9-bcb4f2bddc3e.jpeg)

**Desktop (please complete the following information):**

- OS: iOS 14.4.2
- Browser: Safari
- Companion Version Today's build

**Additional context**
Haven't tried iPad or other mobile device yet.

**Comment by Julusian** [comment]
I am not having any luck reproducing this currently. 
But I have added a polyfill so hopefully this will work now.
Please retest and let me know if it now works

**Comment by MeestorX** [comment]
Looks like it's working fine now. Thank you!
