### ISSUE TITLE
Latest ProPresenter7 ver7.4.2 Instance Connect Error

### ISSUE THREAD

**Issue by ChapelhillChurch** [bitfocus/companion#1555]
Running latest version from Renewed Vision ProPresenter7 ver 7.4.2
Running latest companion version 2.1.2
Running on iMac iOS 10.15.7
Stream Deck firmware is latest at 1.00.008
Stream Deck Software is latest at 4.94

We use buttons to trigger various operations in PP7.

Was working great until iMac and ProPresenter7 were updated last week.

Now we get the following error in the companion debug log:

08. 10:08:59 instance(propresenter): Remote application protocol out of date. Update application

Anyone else having this issue?  We've removed the PP7 instance and started from scratch with same results.

**Comment by Kmeeks877** [comment]
Hello, 

I ran into the same issue. I downgrade my PP7 back to 7.4.1. I am also running iMac iOS 10.15.7

**Comment by kraves-oz** [comment]
Either downgrade PP7 or upgrade companion to the current beta which has support.

**Comment by josephdadams** [comment]
This is fixed in latest beta.

**Comment by ChapelhillChurch** [comment]
Thank you guys.  Went to Beta and all is working beautifully.  Great and timely responses.  Appreciate it!
