### ISSUE TITLE
Feature request: Add an indication in the color picking palette which color that already is selected (if it is visible in the palette).

### ISSUE THREAD

**Issue by Gartom** [bitfocus/companion#1557]
**Describe the feature**
Add an indication in the color picking palette which color that already is selected (if it is visible in the palette).

In the old WebUI, it was possible to see when e.g. a button background color was selected from the color palette:
![bild](https://user-images.githubusercontent.com/4034632/114308968-e54ab980-9ae5-11eb-8e3d-f6a0ece53d45.png)

In the new WebUI this is not visible:
![bild](https://user-images.githubusercontent.com/4034632/114309033-188d4880-9ae6-11eb-8416-d90411fb1c14.png)

**Usecases**
When picking colors from the palette for buttons it is sometimes good to select exactly the same color as other buttons. A clear indication which color from the palette that is used makes the selection easier.

**Comment by Julusian** [comment]
This could be a bit fiddly to do as it looks like [the library](https://github.com/casesandberg/react-color) we are using for the colour picker does not support this

**Comment by fdebeer** [comment]
use less colors in the colorpicker. (see my comment in the issue above this one)
it makes it more easy to find the color you used before

**Comment by Julusian** [comment]
The number of color options was reduced a couple of releases back, and the picker now indicates the current color when possble:
![image](https://user-images.githubusercontent.com/1327476/202919769-04ebb6fb-e2af-4657-9d90-eaa08283f8a7.png)
