### ISSUE TITLE
Colour picker preset selection

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion#1558]
**Describe the feature**
The colour picker in the new ui has the same set of preset colours as the old ui, but they do not work well in the layout.

Either the selection of colours should be changed to fit better, or the layout of the picker should be adjusted to have more columns of colours

![image](https://user-images.githubusercontent.com/1327476/114309809-7454d300-9ae0-11eb-8010-8b5993aa8a9b.png)

**Comment by fdebeer** [comment]
In my opinion there are too many colors in the picker. 3 rows of colors should be enough. it takes to much place in the GUI now, and it's easier to find the right color with less colors. (btw: there are only 32 buttons on an XL, so why 128 colors on the picker...)
also to close the colorpicker, you have to click on the colorbutton again. better and faster to click next to the box to close, like in the old GUI
