### ISSUE TITLE
[BUG] Remote triggering not working on windows in beta release

### ISSUE THREAD

**Issue by webby123** [bitfocus/companion#1559]
There is no remote triggering possible in the latest beta release companion-2.2.0-e91c8249-3241-win64.exe
It gives an refuse connection.
In the latest stable version it works fine.
This issue is found in the windows release, the mac version is okay.

**Comment by Julusian** [comment]
Is this connecting to companion over TCP?

Does it work after a restart of windows?

**Comment by webby123** [comment]
It is appearing when i send a http request, for example when i type in a chrome browser http://127.0.01:8000/press/bank/94/1/  i receive on the mac version ok as result and on windows an connection error, als after restarting windows.

**Comment by Julusian** [comment]
This sounds like companion is listening on the wrong interface or something. The `http://127.0.01:8000` portion should be the same as what you use to access the ui
