### ISSUE TITLE
Bug: Regex checking of option values doesn't work when there is a default value

### ISSUE THREAD

**Issue by dnmeid** [bitfocus/companion#156]
The regex checking in the option fields of the instance configuration is working if there is no default value given but not working if there is a default value given.
Example: Livecore-IP is not working, PDS-IP is not working, PVP-IP is working, Watchout-IP is working...

**Comment by josephdadams** [comment]
@dnmeid purely because this is an old request, can you confirm it is still a bug?

**Comment by josephdadams** [comment]
@dnmeid are you still getting this issue in the latest build?
