### ISSUE TITLE
Feature Request - Loop while button is pressed

### ISSUE THREAD

**Issue by jmcc94** [bitfocus/companion#1563]
**Describe the feature**
Would it be possible to create a 'loop' action that can be used while a button is pressed, that will go back to the start of the actions for that button.

May also need a 'cancel loop' action, either to be used as part of the button pressed, or as part of the button released action.

**Usecases**
Using a long press on a button to continually increase/decrease a fader volume until the button is released

**Comment by istnv** [comment]
It has already been done. Set one up like this: (Press 'This' and Abort 'This' are new features in the Beta builds)
![image](https://user-images.githubusercontent.com/51003420/114787750-21278e00-9d35-11eb-8d5b-984c21a97014.png)
![image](https://user-images.githubusercontent.com/51003420/114787776-2b498c80-9d35-11eb-952b-55ebaf917dcc.png)

**Comment by jmcc94** [comment]
Ah... didn't think about using that...

Thanks
