### ISSUE TITLE
[BUG] StreamDeck lost connection / can't be found in 2.2.0-65e2c336-3251 when VLC started on boot automatically

### ISSUE THREAD

**Issue by ondrejvysek** [bitfocus/companion#1564]
Testing the latest build 2.2.0 (2.2.0-65e2c336-3251) with latest PI updates. After the reboot, StreamDeck is disconnected in about 30 seconds. When I try to rescan USB, StreamDeck is found, but disconnects (sometime immediately, sometime in 30sec)
Now I've seen that the web service on the PI has restarted itself:

> Houston, we have a problem!
> It seems that we have lost connection to the companion app.
>
> Check that the application is still running
> If you're using the Admin GUI over a network - check your connection

At the moment I can see 2 surfaces, but Elgato is not detected. Or StreamDeck not detected at all (but was visible to the Companion after the boot)

> | #0 | emulator | Elgato Streamdeck Emulator |  
> | #1 |  

This was ok in the 3241 build. The emulator is working fine.
Node version 12.22.1

**Comment by ondrejvysek** [comment]
Did some testing, it seems this is caused by the pressing buttons - does not matter if physically on the StreamDeck or in the emulator or as a test action. if the buttons are not touched, the connection remains fine.

**Comment by ondrejvysek** [comment]
Did another test:

1.  a completely fresh install
2. installed GUI & additional apps (VLC, Samba) `sudo apt install lightdm xfce4 xfce4-terminal rc-gui vlc samba samba-common-bin`
3. restored previous config

behavior is as explained in the first post. It seems to be a VLC related problem (?)

**Comment by ondrejvysek** [comment]
After removing VLC from the Raspi `sudo apt-get remove 'vlc*'` Companion seems to be working as expected (no disconnects so far), most probably it is related to the VLC.

**Comment by Julusian** [comment]
I don't see how this could be related to vlc. I have been running companion on linux with vlc installed for months without issue.

Is there anything in the companion log (not the one in the ui) giving an indication as to why it is failing?

**Comment by istnv** [comment]
I have both running and have no problem.
Does VLC automatically play video on startup? 
This resembles a Pi power problem.

**Comment by ondrejvysek** [comment]
I had no issues at all prior 3251 build for a year. Even now when I downgrade to the older build in the CompanionPi everything works fine. I’ll try to rebuild and check the debug log again.

there is no autoplay.

**Comment by ondrejvysek** [comment]
Installed from the scratch now 2.2.0 (2.2.0-ef198718-3270) - different SD card. 

here is the log:

> 21.04.21 12:10:09 device(CL35J1A02645): fillImage failed: TypeError: Cannot write to closed device
> 21.04.21 12:10:09 device(CL35J1A02645): fillImage failed: TypeError: Cannot write to closed device
> 21.04.21 12:10:09 device(CL35J1A02645): Clear deck failed: TypeError: Cannot write to hid device
> 21.04.21 12:10:07 device(CL35J1A02645): Elgato Streamdeck XL device disconnected
> 21.04.21 12:10:07 device(CL35J1A02645): fillImage failed: TypeError: Cannot write to hid device
> 21.04.21 12:10:05 device(CL35J1A02645): Button 1.11 released
> 21.04.21 12:10:05 device(CL35J1A02645): Button 1.11 pressed
> 21.04.21 12:10:04 device(CL35J1A02645): Button 1.11 released
> 21.04.21 12:10:04 device(CL35J1A02645): Button 1.11 pressed
> 21.04.21 12:10:03 device(CL35J1A02645): Button 1.11 released

After rescanning the surfaces:
> 21.04.21 12:11:44 device(CL35J1A02645): Elgato Streamdeck XL detected

While pressing buttons not related to the VLC, everything seems to be fine:
> 21.04.21 12:12:51 device(CL35J1A02645): Button 1.13 pressed
> 21.04.21 12:12:50 device(CL35J1A02645): Button 4.25 pressed
> 21.04.21 12:12:49 device(CL35J1A02645): Button 4.7 released
> 21.04.21 12:12:49 device(CL35J1A02645): Button 4.7 pressed
> 21.04.21 12:12:49 device(CL35J1A02645): Button 4.6 released
> 21.04.21 12:12:48 device(CL35J1A02645): Button 4.6 pressed
> 21.04.21 12:12:48 device(CL35J1A02645): Button 4.3 released
> 21.04.21 12:12:48 device(CL35J1A02645): Button 4.3 pressed
> 21.04.21 12:12:47 device(CL35J1A02645): Button 4.4 released
> 21.04.21 12:12:47 device(CL35J1A02645): Button 4.4 pressed
> 21.04.21 12:12:46 device(CL35J1A02645): Button 4.5 released
> 21.04.21 12:12:46 device(CL35J1A02645): Button 4.5 pressed
> 21.04.21 12:12:44 device(CL35J1A02645): Button 1.24 pressed

Once the VLC button is pressed:
> 21.04.21 12:12:55 device(CL35J1A02645): fillImage failed: TypeError: Cannot write to closed device
> 21.04.21 12:12:55 device(CL35J1A02645): fillImage failed: TypeError: Cannot write to closed device
> 21.04.21 12:12:55 device(CL35J1A02645): fillImage failed: TypeError: Cannot write to closed device
> 21.04.21 12:12:54 device(CL35J1A02645): fillImage failed: TypeError: Cannot write to hid device
> 21.04.21 12:12:53 device(CL35J1A02645): Elgato Streamdeck XL device disconnected
> 21.04.21 12:12:53 device(CL35J1A02645): fillImage failed: TypeError: Cannot write to hid device
> 21.04.21 12:12:52 device(CL35J1A02645): Button 3.3 pressed
> 21.04.21 12:10:03 device(CL35J1A02645): Button 1.11 pressed
> 21.04.21 12:10:03 device(CL35J1A02645): Button 1.11 released
> 21.04.21 12:10:03 device(CL35J1A02645): Button 1.11 pressed
> 21.04.21 12:10:02 device(CL35J1A02645): Button 1.11 released
> 21.04.21 12:10:02 device(CL35J1A02645): Button 1.11 pressed

One (strange) thing - I have VLC set as autostart after boot `/home/pi/.config/autostart/vlc.desktop` after removing and rebooting, it looks good - will do more testing later

**Comment by ondrejvysek** [comment]
Tested today to start VLC as a systemd service result is the same, VLC is running, after few button presses, Elgato is disconnected

```
21.04.22 09:47:57 device(CL35J1A02645): fillImage failed: TypeError: Cannot write to closed device
21.04.22 09:47:55 device(CL35J1A02645): Clear deck failed: TypeError: Cannot write to hid device
21.04.22 09:47:54 device(CL35J1A02645): Elgato Streamdeck XL device disconnected
21.04.22 09:47:54 device(CL35J1A02645): fillImage failed: TypeError: Cannot write to hid device
21.04.22 09:47:52 device(CL35J1A02645): Button 3.2 released
21.04.22 09:47:52 device(CL35J1A02645): Button 3.2 pressed
21.04.22 09:47:52 device(CL35J1A02645): Button 3.3 released
21.04.22 09:47:51 device(CL35J1A02645): Button 3.3 pressed
21.04.22 09:47:50 device(CL35J1A02645): Button 3.4 released
21.04.22 09:47:50 device(CL35J1A02645): Button 3.4 pressed
21.04.22 09:47:47 device(CL35J1A02645): Elgato Streamdeck XL detected
```

This was working without any issues prior to build 3251. Any ideas on how to autostart VLC to make Streamdeck working?

**Comment by istnv** [comment]
Can you make a backup of the sd card that I can copy to a card and load here? 
I just completely reloaded companion on my Pi to build 3260 and vlc and 2 streamdecks attached run fine.

**Comment by ondrejvysek** [comment]
I'll prepare backup later - how are you starting VLC?

**Comment by istnv** [comment]
I put it into a background task from the shell. I have both 15 and 32 button streamdecks attached.

**Comment by Julusian** [comment]
@ondrejvysek Running on a pi 4?
Is vlc playing media from a usb drive?
Is the streamdeck in the usb2 or usb3 ports? (black or blue)

**Comment by ondrejvysek** [comment]
OK, I'll try it. I'm using:

I'll try to make image from this config

```
mkdir /home/pi/.config/autostart
nano /home/pi/.config/autostart/vlc.desktop
```

File content:
```
[Desktop Entry]
Type=Application
Name=VLC
Exec=cvlc --http-password Passw.. --no-playlist-autostart --no-osd --fullscreen --start-paused --play-and-pause /home/pi/Videos
```

When I start the VLC as the Companion command it seems to be fine.

**Comment by Julusian** [comment]
I've just double checked, and the `TypeError: Cannot write to hid device` error is being thrown by underlying usb library. So it doesnt appear to be something companion is doing wrong.

What psu are you using? could you try with another? or connect the streamdeck via a powered usb hub.

I am wondering if this is a power issue. When vlc is open and playing a video that will increase the power draw of the cpu, which with an underpowered psu could not leave enough power for the streamdeck

**Comment by Julusian** [comment]
I can't explain why it would have started around that commit, the serialport lib change should have no effect on anything other than windows

**Comment by ondrejvysek** [comment]
I'm using the original 3A Raspberry PSU. Tested now with externally powered hub - same behavior: after a while, Streamdeck disconnected. What I don't understand is that this is happening only when VLC is started via autostart. When started manually there is no problem at all.

I'll try to play around starting as a service or find a completely different way.

**Comment by ondrejvysek** [comment]
Hm... when using Unit file for systemd, with exactly the same as for desktop:

```
[Unit]
Description=VLC
After=multi-user.target

[Service]
User=pi
ExecStart=cvlc --http-password Passw.. --no-playlist-autostart --no-osd --fullscreen --start-paused --play-and-pause /home/pi/Videos
KillMode=process
Restart=always
RestartSec=10s

[Install]
WantedBy=multi-user.target
```
`sudo systemctl daemon-reload`
`sudo systemctl enable vlc.service`

It seems to be working fine (at least no disconnects so far)

**Comment by istnv** [comment]
As a service (instead of autostart) there may be just enough timing difference to the desktop that things are spread out (with less power draw at a single time)

**Comment by istnv** [comment]
@Julusian Is that also when the change from submodule to node_module happened? Companion startup is a lot faster and may be pushing the CPU. Just a thought.

**Comment by ondrejvysek** [comment]
@istnv  not sure it is related to the boot process - Elgato is connected, even for hours, until pressing the button.

**Comment by Julusian** [comment]
what model streamdeck?

**Comment by Julusian** [comment]
@istnv no, that was in 3145. a fair while ago.

**Comment by ondrejvysek** [comment]
@Julusian I don't think either - as it works when VLC is started in a different way (manually/as a service). I have XL

**Comment by jarodwsams** [comment]
The Raspberry Pi 3, really any model prior to the 4B, is not supported. The biggest reason is because before the 4B, the USB and network adapters (both wired and wireless) shared the same bus which causes the disconnect. The 4B has a redesigned PCB and the USB and Ethernet are now on separate buses. Get a 4B, slap your same microSD card in there, and see if you still experience the issues reported.

https://github.com/bitfocus/companion/wiki/Companion-on-the-Raspberry-Pi#companion-on-the-raspberry-pi---a-primer

**Comment by jarodwsams** [comment]
It sounds like you're running your Pi with a desktop environment installed. That, along with running VLC will increase the system load. One thing that must be considered with the Pi4 is the thermals. Do you have a fan running in your Pi case, or is it just cooling passively? If passive, that could explain the issue. Anything that increases the load on the system will increase the heat, and the system has a throttle built in based on temperatures. No telling what that thing will do when it kicks in.

**Comment by istnv** [comment]
I finally have some time to download your image. I try a boot with my XL on the Pi sometime tomorrow.

**Comment by jarodwsams** [comment]
Be advised, the pre-built image does not ship with a desktop environment. You'd need to add that yourself. There are examples in the wiki for a lightweight desktop environment. LightDM (desktop manager) and xfce (UI) were the recommendations when I wrote the instructions because they were the most lightweight options at the time. I have not revisited the topic in some time, though, so there may be more/better options out there. I'd start with LightDM and xfce and see if that does it for you.

https://github.com/bitfocus/companion/wiki/Manual-Install-on-Raspberry-Pi#adding-a-desktop-user-interface

**Comment by ondrejvysek** [comment]
@jarodwsams Pi has active cooling. I've installed LightDM and xfce manually as per instructions, components added on top of basic installation `sudo apt install lightdm xfce4 xfce4-terminal rc-gui vlc samba samba-common-bin`. As mentioned before - this issue exists only in case VLC is started automatically using .desktop. If started as a service (I'm ok with this) or manually everything seems to be fine. I don't think it is related to power consumption. 
Regarding the heat - .desktop file starts VLC only, no autoplay,...

**Comment by istnv** [comment]
@ondrejvysek I was able to work with this a bit today. I was able to cause a disconnect by pushing buttons while playback was running. The only explanation is power. The Pi USB can only power 1.2A max, but the Pi _itself_ draws some of that. With several tasks running at once and depending on the tasks, it will periodically lose power to drive the XL. The XL wil run (idle) displaying buttons easily. When you press buttons, more power is needed to send that information to the Pi. The XL draws almost the max the Pi can provide.

**Comment by ondrejvysek** [comment]
@istnv  This is happening even when streamdeck is connected via powered USB hub - tested 5 days ago https://github.com/bitfocus/companion/issues/1564#issuecomment-825154164.

**Comment by istnv** [comment]
I think you are running into the limit of how much can actually run at once on the Pi. Even through a powered hub, the XL has 32 buttons of graphics that render and refresh often: About 500k several times per second.

**Comment by ondrejvysek** [comment]
@istnv Thanks John, I'm giving up - it is working fine for me now when started as a service / or started manually. I understand the arguments you provide, but it is unclear to me, why this happens only in the case using .desktop startup. 

As a resolution should be a known issue - `VLC can't be started using .desktop file`.
