### ISSUE TITLE
Companion 2.1.2-f4bcaf3-2679 crashing ProPresenter 7.4.2 (117703185)

### ISSUE THREAD

**Issue by richardlock** [bitfocus/companion#1566]
When Companion 2.1.2-f4bcaf3-2679 tries to connect to ProPresenter 7.4.2 (117703185), it cannot connect.  There seems to be a mismatch with the ProPresenter Remote version.

It causes ProPresenter to crash and gives status ERROR for the instance in Companion.

It worked fine previously with ProPresenter 7.4.1. 

These are the logs.

15. 20:06:32 instance(propresenter): Stopping ConnectionTimer
15. 20:06:32 instance(propresenter): Remote application protocol out of date. Update application
15. 20:06:32 instance(propresenter): Opened websocket to ProPresenter remote control: 127.0.0.1:20562
15. 20:06:32 instance(propresenter): Stopping SDConnectionTimer
15. 20:06:32 instance(propresenter): Starting ConnectionTimer
15. 20:06:32 instance(propresenter): Stopping ConnectionTimer
15. 20:06:10 instance(propresenter): Stopping ConnectionTimer
15. 20:06:10 instance(propresenter): Remote application protocol out of date. Update application
15. 20:06:10 instance(propresenter): Opened websocket to ProPresenter remote control: 127.0.0.1:20562
15. 20:04:59 instance(propresenter): Opened websocket to ProPresenter remote control: 127.0.0.1:20562
15. 20:04:59 instance(propresenter): Starting ConnectionTimer

Thanks, Richard

**Comment by josephdadams** [comment]
This is fixed in the beta builds. You’ll have to use the beta if you want it to work. ProPresenter made this breaking change without any warning.

**Comment by richardlock** [comment]
Thanks Joseph.
