### ISSUE TITLE
Feature Request: Trigger random buttons on page for a time period

### ISSUE THREAD

**Issue by DachsbauTV** [bitfocus/companion#1567]
**Describe the feature**
I was just doing a test run with one of my devices when I had an idea: It would be great to have a trigger functionality that just presses random buttons on a specific page for a pre-definded time period.

**Usecases**
This could be used for 
- automated stress testing
- automated camera changes that feel natural
- automated playing of infos, lower thirds, etc.

**Comment by josephdadams** [comment]
This feels super niche. You could probably accomplish something like this with Triggers?

**Comment by Julusian** [comment]
I agree, I'm not sure this makes sense to have as part of companion and is likely to be enabled by accident and cause lots of confusion.
This would be very simple to implement as a standalone tool which fires osc/http/tcp commands at companion for whatever pages or buttons as desired

**Comment by Julusian** [comment]
I'm still not keen on this being a built in feature, and Im not convinced that 'on a specific page' will be enough control either. What if you want to avoid a couple of buttons because they not relevant to the test. Or you want to trigger buttons across two pages?

It would be much easier to write a crude script in js/python/bash/whatever to fire osc/http commands to trigger presses and get full flexibility on behaviour

**Comment by larryseyer** [comment]
I needed this functionality also, so I wrote something that will do this.

Make an HTML file with the following code in it:

```
<!DOCTYPE html>
<html>
<body onload="myFunction()">

<script>

let ip_address = "192.168.1.153" // ip address of companion
let page = 1 // the page of the button you want to trigger
let button_offset = 8 // if you want to trigger buttons 9-16 the add an offset of 8
let number_of_buttons = 16 // the number of random buttons you want to trigger
let button = Math.floor((Math.random() * number_of_buttons) + button_offset);
let this_url = "http://" + ip_address + ":8000/press/bank/" + page + '/' + button

function myFunction() {
  var x = document.createElement("IFRAME");
  x.setAttribute("src", this_url);
  document.body.appendChild(x);
}

</script>

</body>
</html>
```

Load this newly created HTML file into an OBS browser and refresh when it's loaded and disable when it's not active.

Bingo... works.
