### ISSUE TITLE
Sony VISCA tally light via ATEM

### ISSUE THREAD

**Issue by Desleur** [bitfocus/companion#1578]
**Describe the feature**
The tally light of a specific camara should turn on when the camera is on program in the ATEM and turn off when it's not. 

**Usecases**
We also have panasonic PTZ cameras and they already have this function.

**Comment by McHauge** [comment]
@Desleur you should probably upload this to the repo for the module you want it to be implemented ins, as this is only for the core and will therefore most likely get lost instead.

Just a heads up.
