### ISSUE TITLE
Intermittent GUI display issue of connection/instance information (possibly a dev environment limitation)

### ISSUE THREAD

**Issue by jrviz** [bitfocus/companion#1579]
Occasionally the connections panel has no connections (modules) shown in the right hand panel where a list of modules is expected. The search box is shown but it does not provide a search function.

In this state the presets panel on the buttons tab also shows "? (instance name)" instead of "module name (instance name)"

A refresh of the browser tab will reset to the expected state for bot connections and preset label display

This is possibly an artefact of running in yarn/headless as I have not seen this yet in normal install

**Comment by Julusian** [comment]
Duplicate of #1632
