### ISSUE TITLE
editing of button while atem mixer is offline

### ISSUE THREAD

**Issue by juergen-miessmer** [bitfocus/companion#1580]
Hello,
we do mobile productions, with means all our eqipment is stored, or set up on location.
I would like to be able to add atem:commands to a button while I'm in the office, where the atem mixer is not present.
But unfortunatly i can not choice commands "atem:  " as long as companian has no connection to the atem.
I'm not shure if this is related to the atem-module or to campanian itself. But it would be great to prepare companian to the next show, without having to bring in, unpack and setup the atem.

Thanks

Jürgen

**Comment by McHauge** [comment]
@juergen-miessmer If you go into the instance settings, chose what atem mixer you are using, instead of "Auto" this allows for "offline" programing of buttons :)

**Comment by juergen-miessmer** [comment]
@ McHauge  Thanks for reply.
It is not set to "Auto". 
It is set to the right atem version, witch is in this case "1 ME Production 4K"
But I can choose whatever atem model  I want, as long as there is no atem connected it's not possible to choose atem:... commands from the drop-down list "+Add key down/on action"

**Comment by McHauge** [comment]
@juergen-miessmer  Hmmm, it works fine here, but you have to have a dummy IP typed in, otherwise, it won't "start" the instance. I normally just use localhost for offline setups, so 127.0.0.1 in the IP field.

**Comment by juergen-miessmer** [comment]
@ McHauge
I changed the ip once and now it works, even if I change back to the IP witch was set before.
But after a new start of companian the problem remains.
Simply pressing "Apply changes" without changing anything will also do the trick.
So this workaround will do it for me.

Thank you

**Comment by Julusian** [comment]
I believe this is a bug that has been fixed in newer versions
