### ISSUE TITLE
[BUG] Stream Deck XL is not recognized since latest Windows 10 update

### ISSUE THREAD

**Issue by airbenich** [bitfocus/companion#1582]
**Describe the bug**
Since the latest Windows 10 Update release since round about 1 month, the companion software won't find the Stream deck XL. Only the Streamdeck Logo is displayed on the Streamdeck. Streamdeck App ist not installed.

**To Reproduce**
1. Update to the latest Windows 10 Update
2. Connect Streamdeck via USB
3. Start Companion
3. Companion won't recognize the Streamdeck.
4. Companion won't recognize the Streamdeck even when clicked "Rescan USB ...".

**Expected behavior**
Show the Companion UI on the Stream Deck

**Desktop (please complete the following information):**

- OS: Windows 10 latest Update
- Browser: Firefox
- Companion Version: 2.2 latest build

**Comment by Julusian** [comment]
I have just done a fresh install of Windows 10 20H2 (latest edition) and companion is able to connect to my streamdeck xl just fine.

Does the log in companion show anything when you press rescan?

**Comment by airbenich** [comment]
Thank you Julian!
You were right, the problem was on our side. Sorry for that & thank you for your support!
I had to remove all Companion folders in AppData to make it work again before reinstalling.
