### ISSUE TITLE
Control mouse and keyboard

### ISSUE THREAD

**Issue by jeremiasmanninen** [bitfocus/companion#1586]
**Describe the feature**
An amazing feature would be an ability to control a mouse and keyboard, like make keyboard and mouse move/click macros, in the companion.

**Usecases**
You can use it to control almost everything in computer. Programs and features that all couldn't be added to one platform would be "all in one" controlable.
- I would use it controlling obs plugins
- Automatically creating live streams to different platforms (youtube, facebook, instagram, twitter) and starting them by macros.
- Creating live video cuts in all the platforms at the same time.
- Sending the same chat message to all live stream chats.

With that feature, you can automate almost everything!

**Comment by Julusian** [comment]
The keyboard side of this is already possible when connecting to an instance of https://github.com/JeffreyDavidsz/VICREO-Listener. There doesn't look to be any mouse support, but it might be possible.

I dont think this makes sense to add to the core of companion, but is better suited as a module like vicreo-listener, as being built in will limit this to only be usable on the machine running companion, and many people will want to be able to control another machine.

**Comment by tobielepine** [comment]
> **Describe the feature**
> An amazing feature would be an ability to control a mouse and keyboard, like make keyboard and mouse move/click macros, in the companion.
> 
> **Usecases**
> You can use it to control almost everything in computer. Programs and features that all couldn't be added to one platform would be "all in one" controlable.
> 
> * I would use it controlling obs plugins
> * Automatically creating live streams to different platforms (youtube, facebook, instagram, twitter) and starting them by macros.
> * Creating live video cuts in all the platforms at the same time.
> * Sending the same chat message to all live stream chats.
> 
> With that feature, you can automate almost everything!


I have had some great results with robotask ... Even the Lite version is pretty powerful.
Robotask and Vicreo listener will give you the full automation you require. I use it for very complex tasks.....
Pro version is REALLY powerful with features like variables and If/Then conditions... I created a task today that required 154 steps...  capture2text brings that power even further... now you can even make automated "decisions" based on what's on screen.  Even the non-selectable text. Loops within robotask are awesome for that purpose.  I just wish there would be more feedback support for these dynamic variables.  Anyways, check out ROBOTASK....
