### ISSUE TITLE
Configuration Actions choice menu behavior

### ISSUE THREAD

**Issue by plocher** [bitfocus/companion#1587]
**Describe the feature**
As more instances are added, the Button Configuration page's `add new action` pulldown becomes long and unwieldy.  It would be easier to navigate if it was hierarchical - display a shorter a list of instance names, with a pull right for the actions associated for each instance.

This would eliminate the repeated scroll through all instances and actions to get to the acrions at the bottom of the menu

This UI pattern is especially difficult with a trackpad, where scrolling down through a menu longer than the window size invites inadvertent selection clicks...

**Usecases**

With 8 instances (a couple of ATEMs, a videohub, propresenter, mqtt and visca), the actions menu in the configuration has over 100 items in it...

This would turn getting to the last instance's actions from an error prone scrolling marathon into a simple swipe and click gesture...

**Comment by josephdadams** [comment]
duplicates #89
