### ISSUE TITLE
[BUG] image drawBorder and drawCornerTriangle breaking bug

### ISSUE THREAD

**Issue by thedist** [bitfocus/companion#1588]
**Describe the bug**
Both image.prototype.drawBorder and image.prototype.drawCornerTriangle from `./lib/image.js` attempt to draw graphics with a resolution of 72x58px, which by default is correct, but when the Companion setting `Remove the topbar on each button` is enabled the required size becomes 72x72px,

Because the border/corner indicators draw the wrong size image, it results in this breaking error:
`Error: Pixelbuffer of 12528 bytes is less than expected 15552 bytes`
(note that the received bytes is 72 x 58 x 3, where as the expected in 72 x 72 x 3)

**To Reproduce**

1. Enabled the `Remove the topbar on each button` setting 
2. Create an instance that utilizes drawBorder, or drawCornerTriangle, such as vMix
3. Add a feedback that utilizes the functions at fault, such as the vMix `Tally - Preview State` feedback, and configure the options to display a border or corner indicator.
4. Create the situation in vMix (or other module supporting these image functions) to trigger the issue.

**Expected behavior**
The two image functions should adjust the height of the image being generated based on the state of the enabling/disabling of the top bar setting.

**Desktop (please complete the following information):**

- OS: Win 10
- Companion Version: 2.2.0-bb5050a6-3272

**Comment by krocheck** [comment]
This is actually not an issue with the image library.  In vMix when the image is created it is taking the default raster of 72x58.  instead vMix needs to detect if topbar is removed or not and initiate the image object with 72x72 instead.  I have PR in the vMix repo with untested code that theoretically would resolve.
