### ISSUE TITLE
[BUG] Latch/Toggle Doesn't work with Stream Deck Plugin

### ISSUE THREAD

**Issue by jkhouw** [bitfocus/companion#1589]
**Describe the bug**
"Latch" does not work with elgato streamdeck plugin.  The button executes the key release as soon as the key is released. 

**To Reproduce**

1. Define a button in companion with "latch/Toggle" ticked
2. assign an action to key down/on like change button background color to red
3.  assign an action to key up/off like change button background color to black
4. run Stream Deck software with plugin installed.
5. Press "Test" actions in Companion Admin console - the button will latch and function properly.  
           You can see the button on device, in Companion Admin, and StreamDeck software will all have RED background.
    Press "Test" again to simulate unlatch and 
            You can see the button on device, in Companion Admin, and StreamDeck software will all have BLACK background.
            
6. **Press the physical button on the device** - the button will not remain RED.  If you hold it, it will stay red until you release it.

**Expected behavior**
Expected Latch/Toggle functionality to work with Stream Deck Plugin.  

**Screenshots**
Sample of button config I was testing with.
![image](https://user-images.githubusercontent.com/83513885/116800275-ac42ab00-aacd-11eb-918d-302ca103349c.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Pro/Build 19041.928
- Browser: Edge/Chrome/Firefox
- Companion Version 2.1.3 (6b6820cd-2696)

**Comment by Julusian** [comment]
I cant reproduce this issue in either 2.1 or 2.2. Assuming it has been fixed since this was reported
