### ISSUE TITLE
Crashes on load

### ISSUE THREAD

**Issue by bmacrow** [bitfocus/companion#159]
**Describe the bug**
Bitfocus crashes on launch with a javascript error. I believe it is due to a corrupt db file. Which means my show is lost :( Screenshot below:

![image](https://user-images.githubusercontent.com/1080846/42417174-c95cb6a0-827a-11e8-8226-db2903bfffaf.png)

**To Reproduce**
Run Companion.
Error occurs before initial config screen (where you change network interface.)
I believe it started occurring after PC lost power (so unexpected shutdown)

**Expected behavior**
Companion should load correctly. Only way to get companion to load is to delete the db file from the appuser folder (windows) however that means you lose all your customisations and have to start as though its a clean install.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 x64

**Additional context**
Have attached the (i assume) corrupt db file for error checking, zipped to allow message board upload.
[db.zip](https://github.com/bitfocus/companion/files/2173384/db.zip)

**Comment by willosof** [comment]
Sorry to hear this. 

You database file seems to be filled with 10747 nulls. No data at all, which is really weird. I don't really understand how this can happen in the first place. 

```
$ cat db.json |hexdump -C
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000029f0  00 00 00 00 00 00 00 00  00 00 00                 |...........|
000029fb
```

We have planned a fix for database corruption (it doesn't happen often unless the application crashes the same time as it writes), and it will come in the next version :) I'll make a backup feature as well to backup/load showfiles

**Comment by willosof** [comment]
This should do it in the future. If we're lucky :)

**Comment by tobya** [comment]
I had this issue today again.  In the end I had to delete the database which is stored in the windows Roaming folder.
