### ISSUE TITLE
Anyone working on control for Jands Vista3?

### ISSUE THREAD

**Issue by brad-c7** [bitfocus/companion#1590]
**Describe the feature**
A clear and concise description of what the feature does

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by josephdadams** [comment]
@brad-c7 As far as we know, there is no ethernet protocol or API for Vista, only midi control. However, midi control of Vista through Companion has been covered extensively. I have created a software product that partners with Companion that does this well. You're free to check it out on my personal website, [techministry.blog](http://techministry.blog).

Essentially, you send commands from Companion over the network to the program "midi-relay" which then receives the command and sends out that command on the Vista machine which will then respond to it to advance cues, etc. MIDI Show Control is also supported.
