### ISSUE TITLE
[BUG] when running on ubuntu lts on windows, companion doesnt start

### ISSUE THREAD

**Issue by yyy898** [bitfocus/companion#1595]
**Describe the bug**
i get this error:
![image](https://user-images.githubusercontent.com/479392/117566768-ea852f00-b0b8-11eb-8d24-91aaefea40ca.png)

**To Reproduce**

i followed the wiki and installed companoin using `git clone https://github.com/bitfocus/companion.git`

the i ran `./tools/update.sh`

then i tried `node headless`

and i got the error

**Expected behavior**
companion to start

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Companion Version latest

**Additional context**

**Comment by Julusian** [comment]
You need to run `./tools/build_writefile.sh` to generate the missing file
