### ISSUE TITLE
Can't execute script from Run Shell Script on Companion/Raspberry Pi

### ISSUE THREAD

**Issue by ZachRosing** [bitfocus/companion#1597]
I'm running Companion on a Raspberry Pi 4, and forgive me but I don't know what version I'm running. I only have a ? where the version number should be. I ran an update within the last two weeks.

I'm trying to execute the following script:

```
 #! /bin/sh
sed -i 's/color/crop/' /home/pi/.config/pcmanfm/LXDE-pi/desktop-items-0.conf
sed -i 's/color/crop/' /home/pi/.config/pcmanfm/LXDE-pi/desktop-items-1.conf
export DISPLAY=:0.0
pcmanfm --reconfigure
lxpanel --profile LXDE-pi
```

with the Run Shell Path command: bash /home/pi/restore.sh

I consistently get the error:

instance(internal): Shell command failed. Guru meditation: {"killed":false,"code":1,"signal":null,"cmd":"bash /home/pi/restore.sh"}

Both of the last two commands are causing the problem. The script runs as expected from the command line. I've tried every combination of putting sudo in front of the commands and in the shell path script. The scripts have execute permission.

Can anybody tell me what I'm doing wrong?

**Comment by Julusian** [comment]
If you havent figured this out, you could try putting something like `>> /home/pi/test.log 2>&1` on the end of the command in companion, then review the captured output to figure out what was wrong

**Comment by WoozleEffect** [comment]
I've been having this same issue.

I've added `>> /home/pi/test.log 2>&1` to the command, and the test.log file shows "Host key verification failed."
