### ISSUE TITLE
Bug on launch with 1.0.7

### ISSUE THREAD

**Issue by Deanbau** [bitfocus/companion#16]
**Describe the bug**
On launch of new version

**To Reproduce**
Just opened it up

**Expected behavior**
For there not to be a error on launch

**Screenshots**

![image](https://user-images.githubusercontent.com/39572328/40499482-181c6928-5f50-11e8-8d88-a98eedfc0e17.png)

**Desktop (please complete the following information):**
 - OS: 10.13.4

**Comment by Deanbau** [comment]
No instances able to be added

![image](https://user-images.githubusercontent.com/39572328/40499558-47baa398-5f50-11e8-9abe-8e8c94aa29f9.png)

**Comment by dnny** [comment]
Im having the same on startup
![screenshot 2018-05-24 19 04 37](https://user-images.githubusercontent.com/9256921/40499894-f717621e-5f8b-11e8-92fd-69d948c23a5c.jpg)

**Comment by willosof** [comment]
I think this problem was a onetimer
