### ISSUE TITLE
Corrupted (or too big?) PNG's = crash

### ISSUE THREAD

**Issue by willosof** [bitfocus/companion#160]
from the user with the problem:
[companion.zip](https://github.com/bitfocus/companion/files/2177048/companion.zip)

**Comment by haakonnessjoen** [comment]
It is fixed as it will not crash anymore. But if a user renames a BMP file to a PNG file, it will only silently ignore the invalid file, since the browser generates content-type from the file extension, and trusts it to be png. Might fix a more verbose fix in the future.
