### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by WoozleEffect** [bitfocus/companion#1600]
On startup, I get the following error:
![Screen Shot 2021-05-17 at 9 27 16 AM](https://user-images.githubusercontent.com/60011745/118513405-4b37eb80-b6f9-11eb-912f-1a4e332cc28c.png)
Once started, the app no longer has any of its layouts, and all connections/instances are gone. It also will not detect the stream deck.

**To Reproduce**
Happens every time I start companion.

**Desktop (please complete the following information):**

- OS: macOS Big Sur Version 11.3.1
- Companion Version v2.1.3

**Additional context**
Everything worked fine on Saturday. As far as I know, no updates were made to the OS or any apps during that time.

**Comment by fdebeer** [comment]
This doesn't look like a bug in companion, but more a problem with your setup/os/equipment/software.
Better to adres this in the facebookgroup. more people read there and more chance to get a fast responce.

**Comment by WoozleEffect** [comment]
Thanks!
Got help on the FB group.
Turns out my config files for companion had become corrupted.
I deleted companion, and deleted the companion folder in the library.
After a re-install, everything works again!
Thank you!
