### ISSUE TITLE
[Feature request] Add loop action (from start and backwards)

### ISSUE THREAD

**Issue by buffos** [bitfocus/companion#1601]
We use the time delay to fire different actions based on that delay. For example, we may increase volume by setting the volume in increments.

Here is a sample (with relative delays)

delay: 100ms  action: SetVolume 10
delay: 100ms  action: SetVolume 20

and so on

It would be nice to have an action

100ms internal: action: loop direction: from start OR backward

**Comment by Julusian** [comment]
If the device you want to control already supports relative level adjustments this can already be achieved with:
![image](https://user-images.githubusercontent.com/1327476/119539606-466fd900-bd84-11eb-8a56-6e9d0fe160e0.png)
![image](https://user-images.githubusercontent.com/1327476/119539633-52f43180-bd84-11eb-9cf7-970d80e86a52.png)

I don't think a loop action would be different to this, so I dont think there is anything to do here
