### ISSUE TITLE
[BUG] Importing configuration from 1.4.0 to 2.1.3

### ISSUE THREAD

**Issue by JamesFrank2525** [bitfocus/companion#1603]
When I import my full configuration exported from 1.4.0, the middle row is shifted one position to the left and the bottom one - two positions, which makes some functions disappear. I use the old 5x3 Streamdeck. Restarting the whole software doesn't help. I cannot import individual pages as ATEM from my configuration is visible as VideoHub.

**To Reproduce**

1. Install fresh copy of the Companion v2.1.3
2. Import configuration
3. Click "replace all"

**Expected behavior**
It should import everything as it was, but everything is messed up

**Screenshots**
![image](https://user-images.githubusercontent.com/32199685/119130667-cae6f280-ba38-11eb-8c2b-faccdaebd553.png)
![image](https://user-images.githubusercontent.com/32199685/119131548-e7375f00-ba39-11eb-94d6-5d41769ed8f6.png)

"4" should be under "4" and CUT also under "4".

**Desktop (please complete the following information):**

- OS: MacOS 10.14.6 Mojave
- Browser: Chrome
- Companion Version: 2.1.3

Unfortunately 1.4.0 is not available for download anymore. If I hadn't left old installer in my drive, I would be doomed now.

My config file:
[JFS-Mac-Retina.local_full-config_20210521-1152.companionconfig.zip](https://github.com/bitfocus/companion/files/6522221/JFS-Mac-Retina.local_full-config_20210521-1152.companionconfig.zip)

**Comment by Julusian** [comment]
The layout of this should be fixed with the 2.2 beta build 3344, but the actions and feedbacks on each button may be broken until #1610 is completed

**Comment by Julusian** [comment]
This should be resolved now for some modules. I am working through fixing the rest
