### ISSUE TITLE
[BUG] Import File Corrupt 

### ISSUE THREAD

**Issue by Beatboxx1** [bitfocus/companion#1605]
Running the latest Beta build (2.2.0) on both subsequent computers and have also replicated this issue running the latest non-beta build on both comps. I have tried full resets on both machines and have searched for the same issue and cannot find it anywhere, so I'd really appreciate your help with this.

When exporting the full configuration file from my MacBook pro (Big Sur 11.2.3) and then attempt to import this onto my Mac Mini M1 16gb (Big Sur 11.2.3) it tells me the file is corrupt. This corruption doesn't work the other way. I can happily import the exported config file from the Mac Mini on to the MacBook pro.  I've also tried an export/import on the Macbook pro and the file imports fine so it seems it's some sort of issue with the Mac mini. 

Thanks in advance, 
Danny

**Comment by Julusian** [comment]
Could you attach a copy of the broken export? 
That will help with figuring out the issue

**Comment by Beatboxx1** [comment]
Hey,

Appreciate you getting back to me so quickly. 

I’ve attached the export which only has a problem when importing to my other computer (Mac mini m1).

Thanks again,
Danny

**Comment by Julusian** [comment]
@Beatboxx1 I don't see the file. I have a feeling that files in email responses get lost

**Comment by Beatboxx1** [comment]
Hi @Julusian 

Seems I can't attach the file here either so I've included a dropbox link, I hope this is okay.

https://www.dropbox.com/s/7osxd0aucftqf9s/Dannys-MBP_full-config_20210525-1144%20%281%29.companionconfig?dl=0


Thanks,
Danny

**Comment by Julusian** [comment]
Its a bit picky about file types, zipping it works
[Dannys-MBP_full-config_20210525-1144 (1).zip](https://github.com/bitfocus/companion/files/6546620/Dannys-MBP_full-config_20210525-1144.1.zip)

**Comment by Beatboxx1** [comment]
[Dannys-MBP_full-config_20210525-1144 (1).companionconfig.zip](https://github.com/bitfocus/companion/files/6549108/Dannys-MBP_full-config_20210525-1144.1.companionconfig.zip)

**Comment by Beatboxx1** [comment]
How's that?

**Comment by Beatboxx1** [comment]
Hey I was just wondering if you have any sort of solution to this?

Many thanks,
Danny

**Comment by Julusian** [comment]
I have just given this a test myself, and it happily imports.
This is on my Mac Mini M1 16gb (Big Sur 11.3.1), with todays latest 2.2 beta
As well as working fine on my development machine, so I am not sure how to progress with this
