### ISSUE TITLE
[BUG] ATEM instance stop working after restart (marked as undefined)

### ISSUE THREAD

**Issue by Pierremck** [bitfocus/companion#1606]
**Describe the bug**
I have a CompanionPi installed on a Raspberry Pi4 with the 2.1.2 version of Companion. This is the latest build I can have with the companion-update command.
I have a ATEM instance with action set on a button but every time I restart the Raspberry this instance **stop working**. The instance is still in the instance list but the commands related to it are mark as *Undefined* and I can't add another command with this instance because it's not anymore on the commands list.
I don't know if this bug happens with others instances but I have an X32/GMA2/PJlink and they are working perfectly.

**To Reproduce**
Add an BlackMagic ATEM instance and create on button with a command related to this ATEM.
Restart the computer
You should have the same issue.

**Expected behavior**
The instance should stay up and the button should work.

**Screenshots**

![Atem Undefined](https://user-images.githubusercontent.com/17237130/119658479-7b843600-be2d-11eb-8464-3b8ea3d179ff.PNG)

**Desktop :**

- OS: RaspberryPiOS
- Companion Version 2.1.2

**Comment by Pierremck** [comment]
If i hit the "Apply change" button inside the instance settings and reload the page it's working again. But usually I don't have acces to the webpage in a normal utilisation. I think that because the Atem is not connected but this is because the button starts the ATEM so it can't be online at the Companion startup.

**Comment by Julusian** [comment]
I am pretty sure there is a 2.2 version of companionpi, which will also have that fix
