### ISSUE TITLE
[FEATURE] Trigger second color on X-Keys

### ISSUE THREAD

**Issue by MrXermon** [bitfocus/companion#1608]
**Describe the feature**
It would be great if not only the RED-Color on the X-Keys could be triggered by Companion. It looks like it's currently only possible to set the button-feedback to RED and it would be very useful to be able to use the second color (blue) to display a second (or third in case of counting no backlight, too) state.

**Usecases**
It just improves the integration in case of using a X-Keys as a input for a video-mixer (to display Live- and Preview-state).

**Comment by BenJamesAndo** [comment]
I have the XK-8 Stick and it only has a blue backlight. So support for blue would be wonderful for me.

**Comment by Julusian** [comment]
Testing with a XK-24 in the latest beta, I am able to control both the blue and red backlights.
Digging into the code, it looks like this is fully supported on all models with backlights, with varying rules.

For the stick, it looks like the backlight will be on when the bgcolor of the button is non-black. If any of red, green or blue is non-zero then the backlight will be on.

**Comment by BenJamesAndo** [comment]
Hey @Julusian I've tested it on my XK-8 stick using the very latest beta build for both Mac and Windows. I tried lots of different background colours, including red, green and blue. I couldn't get the blue LED backlight to stay on when the feedback colour was active.
