### ISSUE TITLE
Export Variable Triggers and Schedules

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion#1609]
Currently an Exported config file does not contain any Triggers or Schedules.

Similar to importing individual pages, it would be useful to be able to export/import ONLY the triggers, as well as the option to replace the entire configuration.

**Comment by obcocav** [comment]
This would be a great addition in my opinion!  I have setup a fairly extensive list of triggers as I used this to replace Windows Task Scheduler that was simply pressing Companion buttons anyway.  It would be huge to be able to back all of this up in one place.  Including custom variables.  Thank you!

**Comment by cbradburne** [comment]
+1

This would be an amazing enhancement. I hope this is implemented. 
Triggers can get quite complex, I wouldn't like to lose the settings and start from scratch.

**Comment by nick-rutter** [comment]
I'd really like this too! +1

**Comment by davidjoshuaford** [comment]
While this is still open, can I also add a request for Custom Variables to be exported/ imported as well? My config is becoming reliant on using custom variables to operate, so would like to be able to back this up & restore. Thanks!

**Comment by gerbenvandekraats** [comment]
+1

**Comment by jalmar2000** [comment]
I have been making a very big companion config we would like to share with every computer running companion(We have about 16) I would love to export my triggers and custom variables as well so a +1 from me. Has there been any update or work around of this?

**Comment by obcocav** [comment]
@jalmar2000 .  Copy and paste the entire Companion folder itself.  Works great.  Under Roaming on windows.

**Comment by jalmar2000** [comment]
@obcocav 

Do you know if this is also works from mac to windows?

**Comment by Julusian** [comment]
This is now possible in the 3.0 betas, and will import triggers from exports from 2.4 or later

**Comment by iosdeveloper** [comment]
@Julusian I'm running `3.0.0+5627-beta-3b7abf44` and triggers are disabled for import from a 2.4.1 file. It works fine for 3.0 files.
