### ISSUE TITLE
[BUG] Import fails from Mac version to Pi

### ISSUE THREAD

**Issue by MikeFumbler** [bitfocus/companion#1614]
Hi,

I have been using Companion on my Mac for quite a while. A very satisfying experience.

Today I switched to RPi4B/4GB. Companion Pi successfully starts and the UX is working in Chrome.
When importing my setup in Companion Pi from the Mac version, I got the 'Huston we've got a problem' screen and it reverts back to the import/export screen.

What goes wrong?

Thanks!

Kind Regards,
Mike.

**OLD SETUP:**
-Companion version 2.2.0 (2.2.0-fa0f2bdc-3347)
-MacBook Pro 2,4 GHz i5, late 2013, 8 GByte / macOS 10.14.6
-Chrome 90.0.4430.212
-StreamDeck XL

**NEW:**
-StreamDeck XL
-Raspberry Pi 4B/4 Gbyte
-image: CompanionPi-2021-04-14.img
-flashed via Balena Etcher to 64 Gbyte uSD
-Companion Pi 2.2.0 e198791d-3242

**Comment by MeestorX** [comment]
How big is your setup?
Test it with a smaller setup to see if it's a size issue.

**Comment by MikeFumbler** [comment]
> How big is your setup?
> Test it with a smaller setup to see if it's a size issue.

Thanks for your swift reply!
It is not that big: approx. 35 pages.
8 connections (software links and machines (BMD ATEM Mini Extreme) etc.
Of all buttons 75 of them have user graphics.

I am a bit anxious to make a new and smaller test setup in my Mac version.
Cause a lot of work went into making this setup work... ;-)

But a will overcome my fears and try a smaller export - import.

**Comment by MeestorX** [comment]
Sorry, I meant size as in MB. If it's full of pngs that might be the issue.

**Comment by MikeFumbler** [comment]
> Sorry, I meant size as in MB. If it's full of pngs that might be the issue.

My mistake! Sorry. The export is a 2,3 MB file.
As I just learned from the raspberry group on H2R's Discord: things go wrong when exporting files >= 1 MB on a Mac in version 2.2.0. The solution a user provided is: export in version 2.1.3 (stable non beta).

I'll try that.

**Comment by Julusian** [comment]
Try updating companion on the pi and trying again. I should have fixed this issue yesterday

**Comment by MikeFumbler** [comment]
> Try updating companion on the pi and trying again. I should have fixed this issue yesterday .
> 
> There was a limit of 1mb, which I changed to 100mb

Thanks! Great! Import works again.

But there are some issues with a few instances like OSC and H2R graphics. No communication.
And this error [Failed to load instance edit info: "TimeoutError: Timed out after 5s"] when clicking the edit button at those instances.

I will try to load new instances.
