### ISSUE TITLE
Latest Beta Triggers on Internal Feedback <> Not working [BUG]

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion#1615]
**Describe the bug**
When trying to trigger based on internal variable feedback time of day greater than or less than it does not appear to work.  = works fine.

**To Reproduce**
Create trigger based on feedback: Internal variable time.  Insert time with a < or > operator.  Does not function
Want to use Feedback of time in order to have multiple trigger types. (time and vmix variable both true)

**Desktop (please complete the following information):**

WIN64
latest beta

**Comment by Julusian** [comment]
Are you using the `internal:time_hms` variable?
The > and < operators expect single numbers currently, there is no special handling for times currently.

You could probably achieve the desired result by splitting the feedback up to use the three `internal:time_h`, `internal:time_m` and `internal:time_s` variables

**Comment by obcocav** [comment]
@Julusian .  Thanks for the reply and all the work yall do!  I was using hms.  I tried using the individual time components and it seems to work sporadically and I haven't seen it work with multiple variables.

My goal here is to only trigger a button when another button is pushed and it is past a certain time.  Thanks for your help!  Please let me know if I can help get this going.

**Comment by obcocav** [comment]
@Julusian .  To follow up.  Seems some work and some don't even breaking it down to parts of the time variable.  I have attached screenshots to illustrate.  Thanks again!  Let me know if I can help.

<img width="1440" alt="Start Trigger" src="https://user-images.githubusercontent.com/51127807/121823216-66026f00-cc69-11eb-84c7-1f97061c212c.png">

<img width="1440" alt="Stop Trigger" src="https://user-images.githubusercontent.com/51127807/121823217-67cc3280-cc69-11eb-8906-2aa3f274ebaa.png">

Start does NOT work.  Stop Does

**Comment by obcocav** [comment]
It seems I was mistaken about the root issue.  The stop seemed to work due to a coincidence...It seems that the "On button press" variable combined with a time is what does not work.  Can not get the "On button press" variable to work in combination with any time variable.

**Comment by obcocav** [comment]
Actually digging a little further, it appears the "on button press/latched" feedback trigger does not work at all.

**Comment by Julusian** [comment]
the "on button press/latched" feedback trigger should work in the latest build

**Comment by Julusian** [comment]
@obcocav are you able to confirm if this is now working for you?

**Comment by obcocav** [comment]
@Julian Waller.  Thanks so much!  Seems to work with limited testing!  I am out of town so not able to test on the main Windows system but works on my Mac here!

**Comment by Julusian** [comment]
Great. Im going to close this then :)
