### ISSUE TITLE
[BUG] Companion app loading stops at Syncing

### ISSUE THREAD

**Issue by atscomms** [bitfocus/companion#1618]
The web gui shows the companion app "Syncing" and stops there. Buttons do not load.
I updated to the latest nightly build (2.2.0-24a2d29d-3352-win64), tried killing the Streamdeck app, & rebooting, 
Windows 20H2 build 19042.985

**Comment by Julusian** [comment]
Have you tried refreshing in your browser?
Could you open up the developer tools in your browser, and provide a screenshot of the console/log tab

**Comment by atscomms** [comment]
Yes, I tried clearing the browser cache, closing and restarting, rebooting the PC, etc.
Attached is a Developer Console screen shot showing 3 failures
![image](https://user-images.githubusercontent.com/60936473/120344211-63963180-c2c7-11eb-944b-750eb880c5e0.png)

**Comment by xavier-dc** [comment]
Check to see if there is a corrupt db file in your companion's roaming folder. I resolved this issue by going to Users > (your user) > App Data > Roaming > Companion and deleting the db.corrupt, db.backup, and db files then quitting and restarting Companion.
