### ISSUE TITLE
[BUG] AW-RP50 and AW-RP60

### ISSUE THREAD

**Issue by SupZee** [bitfocus/companion#1619]
**Describe the bug**
The Devices from the Panasonic PTZ Controller(AW-RP50 and AW-RP60) cannot be added as instance, the "Server", Application is killing itself or losing connection.

**To Reproduce**

1. Go to 'Instances'
2. Click on 'Add by Search' 
3. Type 'AW-RP60'
4. Voilà you killed the App

**Expected behavior**
It should add the instance without an error such as Atem-Products 

**Screenshots**

**Desktop (please complete the following information):**

- OS: Win10
- Browser Chrome/Brave/Edge/Firefox (I got on this Browser the same Error)
- Companion Version v2.1.3

**Comment by McHauge** [comment]
@SupZee please test it out in companion v2.2.0 betas, there is an error with this module in 2.1.3, as it got ported back to 2.1.3 without complete testing.

**Comment by SupZee** [comment]
Thanks for the info and the fast reply :)

**Comment by josephdadams** [comment]
@McHauge so this is fixed in latest beta?

**Comment by McHauge** [comment]
@josephdadams it should be yes, not sure why it's broken in 2.1.3, when it works in 2.2.0, as they are only one module version apart if I remember correctly, and that version difference should not affect that

**Comment by SupZee** [comment]
@josephdadams it works fine, little delay but that's on my site I think. But de AW-RP60 connected perfect and is responding to every signal I give to the device

**Comment by josephdadams** [comment]
So can we close this? 😃

**Comment by McHauge** [comment]
yes
