### ISSUE TITLE
Pi build (v 1.1.0) see's device, but can't access; says another application using

### ISSUE THREAD

**Issue by mikesmithdudeman** [bitfocus/companion#162]
July 9th 2018, 15:13:18 USB(StreamDeck): Found device, but no access. Please quit any other applications using the device, and try again.

Clearly, I don't have elgato's streamdeck app opened simultaneously, since this is a Pi.  I'm running a spanking-clean version of raspbian stretch, fully updated.

**Comment by Julusian** [comment]
This works in newer versions, so must have been fixed at some point
