### ISSUE TITLE
[BUG]TCP Remote not working

### ISSUE THREAD

**Issue by Fabian80645** [bitfocus/companion#1621]
I i want to use the Remote via TCP to trigger Buttons but it dont work.
In the Log i see that it connected but if i send a command nothing happend.

I test ist with UDP that works and i can see in the Log that it triggers the button.

Version: 2.1.3 (6b6820cd-2696)

**Comment by josephdadams** [comment]
You sending that crlf at the end?

**Comment by Fabian80645** [comment]
What did you mean? I send only the command.

**Comment by krocheck** [comment]
Commands need to be terminated with a line break, \n

He was asking if you're sending that at the end of your commands

**Comment by Fabian80645** [comment]
I send via a TCP Client the following command:
BANK-PRESS 1 2 without \n and it dont work. But i test it with BANK-PRESS 1 2\n and nothing happend.
If i send "BANK-PRESS 1 2" via UDP it works.

**Comment by Julusian** [comment]
@Fabian80645 for TCP you need the \n. This is because TCP is a stream of data, and the \n is used to determine where each packet/command ends. (Like a paragraph of text, where . split the text into sentances) 
In UDP it is one command per packet, and so the \n is not required

**Comment by Fabian80645** [comment]
@Julusian 
Yes i understand but nothing happend if i write "BANK-PRESS 1 2\n"
Can you say me how it must look like?

**Comment by McHauge** [comment]
@Fabian80645 at least for me I needed to add "\n\r" to the end so it would be: "BANK-PRESS 1 2\n\r" then it worked :)

**Comment by Fabian80645** [comment]
Thanks it works
Sorry for my mistake
