### ISSUE TITLE
Change Active Window

### ISSUE THREAD

**Issue by JohnNorris92** [bitfocus/companion#1623]
Hi All, is there a straight forward way to change active windows? 
Id like to combine this with the Vicreo Hotkey module, Change active window then hit a hotkey to control Livestream Studio.

Help would be appreciated

Cheers

**Comment by josephdadams** [comment]
It largely depends on your OS and personal setups. MacOS, you could run a simple applescript to make a window active. Windows, the process may be different. You could try issuing a command to the VICREO Listener running on the remote device to open the Livestream Studio program, which should bring it into focus if it were already running. Or, you could look into a program like AutoHotKey.
