### ISSUE TITLE
[BUG] Memory leak using keybind Crtl+C, Crtl+V

### ISSUE THREAD

**Issue by dlamon1** [bitfocus/companion#1625]
**Describe the bug**
Browser window slowed in response time when using Crtl+C, Crtl+V to copy buttons.

**To Reproduce**

1. Click a button from the browser
2. Press Crtl+C
3. Click another button
4. Press Crtl+V

**Expected behavior**
Steps copy the button without slowing response time of actions within the browser

**Screenshots**

**Desktop (please complete the following information):**

- macOS Catalina
- Companion Version 2.01

**Comment by josephdadams** [comment]
What browser?

**Comment by dlamon1** [comment]
Chrome. I do not know the version number, sorry.

**Comment by Julusian** [comment]
@dlamon1 can you confirm that version number of companion? `2.01` isnt valid. Perhaps you meant `2.1.0`?

**Comment by Julusian** [comment]
As the ui has been rewritten for 2.2, it is likely this is already fixed
