### ISSUE TITLE
Enable the Internal Button Press button action to select PRIOR or NEXT 

### ISSUE THREAD

**Issue by ltjost** [bitfocus/companion#1626]
**Describe the feature**
Add NEXT REGULAR and PRIOR REGULAR Button options to the selections allowed for the "internal:Button Press" action or as new internal actions [edit: see comment EXECUTE NEXT CUE and EXECUTE PRIOR CUE commands info]

**Usecases**  
 [edit: see comment EXECUTE NEXT CUE and EXECUTE PRIOR CUE commands info]
I have tested Companion with SCS and with an x32 and with the OSC module.  I use x32Theatre Control and SCS regularly...but it is fairly easy to just manage theater cues directly in Companion and skip x32tc or SCS by use of the OSC commands in Companion.  In audio mixing for theater, it is somewhat typical to create cues that assign channels to DCAs and also name the DCA at each Cue.  It is also fairly normal to mute channels not in DCAs or manage mutes at the DCA level or however the user desires.  I have written a script interpreter that allows me to enter a large variety of OSC commands for the x32 through an easy to use input via excel spreadsheets (a JavaScript gets the tab delimited excel file and creates SCS OSC commands from it).  Running SCS or x32tc requires focus, unless Companion is used, and adds add another layer of software that is not really needed.  Companion can do more and can do it faster, I just need to create a script to take excel and turn it into a Companion config file, which looks pretty straightforward having already done this for SCS.  However, in running theater cues we don't always have time to navigate to the next cue, rather depend on a NEXT and/or PRIOR capability that executes the next or prior cue.  With Companion, unique buttons can be generated for each of the hundred+ cues in a show...but there is no NEXT or PRIOR internal option for button presses...but there is a command to press a specific button.  Allowing PRESS NEXT REGULAR button would be great, as would PRESS PRIOR REGULAR BUTTON, either as selections for "internal:Button Press" or as unique "internal" actions.  With this, a sound engineer could just keep pressing a NEXT button at the top of the Companion Emulator or Streamdesk device to run show cues for the x32 or other sound board without needing SCS or x32tc.  It would enhance to use-cases for the StreamDeck or emulator to include enabling use of this tool for direct theater cue management. See [SCS.WorkWebs.com](SCS.WorkWebs.com) for the tool I mentioned for creating SCS files from excel documents)

**Comment by ltjost** [comment]
Thinking about this...may need a special command type "cue" and commands "Execute Next Cue" and "Execute Prior Cue".  It would require the software to keep track of last used "Cue" command and first "Cue" command so that EXECUTE Next would be able to function.  This would enable Streamdesk and the emulator and this software to be a cue manager on its own...that would be so nice!

**Comment by MeestorX** [comment]
Why not just ask the module creators to add a "next cue" and "previous cue" action?

**Comment by ltjost** [comment]
> Why not just ask the module creators to add a "next cue" and "previous cue" action?

That would indeed do it.  Is there a better way to suggest that then by using this post?

**Comment by josephdadams** [comment]
@ltjost I think this would be better suited as a direct feature request of a specific module. You can make a feature request for the SCS module here: https://github.com/bitfocus/companion-module-showcuesystems-scs/issues

**Comment by ltjost** [comment]
Opened as a generic OSC module request

**Comment by Julusian** [comment]
I think this might be solvable with a feature I am working on for companion. Ill report back once there is a PR for it.

**Comment by ltjost** [comment]
> I think this might be solvable with a feature I am working on for companion. Ill report back once there is a PR for it.

Thank you.  Most generically it should be developed so that Next and Prior Cues could be triggered for any interface...perhaps making a whole "cue" structure ... maybe name a cue sequence and then trigger next or prior "name" cue.  In that way it would be well generalized through the entire tool. Every command could be tied to one or more Cue names... however, for my specific need, OSC would suffice.  I could see "Execute Next LIGHT1 Cue" where the button for a Cue would have one or more CUE Names associated with it.  That, however, would be a more complex undertaking, though it would be more versatile.

**Comment by Julusian** [comment]
I think this will be handled nicely with https://github.com/bitfocus/companion/pull/1630
