### ISSUE TITLE
Update yarn version 12.19.1 to 12.20

### ISSUE THREAD

**Issue by AndrewApi** [bitfocus/companion#1627]
Hi 
How do I update the yarn version in Companion to 12.20 from 12.19.1 so that I can update my Pi to the latest beta build please.

pi@raspberrypi:~/companion $ sudo yarn update
yarn run v1.22.5
$ ./tools/update.sh
Already up to date.
Check Node version
Found v12.19.1
Node version is OK 
Core
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "app-builder-bin@3.5.13" is incompatible with requested version "app-builder-bin@3.5.12"
[3/5] Fetching packages...
error atem-connection@3.0.0-nightly-latest-20210530-132658-16c3cdd.0: The engine "node" is incompatible with this module. Expected version ">=12.20". Got "12.19.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Andrew

**Comment by AndrewApi** [comment]
Sorted

**Comment by lotech** [comment]
Cool story - like to share? Having same problem.

**Comment by lotech** [comment]
sudo npm cache clean -f
sudo npm install -g n
sudo n 12.22.1
