### ISSUE TITLE
Launching the GUI to early after startup causes issues with text on available presets

### ISSUE THREAD

**Issue by andybantly** [bitfocus/companion#1632]
**Describe the bug**
When launching the companion GUI as soon as possible after startup, the text on the available preset categories is garbled.

**To Reproduce**
1. Launch companion with 'yarn dev'.
2. As soon as possible click launch GUI.
3. Launch it before companion has discovered all of its network interfaces.
4. Observe that the text of the available presets is garbled.

**Expected behavior**
The text on the available presets is not garbled.

**Screenshots**

**Desktop (please complete the following information):**
Windows 10 Home
Companion v2.2.0 (2.2.0-ef9904ee-3405)
Chrome version 91.0.4472.106 (Official Build) (64-bit)

**Suggested resolution**
Disable the Launch GUI button until companion has completely initialized.

**Unexpected Screen shot**
![Companion Bug](https://user-images.githubusercontent.com/24298392/122443616-6189cf00-cf65-11eb-999a-d374a42f7535.png)

**Expected Screen shot**
![Companion Expected Behavior](https://user-images.githubusercontent.com/24298392/122443824-8ed67d00-cf65-11eb-851f-d1569a77e555.png)

**Comment by estilles** [comment]
This also happens during development the the GUI refreshes after a `nodemon` restart (whether due to saving a watched file or a manual restart). Disabling the Launch button won't some the underlying issue.

**Comment by Julusian** [comment]
This is fixed in 3.0. I dont think it worth trying to fix it in 2.3/2.4, as it is a minor annoyance with an easy workaround
