### ISSUE TITLE
Companion Fails after running companion-update

### ISSUE THREAD

**Issue by justinajordan** [bitfocus/companion#1640]
After running the Companion update at the CLI-  The companion app then becomes unresponsive, but at the stream deck level and the GUI level-

**To Reproduce**
Steps to reproduce the behavior: run sudo companion-update

Here is the output

pi@FBCNBCompanion:~ $ sudo companion-update
remote: Enumerating objects: 2890, done.
remote: Counting objects: 100% (2318/2318), done.
remote: Compressing objects: 100% (770/770), done.
remote: Total 2890 (delta 1763), reused 2030 (delta 1538), pack-reused 572
Receiving objects: 100% (2890/2890), 2.12 MiB | 3.06 MiB/s, done.
Resolving deltas: 100% (2126/2126), completed with 155 local objects.
From https://github.com/bitfocus/companion
   e198791d..a239c138  master                  -> origin/master
 * [new branch]        feat/action-steps-cycle -> origin/feat/action-steps-cycle
 * [new branch]        feat/custom-variables   -> origin/feat/custom-variables
 * [new branch]        feat/instance-getUserSetting -> origin/feat/instance-getUserSetting
   39388bc1..650ba639  feat/registry           -> origin/feat/registry
 * [new branch]        feat/triggers-run-actions -> origin/feat/triggers-run-actions
   f54de56d..6b6820cd  stable-2.1              -> origin/stable-2.1
 * [new branch]        wip/pr-combo            -> origin/wip/pr-combo
 * [new tag]           v2.1.3                  -> v2.1.3
Updating e198791d..a239c138
Fast-forward
 .github/workflows/lint.yaml                        |    4 +-
 .github/workflows/nodejs.yml                       |   47 +-
 .npmrc                                             |    1 +
 .prettierignore                                    |    2 +-
 CHANGELOG.md                                       |   94 +
 Dockerfile                                         |    2 +-
 app.js                                             |   29 +-
 docs/1_gettingstarted/1_before_you_open.md         |    3 +
 docs/1_gettingstarted/2_start_the_server.md        |    9 +
 docs/1_gettingstarted/3_the_user_interface.md      |    7 +
 docs/1_gettingstarted/images/admingui.png          |  Bin 0 -> 131681 bytes
 docs/1_gettingstarted/images/server.png            |  Bin 0 -> 20893 bytes
 docs/2_sidebar.md                                  |    1 +
 docs/2_sidebar/1_community_links.md                |    7 +
 docs/2_sidebar/2_emulator.md                       |    3 +
 docs/2_sidebar/3_web_buttons.md                    |   10 +
 docs/2_sidebar/4_mobile_buttons.md                 |    3 +
 docs/3_config.md                                   |    2 +
 docs/3_config/1_connections.md                     |   20 +
 docs/3_config/2_buttons.md                         |   71 +
 docs/3_config/2_buttons/1_latch_toggle.md          |   14 +
 docs/3_config/2_buttons/2_delays.md                |   15 +
 docs/3_config/2_buttons/3_key_actions.md           |   11 +
 docs/3_config/2_buttons/4_internal_actions.md      |   25 +
 docs/3_config/2_buttons/5_instance_feedback.md     |    5 +
 docs/3_config/2_buttons/6_button_indicators.md     |    8 +
 docs/3_config/2_buttons/images/button-actions.png  |  Bin 0 -> 41703 bytes
 docs/3_config/2_buttons/images/button-delay.png    |  Bin 0 -> 3691 bytes
 docs/3_config/2_buttons/images/button-error.png    |  Bin 0 -> 3627 bytes
 .../images/button-latch-off-with-topbar.png        |  Bin 0 -> 3542 bytes
 .../images/button-latch-off-without-topbar.png     |  Bin 0 -> 3243 bytes
 .../images/button-latch-on-with-topbar.png         |  Bin 0 -> 3672 bytes
 .../images/button-latch-on-without-topbar.png      |  Bin 0 -> 3531 bytes
 docs/3_config/2_buttons/images/delay-absolute.jpg  |  Bin 0 -> 30786 bytes
 docs/3_config/2_buttons/images/delay-relative.jpg  |  Bin 0 -> 33331 bytes
 docs/3_config/2_buttons/images/feedback.png        |  Bin 0 -> 21513 bytes
 docs/3_config/3_surface.md                         |   15 +
 docs/3_config/4_triggers.md                        |    7 +
 docs/3_config/4_triggers/1_trigger_setup.md        |   14 +
 docs/3_config/4_triggers/2_trigger_types.md        |   25 +
 docs/3_config/4_triggers/images/trigger_edit.png   |  Bin 0 -> 28177 bytes
 .../images/trigger_edit_instance_crop.png          |  Bin 0 -> 4421 bytes
 .../images/trigger_edit_interval_crop.png          |  Bin 0 -> 4267 bytes
 .../images/trigger_edit_time_of_day_crop.png       |  Bin 0 -> 7299 bytes
 .../images/trigger_edit_variable_crop.png          |  Bin 0 -> 12895 bytes
 docs/3_config/5_settings.md                        |    3 +
 docs/3_config/5_settings/1_navigation_buttons.md   |    8 +
 docs/3_config/5_settings/2_devices.md              |    2 +
 docs/3_config/5_settings/3_pin_lockout.md          |   11 +
 docs/3_config/5_settings/4_rosstalk.md             |    4 +
 docs/3_config/5_settings/5_artnet_listener.md      |   10 +
 docs/3_config/6_log.md                             |    8 +
 docs/3_config/images/button-with-topbar.png        |  Bin 0 -> 7245 bytes
 docs/3_config/images/button-without-topbar.png     |  Bin 0 -> 7685 bytes
 docs/3_config/images/button.png                    |  Bin 0 -> 63440 bytes
 docs/3_config/images/buttons.png                   |  Bin 0 -> 95992 bytes
 docs/3_config/images/device-settings.png           |  Bin 0 -> 18895 bytes
 docs/3_config/images/devices.png                   |  Bin 0 -> 51868 bytes
 docs/3_config/images/instance.png                  |  Bin 0 -> 120279 bytes
 docs/3_config/images/log.png                       |  Bin 0 -> 155112 bytes
 docs/3_config/images/settings.png                  |  Bin 0 -> 74086 bytes
 docs/3_config/images/triggers.png                  |  Bin 0 -> 71971 bytes
 docs/4_secondary_admin_controls/1_presets.md       |   19 +
 .../2_dynamic_variables.md                         |   15 +
 docs/4_secondary_admin_controls/3_import_export.md |    9 +
 .../images/admingui-variables.png                  |  Bin 0 -> 94421 bytes
 .../images/dynamic-variable-usage.png              |  Bin 0 -> 12235 bytes
 .../images/dynamic-variables.png                   |  Bin 0 -> 53274 bytes
 docs/4_secondary_admin_controls/images/import.png  |  Bin 0 -> 66374 bytes
 .../images/preset-buttons.png                      |  Bin 0 -> 38654 bytes
 .../images/preset-folders.png                      |  Bin 0 -> 29143 bytes
 .../images/preset-modules.png                      |  Bin 0 -> 29441 bytes
 docs/5_remote_control.md                           |    1 +
 docs/5_remote_control/1_tcp_udp.md                 |   29 +
 docs/5_remote_control/2_http_remote_control.md     |   24 +
 docs/5_remote_control/3_osc_control.md             |   27 +
 docs/5_remote_control/4_artnet_dmx_control.md      |    1 +
 docs/5_remote_control/5_rosstalk_control.md        |   11 +
 docs/6_modules.md                                  |    5 +
 docs/structure.json                                |  186 ++
 documentation/Updating streamdeck.md               |    5 +-
 documentation/gettingstarted.md                    |  108 +-
 documentation/images/emptyID.jpg                   |  Bin 0 -> 166677 bytes
 electron.js                                        |    9 +-
 instance_skel.d.ts                                 |   52 +-
 instance_skel.js                                   |  169 +-
 instance_skel_types.d.ts                           |  118 +-
 lib/action.js                                      |   23 +-
 lib/bank.js                                        |  105 +-
 lib/db.js                                          |  457 ++-
 lib/elgato_dm.js                                   |  121 +-
 lib/feedback.js                                    |  320 +-
 lib/graphics.js                                    |  279 +-
 lib/image.js                                       |  198 +-
 lib/instance.js                                    |  235 +-
 lib/io.js                                          |    1 +
 lib/loadsave.js                                    |  155 +-
 lib/osc.js                                         |   16 +-
 lib/schedule.js                                    |   41 +-
 lib/schedule/feedback.js                           |  203 ++
 lib/schedule/interval.js                           |   11 -
 lib/schedule/time_of_day.js                        |   17 +-
 lib/schedule/variable.js                           |   97 -
 lib/tablet.js                                      |   45 -
 lib/usb/elgato-mini.js                             |   48 +-
 lib/usb/elgato-xl.js                               |   50 +-
 lib/userconfig.js                                  |    7 +-
 lib/variable.js                                    |   97 +-
 package.json                                       |  180 +-
 telnet.js                                          |    2 +-
 tools/build_rename_git.js                          |   13 +-
 tools/yarn.sh                                      |    6 +-
 udp.js                                             |    2 +-
 webui/package.json                                 |   46 +-
 webui/public/tablet2.html                          |   50 +-
 webui/src/Buttons/ButtonGrid.jsx                   |   10 +-
 webui/src/Buttons/EditButton/ActionsPanel.jsx      |   22 +-
 webui/src/Buttons/EditButton/ButtonStyleConfig.jsx |  195 +-
 webui/src/Buttons/EditButton/FeedbackPanel.jsx     |  253 +-
 webui/src/Buttons/EditButton/index.jsx             |   21 +-
 webui/src/Buttons/ImportExport.jsx                 |   35 +-
 webui/src/Buttons/Presets.jsx                      |   22 +-
 webui/src/Buttons/Variables.jsx                    |   20 +-
 webui/src/Buttons/index.jsx                        |    4 +-
 webui/src/Components/ColorInputField.jsx           |   26 +-
 webui/src/Components/DropdownInputField.jsx        |  116 +-
 webui/src/Components/GenericConfirmModal.jsx       |   17 +-
 webui/src/Components/TextInputField.jsx            |    8 +-
 .../src/Components/TextWithVariablesInputField.jsx |   63 +-
 webui/src/Components/VariablesTable.jsx            |   11 +-
 webui/src/ContextData.jsx                          |   49 +-
 webui/src/GettingStarted.jsx                       |    2 +-
 webui/src/Instances/AddInstance.jsx                |    4 +-
 webui/src/Instances/InstanceEditPanel.jsx          |    4 +-
 webui/src/Instances/InstanceList.jsx               |   24 +-
 webui/src/Instances/index.jsx                      |    4 +-
 webui/src/Layout/Header.jsx                        |    4 +-
 webui/src/LogPanel.jsx                             |    4 +-
 webui/src/Scheduler/EditModal.jsx                  |   84 +-
 webui/src/Scheduler/index.jsx                      |    8 +-
 webui/src/Surfaces.jsx                             |   52 +-
 webui/src/UserConfig.jsx                           |  543 ++--
 webui/src/index.js                                 |    5 +
 webui/src/scss/_bank.scss                          |    5 +-
 webui/src/scss/_button-edit.scss                   |   26 +-
 webui/src/scss/_controls.scss                      |    6 +
 webui/src/scss/_instances.scss                     |    6 +
 webui/src/scss/_layout.scss                        |   23 +-
 webui/src/scss/_log.scss                           |    2 +-
 webui/src/scss/_presets.scss                       |    1 +
 webui/src/util.jsx                                 |    7 +-
 webui/yarn.lock                                    | 3070 ++++++++++----------
 yarn.lock                                          | 2598 +++++++++--------
 153 files changed, 6768 insertions(+), 4699 deletions(-)
 create mode 100644 .npmrc
 create mode 100644 docs/1_gettingstarted/1_before_you_open.md
 create mode 100644 docs/1_gettingstarted/2_start_the_server.md
 create mode 100644 docs/1_gettingstarted/3_the_user_interface.md
 create mode 100644 docs/1_gettingstarted/images/admingui.png
 create mode 100644 docs/1_gettingstarted/images/server.png
 create mode 100644 docs/2_sidebar.md
 create mode 100644 docs/2_sidebar/1_community_links.md
 create mode 100644 docs/2_sidebar/2_emulator.md
 create mode 100644 docs/2_sidebar/3_web_buttons.md
 create mode 100644 docs/2_sidebar/4_mobile_buttons.md
 create mode 100644 docs/3_config.md
 create mode 100644 docs/3_config/1_connections.md
 create mode 100644 docs/3_config/2_buttons.md
 create mode 100644 docs/3_config/2_buttons/1_latch_toggle.md
 create mode 100644 docs/3_config/2_buttons/2_delays.md
 create mode 100644 docs/3_config/2_buttons/3_key_actions.md
 create mode 100644 docs/3_config/2_buttons/4_internal_actions.md
 create mode 100644 docs/3_config/2_buttons/5_instance_feedback.md
 create mode 100644 docs/3_config/2_buttons/6_button_indicators.md
 create mode 100644 docs/3_config/2_buttons/images/button-actions.png
 create mode 100644 docs/3_config/2_buttons/images/button-delay.png
 create mode 100644 docs/3_config/2_buttons/images/button-error.png
 create mode 100644 docs/3_config/2_buttons/images/button-latch-off-with-topbar.png
 create mode 100644 docs/3_config/2_buttons/images/button-latch-off-without-topbar.png
 create mode 100644 docs/3_config/2_buttons/images/button-latch-on-with-topbar.png
 create mode 100644 docs/3_config/2_buttons/images/button-latch-on-without-topbar.png
 create mode 100644 docs/3_config/2_buttons/images/delay-absolute.jpg
 create mode 100644 docs/3_config/2_buttons/images/delay-relative.jpg
 create mode 100644 docs/3_config/2_buttons/images/feedback.png
 create mode 100644 docs/3_config/3_surface.md
 create mode 100644 docs/3_config/4_triggers.md
 create mode 100644 docs/3_config/4_triggers/1_trigger_setup.md
 create mode 100644 docs/3_config/4_triggers/2_trigger_types.md
 create mode 100644 docs/3_config/4_triggers/images/trigger_edit.png
 create mode 100644 docs/3_config/4_triggers/images/trigger_edit_instance_crop.png
 create mode 100644 docs/3_config/4_triggers/images/trigger_edit_interval_crop.png
 create mode 100644 docs/3_config/4_triggers/images/trigger_edit_time_of_day_crop.png
 create mode 100644 docs/3_config/4_triggers/images/trigger_edit_variable_crop.png
 create mode 100644 docs/3_config/5_settings.md
 create mode 100644 docs/3_config/5_settings/1_navigation_buttons.md
 create mode 100644 docs/3_config/5_settings/2_devices.md
 create mode 100644 docs/3_config/5_settings/3_pin_lockout.md
 create mode 100644 docs/3_config/5_settings/4_rosstalk.md
 create mode 100644 docs/3_config/5_settings/5_artnet_listener.md
 create mode 100644 docs/3_config/6_log.md
 create mode 100644 docs/3_config/images/button-with-topbar.png
 create mode 100644 docs/3_config/images/button-without-topbar.png
 create mode 100644 docs/3_config/images/button.png
 create mode 100644 docs/3_config/images/buttons.png
 create mode 100644 docs/3_config/images/device-settings.png
 create mode 100644 docs/3_config/images/devices.png
 create mode 100644 docs/3_config/images/instance.png
 create mode 100644 docs/3_config/images/log.png
 create mode 100644 docs/3_config/images/settings.png
 create mode 100644 docs/3_config/images/triggers.png
 create mode 100644 docs/4_secondary_admin_controls/1_presets.md
 create mode 100644 docs/4_secondary_admin_controls/2_dynamic_variables.md
 create mode 100644 docs/4_secondary_admin_controls/3_import_export.md
 create mode 100644 docs/4_secondary_admin_controls/images/admingui-variables.png
 create mode 100644 docs/4_secondary_admin_controls/images/dynamic-variable-usage.png
 create mode 100644 docs/4_secondary_admin_controls/images/dynamic-variables.png
 create mode 100644 docs/4_secondary_admin_controls/images/import.png
 create mode 100644 docs/4_secondary_admin_controls/images/preset-buttons.png
 create mode 100644 docs/4_secondary_admin_controls/images/preset-folders.png
 create mode 100644 docs/4_secondary_admin_controls/images/preset-modules.png
 create mode 100644 docs/5_remote_control.md
 create mode 100644 docs/5_remote_control/1_tcp_udp.md
 create mode 100644 docs/5_remote_control/2_http_remote_control.md
 create mode 100644 docs/5_remote_control/3_osc_control.md
 create mode 100644 docs/5_remote_control/4_artnet_dmx_control.md
 create mode 100644 docs/5_remote_control/5_rosstalk_control.md
 create mode 100644 docs/6_modules.md
 create mode 100644 docs/structure.json
 create mode 100644 documentation/images/emptyID.jpg
 create mode 100644 lib/schedule/feedback.js
 delete mode 100644 lib/schedule/variable.js
 delete mode 100644 lib/tablet.js
Already on 'master'
Your branch is up to date with 'origin/master'.
yarn run v1.22.10
error companion@2.2.0: The engine "node" is incompatible with this module. Expected version "^14.16". Got "12.18.4"
error Commands cannot run with an incompatible environment.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Connection to 192.168.2.191 closed by remote host.
Connection to 192.168.2.191 closed.

- OS: companion pi build 2.2
- Browser- All of them
- Companion Version  2.2

**Comment by Julusian** [comment]
The error is explained at the bottom of the output:
> error companion@2.2.0: The engine "node" is incompatible with this module. Expected version "^14.16". Got "12.18.4"
error Commands cannot run with an incompatible environment.

You need to update nodejs

**Comment by justinajordan** [comment]
This is after running a BRAND NEW IMAGE of the current posted PI bundle.  So if this isn't working, who do we work with to get the current PI Image fixed?

**Comment by Julusian** [comment]
@jarodwsams are you able to do an updated companionpi image for the changed node version? 
Should I add a field/script to get the required node version so that you can make `companion-update` manage the version automatically?

**Comment by jarodwsams** [comment]
> @jarodwsams are you able to do an updated companionpi image for the changed node version?
> Should I add a field/script to get the required node version so that you can make `companion-update` manage the version automatically?

I should be able to spit out an updated CompanionPi image this next weekend. If you can figure out how to manage the node version, that would be _amazing_.

**Comment by Julusian** [comment]
> > @jarodwsams are you able to do an updated companionpi image for the changed node version?
> > Should I add a field/script to get the required node version so that you can make `companion-update` manage the version automatically?
> 
> I should be able to spit out an updated CompanionPi image this next weekend. If you can figure out how to manage the node version, that would be _amazing_.

OK, I have a plan that I think will work.
Instead of running `yarn update` do a `MANAGE_NODE_VERSION=1 ./tools/update.sh`.
This will make the script use `n` to install a certain version of node, as specified by the code that will have just been pulled. I hope the permissions line up as I expect, let me know if not and I can have a play on a pi to figure out what went wrong.

Additionally, you may need to install nodejs from nodesource not the default debian repositories (as described in the install steps), and make sure to also do a `sudo npm install -g n` as part of the initial setup. The update script isnt running that right now, but that can easily change in the future if needed

**Comment by jarodwsams** [comment]
@Julusian - Ok. I'll try this with a test machine before I do anything on the image. I can flash the current CompanionPi w/ Node 12-something (I think) and see if it behaves as expected.

**Comment by jarodwsams** [comment]
@Julusian That replacement for `yarn update` seems to do the trick perfectly! So long as something doesn't change that breaks that new command, this should resolve a lot of problems for a lot of people. Thank you!

**Comment by Julusian** [comment]
@jarodwsams perfect. Shouldn't be an issue going forward, as if it does break it is simply a commit to this repo to fix it again :)

I am wondering if the variable should have been called something more companionpi specific, but I dont think it matters that much

**Comment by hussra** [comment]
Is companion-update in Git somewhere?

**Comment by jarodwsams** [comment]
@hussra 
> Is companion-update in Git somewhere?

No. It's a custom bash script that's specific to the CompanionPi custom image. If you're having an issue with the script, please log a fresh issue instead of tacking onto this one.
