### ISSUE TITLE
[BUG] latest beta the “set surface to page” action doesn’t work.

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion#1647]
**Describe the bug**
When using the set surface to page action nothing happens in latest builds.  This occurs with either “surface xxxx” or “current surface” selected.

**To Reproduce**

Create a button that navigates to a selected page.  Click it.  Nothing happens.  

**Expected behavior**
Should navigate to selected page on the selected device.

**Desktop (please complete the following information):**

- OS: [e.g. iOS]. Win10 64
- Browser [e.g. chrome, safari] Firefox 
- Companion Version [e.g. 2.0] 2.2 latest 2 betas as of 30Jun evening.

**Comment by Julusian** [comment]
Which build number are you running?
A fix for this was included in 3451 on the 30th, that fixed the issue for me

**Comment by obcocav** [comment]
I thought it was 3451.  I’ll be able to take a look at the system later and be sure.

**Comment by obcocav** [comment]
@Julusian .  Got a chance to test.  It appears to me that the 3451 build works IF you select a surface.  The "Current Surface", which we use extensively to via an index page on 4 stream decks still does NOT work.

**Comment by obcocav** [comment]
@Julusian .  FYI.  It appears to work in the emulator but not on the decks.  Maybe related to the new ability to name decks?  Just an idea.  Thank you!

**Comment by Julusian** [comment]
That is very strange, I am using the 'current surface' on real devices (both with and without names set) without issue

**Comment by obcocav** [comment]
Strange.  Any idea on troubleshooting steps?  Ive uninstalled and reinstalled multiple times trying the last few builds.   Have to go back to 3438 to get it to work using "current surface". Using two 15 button and two XL's on a dedicated pc just for Companion.

**Comment by Julusian** [comment]
Is there anything in the logs? Other than that I dont know

**Comment by obcocav** [comment]
@Julusian .  So this morning I completely removed companion, including individually removign the the files in /ProgramData and reinstalled.  All seems well now.  Thanks for your help.

**Comment by Julusian** [comment]
huh weird.. no idea why that helped but ok, calling this fixed then
