### ISSUE TITLE
Add Trigger when Feedback is False

### ISSUE THREAD

**Issue by istnv** [bitfocus/companion#1649]
**Describe the feature**
The current boolean feedback provides an automatic trigger to fire when the feedback is True/On. 
There are no options to trigger actions when that feedback changes to False/Off.
This request is to add the ability to trigger actions when the feedback is False/Off.

**Usecases**
Certain module feedbacks indicate the status of the connected device and can be altered outside of Companion. Watching the 'Mute' status of an audio mixer will allow muting/unmuting other channels depending on the status. To be fully useful, a trigger should be available for both states (on/true or off/false).

**Comment by Julusian** [comment]
I think this would be best achieved by having 2 sets of actions on each trigger. A set of 'on' actions and a set of 'off' actions.
That will be the most flexible and avoid the need to create almost identical triggers to handle the different directions

**Comment by jmcc94** [comment]
Not every scenario will be met be just having 2 sets actions on each trigger - it would still be good if a separate trigger condition could be when a feedback is False/Off

Eg. A complex trigger consisting of when feedback A & feedback B are both false, or when feedback C is true & feedback D is false.

Usecase - using triggers to turn on 'CAM LIVE' signs when certain sources in OBS are in PGM, and turning it off when they're not.

**Comment by BryanCrotaz** [comment]
I've been noodling on the same problem for my recent project where I've ended up with about 20 triggers for a boardroom with 6 devices. In your use case, actions for true/false would work perfectly if you can have an ORed set of feedbacks. This can be modelled as If/Else:

If (src1 in pgm OR src4 in pgm OR src7 in pgm)
  turn light on
Else
  turn light off

**Comment by Julusian** [comment]
From the discussion in #2549, it sounds like this is solved
