### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by psifertex** [bitfocus/companion#1652]
2.1.3 -- not sure if there's a better "latest", the beta builds seem organized around feature branches 

**Describe the bug**
"Remove the topbar" setting is missing. 

**To Reproduce**
1. Go to settings 
2. Observe missing setting 

**Expected behavior**
The documented setting should exist.

**Screenshots**
Comparison of documentation and actual interface, sorry for mobile pics, not logged in to GitHub on the machine with companion installed. 
![image](https://user-images.githubusercontent.com/140215/124389799-cc057380-dcb6-11eb-8d37-97888301e666.jpeg)
![image](https://user-images.githubusercontent.com/140215/124389791-c314a200-dcb6-11eb-9ebf-02c6f8575ee3.jpeg)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Safari
- Companion Version 2.1.3

**Additional context**

**Comment by Julusian** [comment]
The 2.2 betas are not feature branch based (those builds are not public).

The docs which you are looking at are for 2.2, which has not yet had a 'stable' release. You will need to use a 2.2 beta if you need that feature
