### ISSUE TITLE
x-keys Generation 1 support

### ISSUE THREAD

**Issue by m-theater** [bitfocus/companion#1656]
It would be lovely to get support even for the older X-Keys MW versions.
I have an MWII with 20 Cherry MX Keys waiting to call a few scripts :)
thanks for your consideration.

USB:
idVendor:           0x05F3 (PI Engineering, Inc)
idProduct:          0x02A5

[x_keys_data-report.pdf](https://github.com/bitfocus/companion/files/6795394/x_keys_data-report.pdf)

**Comment by josephdadams** [comment]
@JeffreyDavidsz ?

**Comment by JeffreyDavidsz** [comment]
@m-theater I've added the model, but looking at the data report, the first bytes are different then the others, so it might be that only the last rows will do something. Could you test it?

**Comment by m-theater** [comment]
@JeffreyDavidsz thanks for taking the time to look into the issue.
i tried the code on my mac and got this error codes in the terminal.
******************************************************************************

[nodemon] starting `node headless.js`
Starting
Starting headless with interface "lo0"
Adding xkeys USB device: MW-II
undefined:0


RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 3. Received 4
    at boundsError (internal/buffer.js:83:9)
    at Uint8Array.readUInt32LE (internal/buffer.js:217:5)
    at HID.<anonymous> (/Users/baer/Documents/github/companion-master/lib/usb/xkeys.js:129:21)
    at HID.emit (events.js:375:28)
    at readFunc (/Users/baer/Documents/github/companion-master/node_modules/node-hid/nodehid.js:119:22) {
  code: 'ERR_OUT_OF_RANGE'
}
******************************************************************************

The Device shows up in the Surfaces List (image attached) but is not loading properly.


![Screen Shot 2021-07-18 at 00 49 26](https://user-images.githubusercontent.com/10233611/126062536-f4c87138-a65d-4701-a7a8-d92c9dec4a49.png)
![Screen Shot 2021-07-18 at 00 49 16](https://user-images.githubusercontent.com/10233611/126062533-bdde652b-7036-48fa-8211-f9aafebbc172.png)

**Comment by Julusian** [comment]
I can't tell if this is supported or not now.
If it isn't then please open an issue with the library we are using https://github.com/SuperFlyTV/xkeys/
Once they have added support, let us know here and we can update the version of the library we use, which will enable it
