### ISSUE TITLE
New Raspberry Pi Installation

### ISSUE THREAD

**Issue by RoggieRog** [bitfocus/companion#1658]
Hello. I just got a Pi4 B 8GB and did a manual Companion installation while following the directions very carefully. At present, I have a few issues:

-I don't get the welcome message when I first boot up either via a connected monitor, or via a PuTTY SSH session.
-I am unable to update via the "sudo companion-update" command. I get a command not found error.
-Upon my initial opening up of Companion via a browser on another laptop, not only were there no connections available, but the list to the right was empty. I'd type something and nothing would show up. A few minutes later the list was populated. Is this an expected first time kind of thing, or will this be the case each and every time I use it?

This is what I have for now.

Thanks in advance for your help.

**Comment by Julusian** [comment]
@RoggieRog 

> -I don't get the welcome message when I first boot up either via a connected monitor, or via a PuTTY SSH session.

This is expected as the manual steps do not set this up

> -I am unable to update via the "sudo companion-update" command. I get a command not found error.

That is a companionpi script that is not setup by the manual instructions

> -Upon my initial opening up of Companion via a browser on another laptop, not only were there no connections available, but the list to the right was empty. I'd type something and nothing would show up. A few minutes later the list was populated. Is this an expected first time kind of thing, or will this be the case each and every time I use it?

There is a known bug with this list being populated slowly/badly. I expect it will happen if you open the ui too soon after starting companion. But refreshing the page after a few seconds should fill it in

**Comment by RoggieRog** [comment]
Thank you very much Julian! When I have a moment to revisit this, I will
give it a go and let you know how it turns out.

Best,

*Roger P. Gruchalski *

Video Systems Engineer

Groupe Solution

131 Varick Street, Suite 1036

New York, NY 10013

m. 917.763.2890 | ***@***.***



www.groupesolution.io



Owner and Certified Operator of:


   -
*Barco E2 Tri-combo image processors *
   -
*disguise vx4 media servers *
   - *Dataton WATCHOUT media servers*

**Comment by RoggieRog** [comment]
Hi. I'm just getting a chance to revisit this. How can I safely uninstall my manual Companion installation and then reinstall the "automatic" one? I don't see clear documentation about this on GitHub.

**Comment by jarodwsams** [comment]
You don't "install" the automatic flavor in the normal sense. It's an entire pre-built image that you flash to your microSD card, same as you did for the basic Raspberry Pi OS. Just download the CompanionPi image, flash it, and you should be off to the races.

**Comment by RoggieRog** [comment]
I successfully reinstalled and it works great, Thank you guys for your assistance. One question that I have is regarding the "Checksum (SHA256)". I'm not sure what to do with that image and don't see any documentation about it. Would someone please shed some light on this for me?
