### ISSUE TITLE
module spotify-remote not working

### ISSUE THREAD

**Issue by DJJeffP** [bitfocus/companion#1659]
Hello, 
I'm currently testing the beta version companion-2.2.0-88056572-3469-win64.exe because I wanted to test if the Spotify module would work. 
When I want to add the Spotify Web API and Controller module in the Admin panel. I get an `Failed to create connection - 
Failed: TimeoutError: Timed out after 5s` .

In the Log file I see this:
`21.07.11 17:39:22 module(spotify-remote): Error loading module: Error: Cannot find module 'aws-sdk' Require stack: - C:\Program Files\Companion\resources\app.asar\node_modules\companion-module-spotify-remote\module.js - C:\Program Files\Companion\resources\app.asar\lib\instance.js - C:\Program Files\Companion\resources\app.asar\app.js - C:\Program Files\Companion\resources\app.asar\electron.js`

Am I still missing a module or is there a config file missing a line?

**Comment by thedist** [comment]
It seems to be an issue with the developer of that module trying to load a dependency that's not present, and not even used.

There's a solution already in a pull request but it seems the developer isn't around to accept it. https://github.com/bitfocus/companion-module-spotify-remote/pull/16

**Comment by JeffreyDavidsz** [comment]
accepted it ;-)
