### ISSUE TITLE
Font size dropdown doesn't reflect the current value

### ISSUE THREAD

**Issue by willosof** [bitfocus/companion#166]
**To Reproduce**
1. Configure a button
2. Set 14pt
3. Go back
4. Go into the button again - and you'll see it shows you 7pt even if it's 14pt.

**Comment by dnmeid** [comment]
I cannot reproduce this issue. For me it is working fine. If you are working with a config using old values ("small" and "large"), you have to change the value to something different so the new value with the pt-size can be stored.

**Comment by dnmeid** [comment]
Closing this now because I still can't reproduce the error.
