### ISSUE TITLE
Slow raspberry Pi install 

### ISSUE THREAD

**Issue by dszoka** [bitfocus/companion#1662]
Fresh install of raspberry Pi image 

seems to running very very slow 
Only running 5 active modules 

[video link ](https://drive.google.com/file/d/1kFiL1_5lfwzRt2xQNiYoDyDxVsns8GVJ/view?usp=drivesdk)

here is a link to my full setup so you import for testing 
[Link](https://drive.google.com/file/d/10vu3VQ55Zodz8R2grVX7o96s5akv2sGQ/view?usp=drivesdk)

**Comment by bradleywehmeier** [comment]
I saw your post on the Facebook group. I think PR https://github.com/bitfocus/companion/pull/1663 will address this issue.

**Comment by dszoka** [comment]
I have done a Fresh install and run update, While its now faster its still slow compared to normal 

Here is my Terminal File so you can see that I'm on the latest version 
[Updated 15th July .txt](https://github.com/bitfocus/companion/files/6819266/Updated.15th.July.txt)

here is another[ video ](https://drive.google.com/file/d/1rZFH4QWahytG76_WHOO0dOvKQdFmWsI3/view?usp=sharing)showing it has gotten faster

**Comment by mrmrphy** [comment]
Agree with @dszoka - speed has improved, but is still lagging.

**Comment by Julusian** [comment]
I gave it a try myself yesterday before the fix from @bradleywehmeier, and it was nowhere near as slow as you were seeing, so it looks like you are seeing a secondary issue but I have no idea what

**Comment by dszoka** [comment]
Really idea dumb, But what I can see the major change in this Pi Image is the auto node update.. Could that be causing the issue??  I was running off the master branch before I flashed with no problems 

Just a dumb idea

**Comment by Julusian** [comment]
I dont think so
I need to give it another test, but I don't have any idea what the issue could be here.

Perhaps you could help. If you could do a fresh install, and document every command you run until you are at a point where this happens. Hopefully that will be enough for me to follow along and get the same result. Or alternatively, you could make an image from your sd card (the program you used to write the sd card to begin with might be able to do it) and send that to me. Either here or email to git@julusian.co.uk

**Comment by dszoka** [comment]
Here is a [link to Google Drive](https://drive.google.com/drive/folders/1MGP1V40EZSKcKgmcHPVSx0APFY6_ed3V?usp=sharing) with image of my setup as of today, plus my terminal log file from where I installed this image, the only part missing is the import of my config, which there is a copy in the folder too.

There are to image files, made with 2 different programs  not sure which one is right. 
Let me know if I can help anymore

**Comment by Julusian** [comment]
I fired up it up on my pi earlier, and had the slowness.
I think I can see the jpeg library used by the streamdeck library semi uninstalling itself. I haven't investigated further yet, but I have a good place to start.
I'll let you know once I have either a hacky or proper fix

**Comment by dszoka** [comment]
Just noticed in log from yesterday some errors I hadn't seen before, might help  

[Comp Pi Log.txt](https://github.com/bitfocus/companion/files/6851836/Comp.Pi.Log.txt)

**Comment by EJBerendsen** [comment]
I just had a chance to update my raspberry today, with the companion-update command.
The pages are getting refreshed faster, but not as fast as it has always been with previous builds.
At the moment it take up to 3+ seconds for building the page.
Running with the Streamdeck XL on a Raspberry PI4.

**Comment by Julusian** [comment]
I don't know why the jpeg library got messed up, but hopefully running the update again should resolve it

**Comment by EJBerendsen** [comment]
@Julusian, I just did the update and it is all good now. Thank you for looking into this!!

**Comment by dszoka** [comment]
Back running at Warp speed, Thank you @Julusian
