### ISSUE TITLE
Feature Request - Trigger Condition - Button state

### ISSUE THREAD

**Issue by jmcc94** [bitfocus/companion#1664]
**Describe the feature**
it would be good to be able to use the state of a button as part of a trigger condition.

**Usecases**
Only run a trigger if a certain button is latched or unlatched.

**Comment by Julusian** [comment]
There is already a feedback that can be used for this
![image](https://user-images.githubusercontent.com/1327476/125760176-8cc16095-97db-4360-b412-25e7111097f3.png)

**Comment by jmcc94** [comment]
Sorry - don't know how i missed that...
