### ISSUE TITLE
[BUG] VICREO hotkey: open a file not executing

### ISSUE THREAD

**Issue by BrianBATL** [bitfocus/companion#1665]
Potential Bug:  Out of the blue, for no apparent reason, "VICREO hotkey: open a file" key action stopped opening files.

This feature was working just fine for a long time, but it has stopped and I can't figure out why.

For reference, I have a button macro that loads my PC screen into Atem Mini Pro's "Preview", then VICREO hotkey opens my podcast intro video (inside VLC) into that Preview with the video paused, then it transitions the video to "Program" and plays the video. After 26 seconds when intro video is done, it transitions my main camera on me into Preview, then VICREO hotkey opens my podcast music file (mp3), then transitions my main camera on me into Program, it then closes the intro video vile (forces VLC to close), and I begin my usual podcast.

This has worked flawlessly for months.  But last week it just stopped opening the video and music files.

VICREO still executes the pause and play attempt of the video and transitions the camera to program after 26 seconds, as I can see it perform these actions in the VICREO Listener log box, and also attempts to close the video (quit VLC), but it no longer appears to execute the "open a file" actions.  There are no "received" logs for those button actions.

And I don't know if this is a VICREO issue or a Companion issue.  It feels like a Companion issue since it appears Companion is sending some actions to the VICREO log but not the "open a file" actions.

I use Windows and Companion 2.1.3 and VICREO Listener 2.1.0.  Everything is set to load as Administrator, and again, it had been working just fine up until last week.  Please let me know if I'm doing something wrong or you know a fix for this on my end.  Or even if there's a better/different way for me to do that macro I referenced.

Thank you! And thank you so much for keeping Companion up to date.  It's an incredible program.

**Comment by Julusian** [comment]
Transferred to https://github.com/bitfocus/companion-module-vicreo-hotkey/issues/19
(it appears to have gotten stuck doing the transfer)
