### ISSUE TITLE
[BUG] Custom variables disappear after CompanionPi restart

### ISSUE THREAD

**Issue by mrmrphy** [bitfocus/companion#1666]
**Describe the bug**
After rebooting a Companion Pi image, custom variables disappear. All programming using those variables still exists, but the variables and their values are no longer present on the Variables > Custom Variables tab.

**To Reproduce**
Install latest CompanionPi image.
Import Companion configuration with variables.
Reboot Raspberry Pi.
On Companion admin page, all buttons are present with programming - but all variables / values are missing.

**Expected behavior**
The variables should not disappear on reboot, which then requires an import of the full configuration.

**Screenshots**
![Screen Shot 2021-07-16 at 9 03 19 PM](https://user-images.githubusercontent.com/87488511/126019062-30439174-5f62-4c26-bb1b-be3064aae6b2.png)
![Screen Shot 2021-07-16 at 9 01 00 PM](https://user-images.githubusercontent.com/87488511/126019063-4b2f01be-8dbb-4e27-99ba-34a80dc8b491.png)
![Screen Shot 2021-07-16 at 9 00 37 PM](https://user-images.githubusercontent.com/87488511/126019064-35ba2489-926d-4322-8283-fd39013f0e39.png)

**Desktop (please complete the following information):**

- OS: Raspberry Pi
- Browser: Chrome
- Companion Version: companion-2.2.0-1e59c552-3480-linux

**Additional context**

**Comment by Julusian** [comment]
Should be resolved now. 
It looks like a save was missing internally after the import, but not after editing/creating one
