### ISSUE TITLE
companion not recognizing elgato stream deck. 

### ISSUE THREAD

**Issue by rontomasch** [bitfocus/companion#1668]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- Companion Version [e.g. 2.0]

**Additional context**

**Comment by Julusian** [comment]
What version of companion?
Which model of streamdeck? (and which generation)
What os?
Elgato software running?
Anything in the log?

**Comment by rontomasch** [comment]
Companion   v2.1.3
15 key stream deck
Windows 10
Elgato software not running
Log says stream deck disconnected

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by mrmrphy** [comment]
Based on the information from @rontomasch in the Companion FB group, the issue was that the Streamdeck was showing as a Surface, but not as an Instance. This seems to be correct, expected behaviour.

https://www.facebook.com/groups/companion/permalink/2911101429108188/

**Comment by Julusian** [comment]
Streamdecks will only show up in the surfaces tab and not connections.

It sounds like this is resolved, let me know if not and I shall reopen

**Comment by rontomasch** [comment]
It has been resolved. Thank you

Sent from my iPhone

On Jul 28, 2021, at 7:50 AM, Julian Waller ***@***.***> wrote:

﻿

Closed #1668<https://github.com/bitfocus/companion/issues/1668>.
