### ISSUE TITLE
Module Request: Analog Way Midra Series

### ISSUE THREAD

**Issue by MrLazerface** [bitfocus/companion#167]
**Describe the feature**
This module would support Analog Way's Midra series of presentation switchers.

**Desired Commands**
-Memory and Master Memory recall (to preview and program)
-Input/Output/Layer Freeze
-Auto Trans and Cuts
-Quick Frame
-Input plug change
-Screen selection for transitions

**If documentation is required to implement, do you know where to find it?**
Documentation is attached. On first look it appears to be a similar command structure to the Livecore series, so it may be possible to use the existing Livecore module to speed up the development process.

[Midra_TPP_commands_for_v02-00-15.pdf](https://github.com/bitfocus/companion/files/2185340/Midra_TPP_commands_for_v02-00-15.pdf)

[Midra_TPP_Programmers-guide_for_v02-00-15.pdf](https://github.com/bitfocus/companion/files/2185330/Midra_TPP_Programmers-guide_for_v02-00-15.pdf)

**Comment by dnmeid** [comment]
I already volunteered for the Midra module. At the moment I'm just waiting for feedback then I can do Livecore and Midra nice with feedbacks.

**Comment by MartijnKraats** [comment]
Already got Midra (Pulse2) working on stream deck via Octopus UDP commands. 
config file is shared with the Facebook Group, hope this helps!

**Comment by dnmeid** [comment]
Midra module is now available in the latest build but it still needs testing. I don't have a Midra device at hand at the moment and there is no simulator. So please try and report any errors here.

**Comment by PerRoine** [comment]
I have tested The Midra Module with Pulse 2 today and it seems to work fine, Nice job Dorian lot's of Actions and functions :-)

**Comment by dnmeid** [comment]
Ok, thank you, closing this Issue now.
