### ISSUE TITLE
OBS Studio: Recording Time

### ISSUE THREAD

**Issue by tipuraneo** [bitfocus/companion#1671]
**Describe the feature**
Similar to the stream time $(OBS-instance:total_stream_time), I would appreciate to see a variable $(OBS-instance:total_record_time).

**Usecases**
Show the recording time on the button similar to the stream time.

**Comment by bryce-seifert** [comment]
This is available in the latest beta builds ([download link](https://bitfocus.io/companion/download/builds/)) as the "recording_timecode" variable.
