### ISSUE TITLE
[BUG] Using "legacy" property to rename a module fails when importing

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#1672]
**Describe the bug**
If a module is renamed and then the old name is added as a "legacy" property in package.json, companion crashes on import of a "legacy" module.

**To Reproduce**
add a "legacy" property with the name of an existing module to your new module.
delete the module from node_modules and "dependencies" in companion's package.json
Fire up companion
import a page that uses the legacy module
Crash!
```
Uncaught Exception:
TypeError: Cannot read property 'label' of undefined
    at Socket.<anonymous> (/Users/andyb/Dropbox/Documents/companion/companion/lib/loadsave.js:426:35)
    at Socket.emit (events.js:315:20)
    at Socket.emitUntyped (/Users/andyb/Dropbox/Documents/companion/companion/node_modules/socket.io/dist/typed-events.js:69:22)
    at /Users/andyb/Dropbox/Documents/companion/companion/node_modules/socket.io/dist/socket.js:428:39
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

**Expected behavior**
The new module is loaded in place of the legacy one, as it does when using an old db

**Screenshots**
Error as above

**Desktop (please complete the following information):**

- OS: macOS Catalina
- Browser : Safari
- Companion Version: Latest

**Additional context**
When importing, the information shown regarding the page for `Config Instance Type` is `Unknown Module`

**Comment by Julusian** [comment]
Fixed

**Comment by MeestorX** [comment]
Thank you!
