### ISSUE TITLE
[BUG] companion won't find my Stream Deck

### ISSUE THREAD

**Issue by Wuff74** [bitfocus/companion#1677]
Under Surfaces my Stream Deck won't be found. Only the emulator is there.
Rescan won't bring solution.

My config:
- iMac 2017, MacOS BigSur
- Atem Mini Pro ISO
- Stream Deck MK.2
-- Firmware 1.00.001
-- Software Stream Deck Version 5.0.0 (14247)
-- Serial Number: DL15K....

Installed companion via the website. Streamdeck Software was installed before and configured.
Atem Mini was found, connected and worked like expected via emulator.

What I have already tried out:
Disconnected Stream Deck and restarted iMac several times. Uninstalled Stream Deck Software and companion.
Restarted, downloaded companion (haven't deleted the config-files, where can I find them on Mac?), started companion
(config was still there), rescanned USB, nothing.

My Stream Deck itself also has the screensaver image, but the software isn't installed and has no function at all.

Tried companion on different browsers (chrome, safari, firefox).

Any suggestions?

Thx in advance,
Frank

![image](https://user-images.githubusercontent.com/88094038/127329389-cdc5bb96-d504-40ff-82f8-79782f3b2b02.png)
<img width="402" alt="image" src="https://user-images.githubusercontent.com/88094038/127329529-78e264c6-7724-4d42-a32d-3e8c95aa7421.png">
<img width="873" alt="image" src="https://user-images.githubusercontent.com/88094038/127329575-22689679-7c80-48c2-90b0-a9bfadcb2acb.png">
<img width="411" alt="image" src="https://user-images.githubusercontent.com/88094038/127330055-6fca8763-7d42-4270-a3ac-004450a1458f.png">

**Comment by Julusian** [comment]
You need to use a recent 2.2 beta to be able to use the streamdeck mk2

**Comment by Wuff74** [comment]
> You need to use a recent 2.2 beta to be able to use the streamdeck mk2

Nope. That seems not to be correct.

After all I found the "solution". Because of not having installed the companion plugin via Stream Deck store, it could not work.
As written above, I uninstalled the Stream Deck Software and had to re-install it. With my backup, all profiles came back, but the previously installed plugins were missing. So I went through all plugins in the store and found the companion plugin. Installed it and immediately it shows the Atem profile.

So as I came across companion because of one of my colleagues, maybe it would be helpful to find a link or a small topic to the companion plugin in the FAQ / Getting Started. Even when I search for Atem and Stream Deck, I will find the bitfocus-site, but not a mention to the plugin except in the Key Features.

Thx
Frank

<img width="852" alt="image" src="https://user-images.githubusercontent.com/88094038/127352436-b09dff17-b537-42b0-aba6-ff8a9a7693c3.png">

**Comment by Julusian** [comment]
Let me rephase, you need to use a recent 2.2 beta to be able to use the streamdeck mk2 without the plugin.

It is recommended to not use the elgato software and the plugin, but that does also work and will let you use older versions of the companion with the new streamdeck.
