### ISSUE TITLE
Smart latch/toggle

### ISSUE THREAD

**Issue by noiseboi** [bitfocus/companion#1679]
**Describe the feature**
A third mode for buttons where the duration of a button push is monitored. A short push would latch a button as when the latch/toggle is checked. A long push would be momentary, only activated while held down, as when the latch/toggle is unchecked)

**Usecases**
Using companion to route talkback microphones through sound desks to vMix, Zoom Teams to remote callers, producers, etc.  This is how Push to Talk switches operate on most professional intercom systems. It prevents mics from inadvertently being left open but still gives the option to latch mics on if needed. I'm sure there could be lots of other uses too.

**Comment by Julusian** [comment]
I think this could be achieved with [long press actions](#925).
so that you could define a button to:
* on down: turn on
* on up after < 1s: turn off
* on up after > 1s: do nothing

I would like to avoid adding anything to the latch mode, as it is likely to be majorly changed in 2.3 by #1630, in a way that is not compatible with this proposed smart mode

**Comment by noiseboi** [comment]
> I think this could be achieved with [long press actions](#925).
> so that you could define a button to:
> 
> * on down: turn on
> * on up after < 1s: turn off
> * on up after > 1s: do nothing
> 
> I would like to avoid adding anything to the latch mode, as it is likely to be majorly changed in 2.3 by #1630, in a way that is not compatible with this proposed smart mode

I'm not seeing a way to achieve this with long buttons, could you give an example?

**Comment by Julusian** [comment]
My previous comment includes the flow I think it could use. But that also isnt supported currently.
There is a way to simulate long presses, which it may be possible to do with but I am not sure

**Comment by noiseboi** [comment]
Just to update. I eventually achieved this with 2 buttons, 1 variable and delay actions  ![image](https://user-images.githubusercontent.com/88212362/205162494-4ad6b7f8-6534-4e61-a0d8-c8da23d8e128.png)

**Comment by Julusian** [comment]
It isnt recommended to use this version right now, but this will be a bit simpler to setup (no custom variable needed) in 3.0 by using two steps setup as follows:

![Screenshot from 2022-12-01 21-43-56](https://user-images.githubusercontent.com/1327476/205165385-afdbf5b6-bcec-4a4a-bb81-0fabeae70af1.png)
![Screenshot from 2022-12-01 21-44-01](https://user-images.githubusercontent.com/1327476/205165382-a5df6f93-62ba-4302-a1b2-444332663fb5.png)

The 'Auto progress step' option will also need to be disabled for the button

**Comment by noiseboi** [comment]
Thanks for the update. I'll be sure to try 3.0 when the Yamaha plugin is compatible
