### ISSUE TITLE
Module Request: Christie M Series/J Series/Boxer Series Projector Control

### ISSUE THREAD

**Issue by MrLazerface** [bitfocus/companion#168]
**Describe the feature**
Basic control of Christie M series, J series, and Boxer series projectors.

**Desired Commands**
-Power on/off
-Shutter open/close
-Test pattern on/off/select
-Color enable
-Geometry on/off
-Input select

**If documentation is required to implement, do you know where to find it?**
Documentation attached for M series and Boxer series. J series is similar, if not identical to M series. The desired commands seem to be the same across all series of projectors.

[Christie-M-Series-Serial-Commands.pdf](https://github.com/bitfocus/companion/files/2185449/Christie-M-Series-Serial-Commands.pdf)
[Christie-Boxer-4K-Serial-API.pdf](https://github.com/bitfocus/companion/files/2185450/Christie-Boxer-4K-Serial-API.pdf)

**Comment by Hitower78** [comment]
Hi
I would like to add also:
FRZ–Image Freeze Freeze and
CLE–Color Enable (with 0,..,6)
Color enable is helpful at Softedge Settings

Thx

**Comment by IanTGreenwood** [comment]
I'd love to have Christie control within the next week or so. ;)

Geometry on/off would be fantastic too.  

I believe the code is:

(WRP+SLCT x)
where x=
0 (off)
1 (2D Keystone)
2-17 (user twist files)

**Comment by PerRoine** [comment]
The module is ready for testing, I have not made input select yet at that require info from the projector just need tu figure out what information comes back so that we can parse it and use it

**Comment by IanTGreenwood** [comment]
I can test this week.

**Comment by IanTGreenwood** [comment]
Currently testing Christie M series.

Everything is working aside from geometry control. No response to any commands.  

In the test pattern commands.  Checkerboard is labelled as “Undefined”

Aside from that, everything else seems good.

One word of caution though.  The projector will allow a hot strike (lamp power up before it has cooled) when using TCP commands.  Perhaps it would be possible to first query the PJ with:
(PWR?)
if it returns:
(PWR!010 "Cooling down")
or
(PWR!011 "Warming up")

and ignore the powerup request and display a note or something.

Thanks @PerRoine

**Comment by PerRoine** [comment]
Closing this request for now but will look into the power on / Hot Restrike Issue

**Comment by iainnorthcott** [comment]
Looking at getting the compatible with Christie's digital cinema range. I have a CP2220 and I desire to have channel functions working however I believe the projector needs a different command
