### ISSUE TITLE
USB(undefined): Found device, but no access. Please quit any other applications using the device, and try again.

### ISSUE THREAD

**Issue by willcgage** [bitfocus/companion#1680]
Getting this error while trying to run Stream Deck XL and Companion.

We replaced the 15 button version of Stream Deck with an XL.  For some reason, it can't get access to the new stream deck to place buttons even though it says everything is connected.  I can also see that Companion button numbering.

Mac OS: Big Sur (11.5)
Stream Deck: 5.0.0 (14247)
Companion: 2.1.3 (6b6820cd-2696)

I've uninstalled, restarted, reinstalled both Stream Deck and Companion.  

Not sure what to do now.  Crazy thing is being stubborn.

**Comment by willcgage** [comment]
<img width="865" alt="Screen Shot 2021-08-01 at 3 22 48 PM" src="https://user-images.githubusercontent.com/12308126/127784338-bbc12fd7-3def-4e93-b3c9-3ca191f01126.png">

**Comment by willcgage** [comment]
<img width="1733" alt="Screen Shot 2021-08-01 at 3 23 15 PM" src="https://user-images.githubusercontent.com/12308126/127784353-f0b74e06-b9ef-48e9-86b3-b568a5375162.png">

**Comment by willcgage** [comment]
<img width="1740" alt="Screen Shot 2021-08-01 at 3 26 50 PM" src="https://user-images.githubusercontent.com/12308126/127784442-8fd1b978-43ed-4334-91d6-2fdd90cd73e7.png">

**Comment by LYMPIA** [comment]
If you want to use the Companion interface (as shown in your last 2 pictures) you need to close the Elgato/Streamdeck software. Once you did, you should be able to establish a connection via Companion.

**Comment by willcgage** [comment]
I was able to resolve the issue. I had to delete the profile and then
restart al the software. Then I reinstalled the Companion add on for
Streamdeck. It then installed the profile again and resolved the issue.
