### ISSUE TITLE
Companion PNG 72x72 showing up as lines

### ISSUE THREAD

**Issue by eleftheriakodikas** [bitfocus/companion#1682]
With Version: `2.1.3` i was able to upload any PNG below 72x72 and adjust the alignment, currently using beta `2.2.0-509a6a41-3498 ` I wasn't able to replace the previous images with another PNG with similar width and height. Even using 72x72 the PNG shows up as lines, the PNG alignment function no longer works either. 72x58 Works

![IMG_1086](https://user-images.githubusercontent.com/71998285/128919963-c35ba0bd-6cd9-4482-a856-74d7cb7ee5c2.png)

**Comment by Julusian** [comment]
Can you provide a sample png that you are having issues with?
I am unable to reproduce any lines myself.

The rules for image size have been changed a little in 2.2, requiring then to be at least 72x58

**Comment by Julusian** [comment]
There isnt enough information to progress on this. If anyone can provide a png that reproduces the issue this can be reopened
