### ISSUE TITLE
[BUG] - Superior or inferior comparators not working with Timecode variable

### ISSUE THREAD

**Issue by LYMPIA** [bitfocus/companion#1683]
As we were trying to get a color warning based on a TC Coundtown we've stumbled upon what might appear as a bug.

In "**Feedback / Internal: Check variable value**" (based on BMD HYPERDECK), the **>** (superior) and **<** (inferior) operations are not responding correctly when used with Timecode or Countdown Timecode variables (HH:MM:SS:FF or HH:MM:SS). The only operation that works with those variables are equal or not equal. 

We did some further tests and inferior and superior operations _**work only**_ with HOUR or MINUTE or SECOND pulled as separated variables.

**Comment by Julusian** [comment]
This is expected.
The timecode is stored as a string HH:MM:SS and not as a number, and so it is not that simple to compare them.
It might be possible to do it, but I suspect it will be fiddly and full of edge cases (eg is a variable HH:MM or MM:SS?) so it would be better for the bmd-hyperdeck to provide its own feedbacks to do the operation correctly

**Comment by LYMPIA** [comment]
Well, it was worth the try. It also could be done if multiple operation/condition based on the same variable was possible. (IF Timecode(HH) < 1 AND Timecode(MM) < 1) 
Thank you for your response.

**Comment by Julusian** [comment]
I dont think it could, not without some more context on the structure of the variable. All companion knows is the current value of the variable and a name for it. Nothing about what the value means, which is the core of the problem.
I am open to making it work, and it probably could be addressed in some way, but I dont think it is worth the cost to do compared to the module providing a feedback for it. Not something to do right now, but it could be considered in a future release

**Comment by LYMPIA** [comment]
Thank you Julian for taking time to answer at my issue. Very instructive.
