### ISSUE TITLE
Analog Way VIO 4K

### ISSUE THREAD

**Issue by PerRoine** [bitfocus/companion#169]
Module to control the Analog Way VIO 4K 
[vio4k_tpp_programmers-guide_for_v1_40_14(2).zip](https://github.com/bitfocus/companion/files/2185591/vio4k_tpp_programmers-guide_for_v1_40_14.2.zip)

**Comment by dnmeid** [comment]
VIO module is in master for a week now. Can somebody please test it with a real device. I got some errors with the simulator.

**Comment by dnmeid** [comment]
@PerRoine, any chance to test with a Vio so far?

**Comment by PerRoine** [comment]
I have tested the VIO 4k and all actions work as expected

**Comment by dnmeid** [comment]
Brilliant, that means the Analogway documentation is correct but the simulator has bugs.
Thank you Per.
