### ISSUE TITLE
[BUG] stream deck mk.2 can not add device list.

### ISSUE THREAD

**Issue by kwonsangjun** [bitfocus/companion#1691]
stream deck app is work.(v5.0)
but companion can not add device list.(v2.1.3)
I guess not support because stream deck mk.2 is latest product.
its same problem on mac and windows.
how can I do?

**Comment by McHauge** [comment]
@kwonsangjun Go ahead and check out the latest 2.2.0 beta, by pressing the "beta builds" button below the normal download button. The latest beta includes drivers for the new streamdeck MK2.

**Comment by kwonsangjun** [comment]
wow!

**Comment by McHauge** [comment]
no problem, but I recommend making a backup of your setup before upgrading. It is after all a beta. but personally, I have used the beta's since 2019 with no problems in my use cases, soo...

**Comment by kwonsangjun** [comment]
hehe~ im beginner. I have no data so not need backup. thank you. I hope get normal new version as soon as passible.

**Comment by McHauge** [comment]
sure, but I would not expect 2.2.0 to be released any time soon maybe in 3-6 months would be my guess. there might however be a 2.1.4 with some stuff backported like support for the MK2, but haven't seen anything that would hint to that yet

**Comment by kwonsangjun** [comment]
okey i see 
you are good advisor
Thank you~

**Comment by Julusian** [comment]
I don't think there are plans to do a 2.1.4, as updating any modules is going to be almost impossible due to various module api changes that have been done in 2.2

I am hopeful that a 2.2rc will be done within 2 months (with a final release within a couple of months after), but there are a couple of things that need some work first.
