### ISSUE TITLE
[BUG] Cannot add Actions or instant feedback to buttons

### ISSUE THREAD

**Issue by Video-Eng** [bitfocus/companion#1692]
When I add a button in Companion, I am unable to add key up, key down, or feedback actions.
I see all of the correct options available in the drop down windows, but upon selecting one, the drop down closes and nothing is added.  The yellow "test actions" button will appear next to the "erase" button, but that is it.

I have tried multiple modules as well as "internal" options

I can add preset buttons and make them work, but am unable to edit those as well.

OS is Windows 10 Pro (x64)
It happens on MS Edge and Google Chrome

Thanks!  Software looks really cool

**Comment by Julusian** [comment]
What modules do you have enabled? 
There is a known bug in 2.1 where if a module updates its list of actions/feedbacks while the add dropdown is open then the dropdown glitches and does nothing. This could be what you are hitting. If so, it is resolved in the 2.2 betas

**Comment by Video-Eng** [comment]
modules I'm using:

bmd-videohub
magewell-ultrastream

**Comment by Video-Eng** [comment]
I was able to resolve the issue with the latest beta build
