### ISSUE TITLE
Failed to load instance edit info: "TimeoutError: Timed out after 5s"

### ISSUE THREAD

**Issue by joshuachung** [bitfocus/companion#1694]
After downloading some configuration from internet, I need to change the module's IP address. In this case the module is PTZoptics VISCA. However, when I tried the to edit the instance, it gives me the above error: **Failed to load instance edit info: "TimeoutError: Timed out after 5s"**. 

<img width="1332" alt="Screenshot 2021-08-22 at 23 31 04" src="https://user-images.githubusercontent.com/2228986/130360979-fb978dda-801c-4a85-b8f8-87a42e62f363.png">

But if I create a new instance, even the IP address of that device are not real and not reachable, no error was found and I can edit the connection afterwards.

Suggest to add an **_edit anyway_** button to ignore the timeout error.

Version: 
2.2.0 (2.2.0-40c762cd-3516)

Tried both macOS and Windows 10.

**Comment by Julusian** [comment]
The problem is that the timeout is in fetching the info needed to display the edit form. So if it was to be displayed, there would be no fields shown.
It would be good to understand why this is timing out. (did it throw and error or is it really slow?) or perhaps the timeout should be increased

**Comment by Julusian** [comment]
I dont think we can do anything here without more information on why it timed out. It is very possible that in this build the visca module would error and fail to return the config fields to display, or it could be anything else
