### ISSUE TITLE
[BUG] Cannot find module 'debug'

### ISSUE THREAD

**Issue by NijsJonas** [bitfocus/companion#1698]
**Describe the bug**
i completely removed companion from my computer and installed it again on my ubuntu subsystem.
when i run companion i get this error: Cannot find module 'debug'

**To Reproduce**

1. went to correct directory: cd /mnt/c
2. cloned companion:git clone https://github.com/bitfocus/companion.git
3. updated: ./tools/update.sh
4. ran companion: node headless.js eth0

**Expected behavior**
companion to start

**Screenshots**
![image](https://user-images.githubusercontent.com/479392/130945487-49bcc383-91f5-448f-89f1-4a1ed4ee170f.png)

**Desktop (please complete the following information):**

- OS: ubuntu subsystem on windows 10
- Browser: chrome
- Companion Version: dont know because it doesnt start

**Comment by Julusian** [comment]
It sounds like ./tools/update.sh didn't run properly. What did it output?

**Comment by NijsJonas** [comment]
![image](https://user-images.githubusercontent.com/479392/131258669-94526ee4-aa45-402b-86a9-3b1365447c88.png)

**Comment by Julusian** [comment]
The last 2 lines of that explain the provlem5

**Comment by NijsJonas** [comment]
my bad, it said recommended and didnt appear as an error so i thought it wasnt important.
it works now, im closing this.

**Comment by curtgrimes** [comment]
I ran into the same issue after following the instructions on https://github.com/bitfocus/companion/wiki/Manual-Install-on-Raspberry-Pi which do not say anything about running update.sh.

**Comment by Julusian** [comment]
@curtgrimes `yarn update` is an alias for `./tools/update.sh`
