### ISSUE TITLE
Feature request: Button Preview

### ISSUE THREAD

**Issue by Deanbau** [bitfocus/companion#17]
Add a preview for button creation page .. if possible have it update with live feedback data

**Comment by PerRoine** [comment]
Just a thought, but could we use the actual emulator with a "edit / emulate" button for the buttonselect in the GUI. Would make sense to have both button select and and the edit window up at the same time.
But that would give you an nice inline PreView and at the same time as you actualy see the whole layout ( and we could flaunt our emulator)
