### ISSUE TITLE
[BUG] connecting ATEM mini - getting started

### ISSUE THREAD

**Issue by geoHeil** [bitfocus/companion#1703]
**Describe the bug**
Trying to getting started & connecting my ATEM Mini with the stream deck MK2 companion is not able to connect to the ATEM device.

**To Reproduce**

1. connect MacBook using thunderbolt-USB-to-ethernet adapter to a switch
     - IP of mac on the switch: 169.254.99.27
     - subnet of mac on the switch: 255.255.0.0
 2. connect Atem mini to switch. Inside ATEM Setup select IP/subnet
     - IP: 192.168.10.240
     - subnet: 255.255.0.0
     - gateway: 192.168.10.1
3. add the ATEM device in the companion app
    - stuck/not completing as device network ping is failing
4. the mac`s WiFi is still enabled

**Expected behavior**
Companion can connect to the ATEM Mini.

**Desktop (please complete the following information):**

- OS: macOS 10.15.7
- Browser firefox
- Companion Version 2.1.3
- Atem Mini Firmware version: 8.6

**Comment by geoHeil** [comment]
Manually setting the IP setup on the Mac to i.e.:

- 192.168.10.241
- 255.255.255.0
allows both devices to find each other.

**Comment by Julusian** [comment]
This is expected due to how ip addresses and networking work. Setting the ip on the mac is the correct solution
