### ISSUE TITLE
[BUG] Elgato Streamdeck MK2 - surface not showing up

### ISSUE THREAD

**Issue by geoHeil** [bitfocus/companion#1704]
**Describe the bug**
My Elgato Stream Deck MK2 is not showing up as a recognized surface

**To Reproduce**

1. go to surfaces
2. rescan
3. the stream deck MK2 is not showing up, although: 1) it is connected via USB and 2) the stream deck app is not running and 3) the stream deck app is finding the MK2

**Expected behavior**
A recognized stream deck MK2

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS 10.15.7
- Browser firefox
- Companion Version 2.1.3
- Streamdeck MK2 Firmware: 1.00.00.1

**Comment by geoHeil** [comment]
seems to be a duplicate of https://github.com/bitfocus/companion/issues/1691

**Comment by Julusian** [comment]
The 2.2 betas are required to use the Streamdeck MK2

**Comment by McHauge** [comment]
@geoHeil Just take the first, they a order after age, each link down is an older build than the one above it

**Comment by geoHeil** [comment]
ok thx
