### ISSUE TITLE
Docker Volumes

### ISSUE THREAD

**Issue by Bond246** [bitfocus/companion#1707]
Hello,

i use the companion with docker on Linux. 
Problem is that by default the container does not use volumes. So everytime i recreate the container i loose my configurations.

So what is to be done do prevent data-loss on docker?
I think everytime export and re-import my full-configuration is not nice.

Thanks

**Comment by Julusian** [comment]
Look into how to run a docker container with a volume mounted https://docs.docker.com/storage/volumes/#start-a-container-with-a-volume

**Comment by Bond246** [comment]
I know how to bind volumes. But I cant find any documentation about where settings and panel configurations are stored.

**Comment by Julusian** [comment]
For a non docker headless installation it is stored under `~/companion`, so I assume that for docker it will be under `/root/companion`
