### ISSUE TITLE
More Commands for PlayBackPro

### ISSUE THREAD

**Issue by Saddi78** [bitfocus/companion#171]
**Describe the feature**
we often have to jump to single Clips. I would like to have the following commands: GOxxxx (Load clip xxx Into Preview) and GTxxxx (Load clip xxx and Take). x should be able to be defined. 
When it's done, I can test it quickly

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
https://www.dtvideolabs.com/user-guide-playbackproplus/#remote_control

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by Saddi78** [comment]
You are great. 
Best regards from Germany. 
We can test in our office the hyperdeck, SpyderX80, casparcg and playbackpro

**Comment by PerRoine** [comment]
Actions added + fast forward, fast reverse, Link temp, play from current location
