### ISSUE TITLE
CompanionPi is it possible to run scripts on a computer within the network?

### ISSUE THREAD

**Issue by BrianGilbert** [bitfocus/companion#1714]
**Describe the feature**
I would like to have buttons on my CompanionPi instance that execute scripts on my PC and Mac that are on the same network.

**Usecases**
Execute scripts related to running my live streams or recording content for youtube of PC or Mac screens (recording/streaming from Atem Mini ISO)

**Comment by Julusian** [comment]
I believe that the vicreo-hotkey module allows for running scripts too

**Comment by BrianGilbert** [comment]
@Julusian Vicreo-hotkey works perfectly, thanks!
