### ISSUE TITLE
[BUG] companion + streamdeck app

### ISSUE THREAD

**Issue by geoHeil** [bitfocus/companion#1717]
How can I get the companion software to play wall with the default stream deck assignments? I want to use my key lights using the control center functionality for brightness, on-off, or color temperature. However, when adding these additional buttons it completely destroys the buttons set up from companion. 

Even when on a different page in the companion app - the buttons are overwritten on all the pages.

**Comment by geoHeil** [comment]
Resetting the profile (by uninstalling and re-installing the stream deck plugin and deleting and re-creating it works (to get the original config back.

However, now the question still remains open how to merge the companion buttons (with the nice pages of hundreds of virtual buttons) with some default buttons from the control center.

**Comment by Julusian** [comment]
You need to make sure that companion doesnt try to access the streamdeck directly. Then you can add the buttons in elgato software to fit into pages for your workflow
