### ISSUE TITLE
More Commands für Hyperdeck

### ISSUE THREAD

**Issue by Saddi78** [bitfocus/companion#172]
**Describe the feature**
can you please include the following commands for the Hyperdeck?
1. play: single Clip: true
2. play: loop: true
3. goto: Clip id: {Clip ID}

**Is this platform dependent (windows, mac, ..)?**
NO

**If documentation is required to implement, do you know where to find it?**
https://private.luxav-cloud.de/index.php/s/dsw92oT5ozzPMAM
You can find the Protocol on Page 73

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by PerRoine** [comment]
Added and tested
