### ISSUE TITLE
[BUG] Raspberry Pi - v2.2.0 - Unable to render settings page

### ISSUE THREAD

**Issue by colegreat06** [bitfocus/companion#1721]
Hey there, I've got many pi's running companion and I just added one to the fleet and when I did a fresh install of it on a Pi 4 with 2GB of ram, I keep getting an error when I visit the settings page. 

Companion Version:  2.2.0 (2.2.0-a8984e8e-3544)
Pi Model: Raspberry Pi 4 B 2GB RAM

Error: "Something went wrong:

Cannot read properties of null (reading 'page_direction_flipped')"

To reproduce: Open companion web portal on Raspberry Pi, click on the settings tab to the right of triggers. It is a red error bar with the message that I listed above.

Browser is Google Chrome on M1 Mac mini (MacOS 11.5.2). In safari, it does the same issue, but it says "Something went wrong:

null is not an object (evaluating 't.page_direction_flipped')"

On both browsers, if I click try again, it works fine, and works for the next page load.
**Update: tested this on a windows PC and an Ubuntu Desktop PC both on Google Chrome and it worked fine. Very strange.

![Screen Shot 2021-09-13 at 9 56 52 PM](https://user-images.githubusercontent.com/71441806/133181937-42aec5b8-7a15-48de-90eb-b5b7715326c9.png)

This is my first time posting on this GitHub (or GitHub in general), so I apologize if I forgot a detail or didn't add the screenshot correctly.

**Comment by jarodwsams** [comment]
1. Did you do a manual install on the Pi OS, or did you flash the pre-built CompanionPi image?
1. Have you tried running `sudo companion-update`
2. Have you tried re-flashing?

**Comment by colegreat06** [comment]
1. I did the manual install on Raspberry Pi OS so I could eventually run other things on the Pi without resetting if needed. I am able to try the pre-built image if you would like, just would prefer the manual install :)
2. Just tried to run `sudo companion update` and it said command not found. Is there something I'm doing wrong?
3. Yes, I actually setup two pi's last night and they both had the same issue, identical hardware and SD cards and all that. On that topic, I did the "reset everything" in companion and it still is giving me the error. I also just tried in Microsoft Edge (still running on m1 mac mini) and still am getting the error.

**Comment by jarodwsams** [comment]
The companion-update command won't work unless you're using the pre-built CompanionPi image. That image can be used as a foundation and then you can run other things on top of it. You just wouldn't want to re-flash later on down the road. That's where the `sudo companion-update` command comes in.

Just for shiggles, try flashing the CompanionPi image and see if you can replicate the behavior.
Flash the image, then on first boot (after the image is expanded to fill the SD card) run the `sudo companion-update` command to make sure you're on the most recent build.

**Comment by colegreat06** [comment]
Oh okay. Good to know. I will test that out later today as soon as I can. Thanks for your help.

**Comment by bryce-seifert** [comment]
FWIW I've seen this on macOS as well. Haven't had time to look into it, but I've definitely seen it more than once.

**Comment by colegreat06** [comment]
Just tried this on the companion Pi image and even on the version that was already on there, it was giving this error.
Preinstalled version of Companion was 2.2.0 (2.2.0-1e65f702-3485). I ran the update command and it updated to 
2.2.0 (2.2.0-a8984e8e-3544). The error isn't happening anymore on this version, no matter which mac I try this on. I'll continue testing this over the next few days.

**Comment by colegreat06** [comment]
Hey there, I wasn't able to find out much more information about this issue. I tested this on a mac running 10.13.6 (previously tested on macs running 12.0 and 11.6) and it's still giving the issue, this time it says "null is not an object (evaluating 't.page_direction_flipped')". Once again works fine on the companion pi image. I have some pi's I need to install at my church this week that will run companion, so I'll use the companion pi image. Thanks for your help.

**Comment by Julusian** [comment]
I have pushed a fix that should resolve this
