### ISSUE TITLE
New trigger condition: "in" and "not in"

### ISSUE THREAD

**Issue by aaronpk** [bitfocus/companion#1725]
When creating a trigger, I'd like to be able to create a condition for trigger when value is in a set rather than just matching a specific value.

I am using the triggers to add an overlay to a two camera angles in livestream when those cameras are on air. I need to be able to remove the overlays when the cameras are off air. The action I would like to create is "Trigger when ATEM program input is not X or Y".

Currently the only workaround is to either create a tally trigger for each of the other 6 inputs to turn the key off air, or add a slight delay to the on air trigger and create two off air triggers for `!=` matching the two camera names.

(The other way to handle this would be to create multiple conditions as an OR, but I realize that's a bigger change with more implications.)

**Comment by Julusian** [comment]
This has been solved with the recent additions to the expression syntax.
