### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DatabaseSuccess** [bitfocus/companion#1729]
https://bitfocus.io/companion/ Safari macOS not showing cookie message, grays page and inoperable. Tested turning off blocker, but not a fix. Safari v14.1.2 on macOS 11.6

**Comment by Julusian** [comment]
If this is still a problem, it would be better to raise this on slack instead https://join.slack.com/t/bitfocusio/shared_invite/enQtODk4NTYzNTkzMjU1LTMzZDY1Njc2MmE3MzVlNmJhMTBkMzFjNTQ2NzZlYzQyZWIzZTJkZWIyNmJlY2U0NzM1NGEzNzNlZWY3OWJlNGE
