### ISSUE TITLE
[BUG] Unable to login to website or download releases

### ISSUE THREAD

**Issue by dan** [bitfocus/companion#1731]
Exactly what the title says.

**Comment by sirwnstn** [comment]
This is correct. I also cannot log into the website to download a release.

**Comment by estilles** [comment]
Site still unavailable.

![image](https://user-images.githubusercontent.com/5514878/134753335-bdb73c16-8cde-4fc1-ae33-89be1be0ee12.png)

**Comment by Kspen** [comment]
Same.  I get "Error creating account. Please try again later. Maximum call stack size exceeded" when trying to create an account.  I downloaded the version from github but not familiar with manually installing electron apps, and the companion docs do not cover the topic.

**Comment by dan** [comment]
It seems odd that the entire human race would be blocked from downloading this software. I wonder how we get the author's attention, when they are clearly not looking here.

**Comment by kraves-oz** [comment]
Jump onto the FB group, someone will have a Google drive link they'll share.  The dev guys are usually pretty responsive to requests, must be busy on projects.  Their server does have hiccups from time to time particularly with the email new accounts side of things.

**Comment by romor001** [comment]
I do not have or use FB. Any other way of downloading the software somewhere?

**Comment by Julusian** [comment]
Slack is also a good place to ask for help https://join.slack.com/t/bitfocusio/shared_invite/zt-o1i0mohx-p_m5I7fUEUJ1BBu_KrDN2Q

It looks from there like this was an issue but might be better now?

**Comment by romor001** [comment]
Yeah thank you for your effort. Much appreciated, but Slack is also one of tose toxic platforms I decline to use.  What a pity.

**Comment by romor001** [comment]
> It looks from there like this was an issue but might be better now?

Still not possible to register new website accounts: "Error creating account. Please try again later. Validation error"

Maybe not a good idea to force users to register. A small "only download" link at the bottom of the form would go a long way.

**Comment by romor001** [comment]
Login and download works now.

Looks like the issue has been resolved.
