### ISSUE TITLE
unable to add instances 

### ISSUE THREAD

**Issue by liquidsky1001** [bitfocus/companion#1732]
**Describe the bug**
when clicking the "add by category" or "add by manufacturer" button no response 
Also when use the search tool, no response...

**Expected behavior**
to add a generic osc

**Desktop (please complete the following information):**

- OS: [windows 7 pro SP1]
- Browser [explorer]
- Companion Version [2.1.3]

**Comment by Julusian** [comment]
Duplicate of #1740
