### ISSUE TITLE
[BUG] nodemon not restarting: [nodemon] restarting due to changes...

### ISSUE THREAD

**Issue by estilles** [bitfocus/companion#1733]
**Describe the bug**
This is not a bug with the actual app. During development when using `yarn headless`, `nodemon` doesn't automatically restart the app when relevant saving files. Occasionally, saving a file several times consecutively triggers a restart.

The issue started after commit 8426564, which bumped `nodemon` from `v2.0.7` to `v2.0.12`. 

This issue has been reported in  remy/nodemon#1882

**To Reproduce**

1. `yarn headless
2. Make changes/save a file
3. `nodemon` displays: `[nodemon] restarting due to changes...` on the console
4. `nodemon` doesn't restart Companion

**Expected behavior**
`nodemon` should restart companion upon saving files and we should see the following message:
```
[nodemon] restarting due to changes...
[nodemon] starting `node headless.js`
Starting
Starting headless with interface "Loopback Pseudo-Interface 1"
Started
```

**Desktop (please complete the following information):**

- OS: Windows 10.0.19043
- Browser: N/A
- Companion Version 2.2.0 (after commit 8426564)
- VS Code 1.60.2

**Additional context**
As a workaround I've manually reverted back to `v2.0.7` during development.

**Comment by Julusian** [comment]
good spot. I have downgraded it to 2.0.7 and will watch that issue to check when it is safe to update again
