### ISSUE TITLE
Extended character support for button text

### ISSUE THREAD

**Issue by DaveShep** [bitfocus/companion#174]
Add support for common non-alphanum characters e.g. arrows or triangles, circle (record), square (stop) , pause, power icon etc.

While you can edit a png to achieve this, i think it would be nice to have.

**Comment by dnmeid** [comment]
Ok, this functionality now has been included since aacb121d27606dadfb63bf910ed4ebc021460a70
Companion now is compatibel with UTF16 unicode characters. Around 1000 symbols have been added to the fonts.
