### ISSUE TITLE
not possible to add connection or instance

### ISSUE THREAD

**Issue by liquidsky1001** [bitfocus/companion#1740]
*Describe the bug**
not possible to add connection 

**To Reproduce**

1. Go to 'instances'
2. Click on 'add by category' or 'add by manufacturer'
no response, no menu that opens to select a connection (generic OSC)
same problem with the search option...

**Expected behavior**
open a selection menu to add a connection

**Screenshots**

**Desktop (please complete the following information):**

- OS: windows 7 SP1
- Browser: explorer
- Companion Version: 2.1.3

**Additional context**

**Comment by Julusian** [comment]
Could you try an up to date browser such as chrome or firefox?
I do not know if we support windows 7 anymore, and it is likely that internet explorer will not work
