### ISSUE TITLE
Cannot download CompanionPi Image

### ISSUE THREAD

**Issue by cmccoll94** [bitfocus/companion#1741]
When I attempt to download the CompanionPi image from any browser or network, I receive an error:
(KCFErrorDomainNetwork)
The image usually downloads between 5 - 130 mb before this error comes up
<img width="586" alt="Screenshot 2021-10-03 at 08 27 39" src="https://user-images.githubusercontent.com/51296701/135744349-5f04018b-dce0-4f26-a064-2ec495f3db59.png">
.

**Comment by MichaelMader** [comment]
Hi, 
Im also having the same issue, Keep getting a network error as well.

**Comment by McHauge** [comment]
Hi @cmccoll94 and @MichaelMader, I get the same error when i try, and I'm not in a position to fix it, but I did find a build of it in my other pc's download folder, there for feel free to donwload it from here: [OneDrive](https://1drv.ms/f/s!AtUYbExJseNtlK56u-n71V_UcLDe7g)
