### ISSUE TITLE
A java script error occurred in the main process

### ISSUE THREAD

**Issue by RevIngram** [bitfocus/companion#1748]
Hi bitfocus,
Thank you for Companion! I'm using it to control an ATEM with a stream deck, in the last couple of days I get this error every time Companion launches (see attached screen shot).
I removed and re-installed, but get the same error.
Cheers,
Charlie
![All Photos - 1 of 1](https://user-images.githubusercontent.com/91961684/136032580-e3bab9ff-79fe-4294-8548-ee982ec78f57.jpeg)

**Comment by Julusian** [comment]
This is a common error that is thrown when the port is in use by another process.
A reboot will generally resolve this
