### ISSUE TITLE
What instance do you use to open websites?

### ISSUE THREAD

**Issue by TIMCARISTA** [bitfocus/companion#1751]
What instance works best with simple commands like opening a specific website?  I am using companion on a stream deck XL.  TIA

**Comment by josephdadams** [comment]
I use the Vicreo Hotkey module along with the free Vicreo Listener program. Depending on the OS, I send a file execute command with the full escaped path to my web browser executable and include an argument to launch a specific URL.

Here's an example of what I might send on MacOS:
![Screen Shot 2021-11-24 at 3 43 58 PM](https://user-images.githubusercontent.com/2559091/143310482-1fba4ff9-1b6a-4080-b452-555928e513bc.png)
