### ISSUE TITLE
When opening Bitforce Companion I receive a javascript error message "A JavaScript erro occurred in the main process - Uncaught Execption: SynbtxError: Unexpected Token" [BUG]

### ISSUE THREAD

**Issue by dlsmith537** [bitfocus/companion#1757]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
![Bitfocus Companion JavaScript Error](https://user-images.githubusercontent.com/92240192/136680928-e224711e-846f-43e7-87cf-8df1efa3ad3b.PNG)

- Companion Version [e.g. 2.0]

**Additional context**
Add any other context about the problem here
![Bitfocus Companion JavaScript Error](https://user-images.githubusercontent.com/92240192/136680924-89f9807c-3f87-4ead-913d-84043894aec7.PNG)
.

**Comment by Julusian** [comment]
The first issue here looks like the db file has gotten corrupt. Try deleting that and it should launch again. should be under `%APPDATA%/companion` or something.

The second issue will likely go away after restarting the computer
