### ISSUE TITLE
Disable access to stream deck

### ISSUE THREAD

**Issue by Grappa2020** [bitfocus/companion#1771]
I like to use stream deck connected directly to application and run companion for other function without affecting stream deck.
so it will be nice to have the ability to disconnect from physical stream deck same as it implemented now for xkeys on version 2.

**Comment by Julusian** [comment]
I have been wondering if there should be an option to choose between companion attempting to use streamdecks, and enabling support for the elgato plugin

**Comment by Julusian** [comment]
This is implemented in the latest betas. There is now a setting to switch between having the elgato plugin api enabled, or to scan for local streamdecks
