### ISSUE TITLE
Automatically resize button images that is below minimum dimensions

### ISSUE THREAD

**Issue by kjetilpp** [bitfocus/companion#1774]
A feature that allows use of smaller icons. 
Now, we use icons from materialdesignicons.com that are 48x48, on the Stream deck Elgato software it works fine, but migrating to Companion we have a problem with "Image dimensions must be at least 72x58"
Maybe auto resizing small icons? Would be nice if we can use the same icons without too much hassle.

**Comment by estilles** [comment]
Hey @kjetilpp. Thanks for opening a new request. Let me think of the best way to implement this.

**Comment by Julusian** [comment]
I think that the current code will handle resizing smaller icons just fine, but its blocked because generally doing so will cause them to not look great due to the lack of resolution.

**Comment by estilles** [comment]
> I think that the current code will handle resizing smaller icons just fine, but its blocked because generally doing so will cause them to not look great due to the lack of resolution.

You're right @Julusian. Resizing smaller images may not look that great. I'm not thinking so much about resizing smaller images, but maybe allowing smaller images and padding them to 72x58.

For example, 48x48, 36x36 and even 24x24 (padded to 72x58) look pretty good.

![image](https://user-images.githubusercontent.com/5514878/139914411-cd78b573-762f-47e9-b80a-ad90c1f83f25.png)

What do you think?

**Comment by kjetilpp** [comment]
I like it 👍

**Comment by estilles** [comment]
I think the 24x24 may be a bit small, but the 36x36 and 48x48 look fine on my Stream Deck.

@Julusian, would you guys be willing to allow me to reduce the minimum button image size to 36x36?

**Comment by kjetilpp** [comment]
Did change the code and rebuild my install, so it works with 36x36, so far no issues with 48x48 from materialdesignicons.com. ❤️

**Comment by estilles** [comment]
> Did change the code and rebuild my install, so it works with 36x36, so far no issues with 48x48 from materialdesignicons.com. ❤️

Great! I have the change in my local build as well. I'm still waiting on guidance so I can submit the PR.

**Comment by estilles** [comment]
@kjetilpp ... Unless, of course, you want to submit the PR since it's your issue. ;-)

**Comment by kjetilpp** [comment]
@estilles Leave it to those of you who can do this, unfortunately not familiar with Git, probably Google can get me to it but.. 😉
You can probably just submit PR, and we'll see if it is approved? 😃

**Comment by KzBoy** [comment]
> > I think that the current code will handle resizing smaller icons just fine, but its blocked because generally doing so will cause them to not look great due to the lack of resolution.
> 
> You're right @Julusian. Resizing smaller images may not look that great. I'm not thinking so much about resizing smaller images, but maybe allowing smaller images and padding them to 72x58.
> 
> For example, 48x48, 36x36 and even 24x24 (padded to 72x58) look pretty good.
> 
> ![image](https://user-images.githubusercontent.com/5514878/139914411-cd78b573-762f-47e9-b80a-ad90c1f83f25.png)
> 
> What do you think?

This is great, using smaller images lets you add text easier without constantly opening an image editor.

**Comment by estilles** [comment]
I'll submit a PR later this weekend. Hopefully it will get approved.

**Comment by KzBoy** [comment]
Does the change pad smaller icons or enlarge them? Ideally it would work how it used to work so that but using smaller images you can actually have a smaller icon. The image you posted is how it should work imo, and anything larger could be scaled down.

**Comment by KzBoy** [comment]
Thats better, I still can use images I used to be able to (32x32) however 48x48 works as intended quite nicely. 

The img above goes down to 28x28. Any reason we shouldn't further lower it?

**Comment by estilles** [comment]
> The img above goes down to 28x28. Any reason we shouldn't further lower it?

On the Stream Deck itself 36x36 images still look excellent, 24x24 look okay, but not great. @Julusian commented above: "its blocked because generally doing so will cause them to not look great due to the lack of resolution."

Taking this into consideration and airing on the side of caution, I suggested the 36x36 limit.
