### ISSUE TITLE
Freeze Inputs for Ascender

### ISSUE THREAD

**Issue by larskmann** [bitfocus/companion#178]
**Describe the feature**
Freeze Input XY as a toggle button? Or just as a button?

**If documentation is required to implement, do you know where to find it?**
[LiveCore_TPP_Programmers-guide_for-v04-02-23.pdf](https://github.com/bitfocus/companion/files/2206911/LiveCore_TPP_Programmers-guide_for-v04-02-23.pdf)

**Usecases**
Could be done by custom command too, but for a faster workflow would be great to have it in the dropdown menu :)

**Comment by haakonnessjoen** [comment]
Freezing of inputs was recently added. Try the latest build at https://builds.bitfocus.io/companion/
