### ISSUE TITLE
streamdeck mk.2

### ISSUE THREAD

**Issue by JeffGefke** [bitfocus/companion#1782]
Mac Mini M1 
Monterey

Streamdeck MK.2
2.2 software

Loaded a file from previous use with regular Streamdeck 15 button
Companion does not see the device, emulator works fine. 

Will it work with the template that used on the original 15 button?

**Comment by Julusian** [comment]
The MK2 streamdeck already works with 2.2 builds from the last few months. 
How recent is your 2.2 beta version?

**Comment by JeffGefke** [comment]
Got it, had 2.1 installed.....late night!

2.2 works perfect!
THANKS
