### ISSUE TITLE
Can't load new beta versions[BUG]

### ISSUE THREAD

**Issue by jsnyder886** [bitfocus/companion#1783]
**Describe the bug**
Last build that I was on successfully was 3583.  I attempted to upgrade to 3594 tonight.  Companion starts up but will not load the config file.  When opening the GUI, it hangs with a red progress bar stuck about 3/4 of the way across the progress bar.

I can remove my old configuration and 3594 will start up just fine.

I then downloaded 3593 and experienced the same results.

I then reinstalled 3583 and my old configuration works as expected.

**To Reproduce**
As described above.

**Expected behavior**
Companion to start and run.

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- Browser: Chrome
- Companion Version:  2.2.0

**Comment by krocheck** [comment]
Try 3595 ... looks like I let a booboo into the wild.

**Comment by jsnyder886** [comment]
It's bound to happen on occasion; thanks for looking into it so quickly!

3595 does in fact startup as expected with the old configuration loading without error or hang.

Thanks again!

Jon
