### ISSUE TITLE
install beta version on raspberry pi

### ISSUE THREAD

**Issue by kwonsangjun** [bitfocus/companion#1786]
how can I install beta version on raspberry pi 4?

I was manual install companion to /home/pi/companion
* installed companion version : 2.2.0 (2.2.0-11dc4b4f-3603)

and I downloaded beta version to /usr/local/src and decompress.

I need beta version because I have stream deck MK.2

stream deck MK.2 works only on beta version.  

but I don't know how to change beta version...

how can I do?

**Comment by krocheck** [comment]
try

**Comment by krocheck** [comment]
Try
`cd /home/pi/companion`
then
`yarn update`

**Comment by kwonsangjun** [comment]
> Try
> `cd /home/pi/companion`
> then
> `yarn update`

thank you for reply
is yarn update insatall beta version? 
I want install last beta version. 
so downloaded beta update tar file. but how to where move it? I don’t know

**Comment by estilles** [comment]
@kwonsangjun, you should check out this article on installing Companion on a Raspberry Pi
https://github.com/bitfocus/companion/wiki/Companion-on-the-Raspberry-Pi

**Comment by kwonsangjun** [comment]
> @kwonsangjun, you should check out this article on installing Companion on a Raspberry Pi
> https://github.com/bitfocus/companion/wiki/Companion-on-the-Raspberry-Pi

thank you I will check~

**Comment by kwonsangjun** [comment]
my Stream Deck MK.2 work on 'CompanionPi-2021-07-25.img.gz' image
I think normal install is old version. 
Thank you.
