### ISSUE TITLE
Regular button broken if used via dropdown [BUG]

### ISSUE THREAD

**Issue by KzBoy** [bitfocus/companion#1789]
**Describe the bug**
If using the drop down arrow the 'Regular Button' link doesn't work.

**To Reproduce**

1. Select an unused button
2. Click the drop down arrow (lists: Regular button, Page up, ect...)
3. Select 'Regular button'
4. Nothing happens

**Expected behavior**
Would expect the same behavior as using the large green 'Regular button' button.

**Screenshots**
![image](https://user-images.githubusercontent.com/33883664/141887261-78c60ddc-d6f6-4e69-ba2e-02ead80902f0.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome
- Companion Version 2.2.0-0d9110af-3609

**Additional context**
Could simply remove the option from the dropdown menu.

**Comment by Julusian** [comment]
This is fixed
