### ISSUE TITLE
Cut transition on ANY layers reverts to BKGD layer upon exit of configuration in Web GUI / only cuts BKGD layer when using "Test actions" button

### ISSUE THREAD

**Issue by PTGitHubber** [bitfocus/companion#179]
On latest Mac OS build - using Panasonic AV-HS410

First option:
Go to 'Buttons'
Click on a button
Add action '410: Send CUT transition'
Set Target to 'KEY'
Click 'Test actions'
**RESULT: Background Layer transitions via CUT; no action on KEY Layer - This result replicated when attempting on all Target Layers**

Second option:
Go to 'Buttons'
Click on a button to enter Configurator
Add action '410: Send CUT transition'
Set Target to 'KEY'
Go to 'Buttons'
Hold Shift and press button to test
**RESULT: Background Layer transitions via CUT; no action on KEY Layer - This result replicated when attempting on all Target Layers**
Click on previously configured button to enter Configurator
**Target Layer is now set to BKGD - Result replicated when attempting on all Target Layers**

**Comment by PTGitHubber** [comment]
I just noticed this in the code:

All Cut destinations are the same number: 00. Changing this should fix the problem listed above.

![screen shot 2018-07-19 at 11 40 53](https://user-images.githubusercontent.com/40829374/42916492-d2960f4c-8b48-11e8-974e-5da575017f22.png)

**Comment by haakonnessjoen** [comment]
Thanks! I will fix it :)
