### ISSUE TITLE
[BUG] Companion Buttons appearing and activating outside of their set folder, despite another folder or page being in focus.

### ISSUE THREAD

**Issue by CravenInsomniac** [bitfocus/companion#1795]
**Describe the bug**
Companion has stopped respecting Stream Deck buttons when companion buttons are placed in folders. To further clarify, Companion actions are being triggered irregardless of the buttons being pressed.

**To Reproduce**
1. Make a folder on Stream Deck software.
2. Place a companion button.
3. Exit folder,
4. Press the button that matches the placement of the companion button. It can be an empty button, a folder, or another type of button. The button's LCD will either briefly flash with the companion buttons graphic if the buttons is occupied, or it will be fully replaced by companion graphic if empty; and the action will be activated.

**Expected behaviour**
When companion buttons are placed in folders, you should need to navigate to said folder in order to not activate companion action by accident.

**Screenshots**
[Link](https://imgur.com/a/kdTkWIT) to Imgur post and accompanying screenshots.

**Desktop (please complete the following information):**

- OS: Windows 10 Pro 21H1 Build:19043.1288
- Companion Version: 2.1.3 (2.1.3-6b6820cd-2696)
- Elgato Stream Deck Version: 5.1.3.14750
- Stream Deck Firmware Version: 1.00.012

**Comment by Julusian** [comment]
This sounds like companion and the streamdeck application are both assuming they have exclusive control of the device.
If you simply unplug and replug the streamdeck then companion should lose it and then the streamdeck software will have sole control.

Essentially you need to be careful of order things start up in. Companion will claim every streamdeck it can find when it starts or when you click scan in the surfaces tab. The elgato software will claim every streamdeck at startup and watches for new ones.

**Comment by CravenInsomniac** [comment]
So, currently I have the Elgato Stream Deck and Companion software start via Window's Task Scheduler. Am I understanding you correctly when I say I should delay Elgato's software so it starts after Companion? Or should I do it in the reverse?

**Comment by CravenInsomniac** [comment]
After tinkering it seems that having Companion start before Elgato's Stream Deck software is indeed the way to go, leaving this open as the bug still occurs, I've just got a workaround. If anyone else happens upon this issue, I do have a recommendation. Make a button on the stream deck to restart the software itself.

To do this, make an "🚀 Open" button (found in System drop down). Have that button open a batch script that contains
`taskkill /F /IM streamdeck.exe & cd {Elgato Stream Deck Install Directory mine is "C:\Program Files\Elgato\StreamDeck" for example} & start StreamDeck.exe --runinbk`.
And then you'll be off to the races if the issue occurs despite setting Companion to run before Elgato's software. (Which occurs randomly but MUCH less frequently than before.)

**Comment by Julusian** [comment]
This shouldnt be a problem anymore.
The elgato plugin api has to be explicitly enabled, and doing so disables companion accessing devices directly
