### ISSUE TITLE
Moduel Request: for Brightsign control

### ISSUE THREAD

**Issue by Roeland22896** [bitfocus/companion#180]
Could you also consider to add brightsign control for selecting video’s and parameters? 
Brightsigns are powerfull media players for signage and other applications. But they don’t really have hardware for control. So this could be a nice solution :)
Brightsign accepts udp commands:
https://brightsign.zendesk.com/hc/en-us/articles/218066697-How-do-I-control-the-BrightSign-using-serial-or-UDP-Crestron-AMX-smartphones-tablets-etc-?mobile_site=true

**Comment by JeffreyDavidsz** [comment]
It's in one of the latest builds, check it out
