### ISSUE TITLE
Companion App - Scheduler - Feature Request !

### ISSUE THREAD

**Issue by Jason-Vaughan** [bitfocus/companion#1803]
**Describe the feature**
Scheduled cues

**Usecases**
For media playback for digital signage, booths and other content that needs cueing devices based on time of day or other logic.  A scheduler would be awesome !

**Comment by josephdadams** [comment]
Boy oh boy do we have news for you!

**Comment by josephdadams** [comment]
@onfire4g05 tell him what he’s won!

**Comment by Jason-Vaughan** [comment]
way to leave a guy hangin !  You got something I can schedule cues to fire thru companion with...?

**Comment by josephdadams** [comment]
We added a scheduler to the betas like a year ago

**Comment by Jason-Vaughan** [comment]
Thats what I get for not running Beta revs...!   Thanks, I'll check it !

**Comment by onfire4g05** [comment]
Hah!! Yeah, I needed this functionality as well and was able to get it added to core and then Julian made it even better. I didn't think it had been a year, but I think it has been! 😂 Have fun and enjoy!!

**Comment by Jason-Vaughan** [comment]
So is it just the module I need to install…?

I found this repo:   https://github.com/bitfocus/companion-module-ltn-schedule <https://github.com/bitfocus/companion-module-ltn-schedule>

Or is there special beta version somewhere….?  I didn’t see a “beta” 

Thanks !

**Comment by McHauge** [comment]
If you go to the normal download place on the website and press the small link "beta builds" just below it, you will find it 👍

**Comment by Jason-Vaughan** [comment]
Oh wow, lots of options here….. 

Is this the one I should try, its at the very top of the list….?

chore(webui): prep package.json for release

**Comment by McHauge** [comment]
@Jason-Vaughan they are basically all the same, it's all from master, but they are sorted by age, so for each line down you are just getting an older version of the same 2.2.0 setup, this means that if you have a problem you can go back and find where that was added/changed an see if that helps, it makes it simpler for testing and If something big breaks you can go back a day or just a few hours until it's fixed again.
