### ISSUE TITLE
Button Numbers not displayed correctly - Streamdeck Displaying XL on Standard Streamdeck[BUG]

### ISSUE THREAD

**Issue by OBtruck** [bitfocus/companion#1805]
**Describe the bug**
My Streamdeck (15 Button) Displays the button number as follows - 1.1 - 1.2 - 1.3 - 1.4 - 1.5
NEXT ROW 1.9 - 1.10 - 1.11 - 1.12 - 1.13
NEXT ROW 1.17 - 1.18 - 1.19 - 1.20 - 1.21

It used to be as follows:
 1.1 - 1.2 - 1.3 - 1.4 - 1.5
 1.6 - 1.7 - 1.8 - 1.8- 1.10
 1.11 - 1.12 - 1.13 - 1.14 - 1.5

Usually should display rows of 5, but when going onto web button tab in companion it has buttons in rows of 8...
It also highlights/shadows my streamdeck model as well but still numbers the buttons incorrectly as seen in image 3

**To Reproduce**
Not sure how to reproduce as this is now default and cannot find a way to revert back to the facotry settings of 5 numbers consecutivley in a row. 

**Screenshots**
See attached
![Image 3](https://user-images.githubusercontent.com/95257811/143962172-2069db56-ef62-48b0-a055-f864f723efac.png)
![Image 1](https://user-images.githubusercontent.com/95257811/143962177-ab818458-36b0-4edf-bd4a-b73ca3320db5.png)
![Image 2](https://user-images.githubusercontent.com/95257811/143962181-5bea77a5-0a5c-4b2f-8213-ce677b97c9a9.png)

**Desktop (please complete the following information):**
- OS: Windows 10 Home 64Bit and iOS High Sierra 10.13.6
- Browser Google Chrome
- Companion Version 2.1.3 and also 2.2.0

**Comment by Julusian** [comment]
We intentionally always show a grid of 8x4 for all users so that if you were to add an XL to your system it will work without needing any complex data updates, so this is by design.
