### ISSUE TITLE
[BUG] No internal functions after importing config file

### ISSUE THREAD

**Issue by slechtvalk200** [bitfocus/companion#1810]
**Describe the bug**
After i imported a .companionconfig from a Macbook, i can not see any internal function anymore. Already did "Reset full configuration" , uninstalled, installed again. No change. 

**Screenshots**
![nionternal](https://user-images.githubusercontent.com/10530930/144601505-49951572-7280-4eb0-927d-ab65be701984.jpg)

**To Reproduce**
just import a config, unshure if it depends if it came from a mac or windows

**Desktop:**
Windows 10
companion V2.1.3
Firefox
Chrome
Edge

**Comment by slechtvalk200** [comment]
deleting AppData\Roaming\Companion solved the problem

**Comment by estilles** [comment]
Hey @slechtvalk200 ... since you resolved the issue I'm going to close the issue for now. Feel free to reopen if you need to.
