### ISSUE TITLE
What "Triggers" Tab? I don't see one

### ISSUE THREAD

**Issue by tacvideo** [bitfocus/companion#1812]
See screenshot below, I'm on the latest version (2.1.3) and on a Mac OsX 11.x & 12.x, don't see the Tab...
![image](https://user-images.githubusercontent.com/73620763/144728327-6eba0431-e7b6-42ed-9ef6-db82603dfddc.png)

**Comment by Julusian** [comment]
It's only available in the 2.2 beta builds
