### ISSUE TITLE
Using Internal Variables for internal shell commands / h2r

### ISSUE THREAD

**Issue by farm-cyeo** [bitfocus/companion#1813]
**Describe the feature**
I would like to be able to use an internal variable and pass that to an shell command.

**Usecases**

So my specific use cases are pretty easy...  We are livecasting out a swim meet.  I have a list of lanes and swimmers based on events and heats.  I have setup counters for the events and heats, and can increment them (as well as reset heats back to 1).

So with that, I want to create a specific webpage based from a template, and a CSV file with data in it.  So I have a script that takes 'Event' and 'Heat' and will update the webpage which creates the overlay that goes over the actual pool with the lane numbers and names.

HTML page created
Script for updating said page created, and tested 
Just need Companion to pass the variable to the script and then I am done.

Now for the second 2 user case...

I would like to display specific lower third, again, I have self incrementing button and when I ask it to push out a lower 3rd, I can't use that variable, and if I try using the generic osc, that doesn't work either.

Now I understand the VMIX plugin works just fine with the internal variables... it would be super handy if all of them did.

**Comment by estilles** [comment]
Hey @farm-cyeo.

This is the right place to request a feature for the "internal: Run shell path" action.

However, for specific modules those should be raised in the corresponding repositories. Module developers are free to implement which ever features they see fit for their modules.

For H2R graphics you should request [here](https://github.com/bitfocus/companion-module-h2r-graphics/issues).

**Comment by estilles** [comment]
Just realized there's already an issue open regarding variables in H2R Graphics. 

bitfocus/companion-module-h2r-graphics#10

**Comment by farm-cyeo** [comment]
> 

HI @estilles if there is anything I can do from testing or to help funding this to make it happen faster, that would be great to know.

**Comment by estilles** [comment]
> HI @estilles if there is anything I can do from testing or to help funding this to make it happen faster, that would be great to know.

You should probably continue this conversation in companion-module-h2r-graphics#10. 

You shoud probably have a chsnt with @iamjohnbarker who is the maintainer of that module.

**Comment by iamjohnbarker** [comment]
I'm working on this for a major rewrite of the H2R Graphics module. It will only work on when using H2R Graphics v2 though

**Comment by Julusian** [comment]
I think all the parts of this are done now
