### ISSUE TITLE
Internal Shell Commands all trigger Guru Meditation Error[BUG]

### ISSUE THREAD

**Issue by ASwann1996** [bitfocus/companion#1815]
**Describe the bug**
Every time I try to run any type of internal shell command(I'm attempting to either launch a program from my applications folder, or simply open a folder in finder), I get this error:

07. 15:40:32 instance(internal): Shell command failed. Guru meditation: {"killed":false,"code":127,"signal":null,"cmd":"\"sh open -a ProPresenter\""}

It seems this is NOT a syntax error - I've tried with and without quotes, I've tried with and without file extensions, I've tried with the complete path, I've tried with and without sudo, and all variations I can think of in all of these combinations. If I type nonsense, nothing changes. If I run these shell commands through the terminal, they work fine. The only thing I've ever typed that does NOT throw this error, is PWD. This is happening on both computers I'm trying this on - Mac OS, Big Sur for one and Catalina for the other.

**To Reproduce**

1. Add a button 
2. Assign button to internal: Run internal shell command
3. Add any shell command besides pwd
4. Error

**Expected behavior**
I should just run the shell command successfully, launching the program or opening the folder in finder.

- OS: [e.g. iOS] Mac OS Big Sur or Catalina(Big Sur is 11.1)
- Browser Chrome and Safari
- Companion Version 2.1.3

**Comment by estilles** [comment]
In order to get `sh` to run a command from a string you need to use the `-c` flag. If the command you want to run (in your case `open -a ProPresenter`) includes spaces you'll also need to enclose the command in double quotes.

Try this:

<img width="622" alt="Screen Shot 2021-12-08 at 10 03 11 AM" src="https://user-images.githubusercontent.com/5514878/145135345-a30a8d10-d09a-44db-941a-5738d5f95a1a.png">

**Comment by ASwann1996** [comment]
> 

Using the sh command was just the last in my many variations of what I tried.

I have not tried what you put here, I’ll try it tomorrow, but is there any reason it should not have worked with just:
“open -a ProPresenter”?

I’ve done that with quotes, with the full path, file extensions, every variation I can think of. I always get the same guru meditation error listed above, no matter what. This error has popped up on some other threads using shell commands, but they all seem to be solved using strange workarounds. 

It doesn’t seem like this is an issue with the syntax, but I will try what you’ve suggested in the morning and report back.

**Comment by estilles** [comment]
I just assumed you wanted to use `sh` because it's in your original message. If you don't want to use `sh` and just want to call the `open` command directly you should enclose just the open command in double quotes followed by whatever parameters (e.g. `"open" -a ProPresenter`)

This should work as well:

<img width="621" alt="Screen Shot 2021-12-08 at 11 04 24 AM" src="https://user-images.githubusercontent.com/5514878/145141118-2956b236-aabb-43a0-a207-8a1a589d7ebc.png">

**Comment by estilles** [comment]
> is there any reason it should not have worked with just: “open -a ProPresenter”?

Does `open -a ProPresenter` work from your terminal?

**Comment by ASwann1996** [comment]
> > is there any reason it should not have worked with just: “open -a ProPresenter”?
> 
> Does `open -a ProPresenter` work from your terminal?

open -a ProPresenter works from the terminal. 

HOWEVER, the other syntax you suggested, with the quotes around "open" worked!
So: "open" -a ProPresenter 
Works great. 


I can't figure out how to open a folder though, even with this same change. 
I've tried with:
"open" -folder /swann/Music/Logic/Bitter - Tracking/Fixed Vox
And also just
"open" /swann/Music/Logic/Bitter - Tracking/Fixed Vox

Thanks for your guidance on this, extreme amateur here and I'm trying to wrap my head around how Companion needs to receive shell commands for them to work.

**Comment by estilles** [comment]
> I can't figure out how to open a folder though, even with this same change.
I've tried with:
"open" -folder /swann/Music/Logic/Bitter - Tracking/Fixed Vox
And also just
"open" /swann/Music/Logic/Bitter - Tracking/Fixed Vox

When specifying a path that contains any spaces (like in your example above) it too must be enclosed in quotes. The `open` command expects a single argument (plus a number of optional flags). Spaces normally serve as argument delimiters, so in your example above `/swann/Music/Logic/Bitter` is the first argument, `-` the second, `Tracking/Fixed` the third and `Vox` the forth. However, if you enclose the entire path with double quotes, the shell will interpret the enclosed string as a single argument.

Try this:
```
"open" "/swann/Music/Logic/Bitter - Tracking/Fixed Vox"
```

**Comment by ASwann1996** [comment]
> > I can't figure out how to open a folder though, even with this same change.
> > I've tried with:
> > "open" -folder /swann/Music/Logic/Bitter - Tracking/Fixed Vox
> > And also just
> > "open" /swann/Music/Logic/Bitter - Tracking/Fixed Vox
> 
> When specifying a path that contains any spaces (like in your example above) it too must be enclosed in quotes. The `open` command expects a single argument (plus a number of optional flags). Spaces normally serve as argument delimiters, so in your example above `/swann/Music/Logic/Bitter` is the first argument, `-` the second, `Tracking/Fixed` the third and `Vox` the forth. However, if you enclose the entire path with double quotes, the shell will interpret the enclosed string as a single argument.
> 
> Try this:
> 
> ```
> "open" "/swann/Music/Logic/Bitter - Tracking/Fixed Vox"
> ```

I've got the same guru meditation error with that syntax - 
<img width="460" alt="Screen Shot 2021-12-09 at 9 29 33 AM" src="https://user-images.githubusercontent.com/95719371/145415097-c6f93454-8222-4022-bb28-57a5b75d877d.png">

**Comment by estilles** [comment]
> I've got the same guru meditation error with that syntax - <img alt="Screen Shot 2021-12-09 at 9 29 33 AM" width="460" src="https://user-images.githubusercontent.com/95719371/145415097-c6f93454-8222-4022-bb28-57a5b75d877d.png">

That is a different error. The original error `code: 127` means "command not found". `code: 1` is a more generalized/non-specific error. Let me see if I can figure out what could be wrong.

**Comment by estilles** [comment]
The first troubleshooting I would recommend is if the command work from the terminal. Have you checked if ...

```
open "/swann/Music/Logic/Bitter - Tracking/Fixed Vox"
```

... works from the terminal?

Is it possible the path name doesn't exist? I see you're trying to open 

`/swann/Music/Logic/Bitter - Tracking/Fixed Vox`.

I'm going to assume:

- you're on a Mac
- `swann` is your user/login name

Is it possible the path you're trying to open is ...

`/Users/swann/Music/Logic/Bitter - Tracking/Fixed Vox`
