### ISSUE TITLE
Cross Profile Support

### ISSUE THREAD

**Issue by martinidean** [bitfocus/companion#1816]
I have a bunch of Streamdecks running companion in a college controlling their zoom setups. At the moment each room has an instructor profile and an admin profile, both of which have to be set up by importing the correct config file with the correct IP addresses. Once set this is not a problem.

The issue is if the IT admins decide to do a mass reimaging of machines or allow users to use their own profiles Companion will not have the correct config file for the room as the config file is specific to a user profile I believe.

So the question is can there be an option where you can specify where to load the configuration file (i.e. in a common folder where all user profiles can see it), either as a setting or a command line option.

**Comment by Julusian** [comment]
In the 2.2 beta versions, you can use the `COMPANION_CONFIG_BASEDIR` environment variable to specify the path to the config. You could either edit the shortcuts used to open companion, or you should be able to define it globally for the computer.
Be aware that every user will need write access to that location or companion will throw various errors while running. Make sure you can trust your users to not mess with the config and break things for everyone.

Another way to go would be to setup a login script to copy a prebuilt config from somewhere to the right place in the user folder (or change the shortcuts to run a launch script). That way the 'master' copy can be readonly to every user, and they will only be able to break the config for themselves which would then be reset back to the default upon next login
