### ISSUE TITLE
"JavaScript heap out of memory" 

### ISSUE THREAD

**Issue by Manfe07** [bitfocus/companion#1818]
Hey I'm trying to install companion on a raspberryPi 3 B+
But every time i run update.sh it crashes at 
`yarn --cwd webui build`
i got the error:

> ```
> pi@raspberrypi:~/companion $ yarn --cwd webui build
> yarn run v1.22.17
> $ react-scripts build
> Creating an optimized production build...
> 
> <--- Last few GCs --->
> 
> [15844:0x41999d0]   124062 ms: Scavenge (reduce) 225.0 (230.9) -> 224.9 (231.4) MB, 7.5 / 0.0 ms  (average mu = 0.211, current mu = 0.061) allocation failure 
> [15844:0x41999d0]   124073 ms: Scavenge (reduce) 225.1 (232.4) -> 225.0 (232.9) MB, 4.7 / 0.0 ms  (average mu = 0.211, current mu = 0.061) allocation failure 
> [15844:0x41999d0]   124806 ms: Mark-sweep (reduce) 225.4 (231.4) -> 223.9 (232.1) MB, 719.3 / 0.2 ms  (average mu = 0.302, current mu = 0.382) allocation failure scavenge might not succeed
> 
> 
> <--- JS stacktrace --->
> 
> FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

**Comment by Julusian** [comment]
We don't support running companion on anything lower then the 4gb pi4.
This error is one of the reasons why. Quite simply, the 3b+ does not have enough memory to build the webui.
It might be possible to setup a swap file to make it work, but it may not help
