### ISSUE TITLE
Feature request: Cut/Copy/Paste for buttons

### ISSUE THREAD

**Issue by SSormunen** [bitfocus/companion#182]
**Describe the feature**
Normal cut/copy/paste for buttons and their configs. So you can easily
rearrange and move buttons in same or between other pages

**Is this platform dependent (windows, mac, ..)?**
No, same for all platforms

**Usecases**
Constantly needing this feature. Pain to re-arrange or update buttons on pages without this.

**Comment by MartijnKraats** [comment]
+1

**Comment by SondreMoan** [comment]
+1

**Comment by willosof** [comment]
Made support for this in the UI now, @haakonnessjoen will do the rest in the backend when he's had enough sun and fresh air.

**Comment by willosof** [comment]
This is more or less a duplicate of the large #150 which also is in progress.. :)

**Comment by haakonnessjoen** [comment]
Fixed in f6aeb2ad2
