### ISSUE TITLE
[BUG] Linux: Stream deck not showing up on re scan / at all. 

### ISSUE THREAD

**Issue by crazy-logic** [bitfocus/companion#1824]
**Describe the bug**
Companion (2.1.3) on Ubuntu Linux (Ubuntu 20.10) doesn't see Stream Deck.

**To Reproduce**
run ./companion as either user or using sudo 
launch the GUI in a web browser, 
in surfaces - click re scan - no device shows up. re plug of device and try again makes no change, nore does another port on a different root hub.  

log shows errors;
17. 22:32:15 module(openweather-rest): Error loading module: Error: Cannot find module 'detect-libc'
17. 22:32:14 module(haivision-connectdvr): Error loading module: Error: Cannot find module 'detect-libc'

**Expected behaviour**
hit re-scan and device shows up. 

**Desktop (please complete the following information):**

- Ubuntu 20.10
- Chromium Version 90.0.4430.212
- Companion Version 2.1.3

**Comment by spruce** [comment]
Do you have a newer version of the streamdeck mk2? I ran into the same problem. The problem is that V2.1.3 doesn't know about the newish productId of the new SD mk2

**Comment by Julusian** [comment]
The 2.1 builds for linux are a bit broken, and arent easily fixable. (https://github.com/bitfocus/companion/issues/1279 https://github.com/bitfocus/companion/issues/1767)
But the 2.2 betas should work fine.

But also, 2.1.3 does not support the mk2. Or it could be that udev rules need setting up?

**Comment by crazy-logic** [comment]
just tried again with my 1st gen 15 button, and get the same issue - will look into 2.2 beta now :)

**Comment by crazy-logic** [comment]
so with 2.2

starting with "./companion" i get log errors within the app UI saying it can see the device but not access. 
with "sudo ./companion" i get an error (see below)
but "sudo ./companion --no-sandbox works" ok 

"[43223:0109/183818.160553:FATAL:electron_main_delegate.cc(252)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Trace/breakpoint trap"

**Comment by Julusian** [comment]
as 2.2 works with sudo, it sounds like you havent setup the udev rules. meaning non-root applications arent allowed to access the usb devices.
Follow step 4 and 5 of https://github.com/bitfocus/companion/wiki/Manual-Install-on-Raspberry-Pi#installing-companion

**Comment by Julusian** [comment]
I am 99% sure this is an issue with udev rules not being setup correctly.
I am happy to reopen this if someone can say otherwise

**Comment by toke** [comment]
Maybe try to add the user companion to group plugdev

`usermod -a -G plugdev companion`
