### ISSUE TITLE
Stream Deck Mobile app

### ISSUE THREAD

**Issue by llamafilm** [bitfocus/companion#1826]
**Describe the feature**
It would be great to show connected Stream Deck mobile devices in the surfaces list (iOS apps)

**Usecases**
The native Stream Deck iOS app easier to use than buttons on a webpage.

**Comment by Julusian** [comment]
It should be possible to do this today through the plugin for the elgato streamdeck software.

I don't think it is worth us trying to use the app directly, it would be better to spend the time making the tablet/mobile webpages better, or perhaps even making our own app.

To do it directly will mean that someone will have to reverse engineer the protocol the app uses, and re-implement the 'server' side of it. And then we will have to hope that whenever elgato update the app that it doesnt break the integration with companion.

**Comment by llamafilm** [comment]
Okay this makes sense, I didn't realize it would require such a big effort.
Which Stream Deck plugin are you talking about, is this something that exists today?

**Comment by llamafilm** [comment]
By the way, one of the features I miss in the current tablet/mobile view is an action to jump to a different page as in #1499.

**Comment by DanTappan** [comment]
Apparently the latest version of the Stream Deck Mobile app for IOS (2.3.1 - Jul 30, 2024) supports USB connectivity. Does this change the calculation for the cost of adding native support? 

It looks to me like the Elgato Companion plugin only works on Mac or Windows. It would be nice to be able to use an iPhone/iPad as a surface with the Raspberry Pi Companion.
