### ISSUE TITLE
How to join the Slack chat?

### ISSUE THREAD

**Issue by hrueger** [bitfocus/companion#1832]
This is not really a companion bug, however, there was no other issue template available.

I would like to create a module for companion myself (I'd say that I'm pretty familiar with JavaScript) and therefore I'd need a module repository. So I read through the https://github.com/bitfocus/companion/wiki/Module-Development Wiki Page and it says that one should click the slack invide link. However, Slack refuses my Gmail Account because it does not end with `@bitfocus.io`. Is that only supposed to work for bitfocus employees?

![grafik](https://user-images.githubusercontent.com/18656830/147384850-28682677-f3f6-4ff2-89ca-581090c699ac.png)

Should I just create an issue in the https://github.com/bitfocus/companion-module-requests repository?

**Comment by Julusian** [comment]
It looks like the invite link has broken, Ill update the docs to a new link https://join.slack.com/t/bitfocusio/shared_invite/zt-o1i0mohx-p_m5I7fUEUJ1BBu_KrDN2Q

**Comment by hrueger** [comment]
That one works, thanks 👍

**Comment by Julusian** [comment]
all the links I can find are updated. thanks for reporting

**Comment by pjaspinski** [comment]
It looks like it happened again. Could you refresh these links once again?
