### ISSUE TITLE
BDM ATEM module issue on 3681 built

### ISSUE THREAD

**Issue by champagj** [bitfocus/companion#1838]
It appears the BDM ATEM module is having issues on 3681 built running on Pi

Clean install of built 3681 on RaspberryPi using manual method.
Full restore of config via previous export of .companionconfig file. (+reboot)
Instance of BMD ATEM not connecting

21.12.29 02:21:30 instance(ext-atem): Error initalizing module: Cannot read property 'options' of undefined

**To Reproduce**
Clean install of Raspi-OS-lite
Manual install of Companion using Manual method
Add BMD ATEM module and configure.
No connection / error in instance tab
Log:
21.12.29 02:32:44 instance(atem): Error updating instance configuration: Cannot read property 'options' of undefined

Using Rpi4B - 4GB running latest Rasberry Pi OS-lite
Configuration via Chrome on WIN10

I have been running various versions of Companion on PI for a while with multiple instances such as ATEM, OBS, VLC, VICREO with very little issues.

config file attached.

[playoutbee_full-config_20211229-0046.zip](https://github.com/bitfocus/companion/files/7787776/playoutbee_full-config_20211229-0046.zip)

A big thanks to all the dev and support people behind companion.

**Comment by Julusian** [comment]
Thanks, fixed in 3682
