### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by harrovandoorn** [bitfocus/companion#1840]
**Describe the bug**
When using the http Generic connection in my Companion I am able to fire a GET command to my internal Home Domotica system and this way starting/ stopping some things like lights, blinds etc.

Now I also want to be able to retrieve data from my domotica system, to display on the Companion buttons. In example when i use a URl in the browser, it will give me a answer of "Status is Green". Or " Light is on" . I then want to be able to save this response, in a COmpanion Variable to use later on.

When using the GET command on a button, I can not find a way to save the response to a Variable. How would I go about that ?

**Comment by harrovandoorn** [comment]
Have re-opend this issue on the Module Page of the HTTP Generic. This seems more logical.

**Comment by abebeos** [comment]
see: https://github.com/bitfocus/companion-module-generic-http/issues/23
