### ISSUE TITLE
Button "goto page xyz"

### ISSUE THREAD

**Issue by JJFlash78** [bitfocus/companion#1841]
I use companion to control several PTZ cameras during live productions. I have created a separate companion page for each camera, currently 12 pages. It takes a long time to get to the desired page using the standard "page up" and "page down" buttons.

I would therefore like to create buttons (on Page 1) with which I can call up other pages directly. How does it work? I've tried a lot and researched for a long time. I can't find a solution. That's why I'm making a feature request.

_Summary: I'm looking for the a possibility to call up a companion-page directly with a companion-button: "goto page xyz"_

I would be very happy if someone would like to help me.

**Comment by Julusian** [comment]
You are looking for this action:
![image](https://user-images.githubusercontent.com/1327476/148139987-89016b6c-bcd9-4b95-bd97-32d6792c518c.png)

**Comment by JJFlash78** [comment]
Thank you Julian! Just what I was looking for!

I had already tested "set surface to page", but rejected it because it didn't work with the mobile buttons. After your message, I tried the emulator. The Buttens work great there!

_Can I do something to use "set surface to page" with the mobil buttons?_

**Comment by Julusian** [comment]
No, it doesnt currently work with the mobile buttons pages, that is a freature already requested https://github.com/bitfocus/companion/issues/1071
