### ISSUE TITLE
[BUG] Offset does not save

### ISSUE THREAD

**Issue by istnv** [bitfocus/companion#1853]
**Describe the bug**
The optional offset feature for Streamdecks smaller than XL ( #1781 ) does not save.  

**To Reproduce**
Shift the starting button using the options.
Exit/Restart companion.
Offset is back to upper left.

**Expected behavior**
Offset stays at the selected button.

**Comment by thereisnoh** [comment]
The offset option doesn't even appear for me, has it been removed?

**Comment by Julusian** [comment]
@thereisnoh are you on a recent build of 2.2?

@istnv I dont see why this wouldnt be saving, its using the exact same way of saving as the other properties..

**Comment by Julusian** [comment]
@istnv I think I found the issue. It would be reset if the yOffset was set...
Fixed in b177f8fb8a2847658c1eceb848aa01d0b358bb6a

**Comment by istnv** [comment]
> @istnv I think I found the issue. It would be reset if the yOffset was set... Fixed in [b177f8f](https://github.com/bitfocus/companion/commit/b177f8fb8a2847658c1eceb848aa01d0b358bb6a)

That would do it. I shift my Mini X + 1 and Y + 2
