### ISSUE TITLE
Yellow label - remove

### ISSUE THREAD

**Issue by maoskip** [bitfocus/companion#1854]
It's possible to remove the top bar on heach button? May be yes...but on Companion vers. 2.1.4 isn't possible.
The get started infos on : https://github.com/bitfocus/companion/blob/master/documentation/gettingstarted.md#surface-settings
say yes...
Thanks in advance

- OS: Windows 10 pro on notebook HP ZBook pro 15"
- Browser all
- Companion Version 2.1.4

**Comment by Julusian** [comment]
This feature is available in the 2.2 beta builds
