### ISSUE TITLE
Ability to use custom variables to open specific pages on on a specific surface

### ISSUE THREAD

**Issue by jsnyder886** [bitfocus/companion#1855]
**Describe the feature**
Ability to use custom variables to open specific pages on on a specific surface

**Usecases**
I would like the ability to make a button open a specific page on the surface based on a stored value in a custom variable.  Specifically, I have four pages of "presets," one for each of the four cameras in use in our main sanctuary.  I have a two-surface setup, with the primary buttons intended to be mostly static, save the feedbacks that are updated as necessary.  The secondary surface is where all of the page switching happens.  In addition to the 4 video pages, I have pages for audio controls, other automation controls, etc.  Those are easy to deal with because I only have one page to map to one button on the primary surface.  Having the ability to choose a page based on a stored value allows me the opportunity to store the last used video preset page (of the 4 currently in use), and use only 1 button on my primary surface to recall the last used video preset page instead of using 4 buttons on my primary surface in a 1:1 mapping.

I can not use the internal set surface page action because the surface and page items are drop down lists with no option to choose a variable.   I tried using custom OSC, which incidentally did come the closest to working.  I can get it to push a button on a page; that will get me started in the right direction, but only if I type in a number.  It will not parse the custom variable.

I see a few paths forward off the top of my head:

1)  Include the custom variables in the list of button choices on the internal set surface to page action.   Doesn't seem like a great option as it opens a Pandora's box on error handling.
2)  Include a check box on the internal set surface page action that would activate a text box that would allow the custom variable to be entered and parsed.  Along with that I would imagine the easiest way to handle errors would be to add a second drop down box that lists the different pages titled "On processing error, go to page:" or something to that effect.
3)  Update the generic OSC module to allow parsing of custom variables in the OSC path field

If I've missed something I'm very open to other ways to reach my goal.  I just haven't seen a way forward yet on this.  My goal is just to save real estate on my primary surface and reduce clutter.

**Comment by josephdadams** [comment]
I would say just code a new action, "set surface to page using custom variable", and just have textinput fields for the surface serial number and the page number that support parsing variables. Then whenever the action runs just verify that the parsed variable for the surface is one of the valid surfaces, and that the page number is a valid page choice. If invalid, it just doesn't do anything.

**Comment by thumperdisney** [comment]
+1 on this please. I would also add that this should also be available to specific buttons on a page so we could press a specific button on a page with the button chosen via a variable rather than just the page.

**Comment by Julusian** [comment]
Transferred to https://github.com/bitfocus/companion-module-bitfocus-companion/issues/47

**Comment by unclewes23** [comment]
This would be a great addition - ie goto page 3  which might be effects page - i am stream deck controlling vMix
