### ISSUE TITLE
NovaPro UHD Jr

### ISSUE THREAD

**Issue by marklneumann** [bitfocus/companion#1868]
Has anyone had any success building a profile for use with the NovaPro UHD Jr processor?  I see a module for the NovaPro HD Jr, and while internally you can select UHD Jr, this does not seem to work.  I am wondering if there are different commands at work between the HD and UHD boxes.   I am looking to trigger presets, screen brightness, etc.

**Comment by Julusian** [comment]
It would be better to ask this question on either the facebook group or slack where there are more users and not just devs floating around
