### ISSUE TITLE
[BUG] Can't add a function to a button

### ISSUE THREAD

**Issue by MarronProd** [bitfocus/companion#1870]
Hi everyonee,

Using companion version 2.1.4.
On Windows 10 (64bits)

I can add several instances. But when I try to add a key nothing happened. The instance and the function appears into the scrolling menu, I select it, but nothing happen. Even the internal function are not running.

Do you know where it can come from?

- OS: Windows 10 (64bits)
- Browser Chrome
- Companion Version 2.1.4

**Comment by Julusian** [comment]
This can happen in 2.1 if a module pushes an update to its list of actions while the dropdown is open
It is fixed in the 2.2 betas, but there are no plans to fix this in 2.1
