### ISSUE TITLE
companion-update breaks install

### ISSUE THREAD

**Issue by blakekrone** [bitfocus/companion#1875]
**Describe the bug**
When running companion-update all steps are successfully completed but upon reboot web service is inaccessible and buttons do not work.

**To Reproduce**
1. Download latest companionpi-2021-07-25.shrunk.img
2. Copy to thumb drive. 
3. Let RPi boot and verify 2.2.0-1e65f702-3485 is active version
4. SSH in and run `sudo companion-update`
5. Reboot, web server will be offline
6. SSH in, `ps -aux | grep companion` will show `/usr/local/bin/node /usr/local/src/companion/headless_ip.js 0.0.0.0` but no `/usr/local/bin/node /usr/local/src/companion/lib/usb/handler.js`

**Expected behavior**
Running `sudo companion-update` should update to the latest github version and be accessible via the web and streamdeck

**Desktop (please complete the following information):**

- OS: raspbian / macOS
- Safari / Edge / Chrome
- 2.2.0-1e65f702-3485 -> latest

**Comment by krocheck** [comment]
@jarodwsams any thoughts here?

**Comment by blakekrone** [comment]
![Screen Shot 2022-01-20 at 7 54 53 PM](https://user-images.githubusercontent.com/5911342/150453541-d2e140e9-566c-4053-ae95-9ac1596ec8b2.png)

Meant to attach this as well. I just clipped the git checkout but it runs.

**Comment by blakekrone** [comment]
`Jan 21 02:54:40 COMPANIONPI01 node[18407]: Starting
Jan 21 02:54:47 COMPANIONPI01 node[18407]: Started
Jan 21 02:54:50 COMPANIONPI01 node[18407]: /usr/local/src/companion/node_modules/companion-module-bmd-hyperdeck/index.js:1038
Jan 21 02:54:50 COMPANIONPI01 node[18407]: #011#011if (this.model !== undeinfed) {
Jan 21 02:54:50 COMPANIONPI01 node[18407]: #011#011                   ^
Jan 21 02:54:50 COMPANIONPI01 node[18407]: ReferenceError: undeinfed is not defined
Jan 21 02:54:50 COMPANIONPI01 node[18407]:     at instance.setupChoices (/usr/local/src/companion/node_modules/companion-module-bmd-hyperdeck/index.js:1038:22)
Jan 21 02:54:50 COMPANIONPI01 node[18407]:     at instance.actions (/usr/local/src/companion/node_modules/companion-module-bmd-hyperdeck/index.js:247:8)
Jan 21 02:54:50 COMPANIONPI01 node[18407]:     at new instance (/usr/local/src/companion/node_modules/companion-module-bmd-hyperdeck/index.js:232:8)
Jan 21 02:54:50 COMPANIONPI01 node[18407]:     at EventEmitter.<anonymous> (/usr/local/src/companion/lib/instance.js:232:23)
Jan 21 02:54:50 COMPANIONPI01 node[18407]:     at EventEmitter.emit (events.js:400:28)
Jan 21 02:54:50 COMPANIONPI01 node[18407]:     at Timeout._onTimeout (/usr/local/src/companion/lib/instance.js:293:11)
Jan 21 02:54:50 COMPANIONPI01 node[18407]:     at listOnTimeout (internal/timers.js:557:17)
Jan 21 02:54:50 COMPANIONPI01 node[18407]:     at processTimers (internal/timers.js:500:7)
Jan 21 02:54:50 COMPANIONPI01 systemd[1]: companion.service: Main process exited, code=exited, status=1/FAILURE
Jan 21 02:54:50 COMPANIONPI01 systemd[1]: companion.service: Failed with result 'exit-code'.
Jan 21 02:54:50 COMPANIONPI01 systemd[1]: companion.service: Service RestartSec=100ms expired, scheduling restart.
Jan 21 02:54:50 COMPANIONPI01 systemd[1]: companion.service: Scheduled restart job, restart counter is at 12.
Jan 21 02:54:50 COMPANIONPI01 systemd[1]: Stopped Bitfocus Companion (v2.0).`

Looks like it might be something with the HyperDeck module. Will look into it some more yet.

**Comment by krocheck** [comment]
Crap.  that's me.  I'll fix

**Comment by krocheck** [comment]
Try a `companion-update` again and let me know.

**Comment by blakekrone** [comment]
@krocheck yup good to go now, thanks!

**Comment by jarodwsams** [comment]
Glad I could be of such profound assistance 🤣
