### ISSUE TITLE
Disguise Multi Transport LOCATION (OPTIONAL)

### ISSUE THREAD

**Issue by Honsbeek** [bitfocus/companion#188]
did a test on a disguise, 

with  disguise multi transport control.
the option 

Command & player is fine, 
disguise get the triggers

only the LOCATION don't work, 

the message that need to be sent is: 

{"request":13,"track_command":{"command":"play","track":"bg","location":"00:00:15:00","player":"background player","transition":10}}

http://help.disguise.one/Content/Configuring/Transports/Multi-Transports.html

**Comment by willosof** [comment]
Will inspectigate!

**Comment by willosof** [comment]
This issue was moved to bitfocus/companion-module-disguise-mtc#1
