### ISSUE TITLE
[BUG] bootloop after adding trigger internal: Rescan USB for devices

### ISSUE THREAD

**Issue by walek75** [bitfocus/companion#1881]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After adding trigger by event: internal: Rescan USB for devices GUI stops work (continuosly refresh page, somethings like bootloop).
error Log:
node[1383]: Started
node[1383]: /home/pi/companion/lib/action.js:510
node[1383]:                                                 self.system.emit('log', 'instance(' + instance.label + ')', 'warn', 'Error executing action: ' + e.message)
node[1383]:                                                                                                ^
node[1383]: TypeError: Cannot read property 'label' of undefined
node[1383]:     at /home/pi/companion/lib/action.js:510:54
node[1383]:     at EventEmitter.<anonymous> (/home/pi/companion/lib/instance.js:75:3)
node[1383]:     at EventEmitter.emit (events.js:400:28)
node[1383]:     at EventEmitter.<anonymous> (/home/pi/companion/lib/action.js:480:16)
node[1383]:     at EventEmitter.emit (events.js:400:28)
node[1383]:     at EventEmitter.<anonymous> (/home/pi/companion/lib/action.js:458:19)
node[1383]:     at EventEmitter.emit (events.js:400:28)
node[1383]:     at scheduler.action (/home/pi/companion/lib/schedule.js:324:16)
node[1383]:     at Timeout._onTimeout (/home/pi/companion/lib/schedule/interval.js:20:20)
node[1383]:     at listOnTimeout (internal/timers.js:557:17)
systemd[1]: companion.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: companion.service: Failed with result 'exit-code'.

### Steps To Reproduce

1. add new trigger
2. enter some name
3. chose type as Time interval 
4. enter 5s interval
5. chose internal: Rescan USB for devices as action
6. save
7. errors appear after restart companion service

### Expected Behavior

rescan USB ports

### Environment (please complete the following information)

```markdown
- OS: Raspbian GNU/Linux 11 (bullseye)
- Browser: any supported (checked on Google Chrome, Mozilla Firefox, Micorsoft Edge)
- Companion Version: v2.0.0
```

**Comment by Julusian** [comment]
Please try updating companion, I have pushed a change that should fix this for you
