### ISSUE TITLE
PTZ  Controller CANON CR-N300

### ISSUE THREAD

**Issue by loptor** [bitfocus/companion#1886]
### Is this a feature relevant to comapnion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Hello,
It is possible to control the new PTZ camera CANON CR-N300 and CR-N500?
I know this camera can be controlled with Sony Visca with RM-IP10, but I don't know if with the Companion and SONY IP VISCA protocol it will be possible control it.

Thanks!

**Comment by davidjoshuaford** [comment]
There is a Canon PTZ module in the latest betas that controls the N300 and N500.

**Comment by loptor** [comment]
> There is a Canon PTZ module in the latest betas that controls the N300 and N500.

Can you tell me  what module or it is now avaliable for everyone ?
Thanks!

**Comment by josephdadams** [comment]
It’s in the beta builds and it’s called Canon PTZ.
