### ISSUE TITLE
[BUG] Emulator: Clicking outside gui unlatch latest used button

### ISSUE THREAD

**Issue by no-connections** [bitfocus/companion#1887]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In Emulator when you latch a button and then click anywhere outside on the page it unlatches the button.
If you press another button (unassigned or not) is does not unlatch.

The unlatch does not show up in debug log.

### Steps To Reproduce

1. Make a button with latch/toggle setting.
2. In web emulator click the button once to latch it.
3. Click anywhere else on the webpage (like white part or border) outside of buttons.
4. The button will be unlatched if it is the latest pressed button.

### Expected Behavior

The button should stay latched when clicking anywhere outside the button.

### Environment (please complete the following information)

```markdown
- OS: Windows 10
- Browser: Firefox, Opera, Chrome, Brave (phone and PC)
- Companion Version: 2.2.0+38380adeee85
```

### Additional context

Every browser/computer/phone I tested shows the same behavior.

**Comment by Julusian** [comment]
Fixed
