### ISSUE TITLE
[BUG] Documentation for module authors does not give them a working module

### ISSUE THREAD

**Issue by BryanCrotaz** [bitfocus/companion#1888]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Following the documentation for module authors does not result in a working module.

Some issues here, but a core dev that knows what they're doing should follow the docs to the letter and notice when they're incorrect or out of date.

1. Docs say that cmake is optional if you only want to develop modules. On macOS it is not. If you follow the instructions without installing cmake the initial build fails with cryptic errors such as `cannot find executable` during module builds. Also the cmake dmg download does not work for this - it must be installed via brew to actually work. 
2. Documentation doesn't state the fields that are required in a module's package.json
3. Documentation doesn't mention how to run companion with your brand new module installed
4. Documentation doesn't mention the difference between `yarn dev` and `yarn dev-headless`. The latter watches the file system for changes
5. Documentation doesn't mention where to put test scripts so that the run as part of the continuous integration of companion itself
6. Documentation doesn't mention where to find typescript types or how to script a build such that (for example) tsc is run during the companion build cycle

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by Julusian** [comment]
1) You definitely do not need cmake. the `cannot find executable` error is unrelated to that, but I cannot explain why you are getting that error.
2) I would guess that the example package.json files show what the required fields are https://github.com/bitfocus/companion/wiki/package.json. It probably should be more explicit
3) It says where to put the code for it https://github.com/bitfocus/companion/wiki/Module-Development#creating-a-new-module, but not how to then run companion
4) Yeah, I dont see that from a skim
5) For test scripts, you cant. Unit tests in modules are really rare, and the one that I know has some runs them in its own ci
6) Using an existing typescript module as a basis is easiest here, as it isnt really documented. Perhaps use https://github.com/bitfocus/companion-module-homeassistant-server as a basis? 

Ill see what I can do to get this documented better

**Comment by BryanCrotaz** [comment]
I've managed to do it but it's taken me well over two days just to get to a hello world module with tests. 

I've found bits of documentation dotted about the should be consolidated into the step by step "writing your first module" docs. 

I've forked the module template and I'll be submitting a hello world PR.

**Comment by dnmeid** [comment]
I resetted my dev environment and ran into that cmake thing too. Seems you need cmake to build some modules and on macOS it has to be a specific version of cmake.

**Comment by Julusian** [comment]
With the module and workflow changes for 3.0, the documentation has been written, so hopefully covers this sufficiently https://github.com/bitfocus/companion-module-base/wiki
