### ISSUE TITLE
Request for SAVE FILE / LOAD FILE / RESET ALL BUTTON or FACTORY DEFAULT .

### ISSUE THREAD

**Issue by clementcle85** [bitfocus/companion#189]
**Describe the feature**
A clear and concise description of what the feature does

**Is this platform dependent (windows, mac, ..)?**
Explain

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by dnmeid** [comment]
This is covered in #150 and already a milestone for v1.1.2

**Comment by clementcle85** [comment]
okey
