### ISSUE TITLE
Companion Button active but Text/Backgroud not showing on Streamdeck

### ISSUE THREAD

**Issue by atscomms** [bitfocus/companion#1892]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

These used to work just fine. I started noticed it a few builds ago. It occurs over several but not all Companion modules

Companion buttons on Streamdeck show the disconnected plug&socket with asterisk icon, but pressing a button actually works.
Streamdeck button edit says it's not connected to local Companion
Log shows "instance(websocket): WebSocket error: Error: connect ECONNREFUSED 127.0.0.1:4444"
Generic Websocket connection status show OK. (OBS controls work)

I've tried quitting and restarting both in every order. I've rebooted the PC

### Steps To Reproduce

Boot Streamdeck
Boot Companion

### Expected Behavior

Button appearance as shown in Companion GUI should show on Streamdeck buttons
Streamdeck should connect to Companion

### Environment (please complete the following information)

```markdown
- OS: Windows 10
- Browser: Firefox
- Companion Version:2.2.0+3850-master-1e4e447d-win64.exe
= Streamdeck V 5.2.0.14948 FW 1.00.012
```

**Comment by Julusian** [comment]
Quit (or uninstall) the streamdeck software, then restart companion.

Because you have both running, and the plugin disabled in companion, they are both trying to use the streamdeck.

**Comment by atscomms** [comment]
I need to have both running. It used to work until the last two Companion updates I used.
Companion buttons are added using the Custom/Companion Button module in the SD software

**Comment by krocheck** [comment]
That being the case, make sure the below setting is enabled and restart both Companion and Stream Deck
![image](https://user-images.githubusercontent.com/749812/152444793-ba1fe0dc-5f7a-4236-a7a7-f6bf1f84df4d.png)

**Comment by atscomms** [comment]
That did the trick.
Thanks
