### ISSUE TITLE
add a way to programmatically enable/disable a trigger

### ISSUE THREAD

**Issue by mark-epstein** [bitfocus/companion#1894]
### Is this a feature relevant to comapnion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I'd like to be able to enable or disable a trigger via a variable or button action

Background: People sometimes leave the DMX-controlled spotlights on at my church. That wastes energy so I have an automated system that just tells them to turn off every few hours on each day, Monday through Saturday. This works great!

Except that sometimes the church has an ad-hoc event like a mid-week funeral. The pastor comes in and turns on some lights, not knowing that my 3-hour timer is going to trigger in 20 minutes.

Yes I can disable the trigger via the web page or teach others to do so, but I need a solution for occasions that a trained operator is not there.  Having a user latch on a button on the stream deck is much more scalable.

### Usecases

Any instance where you don't want an automated trigger to actuate

**Comment by Julusian** [comment]
> Having a user latch on a button on the stream deck is much more scalable.

Will that solve the problem of the lights being left on though? It sounds to me that if they will forget to turns the lights off, they will forget to unlatch the button when they are done, negating the purpose of the timer.

This isnt a solution to your problem, just a thought I had while reading it

**Comment by mark-epstein** [comment]
I agree, but a button can already time out, so if someone turns on the
override switch the program can turn it back off 6 hours later.

**Comment by josephdadams** [comment]
implemented in: https://github.com/bitfocus/companion-module-bitfocus-companion/commit/50bd9367158c2d695a91cc141a4c5334a56c8319
