### ISSUE TITLE
[BUG]Jave Script Error in Main Process

### ISSUE THREAD

**Issue by LightWorx-Denver** [bitfocus/companion#1896]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Running v2.1.4 (2.1.4-b03d4f0f-2714) on Windows 10 v21H2. At launch of Companion I get a pop up stating the following,
"A JavaScript error occurred in the main process. 
Uncaught Exception:
Syntax Error: Unexpected token"

The GUI page cannot find USB surfaces, nor does it correctly start the emulator. Instances cannot be added from Category, Manufacturer or search functions. 

### Steps To Reproduce

1. Uninstall Companion
2. Download latest release
3. Install
4. run as administrator
5. see JavaScript error above

### Expected Behavior

Companion to launch and run as normal. Be able to add instances and connect to USB surface.

### Environment (please complete the following information)

```markdown
- OS: Windows 10 v21H2
- Browser: Edge Version 97.0.1072.76 (Official build) (64-bit)
- Companion Version: 2.1.4 (2.1.4-b03d4f0f-2714)
```

**Comment by Julusian** [comment]
This is caused by a corrupt db. Either manually delete it from `%APPDATA%/companion`, or try a 2.2 build as they have better handling to recover from a backup

**Comment by LightWorx-Denver** [comment]
Thank you for the information. Where can I download a 2.2 or 2.3 build?

*Sean Campbell*
*LightWorx Production Design*
719.339.5079 | ***@***.*** | www.lightworxtech.com

**Comment by kraves-oz** [comment]
Hi Sean

On the download page look for "beta builds" just under the download button. The most recent build ins the top of the list and usually the best to start with. 

Kyle.
