### ISSUE TITLE
Request: Mitti command "playSelectedCue" and Jump to cue

### ISSUE THREAD

**Issue by dnny** [bitfocus/companion#19]
The following commands for Mitti.
/mitti/playSelectedCue

And the jump to specific cue where number 1 is the cue number, maybe some input for the cue number as the drop-down menu might get messy if there are multiple jumps.

/mitti/1/jump
Jumps to the beginning of the Cue.

**Comment by PerRoine** [comment]
There will be a possibility in a future version to ad arguments to actions. it's the only sensibel solution to handle some functions i.e. 40*40 router will need 1600 actions if we don't make that (route: dest,source) so it's on the drawingboard

**Comment by Deanbau** [comment]
New commands added - not really documented yet
/mitti/rewind
/mitti/locate
/mitti/{cuenumber}/select
/mitti/jumpToCueWithName

**Comment by PerRoine** [comment]
added the following for ver 0.0.3

/mitti/1/jump
/mitti/playSelectedCue
/mitti/rewind
/mitti/locate
/mitti/{cuenumber}/select
