### ISSUE TITLE
BUG: If you try to edit a disabled module, companion breaks

### ISSUE THREAD

**Issue by haakonnessjoen** [bitfocus/companion#190]
**Describe the bug**
 If you try to edit a disabled module, companion errors out.

**To Reproduce**
1. Disable a module by clicking disable
2. Click on edit
3. ..
4. profit

**Expected behavior**
Easiest fix would be to disable the edit functionality.

**Comment by willosof** [comment]
Temporary workaround in 0b2a7f2 making it not crash. removed the edit button when it's disabled

**Comment by willosof** [comment]
No one complains about the temporary fix. Closing this.
