### ISSUE TITLE
[BUG] Failed to load bank config

### ISSUE THREAD

**Issue by AHub88** [bitfocus/companion#1903]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I try to edit a button, the button config could not be load.
Error message: Failed to load bank config

### Steps To Reproduce

1. Open Web GUI
2. Click to Tab "Buttons"
3. Click on a Button

### Environment (please complete the following information)

```markdown
OS: Windows 10
Browser: Chrome 94
Companion Version: 2.2.0-b177f8fb-3722
```

**Comment by Julusian** [comment]
What are you running companion on?
There is a timeout on the loading of that, if it takes more than 5s then it will show that error.
It is possible that an error was thrown causing it to fail to load too

**Comment by AHub88** [comment]
On a Win 10 Professional, i7-10750 with 16GB RAM -> enough power.

**Comment by AHub88** [comment]
Now I've upgraded to 2.2.0+3897-8d65a0c6 and the problem resists.
The log is clean.

Here's a list of my connections.
![Connections](https://user-images.githubusercontent.com/99470230/153882454-d807cb09-f801-4791-85bb-1547895e1ae4.jpg)

**Comment by AHub88** [comment]
The problem seems to be with the Vmix connection.

These messages appear in the debug log:
Unknown activator message: ACTS ER Invalid Activator

If I disable the connections, everything works again.

**Comment by AHub88** [comment]
I have some new informations.
It works with 2.2.0+38380adeee85

Newer versions crash when vmix is enabled.

**Comment by Julusian** [comment]
Is this still a problem on the latest beta?
There have been a bunch of general performance fixes that I think might solve your issue here

**Comment by AHub88** [comment]
It seems to be solved :)
