### ISSUE TITLE
[BUG] Typo in settings page

### ISSUE THREAD

**Issue by tcconway** [bitfocus/companion#1906]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Typo

### Steps To Reproduce

1. Visit http://127.0.0.1:8888/settings
2. Notice line "Enable emulator control for **Logitec** **R400/Mastercue/**dSan**"** should be "Enable emulator control for **Logitech** R400/**MasterCue**/**Dsan**"

### Expected Behavior

Should be: Enable emulator control for Logitech R400/MasterCue/Dsan

### Environment (please complete the following information)

```markdown
- OS: MacOS Monterray 12.2
- Browser: Brave 1.35.101 (Latest)
- Companion Version: v2.2.0 (2.2.0+3879ef77e988)
```

**Comment by Julusian** [comment]
Thanks
