### ISSUE TITLE
Module Request: SmartScope Duo 4K

### ISSUE THREAD

**Issue by ryankayson** [bitfocus/companion#191]
**Describe the feature**
Would like to be able to control the SmartScope Duo 4K scope features.  Would like to be able to select what scope is on each monitor, or to be able to toggle through them. 

would like this to run on all versions of companion.

**Usecases**
Would like to be able to control our switching rack with the stream deck.  This include the monitors with scopes.  The only other way to change the settings on these monitors is to breakout a laptop.  We already use a stream deck with companion to control most things.  Adding this device would greatly speed up setting up.  The big plus is for our camera guy to switch back and forth between the setting with just a simple button push

**Comment by PerRoine** [comment]
Module is made and tested there is a bug that we need to track down regarding the Dropdown in the actions which act's strangely at times

**Comment by ryankayson** [comment]
HI.  Thank you for working on this Module.  I downloaded the latest beta version of companion, to see functionality of this module.  When the final 1.1.2 is released, will this have the function to change the type of scope per monitor?  Not just the brightness, contrast, saturation setting.

Thanks.  Really love using the software.

**Comment by PerRoine** [comment]
The smartScope functions should be there already if you select smartscope in instans config, you can try disabling and enabling the instance and see if the 3 extra actions turn up
