### ISSUE TITLE
[BUG] Raspberry Pi Touch screen double trigger on Page up/down buttons

### ISSUE THREAD

**Issue by ryangardner95** [bitfocus/companion#1912]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Changing pages using page navigation button on Raspberry pi touch screen results in a double trigger.
Companion will change the page as expected, but will then also trigger whatever button is sitting in that position on the next page.
This happens on the Raspberry Pi, but also on an iPhone using Safari. Current companion version is  2.2.0+3871, however this has been happening on every version we've tried. We are using the "tablet3" version of the buttons.

### Steps To Reproduce

https://user-images.githubusercontent.com/78697859/153837881-b6d6a336-ef8e-4c1c-a675-f5a57ca83a26.MOV

### Expected Behavior

Pages should change without triggering extra buttons on the next page.

### Environment (please complete the following information)

```markdown
- OS: Raspberry Pi OS
- Browser: Default
- Companion Version:2.2.0+387151f0d218
```

**Comment by Julusian** [comment]
fixed
