### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by thingyt** [bitfocus/companion#1919]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

on cl interface for Companion Pi and running companion-update and after pulling all new versions, yarn fails with error: 
error companion@2.2.0: The engine "node" is incompatible with this module. Expected version "^14.16". Got "12.22.1"
error Commands cannot run with an incompatible environment.

Tried updating node with no success. 

### Steps To Reproduce

1. ssh into companion pi
2. run companion-update
3. see error, get booted off ssh connection

### Expected Behavior

Expected Companion to be updated to the latest stable build.

### Environment (please complete the following information)

```markdown
- OS: Companion Pi
- Browser: Firefox
- Companion Version: current install 2.0.0 something trying to update to 2.2.0
```

**Comment by Julusian** [comment]
Between those two versions we updated the version of node, but there isnt anything we could easily automate in the scripting to avoid this issue.

The simplest option is probably to manually install the correct version, using some commands from  [`n`](https://www.npmjs.com/package/n) 

Or you could try updating your `companion-update` script to add a new 2nd line `export MANAGE_NODE_VERSION=1`, which should cause it to update node for you

Or you could  copy the database folder (I think at `/root/companion`) off the pi, install companionpi again from a fresh image, stop companion `sudo service companion stop`, copy your old db back into place and restart the pi
Or you could try getting [`n`](https://www.npmjs.com/package/n) 

I am hoping that we can make this smoother in the future, but it is hard to fix up any existing companion pi installations

**Comment by thingyt** [comment]
So I was able to use n 14.16 command to install the asked for version, only for it to fail later because one of the modules wanted 14.17. After installing that, I was able to get it to update fully.

If updating the version of node is a known deal breaker for using certain things, why not set it to make the check, then instead of erroring out, throw a question, "Do you want to update node to [version] now?" then run the n [version] command before continuing if they enter y or quitting with current error if they say no?

**Comment by thingyt** [comment]
Sounds good. 

Maybe in the meantime a comment about what version of node needs to be installed to run the latest update for those updating from older versions?
 
I couldn't find info on how to resolve it and was confused by it returning a '^' in front of the version number and was assuming it was mis-reporting the version number instead of just needing to ignore that (which is what I finally did).
