### ISSUE TITLE
Module Request: Irisdown Countdown Timer

### ISSUE THREAD

**Issue by DaveShep** [bitfocus/companion#192]
**Describe the feature**
The Irisdown Countdown Timer now supports network control. A Companion module would allow full remote control of the timer.

**Is this platform dependent (windows, mac, ..)?**
Windows

**If documentation is required to implement, do you know where to find it?**
http://www.irisdown.co.uk/countdowntimer.html
https://release.irisdown.co.uk/CountdownTimerSetup.msi
http://release.irisdown.co.uk/Countdown%20Timer%20v2%20-%20Remote%20Control%20Protocol.pdf

**Comment by PerRoine** [comment]
Module is made and tested, some bugs were found and is probably in the countdown timer,
TOGGLEPAUSE works as pause only it does not start or resume the timer,
DISPLAY CLOCK Changes the button state in the operator GUI but does not change the display TIMER,BLACK and TEST works fine

**Comment by PerRoine** [comment]
Bugs fixed and Module tested THX to DaveShep for quick response

**Comment by sledzik1984** [comment]
Anyone have 1.4.0 compiled for MacOS with **newest** version of Irisdown Countdown Timer module?

**Comment by JeffreyDavidsz** [comment]
Just download the latest stable 1.4 from the website
