### ISSUE TITLE
Builds from 3888 to 3910 do not work with my stream deck companion button. re installed 3673 and it works

### ISSUE THREAD

**Issue by mollertom** [bitfocus/companion#1920]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I had a vmix module issue and decided to try installing newer version of Companion to see if that would resolve it and any of the new versions make the companion buttons in the streamdeck software not connect as if companion is not installed. As soon as I go back and install 3673 at least the buttons connect. I tried installing the following versions... 3910,3888,3883,3878...  I rebooted between each install as well. I did not keep trying all of the versions below 3878 to find the last one that works.

there are no errors showing in the log
I am running windows 10 with the latest updates installed
I have connections to the following instances ; vMix, OBS, SQ, Visca PTZ optics, vicreo hotkey, reaper, OSC. 
![Companion Connections](https://user-images.githubusercontent.com/98034419/154360586-91f34d07-d226-4565-a87f-e9c34e3a9bd7.png)
![3910 and streamdeck](https://user-images.githubusercontent.com/98034419/154361331-c1eb1e72-f757-4bdb-a8b3-605a8fbef056.png)
![3673 and streamdeck](https://user-images.githubusercontent.com/98034419/154361351-61bacc3a-7441-4292-8642-5f60be1919da.png)

### Steps To Reproduce

install any of the latest versions listed above and the issue is the same.
install the older version and it all comes back up correctly.

I can try reinstalling newer versions with the same result every time and I just have to reinstall the older version for it to work.

### Expected Behavior

I expected the companion buttons to connect immediately after the new version was installed.

### Environment (please complete the following information)

```markdown
- OS:windows 10 latest updates installed
- Browser:Chrome
- Companion Version: 3910, 3888, 3883, 3878, 3673
```

### Additional context

The issue I had with the vMix module was that feedback for buttons would stop working and I would have to reboot to get the feedback working again. Likely not related to this issue
A couple of days ago, my companion config files were corrupted and I had to rebuild most of my buttons. That is working fine with the older version of Companion.
Are these two incidences related perhaps but that is way beyond my knowledge and understanding.

**Comment by Julusian** [comment]
Did you enable the config option in the settings tab to let the elgato plugin work? 
![image](https://user-images.githubusercontent.com/1327476/154363169-22a8a1b7-2656-4cd3-aced-216beb8065a9.png)

**Comment by mollertom** [comment]
Hi Julian

 

Thanks for the quick response. I just checked and I did have the option selected. I reinstalled one of the newer versions just to be sure, unchecked the box, restarted then rechecked it and restarted again. No effect.

 



 

Thanks Tom

**Comment by mollertom** [comment]
After double checking I checked the correct settings box and the issue is resolved.

I did not have to have that checked in build 3673 but happy to have it resolved.

Thank you

**Comment by Julusian** [comment]
The 'Use Elgato Plugin' setting was added fairly recently, and the build that worked for you was probably from just before it was added
