### ISSUE TITLE
[BUG] Cannot edit trigger?

### ISSUE THREAD

**Issue by mark-epstein** [bitfocus/companion#1923]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Once a trigger has been created, it cannot be modified; this seems to be true if the 

### Steps To Reproduce

1. "Add new trigger"
2. Set type to Feedback
3. Set variable, operation, and value to anything
I used an internal custom variable, several operators and values
4. Save

5. Click Edit on the newly saved trigger
6. try to change anything: variable, operation, or value; or add a new feedback. You will not be allowed.

Note: "clone" of an existing trigger does the same thing as steps 1-4

### Expected Behavior

edits should be allowed

### Environment (please complete the following information)

```markdown
- PC OS: Windows 11 (browser) 
- Pi OS: Raspbian GNU/Linux 10 (buster) (Companion)
- Browser: Edge Version 98.0.1108.43 (Official build) (64-bit)
- Companion Version: 2.2.0 (2.2.0+3919-7abeccb6)
```

**Comment by mark-epstein** [comment]
I did discover something of a workaround: if you change the trigger type you can then switch back to Feedback without losing any actions in the trigger

**Comment by Julusian** [comment]
Thanks for reporting, this is fixed now

**Comment by mark-epstein** [comment]
Thank you!

**Comment by MeestorX** [comment]
I just ran into this today. The fix is in today's build, @Julusian ?

**Comment by Julusian** [comment]
Yes the latest build or two will have this
