### ISSUE TITLE
Cannot edit triggers [BUG]

### ISSUE THREAD

**Issue by jsnyder886** [bitfocus/companion#1927]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Build 2.2.0 3925

When editing a time based trigger:

- It does not pull in the previously saved date & time that it was to run.
- Any actions added to the trigger do not actually save with the trigger.
- 

### Expected Behavior

Not that

### Environment (please complete the following information)

```markdown
- OS: Windows 11
- Browser: Chrome
- Companion Version: 2.2.0 3925
```

**Comment by ematson5897** [comment]
Also seeing this on 2.2.0-rc1+3931. Additionally, saving a time-based trigger after opening results in the time being listed as "undefined". Adding a new time-based trigger will always result in a time of "undefined"

**Comment by krocheck** [comment]
@Julusian [this](https://github.com/bitfocus/companion/commit/0eb49f3171bba674b3699ffed4277867cffc0f02#diff-da2a29a1370d7a0941b38f32f23209bd401f29b436900e6b7f2b47d948915522R213) is the culprit.  I might have to punt this to you because this flow is a tough read for me at the moment.

**Comment by Julusian** [comment]
I think Ive fixed it

**Comment by ematson5897** [comment]
FWIW, updating to 3946 after seeing this issue deleted all my time-based triggers, and upod adding one, I get the following error:

`"object null is not iterable (cannot read property Symbol(Symbol.iterator))"`


Updating to 3958 to see what happens
