### ISSUE TITLE
Module: Resolume Arena 6

### ISSUE THREAD

**Issue by monoxane** [bitfocus/companion#193]
**Describe the feature**
Controls Resolume Arena 6

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
OSC bindings are visible inside Resolume

**Usecases**
VJ and Media Server use for live shows

(I'm currently working on this, this issue is just here to show its being done)

**Comment by theslainman** [comment]
Is this not in development anymore sine the issue is closed?

**Comment by monoxane** [comment]
> Is this not in development anymore sine the issue is closed?

its complete and in companion, if you have an improvement open a new issue for it and ill take a look

**Comment by haakonnessjoen** [comment]
This module was not in companion yet. But I have now added it.
