### ISSUE TITLE
[BUG] OSC docu fail

### ISSUE THREAD

**Issue by Lackii** [bitfocus/companion#1939]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**Describe the bug**
Maybe there is a small mistake in the doc regarding the OSC protocol given under settings - OSC in the gui. The first command is correcly divided by slashes. But in the following commands there are more than necessary blanks, should they not also be divided by slashes like  /press/bank/\<page\>/\<bank\> <1> instead of /press/bank/ \<page\> \<bank\> <1> and so on?

### Steps To Reproduce

Go to GUI, Settings, OSC Tab

### Environment (please complete the following information)

```markdown
- OS: MacOS
- Browser: Firefox, Safari
- Companion Version: 2.2.0 RC-2
```

**Comment by Julusian** [comment]
You are right, there should be slashes between <page> and <bank>
This is fixed
