### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by thingyt** [bitfocus/companion#1941]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Elgato Stream Deck Plugin doesn't work with release candidate build or any 2.2 beta builds. 

I know it hasn't been rolled out fully quite yet, just finding I want to use some of the new features but still need to have a few Stream Deck buttons for local program control and I'm not able to use both with the newer builds. 

Guessing this is on someone's radar, but I don't see it listed. 

### Steps To Reproduce

Run Companion 
Run Egato Stream Deck Software. 
Load Companion plugin button on stream deck
Shows Connection failure and says to make sure you are using Companion 1.3 or above.

### Expected Behavior

Companion Plugin for Elgato Streamdeck software to work with 2.2 release candidate

### Environment (please complete the following information)

```markdown
- OS: MacOS x86
- Browser: Safari
- Companion Version: (2.2.0-rc2+3956-25a303b7)
- Elgato Stream Deck Version: 5.2.0 (14948)
```

**Comment by josephdadams** [comment]
I think with the new versions you do have to go into Companion settings and specifically enable the setting for the plugin to work. Did you check there?

**Comment by krocheck** [comment]
Yes, see below:
![image](https://user-images.githubusercontent.com/749812/155602838-a97e124e-8b65-4a79-8434-38bc311a58c0.png)

**Comment by thingyt** [comment]
Yep, that was it. Sorry I hadn't found. 

Thanks!
