### ISSUE TITLE
Ability to schedule one-time events

### ISSUE THREAD

**Issue by elliotmatson** [bitfocus/companion#1951]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I would love to be able to have the ability to schedule things to run only once. 

For GUI, I'm thinking maybe a calendar view that shows all repeating time-based triggers as well as one-off's would be the best way to view this? That would be a significant amount of work though.

### Usecases

We do a lot of one-off events that I can't always be around for, so it would be really useful to be able to schedule a video or multitrack recording of that event, loading presets, shutdown after event, etc.

**Comment by kenm-4682** [comment]
Hello! I'm seconding this request, and would love to see it happen for the exact same reason. 

Itneeds to be added as an option under an Event's Triggers -- a small calendar / clock option to set a specific date & time. Not currently possible from any of the options (that I can figure out, including any internal variables).


<img width="1446" alt="Screenshot 2023-12-17 at 11 44 23 AM" src="https://github.com/bitfocus/companion/assets/87292658/38b21025-d66c-4819-8c63-f89a72fc89fb">

**Comment by mikecreates86** [comment]
Adding my voice to this request. Some kind of calendar feature to schedule a singular run of a trigger at points beyond the week. Right now, I have to regularly remind myself to enable or disable certain triggers in order for them to run for an event.
