### ISSUE TITLE
[BUG]: Uncaught Exception: Unexpected Token

### ISSUE THREAD

**Issue by Stranabrade** [bitfocus/companion#1955]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Companion not opening in Windows - Java script error.

![39C7642F-0BAF-4A6D-AA4D-10F4A0EA28CA_1_102_o](https://user-images.githubusercontent.com/101351565/157713431-22ebf95b-c617-47cf-b07a-b47feb332eb9.jpeg)
![IMG_0638](https://user-images.githubusercontent.com/101351565/157713596-c314c3f6-80fe-4fec-bd7e-e42159d1562a.jpeg)

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by Julusian** [comment]
Have you tried deleting the db file?
