### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by serenamonts** [bitfocus/companion#1958]
Uncaught Exception: Error: send EHOSTDOWN
Bitfocus will not open in the browser window and this error keeps popping up (several times after I close the error window)

**Comment by Julusian** [comment]
What version of companion?
Does the error box say anything else?

This is most likely a bug in a module triggered by a device which is turned off

**Comment by serenamonts** [comment]
v2.1.4 (2.1.4-b03d4f0f-2714)
Error message also says:

(my IP Address) :9090
at Object-errnoException
(util.js 1046:20)
at SendWrap.afterSend [as oncomplete]
9dgram.js.498:1 1)

I have two streamdecks connected to bitfocus
I'm running zoomOSC and OBS through companion

**Comment by krocheck** [comment]
:9090 is ZoomOSC, so your old hosts are active on the network but not running ZoomOSC.  The module they developed has been reported as broken, but they have not fixed it yet as best as I've been told.

**Comment by Julusian** [comment]
Hopefully this is resolved under 2.2.0, if not please open an issue in the correct module repository if you can identify which module is having the error
