### ISSUE TITLE
[BUG] Internal feedback options reference "instance" rather than "connection"

### ISSUE THREAD

**Issue by chjaway** [bitfocus/companion#1962]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

TRIVIAL:
"Instances" are now known as "**Connections**", however button "FEEDBACK" options include "internal: Companion **Instance** Status".
The Feedback option _should_ read "internal: Companion Connection Status"

### Steps To Reproduce

1. Create a new "Regular Button"
2. Scroll down to the "Feedback" options.
3. Click "+Add feedback"
4. Observe first option is listed as "internal: Companion Instance Status".

### Expected Behavior

Feedback option should be listed as "internal: Companion Connection Status" to maintain new terminology of "Connections" rather than the former "instances".

### Environment (please complete the following information)

```markdown
- OS: macOS Big Sur (v11.6.4)
- Browser: Chrome Version 99.0.4844.51
- Companion Version: 2.2.0-rc2 (2.2.0-rc2+3956-25a303b7)
```

**Comment by Julusian** [comment]
I have updated everything I could find. This will be in the next beta build
