### ISSUE TITLE
Failed to load variable values list TimeoutError: Timed out after 5s

### ISSUE THREAD

**Issue by chron0** [bitfocus/companion#1963]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After upgrading to latest master, the WebUI hangs in "Syncing"

![oNsx](https://user-images.githubusercontent.com/3270028/158778193-6ef0b3d5-fd5e-40b2-b5af-aa341a09caff.png)

It seems to timeout here:

```
ContextData.jsx:51 Failed to load variable values list TimeoutError: Timed out after 5s
    at http://10.1.10.20:8000/static/js/2.35f1f362.chunk.js:2:862525
```

![oNsg](https://user-images.githubusercontent.com/3270028/158779015-90c02446-ce6d-4c36-85fd-d7a8e6129fa4.png)

Testing from 2 different clients and completely clearing any local browser cache did not make any difference.
Emulator Pages are shown correctly. The configuration set is pretty small, only including streamdeck, bmd-atem, Home-Assistant, http-api and VLC-api (in case it may me plugin related).

### Environment (please complete the following information)

```markdown
- OS: Linux
- Browser: Chromium (different versions and different test clients)
- Companion Version: 2.2.0 (2.2.0+3998-ccea40c7)
```

**Comment by Julusian** [comment]
how did you update? using `yarn update` or some other command?

This sounds like the webui wasnt rebuilt during the update, but that is one of the steps performed by `yarn update`
