### ISSUE TITLE
Custom Variable Set Custom Variable String Expression

### ISSUE THREAD

**Issue by jsnyder886** [bitfocus/companion#1966]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Build upon the existing "Set Custom Variable Expression" to include string expressions

### Usecases

This would provide the opportunity to build custom strings for any number of purposes.

**Comment by PhilVale** [comment]
I'd like to see something like "if <condition> then (True action) else (false action)

**Comment by MikeMoony** [comment]
I can not find any description of this function. where can i find documentations to the functions?

**Comment by Gartom** [comment]
@MikeMoony, check the section "Getting started" in the GUI:
![bild](https://user-images.githubusercontent.com/4034632/162587456-c452afd6-cd55-4173-9ce5-a7e074afcfd5.png)
