### ISSUE TITLE
[BUG] Unicode charcters ▶️`play` and ◀️`reverse` as lables are not rendered

### ISSUE THREAD

**Issue by VuiMuich** [bitfocus/companion#1967]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

1. create a new button
2. paste this as lable/button text: `▶️ play / ◀️ reverse`
3. the symbols get rendered in the text field but neither in the button preview, nor the button itself

### Expected Behavior

The 'triangle left' and 'triangle right' symbolising play and reverse in unicode should be rendered with the correct foreground color.

### Environment (please complete the following information)

```markdown
- OS: Win 10
- Browser: Edge, but should be irrelevant
- Companion Version: 2.2.0+3998-ccea40c7
```

### Additional context

My suspicion is that this fails as the 'pre-emoji' [description ](https://www.compart.com/en/unicode/U+25B6)of the unicode code point [▶ U+25B6](https://emojipedia.org/emoji/%E2%96%B6/) describes it as 'Black Right-Pointing Triangle', so this might be a weird combination of a font fallback combined with some weird character specific trait to 'enforce blackness' that makes this fail.

**Comment by VuiMuich** [comment]
After further investigation it looks like all [geometry](https://www.compart.com/en/unicode/block/U+25A0) unicode charcters in the range of ̀ U+25A0` to `U+25CF` seem to be affected, `U+25D0` renders fine though. 🤔

**Comment by Julusian** [comment]
I don't know how this file was originally generated, but the font is some slightly custom hardcoded font which is stored in this file https://github.com/bitfocus/companion/blob/master/lib/font.js.

If this is something you need please do submit a PR to include it there for all font sizes.

Alternatively it is likely that the next major version of companion (many months away) will be rewriting this rendering so it might start working then.

**Comment by istnv** [comment]
The fonts are prerendered for the buttons.
This page has a list of the characters available in companion.
The 7pt font is a subset of those.

**Comment by VuiMuich** [comment]
I guess `11208` should work as 'play'
