### ISSUE TITLE
rosstalk:Transition Keyer doesn't work

### ISSUE THREAD

**Issue by tvwonder** [bitfocus/companion#197]
**Describe the bug**
Trying to use the rosstalk:Transition Keyer function and it doesn't work. Assigning this feature to a button then pressing the button does nothing. I get a line in the log in Safari that shows a button was pressed but the switcher does not respond.

**To Reproduce**
1. Assign rosstalk:Transition Keyer to a button (doesn't matter which MLE or Keyer I select or whether Auto Transition is Yes or No)
2. Press assigned button (or Test actions in Safari)
3. None of the keyers transition on or off as expected

**Expected behavior**
I expect the keyer to turn on/off, with our without a transition, depending on how I set the button's parameters

**Screenshots**
![companion rosstalk](https://user-images.githubusercontent.com/13799658/43688296-a5dae0a2-98ab-11e8-98f9-1676e1a92d0c.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.12.6
 - Browser: Safari
 - Version: 11.1.2

**Comment by PerRoine** [comment]
We have found the 'Transition Keyer' bug will update it shortly

**Comment by tvwonder** [comment]
Awesome. Thanks!

Dave

**Comment by PerRoine** [comment]
Ok i Think the 'Transition Keyer' should work now, but i'm at home with no carbonite to test on so please test and give feedback watch for next master build at https://builds.bitfocus.io/companion/
but be aware that this is untested code and not suitable for production environments.

**Comment by tvwonder** [comment]
Great! I'll check it when I'm back in the office on Tuesday. Is there any
way to run this build without messing up the main build I already have
installed?

Dave

**Comment by willosof** [comment]
Just install the new build. :) should be fine. To be 100% sure, take a backup of the config files in Library/Application Support/companion :)

**Comment by tvwonder** [comment]
OK thanks! :)

**Comment by willosof** [comment]
This issue was moved to bitfocus/companion-module-rosstalk#1
