### ISSUE TITLE
fillImage attempt 1 failed: TypeError: Cannot write to hid device (not sure if this is a bug) 

### ISSUE THREAD

**Issue by mark-epstein** [bitfocus/companion#1971]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have two Stream Decks connected to Companion. They get used rarely outside of Sunday mornings, and this week they haven't been used at all since Sunday.

I noticed this in the debug log this morning, and am curious what it means:
```
22.03.25 04:26:29 device(CL05K1A01508): fillImage attempt 1 failed: TypeError: Cannot write to hid device
22.03.24 16:23:59 device(CL05K1A01508): fillImage attempt 1 failed: TypeError: Cannot write to hid device
22.03.23 14:11:18 device(CL05K1A01508): fillImage attempt 1 failed: TypeError: Cannot write to hid device
22.03.23 02:05:24 device(CL29J1A00120): fillImage attempt 1 failed: TypeError: Cannot write to hid device
22.03.23 01:26:18 device(CL05K1A01508): fillImage attempt 1 failed: TypeError: Cannot write to hid device
22.03.22 21:11:09 device(CL05K1A01508): fillImage attempt 1 failed: TypeError: Cannot write to hid device
22.03.22 20:25:23 device(CL29J1A00120): fillImage attempt 1 failed: TypeError: Cannot write to hid device
22.03.22 10:30:23 device(CL29J1A00120): fillImage attempt 1 failed: TypeError: Cannot write to hid device
22.03.21 20:23:35 device(CL05K1A01508): fillImage attempt 1 failed: TypeError: Cannot write to hid device
22.03.21 19:34:14 device(CL05K1A01508): fillImage attempt 1 failed: TypeError: Cannot write to hid device
22.03.21 19:34:14 device(CL29J1A00120): fillImage attempt 1 failed: TypeError: Cannot write to hid device
22.03.21 18:58:37 device(CL05K1A01508): fillImage attempt 1 failed: TypeError: Cannot write to hid device
22.03.21 03:20:09 device(CL29J1A00120): fillImage attempt 1 failed: TypeError: Cannot write to hid device
22.03.21 00:30:08 device(CL29J1A00120): fillImage attempt 1 failed: TypeError: Cannot write to hid device
22.03.20 23:50:56 device(CL05K1A01508): fillImage attempt 1 failed: TypeError: Cannot write to hid device
22.03.20 18:07:33 device(CL29J1A00120): fillImage attempt 1 failed: TypeError: Cannot write to hid device
22.03.20 13:03:11 device(CL05K1A01508): Button 9.18 released
22.03.20 13:03:10 device(CL05K1A01508): Button 9.18 pressed
22.03.20 11:56:51 device(CL29J1A00120): Button 5.1 pressed
22.03.20 11:54:09 device(CL29J1A00120): Button 5.6 released
22.03.20 11:54:09 device(CL29J1A00120): Button 5.6 pressed
```
Without anyone touching any buttons, the only thing that changes on the surfaces is a button which displays the time using this button text: `$(internal:time_hm)\n$(internal:time_s)`

I know I'm not on the latest version, but having been burned by a remote update once I now only update on my system at home and hand-carry a microSD card to install at the church. And I'm 1/2 a world away right now and can't do that.

### Steps To Reproduce

1. log into my Companion instance
2. look at the debug log
;-)

### Expected Behavior

I'd expect to not have these messages in the log. I don't know if they cause any bad behavior or indicate anything else is wrong because they happen randomly and infrequently.

### Environment (please complete the following information)

```markdown
- OS: Raspberry Pi
- Browser: Chrome 99.0.4844.84 (Official Build) (64-bit)
- Companion Version: 2.2.0 (2.2.0+3919-7abeccb6)
```

**Comment by Julusian** [comment]
As they are so infrequent they are safe to ignore.
What is happening is that transferring a newly render image to a button failed, which can happen when a lot are changed at one. Not really sure why it happens beyond that. So we try to transfer 3 times before declaring the device 'dead' and unloading it.
We should probably avoid logging this or make it not be an error, but there isnt anything more than that to do here

**Comment by Julusian** [comment]
I have changed this logging, so it will only be logged when it becomes an actual problem rather than expected behaviour
