### ISSUE TITLE
Stuck on "Syncing" graphic in GUI and companion won't start

### ISSUE THREAD

**Issue by dansherer8181** [bitfocus/companion#1974]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello, 

I installed Companion 2.2 (ARM) latest stable build on my MacBook Air M1. It worked! Then, I went on a VPN a few times and pushed the buttons remotely for fun. That also worked. Now when I open companion the red home page says "Starting... waiting for web server" until I choose a network interface or press "change" next to the port 8000 number. Once I select a network or press change then it says Running 127.0.0.1:8000 as usual. However, when I press launch GUI it ends up at the GUI home page with a progress bar that says "Syncing" and stops about 75% of the way through.

I am running a MacBook Air M1, 2020, 8GB ram, MacOS 12.3

<img width="1318" alt="Screen Shot 2022-03-27 at 2 52 44 PM" src="https://user-images.githubusercontent.com/58828632/160298307-27a97af2-fdb6-49f6-86c7-8ae793c4c8f2.png">

### Steps To Reproduce

1. Open Companion

2.change network interface or press "change" to get it to switch from "starting... waiting on web server" to "running"

3. Press GUI to launch webpage and all it shows is "syncing" progress bar stuck at about 75%

4.
  

### Expected Behavior

It ought to work! It did before, so I don't know if the update to 12.3 MacOS has stopped it or what.

### Environment (please complete the following information)

```markdown
- OS: MacOS 12.3
- Browser: Safari or Chrom
- Companion Version: v2.2.0
```

### Additional context

Not sure why this is happening!

**Comment by dansherer8181** [comment]
<img width="389" alt="Screen Shot 2022-03-28 at 10 01 56 AM" src="https://user-images.githubusercontent.com/58828632/160427702-533c2f06-b6e6-4f65-a147-5e2aff55a8c3.png">

Here's a screenshot from when I start up companion. What could cause it to "wait on web server"?

**Comment by krocheck** [comment]
Can you select "All Interfaces: 0.0.0.0" from the list?

**Comment by dansherer8181** [comment]
Yes. Then it loads and says running. Then I get the frozen sync screen.

**Comment by dansherer8181** [comment]
Where does companion read the instances/connection list from? Or where does it store the config file that it’s running? I imagine that is part of the problem as it tries to sync.

**Comment by Julusian** [comment]
The rendering of this button is causing it to crash. Telling it to skip the offending text drawing results in this:
![image](https://user-images.githubusercontent.com/1327476/160467674-67c02be0-8ab5-480d-9608-d06dc2909001.png)

Minimum config file to reproduce: [julus-thinkpad_full-config_20220328-1950.zip](https://github.com/bitfocus/companion/files/8365496/julus-thinkpad_full-config_20220328-1950.zip)
It works changes if the top-bar is shown, so perhaps something slightly wrong with the numbers that uses?

**Comment by dansherer8181** [comment]
Aha I do remember turning off the top bar in the settings menu around the time this problem started!

**Comment by Julusian** [comment]
Fixed in the latest beta 4041 (https://github.com/bitfocus/companion/commit/96247b64149e3ed4e86d025d69353c5895bb3cfb)
