### ISSUE TITLE
[BUG] Shell commands on CopanionPi produce log errors, indicating "Host key verification failed."

### ISSUE THREAD

**Issue by WoozleEffect** [bitfocus/companion#1975]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When running internal shell commands, errors are thrown in the companion log.

Here are a bunch of examples:

'22.03.27 18:26:38 instance(internal): Shell command failed. Guru meditation: 
{"killed":false,"code":1,"signal":null,"cmd":"sudo /test.sh >> /home/pi/test.log 2>&1"}'

or

'{"killed":false,"code":1,"signal":null,"cmd":"sudo test.sh >> /home/pi/test.log 2>&1"}'
'{"killed":false,"code":1,"signal":null,"cmd":"sudo ./test.sh >> /home/pi/test.log 2>&1"}'
'{"killed":false,"code":1,"signal":null,"cmd":"sudo ./home/pi/test.sh >> /home/pi/test.log 2>&1"}'
'{"killed":false,"code":255,"signal":null,"cmd":"sudo /home/pi/test.sh >> /home/pi/test.log 2>&1"}'

'{"killed":false,"code":255,"signal":null,"cmd":"/home/pi/test.sh >> /home/pi/test.log 2>&1"}'
'{"killed":false,"code":127,"signal":null,"cmd":"./home/pi/test.sh >> /home/pi/test.log 2>&1"}'
'{"killed":false,"code":127,"signal":null,"cmd":"./test.sh >> /home/pi/test.log 2>&1"}'
'{"killed":false,"code":127,"signal":null,"cmd":"PBvncON.sh >> /home/pi/test.log 2>&1"}'

'{"killed":false,"code":127,"signal":null,"cmd":"bash ./home/pi/test.sh >> /home/pi/test.log 2>&1"}'
'{"killed":false,"code":255,"signal":null,"cmd":"bash /home/pi/test.sh >> /home/pi/test.log 2>&1"}'
'{"killed":false,"code":127,"signal":null,"cmd":"bash ./test.sh >> /home/pi/test.log 2>&1"}'

The files execute just fine on the pie terminal, and via ssh from my mac terminal.

I do run another shell file: 'sudo reboot -r now'
And that one works just fine.

Is this something about the directory structure of the CompanionPi image, or the location o the files? Or something else?
Not sure what the "Host Key Verification Failed" message in the log is all about.

I also get a "file not found" error in some of the above configurations.
'/bin/sh: 1: ./test.sh: not found'
'sudo: ./test.sh: command not found'
'bash: ./test.sh: No such file or directory'

I am getting the impression the '/bin/sh: 1:' may be a clue to what's happening, but I know too little about code and pi and all this to know what it is.

### Steps To Reproduce

1. internal: Run shell path (local)
2. `/home/pi/test.sh` or `sudo /home/pi/test.sh` or `bash /home/pi/test.sh` or `sudo ./test.sh` ... etc

### Expected Behavior

The command should be run.

### Environment (please complete the following information)

```markdown
- OS: Companion Pi - Current image. Raspberry Pi 4. Companion 2.2.0
```

**Comment by Julusian** [comment]
'Host Key Verification Failed' is output from ssh when it cant verify the identity of the remote host.
Make sure you are doing your testing as the same user that companion is run as. Or perhaps ssh has a parameter to tell it to always accept the new host identity?

I don't think this is a problem with companion, so I am going to close this.
You will probably have more luck with getting help on the slack or facebook group, as there are many more users there who might be able to help

**Comment by istnv** [comment]
Error code 1 is `(command) File not found`
Code 127 is probably `Cannot run a non executable file`
Code 255 is `Command ran, exited with an error`   <-- can't validate host key error was probably these.

When you first run `ssh` to any host it gives you a warning:
```
The authenticity of host 'xx.xx.xx.xx' can't be established.
ECDSA key fingerprint is SHA256:TLsbW/.......
Are you sure you want to continue connecting (yes/no/[fingerprint])?'
```
You need to run that command at least once with the same user id as Companion runs, which appears to be `root`.
-- login to a terminal session on the Pi
-- run `sudo /home/pi/test.sh`
That should give you the `yes/no` option. Once allowed, `ssh` does not ask again for that same host.

**Comment by WoozleEffect** [comment]
@istnv THAT WAS IT!
Thank you!
Problem solved!

**Comment by rmmcdr** [comment]
@WoozleEffect
Hi!
I'm trying to do the same without success :-/
Finally, what command did you use?

**Comment by jfou87** [comment]
I've got the same trouble. On a headless debian with the installation of the companion pi image as explained. It's working fine, but not within Companion shell command. I've got error 1 or 127.
