### ISSUE TITLE
Hi, i have upgraded to V2.20 and keep getting a "sycning" error on start up. Running Windows 10

### ISSUE THREAD

**Issue by Kevlar1979** [bitfocus/companion#1978]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by krocheck** [comment]
Hi @Kevlar1979 .  We have seen this error in the wild, but we need details like your browser, os version, and companion version number in order to track this down.  Most importantly, are you using the `Remove the topbar on each button` setting?  Did you upgrade from a beta or a stable release?  If beta, what version did you upgrade from?

**Comment by Kevlar1979** [comment]
Hi there, Still new at companion. It was working until i upgraded to windows 10 on my PC.  Running Companion V2.2.0 , the latest version on your site. and upgraded from the previous working version. 
![Capture1](https://user-images.githubusercontent.com/102646373/160762956-0ef9d192-adc5-4ee0-8e63-2d0fb1fccd01.PNG)
![Capture2](https://user-images.githubusercontent.com/102646373/160762968-2a3c4cdd-030c-4577-8fb8-3a4f50ed473f.PNG)

**Comment by Kevlar1979** [comment]
"Remove the topbar on each button setting", im not to sure what you mean?

**Comment by Julusian** [comment]
Could you share your config file with us? That will help us identify where the issue lies.
Either attach it here, or email it to git@julusian.co.uk

**Comment by Langsommanden** [comment]
I had the same issue, and this trick fixed it for me:
- Uninstall Companion
- Rename the folder: %USERPROFILE%\AppData\Roaming\Companion
- Install Companion


I found it, in this thread:
https://github.com/bitfocus/companion/issues/1221

**Comment by Julusian** [comment]
@Langsommanden any chance you made a backup of those files before deleting?
Something got corrupt or messed up in your config, and we can't make changes to avoid the issue recurring without knowing what happened

**Comment by Langsommanden** [comment]
@Julusian I'm sorry to say that the folder was deleted afterwards.

**Comment by Kevlar1979** [comment]
@Julusian , so renaming the Install file to "%USERPROFILE%\AppData\Roaming\Companion, didn't work.    I'm not to sure what you mean about Sharing Configuration file.  If i click "configuration Wizard", nothing happens.

**Comment by Julusian** [comment]
@Kevlar1979 I mean zip the folder and either attach it here or email it to me at git@julusian.co.uk

**Comment by Julusian** [comment]
This is lacking information needed to be able to confirm, but I suspect this is the same as a similar bug which is already fixed in the betas.
If anyone who can reproduce this can provide me with their db, I can check if it is the same or a different issue
