### ISSUE TITLE
Slow UI & Failed to load bank config

### ISSUE THREAD

**Issue by LHasenbein** [bitfocus/companion#1992]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Companion seems very slow on my MacBook Pro M1 Max. I have version [2.2.0 (2.2.0+4067-beta-8a90993c)] installed. Saw this on previos versions too, "stable" for me is version [2.2.0 (2.2.0+3998-beta-45c08dc1)].

### Steps To Reproduce

Sometimes the reaction of companion needs seconds e.g. if I first change the buttons page from 1 to 5 it needs up to 10 seconds to get there. After a few clicks on several buttons companion needs again three seconds to show "Failed to load bank config". I saw this on my Intel MacBook too.

### Expected Behavior

Instant action, no waiting time.

### Environment (please complete the following information)

```markdown
- OS: macOS 12.3.1
- Browser: Safari 15.4
- Companion Version: [2.2.0 (2.2.0+4067-beta-8a90993c)]
```

**Comment by amcchord** [comment]
I can confirm this issue.. I cannot trace back when it was introduced. Companion's performance in safari has been degraded for a while. Its especially an issue working in high latency environments like over a VPN.

**Comment by Julusian** [comment]
Please try the latest beta build.
I had a quick look and found a very obvious and large performance bottleneck when connecting. It was sending the log across one line at a time, which could cause many hundreds of ui redraws which would take many seconds (easily 30+).
After batching that up, I am finding it much more responsive

**Comment by LHasenbein** [comment]
I have tried the latest beta build [2.2.0 (2.2.0+4074-beta-671994ed)] - and waiting time is increased. After startup a change of the button page needs over 40 seconds. Still there: "Failed to load bank config", after clicking on a few buttons. New: Regularly the UI is switched off. "It seems that we have lost connection to the companion app." for 140+ seconds. App is still running. UI is coming back.

**Comment by Julusian** [comment]
Thats strange...
Could you go to the log tab and click 'Export support bundle' and send that across to git@julusian.co.uk? That will give a better view of what your setup is doing.
Once you have exported that, if you click the 'Clear log' button, does that help at all?

**Comment by Julusian** [comment]
Hmm.. I've loaded your db, and it looks to be working fine for me. So im a bit stuck on how to proceed.
All I can think is that some/one of the modules you use is being particularly noisy when it is connected to the device. Could you try with them all disabled and re-enable them one by one too see if it gets visibly worse?

**Comment by LHasenbein** [comment]
I needed a few test days. Obviously you were right. It's a module. I've tested every single module and when I activate "BirdDog PTZ" everything becomes slow up to the point where UI losing connection and need minutes to come back. I've now disabled the module, everythings working fine.

**Comment by Julusian** [comment]
@bryce-seifert I think you know the birddog module. Could you take a look to try and hunt down what it is doing that could be causing this?

**Comment by bryce-seifert** [comment]
@LHasenbein With the BirdDog module enabled, are there any messages shown in the log? Also, are you using the latest LTS firmware on your BirdDog


@amcchord Are you also using the BirdDog module?

**Comment by LHasenbein** [comment]
@bryce-seifert First I have to mention that there's no cam connected. If I enable the module there's "instance(Birddog PF120): Connection lost to BirdDog PTZ camera" in the log. After that, no more entrys from the module.

**Comment by bryce-seifert** [comment]
Interesting. Can you try the very latest beta as of yesterday, and see if that makes any different.

Also, if you connect a camera does it still behave slowly?

**Comment by LHasenbein** [comment]
Have tried now latest beta, same problems.

I don't have a cam right now, I'm on vacation. Will try mid next week.

**Comment by Julusian** [comment]
How long after starting companion does it take to get into the bad state? Is that with just the one connection defined/enabled, or with other things too?

Even after loading the config you sent me and waiting for some minutes, it is not appearing noticably slower to me, the only problematic bit in the code I can see is that the polling be running multiple at a time, but they do eventually timeout, so while it is 'leaking' it is very contained. I cant say the same for other modules some of which kept trying to connect even after they were disabled...

**Comment by bryce-seifert** [comment]
I was trying this out (also M1). When I build from beta in my dev environment no problems. When I launch from the build I get this hanging sometimes, and it happens immediately.

This is with the BirdDog module completely deleted too, so I’m not quite sure it’s the issue although I’ll keep investigating.

**Comment by LHasenbein** [comment]
Hey @all I've made a screen record. Maybe it helps a little bit. First the module was off, behaviour of companion as expected. After enabling module it takes a few seconds, then ting get worse. Round about minute 2:18- at minute 3:08 UI died. After disabling the module it needs a few (more) seconds, then behaviour is quite normal.
Everything looks like it is the module. If I keep it disabled no problems the hole day. Hope the video helps a bit. https://we.tl/t-sjGxUxdasJ

**Comment by Julusian** [comment]
I have found an issue with the birddog module that doesnt sound exactly like this, but has some overlap.

There is no call to `'udp.on('error', ....)`, meaning that if a udp packet errors, such as the host being down or unreachable, that becomes an unhandled error. This usually manifests as an error dialog that pauses all application execution until dismissed, but isnt for some reason anymore unless running a dev electron version. And if running the headless version it fully crashes companion.
So I don't know if this is the cause, but it wouldnt surprise me if it was for some reason causing this freezing instead.

**Comment by bryce-seifert** [comment]
@Julusian Noted, I will fix that.

**Comment by Julusian** [comment]
@LHasenbein is this running any better recently? There have been some other reports of slowness that have had some fixes go in. It is possible this has a lot of overlap with those

**Comment by LHasenbein** [comment]
@Julusian Problems are still there. Using 2.2.0 (2.2.0+4127-beta-c23b011f)

**Comment by bryce-seifert** [comment]
@Julusian @LHasenbein The latest beta should have the catch for udp error as well as some other fixes if you want to see if the problem persists.

**Comment by LHasenbein** [comment]
Hello @bryce-seifert I've tested the new version [2.2.0 (2.2.0+4139-beta-02015910)] unfortunately the problem persists. Every few seconds everything is frozen for 2 to 9 seconds and then repeat. Sorry.

**Comment by bryce-seifert** [comment]
@LHasenbein Does disabling the BirdDog module still "fix" the freezing issue? Or does it freeze regardless?

**Comment by LHasenbein** [comment]
@bryce-seifert Absolutely, disabling „fixes“ the problem. When enabled, it needs a few seconds, round 30 or 40, to „begin“ with freezing. After disabling it needs that time too. And then, no more issues.

**Comment by Julusian** [comment]
I believe this has been fixed now in 2.2.2

**Comment by Julusian** [comment]
This has been sat around for so long, with so many changes having been made in 3.0 that if it is still an issue there it needs some new data to attempt to reproduce or understand it.
@LHasenbein is it still a problem in 3.0.0-rc1? If so, are you able to pin it down to a specific module causing it?

**Comment by Julusian** [comment]
Closing this until someone can confirm if it is still happening in 3.0/3.1
