### ISSUE TITLE
Sunrise/sunset trigger times

### ISSUE THREAD

**Issue by Deanbau** [bitfocus/companion#1993]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

The ability to set triggers based on Sunrise/Sunset and offsets for those times. 

GPS location will be required

### Usecases

Automated projection/lighting projects.

**Comment by istnv** [comment]
`openweather-rest` has sunrise and sunset.

**Comment by Julusian** [comment]
Implemented by #2434

**Comment by fkmobile** [comment]
How can you enable it for days of week and not just the time?
