### ISSUE TITLE
tablet page blank on android 5

### ISSUE THREAD

**Issue by martinius332** [bitfocus/companion#1998]
Hi,
I would like to use an old adroid 5 tablet to remote control vmix.. or so via companion...
It works super with my mobile phone (Android 10), but if I connect (with Wifi on ;-)  ) with the old tablet
(android 5) - Opera Mini Browser
to localhost:8088  in my case its: 192.168.100.60:8000  
I tested oder IP adresses an Ports too, but same result.
connects somehow to the page, but no data is loaded...

**Comment by Julusian** [comment]
Can you check what version of chrome the browser reports as being? or what rendering engine it is reporting?
Which tablet page are you trying to use?

I am tempted to say supporting a 5+ year out of date android browser is not something that we are interested in doing, and may not even be possible as sourcing something to test on will be a challenge. 
But lets see how old the browser reports itself as before deciding

**Comment by Julusian** [comment]
I have tried to reproduce this using [browserstack](https://www.browserstack.com/), but all the mobile pages are loading normally in chrome. 
Have you tried using chrome instead of opera mini? opera mini is not an option for testing, but as chrome works I dont see the need to fix it
