### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kjetilpp** [bitfocus/companion#1999]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When i press the page name button, on the stream deck it changes to page 1, as expected. 
But when using HTTP to call the same button, like /press/bank/1/26 it do not change to page 1. 
![Screenshot 2022-04-17 190328](https://user-images.githubusercontent.com/5620578/163724987-1b2af176-231d-4fd4-a82c-84f8f3aed344.png)
![Screenshot 2022-04-17 190750](https://user-images.githubusercontent.com/5620578/163725035-28324556-79ce-430a-b561-c57c352b1d96.png)

### Steps To Reproduce

Send a HTTP (or OSC etc) request to the page name button, in my case /press/bank/2/26

### Expected Behavior

Expecting the stream deck to change page to 1. 

### Environment (please complete the following information)

```markdown
- OS: Companion PI
- Browser: N/A
- Companion Version: 2.2.0 (2.2.0+3998-ccea40c7)
```

### Additional context

Not sure if this is a bug, or missing feature?

**Comment by Julusian** [comment]
This is expected behaviour.
I assume you only have one streamdeck attached, but if you have multiple, then which one would you expect to be changed?

The http/osc/udp/tcp press commands are pressing a button outside of the context of a streamdeck. 

I suggest you look at the `PAGE-SET 23 emulator` command that is in the tcp/udp (maybe more) apis. That will do what you want if you provide the correct surface id to it

**Comment by kjetilpp** [comment]
> This is expected behaviour.
> 
> I assume you only have one streamdeck attached, but if you have multiple, then which one would you expect to be changed?
> 
> 
> 
> The http/osc/udp/tcp press commands are pressing a button outside of the context of a streamdeck. 
> 
> 
> 
> I suggest you look at the `PAGE-SET 23 emulator` command that is in the tcp/udp (maybe more) apis. That will do what you want if you provide the correct surface id to it

Thanks! Do you have A link to the TCP/UDP api documentation?

**Comment by Julusian** [comment]
In your companion, there is a 'getting started' link on the left. then scroll down to the section 'remote control'
