### ISSUE TITLE
Mitti Toggle Play Action does not work

### ISSUE THREAD

**Issue by PerRoine** [bitfocus/companion#20]
The Toggle play action actually requires an argument (1 / 0), we could possibly make a function to change between 1 and 0 for each keypress.

we will look into it.

note : either remove action or make it alternate between 1 and 0

**Comment by haakonnessjoen** [comment]
Wow, they have really misunderstood the concept of «toggle»

**Comment by lov** [comment]
Hi Guys,

just for reference: the upcoming Mitti 1.5 release handles toggles by OSC as expected, but for compatibility you will still be able send 0 and 1 for toggles.

Cheers!

**Comment by lov** [comment]
Oh well, if you want to `/mitti/togglePlay` toggle the state of playback now you can do that without sending an argument. Otherwise, you can still send an argument to switch to specific state. :)
