### ISSUE TITLE
Alert on launch if Stream Deck app is running

### ISSUE THREAD

**Issue by DaveShep** [bitfocus/companion#200]
**Describe the feature**
Alert on launch if Stream Deck app is running. Perhaps offer to shutdown Stream Deck app,  automatically?, before taking over controller.

Running the Stream Deck app while using Companion causes issues. There is no option in the Stream Deck app to not launch at startup. Many users have the same problem, not realising they should exit the app first.

**Comment by Julusian** [comment]
We already don't allow opening devices if the elgato app is detected, and have better support for running both in 2.2
