### ISSUE TITLE
[BUG] Raspberry Companion Update breaks system

### ISSUE THREAD

**Issue by mindandvision** [bitfocus/companion#2002]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If I use the

`sudo companion-update`

command on a fresh installed SD-card from the official Companion image, 

The updater then crashes during "Creating an optimized production build...". Only a powercycle helps.

After the power cycle the result is that Companion will not display the Admin page anymore. All I get is a "Cannot GET /" error on a white browser page.

Cheers

### Steps To Reproduce

1. Flash Comapnion image to a SD card
2. Use putty to update Companion
3. Encounter the error

### Expected Behavior

The update process should run through without crashing.

### Environment (please complete the following information)

```markdown
- OS: Raspberry
- Browser: Chrome
- Companion Version: 2.2.0
```

**Comment by Julusian** [comment]
Are you sure it is crashing and not being slow? That step does take a while on a pi. 

How much memory does your pi have?

**Comment by mindandvision** [comment]
Ah OK - that may be the issue - I used a 2GB Pi4. And yes it is crashing - I cannot connect anymore after this behaviour not via HTTP and SSH. I waited an hour without any change.

Cheers

**Comment by Julusian** [comment]
It should not take anywhere near an hour, and yeah that does sound crashed as ssh wouldn't connect.
It is possible that 2gb memory isn't enough, I'll have a play, I have an idea for a work around. 
Or perhaps the psu isn't liking the  prolonged high cpu usage? Is it an official psu?

**Comment by mindandvision** [comment]
Yes it is the official Raspberry PSU. And nothing is plugged into the USB port (no Streamdeck connected).

But I think the 2GB limit is the problem. I'll try it tomorrow with a 4GB Pi and report if it works.

BTW - I tried it with a Pi3+ and that one showed this problem too.

Cheers

**Comment by istnv** [comment]
Add a swapfile on your SD Card. That will let the OS pretend it has 4G memory. It is quite a bit slower than real ram but it should get past the crash.

**Comment by Julusian** [comment]
@istnv yes that is what I am thinking needs to be done. would be good to have it automatically done for companionpi to avoid others hitting the same thing

**Comment by mindandvision** [comment]
By activating and raising the size of the swap file it works now. Thanks for the tip!
Even on the Pi3+ the update of companion runs now without any crash.

On the Pi4 4GB it worked without activating the swap file. So it seems to be a memory issue.

Thanks again and Cheers

**Comment by mindandvision** [comment]
OK new information:

The Companion update routine works now but after the update the error is still persistent:

"Cannot GET /" on a white page. No Companion Admin page anymore.

Cheers

**Comment by Julusian** [comment]
Sounds like it didn't work then. That "creating an optimized production build" step is recompiling the webui code. What is the log output like now?

**Comment by mindandvision** [comment]
As I said the companion update now runs without any hicup. It doesn't give me any errors. But the result is that the admin page isn't working anymore. If you refer to another log output please let me know where I can find it.

Cheers

**Comment by Julusian** [comment]
Anything or interest would be in the console output when running the command.
I don't know why the webui doesnt load then. I will have to try running the update myself on a pi. I do have a 3b sat around somewhere

**Comment by Julusian** [comment]
I have given this a try on a pi3, and have updated some scripts to add a temporary swapfile during the update process to avoid it running out of memory.
I can now run the update on that pi and the webui will work afterwards
