### ISSUE TITLE
More than 99 Pages

### ISSUE THREAD

**Issue by Madcliff** [bitfocus/companion#2003]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Greetings, can we please get the ability to enable more than 99 pages. 

### Usecases

Companion is perhaps the most mature solution for Streamdeck on the linux Platform. I find that my usecase of the streamdeck is predominantly for expansive use of unicode with diacritics in classical languages and for macro functionalities. 
As part of this requirement, I find it helpful to be able to have increasingly complex nested pages to help me control and have intuitive access to the particular scripted commands that generate the respective unicode character.

**Comment by gerbenvandekraats** [comment]
+1

**Comment by davidjoshuaford** [comment]
+1 for this feature too! 99 pages is not enough... :) Does companion get sluggish or unstable if it were to exceed 99?

**Comment by josephdadams** [comment]
It’s like trying to go past Warp 9. Weird stuff happens

**Comment by MikeTechnical** [comment]
Hi there,
When will more than 99 pages be available?
I have 3.3 running and still don't see the pages option.
Am I missing it somewhere, or is it just not implemented yet?

**Comment by Julusian** [comment]
This is now in the betas

**Comment by davidjoshuaford** [comment]
Will check out warp 9!
