### ISSUE TITLE
Button in Companion app to go back to stream deck created profile page

### ISSUE THREAD

**Issue by ripalashah** [bitfocus/companion#2004]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Button within companion app to go back to stream deck profile. 

I don't find button for going back to stream deck profile once you entered in companion app pages.  

### Usecases

MixEffect button app link - Full approximately 72  profile pages of MixEffect app. While going on first page the feature should be available to link to Stream Deck profile page. 
Need to include other pages in companion app like VLC button and Blackmagic Design Atem Mini button.

**Comment by Julusian** [comment]
The elgato software does not have a documented way for a plugin to change to an arbitrary profile, so it is not possible for us to control the elgato software in this way
