### ISSUE TITLE
Control Latch-State from Feedback

### ISSUE THREAD

**Issue by MaZderMind** [bitfocus/companion#2007]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I'd like to be able to toggle the Latch-State (swapping the Button between Latched/Unlatched State) via a Feedback. When the function is turned on via an external Stimulus, the Button will go into Latch-Mode. Pressing it again would execute the Release-Actions.

### Usecases

I'm controlling Light-Fixtures via KNX-IP (I'll open a PR for the respective Module in the next Week or so). The Lights can be turned on or off by KNX Buttons in the Room. The State can be monitored using a Feedback. I currently have to configure two buttons (On and Off) to visualize the Status and control all States.

<img width="1422" alt="Screenshot 2022-04-28 at 17 36 32" src="https://user-images.githubusercontent.com/142237/165790307-a06a8ecb-1980-41ca-b254-cf4aa4e53485.png">

**Comment by MaZderMind** [comment]
I''d give implementing this a try myself but I would like some Feedback for the Idea beforehand.

**Comment by Julusian** [comment]
By latch state, do you mean whether the 'latch/toggle' checkbox is ticked, or assuming it is ticked, swapping the button between the latched and unlatched state?

**Comment by Julusian** [comment]
Also, what module is that using? 
It might be possible to make the module to have a 'Toggle' option for 'Switch Value', negating the need for this

**Comment by MaZderMind** [comment]
It's a Module I'm currently working on (https://github.com/MaZderMind/companion-module-knxip). Adding Toggle is certainly possible, however I'd find it cleaner to have the functionality within companion (that already has a Toggle-Functionality as part of the Latch Button) instead of implementing additional Toggle-Logic in each Module.

**Comment by Julusian** [comment]
It is cleaner to do it in the module.
To do it in companion will require setting up a trigger to react to the feedback from your module and run an action to set the button state. Feedbacks are only allowed to change how the button looks, and latch state is not part of that

**Comment by MaZderMind** [comment]
Ok, thank you very much for the Feedback!
I'll implement it in the Module then and close this Issue.

Have a nice day :)
