### ISSUE TITLE
Countdown / Countup / Timer function or dummy module.

### ISSUE THREAD

**Issue by lestrobl** [bitfocus/companion#2010]
### Is this a feature relevant to companion itself, and not a module?

- [x] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

It would be awesome to have an internal countup and countdown timer, so something like a dummy module.
It should have the possibility to set a time, start and stop a timer and show the time on a button.
Also a support for multiple timers would be great.
One use case for us would be to monitor the battery runtimes of our RF Cameras.

I think this could be also used for triggers as mentioned in https://github.com/bitfocus/companion/issues/292

### Usecases

-Usage for Triggers 
-Monitoring of runtimes (Batteries...)
-Time to start for the crew
-Time to something

**Comment by lestrobl** [comment]
Is this function still under development for an internal module?
Or should I just write a simple, own module ?

**Comment by nhaun24** [comment]
+ 1 for this, am looking to countdown the delay time as feedback on either the button its self or on an adjacent button.

**Comment by TheSashmo** [comment]
+1 for this too!

**Comment by JeLuF** [comment]
Basic countdown functionality is available from the `generic: stopwatch` module.

**Comment by TheSashmo** [comment]
I see that now! TY
