### ISSUE TITLE
[BUG] Generic SNMP module not visible in Companion builds

### ISSUE THREAD

**Issue by JonathanPowe** [bitfocus/companion#2011]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Generic SNMP module is in the Repositories list and has had a few Releases, 
([https://github.com/bitfocus/companion-module-generic-snmp/releases](https://github.com/bitfocus/companion-module-generic-snmp/releases)), however it doesn't seem to be visible in the modules list in Companion. I've checked the latest beta builds and searched for "SNMP", but can't find it.

Do I need to change a setting in Companion to be able to use this module?
Or is it still awaiting approval before being added to the main builds?
![image](https://user-images.githubusercontent.com/101350871/166662138-4c57fce5-1f08-44d2-a359-00b8ef6a2b5c.png)

### Steps To Reproduce

1. Install and run companion 
2. Open GUI webpage 
3. Search "SNMP" in Add Connection box 
4. No results found 

### Expected Behavior

Generic SNMP module to show in search results 

### Environment (please complete the following information)

```markdown
- OS: Windows 10 / Windows Server 2016
- Browser: Chrome Version 101.0.4951.54 (Official Build) (64-bit) / Edge Version 101.0.1210.32 (Official build) (64-bit)
- Companion Version: 2.2.0 (2.2.0+4127-beta-c23b011f)
```

**Comment by Julusian** [comment]
As far I can see, it looks like it was never submitted for review and inclusion. 
It might have been blocked on https://github.com/bitfocus/companion/pull/1796 and then never finished

Lets ping the author and continue discussion in the module repository https://github.com/bitfocus/companion-module-generic-snmp/issues/1
