### ISSUE TITLE
[BUG] unable to find userguide (gettinstarted.md) on githuvb

### ISSUE THREAD

**Issue by marksyuk** [bitfocus/companion#2015]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

unable to find any user documentation. when i click on the link i get a 404 error

### Steps To Reproduce

1) login to github and navigate to https://github.com/bitfocus/companion/wiki/Getting-Started-Beginners-Guide
2) click on the "getting started" hyperlink in the paragraph titled "Welcome to Companion" 
3) 404 Page Not Found error occurs for this page: https://github.com/bitfocus/companion/blob/master/documentation/gettingstarted.md

### Expected Behavior

valid web page displays

### Environment (please complete the following information)

```markdown
- OS:windows
- Browser:firefox
- Companion Version:n/a
```

### Additional context

obvs. a problem with source tree on github rather than app itself

**Comment by Julusian** [comment]
The documentation was rewritten and moved to https://github.com/bitfocus/companion/tree/master/docs, but that doesnt display well on github directly.

The best way to view the documentation is to click the link in the left sidebar of your companion installation.

@willosof is there somewhere to view those docs online yet?

**Comment by marksyuk** [comment]
should i update  https://github.com/bitfocus/companion/wiki/Getting-Started-Beginners-Guide to reflect this?

**Comment by Julusian** [comment]
The docs are now published at https://user.bitfocus.io/docs/companion, and the link in the wiki has been updated
