### ISSUE TITLE
[Feat] Route HTTP requests from Companion to modules

### ISSUE THREAD

**Issue by thedist** [bitfocus/companion#2017]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

This request follows the discussion thread on slack: [https://bitfocusio.slack.com/archives/CFG7HAN5N/p1652451464856329](https://bitfocusio.slack.com/archives/CFG7HAN5N/p1652451464856329)

As Companion already runs a HTTP server for the web interface it would be beneficial if in some limited capacity this could be exposed to modules that need external interactivity. 

The main difficulty of implementing such a feature would be to give modules the control and data they need to be able to respond to requests while limiting access to the underlying Express server so that no module can negatively impact the function of Companion itself.

My vision for this feature would be for Companion to have a URL path such as `/instances/` and for each running instance to have a path within that base on the instance name (this allows for multiple instances of the same module to have unique paths, and placing them inside `/instances/` will prevent a naming conflict should someone name their instance something that's already in use, such as `connections` or `buttons`).

Companions routing would simply need a wildcard handler for each instance, as any further routing would be handled within the module itself by parsing the path. Companion could then send an event to the module along the lines of:
```
{
  "method": "GET",
  "path": "/instances/SomeModule/data"
  "headers": {
    ...all headers from the request
  },
  "body": ...Body, if present
}
```

The module would then need to send a response back to Companion
```
{
  "status": 200
  "body": ...some JSON
}
```

 Some things that'll need discussion:
- Naming scheme for the each modules path. How to handle modules using names with characters not usable in a URL path?
- Does Companion need to expose request data beyond just request method, headers, and body?
- Should modules need to 'register' a handler with Companion, so that requests to a module without a HTTP handler can be immediately 404'd rather than timing out waiting for the module to respond.
- Should there be some sort of rate limit to prevent excessive requests to one module locking up Express?

### Usecases

Currently my Google Sheets module, periodically polls the spreadsheets API to get sheet values and metadata, but Googles rate limit is quite restrictive so the more apps that need to poll the data reduces the responsiveness. If I was to use a Google Sheet data source in vMix that'd be a 2nd app sharing the same rate limit so the polling for both vMix and Companion would have to be halved.

Alternatively, if I could poll for the data within the Companion module and then serve it over HTTP to others apps, such as a URL `http://localhost:8000/instances/gsheets/data` I can then point vMix or any number of other apps to that URL for data and there'd only be 1 app actually making requests to Google allowing for the rate limit to be used as efficiently and responsive as possible.

**Comment by Julusian** [comment]
> * Naming scheme for the each modules path. How to handle modules using names with characters not usable in a URL path?

Yeah, I've just checked and what we allow as labels is already too loose. I can name an instance `atem:2` which then of course breaks all its variables. So we really should impose some restrictions, but requiring them to be url safe might be too frustrating for users.
Or we could use the internal id in the url, but that has a bunch of usability issues.
Im not sure how best to handle this right now..

> * Does Companion need to expose request data beyond just request method, headers, and body?

I think it should also include the client's ip.
More can be safely added later, so im not worried about covering everything from the beginningr

> * Should modules need to 'register' a handler with Companion, so that requests to a module without a HTTP handler can be immediately 404'd rather than timing out waiting for the module to respond.

I am picturing this to be a method which can be implemented by modules `handleHttpRequest(...)`. We can infer whether the module supports handling requests by whether that method exists at the time init is called. 

> * Should there be some sort of rate limit to prevent excessive requests to one module locking up Express?

Maybe? Is it possible to rate limit it? We would have to apply the rate limit after handling the initial route, at which point express has done 90% of the work it needs to do. 
I dont know. There may be value in some kind of rate limit, but Im happy to start without one and add it later if needed
