### ISSUE TITLE
Trigger on OBS Recording Status

### ISSUE THREAD

**Issue by IBC-IT** [bitfocus/companion#2018]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

There is an option to trigger on OBS active stream, but there is no option to trigger on OBS active recording status.
Please add option to trigger an action on OBS recording.

**Comment by bryce-seifert** [comment]
You should be able to trigger on recording using the variable value, like this:
<img width="782" alt="Screen Shot 2022-05-14 at 6 31 45 PM" src="https://user-images.githubusercontent.com/50299051/168451280-697f95e1-cb88-4260-b322-adca07277a25.png">
It's not currently available as a feedback (like streaming) because there are multiple states to "Recording", including paused. This may be revisited with the 5.0 rewrite I'm doing currently

**Comment by IBC-IT** [comment]
Thank you. 
Could you please clarify what the difference between internal and feedback is?

**Comment by bryce-seifert** [comment]
@IBC-IT Sorry I don’t quite understand the question, is this in relation to triggers? Can you provide an example?

**Comment by IBC-IT** [comment]
@bryce-seifert You say "It's not currently available as a feedback (like streaming) because there are multiple states to "Recording"" 
What is the difference between an "internal" trigger and one that falls under "obs"?

**Comment by IBC-IT** [comment]
> You should be able to trigger on recording using the variable value, like this: <img alt="Screen Shot 2022-05-14 at 6 31 45 PM" width="782" src="https://user-images.githubusercontent.com/50299051/168451280-697f95e1-cb88-4260-b322-adca07277a25.png"> It's not currently available as a feedback (like streaming) because there are multiple states to "Recording", including paused. This may be revisited with the 5.0 rewrite I'm doing currently

This does not seem to work. 
Basically, I need unmute a channel on the Behringer x32 once the recording begins in OBS. I tested the action within Companion and it does work, but it does not trigger on OBS Recording.
However, the trigger does work for the "obs: Streaming Active" condition.

**Comment by bryce-seifert** [comment]
Odd, it's working or me.
<img width="1815" alt="Screen Shot 2022-05-16 at 6 42 54 PM" src="https://user-images.githubusercontent.com/50299051/168699865-72683e4c-e0c5-4f3e-aa13-99376b3d0371.png">
<img width="1823" alt="Screen Shot 2022-05-16 at 6 43 00 PM" src="https://user-images.githubusercontent.com/50299051/168699867-ec60d161-e281-4516-b40a-cc9419ae7c7e.png">

> What is the difference between an "internal" trigger and one that falls under "obs"?
Internal triggers are defined by companion, obs is defined by the module.

What version of Companion are you running? Can you double check what there value of the $(obs:recording) variable is when recording?

**Comment by IBC-IT** [comment]
I'm trying to set this up under the "Triggers" tab, without assigning any buttons.
Using the latest version of both OBS and Companion on Mac.

**Comment by bryce-seifert** [comment]
@IBC-IT Can you double check what there value of the $(obs:recording) variable is when recording?

**Comment by IBC-IT** [comment]
> @IBC-IT Can you double check what there value of the $(obs:recording) variable is when recording?

How would I check for this?
I did double-check that I set "Recording" as you describe above.

**Comment by bryce-seifert** [comment]
<img width="867" alt="Screen Shot 2022-05-16 at 7 16 58 PM" src="https://user-images.githubusercontent.com/50299051/168702498-5b4d14d5-2d72-40a7-b3b2-8e21d06dd2df.png">
If you go to Buttons > Variables > OBS, you should be able to find the recording variable and see what the value is

**Comment by IBC-IT** [comment]
Seems to stay "undefined," regardless of whether it is recording.
![Screen Shot 2022-05-16 at 5 24 13 PM](https://user-images.githubusercontent.com/79610093/168703003-65e43a26-7c9d-4a28-85be-350c5910208c.png)

**Comment by IBC-IT** [comment]
Working now!
Needed to update the websockets plugin for OBS.

**Comment by bryce-seifert** [comment]
Awesome, glad to hear it! 

Like I said I may change the recording feedback to work with this  future versions but for now this should work just the same
