### ISSUE TITLE
Internal Variable that contains the current unix timestamp

### ISSUE THREAD

**Issue by amcchord** [bitfocus/companion#2028]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

This would be an internal variable much like the other date / time variables but it would include the current unix timestamp. Now that internal functions exist to compare variables and to perform basic variable math there are many cases where being able to work with the current unix time would be helpful. 

### Usecases

Compare to a custom variable to see if a current time has passed as part of a trigger.
Using the math functions create a countdown or count up timer.

**Comment by Julusian** [comment]
This is in the betas
