### ISSUE TITLE
Ross Carbonite Solo: Aux switching possible?

### ISSUE THREAD

**Issue by TobiasBecker** [bitfocus/companion#203]
**Describe the feature**
Cut to different Inputs from the Carbonite to the AUX.
The Solo does not have a dedicated AUX Switching bus, also this enabled remote controlling the Solo via the Streamdeck from a 2nd operator or from the same operatoring in a direct manner.

**Is this platform dependent (windows, mac, ..)?**
yes, / Ross TCP IP

**If documentation is required to implement, do you know where to find it?**
-

**Usecases**
see above

Thanks,
Tobi

**Comment by haakonnessjoen** [comment]
Not tested on Solo specifically, but should already be possible using XPT in the current module.

**Comment by monoxane** [comment]
I have done it on a solo black, I'll have to check how i did it next time in have one around but it is definitely possible

**Comment by haakonnessjoen** [comment]
I don't see how this should be different from a regular carbonite. So it should work fine with aux xpt
