### ISSUE TITLE
Sorting triggers

### ISSUE THREAD

**Issue by jsnyder886** [bitfocus/companion#2035]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I would like to be able to sort my triggers for readability.  I would suggest grouping triggers by type of trigger first, then providing sort options based on the type of trigger it is.  For time triggers, the obvious option that comes to mind would be the ability to sort by the next time based trigger to fire, alphabetical by name, schedule etc.  For feedback based triggers, also sorting by name would be helpful, by module name that the feedback comes from, or by variable name, etc.

I have several dozen triggers at this point and it has become quite a chore to try to navigate this list when the need arises to troubleshoot or make adjustments.

**Comment by Julusian** [comment]
I think there are two approaches that could be taken to this:

1) keep the order defined manually, and leave it up to the user to sort them as they like
1) put them into a table that allows for sorting by different column on the fly

And perhaps it would work with either strategy, is to be able to group/categorise the triggers in some way. This would work nicely with manual ordering, and would need some work to figure out how/if that would work with the auto sorting.

Does anyone with long lists of triggers have any insight into what they would like to see?

**Comment by Julusian** [comment]
This is in the 3.0 betas
