### ISSUE TITLE
[BUG] Ubuntu 22.04 execute error

### ISSUE THREAD

**Issue by chowhi123** [bitfocus/companion#2037]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am currently running Ubuntu VM over ESXI with ryzen CPU.  When I execute companion using CLI ./companion I get error 

Configuring sentry error reporting
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

### Steps To Reproduce

1. On linux 22.04 server
2. untar the file
3. use ./companion on untared directory

### Environment (please complete the following information)

```markdown
- OS: Linux 22.04
- Browser:
- Companion Version: 2.2.1
```

**Comment by Julusian** [comment]
Are you wanting a server or desktop installation?
Does it run even with that error? Electron/chromium can produce some weird internal errors that are harmless.

**Comment by chowhi123** [comment]
Hi, I am running a server installation. I couldn't get it working with server so I used one with gui which is working fine.

**Comment by Julusian** [comment]
The linux builds available on the website are for desktop only, and will not run on a headless server.
For that you should refer to the wiki https://github.com/bitfocus/companion/wiki/Manual-Install-on-Raspberry-Pi
