### ISSUE TITLE
Input for triggering buttons with a remote

### ISSUE THREAD

**Issue by goblynn93** [bitfocus/companion#204]
**Describe the feature**
Setup listening for specific trigger messages to activate a button assigned to that trigger, and an action to toggle the external control on/off as needed.

**Is this platform dependent (windows, mac, ..)?**
No.

**If documentation is required to implement, do you know where to find it?**
Not that I know of.

**Usecases**
Often times when running a presentation there is a wireless cue light system involved. Systems such as the D'san PerfectCue send programmable messages to the computer over USB. Typically these will forward or reverse the slides for PowerPoint or Keynote. These messages can be up to 128 characters (I believe this is the limit). The ability to use these to send custom strings  that will trigger a button assigned to that string would be really nice! Sometimes the presenter doesn't want to feel the delay between my seeing a cue light and pressing the button to move forward. It feels broken to them... Being able to trigger a button action with the PerfectCue would eliminate that broken feel and expand the amazing flexibility of Companion and StreamDeck, and would create a new way to handle multiple graphics machines with a single PerfectCue/cue light system.

**Comment by PerRoine** [comment]
We are looking into making more options available for triggering actions in companion in addition to the streamdeck , at the moment we have OSC and are planning to implement TCP/UDP and Midi. PerfectCue and MicroCue is not far fetched as we do use them ourselves. so keep a look out for more information about thi

**Comment by goblynn93** [comment]
This is really good to hear.

So much power!

Thank you for everything you guys have done.

**Comment by chrisrouse** [comment]
Any update on being able to trigger companion directly with MIDI? I'd really like to be able to bypass MIDI to OSC translators and just trigger buttons directly.

**Comment by dnmeid** [comment]
Closing this old issue. Requested functionality is available for long time. Banks can be triggered by OSC, TCP, UDP, HTTP, Artnet and the Emulator can be triggered with keystrokes.

**Comment by goblynn93** [comment]
This is NOT solved.

Please tell me how I'm supposed to trigger Companion from a Perfect Cue?

Thanks!
Brian

**Comment by dnmeid** [comment]
Hi Brian, this is not the place for support but you can open a webpage with the streamdeck emulator. The emulator can be controlled with keystrokes (1,2,3,4,5...). You just have to program e.g. "1" to your perfect cue and then the remote triggers the first button of the emulator. I hope you got the point.

**Comment by goblynn93** [comment]
Got it. Did not realize the keyboard input was there. Thanks.
