### ISSUE TITLE
[BUG] Scrolling not working correctly when Feedback colour picker open

### ISSUE THREAD

**Issue by JonathanPowe** [bitfocus/companion#2042]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The colour picker on feedback (for background and text colour) can display off the end of the page and scrolling down doesn't work to reveal it. 

Possibly an issue related to precisely where the mouse is positioned when rolling the scroll wheel?, as when taking the screenshot it sometimes worked and sometimes didn't. 
Clicking somewhere on the page (which closes the colour picker) brings back the normal scrolling functionality.
![Colour-picker](https://user-images.githubusercontent.com/101350871/173392979-7f85c927-8355-4bb9-9d5b-a7377fb3f9d1.png)

I positioned the mouse on the colour picker itself (instead of next to it, or above it after clicking to open it) and scrolling worked. It allowed me to scroll all the way up the page too, at which point no scrolling worked until I clicked somewhere to close the (now no longer visible) colour picker. 

### Steps To Reproduce

1. Add a module that supports feedback with colour (e.g. pjlink) 
2. Create a button (or edit an existing one) 
3. Add a feedback at the end 
(depending on the size of your screen, additional Actions or Feedbacks might need adding to move the last Feedback to the bottom of the page)
4. Click to change the colour of the Feedback
5. Notice that the colour picker is partially hidden off the bottom of the page 
6. Scrolling the mouse wheel or dragging the scroll bar does not reveal the rest of the colour picker 

### Expected Behavior

Option 1: colour picker detects bottom of the page is too close, so positions itself _above_ the colour selection box / higher up the page 
Option 2: Page allows scrolling when colour picker is open, with the mouse pointer positioned anywhere on feedback section of the page 

### Environment (please complete the following information)

```markdown
- OS: Windows 10 / Windows server 2016 
- Browser: Google Chrome Version 102.0.5005.115 (Official Build) (64-bit) / Microsoft Edge Version 102.0.1245.39 (Official build) (64-bit)
- Companion Version: 2.3.0 (2.3.0+4480-beta-6fa83b5f)
```

### Additional context

Workaround: Temporarily add one or more Feedbacks after the one in question to make the page longer, set the colour of the first one, then delete the temporary Feedbacks.

**Comment by dnmeid** [comment]
I can verify this issue. Specifically in the situation described by @JonathanPowe scrolling is only possible when the pointer is over the colorpicker.
Additionally if the window is too narrow and the layout switches to one column, scroling doesn't work even if the pointer is over the colorpicker.

**Comment by Julusian** [comment]
This is better now in the betas
