### ISSUE TITLE
[BUG] loading GUI sticks while syncing

### ISSUE THREAD

**Issue by tipuraneo** [bitfocus/companion#2044]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After Updating a Pi with
`sudo companion-update`
to 2.2.2 (2.2.0-af93d1a0-3464), .node-version=14.19.0 GUI sticks while loading/syncing. Webconsole reports 'ContextData.jsx:51 Failed to load variable values list TimeoutError: Timed out after 5s at index.js:37:64'

![2022-06-16 11_36_38-DevTools - augamctl1 mt intern uni-leipzig de_8000_](https://user-images.githubusercontent.com/6901598/174041428-27fad318-1fa9-4dbd-8ec8-06fe4da920fe.png)
![2022-06-16 11_43_42-DevTools - augamctl1 mt intern uni-leipzig de_8000_](https://user-images.githubusercontent.com/6901598/174042785-d262b1d8-4b4c-49d9-b573-8071f4d97333.png)

### Steps To Reproduce
1. Restart Pi, restart companion
2. Load GUI via http in incognito window without plugins

### Expected Behavior
GUI is loaded and configuration is available

### Environment (please complete the following information)

```markdown
- OS: Rapsberrian 10
- Browser: Chrome 102
- Companion Version: 2.2.2 (2.2.0-af93d1a0-3464), .node-version=14.19.0
```

### Additional context

Web buttons and companion itself seems to work fine

**Comment by Julusian** [comment]
Can you run `companion-update` again and post the full log?
It sounds like the step of rebuilding the webui failed.
I am pretty sure that the `Failed to load variable values list` step was removed in 2.2.1

**Comment by tipuraneo** [comment]
By "full log" are you meaning the console output or a special file?

**Comment by tipuraneo** [comment]
Log of the console during `companion-update`:
[20220616123945-augamctl1.log](https://github.com/bitfocus/companion/files/8918188/20220616123945-augamctl1.log)

**Comment by tipuraneo** [comment]
Saw this too but did not thought it is an issue on my side. Let me check this with our network team. Could you please tell me which domain is beein called by 140.82.121.3?

**Comment by tipuraneo** [comment]
Your are right:

```
root@augamctl1:/home/pi# nc -vzw 5 140.82.121.3 443
nc: connect to 140.82.121.3 port 443 (tcp) timed out: Operation now in progress
```
On another hosts `nc` is able to connect. So it's not a bug, it's a network issue on my side. Thank you!

**Comment by Julusian** [comment]
Im going to leave this open as issues with `companion-update` failing halfway and users not noticing is not uncommon.
We should be able to make it clearer that something failed, and stop companion from running while in this broken state

**Comment by m-lux** [comment]
Hi guys,
I'm facing the same issue on a windows 11 machine.
The same problem occurs when downgrading to version 2.2.0
![Screenshot 2022-06-16 182119](https://user-images.githubusercontent.com/107638510/174119098-77df8da1-574b-47b1-8860-01ed0f87bf1a.jpg)

**Comment by Julusian** [comment]
@m-lux that looks different, and like companion crashed/died or something. Im going to need some more information or a db file to be able to begin looking into it

**Comment by m-lux** [comment]
@Julusian What information are you looking for and where can I find it?

**Comment by m-lux** [comment]
What I can say from now when starting companion it stucks on "Starting. Waiting for webserver".
When selecting a network interface it is running but the GUI says "Syncing".
I tried to start companion when logged in with a different user and it was starting and working immediately.

**Comment by hgy59** [comment]
> I tried to start companion when logged in with a different user and it was starting and working immediately.

have had the same issue https://github.com/bitfocus/companion/issues/1221#issuecomment-1158745969
probably the companion db is corrupt for the first user. The second user has a different profile with a newly created companion db that works.

**Comment by Julusian** [comment]
@m-lux a copy of your db file would be simplest. Either attach it here or email it to me at git@julusian.co.uk

@hgy59 it feels like something else has gone wrong due to the lack of completely crashing, but I could be wrong.
Some work was done a few releases ago to make it more durable, and as far as we can tell it appears to have helped and the number of occurances has almost completely dropped off. Any issue I see now with companion not opening properly is usually some unexpected data in the file, which we are working on handling better but it is taking time

**Comment by hgy59** [comment]
@Julusian y're right. With a db filled with zeros the sync doesn't show any progress, but here the progress stops at a certain level.

**Comment by Julusian** [comment]
The latest beta is doing better at discarding the corrupt files. It was handling a corrupt db fine if there was a valid db.bak, but if they were both corrupt or db.bak didnt exist it would throw an error and get stuck. It should now show an error dialog and then start with a blank config.

So it sounds like both db and db.bak got corrupt which is interesting. Actually rather concerning, as those two files were likely written many seconds (or longer) apart, so for them to have both corrupted on power loss is bad...

**Comment by tipuraneo** [comment]
I granted internet access to the pi and restarted the update procedure with `companion-update`. Update was successful. Now I am on 2.2.2+4454-be663609.
