### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by perrykoenig** [bitfocus/companion#2047]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I launch the new version of Companion (I believe that it is 2.2.2) and as soon as it launches, I lose connection from my 4ME Panel to the Constellation 8k frame.

Not sure what would be causing this but it was working fine up until I updated to 2.2.2. 

Thanks ahead of time.

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by Julusian** [comment]
I would guess that you have too many clients connected to the atem. Perhaps by updating/restarting companion you have some dead connections stuck. Try power cycling the atem, it may help.

What version did you update from? 2.2.1 or older? The atem module did not change between 2.2.1 and 2.2.2, so if you did that jump then it cant be something new in companion.

I dont think this is companion at fault, as there have not been other reports of this and your setup is pretty common. It very much sounds like something with your environment is causing it to misbehave like this.
