### ISSUE TITLE
Can't change surface page by index after upgrade to 4489 [BUG]

### ISSUE THREAD

**Issue by jsnyder886** [bitfocus/companion#2051]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After upgrade to 4489 which included a fix to the issue where setting a surface to a page by SN wasn't working, I can no longer set a surface to a page by index number.  Reverting to my previously known good release immediately corrected the issue.  As a positive, the fix for the surface by SN issue does appear to have worked, albeit with unintended consequences to the noted process.

### Environment (please complete the following information)

```markdown
Windows 11
Chrome latest release
```

**Comment by Julusian** [comment]
What build was it last working for you in?

**Comment by jsnyder886** [comment]
It had been a while since I last updated.. 4184

**Comment by Julusian** [comment]
Fixed in 4495 (b719b38ac08d9403bad570dcdab27073fc5d6fec)

This looks to have been broken by #2009

**Comment by DeeJayMX** [comment]
Always broken in 2.3.0 (2.3.0+4498-beta-bd1c8aa2)
Thanks
