### ISSUE TITLE
[BUG] "Set surface to page" has no effect from triggers

### ISSUE THREAD

**Issue by thirtythreeforty** [bitfocus/companion#2052]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A trigger which attempts to set the current page in response to a "trigger" variable AND some other gating action, fails to change the current page.  The trigger does trigger and other actions from the trigger do take effect.

No choice of the "surface/controller" setting has any effect.

(The goal here is to cause a button to change pages to a page determined by the state of a plugin.)

### Steps To Reproduce

Create a trigger with an action that sets the current page, then click "Test action":

![Screen Shot 2022-06-19 at 11 45 51 AM](https://user-images.githubusercontent.com/3952613/174491609-67fbab65-b284-476f-8d12-f65c134e13e5.png)

### Expected Behavior

The controller's current page should change.

### Environment (please complete the following information)

```markdown
- OS: macOS 10.15.7
- Browser: Chrome 102.0.5005.115
- Companion Version: 2.2.2
```

**Comment by Julusian** [comment]
Yes, the "Set surface with s/n to page" is known to be broken in 2.2.1 and 2.2.2.
Either update to the betas where it is fixed or use the "Set surface with index to page" action

**Comment by thirtythreeforty** [comment]
Nice, thank you for the workaround!
