### ISSUE TITLE
[BUG] satellite api not handling socket breakage/closing well

### ISSUE THREAD

**Issue by alex-Arc** [bitfocus/companion#2054]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Trying to remove a device results in an error return message

satellite device in companion
![image](https://user-images.githubusercontent.com/19875125/174998645-cb249500-9349-4c4b-9f86-2cfb7bab9a93.png)

remove message (i have tried with and without quotes)
![image](https://user-images.githubusercontent.com/19875125/174998852-53ad2e4b-decb-44dd-acf4-05d23bc0e965.png)

response from companion
![image](https://user-images.githubusercontent.com/19875125/174999068-b820b592-1ef0-4890-a13e-4ba5547b4e6c.png)

### Steps To Reproduce

1. add a device with `ADD-DEVICE DEVICEID=5534 PRODUCT_NAME="test" KEYS_TOTAL=4 KEYS_PER_ROW=4 BITMAPS=0 COLORS=1 TEXT=0\n`
2. try to remove it with `REMOVE-DEVICE DEVICEID=5534\n`

### Expected Behavior

The device should be removed from companion and a `REMOVE-DEVICE OK DEVICEID=5534\n` sent back

### Environment (please complete the following information)

```markdown
- OS: Windows 10
- Browser: Chrome
- Companion Version: 2.2.2 (2.2.2+4454-v2-2.2-be663609)
```

**Comment by alex-Arc** [comment]
Hey @Julusian 
The problem seams to stem from companion not releasing the tcp socket when the device disconnects abruptly.
so every time I upload new code to my mcu it hard resets and looses the tcp socket, companion then wont let me add the device because it already exists and I can't remove it from a separate socket.

When my device is connected 1:1 to the companion server the socket is released correctly, because the nic goes offline and the socket ceases to exist.
But when the connection is through something like a switch, the nic stays online and the socket is not terminated.

There needs to be a check on the socket state somewhere.

it seams this:
https://github.com/bitfocus/companion/blob/7bf2464b6d46901cac12c91b093aa943dec50d7a/lib/satellite/satellite_server.js#L110
is not enough to catch a device that goes offline without announcing it-

Maybe there should also be a [timeout](https://nodejs.org/api/net.html#event-timeout) listener?

**Comment by Julusian** [comment]
Right ok.
I have observed some weirdness around this myself, but I havent been able to reliably reproduce the issue.
I think I have found it to fix itself after a while, but I am not certain.

Could you help with either a fix or an STR for this? I do have an arduino uno and ethernet shield somewhere if that is easiest

**Comment by Julusian** [comment]
I managed to reproduce this by running companion-satellite on a machine and physically disconnecting its network cable.
Setting a timeout on the connection solved it for me, as the client is expected to 'ping' the server frequently over the socket to check for connection loss.

For now I have gone with a generous timeout of 5s, but I am open to changing this if needed

https://github.com/bitfocus/companion/commit/385edd3271ba57314ecc90c416d1f5dafab37628
