### ISSUE TITLE
[BUG] i cant connect to the emulator site with my iphone/ipad/android

### ISSUE THREAD

**Issue by pexayt** [bitfocus/companion#2059]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

My pc is connected to the ethernet/lan via cable but my iphone, ipad and android phone is connected to the internet via WLAN.
If i try to connect to the emulator or mobile adress (http://myip:8000/emulator) there is an error, that this website is not available.
Please help

### Steps To Reproduce

try to connect to the emulator page

### Environment (please complete the following information)

```markdown
- OS: Windows 10 / iOS / Android
- Browser: Brave / Safari / Firefox
- Companion Version: newest
```

**Comment by Julusian** [comment]
Are you also using http://myip:8000/ to access the ui from your computer and it works?

**Comment by pexayt** [comment]
I use the Port 8888 now but yes from my computer I can access. I got a workaround by changing my Androids Port to 8888 too but I have to to this everytime I want to connect to the emulator page. But I want to use the emulator on my iPad and I can’t change the Port on my iPad. I think it’s the problem, that my mobile devices are in the WLAN and my computer is in the LAN. I’m thankful for every help

**Comment by Julusian** [comment]
it will be the same port number from everything.
Why do you have to `have to to this everytime I want to connect to the emulator page`? Couldnt you update the link/bookmark you are using?
Or, you could change companion to run on port 8000.

**Comment by pexayt** [comment]
So.. My problem is, that when i open the adress (http://127.0.0.1:8888) on my mobile devices, there is an error in the browser, that says that there is no website like this. You understand? I cant connect to the website for the emulator or tablet3 website

**Comment by Julusian** [comment]
`127.0.0.1` means the current device, you need to use a real ip address for it to work. but arent you already doing that as it works when you change the port?

**Comment by pexayt** [comment]
Yeah i changed the port on my android (i have to do it everytime i start the phone) and then it works. But i want to do it on my iPad and on my iPad i cant change the port and i want to do it right with the ip adress then. So does it work with ip adress, if my pc is in lan and my iPad is in WLAN?

**Comment by Julusian** [comment]
Why do you have to change it everytime you start the phone?
And why cant you change the port on the ipad? 

If the lan and wlan form the same network then yes it should work. but it very much depends on how your network is setup

**Comment by pexayt** [comment]
for clearance: 

I have to execute this command in adb: "adb reverse tcp:8888 tcp:8888" to change the port. When i dont execute this command from my windows computer, i can't get on the website on my android. But when i execute this command i can. So i have to execute it everytime my pc restarts or the phone.

I dont know if i really change the port with this command but it works.

I can't change the port, because i dont know how. 

I think there were some misunderstandings because I don't know English that well. I thought I must have the same port as I have in the address. so the numbers after the :. So that my mobile device must have the same port to access this website, because now if I take my iPad and enter the address "http://127.0.0.1:8888/tablet3" it doesn't work.

My LAN is plugged into the router that also outputs the wifi

What my goal is:

Connect my iPad to the website, but when I enter the address in the Safari browser, Chrome or other browser always comes an error message that this website does not exist.

**Comment by Julusian** [comment]
Closing as I believe this isnt something wrong with companion
