### ISSUE TITLE
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"] [BUG]

### ISSUE THREAD

**Issue by cameronaffleck** [bitfocus/companion#2060]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Cannot import or export any files on 2.2.2, presented with following error... Windows 10, Microsoft Edge

TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]

![WhatsApp Image 2022-07-04 at 1 44 42 PM](https://user-images.githubusercontent.com/64044013/177163589-af3b2ef0-62f4-44ea-a657-32a889aa2b35.jpeg)

### Steps To Reproduce

1. Go to Export (or import)
2. Click on Export (or import)
3. Error presents itself

### Expected Behavior

Should be able to open file explorer to import / export.

### Environment (please complete the following information)

```markdown
- OS: Windows 10
- Browser: Microsoft Edge
- Companion Version: 2.2.2-be663609-4454
```

**Comment by Julusian** [comment]
what is the name of your computer? we use that in the export filename which could cause this if it has unusual characters in it

**Comment by cameronaffleck** [comment]
Let me guess.. you don't support umlaut's? 😂 That'll be it

**Comment by Julusian** [comment]
This is something we should fix. it would be easy to make a safe version of the hostname

**Comment by Julusian** [comment]
Hopefully this works better now
