### ISSUE TITLE
Unable to import image files or configs

### ISSUE THREAD

**Issue by cameronaffleck** [bitfocus/companion#2063]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Unable to import Image files or configuration files.

image files appear to be blank (or unimported), and configuration files do not show the usual screen after import. #

### Steps To Reproduce

Occurs whenever importing image for button or configuration for individual pages or whole configs.

### Expected Behavior

To be able to import files

### Environment (please complete the following information)

```markdown
- OS: Windows 10
- Browser: Microsoft edge
- Companion Version: 2.2.2-be663609-4454
```

**Comment by Julusian** [comment]
Can you provide some images and configuration files which are not working for you?

**Comment by Julusian** [comment]
Closing this as there isnt enough details to be able to reproduce the issue.
If some examples are provided it can be reopened
