### ISSUE TITLE
Allow Variables to be changed over udp/tcp etc.

### ISSUE THREAD

**Issue by ISSac25E** [bitfocus/companion#2069]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Change the current value of a **custom** variable declared in Companion via UDP, TCP and OSC, similar to how 'bank-press' and 'style bank' works

Or even through an html request, just some way to update custom variables over network

### Usecases

- This would allow for simple custom-made iot devices to "communicate" with companion without needing a separate module to be created. This would allow the device to update its state(of whatever its doing) to Companion
- One example is a DMX-Arduino. The Arduino would be able to update simple DMX states over UDP by updating a custom variable in Companion. This Variable could later be used to change the color of a button on Companion to act as a "Tally" of sorts.

**Comment by Julusian** [comment]
#2056
