### ISSUE TITLE
[BUG]Remote Access removes Preset Actions 

### ISSUE THREAD

**Issue by E2SLLC** [bitfocus/companion#2070]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When accessing the computer running Companion remotely over the network (using the IP ADDRESS:PORT protocol), I noticed that the Barco Event Master module lost all the built in Preset actions except for the Basics button.  I had to quit and restart Companion to get the other preset actions back.

### Environment (please complete the following information)

```markdown
- OS: MacOS 12.4 Monterey (Companion Machine); MacOS 11.6.2 Big Sur (remote admin computer)
- Browser: Safari 15.5/15.2
- Companion Version: 2.2.3
```

**Comment by Julusian** [comment]
I cant explain what happened here. Companion doesnt treat local and remote admin ui sessions any differently.
Perhaps this is a weird edge case in preset handling that happened to coincide with the remote access?
Or it could be a bug in the barco event master module?

Is this reproducable or does it only happen very rarely?

**Comment by Julusian** [comment]
I dont have enough information to work from here currently.
I mostly use my companion remotely, and have not had any presets disappear, so it could be the module at fault, or some one time glitch?

If someone can provide some steps to reproduce this then I can reopen and take a look
