### ISSUE TITLE
Add "internal variables " about surfaces and pages.

### ISSUE THREAD

**Issue by houtacheng** [bitfocus/companion#2071]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Sorry about my poor English.

I need to know the value of what surfaces and the current page.

eg.

surfaces 1 page 1
surfaces 2 page 3

### Usecases

feedback value to change the button color.
<img width="1147" alt="Snipaste_2022-07-13_23-18-45" src="https://user-images.githubusercontent.com/25832189/178883879-91cfa204-c1d9-426e-a0d0-b01c2239e65f.png">

https://user-images.githubusercontent.com/25832189/178883580-f0a53f5f-ccb6-43ed-88c4-55399562f7e0.mp4

**Comment by n9yty** [comment]
+1 - need to be able to know what page is current so I can set a variable with it in an expression to dynamically calculate which page to jump to.

Use case: System returns a variety of values, but the number returned is not consistent. They are spread out over pages, but I would like to press a button to step through them, ignoring the blank ones. It seems this could be done with a variable telling how many were returned, knowing how many fit on the current device size (hardcoded in the expression unfortunately), then deciding how many pages that would be and jumping to either the next page or back to the start of the page group if there were no more pages with values.

**Comment by Julusian** [comment]
This is implemented in the betas now
