### ISSUE TITLE
Input validation broken on "add connection" search box [BUG]

### ISSUE THREAD

**Issue by HaxNobody** [bitfocus/companion#2075]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Entering certain characters into the search box on the Connections page under "Add Connection" causes the GUI to render an error as follows:

`Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=SyntaxError%3A%20Invalid%20regular%20expression%3A%20%2F(%2F%3A%20Unterminated%20group for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

The characters I have tested and identified so far are as follows:

` \ [ * ( ) +`

Also, the caret symbol ^ does nothing, no search and no error.

### Steps To Reproduce

Go to Connections page http://127.0.0.1:8888/connections
Find search field under "Add Connection" and select it
Type any combination of characters including the ones that are reported to not validate properly, I.E. \ [ * ( ) + ^
Observe error message

### Expected Behavior

The invalid input should not cause a fatal error that resets the search field, especially with such common characters.

### Environment (please complete the following information)

```markdown
- OS: Windows 10 x86-64 and Windows 11 arm64
- Browser: Chrome and Edge
- Companion Version: 2.2.3
```

### Additional context

I have not tested any other symbols that may also be affected.

**Comment by Julusian** [comment]
I cant remember if it was intentional that this filter should allow for regexes, but I have left that in place for now.
There was error handling to handle this, but it wasnt stringifying the error before outputting it, which was causing the crash

This is fixed in the latest beta
