### ISSUE TITLE
[BUG] Cannot edit any button

### ISSUE THREAD

**Issue by RuryBild** [bitfocus/companion#2077]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When clicking on any "Regular Button" or empty Bank I get:

```
Something went wrong:

Cannot read properties of null (reading 'split')
```

Clicking "Try Again" gives the same error.
If the Bank is empty, clicking "Try Again" it goes to the "Add Button" view, but then if I add a "Regular Button", I get the same issue.
Adding a "Page Up/Down" button works fine.

Exporting config to another machine is fine
Re-installed Companion - no help
Re-imported Config - no help

### Steps To Reproduce

I'm afraid I don't know what set it off.

### Environment (please complete the following information)

```markdown
- OS: Windows 11
- Browser: Version 103.0.5060.134 (Official Build) (64-bit)
- Companion Version: [2.2.3 (2.2.3+4469-v2-2.3-82b174db)](https://bitfocus.io/companion/)
```

### Additional context

Using Blackmagic Hyperdeck Module only
Also using custom variables

**Comment by RuryBild** [comment]
Got fixed, had set my GUI NIC to an ethernet port. As soon as I switched to localhost, it started working.

**Comment by Julusian** [comment]
I dont see how that would have any effect.
I have pushed a pre-emptive fix that may fix the underlying problem, but without knowing the cause it is hard to figure out the fix

**Comment by RuryBild** [comment]
I still occasionally get the issue when I have been adding or removing a bunch of connections, but a refresh of the GUI always fixed it (while displaying over localhost).
If there's any diagnostic info that would help, just let me know and I can shoot some over.
