### ISSUE TITLE
More font sizes for buttons

### ISSUE THREAD

**Issue by Byberg33** [bitfocus/companion#2078]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

A wider range of font sizes especially for smaller sizes is needed. There are many times when I find myself looking for something a bit larger than 7pt but not as big as 14pt. Something in between would be nice to have. I suggest 10pt.

### Usecases

I set up very large companion projects that are later used by many others. Making the buttons clear and look tidy is a big part of making it easy to follow and understand the layout. Many times 10pt or maybe 9pt would have been perfect for making the button readable by still descriptive.

**Comment by dnmeid** [comment]
The way we render text on buttons is very outdated. The whole graphics part has to be reworked to be vector based. At the moment all chars are small bitmap images encoded in a special way. Adding a font size is quite of a big task. I don't think it will happen soon.

**Comment by staticlondon** [comment]
This would be a good improvement. Bold text would also be great.

Would a move to vector based buttons also improve the image quality on the web button interface?

**Comment by dnmeid** [comment]
Overhaul of the graphics generation is now in the roadmap for 3.1 or 3.2. Vector based means that there will be a canvas for drawing text from a real font. So it will have any font size and also all glyphs and unicode characters. Rendering will then be done to the native raster of the button, so yes, this will drastically improve the quality on web buttons.
As always: this is mostly a voluntary project, so please understand if a special feature is not implemented fast. But usually you can speed up things by sponsoring a developer to do it. ;-)

**Comment by dnmeid** [comment]
Coming soon
<img width="842" alt="image" src="https://github.com/bitfocus/companion/assets/8548888/5ea3d80b-53ac-4552-8f6d-ee79890f41fb">

**Comment by staticlondon** [comment]
> Coming soon <img alt="image" width="842" src="https://user-images.githubusercontent.com/8548888/243097013-5ea3d80b-53ac-4552-8f6d-ee79890f41fb.png">

This looks fantastic, thanks for your work on this.

**Comment by Byberg33** [comment]
Looks fantastic! Can't wait for the build

**Comment by JRzen** [comment]
Any chance that we'll be able to mix font sizes?
So have a label that says "AUTO" across the top, with smaller letters "manual" underneath to show the alternative...

That would let the label say what the current state is, and have an indication of what it would change to - feels clunky having a label that either says what you don't have at the moment or one that says what you won't get it you press it.

**Comment by Julusian** [comment]
More font sizes is now included in 3.2 (current beta builds)

**Comment by jgclark** [comment]
I'm failing to see the new font sizes on 3.2.0 stable or 3.3.0 betas. Nor can I see any setting to turn this newer behaviour on. What am I missing?

**Comment by Julusian** [comment]
@jgclark the font size field allows you to type any number then press enter to apply it

**Comment by jgclark** [comment]
Aha, thanks.
However, the usual conventions for list-but-you-can-type aren't followed.
And I've already spotted a bug.
Where should I file these comments?
