### ISSUE TITLE
cancel running delayed actions ("panic-stop")

### ISSUE THREAD

**Issue by joephi** [bitfocus/companion#208]
**Describe the feature**
An assignable action, that cancels any delayed action that had been triggered but wasn't carried out yet. (e.g. stop all internal timers of delayed actions and suppress their start)

**Is this platform dependent (windows, mac, ..)?**
no

**If documentation is required to implement, do you know where to find it?**
n/a

**Usecases**
Imagine a Button with a Video-play command (e.g. "mitti: play"), a "pds: TAKE" and a second "pds: TAKE"  to come back from that video into a gfx-source. So that action would be delayed e.g. by 90.000 ms for a 1:30m intro Video.
If you now press that button "accidentally" as an operator - you can of course "panic-stop" your video. But the delayed actions will still be carried out later (e.g. switch to the specified source)
Therefore it would be beneficial, to have an assignable "action" that can cancel any still delayed actions before there are carried out

**Comment by haakonnessjoen** [comment]
I am thinking about this. Maybe an action that has these options: "Abort all delayed actions", "only on same page" or "on bank x.x"

**Comment by joephi** [comment]
I would think that a "stop all delayed actions" would suffice
If I'd long for more - than it would be to see every "running" action somewhere and stop them individually ...
but (form an operator point of view) I don't see a huge benefit in "per page" / or "per bank"

**Comment by willosof** [comment]
Relates to #229 :)

**Comment by willosof** [comment]
This will be really easy to implement in the internal module.

**Comment by willosof** [comment]
fixed in f327e9437ec380d3f568a6b2f639137a5b9ff9b5 and 5cc3afcc32640474654b78c361e0486fd34c0132
