### ISSUE TITLE
[BUG] internal: Enable or disable trigger no longer works after MacOS sleep/wake cycle

### ISSUE THREAD

**Issue by jfleckc** [bitfocus/companion#2082]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Creating a button with an "internal: Enable or disable trigger" action correctly enables, disables, or toggles a trigger as expected. However, upon putting my MacBook Pro to sleep, and waking from sleep cycle, enabling, disabling, and toggling a trigger fails to work for all triggers.

### Steps To Reproduce

In the Triggers tab, create Trigger with a desired behaviour. Ensure this Trigger is enabled.
In the Buttons tab, create a Regular Button
Add a Press Action: "internal: Enable or disable trigger"
Choose the Trigger you created earlier.
Choose "No" for the Enable dropdown.
Switch to the Triggers tab in Companion
Use Stream Deck or Emulator to press the button, and observe the state change.
Reset the trigger to enabled.
Put MacBook to sleep.
Wake MacBook from sleep.
Whilst observing Triggers tab, test the button you created earlier - Trigger does not successfully enable.

### Environment (please complete the following information)

```markdown
- OS: MacOS 12.5
- Browser: Chrome 103.0.5060.134
- Companion Version: 2.3.0+4578-beta-7a96ef49
```

**Comment by davidjoshuaford** [comment]
I have found the same bug. The "Enable or Disable Trigger" action does not work upon Companion startup. The button action only works after I manually go to the Trigger page and Enable and then Disable the trigger.

Tested on Mac M1 Max, OS v12.5, Companion beta build v2.3.0-4604.

**Comment by Julusian** [comment]
fixed!
