### ISSUE TITLE
[BUG] v2.2 after hybernation Atem control lost for control and after a internal command timeout but feedback from atem is still available 

### ISSUE THREAD

**Issue by arne182** [bitfocus/companion#2086]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

this is in Windows 10 with a StreamDeck and ATEM Mini Pro. After hybernation the connection is lost and the button presses do not work anymore with the Atem until the connection is reset to the Atem. Then after a few minutes it loses connection again and in some cases until the whole companion is reset. This was not the case in v2.1 
As we do shut down our streaming PC but set it in hybernation to preserve settings but then we expect that the connections correctly reconnect after the PC wakes up.

### Steps To Reproduce

Connect atem
Hybernate PC
Wake up PC
Attempt to control Atem for a few minutes

### Expected Behavior

Just work. Or at give a warning that the commands are not forwarded. The button presses and connection do not give an indication that it is not working

### Environment (please complete the following information)

```markdown
- OS: Windows 10 
- Browser: Chrome 94
- Companion Version: 2.2
```

**Comment by Julusian** [comment]
What does the log tab in companion show?
I have given this a try and it is reconnecting as expected

**Comment by arne182** [comment]
Will give this a look at when I am in the church studio next week

**Comment by Julusian** [comment]
Do other modules remain working? If so what are they?

**Comment by arne182** [comment]
h2r-graphicsHere To Record: Working
atemBlackmagic Design: Not working
h2r-graphicsHere To Record: Not in use
vlcVideoLAN: working
artnetGeneric: working
oscGeneric: working
Will get the log later to day after our live stream

**Comment by arne182** [comment]
22.08.14 11:35:09 device(CL08K1A02623): Button 2.2 released
22.08.14 11:35:09 device(CL08K1A02623): Button 2.2 pressed
22.08.14 11:35:09 device(CL08K1A02623): Button 2.3 released
22.08.14 11:35:09 device(CL08K1A02623): Button 2.3 pressed
22.08.14 11:35:08 device(CL08K1A02623): Button 2.2 released
22.08.14 11:35:08 device(CL08K1A02623): Button 2.2 pressed
22.08.14 11:35:08 device(CL08K1A02623): Button 2.10 released
22.08.14 11:35:08 device(CL08K1A02623): Button 2.10 pressed (Theses ones do not)
22.08.14 11:34:23 instance(Songbeamer osc): Bringing back instance from sleep
22.08.14 11:34:23 instance(artnet): Bringing back instance from sleep
22.08.14 11:34:23 instance(vlc): Bringing back instance from sleep
22.08.14 11:34:23 instance(h2r-graphics2): Bringing back instance from sleep
22.08.14 11:34:22 instance(atem): Bringing back instance from sleep
22.08.14 11:34:22 instance(h2r-graphics): Bringing back instance from sleep
22.08.14 11:34:22 instance(internal): Bringing back instance from sleep
22.08.14 11:25:07 device(CL08K1A02623): Button 2.20 released
22.08.14 11:25:07 device(CL08K1A02623): Button 2.20 pressed (These ones work)

**Comment by arne182** [comment]
![image](https://user-images.githubusercontent.com/844102/184531140-7fd542ba-4f76-4760-8d47-eb4edfc8ef6d.png)
The Connection is there but it only shows 
22.08.14 11:35:08 device(CL08K1A02623): Button 2.10 pressed
22.08.14 11:34:51 instance(h2r-graphics): 192.168.0.20:8181/h2r-graphics/timer, [{"type":"s","value":"show"}]
22.08.14 11:34:51 instance(h2r-graphics): 192.168.0.20:8181/h2r-graphics/timer-custom-down-time-of-day, [{"type":"s","value":"10:00"}]
22.08.14 11:34:23 instance(atem): Connected to a ATEM Mini Pro
22.08.14 11:34:23 instance(vlc): Connected to 192.168.0.20:8080
22.08.14 11:34:23 instance(atem): Lost connection
22.08.14 11:34:23 instance(Songbeamer osc): Bringing back instance from sleep
22.08.14 11:34:23 instance(artnet): Bringing back instance from sleep
22.08.14 11:34:23 instance(vlc): Bringing back instance from sleep
22.08.14 11:34:23 instance(h2r-graphics2): Bringing back instance from sleep
22.08.14 11:34:22 instance(atem): Bringing back instance from sleep
22.08.14 11:34:22 instance(h2r-graphics): Bringing back instance from sleep
22.08.14 11:34:22 instance(internal): Bringing back instance from sleep
22.08.14 11:34:22 system(power): Resuming
22.08.14 11:29:35 instance(atem): Lost connection
22.08.14 11:29:35 system(power): Suspending
22.08.14 11:25:07 device(CL08K1A02623): Button 2.20 released

![image](https://user-images.githubusercontent.com/844102/184531175-5a2bc180-a529-4bd5-a2f3-1c7f00ba974e.png)

Button feedback correctly
![image](https://user-images.githubusercontent.com/844102/184531193-7d74ef3c-394c-4f94-9238-5687f1a015ff.png)
But the buttons in Companion does not change the atem state and there is no other warnings in the log
![image](https://user-images.githubusercontent.com/844102/184531252-402096a9-f038-417c-8b79-c7f3f95579f3.png)

**Comment by arne182** [comment]
Looks like the connection is lost also after this 
22.08.14 11:46:15 instance(internal): Shell command failed. Guru meditation: {"killed":true,"code":null,"signal":"SIGTERM","cmd":"C:\\Temp\\m.exe"}
Error message. Which causes the same issue like after hybernation

**Comment by arne182** [comment]
After increasing the timeout time of the internal command the atem does works and does not disconnect. 

What is also strange to see is the live stream timer button flickers between 00:00 and and the actual time.

**Comment by arne182** [comment]
> What does the log tab in companion show? I have given this a try and it is reconnecting as expected
@Julusian 
Are you able to test this again to see if the internal command timeout is the cause of the atem not working?

**Comment by Julusian** [comment]
> Looks like the connection is lost also after this
22.08.14 11:46:15 instance(internal): Shell command failed. Guru meditation: {"killed":true,"code":null,"signal":"SIGTERM","cmd":"C:\Temp\m.exe"}
Error message. Which causes the same issue like after hybernation

Is that an action being run on another button? And after running it the atem connection is half broken?

**Comment by arne182** [comment]
Yes. It is a custom set of actions that include both atem and internal shell command and other Atem commands in one button press.

**Comment by Julusian** [comment]
Are you able to check if this is any better in 3.0?

**Comment by Julusian** [comment]
Hopefully this is better in 3.0. The way we run modules has changed, and by consequence so has the way we stop and start them during sleep/hibernation, so it is likely that this behaves better now.
If not, comment here and this can be reopened
