### ISSUE TITLE
Bonjour discovery helper

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion#2087]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Many devices (blackmagic, chromecast, dante) use bonjour(mdns) to announce themselves to the network to allow for auto discovery.

The bmd-atem module has had mdns support in it for a while to be able to suggest ip addresses that can be added.  
In 2.3 and earlier, this has been fine as it has created a single mdns browser shared across all instances. But in 3.0, due to the threading changes this will end up with one browser per instance.

Having many bonjour browsers distributed like this will not be very efficient. It would be better if there was a central bonjour helper run by companion, that instances could use for doing discovery. This would also less us be more intelligent with it, such as having a `bonjour-device` field type for the configuration, to allow for live updating suggestions while the config panel is open.

### Usecases

Various modules could make use of this:
* bmd-atem (and every other bmd probably)

Probably others, if there is a good example of how to check and get it setup.

This could also be used as the basis of discovering other companion installations visible on the network.

**Comment by krocheck** [comment]
Shure products have mdns.

**Comment by Julusian** [comment]
This is possible in 3.2 (current beta builds)

https://github.com/bitfocus/companion-module-base/wiki/Bonjour-device-discovery
