### ISSUE TITLE
[BUG] Feedback based on custom variable value set through shell command not working

### ISSUE THREAD

**Issue by commputethis** [bitfocus/companion#2089]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a custom variable whose value is being set from the output of a shell command.  I have feedback setup to change the color of the button based on the value of the variable being set to true or false.  If it is true, then the button should be green.  If it is false, the button should be red.  If I manually set the current value to true, then the button turns green.  If I manually set the current value to false, the button turns red.  However, if I run the action to set the value, the button color doesn't change.  I have verified there aren't extra characters in the value set by the command.

In this screenshot, you can see the variable has a current value of "true" and it was set by running a shell command (can't see that part, but it is the case).
![custom_variable](https://user-images.githubusercontent.com/17625274/184515375-e361b6e3-dd7a-483a-b6f4-05d7318fb261.png)

In this screenshot, you can see we are looking at the value of the variable equal to true.
![feedback equal true](https://user-images.githubusercontent.com/17625274/184515412-f6cc9d50-0333-45cc-8e21-0a673aa1a4b0.png)

In this screenshot, you can see we are looking at the value of the variable not equal to true.
![Screenshot from 2022-08-13 17-33-57](https://user-images.githubusercontent.com/17625274/184515448-41c0888c-d955-4bdc-bd78-b85cc69162da.png)

Again, if I type true into the current value of the variable manually, the feedback works as it should.  It is only when having it set through an action or trigger running a shell command.  I even tried copying the value set by the command and pasting it into the value we are looking for and it still doesn't work.  I just can't wrap my head around the issue.

### Steps To Reproduce

1. Create & run shell command action ```echo true``` and have the target variable be a custom variable.
2. Add feedback to a button to change the color of a button based on the value of that custom variable being equal to true.

### Expected Behavior

Expected behavior is that the button would turn the color specified.

### Environment (please complete the following information)

```markdown
- OS: MacOS Monterey
- Browser: Google Chrome
- Companion Version: 2.2.3
```

**Comment by commputethis** [comment]
I tried using other values (like tru, 1, and 2) with the same result.  I wanted to make sure there wasn't an issue using true and false.

**Comment by webflo-dev** [comment]
If your script ouput is 1 or 0, you should use ">" or "<" as operation value. Otherwise it won't work.

**Comment by commputethis** [comment]
The output is "true"

**Comment by Julusian** [comment]
Fixed in build 4653.
There was an newline being left at the end of the output, making string comparisons to be impossible to do
