### ISSUE TITLE
[BUG] Inconsistent Time Zone

### ISSUE THREAD

**Issue by dillwishlist** [bitfocus/companion#2093]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The variable $(internal:date_iso) returns the date in UTC, while $(internal:time_hm) returns the local time.  This will result in timestamps being off by a day if the local time is a different day than UTC.

For example, If you are in a UTC-5 timezone and local time is 22:45 on 8/17/2022, UTC would be 03:45 on 8/18/2022.  However the variables would read as follows:

```
Incorrect:
$(internal:date_iso) 2022-08-18
$(internal:time_hm) 22:45

```
```
Variables should read:
$(internal:date_iso) 2022-08-17
$(internal:time_hm) 22:45

```
Thanks

### Steps To Reproduce

This bug exists when the UTC date is different than your local date.  Please make sure your local date is different than UTC when evaluating this bug.

Go to Buttons, Variables, Internal.  Scroll down to see $(internal:date_iso) and $(internal:time_hms).

### Expected Behavior

Variables should read:
$(internal:date_iso) 2022-08-17
$(internal:time_hm) 22:45

### Environment (please complete the following information)

```markdown
- OS: MacOS 11.6.5 (Big Sur)
- Browser: Safari 15.6
- Companion Version: 2.2.3(2.2.3+4469-v2-2.3-82b174db)
```

**Comment by Julusian** [comment]
Fixed in beta 4671
