### ISSUE TITLE
[BUG] Companion still locks up after being idle

### ISSUE THREAD

**Issue by EnergeticStick** [bitfocus/companion#2098]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am aware that someone reported this bug a while ago, but it was closed even though the issue was never truly fixed.  Much like the first person to report the bug, kd8ssq, we use companion 3 times a week and leave our computers running 24/7.  It only takes an hour or two for Companion to lock up.  A few days ago I was using Companion for an unusually long period, and I had to restart it 4 or 5 times to keep it functional throughout the roughly 6-hour period I was using it.

We're only using it to control a PTZOptics camera with a Stream Deck, nothing else. (If Elgato would just allow you to run actions on both button press and release in their software, I wouldn't even need to use Companion, but that's another story)

I read the entire thread from the other report and none of it helps me.  The log is always empty since there are no constantly failing connections as all of our devices are on 24/7.

I'm pretty sure there's nothing I can do.  I even tried circumventing the issue by setting up Task Scheduler to restart Companion once a day, but that was before I realized it locks up after just a couple of hours, not days.

The bug just needs to be fixed.

### Steps To Reproduce

Start Companion and leave it alone for a few hours.

### Expected Behavior

Companion to be responsive after being inactive for several days. (Copied from the other report as there's no need to change it)

### Environment (please complete the following information)

```markdown
- OS:Windows 10
- Browser:Chrome 104.0.5112.102
- Companion Version:2.3.0+4608-v2-3.0-2994a6d0
```

**Comment by EnergeticStick** [comment]
so is there anything I can do about it or I just have to wait for 3.0?

**Comment by Julusian** [comment]
No, this is something that can and should be fixed soon, but will need some attention from someone who can debug and test with a ptzoptics device. It might be worth opening an issue at https://github.com/bitfocus/companion-module-ptzoptics-visca/issues to try and get the attention of the module developers. (Perhaps this is related to https://github.com/bitfocus/companion-module-ptzoptics-visca/issues/20?)

The generic-http might be able to do it? It cant open a page and do something though, but it might be possible to figure out the single request to make to do something?

**Comment by EnergeticStick** [comment]
Agh the Generic-HTTP would work if I could request commands on both button press AND release.  In its current state, it's no different than the Stream Deck software's "Website" action that I can't use for that reason.  Thanks for the help, though!  I'll post something in the PTZOptics area.
