### ISSUE TITLE
Set current surface to page X (internal action)

### ISSUE THREAD

**Issue by airbenich** [bitfocus/companion#2100]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

When using multiple surfaces, it would be good to have the following action:
`internal: Set current surface to page`

This function does the same as the action
`internal: Set surface with index to page`
but can detect itself from with surface the command came and selects the index by itself.

### Usecases

When using more than one surface at one computer for multiple concurrent users, you need this feature so that each user with its own surface navigates on the correct surface.

**Comment by Julusian** [comment]
You are looking for the `Set surface with s/n to page` action, which allows for selecting the 'current' surface

**Comment by airbenich** [comment]
You are totally right! Sorry for missing that.

**Comment by Julusian** [comment]
No problem, I can appreciate that from the name it isnt clear that it would have an option for 'current'.
Wording of these action names is something that should definitely be reviewed

**Comment by airbenich** [comment]
Yes, a seperate action called `internal: Set current surface to page` would be something i would expect. Thank you for your quick help on that!
