### ISSUE TITLE
Go To Page Action for Current Device

### ISSUE THREAD

**Issue by quickestpastor** [bitfocus/companion#2101]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I would like a go to page action using the current device instead of device index or serial number.    

### Usecases

 I am using two stream decks simultaneously on the same computer so it would be helpful to be able to go to a specific page on either device without having to define a stream deck so I could use the same pages/buttons on either device.  If I have to define the button in the page jump function that means that action/button will only work on a specific device instead of both and I want each device to operate independently of each other.      I recognize that i could just create a unique set of pages with buttons for each device but that seams like a waste of time since i want the same pages to be available on each device.

**Comment by Julusian** [comment]
You are looking for the Set surface with s/n to page action, which allows for selecting the 'current' surface

#2100
