### ISSUE TITLE
Show Buttons Visually on Actions

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion#2102]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

It would be very helpful if Actions that reference other buttons would show the button they are pressing.

This would be for Actions such as: 

internal: Button press and release
internal: Button press
internal: Button release
internal: Button Press and Release if Variable me

ets Condition
internal: Abort actions on button
etc

Here's a mock up to show how we could very quickly visually scan button 2/12 to see that when we press the button, it will be actioning a cut to Cam1 and Mute audio:

<img width="1463" alt="Screen Shot 2022-08-24 at 4 35 32 PM" src="https://user-images.githubusercontent.com/76959770/186520773-fa1d0f23-246e-4782-9bdc-533260748fec.png">

### Usecases

The reason we need visual representation is to improve human accuracy when reviewing a stack of actions. 

When there are multiple Actions referencing various other buttons in a configuration, I have to go to each page to double check they are targeting the intended button. This slows down the configuration process, and increases the potential for human error. If the targeted button gets moved or cut, there's no immediate feedback to indicate that the action is targeting an empty or incorrect bank/button.

If we saw a preview of the button, we could scan down a list of actions and see at a glance what other buttons would be triggered, and troubleshoot any irregularities.

**Comment by Julusian** [comment]
Yeah I like the concept and think it is doable. 
As this is only useful for the 'internal' module, I think we can get away with some specific bits or assumptions for it too

**Comment by Julusian** [comment]
This will be in v3.0
![image](https://user-images.githubusercontent.com/1327476/193128028-f304f8aa-fa6f-4656-b135-000ca1421398.png)

**Comment by davidjoshuaford** [comment]
Looks great!
