### ISSUE TITLE
[BUG] USB(elgato-mini): Found device, but no access - on Raspberry Pi running companion 2.3.0 (2.3.0+4610-38a453f3)

### ISSUE THREAD

**Issue by darongreen** [bitfocus/companion#2103]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Raspberry Pi running Companion 2.3.0 (2.3.0+4610-38a453f3) gets the following error/log:

USB(elgato-mini): Found device, but no access. Please quit any other applications using the device, and try again.

This was when trying to use the Elgato Streamdeck Mini (6 button model).

I swapped to other Elgato Streamdecks (eg 48 button - XL and 15 button standard model) and these both work fine on this installation with no other changes. Also, the streamdeck mini (6 button) works fine on other companion installs (eg the latest Companion release for Windows). 

I have rescanned the USB multiple times and receive the same error.

All the software on the Pi and Companion install are up to date. Nothing else is installed on this headless Pi.

Pi OS is: Raspbian GNU/Linux 10 (buster).

### Steps To Reproduce

Install Raspberry Pi 4 with Buster OS v10
Install latest versions of Companion
Plugin Elgato Stream-deck Mini
Rescan USB port
Check Companion error log

### Environment (please complete the following information)

```markdown
- OS: Raspbian GNU/Linux 10 (buster).
- Browser: Chrome Version 104.0.5112.102 (Official Build) (64-bit)
- Companion Version: 2.3.0 (2.3.0+4610-38a453f3)
```

**Comment by Julusian** [comment]
This should be resolved by running `sudo companion-update` and follow the steps selecting the same version (2.3.0).
You likely have the new revision of the mini, and it had not been added to the `udev` rules, meaning companion wasn't allowed to access it

**Comment by darongreen** [comment]
I'm not running CompanionPi so sudo companion-update won't work.

**Comment by Julusian** [comment]
You can do the fix manually by updating the udev rules file to match https://github.com/bitfocus/companion-pi/blob/main/50-companion.rules and rebooting. It will be located inside `/etc/udev/rules.d/`

**Comment by darongreen** [comment]
That worked! Thank you

**Comment by spoelstraethan** [comment]
You can also run `sudo udevadm control --reload` after `sudo cp 50-companion.rules /etc/udev/rules.d` and then unplug and replug the Stream Deck instead of rebooting.
