### ISSUE TITLE
Network Error with more than 10 Clients 

### ISSUE THREAD

**Issue by ChrisSmartregie** [bitfocus/companion#2106]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We running 12 Windows Surfaces with Companion at the moment. We use them to remote control mix buses in a Yamaha Rivage PM5 (Yamaha-Rcp Module). Our big problem at the moment is. We can only use 10 of them the other 2 have status error. The weird thing, it’s not always the same Surface. Sometimes it’s 6&9 sometimes 1&12 and so on. We already used different Cat cables, different adapters, different switch and a different vlan. The Log is displaying a „Network Error: Write Econnaborted“. 
Is there by any chance somebody who can help us out fixing this weird problem 

### Environment (please complete the following information)

```markdown
- OS:Win 10
- Browser: Chrome
- Companion Version: 2.2.3
```

**Comment by Julusian** [comment]
Based on the facebook post https://www.facebook.com/groups/companion/permalink/3201054140112914/, this is an issue with the yamaha only supporting up to 10 connections.
I originally read this as 10 web clients trying to connect to the one companion instance.

As such, there isnt anything that we can fix here, you need to figure out how to achieve the same with less companion instances. Potentially with companion-satellite or some other way of multiple clients sharing a companion installation
