### ISSUE TITLE
[BUG] Companion breaks Windows DNS resolving

### ISSUE THREAD

**Issue by isaiahfranco** [bitfocus/companion#2108]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This is an interesting one that took me a while to nail down including wiping my computer and reinstalling everything. I'm on a Dell  Precision 7560 running Windows 10 and if Companion is set to bind to all network interfaces, my ability to access the internet or the local network stops working. As soon as I shut down Companion everything starts working again. When I re-open Companion, my network will function for several minutes before it stops again. Once it stops, I can ping IP addresses, but DNS won't resolve. It's super weird.

Oh, and it doesn't affect the dock that I'm attached to but ever other NIC (wifi, internal, USB, etc) stops working.

### Steps To Reproduce

Launch Companion.
Wait several minutes.

### Expected Behavior

My ability to access WAN and LAN keeps working.

### Environment (please complete the following information)

```markdown
- OS: Windows 10
- Browser: Chrome 94
- Companion Version: 2.2.0-b177f8fb-3722
- Computer: Dell Precision 7560
```

### Additional context

I can definitely say Companion is causing the issue. If I shut Companion down, everything works as it should.

**Comment by Julusian** [comment]
Does this happen on other computers for you, or just this one?
There was another issue report of this a couple of months ago (I'll dig out the link later) but I still struggle to understand how an application could accidentslly break windows in this way..

**Comment by isaiahfranco** [comment]
This is the only computer I have available to test it on. I will say, however, that I did do a full wipe and reinstall of Windows because I thought it was a system issue. I'd love to help nail this bug however I can.

**Comment by isaiahfranco** [comment]
@Julusian Hey man so here's the weird thing: it started happening even with my dock connection if the GUI is bound to all interfaces. Any ideas on why that would be?

**Comment by Julusian** [comment]
I am trying to reproduce this, but not having any luck.

Could you run `ipconfig` in command prompt and share the output. That should show answer some questions I have about your network setup.
If you could do that for both when the network is working and when it is broken that would be ideal.

To check, this happens without having any connections setup inside of companion?
And you are able to connect directly to other things by ip address, but not by a dns name?

**Comment by isaiahfranco** [comment]
![ipconfig not working](https://user-images.githubusercontent.com/41401412/190469842-daf42143-37e5-4d13-9b18-b06eddbd492f.png)
![ipconfig working](https://user-images.githubusercontent.com/41401412/190469848-cba72a0e-87cf-4a0b-8e9e-f6876fc5ade6.png)
![Companion Connections](https://user-images.githubusercontent.com/41401412/190469850-ab92b432-507b-4ed1-b07e-eec8f75030b5.png)
![Companion Settings](https://user-images.githubusercontent.com/41401412/190469853-91ccb8ca-b351-482b-bb59-8ee84a2d2c0b.png)


Ethernet 2 is the Dock.

**Comment by Julusian** [comment]
Hmm.. Could you try `ipconfig /all`?

The only changes I can see between those two screenshots are the refreshed ipv6 address. 

Perhaps you could try disabling ipv6? That could be the difference here that I am missing?

**Comment by isaiahfranco** [comment]
I ended up closing Companion to get my connection going again so I could continue working. I just disabled IPv6 and, if this happens again, I'll run the /all command.

**Comment by isaiahfranco** [comment]
![ipconfig all](https://user-images.githubusercontent.com/41401412/190487519-9c22d05e-7c6c-4c93-a176-a9e52f4a4626.png)
Just went out again.

**Comment by isaiahfranco** [comment]
I might have it narrowed down to the tplink-kasasmartbulb connections I'm using. If I break them by pointing them to the wrong IP address, eventually my connection fails. If I disable them or point them to the correct IP address, everything is fine.

**Comment by Julusian** [comment]
Ah yeah, I can see why that would happen https://github.com/bitfocus/companion-module-tplink-kasasmartbulb/blob/71c7c9ee35d85081635a858db2fdf34b485bbef6/src/actions.js#L31
Every time it sends a message to the bulb it opens a new socket, and never closes it.

So you will be experiencing UDP port exhaustion. DNS is UDP based, but pinging or normal web traffic is not which is why they continue to work

**Comment by Julusian** [comment]
I've opened an issue in that module repo, Im going to close this as it should only require a fix to that module.
Im glad you figured that out, I was very lost on how to continue trying to figure this out!

**Comment by isaiahfranco** [comment]
Copy that. Thanks, @Julusian!
