### ISSUE TITLE
[BUG] Image size for Button still states 72x58 PNG

### ISSUE THREAD

**Issue by mckernant** [bitfocus/companion#2109]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

With the update to remove the top bar from buttons, I believe the dimensions for the uploaded images should now be 72 x 72 not 72x58

![image](https://user-images.githubusercontent.com/97212123/188070486-2fa047e7-9c8b-4ea7-939b-f84629127213.png)

### Environment (please complete the following information)

```markdown
- OS:Windows 10
- Browser: Google Chrome
- Companion Version:2.3.0 (2.3.0+4608-v2-3.0-2994a6d0)
```

**Comment by JeffreyDavidsz** [comment]
Actually the size stays the same, the image is shifted to center when top bar is removed. This way the same image can be used for both settings
