### ISSUE TITLE
Failed to build list of modules [BUG]

### ISSUE THREAD

**Issue by kjetilpp** [bitfocus/companion#2111]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After updating to [2.3.0 (2.3.0+4648-beta-5f8ef99e)](https://bitfocus.io/companion/) running on CompanionPI, the search box is not working for me.
It returns error: 
```
Failed to build list of modules:
TypeError: c.find is not a function
```
![Screenshot 2022-09-03 145727](https://user-images.githubusercontent.com/5620578/188271471-2a5b8844-e443-4116-b3bc-93bf2c14b462.png)

### Steps To Reproduce

Go to Connections, type any text in the search box.

### Expected Behavior

Expect the search box to return a result.

### Environment (please complete the following information)

```markdown
- OS: CompanionPI
- Browser: Chrome 103.0.5060.134
- Companion Version: 2.3.0 (2.3.0+4648-beta-5f8ef99e)
```

Edit: Added error message in clear text.

**Comment by Julusian** [comment]
This is fixed in 4652

**Comment by kjetilpp** [comment]
> This is fixed in 4652

Can you link to 4652? Can't find it.

**Comment by Julusian** [comment]
As you're on companionpi, do an update to `beta` and you will get it
