### ISSUE TITLE
Streamdeck action appears on all pages of Companion

### ISSUE THREAD

**Issue by FBCMoyock** [bitfocus/companion#2112]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When adding a Streamdeck function to a button while in companion, the button appears on all pages and erases any other functions on those pages. If I am in stream deck with Companion closed, the function is only on the one page. As son as I open Companion the button appears on all pages.

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by Julusian** [comment]
What version of companion are you using?

It sounds like companion and the elgato software both think they have exclusive access to the streamdeck and so are fighting over it.

You have two choices
1) pick just one bit and software and use only that
1) use the 'companion plugin' in the elgato software to bring companion into there and let the elgato software do all streamdeck communication. how you do this one depends on the version of companion you are using

**Comment by FBCMoyock** [comment]
Streamdeck is 5.3.1 \ Companion 2.3.0
The problem seems to have started in the last month or so. I set this up 2 months ago with no problems.

Sent from my iPad

On Sep 5, 2022, at 8:44 AM, Julian Waller ***@***.***> wrote:

﻿

What version of companion are you using?

It sounds like companion and the elgato software both think they have exclusive access to the streamdeck and so are fighting over it.

You have two choices

  1.  pick just one bit and software and use only that
  2.  use the 'companion plugin' in the elgato software to bring companion into there and let the elgato software do all streamdeck communication. how you do this one depends on the version of companion you are using

**Comment by Julusian** [comment]
what os are you on?
have you upgraded companion since it you set it up 2 months ago?

**Comment by Julusian** [comment]
@FBCMoyock any more details?
I am 90% sure this is not a bug in companion, especially as it hasnt been reported by anyone else.

I still think it must be companion and the streamdeck software both opening the device and thinking they have exclusive access and so both respond to every press directly unaware of the other one
