### ISSUE TITLE
[BUG] El gato Streamdeck XL rev 20GAT9902 doesn't work using Use Companion natively

### ISSUE THREAD

**Issue by alepradolobo** [bitfocus/companion#2113]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi, I bought a new revision of streamdeck el gato model rev 20GAT9902 and it doesn't work in companion natively. I tried it in Windows version 2.3.0 and linux version 2.3.0

I can work with it ussing stream deck companion plugin.

Everything works ok in the same machines with an streamdeck el gato model rev 20GAT9901

### Environment (please complete the following information)

```markdown
- OS: Windows 10 and Debian 10
- Browser:
- Companion Version: 2.3.0
```

**Comment by Julusian** [comment]
From a quick google, this sounds like this is a new revision of the XL

**Comment by njrl** [comment]
semilar problem here (win10 and ubuntu22.04)... but strangely my 
model rev is 20GAT9901  and it doesnt work
lsusb shows:  ID 0fd9:**008f**
companion: 2.3.0+4608
streamDeck firmware: 2.01.002

tell me if i can supply further information to make progress on this topic
greetings

**Comment by njrl** [comment]
hey, i just tryed to change the device.productId to  0x008f  in /lib/elgato_dm.js ... this leads to:
` lib/elgato_dm USB: checking devices (blocking call) +11s
  lib/elgato_dm add device 0001:0007:00 +1ms
  lib/elgato_dm USB: done +136ms
  lib/usb Error from usb module elgato-xl: Device "0001:0007:00" was not found AND GOT: {"id":"yMuQQL7__","cmd":"add","type":"elgato-xl","devicepath":"0001:0007:00"} (id: yMuQQL7__ / yMuQQL7__) +11s`

The reason for "was not found" is probably a reset of the streamdeck in that moment which is visible in my syslog.
Is that a hint that there are real protocol changes like @Julusian mentioned ?

**Comment by Julusian** [comment]
No, changing that isnt enough to get it working.
https://github.com/julusian/node-elgato-stream-deck also needs some changes for this to be able to work.

I shall make a test build of something when I have a chance for someone to test

**Comment by njrl** [comment]
I was already certain that there is some upstream work to do ...
I'm willing to test builds on ubuntu, debian or win10 ...
If that is not expedient i could give you access to a vm or we do some "USB over internet" something.

**Comment by Julusian** [comment]
@njrl could you try out this build of companion-satellite? https://s3.bitfocus.io/builds/companion-satellite/companion-satellite-x64-147-1f0de80.exe

**Comment by njrl** [comment]
It seems to work flawless .... 
i tested buttons on different coordinates and pages .... anything else to do to proof that it's fine?

**Comment by Julusian** [comment]
Things needing testing:
* button presses
* button display
* serialnumber/id reports correctly
* changing brightness

There are some other methods that would be nice to verify, but that isnt possible from companion. That would require firing up a dev environment for the library

**Comment by njrl** [comment]
- button press - working (yellow top background goes on and any added function is reactiong)
- button bg and text color - working
- button bg graphic - working
- button rotation - NOT working
- serialnumber/id - working (satellite-CL26L3A03xxxx)
- changing brightness - working (off<->full)

"...require firing up a dev environment for the library"  with a short explanation i can do that ... because i'm not shure what you mean .. compile your stream deck lib seperately or pull the recently updated github version into the companion source folder and link it ... sorry i'm not that experienced with that nodejs stuff.

**Comment by Julusian** [comment]
> require firing up a dev environment for the library

I mean for the library. But I dont think I have a good process on doing that testing, so lets not bother for now.

Ill get this merged into companion and proper satellite builds soon

**Comment by Julusian** [comment]
This should be working in the latest companion beta build now

**Comment by njrl** [comment]
i've installed the beta version on ubuntu and it seems working fine.
But, while playing around i added the "companion restart" funktion to a butten ... which restarts companion just fine but the deck is not reconnecting anymore (also not by pressing rescan usb). it only works again by restarting companion manually or replug the deck and pressing rescan afterwards. I dont need that function, but should i file an issue for that anyways?

 then i wanted to check that specific behaviour on win10 but immediately after starting that beta it puts the CPU to 100% and is slowly eating up the RAM .  from what i was able to see in the TaskManager it looks like the Process is spawning a lot of subprocesses (the number in the brackets behind the process name was ascending every second until my system was freezing). at the moment i dont have another windooze10 box on hand to verify that.

btw thanks a lot for your work on that and in general

**Comment by Julusian** [comment]
I believe this is all working now
