### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Fabsim08** [bitfocus/companion#2122]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Impossible to open companion. the message ''another instance is already running''appear.

I find companion running in the background on my tasks desk but nothing appear, I close it but never succed to launch it.

### Environment (please complete the following information)

```markdown
- OS:W10
- Browser:Chrome
- Companion Version:The last one
```

**Comment by Julusian** [comment]
Have you checked if companion is minimised to the tray?

**Comment by Fabsim08** [comment]
Sorry I don't understand, you mean if I see an small icon in the toolbar?

**Comment by Fabsim08** [comment]
Ok I see, yes it's the solution, thanks a lot!!
