### ISSUE TITLE
Consistent buttons across pages

### ISSUE THREAD

**Issue by IanPurpose** [bitfocus/companion#2123]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Have set buttons that work the same consistently across select pages. But also with the ability to set which pages it appears on and/or change the preset commands for on specific pages. Can be handy for buttons used consistently across shows or on a daily basis.

**Comment by Julusian** [comment]
Duplicate of #27
