### ISSUE TITLE
Open on startup

### ISSUE THREAD

**Issue by CoolAEW** [bitfocus/companion#2130]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Could you please add a checkbox in settings to tell companion to start automatically on system startup?
It annoys me a little that I have to manually open companion every time my pc boots to get my streamdeck working.
I know It's possible to acomplish this by other means, but a built in feature would be nice.

**Comment by EnergeticStick** [comment]
This should definitely be added to the software itself, but until then, you can just configure it manually as I did.  Here's a pretty good youtube walkthrough for it:  https://youtu.be/-rXENhLkvTU

**Comment by Julusian** [comment]
It looks like electron can handle this for us https://www.electronjs.org/docs/latest/api/app#appsetloginitemsettingssettings-macos-windows

**Comment by millerdq** [comment]
I upvote this feature request.  In the meantime, you can autostart Companion by copying a Companion shortcut to the Startup folder.  Usually \windows\start menu\programs\startup

**Comment by Julusian** [comment]
This is possible in the 3.0 betas

**Comment by compumatter** [comment]
Got the new 3.1.  Found the checkbox.  Just what I was looking for!
