### ISSUE TITLE
[BUG] the slack chat invite link is not working

### ISSUE THREAD

**Issue by eulores** [bitfocus/companion#2131]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Similar to the closed bug report #1832, the link is again not working.
Unless this gets fixed, people new to your slack community won't be able to join.

### Steps To Reproduce

This link [slack chat](https://join.slack.com/t/bitfocusio/shared_invite/zt-o1i0mohx-p_m5I7fUEUJ1BBu_KrDN2Q) is no longer working.

**Comment by Julusian** [comment]
Use https://join.slack.com/t/bitfocusio/shared_invite/zt-1fsnlu7iv-YIjW9dRECR_VDZY8QX4r5A

**Comment by istnv** [comment]
Slack invite links expire. This is a feature of Slack, not Companion.

**Comment by Julusian** [comment]
All the links I can find are now updated
