### ISSUE TITLE
Duplicate Option for Press/Release/Feedback Actions

### ISSUE THREAD

**Issue by taliafin1000** [bitfocus/companion#2132]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Option to duplicate an action for press/release/feedback etc. and paste it in the same section.

**Comment by Julusian** [comment]
This will be in the 3.0 release, which does not yet have a planned release date
See https://github.com/bitfocus/companion/pull/2127
