### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by Cypris2010** [bitfocus/companion#2134]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I lost my pin / Password for the companion admin interface. Is there a way to reset the password, when I have access to the windows device witch companion is on?

**Comment by Julusian** [comment]
Are you asking for some easy tool to achieve this?

You can manually recover the password by looking in the db file go to `%APPDATA%/companion` in file explorer, and then it will be in the file called `db` somewhere

**Comment by Cypris2010** [comment]
Thank you, that second thing I was looking for.

**Comment by Takabrycheri** [comment]
Sorry,
what about macOS? Where I can find the password?

**Comment by kraves-oz** [comment]
> Sorry,
> 
> what about macOS? Where I can find the password?

Similar location. 

Look under your User folder in the ApplicationSupport folder

**Comment by Julusian** [comment]
The tray icon has an option to open to the folder
