### ISSUE TITLE
Keep Variables if Companion is closed?

### ISSUE THREAD

**Issue by Newyears1978** [bitfocus/companion#2135]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I am storing variables with button presses and those variables will be used until weeks later, but often our companions go down or we have to restart companion, etc, and the variables are being lost.

Is there a way to retain stored variables? I thought maybe storing the variable int he starting variable might work but of course, that did not for obvious reason.

Thanks in advance.

### Usecases

Any time a user wants variables to persist for periods of time.

In my case the variables are being passed to buttons that need to stay until it is time for new variables to be set.

**Comment by Julusian** [comment]
This is possible in beta build 4708

It has support for:
* Making a custom variable 'persistent'
* Storing the current value as the default
* Resetting back to the default value

**Comment by Newyears1978** [comment]
Awesome, where are Beta builds downloadable from?

**Comment by Newyears1978** [comment]
Is it possible this update broke the way the Current Path variable is saved? Before I Post it as a new issue? I had a button that saved the current slide and path to variables then moved a diff propresenter to those values.

The path was stored as 0:1 etc,, but now it is being stored as the name of the presentation (in pp7) like WalkOut.Pro

This was previously working but that may have been in PP6 that I was testing it. I am using the beta you provided so that may have caused this or it could be something else.

![image](https://user-images.githubusercontent.com/4557630/193436849-434cf8c1-ffb3-458e-9056-47ab66a1e2be.png)
![image](https://user-images.githubusercontent.com/4557630/193436850-fa7f66d5-8fc9-44ff-b597-42e9e219fcf7.png)
![image](https://user-images.githubusercontent.com/4557630/193436852-b927d258-7d12-4c31-84e5-533dd170ffac.png)

**Comment by Newyears1978** [comment]
Hey Julusian: I forgot to report back, after we tried this beta, companion would not load. It would just give the Rainbow loading icon forever. I could see companion icon but you could not get anything to open. Reverted back to 2.3 and all worked again.

**Comment by Julusian** [comment]
That would have been https://github.com/bitfocus/companion/issues/2139, which was included at the same time.
It is fixed in newer betas

**Comment by fbosman** [comment]
Great, but how can we use this feature?
