### ISSUE TITLE
[BUG] bitfocus-companion v1.10.0 Upgrade (beta 8de39d76) makes Companion unusable on mac-arm64

### ISSUE THREAD

**Issue by matbox** [bitfocus/companion#2139]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Installing build companion-mac-arm64-2.4.0+4708-beta-8de39d76.dmg increases CPU load for the Companion process 4-5x on my M1 Ultra mac, resulting in an unusable state (extreme sluggishness).

Moving back to the prior build ([companion-mac-arm64-2.4.0+4705-beta-8d50b9bb.dmg] fixes it. The issue is also present in all newer builds up to the latest one [companion-mac-arm64-2.4.0+4710-beta-05bf0507.dmg].

Disabling/Removing my connections does not fix the issue.

### Steps To Reproduce

Download and install companion-mac-arm64-2.4.0+4708-beta-8de39d76.dmg. Launch Companion. Try to navigate the toolbar-context menu or watch the Activity monitor.

### Environment (please complete the following information)

```markdown
- OS: MacOS 13.0 Beta (22A5358e)
- Browser: Google Chrome Version 105.0.5195.125 (Official Build) (arm64)
- Companion Version: 8de39d76
- Stream Decks: 2 (earlier XL builds)

**Comment by Jorick-tv** [comment]
Confirmed on Safari and Firefox alike.
Macbook Pro M1 2020, mac OS 12.3.1
Taking it back to 2.3.0 works

**Comment by obcocav** [comment]
Can confirm on win64 version also.  CPU load ran up to 100% and dozens of companion instances running in task manager.  System was unusable.  Had to go to safe mode and install previous (4695 build) Companion

**Comment by njrl** [comment]
can confirm, too. [](https://github.com/bitfocus/companion/issues/2113#issuecomment-1264355347)

**Comment by Julusian** [comment]
This should be better now, I believe this was caused by the implementation of #1022
