### ISSUE TITLE
[BUG] internal: Run shell path - Guru mediation - when running "python script.py" containing environment variables

### ISSUE THREAD

**Issue by DrillableBit** [bitfocus/companion#2144]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As title: running shell python script with environment variables via companion triggers error code: 
instance(internal): Shell command failed. Guru meditation: {"killed":false,"code":1,"signal":null,"cmd":"sudo python script.py"}

Here is the code: 
```
import os
import time

if os.environ['RUN_UNTIL'] == "0":
    os.environ['RUN_UNTIL'] = "{}".format(time.time() + 60)
    # start
    while time.time() < float(os.environ['RUN_UNTIL']):
        time.sleep(1)
    os.environ['RUN_UNTIL'] = "0"
    # stop
else:
    os.environ['RUN_UNTIL'] = "{}".format(time.time() + 60)
```

The snippet works if: 
Replacing **(os.environ['RUN_UNTIL'] == "0":)** with **(1 < time.time():)** (time.time() will always be a value larger than 1)
Running natively on pi as "python script.py"

### Steps To Reproduce

1. Install companion
2. Create above mentioned script.py
3. Initiate RUN_UNTIL variable in .bash or locally as "0"
4. Run chmod +x script.py OR chmod 777 script.py
5. Connect to Companion IP - add shell script "python (path/to/file/script.py)
6. Run shell script

### Expected Behavior

Should produce error log : 
instance(internal): Shell command failed. Guru meditation: {"killed":false,"code":1,"signal":null,"cmd":"sudo python script.py"}

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by DrillableBit** [comment]
Edit: 
Running script as "sudo script.py" produces same error as running script through Companion. 
Running script as "sudo -E script.py" works. 

Tried setting environment variables in:
 ~/.bashrc
 ~/.profile
 /etc/profile
 /etc/environment
All produce the same error. 

Does Companion have a set script it loads variables from?

**Comment by Julusian** [comment]
Are you running this on companionpi? If so how old is your image?

Companion-pi images made before 2.2.0 are different, but in the 2.2.0 and new images the following is true:

* Companion is only allowed to run a very small list of commands with `sudo`
* Companion is run as a `companion` user instead of the `pi` user, so shares a different environment to the builtin user

**Comment by DrillableBit** [comment]
This is being run on companionpi. Mounted using (https://s3.bitfocus.io/builds/companion-pi/companion-pi-stable-v2.2.3-06-07-22.img.gz)

I ran sudo companion-update this morning, but it produces the same issue. 

Running sudo script.py with "Print(os.getenv('VARIABLE'))" returns "NONE". 

I'm confident I'm just not setting the variable in the right place...

**Comment by Julusian** [comment]
yeah, your companionpi is not allowed to run `sudo script.py`

It is possible to allow certain things to be run with `sudo` by companion, I dont remember how without googling

**Comment by DrillableBit** [comment]
Running sudo through companion seems like a security issue, but this should be solvable without running the script in "sudo -E".

Storing a new variable inside a script using os.environ seems to work for the script, but the variable doesn't retain cross-script -which is the entire point of a environment-variable. 

Is there any way to manipulate Companion environment variables?

**Comment by DrillableBit** [comment]
If anyone else runs into the same issue, a viable workaround is to use an object storage (Redis) or database as key value storage.

**Comment by Julusian** [comment]
> Storing a new variable inside a script using os.environ seems to work for the script, but the variable doesn't retain cross-script -which is the entire point of a environment-variable.
> 
> Is there any way to manipulate Companion environment variables?

Well, thats not how environment variables work. They wont be persisted across shell sessions unless you write them to the startup script for the shell.  

The simplest solution I can think of is to write the values you need to persist to a file on disk, which you can then read from later on.

**Comment by DrillableBit** [comment]
I see,
Thank you!
