### ISSUE TITLE
[BUG] Button Press and Release if Variable meets Condition breaks if you select a button on "this page" as the target

### ISSUE THREAD

**Issue by Mozoloa** [bitfocus/companion#2146]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As the title says, **Button Press and Release if Variable meets Condition** breaks if you select a button on "this page" as the target, the target button is never triggered.

### Steps To Reproduce

1. Create a button 1 , make it a toggle
2. Create another button 2 on the same page
3. On button 2 use *Internal:Button Press and Release if Variable meets Condition* as a press action
4. Take any variable, and make it so it triggers when it's != something random (so it should trigger all the time)
5. Make it so it triggers button 1 on **This Page**
6. Observe as the button is not triggered
7. Make it so it triggers button 1 on **X (PAGE)** (X being the page where the buttons are, so it should be the exact same as **This Page**)
8. It's working now

### Expected Behavior

Well the button should trigger, like it does when you explicitly choose the page and not **This Page**

### Environment (please complete the following information)

```markdown
- OS: W10 and W11
- Browser: Brave and Chrome
- Companion Version: Latest Stable 2.3.1 and Latest Beta 2.4.0+4723-beta-c3cb02b6
```

**Comment by Julusian** [comment]
This is fixed in build 4743
