### ISSUE TITLE
Real-time keyboard -> variable entry

### ISSUE THREAD

**Issue by mark-epstein** [bitfocus/companion#2148]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I would love to be able to go into a mode in Companion where any entry on a keyboard attached to the system was dumped into a custom variable.  Assuming the keyboard was actively being "captured" by Companion, I'd like to, by pressing a button, redirect the keyboard text entry to 
- replace a specified variable
- append a specified variable
and I'd need a way - whether toggling the original button or with another companion button - to say, "stop capturing the keyboard."

### Usecases

on-the-fly text changes of buttons, most notably camera presets
rudimentary chat function between companion users without leaving the app

**Comment by Julusian** [comment]
Im not sure about this. It feels like this will mean that companion can be turned into essentially a keylogger.
Also, it would only work on the machine where companion was running, not another machine connected to the same web interface.
And I dont expect it will be possible to stop the keyboard events reaching whatever application is in focus, so you will need to make sure that whatever you are typing wont be interpreted as anything by whatever is in focus.

I'm not saying no (for now), but there are a lot of questions here that require some serious thought

**Comment by mark-epstein** [comment]
Yeah, the keylogger risk occurred to me, but could you make it *only* work
if Companion had focus?

I hadn't really thought beyond the computer running Companion itself but I
can see that web connected GUIs wouldn't work.
