### ISSUE TITLE
[BUG] Local build returns `incorrect data check` error.

### ISSUE THREAD

**Issue by GarthDB** [bitfocus/companion#2149]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I run `yarn --frozen-lockfile` or `./tools/update.sh` I get following error:

```
~/Projects/companion master
❯ yarn --frozen-lockfile
yarn install v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error An unexpected error occurred: "https://codeload.github.com/bitfocus/companion-module-analogway-midra/tar.gz/d65e12c7c646fbb9f1a12b763882ddded4fe0430: incorrect data check".
info If you think this is a bug, please open a bug report with the information provided in "/Users/garthdb/Projects/companion/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Steps To Reproduce

Run `yarn --frozen-lockfile` or `./tools/update.sh` in the main directory.

### Expected Behavior

It should install the git submodules and dependencies.

### Environment (please complete the following information)

```markdown
- OS: macOS 12.6 (Monterey) m1
- Browser: N/A. Node v14.19.3
- Companion Version: current master branch (v2.3.1)
```

**Comment by GarthDB** [comment]
If I remove the `yarn.lock` file and run `yarn` I eventually get the following error:

```
[3/5] 🚚  Fetching packages...
error An unexpected error occurred: "https://codeload.github.com/bitfocus/companion-module-analogway-midra/tar.gz/d65e12c7c646fbb9f1a12b763882ddded4fe0430: incorrect data check".
```

**Comment by Julusian** [comment]
Can you share the file `/Users/garthdb/Projects/companion/yarn-error.log`?

**Comment by GarthDB** [comment]
I put the `yarn-error.log` file in a [gist here](https://gist.github.com/GarthDB/0bd34ee30313de24ed82174c2e03a6ad).

**Comment by Julusian** [comment]
With the changes in 3.0, this should not be a problem anymore.
