### ISSUE TITLE
[BUG] Enabling or Disabling a trigger by a button

### ISSUE THREAD

**Issue by DeeJayMX** [bitfocus/companion#2152]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Create multiple triggers
Create a button to disable or enable the triggers
>> The web interface got cleared !

just refresh the page and everything comes up as usual but...

very strange behavior.

here is my trigger sample:
![image](https://user-images.githubusercontent.com/36418772/198072309-769571de-a37d-4c5c-9e18-4be99a51fd5b.png)

tested on MS EDGE
Companion version [2.4.0 (2.4.0+4735-beta-0700874e)]

### Steps To Reproduce

Create multiple triggers
Create a button to disable or enable the triggers
>> The web interface got cleared !

### Expected Behavior

The interface has to stay as usual

### Environment (please complete the following information)

```markdown
- OS: Windows 10
- Browser: Edge 
- Companion Version:[2.4.0 (2.4.0+4735-beta-0700874e)]
```

**Comment by Julusian** [comment]
Which part of the webui gets cleared?
