### ISSUE TITLE
Companion overwrites buttons in profile

### ISSUE THREAD

**Issue by images0rla** [bitfocus/companion#2154]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://user-images.githubusercontent.com/116817221/198302393-1dd770b1-d0f3-42f1-9477-08669db560de.png)

### Environment (please complete the following information)

```markdown
-Windows 10,  Companion 2.3.1v; Chrome  Version 106.0.5249.119 (Official Build) (64-bit)
```

### Additional context

If I don't load companion in a profile, and create a folder on a page or add a streamlab event, it works correctly and does not populate those on every page. but as soon as I load Companion profile it will overwrite these buttons. Thanks, Appreciate any help

**Comment by Julusian** [comment]
I don't think there is enough detail here to work off.
Closing until more is provided
