### ISSUE TITLE
UI: Warning before exiting trigger modal if changes have been made

### ISSUE THREAD

**Issue by bryce-seifert** [bitfocus/companion#2155]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

When you're working in a trigger modal, if you accidentailly click outside the modal before you've save you lose all of your work.

I suggest that if the user has made any changes, ie added actions or feedbacks, that there be a prompt before closing to help prevent losing work from errant clicks.

**Comment by Julusian** [comment]
This is no longer an issue in v3.0. See #2165 
I shall leave this open for now, as this could be improved in 2.4 pretty easily

**Comment by Julusian** [comment]
This is in the 3.0 betas
