### ISSUE TITLE
[v3]: Modules with compatibility issues

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion#2157]
Modules in the 3.0 dev/beta builds with known compatability issues/crashes:

https://docs.google.com/spreadsheets/d/153YDDxvtXw2zmdBmYqw3QrWkmCAVzwx6eCTXl3_2NX4/edit?usp=sharing

**Comment by TechnikCMI** [comment]
> Modules in the 3.0 dev/beta builds with known compatability issues/crashes:
> 
> ### Build errors
> * [ ]  ecamm-live
> * [ ]  generic-pjlink
> * [ ]  google-sheets
> * [ ]  videocom-zoom-bridge
> * [ ]  vystem-api
> * [ ]  zoom-osc-iso
> 
> ### Build errors (due to node18)
> * [ ]  analogway-awj
> * [ ]  barco-clickshare
> * [ ]  bitfocus-snapshot
> * [ ]  cisco-webex-websocket
> * [ ]  discord-api
> * [ ]  esphome-api
> * [ ]  generic-emberplus
> * [ ]  ipl-ocp
> * [ ]  linkbox-remote
> * [ ]  magewell-ultrastream
> * [ ]  olzzon-ndicontroller
> * [ ]  panasonic-ptz
> * [ ]  panasonic-kairos
> * [ ]  seervision-suite
> * [ ]  sennheiser-evolutionwireless
> * [ ]  sonos-speakers
> * [ ]  soundcraft-ui
> * [ ]  studiocoast-vmix
> * [ ]  theatrixx-xpresscue
> * [ ]  twitch-api
> * [ ]  ventuz-director
> * [ ]  youtube-live

Problem with

**Comment by NefDak** [comment]
Hope I post the error correctly here (I'm new to Github but have been using Companion for a very long time). The "Fader adjust" no longer reacts to the Behringer xair module.
The "Fader set" or "Mute" e.g. work without problems.
In the log of the connection I can see the events for other buttons (e.g. mute). E.g.:
debug: received /ch/01/mix/on from
debug: received /ch/02/mix/on from
But when I assign buttons with "Fader adjust" and press them, I don't see any events in the debug log.
At the moment I'm on version 3.0.0+5713-beta-cdefdadf. Unfortunately, I can no longer say from which version the functions were no longer there. I think so far 2 weeks.

**Comment by kyzurale** [comment]
Incompatible with V3.0

modules:
ptzoptics-visca
obsidiancontrol-onyx
neodarque-stagetimer2

When modules added, stuck at "Waiting for connection to start..." under the Edit Connection Tab.

**Comment by staticlondon** [comment]
The SPX-CG module isn't working in v3.0. The debugger says: "Missing module package.json data."

**Comment by FlorianFSA** [comment]
The _Anomes: Millumin 2_ module is broken. 
`Instance/Wrapper/millumin: Error initalizing module: Cannot read properties of undefined (reading 'on')`
Tested on Build 3.0.0-rc1+5909-v3-0.0-rc1-725c3583

**Comment by DiakonTV** [comment]
StageTimer2 is not functioning under version 3.0.  It will connect, but not pass any commands.

**Comment by gdigloria** [comment]
Here to record H2R Graphics module stuck on "connection config unavaible" in edit connection tab. 
Thanks a lot.

Companion v3.0.0-rc1
H2R v2.16.1
Mac os 16.6.2 intel.

**Comment by ddn4t** [comment]
The Generic: SW-P-08 router module has had the drop down to select router levels broken in 3.0 and up.

The module itself seems to be working properly outside of that still, as though the drop down is still broken on them, buttons made prior to the upgrade to 3.0 and up still work properly. The levels that were selected on the button during its construction pre-3.0 are still technically "selected" when the button is pressed though you can not see them.

**Comment by Julusian** [comment]
@ddn4t huh, that was using a config field type that was only half documented, so it was missed in the compatibility layer.
That will work in the next beta build and release

**Comment by gsigouin** [comment]
New version cannot connect to TPLink-KasaSmartBulb!  Works with the smart plug, but not the smart bulb.

**Comment by sharadagg** [comment]
> Modules in the 3.0 dev/beta builds with known compatability issues/crashes:
> 
> https://docs.google.com/spreadsheets/d/153YDDxvtXw2zmdBmYqw3QrWkmCAVzwx6eCTXl3_2NX4/edit?usp=sharing

Happy to test SPX GC
Would it be possible to update the plugin to support SPX GC 1.2

**Comment by TBuTcher71** [comment]
Panasonic: PTZ Camera PAN/TILT
Button Image Arrows missing from Presets

ByteHive Doesn't Connect to Server

**Comment by mou22y2** [comment]
The SPX-CG module does not work in 3.xx

**Comment by loolou** [comment]
NewBlue Titler Live is outdated, in V3.2.2

**Comment by Froostix** [comment]
TP-Link Tapo Smart Plug is outdated too, in V3.2.2. Can't connect.
