### ISSUE TITLE
[BUG] "Disable rotary actions" alert popping up whenever navigating to buttons in Admin UI

### ISSUE THREAD

**Issue by matbox** [bitfocus/companion#2159]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

<img width="611" alt="image" src="https://user-images.githubusercontent.com/112365/199361087-5fce62ce-1b43-43f8-a7fe-e2c6e0b35341.png">

Since the last beta (2.4.0+4760-beta-2993bdef) I get the alert whenever I navigate to a button in the admin UI.

### Steps To Reproduce

1. Open UI
2. Click on any button in the UI to configure buttons for a surface

### Environment (please complete the following information)

```markdown
- OS: Mac OS Ventura (with companion being installed on a Raspberry Pi)
- Browser: Google Chrome Version 107.0.5304.87 (Official Build) (arm64)
- Companion Version: 2.4.0+4760-beta-2993bdef
```

**Comment by Julusian** [comment]
This is fixed in the next beta build
