### ISSUE TITLE
Moving a button generates a javascript error

### ISSUE THREAD

**Issue by wvanmaris** [bitfocus/companion#216]
Using the latest build, I tried moving a button. It generated the error as seen in the screenshot. (after second step of moving, "the paste".

![image](https://user-images.githubusercontent.com/42930028/44975205-2491f080-af62-11e8-94e6-e6400cd7695a.png)

**Comment by haakonnessjoen** [comment]
Could you try again. You should have gotten another error before that one.

**Comment by wvanmaris** [comment]
On OSX, build ab1d0c7 (sep3) it works as expected! (works fine).

**Comment by kraves-oz** [comment]
![capture error](https://user-images.githubusercontent.com/42990369/45070663-c1e15600-b115-11e8-8a51-3c150bd618f2.png)

I have the same error, anytime it tries to access the db by the looks of it.  Adding instances in this example.  Latest build, uninstalled previous version and deleted Companion appdata folder before new install.  
Win10:   companion-1.1.1-518d6ed-win64.exe

thanks
Kyle

**Comment by willosof** [comment]
This is weird. This error tells us that the companion database file is being saved, but it's not allowed to by the OS. First we write to a file named "db.tmp" and when we're done writing it, we rename and overwrite it to "db". So, this process happens everytime you change anything in companion.

Does the same error happen when you guys:
* Change a button design?
* Change an instance?
* Change userconfig?

**Comment by wvanmaris** [comment]
No on button design.
No on editing an instance, but yes on enabling/disabling an instance
No on user config.

Verzonden vanuit Mail voor Windows 10

Van: William Viker
Verzonden: woensdag 5 september 2018 18:57
Aan: bitfocus/companion
CC: wvanmaris; Author
Onderwerp: Re: [bitfocus/companion] Moving a button generates a javascript error(#216)

This is weird. This error tells us that the companion database file is being saved, but it's not allowed to by the OS. First we write to a file named "db.tmp" and when we're done writing it, we rename and overwrite it to "db". So, this process happens everytime you change anything in companion.
Does the same error happen when you guys:
• Change a button design?
• Change an instance?
• Change userconfig?

**Comment by haakonnessjoen** [comment]
Can people test if this has been resolved in build 5c80b99 now?

**Comment by haakonnessjoen** [comment]
Should be fixed in latest build, please reopen if not.

**Comment by kraves-oz** [comment]
Thanks lads. I haven’t got my win10 machine with me this week to test. Will check latest build later in week.
