### ISSUE TITLE
[BUG] Companion doesn't start when added as a macos login item

### ISSUE THREAD

**Issue by kjvisual** [bitfocus/companion#2164]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Previous versions of Companion (the last version before 2.3.1) launched at login. This issue may be due to Mac 12.6.1 update. Basically the start at login feature was working until I updated both Companion and the OS. I am placing more blame on the OS. Is there anything you can do to address this?

### Steps To Reproduce

1. update Companion
2. Update to MacOS 12.6.1 from previous version. 
3. Add Companion to User Login items.

### Expected Behavior

Companion will not automatically launch when the computer is restarted and user is logged in. 

### Environment (please complete the following information)

```markdown
- OS: 12.6.1
- Browser: Chrome 107.0.5304.87 
- Companion Version: 2.3.1 (2.3.1+4641-v2-3.1-dc01ac7c) Apple Silicon
```

**Comment by Julusian** [comment]
3.0 supports registering itself at a startup item, so hopefully this will work better. If not please open a new issue for that
