### ISSUE TITLE
Ability to add delays based on variables

### ISSUE THREAD

**Issue by asdsh29** [bitfocus/companion#2172]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I think it could be helpful if there is the ability to set a variable as a delay time in between actions. Maybe also with a checkbox to ignore the delayed action if the value is 0 and/or not an integer.

### Usecases

I wanted to perform an auto transition on a video mixer right after a clip on an external video player. To do this, I wanted to dynamically write the length of the clip as a variable and set this as a delay between the "play clip" action and the "auto transistion" action. I then realized that the delay value can only be set as a fixed integer and not as a variable value.
This also can be helpful for a lot other timed application like show run downs or audio fading.

A big thank you to everyone who is involved in this great project!

I hope that this idea/feature will be integrated at some point and will help with some projects!
Thanks a lot,
cheers,
Stefan

**Comment by LukeSCC** [comment]
This would be a really useful feature.

**Comment by Mozoloa** [comment]
I like this, being able to delay an action on a dynamically set timer would be great

**Comment by tubalois** [comment]
+1 I'm also looking for a way to delay and/or delay two playbacks on different devices. this feature would be awesome

**Comment by dnmeid** [comment]
Using delays for such a task is not the best option.
1. if your clip is quite long the times of the delay and the running time of the clip may not stay within sufficient equality
2. if you pause, abort or shuffle your clip, eventually not from Companion, your delayed action will fire at the wrong time
3. you always have to keep track of clip length yourself which is tedious and prone to errors

A better solution would be to use a trigger from a feedback wether a clip is playing to fire the action. Then you can do your transition when the clip stops. If you want to do a fade maybe on the last second, use a remaining time variable.
If those feedbacks or variables are not available for your device, it is better to ask for such functionality than for a variable based delay.
Despite a variable delay not being the best solution for you, it generally is not a bad idea to have variable delays as a feature.

**Comment by albertorighetto** [comment]
This would be really useful.
I'm currently on a show where 144 buttons have the same hard-coded delay.
I wish I could have used a custom variable if something needs to change later.

**Comment by kenj1** [comment]
I could really use this feature.  I'm using Mitti to play a cue and want Fade to black after the cue ends.  Using the remaining cue time variable for the delay would really be useful.

**Comment by Julusian** [comment]
This is possible in the betas as part of #3163
