### ISSUE TITLE
[Feat] Text input for triggers on variables

### ISSUE THREAD

**Issue by thedist** [bitfocus/companion#2176]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Both the `On variable change` Event, and `internal: Check variable value` Condition, for triggers use a dropdown box listing variables that have a definition. The issue with that is some variables are used without a definition (examples being vMix and Google Sheets).

For modules with a small set of instance variables it may be simple to have a definition for each of them, but for modules like vMix which have variables for inputs by name, key, and number, or Google Sheets which has variables for every cell within the returned range can result in tens of thousands of variables. This large number of variables while being handled fine by Companion itself, the frontend struggles if it was to fill a Dropdown with that many variables (and even worse is auto-complete when typing a variable into a text input which has performance issues already).

### Usecases

This feature would allow for more instance variables to be used with triggers without forcing them to either not make all variables available as triggers, or to create definitions for each of them and greatly degrade frontend performance.

**Comment by Julusian** [comment]
There is a bigger 'problem' at play here, in that the module-api in v3 is enforcing that variable values cannot exist without a matching definition https://github.com/bitfocus/companion-module-base/blob/main/src/module-api/base.ts#L550-L564

So while those dropdowns could benefit from allowing custom values (so you can set it up for a variable you know will exist later on), it wont help with your use case

**Comment by thedist** [comment]
Is there a technical reason definitions will be enforced, or is this just to encourage best practices? From a performance point of view it's a detriment to the frontend if there are too many definitions. 

In the vMix module I have config options to allow the user to choose which are defined (for example, if a user wants to reference inputs by name, they can have it only display variables by name and not define inputs by keys or numbers). While I can just define all variables in vMix it will result in roughly 3x the number of variables. For Google Sheets it would be impossible to use instance variables at all for cell data as there'd simply be far too many definitions and the browser tab would grind to a halt trying to autocomplete variables or using the dropdown.

**Comment by Julusian** [comment]
It is mostly a usability/consistency thing of 'hidden' variables are not intuitive for the user, but I also know that a rework of the variables system is needed, and I don't want to force us into supporting this when I suspect it won't be possible without some comprises after that rework. 

Im going to make https://github.com/bitfocus/companion/issues/2055 be something that needs to be looked into for v3, as that feels like the proper solution here, but I shall think some more on whether this restriction should also be changed.
Im trying to ensure we don't need to make any breaking changes to the module api for a while, so there are some new limitations to the module api of what felt reasonable. This could well be a case of somewhere that was too far

A semi-related question, does the variable view table popup/table work for google-sheets? we aren't filtering the values sent to the ui, so that will also be a huge set of data for you.

**Comment by thedist** [comment]
It's a tough thing to figure out the best solution, as for triggers I could get away with creating a basic feedback for the Google Sheets module and use that to see if a cell meets a condition without it needing to be a variable, but that wont help those who want to use the value of a cell as text on a button, or as data for some action in another module, or anything like that.

As for the variable view, I'm currently using the Google Sheets module with 1 spreadsheet, containing 21 sheets, resulting in 120,471 instance variables, of which only 46 are defined (4 specific variables, 1 variable for each sheet name, and 1 variable for the value of A1 in each sheet as an example). With all of those instance variables the CPU usage of the browser tab is about 10% higher than it would be without that instance running, but the Variables table and autocomplete when I start to write a variable is perfectly usable. If I was to define all 120,471 variables the tab crashes.

The number of variables is not an issue computationally, as NodeJS handles this perfectly fine as does the Javascript on the page, but one of the most costly operations on a webpage is changes to the DOM, and having that many elements load in/out is not viable, which is why I've been going by this approach for so long of not defining all variables.

**Comment by Julusian** [comment]
This is now possible.

I think it has merit outside of your use case, as some variables will appear and disappear while companion is running, when modules connect or disconnect or other changes.
