### ISSUE TITLE
Unresponsive module author following update that broke module

### ISSUE THREAD

**Issue by jsnyder886** [bitfocus/companion#2178]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm certain this is not the correct place to post this, but I have no idea how to properly address this.  I posted an issue in the Roland V60HD module repository about their recent update that effectively broke the module as it no longer switches the video input on a video switcher.  I've downgraded since then, but there are updates to other modules that I'm using that I cannot use because if I update past where I'm currently at, my video switcher doesn't work.  Here's the link to my issue that I created:  

https://github.com/bitfocus/companion-module-roland-v60hd/issues/10

Given that they aren't able to respond (I get that this is an open source project and people have lives, etc...), can we roll back that module until they can get it fixed and tested and include that old working version in the updated companion beta release please?

Thanks in advance for your time!

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by josephdadams** [comment]
Try tagging me next time to get my attention
