### ISSUE TITLE
Log not showing ATEM Models

### ISSUE THREAD

**Issue by cxselph** [bitfocus/companion#218]
Companion 518d6ed

**Describe the bug**
Not an issue with functionality, but the official names disappeared and show up as numbers in the log. Also the Broadcast Studio 4ME shows up as the 2ME Broadcast Studio model. #7

![screen shot 2018-09-05 at 4 49 44 pm](https://user-images.githubusercontent.com/14942903/45120723-f6144100-b12c-11e8-8825-5c6d1fcb5a6d.png)

**Desktop (please complete the following information):**
OSX 10.13.2 and 10.12.6
 Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by willosof** [comment]
This issue was moved to bitfocus/companion-module-atem#3
