### ISSUE TITLE
[BUG] Loupedeck Live S - LED position issues

### ISSUE THREAD

**Issue by CD6-timury** [bitfocus/companion#2186]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The `Loupedeck Live S` (https://www.bhphotovideo.com/c/product/1713342-REG/loupedeck_ldd_2201_live_s.html) has 2 encoder rings, 4 physical buttons and space for 15 led buttons.
If I use the native Loupedeck software and their Companion plugin - I do not have any issues, however if I use native Companion: the LED screen seems to be displaced:
![Untitled-3](https://user-images.githubusercontent.com/8738747/202313771-48e6c078-7cca-4cfd-87e3-a922e28dd13b.png)

Companion Version: `2.4.0 (2.4.0+4786-beta-8155f54f)`
Loupedeck Version: `0.1.4`
Operating System: Windows-10

PS. And yes, with 7 buttons horizontally across - the button assignment is as following:
- Row 1 (1 encoder, 5 LCD buttons, 1 physical button) - act as Companion buttons 1-7
- Row 2 (1 encoder, 5 LCD buttons, 1 physical button) - act as Companion buttons 8-14
- Row 3 (1 physical button, 5 LCD buttons, 1 physical button) - act as Companion buttons 15-21

### Steps To Reproduce

1) Turn on Companion
2) Go to `Settings` & tick `Enable connected Loupedeck Live devices (Requires Companion restart)`
3) Restart Companion
4) Make sure Loupedeck software is closed
5) Plug in the Loupedeck Live S device into the computer
6) Go to `Surfaces` & click `Rescan USB`
You will see the misplace already, but what helps is giving each button a different color.

### Environment (please complete the following information)

```markdown
- OS: Windows 10
- Browser: Chrome (Version 107.0.5304.107)
- Companion Version: 2.4.0 (2.4.0+4786-beta-8155f54f)
```

**Comment by asdf23** [comment]
Here are my observations using node/loupedeck.

I had the same dead 6 rows of pixels issue (on the right), I was using this device on Linux. Loupedeck said to run their software to recalibrate it, I did so and I saw that this problem did not exist, I don't know that this addressed this issue or not, but perhaps it did something. Moving back to node/Linux I found I had to readjust the button locations.

The button locations are a bit of a judgement call. They are not exactly lined up, not exactly square, not spaced apart evenly.

**Comment by Julusian** [comment]
My live-s arrived earlier today, so I will be looking into it this evening and making sure it works properly

**Comment by Julusian** [comment]
This should be working properly now in 4789 (b2d0e469ca456c824d55db48e5994c98307a9e57)

![PXL_20221117_175102612](https://user-images.githubusercontent.com/1327476/202522843-9c7442a7-669e-4cdd-8399-99d7bd210482.jpg)

**Comment by zingo** [comment]
Sorry for an offtopic question @asdf23 
> Moving back to node/Linux I found I had to readjust the button locations.

Under Linux I only get a /dev/ttyACM0 device but no eth on 100.127.x.x did you need to do any "magic" for that to appear.
Tested a fast dualboot to Windows and there the loupedeck software can talk to the unit so it seem to work as it should. Thanks for your time.

**Comment by Julusian** [comment]
@zingo They changed the devices a while ago to be a serialport rather than a virtual network interface. I think they said there were issues for people who were using a vpn

**Comment by zingo** [comment]
> @zingo They changed the devices a while ago to be a serialport rather than a virtual network interface. I think they said there were issues for people who were using a vpn

Ahh thanks for the info, that is a good clue!  :)
Do we know the serial setting like baud rate used? I tried opening a term to it in different speeds but I don't even get any garbage back :( (also tried browsing the different project out there and didn't find any baud rate) Ill see if I can get your project running, I see you made a 0.22 release yesterday :) I haven't use nodejs before so it's a bit of a setup struggle for me but fun :)  also @asdf23 made some Live S patches for foxxxyz project so that might also work.

**Comment by Julusian** [comment]
@zingo https://github.com/Julusian/node-loupedeck/blob/main/packages/node/src/serial.ts#L41

**Comment by asdf23** [comment]
@zingo I don't think there is any concept of a baud rate, it's not that type of device. 

https://rfc1149.net/blog/2013/03/05/what-is-the-difference-between-devttyusbx-and-devttyacmx/

If a device is missing,.. (I don't think that it is based on your description & specifically for this device) but if it were that magic you'd want is `modprobe`
