### ISSUE TITLE
FEATURE REQUEST : Ability to use < > != etc to variables in triggers and feedback

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion#2188]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

It would be very helpful to be able to use expression symbols in feedbacks etc.  For example on the Yamaha TF module I can activate a feedback for fader to value X but I would like to have that feedback activate for X or greater.  Other modules could make great use of this as well.  Thanks!

**Comment by Julusian** [comment]
It sounds like this feedback covers what you are after? 
![image](https://user-images.githubusercontent.com/1327476/202900713-297dd486-d75f-4479-95c8-d854af9e414b.png)

**Comment by MeestorX** [comment]
We've already solved this, haven't we @obcocav ? 

FYI, you can't do comparisons using feedback because it's boolean-only. My "set variable from feedback" mod gets past this limitation in the Yamaha-RCP module at least...

**Comment by Julusian** [comment]
So it doesn't sound like there is anything to do here except for potentially implement your "set variable from feedback" idea?

**Comment by obcocav** [comment]
@MeestorX .  Yeah I guess so.  I think I had a misconception and mixed this up with another reply to make a request directly to Companion rather than the module! 

Trying to figure out my schedule and will get back to your other message!  

Sorry for the mixup and thanks guys!  Thank you.
