### ISSUE TITLE
[BUG] Problem with custom variables

### ISSUE THREAD

**Issue by sstaub** [bitfocus/companion#2191]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have problems with custom variables on Stream Deck + using generic OSC module
While making the config all works fine but:
When I export a project and then reimporting after reset, the current values are gone away.
I don't know if this is the problem, but the startup values are also ignored most times.
It is very tricky config witch uses the latch/unlatch function to give a custom variable different values.
This custom variable is used to send a value with an OSC message, which is different for encoder left/right direction.
e.g.
- `$(internal:custom_intens_state)` with value 1 as current and startup
- There is a button with latch action value 4 and unlatch action with value 1 for this variable
- The encoder send an OSC message `/eos/wheel/Intens` with integer value `-$(internal:custom_intens_state)` for left encoder action and `$(internal:custom_intens_state)` for right encoder action.

It seems that the startup values are not correctly initialized for most of the variables.
You can find the configuration file also on https://github.com/sstaub/eosstreamdeckplus
[eos_streamdeck+.companionconfig.zip](https://github.com/bitfocus/companion/files/10058414/eos_streamdeck%2B.companionconfig.zip)

### Steps To Reproduce

- Reset the configuration
- Load the config file
- Most of the OSC messages send `0` as an integer argument

### Expected Behavior

The startup values should correctly initialized over all instances.

### Environment (please complete the following information)

```markdown
- OS: macOS Ventura 13.0.1
- Browser: Safari 16.1
- Companion Version: 2.4.0 (2.4.0+4792-beta-30009eb2)
```

### Additional context

The Stream Deck + is not automatically recognized on macOS, a rescan is needed.

**Comment by Julusian** [comment]
This is fixed in Beta 4808 (d1b2b695c557c9585fb4d085b2db97ec553b394e)
When importing a config it will now initialise all imported custom variables to their startup values
