### ISSUE TITLE
ATEM MINI PRO ISO with Stream Deck Mk2 - In Buttons tab the Buttons are 5x8 rather then 3x5?[BUG]

### ISSUE THREAD

**Issue by lordofdb** [bitfocus/companion#2194]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 In Buttons tab the Buttons are 5x8 rather then 3x5?

### Expected Behavior

Shouldnt it show the same elgot button Matrix?

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by Julusian** [comment]
This is expected. We do not support changing the view of how the streamdeck is shown currently.

See #1607 #1352 and some more issues asking for this or something similar
