### ISSUE TITLE
More datatypes for custom variables

### ISSUE THREAD

**Issue by sstaub** [bitfocus/companion#2195]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

In the moment only Integers are supported as datatypes. This should extended to Floats and Strings.

### Usecases

Especially OSC support more datatypes than Integer.

**Comment by Julusian** [comment]
What do you expect to be done here?

Strings work very nicely in custom variables already, I haven't tried with floats

**Comment by sstaub** [comment]
I need to manipulate OSC float variables by button press.
I need also to manipulate OSC messages. e.g. : 
I want change following OSC message from `/eos/wheel/course/intens` to `/eos/wheel/fine/intens` and back by button press.

**Comment by Julusian** [comment]
ok, what specifically are you trying to do that doesn't work?

I can manipulate and display both float and string based variables:
![image](https://user-images.githubusercontent.com/1327476/203425187-a6a5eb25-d649-4959-9c69-5ce49bf49c80.png)

**Comment by sstaub** [comment]
Thank you, I will try it. I thought only integers were supported.

**Comment by Julusian** [comment]
@sstaub did this work for you?

**Comment by sstaub** [comment]
Thank you for that advices, it works as expected
