### ISSUE TITLE
Triggers not allowing variables to be selected[BUG]

### ISSUE THREAD

**Issue by AndrewApi** [bitfocus/companion#2196]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When creating a new trigger the variables drop down list does not work allowing you to select the required variable
![image](https://user-images.githubusercontent.com/46345232/203573326-b29d16c4-2f7b-48f7-ad1d-32aa9242f6ed.png)

### Steps To Reproduce

1. Trigger Tab
2. Add New Trigger
3. Select Feedback
4. Select variable dropdown arrow

### Expected Behavior

Select a list of variables

### Environment (please complete the following information)

```markdown
- OS:Wnidows 10
- Browser: Edge and Chrome
- Companion Version: 2.4.0 (2.4.0+4804-beta-d5edcf5a) running on Pi
```

**Comment by Julusian** [comment]
Thanks for reporting this!

It is fixed in the latest beta

**Comment by AndrewApi** [comment]
Great thank you, just updated, triggers work, physically connected Streamdeck now does not (just the Elgato logo), it has been working all day. Tried rebooting a number of times.

**Comment by Julusian** [comment]
I don't see how that could be related to the fix for this, the changes were purely in the ui code, nowhere near anything that handles streamdecks..

**Comment by AndrewApi** [comment]
It does not see it even if you force a rescan
