### ISSUE TITLE
export with optional formated JSON

### ISSUE THREAD

**Issue by ComingHOME-Darmstadt** [bitfocus/companion#2198]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

It should be possible to export with formated JSON instead to have one row in the config-file.

### Usecases

If you will track changes in the config-file with a version control you must now format JSON manually.
With an option in the export-dialog you can omit this necessary step.

**Comment by Julusian** [comment]
I am open to this (and made the same request myself in another project).

Perhaps this conflicts with the idea #231, or maybe not. It could be allowed to export 'compressed' (in a zip) and 'uncompressed' (multiline json).

**Comment by Julusian** [comment]
This is possible in 3.2 (current beta builds).

The default export format is now compressed, with an option to export uncompressed which is pretty formatted json
