### ISSUE TITLE
Set page/button(bank)/step with a variable

### ISSUE THREAD

**Issue by sstaub** [bitfocus/companion#2199]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

It should possible to set the page number with a variable, there should also an internal variable for the recent page number which could also stored in a custom variable. See also #1909

### Usecases

I want to create a one button action for changing the page numbers, each click should increase the page number and should go back to the first page number after a defined number of pages.

**Comment by BBrazner** [comment]
+1

**Comment by sstaub** [comment]
This should also for bank(button number) and button step.

**Comment by Julusian** [comment]
All of the internal actions have accepted variables for a couple of days.
The new variables wanted will be covered by https://github.com/bitfocus/companion/issues/2071, closing in favor of that task
