### ISSUE TITLE
Module Request: GrandMA 2 Telnet

### ISSUE THREAD

**Issue by Deanbau** [bitfocus/companion#22]
See : 
https://help2.malighting.com/Page/grandMA2/remote_control_telnet/en/3.3

Commands could include:

Execute Sequence number
Execute Macro
Dead Black Out toggle

In selected sequence
 - Next cue
 - Previous cue
 - Goto X cue

**Comment by willosof** [comment]
This module now accepts everything you can type in the MA command line.
