### ISSUE TITLE
JS error on every action

### ISSUE THREAD

**Issue by timothygruetzner** [bitfocus/companion#220]
Every action, no mater what, forces a JS error. Restarting of the application does not help, neither could I identify a certain pattern before the error pops up.

**Environment**
Windows 10, Version 1803, Build 17134.228
Chrome Browser, Version 69.0.3497.81, 64bit
Companion v. e1d7e4a30e

![image](https://user-images.githubusercontent.com/22869208/45174962-752c7680-b20c-11e8-8870-3b0eb072fd93.png)

**Comment by willosof** [comment]
Ouch. We'll look into that. Try deleting your db file!

**Comment by timothygruetzner** [comment]
And how would I do that? I can't seem to open the asar archive without some sort of additional tool.

**Comment by PerRoine** [comment]
as far as i can understand this must be a privilege issue on windows stemming from fs-extra dependencies in DB.js

**Comment by haakonnessjoen** [comment]
Can people test if this has been resolved in build 5c80b99 now?

**Comment by timothygruetzner** [comment]
Seems to work with said build.

**Comment by haakonnessjoen** [comment]
Fixed by 5c80b99
