### ISSUE TITLE
[BUG] Triggers and schedules, color change

### ISSUE THREAD

**Issue by desertdognl** [bitfocus/companion#2203]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When adding a color related action to a trigger, the color picker is in an underlying (z-index) window and can't be chosen. Trying to pick a color leads to exiting the trigger without saving

### Steps To Reproduce

1. Go to Triggers
2. Add a new trigger of change an existing tigger
3. go to action part
4. click browse
5. add 'Button Background Color'
6. Click done
7. Click background color

### Expected Behavior

Color picker should be in top window

### Environment (please complete the following information)

```markdown
- OS: Mac OSX 13.0.1
- Browser: Chrome 107.0.5304.110 (Official Build) (x86_64)
- Companion Version: 2.4.0 (2.4.0+4877-v2-4.0-cd0b68c6)
```

**Comment by Julusian** [comment]
This is fixed in the latest beta.

Im going to leave this open as a reminder to include it in a 2.4.1 release
