### ISSUE TITLE
[BUG] StreamDeck+ dial does not trigged any left/right/press actions

### ISSUE THREAD

**Issue by rse** [bitfocus/companion#2205]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

With the brand-new StreamDeck+ and even the latest Companion 2.4.0 (2.4.0+4877-v2-4.0-cd0b68c6), the dial buttons seem to be not working. I've created a button with "Enable Rotary Actions" enabled and right/left/press actions. I can see the button on the touch display of the StreamDeck+ and I can even trigger the press action through a touch on the touch display. But when I turn left or right or even press the dial no left/right/press actions are triggered. Not even the press action. As a wild guess I even tried with "Enable connected Loupedeck Live devices" enabled in the Settings (as the LoupeDeck also has those rotary actions), but even does does not help. I'm under Windows 11 22H2.

### Steps To Reproduce

1. Create a button with "Enable Rotary Actions" enabled and with a left/right/press action
2. Show the page on the StreamDeck+ device
3. Press the button on the touch screen
4. Press the dial
5. Rotate the dial left
6. Rotate the dial right

### Expected Behavior

1. Press action should be triggered by touch screen press
2. Press action should be triggered by the dial press
3. Left action should be triggered by turning the dial to the left
4. Right action should be triggered by turning the dial to the right

### Environment (please complete the following information)

```markdown
- OS:Windows 11
- Browser: Chrome or Firefox
- Companion Version: 2.4.0 (2.4.0+4877-v2-4.0-cd0b68c6)
```

**Comment by Julusian** [comment]
Are you enabling the rotary actions for the row below the touch strip?
We are handling them as separate controls

**Comment by rse** [comment]
Oh, my fault in completely missing this point. I was under the impression that the touch display buttons are 1:1 tied to the dials and hence Companion just uses a 4x3 button matrix for the StreamDeck+. You're right: when I use a 4x4 matrix (using different buttons for the dial row) it works like a calm! Sorry, entirely my fault in thinking into the wrong direction. Many thanks for the clarification.
