### ISSUE TITLE
Support Windows 10 ARM

### ISSUE THREAD

**Issue by Kinderix** [bitfocus/companion#2207]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The app doesn't run on Windows  10 ARM version. Is there any way to run it?

### Environment (please complete the following information)

```markdown
- OS: Windows 10
- Browser: Chrome 
- Companion Version: 2.4.0
```

**Comment by D4rkSoul67** [comment]
Ok. Thanks for the response. Is there any possibility that in the future you will provide support for ARM versions?

**Comment by Julusian** [comment]
Closing in favour of #2933
