### ISSUE TITLE
[BUG] ATEM Feedback for Audio Controls No Longer Working in v2.4

### ISSUE THREAD

**Issue by kmiller1357** [bitfocus/companion#2211]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

ATEM for classic audio controls like Mix Mode used to provide Feedback correctly.  After updating to v2.4 none of the ATEM Audio FEEDBACK functions work for any of the ATEM Classic Audio Controls I tested.

I guess its possible this could be a module issue if the ATEM module was updated, but since it appears to affect the FEEDBACK function for ALL ATEM Audio functions, I am suspecting that a change in Companion is causing the issue.

One Case Which Fails: ATEM Classic Audio/ MIX MODE/ XLR/ Toggles ON/OFF with Feedback configured for Green or Red BACKGROUND color.  One of the configured colors is provided but never changes, even though the MAIN FUNCTION of switching the XLR input On and Off does work.  That is, it is only the FEEDBACK that is not working.

### Steps To Reproduce

ATEM Module/Classic Audio Function/ XLR input/ ON-OFF TOGGLE/ FEEDBACK set to change Background Color.
Main Function (XLR ON/OFF works; but Feedback triggered Background Color change is not working.

### Expected Behavior

In older versions the ATEM Classic Audio Functions all provided proper FEEDBACK including supporting Background Color change.

### Environment (please complete the following information)

```markdown
- OS:Win 10
- Browser: Brave
- Companion Version: 4.2
```

**Comment by Julusian** [comment]
This was a bug in the atem module.
With some changes for better variables for audio, the call to recheck the feedbacks was never being done.

Itll be in the next beta build
