### ISSUE TITLE
[BUG] v3: action subscriptions don't fire on creation of action

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#2213]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Companion v3.0.0+5329-develop
An action subscription fires properly when a parameter of an action is changed, but it doesn't fire when the action is created. It should fire in both scenarios.

### Steps To Reproduce

Create a subscription for an action using `myAction.subscribe = (action) => {}` and then create an action in companion. Normally that subscription function would be called when the action is added, but it isn't. You can verify that the action subscription is called when editing the action.

### Expected Behavior

subscription called when adding an action

### Environment (please complete the following information)

```markdown
- OS: MacOS
- Browser: Safari
- Companion Version: 3.0.0+5329-develop
```

**Comment by Julusian** [comment]
You can fix this by updating `@companion-module/base` to `~1.0.0`.
You updating to the next build of companion. I am hoping by releasing 1.0, that we can reduce this annoyance of having to update both simultaneously..

**Comment by MeestorX** [comment]
Ty!
