### ISSUE TITLE
[BUG] v3: UI issue on Safari

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#2214]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On FF and Edge, the "switch" to enable/disable a module is above the "EDIT | DELETE" buttons.
On Safari, it's to the left and not centered.

FF/Edge:
![image](https://user-images.githubusercontent.com/29129658/205101895-227f396b-92dc-4593-9676-44a6d774c694.png)

Safari:
![image](https://user-images.githubusercontent.com/29129658/205101953-49e65b46-48ef-453e-9fd8-c5e659061b6e.png)

### Steps To Reproduce

Fire up the Companion UI on Safari

### Expected Behavior

Layout should be the same across browsers

### Environment (please complete the following information)

```markdown
- OS: MacOS
- Browser: Safari
- Companion Version: 3.0.0+5329-develop
```

**Comment by Julusian** [comment]
What version of safari?

**Comment by MeestorX** [comment]
Latest for MacOS, I think 15.6.

I haven't checked iOS but usually any ui issues on one show up on the other.

**Comment by sstaub** [comment]
I see this issue also and it depends on the width of the Safari window.

**Comment by Julusian** [comment]
This should be fixed now

**Comment by MeestorX** [comment]
It still seems to be broken in 3.1.0+5401
