### ISSUE TITLE
Use another buttons style: selective properties

### ISSUE THREAD

**Issue by Curtismacd31** [bitfocus/companion#2219]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

in beta build (companion-2.2.0-ce31f8c9-3694-win64) when using feedback  to "use another buttons style" to set many buttons color it would take the color and text color. In the newer versions of the the beta build it takes all the button attributes including text value. So all buttons using the "use another buttons style" now all have they same button display name as the original button.

### Steps To Reproduce

1. Set a button color and text color
2. add a new button
3. set new button feedback to "use another button style" 
4. new button now uses original button name as well as color

### Expected Behavior

use original button color and text color but not name, keep new button name.

### Environment (please complete the following information)

```markdown
- OS: Win10 64Bit
- Browser: Chrome
- Companion Version: companion-2.2.0-ce31f8c9-3694-win64
```

**Comment by davidjoshuaford** [comment]
I was searching for open requests to update "selective" parameters of the button mirroring, and found myself back here!

Could we update the "use another button's style" to include all parameters by default (fully mirrored), and then if the user crosses off certain parameters, that parameter won't pass through? 

Use case: I want to take the Record Duration text from a Record button ("00:00:00") and reformat it onto a different button, but I also want the color to update (ie the original red text will pass through when recording), but not to change any other parameters, such as the newer button's PNG. 

<img width="570" alt="Screenshot 2023-03-13 at 2 53 34 PM" src="https://user-images.githubusercontent.com/76959770/224802956-18ab1f5f-491f-4e4a-8c85-b2f09bc94534.png">
