### ISSUE TITLE
Button debounce

### ISSUE THREAD

**Issue by DrewLX** [bitfocus/companion#222]
**Describe the bug**
I've used Companion on a few shows and have had issues with 'double' presses. In particular when cutting on an ATEM, it will flicker and cut back. The option to have a debounce time - ideally adjustable - would actually make me use this for shows.

**Ideal behavior**
Set a time, in milliseconds, where button presses are ignored following a press. A default of 250ms should suffice.

**Comment by haakonnessjoen** [comment]
Have you upgraded the firmware of your streamdeck with the elgato stream deck application? In one of the first upgrades, they added debounce.

**Comment by DrewLX** [comment]
I've just re-flashed the firmware, the version didn't update but the problem does seem to have gone - weird! Thanks for your speedy response
