### ISSUE TITLE
Add `Internal: Rotate left/right button` action

### ISSUE THREAD

**Issue by who2us** [bitfocus/companion#2226]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

you have made an option to click or activate another button from another page or function, can we have the same with the rotating encoders?
    

### Usecases

  I might want to call a rotate function or a list of commands, that derives from rotational movement. 
this feature is all ready possible with buttons and calling the functions from other pages.
I merely want to choose if its a button or an encoder.

**Comment by Julusian** [comment]
This is implemented in the 3.0 betas
