### ISSUE TITLE
[BUG] IN Beta and Dev, My PC won't find the Streamdeck +, but when running 2.4.1 it does. 

### ISSUE THREAD

**Issue by a1whittaker** [bitfocus/companion#2230]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

IN Beta and Dev, My PC won't find the Streamdeck +, but when running 2.4.1 it does. 
I also can't find where to program rotary encoders.

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by Julusian** [comment]
Have you read the documentation? https://github.com/bitfocus/companion/blob/master/docs/7_surfaces/elgato_streamdeck.md#stream-deck-

I'll take a look into why it isnt working in beta

**Comment by Julusian** [comment]
Does anything show in the log?
I am able to use mine in the beta versions

**Comment by Drolalan** [comment]
I have the same issue. Log is empty.

**Comment by Julusian** [comment]
Is this still an issue? 
What os are you using?

**Comment by a1whittaker** [comment]
Hi, Looks to have fixed it self. I reimaged my PC.


Anthony Whittaker

Technical Services Coordinator

Technology Support | Digital Business Solutions

QUT | X Block, Level 1 | Gardens Point Campus

2 George Street, Brisbane QLD Australia 4001

GPO Box 2434 Brisbane QLD 4001

Ph. (07) 3138 9201 | ***@***.******@***.***>

[cid:ed3ac14a-d3d2-4945-be44-7fce06c9ac22]

CRICOS No. 00213J | ABN 83 791 724 622 | Acknowledgement of Traditional Owners<https://www.qut.edu.au/about/our-university/acknowledgement-of-traditional-owners>

P Please consider the environment before printing this email

________________________________
