### ISSUE TITLE
Per page device offset / Device offset action

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion#2231]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I would like to be able to define a device offset per page per device.  Or maybe an action so that when a page is selected I have the ability to got to page X with Offset X Y on Device Z. 

### Usecases

Use case would be that I have a few pages where I want the full page show if on an XL but only certain buttons if on a regular 15 key deck.  I do this now with the layout itself BUT have a need ergonomically to have a few important buttons on the bottom right side of the stream deck.  I want these buttons to be visible whether viewed on an XL or regular.  I could rebuild all the pages to have the buttons I need all on the right side of the deck then use the per device offset but I have a pretty extensive build and that would be tons of work and reprogramming triggers etc.

Thank you!

**Comment by dnmeid** [comment]
We are working at a system to place surfaces freely and project your programming to them with windows.
The windows will allow for your usecase with a similar effort than defining an offset per page.
So it is very unlikely that we introduce per page offsets in between.
