### ISSUE TITLE
Reaper connection doesnt work anymore [BUG]

### ISSUE THREAD

**Issue by Exenye** [bitfocus/companion#2235]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Since installing the latest reaper version v6.71, the streamdeck doesnt communicate with reaper anymore.

Companion states the connection with reaper is still working but reaper deosnt get any osc messages from either cmpanion GUI or the elgato streamdeck connected to companion.

Any ideas how to fix this?

I have so much stuff on the streamdeck, its very hard to work without in now..

Any help is appreciated

### Steps To Reproduce

Use the streamdeck
press any button

### Expected Behavior

it should run the action behind the button

### Environment (please complete the following information)

```markdown
Windows 10
Elgato Streamdeck XL
Google Chrome
Reaper v 6.71
AMD x570 board with 3700x, RX 6700 XT and Vengance 32gb ram
```

**Comment by Julusian** [comment]
What version of companion?

**Comment by Julusian** [comment]
Closing as there is not enough information to work from
