### ISSUE TITLE
Wrong button activated from Streamdeck [BUG]

### ISSUE THREAD

**Issue by atscomms** [bitfocus/companion#2239]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After updating Companion to V3.0.0 (3.0.0+5404-beta-7574e375) and updating Streamdeck XL to V6.0.1.17722
A Streamdeck button (in mixed mode) set to fire Companion button #X will fire button #X -1 (ie: 5 instead of 6)
Release V 2.4.1 works properly

### Environment (please complete the following information)

```markdown
- OS:Windows 10
- Browser:Firefox
- Companion Version: 3.0.0 (3.0.0+5404-beta-7574e375)
- Streamdeck XL Version: V6.0.1.17722
```

**Comment by Julusian** [comment]
This is fixed now

**Comment by atscomms** [comment]
Wonderful, thanks.
Which version includes the fix?

**Comment by Julusian** [comment]
5410

**Comment by atscomms** [comment]
Thanks.
I only see 5401 as Experimental and 5413 as Beta.
