### ISSUE TITLE
Support port 80/443

### ISSUE THREAD

**Issue by fkmobile** [bitfocus/companion#2240]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Allow Companion to run as the default webapp on a device.  This reduces port complexity and confusion for end users that are using the emulator.

**Comment by Julusian** [comment]
What happens when you try to set to those ports?

**Comment by fkmobile** [comment]
Currently, only a 4-digit number is accepted (Mac OS).  80, 443, etc  can be input but the Change button does not make any change.  Any 4-digit number is accepted.

**Comment by Julusian** [comment]
Ah. Applications have to be run as root to bind to ports below 1024, so when we attempt to use a port below 1024 it fails so we fallback to 8000.
Maybe there is something we can do to make it possible to do without running as root (running as root would be a bad idea), but I'm not sure how worth the time it would be to figure out

**Comment by fkmobile** [comment]
Interesting.  Is this a mac only limitation?
Apache and Nginx are able to run their web servers at lower ports.  May need to review how they have done it.
For now, we have an extra apache web server running to do an HTTP redirect to the Companion page.

**Comment by Julusian** [comment]
No, the same is true for linux. Not sure about windows.

According to https://formulae.brew.sh/formula/nginx, you have to run nginx as sudo (root) to be able to use port 80. Running something like nginx as root is a lot safer than companion, as it has a much better security model, and any paths accessed are defined in its config file. For companion, it would mean that anyone who can access the webui will have root access to your machine (through the `internal: run shell command` action).

**Comment by Julusian** [comment]
As this isn't an easy thing for us to solve, I am going to close this.
For those who want this, the easiest solution is to use nginx or an alterative as a reverse proxy, which google will be able to provide guides on setting up.
