### ISSUE TITLE
variable to value with in a function

### ISSUE THREAD

**Issue by who2us** [bitfocus/companion#2241]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I've always wanted to be able to adjust the values of functions on the fly either based on feedback or by another variable. (in this case, I'm using a rotary encoder from the stream deck.)

### Usecases

so there are a number of functions within the different plugins (ie, "Philips-hue: Lamps_Switch_Bri" & "Philips-hue: LightGroup_Switch_Bri" &  "internal: Set surface with s/n brightness" & "atem: Transition: Change rate" & "Spotify: Set Volume to Specific Value")

it would mean the world to most people to be able to set and change variables and apply them to modules (for output to devices)

**Comment by Julusian** [comment]
I believe this is covered by my plan in https://github.com/bitfocus/companion/issues/1187. I am closing in favor of that task

The problem that task is trying to solve is that modules currently expose actions (do a thing), feedbacks (is something true or how should this button look) and variables (some value). The aim is to replace variables with a better 'properties' system, that will allow modules to expose 'values' to companion that may be readonly or may be writable. And that should allow modules to not need to expose actions, feedbacks and variables for the same bit of data.   
These properties will then be able to do as you desire
