### ISSUE TITLE
Button style actions

### ISSUE THREAD

**Issue by sstaub** [bitfocus/companion#2242]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

It should possible to change the button style of any button. Button style actions seems only working with the selected button.
I want to change the style (text, background color, text color) of any other button. e.g.:
with the press of button 1.1 I want to change the text of button 1.3

**Comment by Julusian** [comment]
![image](https://user-images.githubusercontent.com/1327476/208245939-89b7005b-6076-41bf-b477-a086daa81ff6.png)
This is working for me

**Comment by sstaub** [comment]
You misunderstood, it is for the button you selected. But there is no way that I can change the styles for other buttons.

**Comment by Julusian** [comment]
That action was on 1.9 and changed 1.11 as it shows it will

**Comment by sstaub** [comment]
Did I understood it well, that bank number is the button number?
