### ISSUE TITLE
Rename "Bank" to "Button"

### ISSUE THREAD

**Issue by sstaub** [bitfocus/companion#2244]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Some actions use the word "Bank". This is semantic misleading it should replaced with "Button".

**Comment by sstaub** [comment]
Thank you for doing this. Found some items which must also renamed:
- Internal actions
  - Skip bank step
  - Set bank step

**Comment by sstaub** [comment]
As a consequence of renaming all remote commands (TCP/UDP, HTP, OSC) needs also to change from `bank` to `button`

**Comment by Julusian** [comment]
I can't find any more user facing uses of `bank` (other than protocols), although as there are  1084 uses of `bank` in the code it is hard to say for certain.

In 3.1 we should work on renaming these, but many will go away as part of other refactoring.

For the protocols, they could be updated to support both `bank` and `button` keywords, but there is already a task to review/formalise/tidy them and it would be a good idea to not do major breaking changes there two releases in a row.

**Comment by Julusian** [comment]
This is done in 3.2 as much as I think it can for now. There are still hundreds of references in the code, but these are needed for backwards compatibility. Everything user facing is renamed, with the protocols having new endpoints/messages using 'button' instead. Again, the old naming is supported in the protocols to give users some time to migrate across.
