### ISSUE TITLE
Bug: build number not showing in GUI header

### ISSUE THREAD

**Issue by sstaub** [bitfocus/companion#2247]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Can you add the installed build number in the header? This would help for issues depending on build number.
<img width="357" alt="Bildschirm­foto 2022-12-19 um 09 50 24" src="https://user-images.githubusercontent.com/6450325/208385671-a7f19402-e205-4fa4-9cd1-0b3821d94920.png">

**Comment by Julusian** [comment]
It is supposed to be there, and is working for me.

What os are you on? Running from source or a build from the website?

**Comment by sstaub** [comment]
Using macOS and Safari, latest versions. The build comes from your website.

**Comment by Julusian** [comment]
Is this still happening for you?

I havent seen it in any of my testing

**Comment by sstaub** [comment]
The problem is an AdBlocken I use on Safari.
