### ISSUE TITLE
feat: [v3] support variables in feedbacks

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#2249]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Can't parse variables in a feedback callback ATM since `parseVariablesInString` returns a promise and the `feedback.callback` event can't be async?

### Expected Behavior

Some way to use variables in feedbacks.

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by Julusian** [comment]
This is expected.
While it was possible to parse variables in feedbacks in 2.4, they wouldn't react properly to changes, making their behaviour unpredictable. They would only be rechecked when the feedback changed, not when the variable changed.

**Comment by MeestorX** [comment]
Ok, so moving forward, how can we solve this in v3?
