### ISSUE TITLE
Discussions on Github

### ISSUE THREAD

**Issue by sstaub** [bitfocus/companion#2254]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

For simple questions and ideas, the Discussions tab on your GitHub rep will nice.

**Comment by Julusian** [comment]
[Slack](https://join.slack.com/t/bitfocusio/shared_invite/zt-1fsnlu7iv-YIjW9dRECR_VDZY8QX4r5A) is already used for this, with support and some ideas on [facebook](https://www.facebook.com/groups/companion). I'm not sure that we need another place for this

**Comment by sstaub** [comment]
I give Slack a try
