### ISSUE TITLE
Ability to do math operation with time / Define a variable as a "TIME" value.

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion#2256]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I would like some ability to define a variable as a time value and do math operations with it.  I am trying to set up a system to set trigger times via a UI on the buttons with actions.  This way I can adjust all of our automations via the Streamdeck itself without digging into the GUI.  I'm almost ther but its very convoluted dealing with MM >60 and HH etc.  This would be a huge help if I could define an event time then set a Time - Xmin for event Y etc with a trigger for something to happen with internal time = the trigger time.

**Comment by Julusian** [comment]
This is possible in the 3.0 betas using https://github.com/bitfocus/companion/pull/2253.

**Comment by obcocav** [comment]
@Julusian .  Finally getting back around to finishing this and upgrading my workflow for 3.0.  Still having trouble grasping how to do this with 3.0 though.  So if I have a time of 09:00:00.  What expression and variables would I use to set a custom variable to that time minus 45 minutes (08:15:00)?  Thansks!

**Comment by Julusian** [comment]
`secondsToTimestamp(timestampToSeconds('09:00:00') - (45 * 60))` is the simple form of it.
`secondsToTimestamp(timestampToSeconds($(some:variable-name)) - (45 * 60))` with the input time being a variable

**Comment by obcocav** [comment]
Got it.  Thank you!

**Comment by obcocav** [comment]
@Julusian. How about what I'm doing wrong with the formatting parameter?  Just trying to show the result as HH:MM.  Here's what I have:

secondsToTimestamp(timestampToSeconds($(internal:custom_SUNDAY_AM_TIME_TEST))-(45*60),hh:mm)

I'm sure its something simple but I'm learning as I go here. :)

**Comment by mysticalchemist** [comment]
> `secondsToTimestamp(timestampToSeconds('09:00:00') - (45 * 60))` is the simple form of it. `secondsToTimestamp(timestampToSeconds($(some:variable-name)) - (45 * 60))` with the input time being a variable


forgive my noobery, where do i put these strings? Into variable "internal: Modify Variable Value with Math Convert To Int Operation"?

**Comment by Julusian** [comment]
@mysticalchemist these only work in 3.0

Either in the button text once it is switched to expression mode, or with the 'set with expression' action

![image](https://user-images.githubusercontent.com/1327476/236816258-9870b64f-7b16-438a-ad50-4b22a6d666fd.png)
