### ISSUE TITLE
[BUG] Adding step11 and further have weird effect on previous steps

### ISSUE THREAD

**Issue by LikeThisReview** [bitfocus/companion#2259]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

WhenI add step11 to button in v3.0.0+5435 step3 shifts to step4 and step3 becomes empty (no action anymore). Sorry if this is a duplicate report

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by Julusian** [comment]
this should be fixed now
