### ISSUE TITLE
Minimise to system tray

### ISSUE THREAD

**Issue by silid** [bitfocus/companion#226]
**Describe the feature**
Have the ability to minimise to system tray to avoid accidental close.

**Is this platform dependent (windows, mac, ..)?**
No. Electron supports this on all platforms.

**If documentation is required to implement, do you know where to find it?**
Example of where this was added to signal:
https://github.com/signalapp/Signal-Desktop/pull/1676/commits/141eaef4eb3bb9dbbbe872491de68e18bcbf6192
https://electronjs.org/docs/api/tray

**Usecases**
Can be used to auto start companion to the system tray and leave running in the background.

**Comment by willosof** [comment]
We would love if you contributed this as source code if you're able :) Seems like you've done some research.

**Comment by willosof** [comment]
Fixed in 5d77929
