### ISSUE TITLE
update plugin to assign button to steam deck plus dials

### ISSUE THREAD

**Issue by srinivasvizag** [bitfocus/companion#2260]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by chibiconsulting** [comment]
How can the elgato-plugin v3.0.x be tested. Elgato seems to have the v2.x version on their plugins page.

**Comment by Julusian** [comment]
It will probably work to download the code zip from github https://github.com/bitfocus/io.bitfocus.companion-plugin/archive/refs/heads/master.zip and unzip it to the correct place on your computer.
According to Elgato that path should be
> On macOS, you will find it here:
> path ~/Library/Application Support/com.elgato.StreamDeck/Plugins/
> 
> On Windows, you will find it here:
> path %appdata%\Elgato\StreamDeck\Plugins\

**Comment by dustindmiller** [comment]
Click Left & Click Right aren't being sent from the Stream Deck app to Companion even with the code downloaded and extracted. (M2 MacBook Pro, Ventura, Companion 2.4.2, SD 6.1.0)

**Comment by Julusian** [comment]
> Click Left & Click Right aren't being sent from the Stream Deck app to Companion even with the code downloaded and extracted. (M2 MacBook Pro, Ventura, Companion 2.4.2, SD 6.1.0)

It requires Companion 3.0.  
Publishing of this updated version is waiting until 3.0 is released as the stable version, to avoid this confusion over it not working

**Comment by dustindmiller** [comment]
This makes so much more sense. Thank you!!
