### ISSUE TITLE
feat: scan USB devices on wake

### ISSUE THREAD

**Issue by echalupka** [bitfocus/companion#2262]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I have companion installed on my mac. When I disconnect and reconnect my laptop from the streamdeck (bringing my laptop to a different location then back) I have to manually select "Scan USB Devices" from the menu icon before my stream deck reconnects. I'd like this to happen automatically each time my mac wakes from sleep if companion is running.

**Comment by sstaub** [comment]
In v3 beta there is an item in settings called "Watch for new USB devices" this works on mac for reconnecting.
But for wake from sleep I didn't know if it works as expected.
