### ISSUE TITLE
Changing custom variables via HTTP not working

### ISSUE THREAD

**Issue by andik2000** [bitfocus/companion#2266]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi, im running the Beta 3.0 on Intel Mac - i want to send a custom variable value via HTTP as it is shown in the examples - but i'm getting an internal server error. In the stable 2.4 release it's working.
The variable is set up and i also used the example variable:
http://192.168.1.3:8000/set/custom-variable/cue?value=intro

Other actions like Pressing a button or changing text and style via HTTP request are working.

### Environment (please complete the following information)

```markdown
- OS: Mac Intel
- Browser: Safari
- Companion Version: 3.0 beta
```

**Comment by Julusian** [comment]
Thanks for reporting, this is fixed in build 5448
