### ISSUE TITLE
Button action press other button by address "page.bank"

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion#2268]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Allow to trigger an action by entering an address in the "page.bank" format.

Example:
3.25

Input could be string or variable.

### Usecases

I can use a custom variable and put a value in it in this format as input for PRESS/RELEASE action. It is currently possible to call the button using a variable, but I have to enter PAGE and BANK as separate values.

**Comment by dnmeid** [comment]
This is currently worked on. We are going to replace the page.bank location with a page/row/column location and you will be able to use this in option inputs.

**Comment by Julusian** [comment]
This is possible in 3.2 (current beta builds)
