### ISSUE TITLE
BMD SmartScope

### ISSUE THREAD

**Issue by SimonBick** [bitfocus/companion#227]
Would it be possible to add the ability to switch the monitors between Vectorscope, Waveform etc

**Comment by PerRoine** [comment]
It's already there but there is a bug in Core that we struggle with, try deleting the instance and put it in again and be sure to select smartscope when you create the instance, the bug sometimes but not always selects the wrong variant.

**Comment by SimonBick** [comment]
Thanks for the quick response, i will give it a try.
