### ISSUE TITLE
[BUG]  Cloning a trigger and then changing the conditions retains the original cloned conditions

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion#2270]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am in the process of chaning how some of my triggers and scheduling works.  To do this I cloned my current triggers and then changed the Conditions fields to the new set of parameters I want.  The cloned trigger however still executes at the original condition rather than the new one.  

### Steps To Reproduce

1.  Create a trigger
2. Clone it
3. Change conditions
4. See that trigger ignores new conditions and fires at the old time.

### Expected Behavior

To fire at the new condition

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by Julusian** [comment]
Is this in 2.4 or 3.0?

**Comment by obcocav** [comment]
2.4.1 latest stable.Sent from my iPhoneOn Jan 8, 2023, at 16:59, Julian Waller ***@***.***> wrote:﻿
Is this in 2.4 or 3.0?

**Comment by Julusian** [comment]
3.0.0-rc1 has been released, so we will not be doing another 2.4 release. This is working in 3.0
