### ISSUE TITLE
Test Actions in Triggers is not working (3.0)[BUG]

### ISSUE THREAD

**Issue by DVEntertainment** [bitfocus/companion#2275]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In Companion 3.0 the Test Actions button doesnt work. For example i try to change the background color with a button from a variable change. The trigger works, but when i press the yellow test actions button, nothing happens.

I believe this button should trigger the action that would normally be triggered by the event set in the trigger, but maybe i dont understand the purpose of this button.

### Steps To Reproduce

1. Make new trigger
2. fill in action to do when conditions are met
3. press test actions
4. nothing happens

### Expected Behavior

The set actions should be run

### Environment (please complete the following information)

```markdown
- OS: Windows
- Browser:Firefox
- Companion Version:    3.0.0 (3.0.0+5551-beta-35564151)
```

**Comment by Julusian** [comment]
thanks for reporting, this is fixed now

**Comment by DVEntertainment** [comment]
Great, thanx for the fast response
