### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LondonV** [bitfocus/companion#2276]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I installed Companion and then my streamdeck buttons that were setup prior were taken off the screen. Then the companion buttons stopped working as well and vanished from the streamdeck. Now I'm tryign to get back what I had prior to companion. What is the solution? When I unplug and replug in the streamdeck I get a flash of the old buttons I had setup but then they disappear every time. 

Any help would be great. This is interrupting my business. 

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by Julusian** [comment]
What version of companion?

It sounds like both companion and the streamdeck software think they have exclusive access to the streamdeck. If you want to run both bits of software at once, you need to tell companion to not use usb directly by enablign the plugin in settings. Or if you only want one, then make sure the one you do not want is closed and is not running in the tray

**Comment by Julusian** [comment]
I am closing this for now. In the future you should have better luck at getting a quick response on either slack or the facebook group
