### ISSUE TITLE
Move variable menu 

### ISSUE THREAD

**Issue by QuinnMatthews** [bitfocus/companion#2278]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Currently variables are a submenu displayed under the "Buttons" tab, however variables are really used outside of the context of just buttons (ie in triggers) so in my opinion, it would make sense to move variables up as it's own tab on the main menu. This would also allow for increased flexibility in how variables are presented to the user in the future due to the extra screen space. 
![image](https://user-images.githubusercontent.com/55562296/211696900-290908f8-4fe5-4ab6-ae0c-4ad762543448.png)

**Comment by dnmeid** [comment]
The whole structure of the Companion GUI is not very consistent. We will replace the plethora of menus and submenus and tabs and subtabs by a big tree some day. Look here: #2387

**Comment by QuinnMatthews** [comment]
Thanks for pointing that out @dnmeid I hadn't seen that discussion yet. I'm good with closer this issue in favor of a more comprehensive plan such as the one linked.
