### ISSUE TITLE
Companion plug-in for Elgato App does not work with newest versions of companion

### ISSUE THREAD

**Issue by zackdickinson16** [bitfocus/companion#2279]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Companion plug-in for the Elgato Stream Deck app doesn't seem to be working with the newest versions of Companion. When opening Companion it will not connect to the Elgato Companion plug-in and the Elgato Companion plug-in does not show up in the surfaces tab in the GUI. The only version of Companion I was able to get working with the Elgato app was companion V2.2.0

Here are the versions I tried of the applications

Companion v2.2.0 - Worked with Elgato Stream Deck v6.0.1 & v6.0.2
Companion v2.3.0 - Did not work with Elgato Stream Deck v6.0.1 & v6.0.2
Companion v2.3.1 - Did not work with Elgato Stream Deck v6.0.1 & v6.0.2
Companion v2.4.1 - Did not work with Elgato Stream Deck v6.0.1 & v6.0.2

### Environment (please complete the following information)

```markdown
- OS:
- Browser: 
- Companion Version:
```

**Comment by Julusian** [comment]
Have you enabled the plugin in the settings of companion?

**Comment by Julusian** [comment]
In my testing it does work, and there is not enough detail here to work from
