### ISSUE TITLE
Disable Devices via Button Toggle

### ISSUE THREAD

**Issue by IanTGreenwood** [bitfocus/companion#228]
**Describe the feature**
The ability to enable/disable instances via a companion button/action.

**Is this platform dependent (windows, mac, ..)?**
No

**Usecases**
This would be quite useful for things like slide or video playback control.  It would allow you to create a single button to advance both main and backup PowerPoint machines, then simply disable the one that you don't want to control.  This would reduce the number of buttons that you need to create for a typical scenario (Main Forward, B/U Forward, Both Forward).

Ideally this would have feedback so that you could have a toggle style button with visual indication if an instance is enabled or not.

**Comment by willosof** [comment]
Relates to #229
