### ISSUE TITLE
[BUG] v3: Pressing "Enter" when creating a custom variable crashes Companion

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#2280]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When creating a custom variable, after adding the name, if you press "Add", no problem, but if you hit "Enter", Companion restarts.

### Steps To Reproduce

1. Go to Custom Variables tab
2. Scroll to the bottom
3. Enter a name
4. Hit Enter
5. Companion Restarts

### Expected Behavior

Adding Custom variable, same as clicking "Add"

### Environment (please complete the following information)

```markdown
- OS: MacOS
- Browser: Safari Version 16.2 (16614.3.7.1.7, 16614)
- Companion Version: 3.0.0+5557-beta
```

**Comment by Julusian** [comment]
Fixed now

This didnt crash companion, but caused the webpage to reload. So not a particularly bad bug.

**Comment by MeestorX** [comment]
Oh, ok. I thought it was restarting because it brought up the warning popup that you get when you start companion.
