### ISSUE TITLE
v3 Internal Actions Name cleanup

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#2283]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Some renaming could help for the internal actions list since they're in alphabetical order.

Not sure of the prefixes, but here's some suggestions. They should at least each be grouped by SOME prefix so they're easier to find in the list.
[Companion Internal Actions Rename.csv](https://github.com/bitfocus/companion/files/10429529/Companion.Internal.Actions.Rename.csv)

### Usecases

Helps keep things organized!

**Comment by Julusian** [comment]
I haven't followed your list exactly, but all the internal actions and feedbacks are tidied up a bit

**Comment by MeestorX** [comment]
Minor suggestions...

`Button Skip step` is missing the colon
`Restart companion` should probably be `System: Restart companion` for consistency
Maybe `Connection: Enable or disable connection` should be part of `System:` or `Surface:` so it's not all by itself?
I would suggest that the word `Trigger` be removed from `Button: Trigger ...` commands to reduce confusion with the actual `Trigger` function in companion.
