### ISSUE TITLE
[BUG] install fails on linux

### ISSUE THREAD

**Issue by llamafilm** [bitfocus/companion#2284]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The `yarn.sh` install script fails on my linux machine.

### Steps To Reproduce

1. Clone the companion repo and switch to beta branch
2. Install node 18
3. Run `./tools/update.sh`

It hangs forever showing "Check Node version".
I added `set -x` to the beginning of `yarn.sh` and found the issue happens here:
```
$ ./tools/yarn.sh 
++ heading 'Check Node version'
++ echo -e '\033[1mCheck Node version\033[m'
Check Node version
+++ node -v
++ NODE_VERSION=v18.13.0
+++ node -p -e 'require('\''./package.json'\'').engines.node'
++ REQUIRED_VERSION='>=18.12 <19'
+++ npx semver --range '>=18.12 <19' v18.13.0
```

It's waiting for user input, but for some reason the prompt is not displayed in the terminal.  As a workaround, I ran that last line manually like this:
```
$ npx semver --range '>=18.12 <19' v18.13.0
Need to install the following packages:
  semver@7.3.8
Ok to proceed? (y) y
18.13.0
```

After that, the `update.sh` script worked.

### Environment (please complete the following information)

```markdown
- OS: Ubuntu 20.04
- Companion Version: 246cbf9f
```

**Comment by Julusian** [comment]
Thanks, this looks to be an issue that only occurs when `npx semver` hasn't been run before, and somehow hasn't been noticed.
I can reproduce it with a fresh clone in docker, so this is now fixed
