### ISSUE TITLE
[BUG] "internal: Set custom variable with expression" does not add the variables in the expression

### ISSUE THREAD

**Issue by LikeThisReview** [bitfocus/companion#2289]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

internal: Set custom variable with expression with custom variable A and Expression B+C returns 11 instead of 2 (so it concatenates 1 and 1 instead of doing a sum). Companion v3.

### Steps To Reproduce

1. Create 3 variables A, B, and C with current values 0, 1, and 1
2. Create a button with button text is variable A and Press Action is "internal: Set custom variable with expression" <custom variable A> <Expression A+B>
3. Push button Test actions or Shift+Button (in GUI) returns 11

### Expected Behavior

One and One is Two, unless I misunderstand the expression function

### Environment (please complete the following information)

```markdown
- OS: latest Mac OS with Apple Silicon
- Browser: Safari
- Companion Version: 3.0.0+5559
```

**Comment by Julusian** [comment]
yeah this is hitting a quirk in how javascript works.. 
I've fixed it by making it so that `+` (along with many other operators) converts both values to numbers first. This makes forming strings a bit more tedious, but will have to do

**Comment by LikeThisReview** [comment]
👍

Op di 24 jan. 2023 om 22:13 schreef Julian Waller ***@***.***>
