### ISSUE TITLE
Builtin module in core exposing actions for controlling companion

### ISSUE THREAD

**Issue by willosof** [bitfocus/companion#229]
The module should expose actions like:
* Enable/disable instances
* Tell the streamdeck that have been pressed to go to another page
* Tell another streamdeck to go to another page?
* Simulate pressing or releasing a bank (then one bank can press other banks)
* Clear log??
* More??

**Comment by haakonnessjoen** [comment]
* Action for flashing stream decks using brightness control

**Comment by DaveShep** [comment]
Following a Goto Page, a Back button would allow return to the calling Page

**Comment by willosof** [comment]
Fixed over a period of time. :)
