### ISSUE TITLE
[BUG]: UI crashes with `Objects are not valid as a React child`

### ISSUE THREAD

**Issue by tacvideo** [bitfocus/companion#2290]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Log displays:

Something went wrong:

Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Berrno%2C%20code%2C%20syscall%2C%20address%2C%20port%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### Steps To Reproduce

1. Restarted Companion to try clear error
2. May or may not have checked button programming
3. Left Companion alone for awhile (maybe 15-20 minutes)
4. Checked Log again and error was back

### Environment (please complete the following information)

```markdown
- OS: MacOS 13.1
- Browser: Microsoft Edge (109.0.1518.49)
- Companion Version: 2.4.1
```

**Comment by Julusian** [comment]
I am pretty sure this is fixed in 2.4.2, and in 3.0
