### ISSUE TITLE
Use custom variable contents in tcp commands (generic tcp, rosstalk, generic udp)

### ISSUE THREAD

**Issue by DVEntertainment** [bitfocus/companion#2293]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I would love to use the content of a custom variable in a tcp command. 
for example, my custom var holds the var "340" and i'm trying to send the command "FOCUS $(internal:custom_ID1)"
I want the module to send "FOCUS 340". But currenty it sends the whole $(blah).

I cant seem to get it done in the rosstalk nor generic tcp request module...
Would that be possible?

### Usecases

Anything tcp/udp related

**Comment by Julusian** [comment]
This currently has to be implemented within each module. Please open issues on the modules where you need it so that the module devs can do so.
