### ISSUE TITLE
[BUG] v3: Trigger actions cannot be re-ordered by drag/drop

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#2295]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the Trigger Edit menu,
Events and Conditions can be dragged/dropped to change their order, but Actions cannot.

Error shown in log when trying to drag:
`23.01.25 14:45:30 UI/Handler: Error in client handler 'controls:action:reorder': TypeError: Cannot read properties of undefined (reading '0') TypeError: Cannot read properties of undefined (reading '0')
    at m.actionReorder (/Applications/Companion v3-beta.app/Contents/Resources/main.js:2:2503312)
    at /Applications/Companion v3-beta.app/Contents/Resources/main.js:2:2515974
    at /Applications/Companion v3-beta.app/Contents/Resources/main.js:2:8198432
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

### Steps To Reproduce

1. Create a Trigger
2. Add more than 1 action
3. Try to drag an action to re-order
4. Doesn't change position

### Expected Behavior

Actions in triggers should drag reorder the same as Events and Conditions

### Environment (please complete the following information)

```markdown
- OS: MacOS
- Browser: Safari 16.2 
- Companion Version: v3.0.0+5581-beta
```

**Comment by Julusian** [comment]
I stumbled upon this typo last night, which should be fixed from 5585 https://github.com/bitfocus/companion/commit/06a46a5e333756deb8aca9e3f47b6101e1e63f33
