### ISSUE TITLE
Add ability to use machine name for connections

### ISSUE THREAD

**Issue by jwagg999** [bitfocus/companion#2296]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

The ability to use NetBIOS/WINS machine name when adding a connection, in addition to IP address.

### Usecases

Mobile setups could be connected to various networks with different IP schemes. The use of a machine name would eliminate reconfiguration of the connection for every network, making usage easier for non-technical users.
![companion-feature](https://user-images.githubusercontent.com/123598148/214699717-b0068525-3ef0-4722-bc11-c5ae1485bee0.jpg)

**Comment by Julusian** [comment]
This currently has to be supported per-module.
Please open an issue on the modules where you need this implemented
