### ISSUE TITLE
v3: Add large edit window for button text field

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#2297]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Now that expressions are possible, the edit window can be too small. I'm thinking of the button text input field, but there may be others as well.
Add a button to click and show a larger edit window than the 46 or so characters when needed.

### Usecases

A common expression I'll be using is:
`($(internal:custom_Fader)  == -32768) ? "-inf" : toFixed($(internal:custom_Fader) / 100, 2) + "dB"`

Would be great to have an edit window about the size of this one I'm currently typing in for these long expressions. I'm sure I'll have even longer ones in the future!

**Comment by Julusian** [comment]
expression input fields now all support multiline
