### ISSUE TITLE
Add post request for button png backgrounds.

### ISSUE THREAD

**Issue by buffos** [bitfocus/companion#2299]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

This is related to #2097 

I had a very bad experience using png background upload through url queries. I mostly get 431 errors (very long url request).
It is trivial to create another router endpoint (POST) just for the png. Provide there the base64 string and solve the issue.

### Usecases

It would be very easy for users to automate the change of buttons image background.

**Comment by Julusian** [comment]
This is in the beta builds now

**Comment by buffos** [comment]
I could not find any info on the endpoint and how to call it, at least not were the other supported calls are listed inside the app.

**Comment by Julusian** [comment]
![image](https://github.com/bitfocus/companion/assets/1327476/40c5a92c-04ac-4e41-bf4a-0fa87cfb18cd)

It's not mentioned there, but you can set the `png64` value in the same way
