### ISSUE TITLE
[BUG] Logs filling up CompanionPi SD Card

### ISSUE THREAD

**Issue by coleg06** [bitfocus/companion#2300]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I installed companion yesterday on a pi and the SD card is filling up really quickly for some reason. I traced it down to some log files (see the steps to reproduce for more info) and they are getting larger and larger quickly. I'd like to think this is an issue with companion, not the module as I'm not having this issue with any other installations of companion I have at other locations. 

My other installations I use include:
1x  - 2.2.3 (2.2.3+1-82b174d)
2x  - 2.3.1 (2.3.1+1-dc01ac7)
1x  - 2.2.0-rc2 (2.2.0-rc2+1-25a303b)

All of them also use ATEM module, some are running on Ubuntu virtual machines, some on Pi 4's. Either way, I'm not having this issue with other installations.

### Steps To Reproduce

1. Fresh install of Companion Pi downloaded from bitfocus.io (downloaded it 01-27-23 around 7am EST)
2. At the moment I am unable to test with non ATEM integrations but I don't know if the companion modules actually control their own logs or if companion itself logs events.
3. Observe `/var/log/daemon.log` and `/var/log/syslog`

### Expected Behavior

Not everything should be logged, or logs should be dumped after a certain amount of time. 

### Environment (please complete the following information)

```markdown
- OS: macOS Ventura 13.1 on M1 Mac mini, Pi 3 B+ with 32GB SanDisk SD
- Browser: 109.0.5414.87 arm64
- Companion Version: 2.4.1 (2.4.1+4898-unknown-9646192a)
```

### Additional context

`Jan 27 22:09:47 video-booth-sd launch.sh[603]: settings.multiViewers.2.windows.4
Jan 27 22:09:47 video-booth-sd launch.sh[603]: settings.multiViewers.2.windows.5
Jan 27 22:09:47 video-booth-sd launch.sh[603]: settings.multiViewers.2.windows.6
Jan 27 22:09:47 video-booth-sd launch.sh[603]: settings.multiViewers.2.windows.7
Jan 27 22:09:47 video-booth-sd launch.sh[603]: settings.multiViewers.2.windows.8
Jan 27 22:09:47 video-booth-sd launch.sh[603]: settings.multiViewers.2.windows.9
Jan 27 22:09:47 video-booth-sd launch.sh[603]: settings.multiViewers.2.windows.10
Jan 27 22:09:47 video-booth-sd launch.sh[603]: settings.multiViewers.2.windows.11
Jan 27 22:09:47 video-booth-sd launch.sh[603]: settings.multiViewers.2.windows.12
Jan 27 22:09:47 video-booth-sd launch.sh[603]: settings.multiViewers.2.windows.13
root@video-booth-sd:/var/log# `

Here are some of the recent lines of the `daemon.log` file.

**Comment by Julusian** [comment]
did you download the 3.0 beta or the 2.4.1 version?

from the output you provided that looks like some debug logging from the atem module that was left in by accident. the 'new' constellations are incredibly noisy in network traffic which it appears to be logging. (based on that output it looks like you have a 4me, so it will be doing 4*16*60 lines a second from that traffic alone)

**Comment by coleg06** [comment]
I downloaded the 2.4.1 version.

Oh wow, yes we do have the new 4me Constellation HD switcher.

Should I try downloading the beta version or would I have the same issue?

**Comment by kraves-oz** [comment]
Perhaps a temporary fix: add a CRON job to delete the log regularly, until the module gets sorted.

**Comment by coleg06** [comment]
I figured out a temporary fix of disabling system logs (`sudo systemctl disable rsyslog`) to reduce SD card wear (instead of removing the log file and it rewriting it). 

Thanks for the suggestion, I think I'll mark this as resolved unless there's something else I need to do to let whoever works on the ATEM module know about this issue.

**Comment by Julusian** [comment]
I expect that the beta version should be fine, due to various changes.

> Thanks for the suggestion, I think I'll mark this as resolved unless there's something else I need to do to let whoever works on the ATEM module know about this issue

That person is me, so you don't need to do anything there :)

**Comment by Julusian** [comment]
In 3.0, it is logging the info level which will be a lot quieter than in 2.4.
Hopefully this means it is logging less
