### ISSUE TITLE
Not sure if this is a bug but it is a question.

### ISSUE THREAD

**Issue by Davrid** [bitfocus/companion#2303]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an installation of companion (Version 1.3.0 I think!) running successfully for several months. Had some issues recently where it would not start up correctly and was a bit unstable. Went to site and upgraded to version 2.4.0 and afterwards could not connect to the Birddog camera after. I looked for the earlier version on your website to rollback versions but it said not available so I found the earlier version on their laptop and re-installed. Got it all working again correctly but we get this Java error message popping up and when we click OK companion loads correctly onto Streamdeck and all is good. 
Any thoughts on how to get rid of this popup
![PXL_20230127_020611682](https://user-images.githubusercontent.com/123920034/215388222-429b0aaa-5775-4624-a218-3fbb4a9f300b.jpg)

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by Julusian** [comment]
I vaguely remember seeing this issue back in 2.2 or something around there.

To fix it, make a backup of your db file, then you are looking for a string which I think will look like `"emulator":{"config":{}` in it. Replace it with `"emulator":{` and hopefully the error will go away and not have corrupted your config

**Comment by Davrid** [comment]
Thankyou for the reply. I will attempt to do this when I next go to the system.

 

Thanks.  David Riddell – Mobile 0419 758650
