### ISSUE TITLE
[BUG] v3 "Cannot create control"

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#2304]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```23.01.30 08:19:59 Log/Controller: Application starting
23.01.30 08:19:59 Log/Controller: Build 3.0.0+5607-beta-ad4c25aa
23.01.30 08:19:59 Registry: configuration directory: /Users/andyb/Library/Application Support/companion/develop
23.01.30 08:19:59 Registry: launching core modules
23.01.30 08:19:59 Data/Upgrade: Upgrade from version 3 to 3 not necessary
23.01.30 08:19:59 Log/Controller: Sentry error reporting configured
```
**23.01.30 08:19:59 Controls/Controller: Cannot create control "bank:1-8" of unknown type "press"
23.01.30 08:19:59 Controls/Controller: Cannot create control "bank:1-16" of unknown type "step"**
```
23.01.30 08:19:59 Service/OscSender: Ready to send OSC commands
```

### Environment (please complete the following information)

```markdown
- OS: MacOS
- Browser: Safari 16.2
- Companion Version: 3.0.0+5607-beta
```

**Comment by Julusian** [comment]
What did you do to get this?
Did you update from another version, or import a config?

**Comment by MeestorX** [comment]
After a `Reset All configuration`
Restarted, same error, still a blank config
Also seeing this error:
```
23.01.30 11:51:00 UI/Handler: Error in client handler 'connection-debug:subscribe': Error: Unknown connection Error: Unknown connection
    at /Applications/Companion v3-beta.app/Contents/Resources/main.js:2:8075338
    at /Applications/Companion v3-beta.app/Contents/Resources/main.js:2:8199363
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by MeestorX** [comment]
Should I try deleting the dB to restart and see what happens?

**Comment by Julusian** [comment]
so you did a full reset and it still has some controls in it? that is strange.

**Comment by MeestorX** [comment]
Indeed!
Should I delete the dB and try again?

**Comment by Julusian** [comment]
yeah that would be a good idea. now that they are there and failing to load there are most likely stuck

**Comment by MeestorX** [comment]
Deleted the dB. "Cannot create control" error is gone, but the other one still shows up.
```
23.01.31 10:22:07 UI/Handler: Error in client handler 'connection-debug:subscribe': Error: Unknown connection Error: Unknown connection
    at /Applications/Companion v3-beta.app/Contents/Resources/main.js:2:8075338
    at /Applications/Companion v3-beta.app/Contents/Resources/main.js:2:8199363
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by MeestorX** [comment]
Error message gone in v3.0.0+5617-beta.
