### ISSUE TITLE
[BUG]? ember+ commands don't work properly?

### ISSUE THREAD

**Issue by Bart-SL** [bitfocus/companion#2310]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello,
I'm trying to use Companion/StreamDeck to operate via ember+ protocol. The connection is set properly and I manage to use GPI through **Set Value Boolean**. And it works **perfect** (thanks!!).

But I cannot use any other types of data - Integer, Real or String. Of course the types match with the corresponding device's ember tree.
There's no error log in Companion but the command does not go out "from" it (it's not seen in eg. EmberViewer) so it won't come to the device either.
When using **Set Value String** I get "_Error TypeError: Cannot read properly 'contents' of undefined_". So is there any particular syntax of values other than boolean? Or the command just won't work OK...

### Environment (please complete the following information)

```markdown
- OS:Windows10
- Browser:Edge 109.0.1590.70
- Companion Version:2.4.1
```

**Comment by Bart-SL** [comment]
It seems it's not a proble on Companion side. Sending commands to other devices works fine. I have a problem only with LAWO PowerCore at the moment but trying to solve it.

**Comment by OliverWilkinson** [comment]
Hi Bart, 

We are experiencing similar issues with Lawo Powercore - If you do have any success I would appreciate any advice! 

Many thanks
Oliver

**Comment by Bart-SL** [comment]
Hello!
Well, yes I can say I succeded to control PowerCore. The easiest part is emberGPIO handling as it worked from the beginning. It's only a matter of proper IPs and ports handling. But I couldn't set any other ember parameters. Now I guess I know the reason - I was running Vistool with its own ember instance on OTHER port on the same machine Companion was started. When using only one ember+ connection with matching ports (in Companion and PowerCore) I can control other parameters (like Source params eg. PFL on or setting the value of a fader). So I can use setInt and setReal.
BUT still what is not working to PowerCore is setString command (eg. to set userlabel of a source). This is a bit hardly to understand to me because I can set the label "manualy" from ember+Viewer runing from the same machine.
What makes it even more confusing - I can set without ANY problem A__MIC8 parameters including a TEXT (via setString command)

anyway - good luck :)

From the other hand it'd be really helpful if StreamDeck/companion could READ ember+ states...

**Comment by OliverWilkinson** [comment]
Hi Bart, 

Thanks for getting back to me, sadly no luck for me so far, we are seeing the type error on any attempt to control the Lawo - Back to the drawing board for us! 

Many thanks
Oliver
