### ISSUE TITLE
Export File Dialog

### ISSUE THREAD

**Issue by sstaub** [bitfocus/companion#2311]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

In the moment Export saves in the download folder. There should a file save dialog to save to a path with a user given name.

**Comment by Julusian** [comment]
I am pretty certain this behaviour is decided by the browser, and there is nothing we can do to influence that.

I've tried to search docs for this, and the only 'useful' thing I found was to change a setting in Chrome

**Comment by sstaub** [comment]
I think there must a solution because importing have also a file menu like any application on macOS.

**Comment by sstaub** [comment]
The behavior is browser independent, with MS Edge there is also no file menu.

**Comment by Julusian** [comment]
But importing is different. If it didn't show a prompt how else would a website know what file to access on your computer? And if it could be done without you picking a file, that would allow malware infected sites to look around for something interesting

I have found an api which would allow this, but its experimental and requires being used over https. So won't work for us https://developer.mozilla.org/en-US/docs/Web/API/Window/showSaveFilePicker

**Comment by Julusian** [comment]
https://stackoverflow.com/questions/43649952/instruct-browser-to-make-user-select-location-for-downloaded-file

**Comment by sstaub** [comment]
I see that it should possible https://stackoverflow.com/questions/3802510/force-to-open-save-as-popup-open-at-text-link-click-for-pdf-in-html
But I have no programming experience with HTML, JS ... I do only C/C++ open source programming with Arduino

**Comment by Julusian** [comment]
From https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download

> How browsers treat downloads varies by browser, user settings, and other factors. The user may be prompted before a download starts, or the file may be saved automatically, or it may open automatically, either in an external application or in the browser itself.

I also tried it earlier and in Chrome it didnt change anything
