### ISSUE TITLE
[BUG] Step control confusing

### ISSUE THREAD

**Issue by sstaub** [bitfocus/companion#2314]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Step control gives confusing results, see the attached file
[step_bug.companionconfig.zip](https://github.com/bitfocus/companion/files/10571967/step_bug.companionconfig.zip)
I have 3 steps behind the "Text <x>" button:
1. Step: text color is white 
2. Step: text color is green
3. Step: text color is red
Stepping thru the "Text <x>" button makes 1. step text green, 2. step text color white and 3. text color red
which is not what programmed in the button steps.

Next problem is the action "Set current step"
I have 2 action behind the "BTN <x>" button:
Both set the step number of "Text 1" and "Text 2" to step 1 of "BTN 1" and "BTN 2"
I can see that step number changes but the action behind the steps, which should change the text color, are not executed.

### Steps To Reproduce

see above

### Expected Behavior

- Step action should follow the step numbering 
- Action "Set current step" should execute the action behind the step

### Environment (please complete the following information)

```markdown
- OS: macOS 13.2
- Browser: Safari 16.3
- Companion Version: latest beta
```

**Comment by MeestorX** [comment]
I think the "starred" step indicates the NEXT step that will be performed.
If you look at the button header, it will indicate which step will happen next.
e.g. button 1.2 will show `1.2.1 `if the next step will be step 1, `1.2.2` if the next step will be be 2, etc.

Not sure if that makes things clearer or if there's still an issue, but maybe that info is helpful?

**Comment by Julusian** [comment]
it looks like the zip file has a password, so I cant view your config.

Trying to rebuild that setup myself, it is behaving as I expect.

> I can see that step number changes but the action behind the steps, which should change the text color, are not executed.

The `Set current step` action is intended to simply change the step the button is on, and not to execute any actions from that button. 
It sounds like this is working as intended, but you are after a different action which doesnt exist currently.

**Comment by Julusian** [comment]
This is working as I expect:

When the top bar is `1.18.1`, pressing it will make the text go white (which is defined as step 1)
When the top bar is `1.18.2`, pressing it will make the text go red (which is defined as step 2)
When the top bar is `1.18.3`, pressing it will make the text go green (which is defined as step 3)

**Comment by sstaub** [comment]
I didn't understand the logic. The top bar indicates what happen next instead of the current state? This makes no sense.

**Comment by Julusian** [comment]
But what happens next is the current state. That number indicates the actions currently bound to the button.
If you have rotary actions enabled, they will be executed from the step as shown in the top.
If you disable the auto-progression, what should it show? it will keep running the actions from step 1 until changed with the `set current step` action.

One intended use case for steps is to make shift layers. You can set it up so that a group of buttons don't automatically progress the steps when pressed, and to change them to step 2 while a button is held and change it back to 1 when released.
What should the number in the top bar be here? Surely it makes sense for it to indicate what will happen?

**Comment by sstaub** [comment]
I understand the intention, and this I want also to achieve,  but it the solution have no logic.
When I start the GUI the first press of the "Text <x>" button does nothing and that's the problem.
Sorry, but I'm writing libraries for microcontrollers which use also real world buttons, and users will gives me an issue with this behavior. What is the init state and what should  happen next?!

**Comment by sstaub** [comment]
Meanwhile I understand the behavior you intend, but the action "Set current step" is misleading by it's name,
better will "Set next current step". 
Also the top bar indicating is misleading. If I see 18.3 I will think this is the current step, not what happens next.
Maybe better will indicate this behavior with "18.1*", the asterix will indicate that 18.1 is the next step.
But there should also an action to force a step which execute the actions behind, that is what I want to achieve with this action. This should in my example "reset" the step to the beginning.
Another problem for me is following example, e.g. I have two buttons with 4 steps behind.
When I'm on the second button on step 2, then I go button 1 to change the step. But when I press the second button again it goes to step 3. But I would like that the press of button 2 holds the last step. Any solution? I think your solution is missing a "restore last step" functionality.

**Comment by Julusian** [comment]
> When I start the GUI the first press of the "Text " button does nothing and that's the problem.

That entirely depends on what they are programmed to do. When using the internal actions to change button style, then yes that can easily happen. I really do not like those actions as they can cause so many edge cases such as this.  
Are not liking here that at startup all the buttons are reset back to the first step?

>  the action "Set current step" is misleading by it's name, better will "Set next current step".

I'm not opposed to changing this to be "set next step", and using that name everywhere. until the other day some places said next and some said current..

>Also the top bar indicating is misleading. If I see 18.3 I will think this is the current step, not what happens next.
Maybe better will indicate this behavior with "18.1*", the asterix will indicate that 18.1 is the next step.

I dont think a `*` will make it any clearer. If anything it will more confusing and I would expect many questions of 'what does the star mean?'  

Assuming we do the rename as discussed above, then I don't know what you would want to be shown there, as there is no current step. We know the next step, the step that comes before the next step and the last step that was executed.
If it shouldn't show the next step, then what should it show:
1) At startup
1) when step 1 includes an action to set the next step to 5
1) when next is step 2, and auto-progression is disabled so every press will execute step 2

> But there should also an action to force a step which execute the actions behind, that is what I want to achieve with this action. This should in my example "reset" the step to the beginning.

I am open to having this

> This should in my example "reset" the step to the beginning.
Another problem for me is following example, e.g. I have two buttons with 4 steps behind.
When I'm on the second button on step 2, then I go button 1 to change the step. But when I press the second button again it goes to step 3. But I would like that the press of button 2 holds the last step. Any solution? I think your solution is missing a "restore last step" functionality.

I don't entirely follow this. 

'I would like that the press of button 2 holds the last step.' I dont understand this
'"restore last step" functionality.' I dont understand what this should be or do

**Comment by krocheck** [comment]
The only thing I'd like to add to this discussion is that when I added this `.x` display, probably poorly, I intended it to show the "last run" cue of the stack, similarly to how a lighting console show the currently live cue and then you have the 'Go' button to execute the next one.

**Comment by Julusian** [comment]
It sounds like there isnt anything we want to do here.
I am open to changing it, but it needs some thought put into what to show in each of the scenarios above and probably more
