### ISSUE TITLE
[BUG] v3: Minified react error #185

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#2317]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When resizing the WebGUI, I see the following error:
```
Something went wrong:

Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.```

Clicking "Try Again" refreshes the screen and it's ok.

### Steps To Reproduce

1. Open the Web Gui in it's own window
2. Resize it to be smaller (quickly?)
3. Error shows
4. Press "Try again" and it refreshes and looks normal

### Expected Behavior

No error

### Environment (please complete the following information)

```markdown
- OS: MacOS 11.7.2
- Browser: Safari 16.2
- Companion Version: 3.0.0+5617-beta
```

**Comment by Julusian** [comment]
Its happening when the ui is in the one column layout. Its trying to measure the height of a component, but every time it tries it grows because its not limited by the window height anymore
