### ISSUE TITLE
Webbuttons don't respond unless streamdeck is on same page

### ISSUE THREAD

**Issue by JeffreyDavidsz** [bitfocus/companion#2321]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Be aware this is Companion 2.4.2! Client is using webbuttons on a iPad (but testing in Windows > Edge). Switching between pages doesn't work. Clicking on actions only works when the streamdeck is on the same page. Current Surface is beeing used, But considering the actions don't work I feel something else is going on.
Assigning this to myself, to keep track

### Environment (please complete the following information)

```markdown
- OS: Windows
- Browser: Edge
- Companion Version: 2.4.2
```

**Comment by Julusian** [comment]
@JeffreyDavidsz is there anything to do here with 3.0 about to be released?

**Comment by JeffreyDavidsz** [comment]
I'm not seeing this behavior in 30.0.0-rc1(but with no deck attached)
