### ISSUE TITLE
[BUG] "Current Surface" ("Set surface with s/n to page") not working when triggered by "Button Press and Release"

### ISSUE THREAD

**Issue by DanielBaulig** [bitfocus/companion#2322]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I "Press and Release" a button that contains a "Set surface with s/n to page" action with Surface set to "Current Surface" then the "Set surface with s/n to page" action doesn't actually switch to the set page.

If I manually tap on the button containing the "Set surface with s/n to page" action however, it will.

Replacing the "Current Surface" option with a fixed surface "fixes" the behavior (i.e. will change the page even when triggered by a "Press and Release" action, but obviously isn't going to work for multiple concurrently connected surfaces.

### Steps To Reproduce

- Add a button A on Page 1, containing a "Press and Release" action.
- Add a button B on Page 2, containing a "Set surface with s/n to page" action. Set the surface to "Current Surface", set the page to 3.
- Set button A's Press and Release action to trigger button B on page 2.

Go to page 1, tap on button A, notice nothing happening.
Go to page 2, tap on button B, notice the page switching to 3

Replace the "Current Surface" option on button B with the surface used for testing and repeat steps.

Notice how the page will not switch to 3 when tapping button A on page 1.

### Expected Behavior

Indirectly pressing a button should retain the information identifying the surface on which the original button was pressed, allowing for an indirect triggering of a "Set surface with s/n to page" action using "Current Surface"

### Environment (please complete the following information)

```markdown
- OS: Windows 10
- Browser: Chrome 109
- Companion Version: 2.4.1 (2.4.1+4898-v2-4.1-9646192a)
```

### Additional context

It seems like some metadata get's lost when invoking the Press and Release action vs directly tapping on a button. This metadata should probably be passed through to any Press and Release actions triggered from a button press.

**Comment by Julusian** [comment]
I am 90% certain that this is fixed in the 3.0 betas.
I don't expect there to be any more 2.4 releases

**Comment by DanielBaulig** [comment]
Thanks for the clarification! Is upgrading at this point recommended or should we wait until 3.0 officially hits "stable"?

**Comment by Julusian** [comment]
Some modules are known to be broken in 3.0, and some are probably working, but maybe broken. So it depends on what modules you use. There is an up to date list of the status of each https://docs.google.com/spreadsheets/d/153YDDxvtXw2zmdBmYqw3QrWkmCAVzwx6eCTXl3_2NX4/edit?usp=sharing

Installing 3.0 will make a copy of your current config, and will leave the current config untouched. so it is perfectly safe to install 3.0 to see if it works for you and then go back to 2.4 if it does not.

**Comment by DanielBaulig** [comment]
Thanks! I'll give it a shot.

**Comment by DanielBaulig** [comment]
Just want to confirm that this indeed is working correctly in 3.0. Closing ticket.

**Comment by DanielBaulig** [comment]
Just one little callout: the internal time_unix variable is gone in 3.0. It might be worth calling that out in addition to some of the components being not fully migrated yet. This broke some of the custom timers I had built. Can be relatively easily be replaced by `floor(unixNow() * 1000)`, but still worth calling out.

**Comment by Julusian** [comment]
@DanielBaulig thanks for pointing that out. There was a bunch of 'internal' actions/variables/feedback changes that were made for 2.4 that hadn't made it across to 3.0. They are now, so the `time_unix` and others are back
