### ISSUE TITLE
[BUG] Trigger Condition field label says 'Add feedback' instead of 'Add condition'

### ISSUE THREAD

**Issue by smellyspice** [bitfocus/companion#2324]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

build: 3.0.0 (3.0.0+5657-beta-8986fd01)

On the Edit Trigger page, under Condition, the combo box label says 'Add feedback' -- I think it should say 'Add Condition'

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:3.0.0 (3.0.0+5657-beta-8986fd01)
```

**Comment by 7tech7** [comment]
It seems everything is mixe up in the trigger area. It seems like **CONDITION** is renamed to **EVENTS**, but there we do not have a way to add variable, operation and value.

Please add them back
![trigger](https://user-images.githubusercontent.com/116564033/219870151-a1fda028-f2fc-447b-aaea-c2b46124284a.png)
  Thank You!

**Comment by Julusian** [comment]
@7tech7 

> It seems everything is mixe up in the trigger area. It seems like CONDITION is renamed to EVENTS, but there we do not have a way to add variable, operation and value.

This will give the same behaviour as 2.4:
![image](https://user-images.githubusercontent.com/1327476/219949346-b2ca0778-fc8e-4b59-939e-2f0a42139767.png)


Condition has been split out to have the events portion separate. A common request in 2.4 was wanting to run a trigger whenever a certain variable changed, but as the condition and event were the same thing, it was only possible to do something when the condition became true. This is now just one of many ways of using the triggers.

**Comment by Julusian** [comment]
The add dropdown has been changed to say 'Add Condition'
