### ISSUE TITLE
[BUG] Release Actions not executed after Step Increment

### ISSUE THREAD

**Issue by DanielBaulig** [bitfocus/companion#2325]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a button that delays two step increments by a second each and another final action after one more second. The idea is that I want the button to be depressed for at least 3 seconds before executing the final action while using increasingly aggressive colors in the feedback to indicate the progress towards the final action.

I then wasn't sure if the Release action of the original Step 1 would be used or the Release action of the step I had switched to, so I added the following actions to all steps, but to my surprise that didn't work. Upon Release I would abort all delayed actions and set the button back to Step 1. 

If I released the button before reaching Step 2, this works. But once Step 2 was reached releasing it at any time will continue running through all delayed actions and not run any Release actions, neither the Step 1 Release actions, nor any other Step release actions.

The button should either run the Release actions of the step it was pressed on or the Release actions of the Step it is currently on when Released. It should not run any Release actions.

### Steps To Reproduce

1. Add a button with two Press actions "Skip Step" delayed by 1000ms and 2000ms respectively. Leave the default configuration for these actions.
2. Add a third Press action (e.g. Press and Release button) at 3000ms respectively. Change the target button to some other button on the page.
3. Depending on what the intended behavior is, add the following two actions either to each Step or only to Step 1. The former is the foolproof way though.
4. Add the actions "Abort all delayed actions" and "Set current step" as Release actions.
5. 4. Disable the "Auto progress step" option on the button.
6. (Optional, for better visualization): Set the feedback of the button to "When Pushed", "Check Step", "Check Step", in that order. Set the two "Check Step" feedbacks to steps 2 and 3 respectively and change the background color on each of the feedback steps to a continuous color gradient (e.g. yellow, orange, red).

Tap and immediate release the button. Notice how the first color will briefly show up, but the button will return to it's default color once released (before 1000ms have passed). Also note how the little play indicator for delayed actions is cleared the moment the button returns to default colors. This is correct behavior.

Now tap and hold the button for at least 1000ms. Once the button is depressed for at least 1000ms the color will change to the second color in the sequence. Release the button now. Notice how the green play icon for delayed actions will *not* disappear and notice how the button will continue to cycle through the other actions (including skipping steps again and lastly running the final action). You can observe this by the colors of the button continuing to change and should also be able to verify that the final action was run. Also note how the button remains in step three at the end.

### Expected Behavior

The button should either run the Release actions of it's current step or those of the step it was in when originally pressed. This should lead to the button aborting all remaining delayed actions and returning to step one regardless of when the button is released.

### Environment (please complete the following information)

```markdown
- OS: Win 10
- Browser: Chrome 110
- Companion Version: 3.0.0+5654-beta-35e3c099
```

### Additional context

Note that it may make sense to run either the original step release actions or the release actions of the step changed to. I don't have a strong intuition which is better / more in line with user expectations and / or lead to more desirable outcomes. My gut feeling tells me it should probably run the Release actions of the step it is on once the button is released, but I am not 100% sure this is the correct choice. But it shouldn't just not run any release actions.

**Comment by DanielBaulig** [comment]
A small addition/correction for the steps: I forgot to mention that the "Auto progress step" option should be disabled for the button.

**Comment by Julusian** [comment]
First off, are you aware of the new 'duration group' (aka long press) functionality? It allows for defining this delay and abort flow in a much nicer way. I think it does hit the same issues though depending on what you are trying to actually achieve.

I'm honestly not sure if this is correct or not.

It feels like it could be correct, because you changed the step while the button was held, and it is 'aborting' the current press.
But also, it does feel slightly odd that they get skipped.

If it runs any actions I think it will have to be the ones from the step used for the press. Otherwise I don't think it will interact with the duration groups in a sensible way. 

The current behaviour is consistent with what happens if you change the current page while a button is held. The release actions in that scenario never fire, so perhaps this should behave similarly?

**Comment by Julusian** [comment]
Oh wait, when changing page, the release actions from the original page are run.  
So I think the best approach is that this should be consistent with that, and the release/held actions from the step where the press was started should be run.
