### ISSUE TITLE
[BUG] $(internal:date_dow) not available (for 0=sunday) in 2.4.2

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion#2327]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the 2.4.2 release the `$(date:date_dow)` appears to be broken.  Updated this week and ALOT of my triggers didn't fire today causing a mess.  Finally realized there were all looking to match DOW=0.  That variable is blank when called.  Any help appreciated!  The `$(internal:date_weekday)` IS CORRECT.  Just no DOW listing for today.  We have this interwoven with a ton of automation in our setup. @Julusian 

Thanks for all y'all do with Companion!

### Steps To Reproduce

1.  Call `$(internal:date_dow) ` 
2. See that variable is listed as blank. (at least currently on Sunday)

### Expected Behavior

Show DOW as 0 for Sunday.

### Environment (please complete the following information)

```markdown
- OS:WIN10
- Browser:Edge
- Companion Version:2.4.2
```

**Comment by obcocav** [comment]
So I know this has been working but now I went back all the way to 2.3.0 and its blank there too on another machine!  Is there some kind of Windows dependency that could have updated that is feeding the wrong data to Companion (not a coder so no idea if this makes sense).  But I know my setup worked being based on DOW=0 until this week and now multiple machines are showing DOW for today as blank.  Thanks!

**Comment by obcocav** [comment]
Ok so the this is definitely not a one time thing.  Happened again this morning.  DOW variable was blank.  Changed the day in Windows time, waited a few seconds for DOW to populate to 2, then changed it back and all is well.  @Julusian.  Any idea if this is squashable or do I need to rewrite all my triggers?  Really hoping not as I use some expressions with the DOW value.  Thanks!

**Comment by obcocav** [comment]
@Julusian.  I did some testing today and have some good data I think.  So I changed the time to 23:59 local on Saturaday and watched the DOW variable as it switched over.  It showed 0 just as expected and needed.  I then restarted companion.  It blanked.  Reset to 11:59 again and restarted the entire PC and it blanked again.  SO it appears that as long as Companion is running during the changeover to day 0 it works fine but if it is restarted or the PC rebooted on day 0 the variable blanks.  This explains my change as I have Companion restart itself on Sundays before service and just started doing that a couple weeks ago.  I hope this helps and maybe a bug fix made!  :)  Still waiting on Birddog and ProPresenter modules to jump over to v3.0.  Thanks for all yall do!

**Comment by Julusian** [comment]
I don't see any reason for this to have changed recently, the areas of relevant code havent changed since those additional date variables were added

There is a fix for this in the `stable-2.4` branch, but I don't know when/if that will be in a build

**Comment by Julusian** [comment]
3.0.0-rc1 has been released, so we will not be doing another 2.4 release
