### ISSUE TITLE
[BUG] Page increment and decrement

### ISSUE THREAD

**Issue by randytaber** [bitfocus/companion#2328]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If I program three page decrements, on button press, the page will decrement only twice....any actions thereafter are ignored...even if a time delay is enabled for each subsequent page decrement. I tried adding on button release commands, but I have found the same limitation

### Environment (please complete the following information)

```markdown
- OS:Mac Big Sur
- Browser: Chrome 110.0.5481.77 (Official Build) (x86_64)
- Companion Version: 2.4.2
```

**Comment by Julusian** [comment]
I don't know what was happening in 2.4, but in 3.0 this was resulting on only the one ever executing.

This was caused by the code delaying the page change briefly, to minimise the risk of other actions being blocked while the device handled the drawing. But reshuffling this has resolved it for 3.0
