### ISSUE TITLE
Webserver

### ISSUE THREAD

**Issue by somerockenguy** [bitfocus/companion#233]
Some sort of webserver so a phone or tablet could be used as an emulator, preferably with a customization button grid size

Would not be platform dependent

Having an ipad or adroid tablet as a larger 8x12 button control surface. Ability to use a second device to change through switcher test patterns and control a projector from FOH.

**Comment by PerRoine** [comment]
It' already under development, it will not be included in release 1.2.0 but we have been testing it in dev. builds
