### ISSUE TITLE
Press & Release based on Variable Problem with X32/M32 Fader Levels[BUG]

### ISSUE THREAD

**Issue by BrianMSimons** [bitfocus/companion#2336]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using the "internal: Button: Trigger press and release if variable meets condition" with the fader level from a channel on the X32 Mixer, it isn't using a number as the value.  It also includes the dB at the end.  So the only way you can get it to work is if you set the condition to equals, and set the value exactly as a string, such as -20dB.  The problem with this acting as a string and not a number, is that for any of the other compare options - greater than, less than, etc., it doesn't work.  I had the fader set to -20dB, and I tried setting it up to press another button if the fader is greater than -50dB, and it won't work.  I tried using the values -50 and -50dB and no dice.  However, as soon as I change the operator to equals, and the value to "-20dB" to match the mixer variable exactly, it works.  

### Steps To Reproduce

1. Create a button and add "internal: Button: Trigger press and release if variable meets condition"
2. Set the Variable to check to Fader: Channel X 
3. Set Operation to > or < depending on what you want
4. Set the Value to desired fader value, either as a number like -50, or a string like -50dB
5. The action won't work
6. If you set the operation to =
7. Then set the value to match the exact string of the fader value, such as -20dB
8. The action will work. 

### Expected Behavior

I would expect for a fader value to put in a number for the value, such as -50, and if my Operation is to fire when the value on the fader is great than that, such as -20 - the action will run.  I'm not a programmer, but I'm assuming it needs to have an operation that strips the "dB" and converts the string to a number.

### Environment (please complete the following information)

```markdown
- OS: Windows 11
- Browser:Chrome
- Companion Version:3.00+5667-beta7ff40a63
```

**Comment by Julusian** [comment]
I think that the best way forward on this would be to replace these actions with new versions such as `internal: Button: Trigger press and release if expression is true`. Ideally this would be better handled by #1052, but I think that is too far away to be a suitable substitute.

Actions such as that would allow for you (the user) to handle the conversion (or more complex conditions) such as `fromRadix($(internal:custom_aux)) > -20`

**Comment by Julusian** [comment]
This has been added in build 5682. Hopefully this solves your issue sufficiently

**Comment by Sion-Jones** [comment]
> I think that the best way forward on this would be to replace these actions with new versions such as `internal: Button: Trigger press and release if expression is true`. Ideally this would be better handled by #1052, but I think that is too far away to be a suitable substitute.
> 
> Actions such as that would allow for you (the user) to handle the conversion (or more complex conditions) such as `fromRadix($(internal:custom_aux)) > -20`

I’m not following how that helps this situation, the issue is having an unnecessary string at the end of a variable, meaning that various numerical features are unavailable, such as adding, comparing, and so on.
