### ISSUE TITLE
Insert, re-order and label steps

### ISSUE THREAD

**Issue by noiseboi** [bitfocus/companion#2337]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Currently it is only possible to add a step at the end of the existing step sequence. I would like the ability to insert additional steps between existing steps or append then move steps. Also, each step could have a label eg describing the function of the commands within that step.

### Usecases

This is of course possible by rebuilding the buttons but I have some buttons with 40+ commands, rebuilding these and testing when hardware is available isn't optimal. Labelling steps could help make programming and debugging easier. So essentially, ease and speed of programming, especially when importing legacy buttons from 2.x

**Comment by Julusian** [comment]
It is already possible to reorder steps, with the arrows next to the delete button for the step

**Comment by noiseboi** [comment]
Thankyou!

**Comment by Julusian** [comment]
This has been possible for a few releases
