### ISSUE TITLE
[BUG] Stream Deck XL: No longer displays buttons after update(v2.4.2)

### ISSUE THREAD

**Issue by jinsilgame** [bitfocus/companion#2339]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 I'am using Atem television studio hd switcher with stream deck xl. I've used companion for the stream deck xl in order to create buttons out of the Atem switcher. Yesterday, I updated v2.4.2. But right after installing the update, my stream deck xl stops showing the buttons while functions of the buttons are still working. Could you please let me know how to resove this issue? Thank you.

### Environment (please complete the following information)

```markdown
- OS: windows 10
- Browser: Chrome
- Companion Version: v2.4.2
```

**Comment by Julusian** [comment]
I think you will have better luck here asking on the facebook group, unless you can provide some details that will allow others to reproduce this.
I don't know what would be useful to know, but as noone else is having this issue it sounds like something specific to your machine.
