### ISSUE TITLE
HTTP actions

### ISSUE THREAD

**Issue by kultikom** [bitfocus/companion#234]
**Describe the feature**
Hi, why don’t we have some easy to use http actions?
So pressing a button -> calling an URL
Like in the original Streamdeck App, where you can choose, if you want the URL to be opened quietly in the background or in your default Browser...

**Is this platform dependent (windows, mac, ..)?**
Works everywhere...

**If documentation is required to implement, do you know where to find it?**

**Usecases**
By this Implementation we war very flexible by implementing ANY other program or device, which can be remotely controlled by http actions. So for example a simple relay-plug, a homematic device, and so on...

**Comment by dnmeid** [comment]
Has been implemented with 9c057fcf9480bb67d417a8f59323b5edfc2956e9
