### ISSUE TITLE
use without linux desktop

### ISSUE THREAD

**Issue by MatzeP** [bitfocus/companion#2340]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Hi,
is it possible to install companion on a linux without Desktop enviroment?

**Comment by MeestorX** [comment]
Yes. I've gone through this and probably need to do a "step by step" or video. It's not hard but it can be confusing.
Basically, download the Linux build and add some libraries.
`libusb-1.0-0-dev` and `libudev-dev`
Add some rules as per https://github.com/bitfocus/companion-pi/blob/main/update.sh#L95-L105
Then run it headlessly:
cd into the companion/resources folder
type `./node-runtime/bin/node main.js`

**Comment by MatzeP** [comment]
Hi thanks for your fast answer.
1. I have download "companion-x64-2.4.2+4911-v2-4.2-fcb5a863.tar.gz"
2. I have install "libusb-1.0-0-dev and libudev-dev"
3. I have copy from the Pi-Image 50-companion.rules and 090-companion_sudo and copy it in the right folder
4. I found the folder "companion/resources", **BUT** there are only "app.asar, docs.zip and webui.zip" and nothing *.js files

If you mean with "Linux" the the pi-version, then their are *.js files, but no resources folder or node-runtime folder

**Comment by MeestorX** [comment]
No, not the pi version, I was using the Arm64 version.
Not sure why you're not seeing it, but I might have done another step and forgot about it.
Here's my folder list..
![Companion Files on Arm](https://user-images.githubusercontent.com/29129658/220420850-c47a3973-e5d4-4e82-b880-f3fab590d8f0.png)

**Comment by Julusian** [comment]
That only works with the 3.0 betas, not 2.4.2.

Yoi can use 2.4.2 headless, but it requires building from source instead of downloading from the website

**Comment by MatzeP** [comment]
Great. It runs.
Thank you!!

**Comment by MeestorX** [comment]
Didn't notice that the OP was looking to do 2.4. Yup, 3.0 is the way.
