### ISSUE TITLE
[BUG] streamdeck does not let other application take focus with shell command appactivate

### ISSUE THREAD

**Issue by buffos** [bitfocus/companion#2342]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am trying to control powerpoint through powershell commands. A part of the script is as follows

```
# prepare shell script object
Add-Type -AssemblyName System.Windows.Forms # in order to use .NET forms
Start-Sleep -m 200

$wshell = New-Object -COMObject Wscript.Shell; # create a shell vb object
$wshell.AppActivate("PowerPoint") # activate powerpoint
Start-Sleep -m 200
[System.Windows.Forms.SendKeys]::SendWait("{F5}")
 return
```

When this is run inside companion (shell command run) the result is to send F5 to the companion webpage and reload the page

### Expected Behavior

The expected behavior is to activate powerpoint (which is running) and start the slideshow

When I run the command from the terminal, I get the expected behavior.

### Environment (please complete the following information)

```markdown
- OS: Windows
- Browser: Chrome
- Companion Version: 3.0.5675
```

**Comment by Julusian** [comment]
I'm not sure if there is anything we can do about this, or if it is even a bug.

The fact that the companion webpage refreshed shows that your script ran to completion, but the `$wshell.AppActivate("PowerPoint")` failed, so what I assume happened was the window already in focus got the F5 instead. It being the companion webpage that got the F5 is 'luck', and it could have just as easily been anything else.

Maybe the way the script is being run is causing that to fail in a way similar to [this thread](https://social.technet.microsoft.com/Forums/en-US/5f71b09e-5244-4f81-8c1d-b0aff24187bf/vbs-objshellappactivate-doesnt-work-with-windows-task-scheduler?forum=ITCG)? If so, is it even possible for us to do better?

**Comment by buffos** [comment]
On my side it runs fine everytime, when I run it inside a terminal.

I tried another way, with the same result (maybe the way the command is executed).

Here is the alternate script

```
Add-Type @"
    using System;
    using System.Runtime.InteropServices;
    public class WinAp {
      [DllImport("user32.dll")]
      [return: MarshalAs(UnmanagedType.Bool)]
      public static extern bool SetForegroundWindow(IntPtr hWnd);

      [DllImport("user32.dll")]
      [return: MarshalAs(UnmanagedType.Bool)]
      public static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);
    }
"@


$p = Get-Process | Where { $_.mainWindowTitle } |  Where { $_.Name -like "POWERPNT" }
if (($null -eq $p) -or ($p -eq "")) {
    Write-Output "PowerPoint is not running."
    return # exit script
}

$wshell = New-Object -COMObject Wscript.Shell; # create a shell vb object

$handle = $p.MainWindowHandle
[void] [WinAp]::SetForegroundWindow($handle)
[void] [WinAp]::ShowWindow($handle, 3)
wshell.SendKeys("{F5}")
```

Again the same result. I will keep trying since this is a quite important (I can try going the autohotkey way, but his adds another dependency to the stack)

**Comment by buffos** [comment]
I worked around the issue, using autohotkey.
Created scripts there and run those scripts instead of powershell scripts and it works fine.
