### ISSUE TITLE
[BUG] Variables used in feedback text are not changed when connection is renamed

### ISSUE THREAD

**Issue by dnmeid** [bitfocus/companion#2343]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When variables are used at button text and the label of the connection generating that variable is changed, then the variable gets updated automatically.
Boolean feedbacks can be used to change the button text and the text can also contain variables. These variables in feedback text are not changed when the connection is renamed.

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version: 3.0.0 (3.0.0+5682-beta-d4467c08)
```

**Comment by Julusian** [comment]
This should now be fixed in beta
