### ISSUE TITLE
[BUG] StreamDeck Mk2 not found in Beta branch

### ISSUE THREAD

**Issue by jspoe** [bitfocus/companion#2346]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have two instances, stable and beta. Just running 1 at the time.

At the stable 2.4.2 version, the Streamdeck is recognized and working fine.
At the beta 3.0.0+5686 version, the Streamdeck is not recognized and giving the following message in console:

`2023-02-25T13:52:09.512Z error Surface/Controller Found "elgato-streamdeck" device, but no access. Please quit any other applications using the device, and try again.
`

I'm not having other instances running, 2.4.2 is working fine directly after boot, 3.0.0 is not directly after boot.

### Steps To Reproduce

1. Connect StreamDeck Mk2 or StreamDeck (Original)
2. Run beta 3.0.0+5686 with ./companion-launcher from terminal

Default buttons not showing

---

3. Open the GUI and go to Surfaces
4. Press Scan for Rescan USB
5. Check the terminal

Message shown:

`2023-02-25T13:52:09.512Z error Surface/Controller Found "elgato-streamdeck" device, but no access. Please quit any other applications using the device, and try again.
`

### Expected Behavior

A connected StreamDeck, Default buttons showing

### Environment (please complete the following information)

```markdown
- OS:Ubnuntu Mate
- Browser:Chrome, Firefox. Doesn't matter
- Companion Version: 3.0.0+5686
```

**Comment by Julusian** [comment]
The needed udev rules changed between 2.4 and 3.0.

Please try updating those to this https://github.com/bitfocus/companion-pi/blob/main/50-companion.rules, which will work for both 2.4 and 3.0

**Comment by jspoe** [comment]
Ohh good one, thank you! Never thought that would be any issue.
Is that noted somewhere? I just downloaded the beta-version and installed it next to the stable version.
Might be a good idea to add that to the launcher or first-time setup wizard.

Thank you!
