### ISSUE TITLE
Go-to-Page Button

### ISSUE THREAD

**Issue by kultikom** [bitfocus/companion#235]
**Describe the feature**
Just a simple Action, which brings up a defined Page, to navigate quickly through the pages

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**

**Usecases**
If you are at page 36, you could quickly go back to page 1 with this function...
Or
On one of the first pages you could setup an index page which refers directly to other pages

**Comment by somerockenguy** [comment]
To add to this I would love to see the page number button (row 2 column 1) to bring up a page of customization page shortcuts. This would be accessible on any page to open up the same 3x4 grid of  shortcuts.

Usecase
 I'm on page 1 and I want to go to 14. Press the page number button then the defined shortcut key.

**Comment by willosof** [comment]
Duplicates what's being solved in #229

**Comment by willosof** [comment]
Fixed.
