### ISSUE TITLE
trigger on event - import configuration

### ISSUE THREAD

**Issue by noiseboi** [bitfocus/companion#2355]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Currently, actiones can be triggered on startup but not when a new configuration is loaded. Loading a new configuration appears almost like a restart of companion and I _assumed_ startup triggers would operate. 

Perhaps consider firing triggers set for startup when a configuration is loaded or add a 'on configuration load' event?

### Usecases

I have a scheme which ensures some faders are set at a nominal level on startup. I would also like this same behaviour when I load a configuration.

**Comment by Julusian** [comment]
When doing a full import, it definitely would make sense to run any 'on startup' triggers.
Im not sure if the same is true when doing a partial import, that could quickly end up rather complex and heavily dependant on what was imported. Perhaps any time triggers which are 'on startup' are imported, those which were imported should be executed?

**Comment by noiseboi** [comment]
Yes, I see. Personally, I think it would be reasonable to only expect 'onstartup' triggers to run on a full 'Reset and Import'

**Comment by Julusian** [comment]
this is implemented
