### ISSUE TITLE
[BUG] v3: Action Recorder: Value of "Connections" Instance in "Set Connections" action not importing correctly

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#2360]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When importing a page, the value of "Connections" in the "Set Connections" action is not updated.

### Steps To Reproduce

Create a button with the "Action Recorder: Set Connections" action
Export that page/config with the button
Import that page/config
The "Connections" field is blank

### Expected Behavior

The connections field should be updated the same way as with other buttons, where it picks the connection based on the mapping.

### Environment (please complete the following information)

```markdown
- OS: All
- Browser: Any
- Companion Version: v3.0.0+5702
```

**Comment by MeestorX** [comment]
Friendly bump in case this is an easy fix - it's hindering getting people to use the action recorder ATM.

**Comment by Julusian** [comment]
I have made a start on this, but life is getting in the way of finishing it.
Its part of a larger problem of not fixing up various labels/ids during import

**Comment by Julusian** [comment]
This should now be fixed in beta. Please give it a try and let me know if it still isnt working for you

**Comment by MeestorX** [comment]
TY. Won't be able to test for a while, but appreciate you fixing this!
