### ISSUE TITLE
[BUG] v3: Cloning trigger disables trigger that was cloned

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#2361]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This one had me scratching my head for a while!

If you create a trigger and then clone it, only the clone actually works. The original trigger stops working, but with no indication of why.

### Steps To Reproduce

1. Create a Trigger
2. Clone it
3. Do whatever is needed to activate the original trigger
4. Original trigger doesn't work, (But the clone does)

### Expected Behavior

Cloned triggers should work ;-)

### Environment (please complete the following information)

```markdown
- OS: MacOS
- Browser: Safari
- Companion Version: 3.0.0+5702-beta
```

**Comment by Julusian** [comment]
yeah, it wasn't changing the ids in the clone, resulting in the id clash causing the checks to fight each other
