### ISSUE TITLE
3.0.0+5706 Button step progression out of order. [BUG]

### ISSUE THREAD

**Issue by Fishbros13** [bitfocus/companion#2362]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have multiple buttons with 21 steps, each step changing a variable to a specific number not in numerical order. When I press the buttons to cycle through the steps, it progresses in a very sporadic, yet consistent order. The order I am getting is 1, 2, 11, 12, 13,  14, 15, 16, 17, 18, 19, 20, 3, 21, 4, 5, 6, 7, 8, 9, 10. I have had this happen on a few different buttons and it always does a weird order like this.

### Steps To Reproduce

Create a button with 11 or more steps and press it to cycle through the steps and watch the step number on the button. (Actions unneeded to demonstrate issue.)

### Expected Behavior

I would expect buttons to cycle through in numerical order.

### Environment (please complete the following information)

```markdown
- OS: Mac OS Ventura 13.0.1
- Browser: Google Chrome
- Companion Version: 3.0.0+5706 Beta
```

**Comment by dnmeid** [comment]
fixed in 58a6c611488a51dfac5b1f7e2200df63118ffc50
