### ISSUE TITLE
[BUG]? In triggers, Use variables for button and page needs an expression

### ISSUE THREAD

**Issue by noiseboi** [bitfocus/companion#2364]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In trigger actions actioning a button, checking 'Use variables for button' or 'Use variables for page' prompts for an expression. Inserting just a variable eg `$(internal:custom_Int_Ident_Button) `does not work but inserting an expression eg `$(internal:custom_Int_Ident_Button) *1` does. 

### Steps To Reproduce

Create a trigger with a button action 
check 'Use variables for button'
inset a variable into the button (expression) field

![image](https://user-images.githubusercontent.com/88212362/224488774-420d3fe6-4865-4ecd-9ee6-eddbb685e57f.png)

### Expected Behavior

A variable and an expression to work?

### Environment (please complete the following information)

```markdown
- OS:w10
- Browser:Chrome 110
- Companion Version: 3.0.0+5713
```

**Comment by Julusian** [comment]
fixed
