### ISSUE TITLE
[v3 BUG] Bring back button text variables

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion#2366]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

v2 of companion used to be able to recall button text variables “button text string” ie:

`$(internal:b_text_5_32)`

While there is the action to “use another button style”, it uses the whole button style. 

Instead, I need to pipe the _text only_ variable and reformat it on a central button, based on a current custom variable. 

Request to bring these text variables back to v3 of Companion! (& any other text variables not listed here)

<img width="557" alt="Screenshot 2023-03-11 at 3 58 54 PM" src="https://user-images.githubusercontent.com/76959770/224511798-22d21aca-9d2b-4dc1-8e5d-5429fc846a80.png">

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by MeestorX** [comment]
As a workaround, can you not just use a variable for your actual button text and then change it instead of the other way around?
e.g. Button 5-9's text is $(internal:custom_button_5_9) which is set to whatever you would normally have button 5-10's text set to.
If custom_cue = 2, set $(internal:custom_button_5_9)'s text to the new value.

**Comment by Julusian** [comment]
done

**Comment by davidjoshuaford** [comment]
Amazing, thanks Julian!

Out of interest, if there are other similar variables available internally, could they be added to the list on the documentation page? 

https://user.bitfocus.io/docs/companion

Those little variables are super useful for building interesting functions. 

Best, 
David
