### ISSUE TITLE
[BUG] Crash after disabling a Module/Connection

### ISSUE THREAD

**Issue by zahedhelmand** [bitfocus/companion#2374]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Companion / the Docker Container are crashing after trying to disable a connection/plugin.

I hope I am doing everything right, it is my first time opening an issue in github.

### Steps To Reproduce

1.  Compose companion beta in Docker on my Synology NAS with

> version: "3"
services:
  companion:
    image: ghcr.io/bitfocus/companion/companion:beta
    ports:
      - 8654:8000
    volumes:
      - /volume1/docker/companion-beta/config:/companion
      - /volume1/docker/companion-beta/module-local-dev:/app/module-local-dev

2. Install a connection/plugin
3. Try to disable a connection/plugin
4. Companion is crashing. See logs.

### Expected Behavior

Plugin should be normally deactivated without crashing.

### Environment (please complete the following information)

```markdown
- OS: Synology 923+ with Portainer
- Browser: Google Chrome
- Companion Version: 3.0.0+5746-beta-a2a120ae
```

### Additional context

Logs form Docker Container:
`2023-03-16T18:45:51.999Z info Instance/Controller Adding connection bmd-atem ATEM 
2023-03-16T18:45:52.000Z info Instance/ModuleHost Starting connection: "atem"(4yggLqMWuf_h91SUBteIF) 
2023-03-16T18:45:54.976Z info Instance/Controller Disable instance atem 
Error: spawn ps ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
sentry error {
    "values": [

{
            "type": "Error",
            "value": "spawn ps ENOENT",
            "stacktrace": {
                "frames": [
                    {
                        "filename": "node:internal/process/task_queues",
                        "module": "task_queues",
                        "function": "process.processTicksAndRejections",
                        "lineno": 82,
                        "colno": 21,
                        "in_app": false
                    },
                    {
                        "filename": "node:internal/child_process",
                        "module": "child_process",
                        "function": "onErrorNT",
                        "lineno": 476,
                        "colno": 16,
                        "in_app": false
                    },
                    {
                        "filename": "node:internal/child_process",
                        "module": "child_process",
                        "function": "ChildProcess._handle.onexit",
                        "lineno": 283,
                        "colno": 19,
                        "in_app": false
                    }
                ]
            },
            "mechanism": {
                "type": "onuncaughtexception",
                "handled": false
            }

}
    ]
}
`

**Comment by tyler351** [comment]
I'm also seeing this issue on a linux VM with the beta version running in docker. I've had it happen with multiple modules. Happy to post logs if it's helpful.

**Comment by Julusian** [comment]
I think I have figured this out, it is trying to invoke `ps` to do some process management, but that was missing from the docker image. The image is now installing this so should now work
