### ISSUE TITLE
[BUG] internal: Trigger lockout actions misbehaving (2.4.2)

### ISSUE THREAD

**Issue by robwelch22** [bitfocus/companion#2376]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

"internal: Trigger a device to lockout immediately." -> Locks out all Surfaces.  "internal: Trigger all devices to lockout immediately." does not lock any surfaces.  Testing with Companion 2.4.2 (2.4.2+4911-v2-4.2-fcb5a863).  Directly connected / USB Stream Deck, Emulator, and latest Raspberry Pi Satellite.

### Steps To Reproduce

1. Configure Companion to enable / check Link Lockouts.
2. Configure Companion with PIN code.
3. With or without Companion setting for Pin Timeout (seconds, 0 to turn off).
4. With or without Companion setting for Enable Pin Codes.
5. Create new Button Action with  "internal: Trigger all devices to lockout immediately." 
6. Test button press.  No action occurs.
7. Change Button Action to "internal: Trigger a device to lockout immediately." specifying local Surface.   This works to lock out all Surfaces. 

### Expected Behavior

 "internal: Trigger all devices to lockout immediately."  should lock out all Surfaces.  

### Environment (please complete the following information)

```markdown
- OS: Windows 10
- Browser: Chrome, Firefox, etc. 
- Companion Version: 2.4.2 (2.4.2+4911-v2-4.2-fcb5a863)
```

**Comment by Julusian** [comment]
This is fixed in 3.0
