### ISSUE TITLE
Surface Name Companion Internal Variable. 

### ISSUE THREAD

**Issue by robwelch22** [bitfocus/companion#2377]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Internal variables include IP address of Companion and other important values.  The Surface name is invaluable to be shown on Stream Decks to ensure that the proper button configuration is being used.  Suggested is to have an internal variable for for the Surface name to be displayed on a button.  This may be challenging with Satellite systems, but is extremely useful.

**Comment by Julusian** [comment]
related to https://github.com/bitfocus/companion/issues/2071

**Comment by dnmeid** [comment]
Can you describe your usecase?
It seems to me that you have a setup with multiple stream decks and want to make sure that all are loaded at a different, specific page. There are various ways to achieve this.
- In surface settings you can define a startup page for every stream deck, this will be remembered according to the serial number.
- you can have a trigger running at startup and setting your streamdecks to a page by s/n
- if you are working with multiple changing streamdecks, you can have the startup trigger set pages by id

**Comment by robwelch22** [comment]
Dorian,

I work with vendors deploying virtual environments and live productions.  The current solution, which was developed by a 3rd party, and reliant upon the 3rd party, uses OSC triggered Devices / Connections.  The start page is designated when the Raspberry Pi boots and initiates the OSC to Stream Deck application.

Since the Surface page already has an option for "last page", and for consistency, having an option for "start page" on that same form seems most reasonable and supportable.  The projects is moving from and "IP / OSC" based deployment using pre-configured Connections to Satellite.

Pre-loading the Satellite Surfaces would also be beneficial.  A status of connectivity could be shown.  That way one can pre configure a production, assign button actions and Stream Decks / Surfaces.  This method is consistent with Devices.  That is, pre-loading the target Devices.  As you know all to well, the Surfaces are "live" devices.

I'm fairly new to Companion, and being asked to help with with the development of a more elegant solution.  But there are currently gaps to close.  You and the team have done a wonderful job of programming a very stable platform.  The code is very cleanly written with notes and failure checks.

Thanks for all that you and the team are doing.

Best,
-Robert Welch
________________________________

**Comment by davidjoshuaford** [comment]
I have a similar request, which I hope is related - 

I want to update multiple surfaces to work in tandem as a matrix larger than the 8x4. I know I can currently do this using a custom variable such as` $(internal:custom_surface1)`, `$(internal:custom_surface2)` etc, and by entering each surface or emulator's ID number into that variable.

However, this takes a while to reconfigure if swapping out different surfaces (ie switching between a stream deck XL on one production and using an iPad emulator on a different production). Plus, trying to communicate this to a team member is more complicated as well.

A cleaner approach would be to rename the Surfaces under the Surface's tab, and for Surface names to be able to determine the page jump Action:

`internal: Surface: Set Name to page`

For example, here I have 4 emulators arranged in a 2x2 grid, with the names 1, 2, 3, 4. 

<img width="1865" alt="Screenshot 2023-04-11 at 5 05 19 PM" src="https://user-images.githubusercontent.com/76959770/231288331-ca22a925-b32b-4d59-976a-959fd45b2e89.png">


I'd like to be able to easily add in my two XL surfaces by deleting the names 1 and 2 from the emulator, and renaming the two XL surfaces to "1", and "2", and keep my two other emulators on the iPads as "3" and "4". 

<img width="822" alt="Screenshot 2023-04-11 at 4 51 40 PM" src="https://user-images.githubusercontent.com/76959770/231285621-0c9397c8-895e-4608-90a3-04b1ed728bdd.png">

<img width="822" alt="renaming" src="https://user-images.githubusercontent.com/76959770/231288954-b278cbdd-d4eb-48be-99a3-b4b70da452ed.png">

**Comment by Julusian** [comment]
This is implemented in the betas now
