### ISSUE TITLE
[BUG] Pin Timeout (seconds, 0 to turn off) - Restrict values to positive numbers.

### ISSUE THREAD

**Issue by robwelch22** [bitfocus/companion#2378]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Pin Timeout (seconds, 0 to turn off) - The value can be set to a negative number.  When this occurs, the surfaces, such as Stream Decks go into a "wild" state.  Restrict the value to only positive numbers. 

### Steps To Reproduce

Bitfocus Companion Settings - Set Pin Timeout (seconds, 0 to turn off) = < 0. 

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version: 2.4.2 (2.4.2+4911-v2-4.2-fcb5a863)
```

**Comment by Julusian** [comment]
This is fixed in 3.0
