### ISSUE TITLE
PIN Pad Unlock On / Off for New Connections

### ISSUE THREAD

**Issue by robwelch22** [bitfocus/companion#2379]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

When a new Surface is connected to Companion, such as the Stream Deck, with "Enable PIN Codes" checked / enabled, the Surface is required to enter the PIN.  Requested is a system wide option "Lock upon Connection" which is a toggle to initialize on the PIN page or the designated start page.

### Usecases

There is currently an issue with Satellites reconnecting which results in all Surfaces being locked out when "Link Lockouts" are enabled or any of the permutations for Lockout.  This option allows the toggle to start the Surface on the PIN page or start page.

**Comment by Julusian** [comment]
I don't think this is the correct solution to take for this, as it would mean a locked surface could be unlocked by unplugging and reconnecting it.
But something could be done to improve on how this behaves today

**Comment by robwelch22** [comment]
There should be a mechanism to determine if that particular Surface is locked.

**Comment by Julusian** [comment]
When I read this previously, it sounded like what was happening was that when connecting a new streamdeck it would cause all surfaces to get locked. But it is only the ones being connected that get locked.  
This is a little odd, as when lockouts are linked some devices will be locked and not others.

But it looks like this currently working as intended, but some work should be put into persisting the locked status when a device is disconnected and reconnected. As such I am changing this from a bug to an enhancement.
I think this is going to require an overhaul of how the lockouts are implemented, and how the state of each device is tracked to achieve, and this needs to start with sketching out the the different scenarios.

**Comment by robwelch22** [comment]
Team,

I apologize for the late response.

During testing, when the Satellite with a StreamDeck determined there was a network issue from the ping / ICMP polling, all of the Surfaces would lock.  Tuning the values in clients.js increased the ping timeout and number of missed pings resulted in the Satellite being more stable and not disconnecting.  The Companion configuration was to lock all Surfaces if one was locked.  The lock ocurred as a result of a Satellite disconnects and reconnects.

Further testing is required to determine what the status is of connected Satellites when a new Satellite is connected.

--- March 18, 2023 FaceBook Post ---
<Edited> Original issue: Ghost in the machine. All Stream Deck Surfaces go to the PIN login page arbitrarily. Root cause: Satellite ping timeout.

Using journalctrl to watch the Satellite status: "journalctl -n 50 -u satellite.service -f" revealed that two incidences were related. With PIN Lockout enabled with Link Lockouts, when a Surface is newly connected, all Stream Deck Surfaces will revert to the login page. (An issue IMHO). Upon ping timeout, the Satellite Surface will reconnect.

The solution is to increase the ping timeout values.
/usr/local/src/companion-satellite/dist/client.js
const PING_UNACKED_LIMIT = 15; (Default 10)
const PING_IDLE_TIMEOUT = 800; (Default 100)

Tuning these values and exercising the Satellite Stream Deck buttons with curl indicated these values were optimal. Note that running ping via the Linux CLI is not the same as the multi-threaded node js ping execution.

This solution may be beneficial for others, especially with VPNs.
----------------------------------------------------------------------------------------

Regards,
-Robert Welch

________________________________

**Comment by Julusian** [comment]
I have taken a look at this and made some changes that I think make this more consistent and will resolve your issues

1) When lockouts are linked, we now track the current target lock state, so connecting a new surface will start off correctly, rather than defaulting to locked.
2) The lockout timers are moved so that they are remembered when a surface is disconnected. This results in reconnecting a surface in the middle of the timer retaining the correct state. The same has been done for tracking the locked state, so that reconnecting will result in the same state.

Please give it a test and let me know if there is still anything wrong, or any new bugs have been introduced
