### ISSUE TITLE
Webserver: Analog Way Midra (QuickVu) Buttons don't show

### ISSUE THREAD

**Issue by somerockenguy** [bitfocus/companion#238]
Adding buttons for the Analog Way Midra QuickVu do not show in the webserver.

**To Reproduce**
-Create an Analog Way Midra QuickVu instance
-Add some buttons
-Open Webserver

**Expected behavior**
Buttons should show

**Desktop (please complete the following information):**
 - Windows 10
 - chrome
 - 1.1.1.669

**Comment by willosof** [comment]
This issue was moved to bitfocus/companion-module-analogway-midra#2
