### ISSUE TITLE
Companion will not load on 3.0 beta 5454 forward Windows [BUG]

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion#2382]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Was excited to try 3.0 now that one of my big modules was included.  I've used it along without issue.  From version 5454 at least and through 5757 Companion GUI will not load.  Opening Task Manager shows dozens of Nodejs runtime instances loaded and CPU and memory maxing at 90-100%.  Also unable to load previous configs with triggers via the appdata folder copying method like I have done in the past.  Get a message that says "Companion unable to start".

### Steps To Reproduce

Download and install 5454 or 5457.  Attempt to load the gui via ethernet or local host.  page never loads and Node instances run away in task manager with CPU and Mem.

### Environment (please complete the following information)

```markdown
- OS: WIN 11
- Browser: EDGE
- Companion Version: 3.0 5454-5457
```

**Comment by krocheck** [comment]
I'm not having this issue on Win 11 using 5459, but there were only module changes, so I don't except the very latest to resolve this.

I'm going to recommend we take your database out of the loop, so go to %APPDATA%\companion\develop and cut and paste the various `db` files out to your desktop.

Can I get a readout of the modules you use?

**Comment by obcocav** [comment]
@krocheck.  Also noticing that when I uninstall 3.0.0 via the Add/remove programs tool it works fine but the 2.4.2 install will then not uninstall.  I get an error saying "companion uninstall cannot be found".  If I attempt to uninstall 2.4.2 first, then it works fine but strangely enough the 3.0.0 item in the program list then "becomes" 2.4.2 and gives the same error.  

Here is my list of modules:
![Screenshot 2023-03-21 080650](https://user-images.githubusercontent.com/51127807/226615234-648b1502-f551-43da-98cf-5ca389ec50cf.png)
![Screenshot 2023-03-21 080616](https://user-images.githubusercontent.com/51127807/226615238-4e584cf9-ddba-42c2-b14b-c6d098031789.png)
![Screenshot 2023-03-21 080636](https://user-images.githubusercontent.com/51127807/226615240-51ba4c90-45fa-4549-aef5-b3e6433f13e1.png)

**Comment by obcocav** [comment]
@krocheck.  Just reinstalled 2.4.2 on a new user account.  Then cleanly uninstalled.  Then install 5459.  Installed and started fine.  Imported full config only (not the DB).  Companion encountered an error and needs to restart the wizard.  Restarted companion and it comes up empty and like a fresh install.  So it does appear something in the modules is incompatible.

**Comment by krocheck** [comment]
5754 introduced the v3 compatible `birddog-ptz` module.  Can you email me your `db` file? keith.rocheck@gmail.com

**Comment by obcocav** [comment]
@krocheck.  Email sent.  I think I've been able to narrow it down to maybe my long list of custom variables or Long list of triggers.  Was able to get my config imported via page by page import rather than full config.  All connections in and it works.  Is there a way to import only the custom variable or only the triggers one at a time to see where the crash starts?  Thanks

**Comment by krocheck** [comment]
Interesting.  I haven't been able to load up the file you sent, so stand by for news on that.  I thought the import/export tool is able to do selective import of these different components?

**Comment by obcocav** [comment]
The checkboxes are there for it but it looks like Triggers and Surfaces are greyed out for now.  Was thinking that the ability to export triggers was disabled temporarily a while back and never reintroduced (or really introduced to begin with)

**Comment by krocheck** [comment]
Oh, are working with a 2.4 export?  Yeah, triggers aren't in there if that's the case.

**Comment by obcocav** [comment]
Right.  I have a huge list of triggers and looking to make the move to 3.0 from 2.4.2.  Had always copied the companion folder from Roaming in the past to get it all

**Comment by Julusian** [comment]
@krocheck we did sneak the export of triggers into 2.4 (https://github.com/bitfocus/companion/blob/master/lib/loadsave.js#L927-L929), so 3.0 should be able to import them. I dont remember if I tested it, so it is possible that it doesnt work for some reason

**Comment by Julusian** [comment]
I'm not surprised by there being dozens of processes, from those screenshots it looks like you have 43 connections, and each of those might now show as their own process in task manager.

Perhaps its a problem of trying to launch that many processes at once is causing cpu to be maxed out, causing some of those launches to timeout, and for us to then retry the launch prolonging the high cpu period?

**Comment by krocheck** [comment]
@Julusian it's a runaway of exceptions during feedback status checks for bank_style because of undefined feedback.options.properties.

I just need to spend more time with it because I figured that out yesterday but then had to work on other things.

**Comment by obcocav** [comment]
FYI.  Tried it on my Mac earlier and it appears to not be an issue on Mac.  Definitely something up with windows though.

**Comment by obcocav** [comment]
Any update on this?  Tried the latest builds and still unusable.  I’m thinking it’s related to the vmix module now.  Finally got 3.0 open and disable all modules.  Still sluggish compared to v2.4.2 but functional.  Once I turn on the vmix module it slows to a crawl
And becomes unusable in the GUI.  I’ve disabled all input variables except name.

**Comment by Julusian** [comment]
I am seeing a couple of issues here.

1) As @krocheck suspected, the `bank_style` feedback is erroring from a newly added property that there isnt an upgrade in place to populate. 
2) When starting companion, it has high cpu for quite a while, as it attempts to launch every connection at once resulting in a lot of them crashing (due to a timeout) and being retried. 
3) Higher than expected cpu afterwards, which looks to be excessive amounts of redrawing buttons.


1 is a simple fix to handle
2 is a straightforward fix of limiting how many connections can be in the starting phase at a time. 
3 could need a bit more work, but it looks like adding some debounces has helped

@obcocav could you give 5790 a try? hopefully it runs better for you

**Comment by obcocav** [comment]
Need to do a little more testing with time but initially it looks like this solved the problem.  Companion now loads without hangs on 5790 onward!  Thank you @krocheck @Julusian !!

**Comment by Julusian** [comment]
@obcocav hopefully your silence means it is still working?
If not this can be reopened

**Comment by obcocav** [comment]
@Julusian.  The last few betas have regressed.  It does load and is "usable" BUT takes a long time to load and does not run near as well as the few builds after your fix.  Thanks for all your work!

**Comment by obcocav** [comment]
This same kind of issue is  BACK on build 5959.  Going to start backtracking to see if I can find where it was introduced. @Julusian
