### ISSUE TITLE
Highlight Trigger Being Edited

### ISSUE THREAD

**Issue by ZoomTestKitchen** [bitfocus/companion#2385]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

While editing triggers, onMouseOver highlights the saved trigger names on the left panel. After clicking/selecting a trigger to edit, there are no visual indicators of which trigger is currently being edited.

It would be desirable to provide a visual highlight of the trigger that is currently being edited.

**Comment by Julusian** [comment]
This will be in the beta builds shortly
