### ISSUE TITLE
[BUG] Replacing jsonpath with jsonpath-plus in v3 changes set custom variable behavior

### ISSUE THREAD

**Issue by maxbaeumle** [bitfocus/companion#2388]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`jsonpath-plus` [used](https://github.com/bitfocus/companion/blob/c6884044d9113c7532f1ddec7dd8b6270d29595e/lib/Internal/CustomVariables.js#L18) in v3 behaves differently than `jsonpath` [used](https://github.com/bitfocus/companion-module-bitfocus-companion/blob/0e08cd04020a7f0c8b39d95abbf652356cd9eab7/index.js#L6) in v2. Examples for this can be found [here](https://cburgmer.github.io/json-path-comparison/). This may produce different results for the set custom variable from jsonpath action and break migrated v2 configs.

### Steps To Reproduce

1. Create two custom variables, `json` and `result`. Set the value of `json` to `{"status":"pressed"}`.
2. Create a button and set its text to `$(internal:custom_result)`.
3. Create an action `Custom Variable: Set from a stored JSONresult via a JSONpath expression`. Set the JSON variable to `json`, the path to `$.status` and the target variable to `result`.
4. Press the button.
5. The value of `result` (and the text of the button) will be `pressed` on Companion v2 using `jsonpath` and `["pressed"]` on Companion v3 using `jsonpath-plus`.

### Expected Behavior

Revert back to `jsonpath` to maintain compatibility with migrated v2 configs.

### Environment (please complete the following information)

```markdown
- OS: macOS Ventura 13.2.1
- Browser: Safari 16.3
- Companion Version: 3.0.0+5755-beta-a2a8db8a
```

**Comment by maxbaeumle** [comment]
Getting the previous behavior while still using `jsonpath-plus` might be as easy as setting the `wrap` option to `false`, i.e. changing [this line](https://github.com/bitfocus/companion/blob/c6884044d9113c7532f1ddec7dd8b6270d29595e/lib/Internal/CustomVariables.js#L262):

```
				valueToSet = JSONPath(action.options.jsonPath, objJson)
```

To this:

```
				valueToSet = JSONPath({wrap: false}, action.options.jsonPath, objJson)
```

**Comment by krocheck** [comment]
@Julusian do you remember the reason for the switch from `fast-json-patch` to `jsonpath-plus`?

**Comment by Julusian** [comment]
I expect it was either that `jsonpath` looks a bit dead and `jsonpath-plus` looks better maintained, or https://github.com/dchester/jsonpath/issues/166 suggests it wouldnt be loadable in webpack
