### ISSUE TITLE
[BUG] [v3] Importing a v2 config with spaces in instance names is not handled correctly

### ISSUE THREAD

**Issue by sphlabs** [bitfocus/companion#2389]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

v2 allowed spaces in instance labels. v3 does not.

When importing a v2 config file into v3, where there are spaces in instance labels, the spaces are replaces with underscore characters in the instance config. But any use of variables for that instance, e.g. in button text, is not updated; thus breaking all such variables.

This may also relate to variables in other places (e.g. feedbacks) -- I have not personally tested that.

### Steps To Reproduce

1. Create an instance in v2 with spaces in the label.
2. Create some button text using variables from that instance
3. Export the config
4. Import the config into v3
5. Observe that the instance name now contains underscores, but the variables in button text still have spaces, and do not resolve.

### Expected Behavior

Either, spaces should be preserved in imported instance labels and continue to be allowed -- **preferred behaviour**;
Or, all uses of variables relating to that instance should be updated to also replace spaces with underscores.

### Environment (please complete the following information)

```markdown
- OS: macOS
- Browser: Safari
- Companion Version: 3.0.0 (3.0.0+5760-beta-c6884044)
```

### Additional context

There is a related bug, #2343, where manual changes to an instance label results in feedback variables not being updated.

**Comment by Julusian** [comment]
I think this is a more general issue where any instance re-mapping done during import are not applied to usages of variables.
and is also related to https://github.com/bitfocus/companion/issues/2360

**Comment by Julusian** [comment]
This should now be fixed in beta. Please give it a try and let me know if it still isnt working for you
