### ISSUE TITLE
Request: Custom Variables sidebar list: expand/contract, filter, sort

### ISSUE THREAD

**Issue by tcconway** [bitfocus/companion#2394]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I use a lot of custom variables. I'd like to better work with the custom variables in the sidebar list.

Request: 
- Have each custom variable in the list expand/contract
     -- When un-collapsed, it shows the variable details like we see today...with the addition of a collapse button.
     -- In collapsed view, we see just a single line showing the variable name and an expand button.
- Filter the Custom Variables list (just like what's been implemented in 3.x for preset variables lists).
- Sort the Custom Variables list (just like how you sort actions by dragging an up/down arrow up or down)

Thanks for reading.

### Usecases

For people like me who rely heavily on custom variables, this would save hours of time and relieve headaches dealing with so many custom variables.

**Comment by Julusian** [comment]
> Have each custom variable in the list expand/contract
-- When un-collapsed, it shows the variable details like we see today...with the addition of a collapse button.
-- In collapsed view, we see just a single line showing the variable name and an expand button.

Done

> Sort the Custom Variables list (just like how you sort actions by dragging an up/down arrow up or down)

Done

**Comment by Julusian** [comment]
> Filter the Custom Variables list (just like what's been implemented in 3.x for preset variables lists).

Done
