### ISSUE TITLE
[BUG] Trigger incorrectly firing

### ISSUE THREAD

**Issue by DanielBaulig** [bitfocus/companion#2397]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm at this point not 100% sure if this is a bug in companion or a module, but I find it more likely to be an issue in Companion.

I have a trigger setup that will run an action when a given condition turns true. I've noticed that this trigger will occasionally fire when I do not expect that condition to turn true.

Specifically, I've set it up to toggle a switch on in Home Assistant when the "atem: Recording: Active/Running" condition becomes "Recording" and a separate trigger to turn off the switch when the "atem: Recording: Active/Running" condition becomes "Idle". I've noticed the first condition to occasionally fire, even when I know my ATEM Mini is not being used. It doesn't appear to trigger the separate "Idle" trigger leaving the Home Assistant toggle switch in an on state.

The reason I believe this might be a Companion issue, rather than a ATEM or Home Assistant module issue is that I can tell from the Companion UI that the "Recording" trigger actually triggered (given the timestamp) and that the "Idle" trigger didn't trigger since, but my ATEM Mini is not actually in recording state *and* the feedback button on my Steam Deck (driven by Companion) is not showing the Recording state either. So either the ATEM module changed the state of the "atem: Recording: Active/Running" to Recording (triggering the Recording trigger condition) and then back to Idle without triggering the Idle trigger condition), or the Recording trigger somehow triggered without the "atem: Recording: Active/Running" actually changing to "Recording". The former simply seems to require more broken parts than the latter, which in conjunction with Occam's Razor just makes the latter seem more likely.

I decided to pull up the ATEM module logs, but they are empty. Not sure if the logs would have to be opened while the issue occurs to show anything meaningful, but I've also tried pushing some buttons and some actions on the ATEM while the log window was open and it didn't actually print anything. So not sure if this is going to reveal any more helpful information.

### Steps To Reproduce

Unclear. Seems to happen randomly.

### Expected Behavior

The condition trigger should not fire.

### Environment (please complete the following information)

```markdown
- OS: Windows 10
- Browser: 111
- Companion Version: 3.0.0 (3.0.0+5757-beta-06e88e48)
```

### Additional context

N/A

**Comment by dnmeid** [comment]
One possible reason for this problem I can think of is the "become" in "On condition becoming true". Companion checks if the condition *is* true and if it *was* true at the last check. If the stored value of the last check is not correct, the trigger may fire.
When you see an unexpected trigger, are you doing anything in Companion or is it just sitting there unattended?

**Comment by DanielBaulig** [comment]
Companion (and the entire Computer including the ATEM Mini) was sitting there unattended. I did just notice though, that it appears like that the computer resumed from a sleep or suspend state at the exact same time. I will try to reproduce it by manually putting the computer to sleep and waking it again.

**Comment by DanielBaulig** [comment]
So, I tried manually putting my computer to sleep and waking it again and that didn't trigger the condition. But I also have my ATEM Mini on a smart power switch that I use to turn off the ATEM Mini when my computer turns off. So I thought maybe turning off the ATEM Mini or disconnecting it could cause the issue. And indeed: if I disable the ATEM module in Companion, the trigger will fire. I *assume* that the same thing will happen if it were to loose connection (which could explain why it fired when my computer resumed from sleep), but haven't verified this specific behavior. 

The behavior of triggering based on the condition of "atem: Recording: Active/Running" being "Recording" when the ATEM module get's disabled is certainly wrong. I'm still not 100% certain if this issue is in the ATEM module (e.g. briefly reporting a "Recording" state when being turned off) or Companion. If I had to guess, I would still guess Companion and would check if there might be a bug related to there not being any valid conditions to check (since the only valid condition belonging to a module that is now disabled). 

I actually think I saw something somewhere about invalid conditions evaluating to true (instead of being removed from the evaluation) which could lead to such a bug, but was under the impression that what I read was that this bug had been fixed. I think I just recently did before filing this bug, but should I try updating my beta release?

**Comment by Julusian** [comment]
@DanielBaulig have you been able to narrow this down to be a reproducible bug that can be looked at?

**Comment by DanielBaulig** [comment]
@Julusian: I believe the steps in my most recent comment describe a reliable reproduction. By disabling and reenabling the ATEM module will fire the trigger (even though the ATEM itself never started or stopped recording).

Without having this re-verified right now, I believe setting up a trigger condition on "atem: Recording: Active/Running" turning on and then simply disabling and re-enabling the ATEM module. This seems to fire the condition incorrectly.

**Comment by Julusian** [comment]
When do we detect the computer going to sleep, we do stop all the connections, then restart them at wakeup which I expect would have the same effect as disabling a module here.

OK, I've finally taken a look into this, and what is happening is that when the connection is disabled, the trigger gets rechecked as the value for the condition has changed. At this point , the atem feedback has a value of undefined, which is gets ignored while we are computing the combine value of all the conditions. Meaning it fell back to the default of returning true.

I think the fix is to make it so that when we are missing or have an invalid value for a feedback in a condition, we treat that as false. I am a little concerned that it could cause some values to jump briefly to false, but I cant think when that could happen in practise. 
This has been done in beta

**Comment by TPaulManohar** [comment]
Hi,

I got the same error, When **Events - On any Button Press**, and there is not condition. We noticed that this trigger will occasionally fire even if trigger disabled .

```
Environment.
 - OS: Windows 10
 - Companion Version: 3.0.1 (3.0.1+6068-stable-a05a9c89)
```
