### ISSUE TITLE
Companion is Locked

### ISSUE THREAD

**Issue by m8720y** [bitfocus/companion#2398]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

My computer is MacBook Pro with Apple M1 Pro CPU.
After I install Companion app, it shows 'Companion is locked.'
I have reinstalled and doesn't work.

### Environment (please complete the following information)

```markdown
- OS: Mac M1 Pro macOS Monterey 12.3
- Browser: Chrome 111.0.5563.110
- Companion Version: 2.4.2
```

**Comment by Lifesjourneyproductions** [comment]
I have a client with this same issue running the newest stable version and when he launches the GUI he get's thye Companion is locked screen.

**Comment by video-en-direct** [comment]
embarassing, same problem here on a mc book pro intel

**Comment by ratte** [comment]
and?
