### ISSUE TITLE
[BUG] Values of "Variables within Variables" aren't fully recognized in the "Feedback" comparisons. 

### ISSUE THREAD

**Issue by chjaway** [bitfocus/companion#2400]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Custom Variables can be based on values & include references of other Custom variables.  Companion recognizes this and will render an expected value for button labels.
However, when in "Feedback", the value isn't understood by the comparison functions.

"Why would someone do this?"
If I have multiple connections (in my case "Roku Tvs"), I can create one set of buttons that returns connection information depending on the context of the variable "$(internal:custom_rokuConnection)" I've setup through other button clicks.  
Ex: I can have one Page that lists out drill-down buttons labeled with every Roku Device, and when I click one of those devices, it sets the $(internal:custom_rokuConnection) value to the right connection and the drill-down page shows a complete listing of all values for the connection (same drill-down page for all.. but.. contextually aware of the desired connection because of the variable within a variable.  And it WORKS for labels at least.. just not for any Feedback comparison functions).

### Steps To Reproduce

1. I added a "roku" connection labeled "roku-tv".
2. I created a Custom Variable "$(internal:custom_rokuConnection)" with the current value "roku-tv"
3. I created a Custom Variable "$(internal:custom_ActiveRokuPower)" with the current value "$($(internal:custom_rokuConnection):power-mode)"

### Expected Behavior

DOES WORK: 
The Custom Variable "$(internal:custom_ActiveRokuPower)" will **correctly** render the value "PowerOn" as a button label when the label is set as "$(internal:custom_ActiveRokuPower)"

DOESN'T WORK:
The Feedback "internal: Check variable value" Should recognize the variables *$(internal:custom_ActiveRokuPower)" value "PowerOn" for accurate comparisons (but doesn't)

### Environment (please complete the following information)

```markdown
- OS: MAC OS Ventura 13.2.1 
- Browser: Chrome Version 111.0.5563.110
- Companion Version: 2.4.2 (2.4.2+4911-v2-4.2-fcb5a863)
```

**Comment by Julusian** [comment]
I have a feeling this works better in 3.0, or if not it will be pretty straightforward to implement there

**Comment by Julusian** [comment]
Having now looked at the code, I am confident that this will work in 3.0
