### ISSUE TITLE
Ability to modify a button's action parameters based on status of a custom variable feedback

### ISSUE THREAD

**Issue by alomanto** [bitfocus/companion#2402]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Similarly to how we are able to modify a button's colors, text and other visual parameters based on the status of a custom variable (via the "Check Variable Value" internal feedback), it would be great to be able to modify a button's native parameters (such as being able to toggle the Latch/Toggle button, Relative Delays, etc. 

Additionally, being able to modify the parameters of _any_ button's_ actions based on the status of a custom variable. For example, being able to change the "Delay" parameter on any action that has this field. For example: If CustomVariable = True, change the delay parameter on the "Program: Set OBS Scene" action on the same button to a delay of 500. If CustomVariable = False, change the delay parameter on the "Program: Set OBS Scene" action on the same button to a delay of 0. 

I've included my specific use-case below.

### Usecases

I am attempting to do the following:

- I have two Stream Decks - One XL and one "Normal" size. 
- I have "Folder" buttons on the XL, which only exist to change the page of my normal sized stream deck. They're set by default to allow me to simply hold the button down, and press the button that I need on the other stream deck, then release to set it back to the "Main" page on the normal SD. 

![image](https://user-images.githubusercontent.com/20320269/228988466-343e57a9-6521-489a-945b-04ef81c96d62.png)

- I would love to be able to have another Toggle/Latch on my Stream Deck that sets a custom variable between two states: Latch and Hold. For the sake of an example, the custom variable i'm using is "EnableFolderLatch". Here's an example of that button:

![image](https://user-images.githubusercontent.com/20320269/228989449-1bdc3ff9-ac02-4703-925e-bce3877cd75a.png)

The point of this request would be a feedback action on the original "Folder" button that, when the "EnableFolderLatch" custom variable is set to "Latch", the "Latch" option on this button is enabled and it allows me to swap back and forth between pages on the normal stream deck with a single press of the folder button.

Alternatively, if the "EnableFolderLatch" custom variable is set to "Hold", the folder button will require you to hold it down to press a button on the normal stream deck, and will revert back to the original page when released. 

If there's a way to do this that I haven't found, please let me know.

Thank you!

**Comment by dnmeid** [comment]
This can be done in v3 with steps.
You can have one step with your toggeling behaviour and one step with your hold behaviour. Make the buttons not automatic progress to the next step and select the step/behaviour you want manually from another button.

I'm Closing this request as resolved.
