### ISSUE TITLE
Make color values compatible with alpha/transparency

### ISSUE THREAD

**Issue by dnmeid** [bitfocus/companion#2406]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

At hte moment we store colors in the database as number, generated from the red, green and blue value.
This number is not compatible with rgba or any other color information then rgb.
Making it compatible would either require an internal format of trgb (t = transparency) or moving away from the numeric storage.
As there may be also the need for deeper colors (>8 bit / channel), a non numeric storage should give greater flexibility.
The proposal is to use css color strings as a method for defining colors and also store them.

**Comment by dnmeid** [comment]
Update: internal color handling is now with CSS strings.
Todo:
* expose alpha possibility to the colorpicker
* make a property in base to the colorpicker option
* adjust types

**Comment by dnmeid** [comment]
Update: colorpicker now can handle alpha values

**Comment by Julusian** [comment]
This is possible in 3.2 (current beta builds)

**Comment by backporchengr** [comment]
Confused...  Don't see anything about transparency in 3.4 beta color picker (didn't in 3.3 stable either).  PNG display doesn't seem to respect transparency.

Companion 3.4.0+7218   MacOS 12.7.6 Safari 17.6

**Comment by dnmeid** [comment]
You will see a transparency slider in the color picker if the module developer did activate it. Not all all devices can handle transparency and we don't show the slider by default. If you are working with a connection where the color you are dealing with would support transparency and there is no alpha enabled color picker, please tell the maintainer of the connection to update it.
