### ISSUE TITLE
[BUG]GUI problems with actions on button tab

### ISSUE THREAD

**Issue by sstaub** [bitfocus/companion#2407]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When opening the action dialog the window slider of the buttons tab is overpainting the dialog.
Screenshot:
<img width="1742" alt="Bildschirmfoto 2023-04-01 um 15 46 16" src="https://user-images.githubusercontent.com/6450325/229293052-b15ba593-169a-4b83-98ac-ac18d5b7695b.png">

### Environment (please complete the following information)

```markdown
- OS: macOS Ventura 13.3
- Browser: Safari 16.4
- Companion Version: 3.0.0+5769
```

**Comment by Julusian** [comment]
This doesn't happen in Chrome, so is going to need someone that uses mac to investigate and provide a fix

**Comment by Julusian** [comment]
I am pretty confident this is a bug in safari. 
This looks to be happening to every scrollbar that goes behind another component.
For example, it also happens with scrollbars going behind the header:
![image](https://github.com/bitfocus/companion/assets/1327476/3f291b7b-0976-4de1-9fb6-ce2e4070d516)

Looking at the component with the rogue scrollbar, it has
![image](https://github.com/bitfocus/companion/assets/1327476/251529b8-4878-42f2-be8e-5fbf912a2097)
If I explicitly force the z-index to what should be the same thing
![image](https://github.com/bitfocus/companion/assets/1327476/a75553ef-459f-4ad3-9e1c-3ee359c69c42)
then it draws correctly.
Or alternatively, forcing the header to a z-index of 10000 fixes it. 10000 is an oddly large number to have any impact

The same hack doesn't work for the other scrolbars. While it will no longer be over the modal, it still shows above the dim backdrop, which while functional still looks odd
![image](https://github.com/bitfocus/companion/assets/1327476/73da46aa-1e0b-49de-9df7-042e2a249391)

Maybe it is a problem of some missing z-indexes, or maybe it is a bug in safari

**Comment by sstaub** [comment]
I have seen that problem only with your web interface, so I don't think this a bug. Maybe only with 3.x.
I will test the next days.

**Comment by Julusian** [comment]
The bit that pushes me into this being a safari bug is that the scrollbar is rendering differently to the component it belongs to. If they were together then yeah it is more likely to be our fault. But this is just affecting the scrollbar, which we have no ability to control the styling of.
Also worth noting that the scrollbar doesnt get hover or click interaction where it is incorrectly drawn on top. So the mouse interaction logic disagrees with the drawing.

Digging deeper, it looks to be caused by an element created by https://github.com/JedWatson/react-select. That component has a z-index of 9999 (which explains the 10000 for the header).
Knowing that I do have a potential fix, adding a z-index to the parent element 'fixes' it, but I don't know if that will have any side effects

Heres a minimal reproduction of the issue:
```
<html>

<head>
    <style>
        #a {
            background-color: #ff0000;
            height: 100vh;
        }

        #b {
            background-color: #00ff00;
            height: 50vh;
            width: 100vw;
            z-index: 100;
            position: absolute;
            top: 0;
            left: 0;
        }

        #c {
            background-color: #0000ff;
            height: 100vh;
            width: 50vw;
            overflow-y: scroll;
            z-index: auto;
        }

        #d {
            position: relative;
            z-index: 9999;
            height: 200vh;
        }
    </style>
</head>

<body>
    <div id="a">
        <div id="b">
            B
        </div>
        <div id="c">
            C
            <div id="d">
                D

            </div>
        </div>
    </div>

</body>

</html>
```

**Comment by sstaub** [comment]
This a bug with v3.x, 2.4.2 works as expected.

**Comment by Julusian** [comment]
The react-select component which is causing this was added in 3.0, to make the jumping to pages more interactive. 
Good thing I took a screenshot, the fix made this mess in every browser:
![image](https://github.com/bitfocus/companion/assets/1327476/43025dd0-6e4e-4b42-aa7d-50e2b88fb95d)
Hopefully chooser a higher number will work better and wont break other things
