### ISSUE TITLE
Client and Server

### ISSUE THREAD

**Issue by hadphild** [bitfocus/companion#241]
If you could have a server and a client. 

IE at Control you could have the main server Companion. But onstage you could have another computer with a stream deck connected Client page that can be edited from the server. They could switch Auxs or cameras from long audiance shots in Q and A. 

This Client version could be restricted to only press selected buttons or only see there page.

**Comment by josephdadams** [comment]
This is easily accomplished in current releases by simply running Companion on two computers, with slightly different configurations. Like @dnmeid said, you can use OSC or you can even use the generic HTTP instance on the "client" to send requests to the "master/server" to execute actual tasks there. Any further "satellite" type functionality will more than likely be a separate Bitfocus project. Closing this issue.
