### ISSUE TITLE
[BUG] goto page broken (2.4)

### ISSUE THREAD

**Issue by SKStrettonParish** [bitfocus/companion#2413]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a Streamdeck XL and a Mk2 connected to a Windows PC using Companion which were working fine. One drives an ATEM Mini Extreme and the other drives Easyworship. Both have "goto page" buttons as well as the "do stuff" buttons.
I have made a few changes as follows and now the "goto page" buttons don't do anything but the "do stuff" buttons work fine. If I shutdown Companion and restart it everything goes back to working fine.

1) connected the Streamdecks to a powered hub.
2) configured the PC to boot up Windows from power on.
3) Updates Windows 10 to Windows 11. Well Windows did that all by itself. I didn't want it to.

I considered maybe the powered hub might be causing problems so removed that but no change. Buttons do not work. Restarting Companion fixes the problem.
I backup out the change to boot up on power on but no change. Buttons do not work. Restarting Companion fixes the problem.

It looks to me like a timing or compatibility (with Windows 11) issue. 

I have temporarily fixed the problem by right clicking on the companion file, and selecting "troubleshoot compatibility".

Companion now works as before. I have also re-instated the boot up on power on, and the powered hub and all continues to work.

Version numbers of Companion, Windows, and the streamdeck surfaces in attached photos.

![Companion Version](https://user-images.githubusercontent.com/99482616/230405626-cb2426f4-24dd-4c58-8375-021384577fdb.jpg)
![StreamDeck info](https://user-images.githubusercontent.com/99482616/230405642-96608c49-f7d8-46cc-865b-4dc8386718c1.jpg)
![System info](https://user-images.githubusercontent.com/99482616/230405668-630a588e-cc40-430d-bbeb-1943569f6858.jpg)

### Steps To Reproduce

Using Windows 11
Run companion at Windows startup.
Try "goto page" buttons.
Goto buttons do nothing.

### Expected Behavior

Using Windows 11
Run companion at Windows startup.
Try "goto page" buttons.
Goto buttons change the page layout to the correct page,

### Environment (please complete the following information)

```markdown
See attached photos.
```

### Additional context

System is used in a church environment, using StreamDeck XL to control projector, 1 projector screen, and 2 cameras, and StreamDeck Mk2 to control EasyWorship 7.

**Comment by Julusian** [comment]
do feedbacks update on the page you are stuck on properly?
I am wondering if its a problem with the drawing, but not the functionality of the buttons?

**Comment by SKStrettonParish** [comment]
All of the modules work e.g. the screens go on and down on button press,
the projector turns on and off. The buttons to go to a specific page do
nothing.
Thanks
Steve

**Comment by davidjoshuaford** [comment]
Hi Julian, I'm running v3 beta 5783 and notice that the "back" page option for: 

`internal: Surface: Set serialnumber to page`

...doesnt work for my Stream Deck XL surfaces. 

However the "back" action _does_ function correctly for the emulators.

<img width="722" alt="Screenshot 2023-04-12 at 4 13 11 PM" src="https://user-images.githubusercontent.com/76959770/231574039-3fe0429a-f0ee-408a-8af4-e271e5a5f621.png">

**Comment by Julusian** [comment]
strange, these are all working fine for me in 5791..

**Comment by Julusian** [comment]
strange, these are all working fine for me in beta 5791

**Comment by davidjoshuaford** [comment]
Hmm it's working again for me now...not sure why. 

I tried updating one surface's Elgato firmware from 1.00.012 to 1.01.000 and it worked, but my second surface also worked on 1.00.012, so maybe it was just the rebooting of apps that flushed something out.

**Comment by travler775** [comment]
Hello - I actually have encountered this exact same issue, on two different installations of Companion and StreamDeck.
Companion 2.4.1 and 2.4.2 both behave the same way - the PAGE buttons fail to respond on the physical StreamDeck, but do virtually.

I upgraded to 3.0.0, but that actually broke control of my Black Magic Enterprise 288/288 VideoHub so I had to downgrade.

Has anyone made any progress is a workaround?  My Users have multiple pages in each installation on the physical StreamDeck, so having that Page control is pretty important.

Thanks for any insights.

**Comment by Julusian** [comment]
@davidjoshuaford  the bug in 3.0 with back is now fixed

The original issue here in 2.4 isn't going to be looked into any further as there will not be another release of 2.4. So I am closing this.

@travler775 The issue with videohub is fixed in the betas, and the betas are more stable than 3.0.0-rc1 at this point
