### ISSUE TITLE
Implement protocol for automatic detection of devices on network

### ISSUE THREAD

**Issue by DaveShep** [bitfocus/companion#242]
**Describe the feature**
Companion will either broadcast a are_you_there packet or just spend some time listening for a module to broadcast i_am_here packet (SSDP style etc.). Discovered devices can now be shown in a list for easy selection. Also consider supporting a unique identifier for the device, which could abstract away the need for the user to know the IP address, allowing automatic network configuration or a device IP change being automatically handled.

**Comment by dnmeid** [comment]
Possibly a duplicate of #240

**Comment by josephdadams** [comment]
Closing as this does seem to be a duplicate of #240, and MDNS support has been discussed and could be implemented down the road to speed up instance creation.
