### ISSUE TITLE
Ember+ additional fielsd

### ISSUE THREAD

**Issue by Jeffulka** [bitfocus/companion#2435]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Hello all,
I was adding feature request for TCP/UDP Listener recently, But I have realised, that there is better way to proceed in my integration.

Would it be difficult to add button BG color and mazbe text color to the Ember+ Listener ? As I can use Ember+, which is way better for integration, there is "State" parameter of button but there is only "Label" parameter. I would like to have also control of background color and text color. 

Right now there is:

				<Page_1 TYPE="GROUP" ID="1" NAME="Page 1">
					<Bank_1 TYPE="TABLE" ID="1" NAME="Bank 1.1" HINT="Bank_1_$$ROW" ROWS="32">
						<State DISPLAY="BOOL" TYPE="VALUE" ID="0"/>
						<Label DISPLAY="STRING" TYPE="VALUE" ID="1"/>
					</Bank_1>
				</Page_1>

And if we would have:

				<Page_1 TYPE="GROUP" ID="1" NAME="Page 1">
					<Bank_1 TYPE="TABLE" ID="1" NAME="Bank 1.1" HINT="Bank_1_$$ROW" ROWS="32">
						<State DISPLAY="BOOL" TYPE="VALUE" ID="0"/>
						<Label DISPLAY="STRING" TYPE="VALUE" ID="1"/>
						<BG_Color DISPLAY="STRING" TYPE="VALUE" ID="2"/>
						<Text_Color DISPLAY="STRING" TYPE="VALUE" ID="3"/>
					</Bank_1>
				</Page_1>

It would be great.
Thank you

**Comment by krocheck** [comment]
@baltedewit any chance you want to pick this up for the core?

**Comment by Julusian** [comment]
This is in beta:
![image](https://github.com/bitfocus/companion/assets/1327476/6ca8b467-01a3-449c-b9d1-7ec9b069a789)
