### ISSUE TITLE
Companion is locked[BUG]

### ISSUE THREAD

**Issue by EVENTANDMEETING** [bitfocus/companion#2439]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi all, when I open Companion, a box appears that says: Companion is locked.
I try to enter the PC PIN, the Companion password but nothing.
I also tried from another PC and I don't have this problem, what does it depend on?

### Steps To Reproduce

![bitfocus](https://user-images.githubusercontent.com/132766915/236632061-38706afb-0e76-4563-9bfa-e4d6e30271b8.jpg)

### Expected Behavior

no

### Environment (please complete the following information)

```markdown
- OS: windows 11
- Browser: chrome / Firefox / Edge
- Companion Version: 2.4.2
```

### Additional context

no

**Comment by bryce-seifert** [comment]
You can click the Companion icon in the menu bar/ taskbar and go to “show config folder” and open the file that is called “db”. Then search for “admin_password” and it should be there.

**Comment by Julusian** [comment]
https://github.com/bitfocus/companion/issues/2393#issuecomment-1483900433

**Comment by bryce-seifert** [comment]
@ofosuappiah you can click the Companion icon in the menu bar at the top of the screen and go to “show config folder” and open the file that is called “db”. Then search for “admin_password” and it should be there.

**Comment by bryce-seifert** [comment]
@video-en-direct You can navigate to the path thru finder, it should be this file:
`/Users/USERNAME/Library/Application Support/companion/db`
