### ISSUE TITLE
Feature Request: eject mass storage

### ISSUE THREAD

**Issue by Jockgerman** [bitfocus/companion#244]
**Describe the feature**
- Eject Mass storage device. D:
- Eject Mass storage device. E:
- Eject Mass storage device. F:
- Eject Mass storage device. G:
- Eject Mass storage device. H:
It would be great to have this in regards to the IP. But that is just a bonus!

**Is this platform dependent (windows, mac, ..)?**
Windows

**If documentation is required to implement, do you know where to find it?**

Here is already a .exe file that does this. 
https://www.uwe-sieber.de/drivetools.html

**Usecases**
Quickly connecting and disconnecting USB Sticks.

**Comment by willosof** [comment]
That's a funny feature! I like it. 
- I think this should be a part of the Companion Helper (redundant, intended). This will do stuff like the octopus thingy, but a bit more nifty stuff.
