### ISSUE TITLE
Reorder Connections

### ISSUE THREAD

**Issue by jeffmpelletier** [bitfocus/companion#2440]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

In the connections tab, I would like the ability to sort, ideally manually by dragging connections up or down, but I would think it's easy to add the ability to sort at least by the 'Module' or 'Label' fields.

**Comment by jeffmpelletier** [comment]
Sorry if this is a stupid question, but I assume 3.0 is beta. When might it
be public release?

**Comment by Julusian** [comment]
yes 3.0 is beta
at this point 'soon' is the most accurate I can be. we wanted to have it done by now, but have been blocked on some popular modules being very broken
