### ISSUE TITLE
[BUG v3] Capslock breaks copying buttons

### ISSUE THREAD

**Issue by UnderscoreZero** [bitfocus/companion#2443]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It seems that companion recognises a copy/paste with ctrl+c but not ctrl+C. Might be handy to fix this for general usability

**Comment by Julusian** [comment]
Thanks for the report. This is fixed in the next beta build
