### ISSUE TITLE
Module Request: Roland V-1HD 4/ Roland V800HD

### ISSUE THREAD

**Issue by Jockgerman** [bitfocus/companion#245]
**Describe the feature**
- Select Input to Preview Output
- Select Input to Main Output
- Take 
- Change Frequency 50Hz <--> 60Hz (59,9)
- Preview Out --> Switch between Modes (Multiview, Preview, Output 2)
 
**Is this platform dependent (windows, mac, ..)?**
Windows

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along

**Usecases**
Remotly control Roland Video Switch

**Comment by willosof** [comment]
Can I close this? 🤔I for sure won't work on it. 😁

**Comment by Jockgerman** [comment]
😄 sure

Am So., 25. Nov. 2018, 18:04 hat William Viker <notifications@github.com>
geschrieben:

**Comment by dnmeid** [comment]
Closed because of non-compatibility with Companion at this time. You can re-open the issue when we have a solution for controlling stuff by other means than ethernet.
