### ISSUE TITLE
[BUG][Beta 3.0.0] `Collapse Action/Feedback view` is lost when deactivatiing action

### ISSUE THREAD

**Issue by VuiMuich** [bitfocus/companion#2452]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When deactivating some added `Action` or `Feedback` on the respective tab of a button config the widget button `Collapse` disappears and is not restore with reactivation.
(only when the whole view of the `div` is forced to update it gets restored)

### Steps To Reproduce

1. Go to `Buttons` tab
2. select any button
3. [optional] select `Feedbacks` tab
4. add an arbitrary Action/Feedback
5. use the `deactivate` switch
6. _observe_ `collapse` button vanish
7. use `activate` switch
8.  _observe_ `collapse` button still missing
9. [optional] refresh the whole div by either clicking one of the tabs `Actions`, `Feedback`, `+` (to add step) or the whole button config to see the button restored

Step 5
![2023-05-15-200815_174x92_scrot](https://github.com/bitfocus/companion/assets/4779365/8773ed91-63b3-45b0-abe5-ac2d0995e8d0)
Step 6
![2023-05-15-200834_153x74_scrot](https://github.com/bitfocus/companion/assets/4779365/093a4979-7c5b-4988-9fe7-b307bd83a32f)
Step 8
![2023-05-15-200844_141x70_scrot](https://github.com/bitfocus/companion/assets/4779365/031988cf-b7ae-47e4-be43-f0eb72924de3)
 

### Expected Behavior

The button should get restored with the re-activation of the action/feedback.

### Environment (please complete the following information)

```markdown
- OS: Manjaro Linux x64 and Win11
- Browser: qutebrowser (webengine/blink) and MS Edge
- Companion Version: Build 3.0.0+5885-beta-142d1bfa
```

**Comment by Julusian** [comment]
Thanks for reporting this.
Should be fixed now
