### ISSUE TITLE
Streamdecks not detected

### ISSUE THREAD

**Issue by tejasraman** [bitfocus/companion#2457]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In Bitfocus versions 3.0.0-beta and 3.9.9-dev, my Original Stream Deck is not detected by the Companion app. I am using Fedora 38 (KDE). This does not occur in 2.4.2 (Deck is detected).

### Steps To Reproduce

Download Bitfocus Companion for Linux
Launch the app
Try to detect Stream Deck(s)

### Expected Behavior

The Deck would be detected

### Environment (please complete the following information)

```markdown
- OS: Fedora 38 (KDE)
- Browser: Firefox 113.0.1
- Companion Version: 3.0.0 and 3.9.9 (not 2.4.2)
```

**Comment by Julusian** [comment]
Did you update the udev rules on your system?
In 3.0 a different hhid backend is used which needs different udev rules to 2.4

**Comment by tejasraman** [comment]
No. I am running a systemd version which is >250 (which supposedly doesn't need udev rules); however, I might need them for version 3.

I'll try to find the udev rules and try them. Thanks so much @Julusian

**Comment by Julusian** [comment]
https://github.com/bitfocus/companion/blob/beta/assets/linux/50-companion.rules
This is what you need. I think there is a rradme file next to it in the repository that explains what to do with it.

I'm pretty sure you will still need it even with systemd

**Comment by tejasraman** [comment]
It all works now - thanks so much @Julusian
