### ISSUE TITLE
Feature Request: Action to change button style as a delayed action.

### ISSUE THREAD

**Issue by SalkinDK** [bitfocus/companion#246]
**Describe the feature**
Have a generic action to change the button style, fx the png file, when the button has been pressed.

**Is this platform dependent (windows, mac, ..)?**
no

**If documentation is required to implement, do you know where to find it?**

**Usecases**
If I have a aja-helo action to start a recording, I could have a pause and a record logo, and then make it change when the button was pressed.

**Comment by dnmeid** [comment]
This will be possible with #229

**Comment by dnmeid** [comment]
Closing this old issue now that the internal module can provide most of the requested functionality. Text and background color can be changed from an action. As text can contain icons for the usecase changing pngs is not needed.
