### ISSUE TITLE
[BUG] Stream Deck Mini not found

### ISSUE THREAD

**Issue by gobo-ws** [bitfocus/companion#2464]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Elgato Stream Deck Mini not found in the surface list, clicking on the button "Rescan USB" generates the following text in the log:
`23.05.31 16:53:03 Surface/Controller: Failed to add "elgato-streamdeck" device: could not get feature report from device AND GOT: {"id":"0","cmd":"add","type":"elgato-streamdeck","devicepath":"\\\\?\\hid#vid_0fd9&pid_0063#6&495cd8f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}"}`

### Steps To Reproduce

Clicking on Surfaces -> Rescan USB -> Results in an empty Surfaces list

### Expected Behavior

The device should appear in the Surfaces list

### Environment (please complete the following information)

```markdown
- OS: Windows 11 22H2 x64
- Browser: Chrome 114.0.5735.91
- Companion Version: 3.0.0-rc1 (3.0.0-rc1+5909-v3-0.0-rc1-725c3583
```

### Additional context

Elgato Stream Deck Mini firmware 3.02.001

**Comment by Julusian** [comment]
Does this streamdeck work with 2.4.2?
That log line says that we know what it is, and tried to use it but it didnt respond to one of the messages we sent to it

**Comment by gobo-ws** [comment]
> Does this streamdeck work with 2.4.2? That log line says that we know what it is, and tried to use it but it didnt respond to one of the messages we sent to it

Hi, thanks for your answer. I have not tried to install 2.4.2 but I will test it during the weekend. Will return with the result

**Comment by gobo-ws** [comment]
2.42 has been removed from the download section.

Tested with the beta and the new experimental version but still the same problem:

**Beta 3.0.0 (3.0.0+5920-beta-9cc0ebee)**
`23.06.02 18:56:06 Surface/Controller: Failed to add "elgato-streamdeck" device: could not get feature report from device AND GOT: {"id":"0","cmd":"add","type":"elgato-streamdeck","devicepath":"\\\\?\\hid#vid_0fd9&pid_0063#6&495cd8f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}"}`

**Experimental 3.99.0 (3.99.0+5971-develop-23af99f4)**
`23.06.02 18:46:40 Surface/Controller: Failed to add "elgato-streamdeck" device: Error: could not get feature report from device`

**Comment by Julusian** [comment]
The download is still there, but it's under the older builds (button on the right)

**Comment by gobo-ws** [comment]
Yeah sorry, found it. The device is not detected with version 2.4.2 either. The logs file is empty without any errors messages.

**Comment by adlaws** [comment]
I can confirm that I see the same behaviour on Windows, and also under Debian 11 with v3.0 rc-1 with a StreamDeck Mini (3x2 buttons).

Interestingly, on Debian 11 it works fine with the v2.4.2 release, though with Windows (on the v2.4.2 release) it fails to detect it.

As with @gobo-ws, the log is completely empty in the case of no detection - it just fails to detect anything.

Both v2.4.2 and v3.0 rc-1 work fine when operating using the "StreamDeck software via Companion plugin" option (in Windows, at least), though of course in this mode it's not worrying about USB detection.

In case it's of any use in tracking down the problem, the model number of my StreamDeck Mini is 20GAI9901.

**Comment by gobo-ws** [comment]
I installed 3.0.0-rc1 on a Raspberry Pi 4 running Debian 11 (don't know why the installation script replaced my MOTD though but that is another question)
Companion detects the device and it is working fine. I also have the 20GAI9901 model.

**Comment by Julusian** [comment]
I have gotten my hands on a mini to test this with, and I can confirm that a 20GAI9901 with the latest firmware (3.02.001) it does work on linux but not on windows.

This shouldn't be too bad to fix now that I can reproduce it!

**Comment by Julusian** [comment]
This is fixed in beta 5978

**Comment by adlaws** [comment]
I can confirm that my StreamDeck Mini is now detected - tested with Beta 3.0.0+5979

**Comment by gobo-ws** [comment]
> I can confirm that my StreamDeck Mini is now detected on Windows - tested with Beta 3.0.0+5979. I'll check on Debian as soon as I am able.

Same here

**Comment by Julusian** [comment]
Thats great to hear!

> I can confirm that my StreamDeck Mini is now detected on Windows - tested with Beta 3.0.0+5979. I'll check on Debian as soon as I am able.

The debian is more likely to be that between 2.4 and 3.0 we changed hid backends on linux, and they need different udev rules.

**Comment by fmg-andrewlaws** [comment]
Hi again - I've just tested in Debian using 3.0.0+5987-beta-16c68af4, but it's still *not* detecting the StreamDeck mini under that OS (it's the exact same StreamDeck Mini in both cases - I just switch the USB cable across).

v2.4.2 (2.4.2+4911-v2-4.2-fcb5a863) works fine though.

**Comment by adlaws** [comment]
Hi again - I've just tested in Debian using 3.0.0+5987-beta-16c68af4, but it's still not detecting the StreamDeck mini under that OS (it's the exact same StreamDeck Mini in both cases - I just switch the USB cable across).

v2.4.2 (2.4.2+4911-v2-4.2-fcb5a863) works fine though.

**Comment by Julusian** [comment]
@adlaws did you check/update your udev rules?

The linux downloads include a copy of that file you can use

**Comment by adlaws** [comment]
@Julusian - that's fixed it. My apologies that I missed that - everything is working perfectly now 👍
