### ISSUE TITLE
[BUG] Pagenumber button not updated correctly

### ISSUE THREAD

**Issue by dnmeid** [bitfocus/companion#2468]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The button preview for page number buttons is not reliably updated in webui in the buttons grid.
If you open the webui and then edit the page name for the first page the preview is updated immadiately.
After you changed the previewed page the first time, the preview of the page number button will not be updated any more when the name changes.
The update is correctly done in the preview of the EditButton component and also in emulator. Socket.io gets the update immediately. I guess it's some problem with the caching.

### Steps To Reproduce

* Open Webui
* Change to different page
* Edit page name

### Environment (please complete the following information)

```markdown
- OS: MacOS
- Browser: Firefox
- Companion Version: 3.0.0-rc1
```

### Additional context

<img width="119" alt="image" src="https://github.com/bitfocus/companion/assets/8548888/477c581b-b683-4259-806e-1d3606710cb7">

**Comment by Julusian** [comment]
db19510100f1bec7ceccabfb35912d24518dd17f
