### ISSUE TITLE
analogway-midra: Switch Layer Input In/Frame 10 switches to input 9

### ISSUE THREAD

**Issue by SalkinDK** [bitfocus/companion#247]
**Describe the bug**
choosing a analogway-midra: Switch Layer Input action with the following settings, switches to input 9 (SDI 3) instead of input 10 (SDI 4)
Screen: S1
Preview/Program: Program
Layer: pip layer 1
Input: In/Frame 10

**To Reproduce**
Config the button with the settings above, and press test action.
It should work, but when you then go to instance and back to buttons, and press edit button, it have changed to In/Frame 9 instead.

**Expected behavior**
Should not change

**Screenshots**

**Desktop (please complete the following information):**
 - OS: osx
 - Browser chrome, and safari
 - Version companion-latest-osx.zip as of 2018-Sep-19 10:29

**Additional context**

**Comment by willosof** [comment]
This issue was moved to bitfocus/companion-module-analogway-midra#3
