### ISSUE TITLE
[BUG] Set Current Step for button not executing said step actions

### ISSUE THREAD

**Issue by Mozoloa** [bitfocus/companion#2476]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm wondering what I'm doing wrong, I'd like to have a "Mass untoggle" button that resets multiple buttons to step 1 but when using "set current step" on all of those button in the main button, it does change the step well but doesn't execute the actions from said step ?

Before when there only was a toggle functionnality, I could use "release" so it would untoggle any button that was toggled, but now there's no indication as to from which step it's going to to exec the release actions.

This is important: some buttons might already be at step 1 when the "mass untoggle" button is pressed, I want them to stay there

Using 3.0.0-rc1 (3.0.0-rc1+5909-v3-0.0-rc1-725c3583

### Steps To Reproduce

1. Create 2 buttons with two steps (toggle configuration)
2. Add press actions for toggle (step 1) and untoggle (step2) steps
3. Create a third button to mass untoggle the first two the following way:
4. Use the **_Set current step_** action on said button, to revert to step 1 on the first two buttons 
<img width="579" alt="image" src="https://github.com/bitfocus/companion/assets/20817233/02864d23-ef1e-48de-9cf9-e15adc313ae4">

5. Toggle the first two buttons to check actions execute correctly then leave them toggled (on step 2)
6. Press the third "mass untoggle" button
7. Observe that the first two buttons are indeed reverted to step 1
8. Observe that step 1 action never got triggered on those buttons tho

### Expected Behavior

I expect the step the buttons are reverted to, to actually trigger the actions on said step

### Environment (please complete the following information)

```markdown
- OS: MacOS Ventura 13.2.1
- Browser: Brave
- Companion Version: 3.0.0-rc1 (3.0.0-rc1+5909-v3-0.0-rc1-725c3583
```

### Additional context

- Using **trigger press** or **press + release** just cycles through the steps so it's useless to force untoggle
- Using **trigger release** does nothing (there are no release actions on either step anyway)

**Comment by dnmeid** [comment]
The action will set the button to a step. This means the actions of the step are to be executed when the button is pressed the next time.
What you describe is not a bug but the intended behaviour of this action.

**Comment by Mozoloa** [comment]
How could I do what I intend to do though ? Before with the toggle mechanism it was pretty straight forward and self contained, now I'm a bit confused

**Comment by Mozoloa** [comment]
For those searching for a solutions, just set the "set current step" action to set it to the step before the one you want to actually trigger, then simply add another action to press (force) the button. This adds one action for every button but it's way faster than fiddling with variables.

@dnmeid do you think it would be worth posting an internal module feature request to add a checkbox in the set current step action to press the button afterwards ?

**Comment by dnmeid** [comment]
> do you think it would be worth posting an internal module feature request to add a checkbox in the set current step action to press the button afterwards ?

no, it won't. We already have too many checkboxes written for some special needs of only a very few users. There is an existing solution and it takes a few more actions to solve your problem but it enhance the clarity of actions and options. It is more the RISC approach.
