### ISSUE TITLE
[BUG] How to install 2.4.2 on Raspberry PI

### ISSUE THREAD

**Issue by sledzik1984** [bitfocus/companion#2477]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As - at the moment - many modules are marked as "May not work" there should be a way to install 2.4.2 using "old method" (git clone, yarn update ....)

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by Julusian** [comment]
The v2.4.2 companionpi image is still available on the website.

Or if you want to install it yourself, I have added some extra steps to the install guide [here](https://github.com/bitfocus/companion-pi#other-debianubuntu) which will downgrade that install from 3.0 to 2.4.2

**Comment by Julusian** [comment]
> As - at the moment - many modules are marked as "May not work" 

As far as we're aware, 85% of the modules marked as "May not work" have not been reported as being broken. Until someone reports them as broken we are assuming they are working fine
