### ISSUE TITLE
[BUG] Default username/password in documentation correct?

### ISSUE THREAD

**Issue by rwslippey** [bitfocus/companion#2478]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've just got companion going on a Pi4 and for the life of me I can't SSH into it. is the default password still "raspberry"?

### Steps To Reproduce

ssh pi@<IPADDRESS>
Prompted for password
Enter password "raspberry"
Incorrect password

### Environment (please complete the following information)

```markdown
- OS: Campanion Pi image
- Browser: N/A
- Companion Version: companion-pi-stable-v3.0.0-rc1-05-06-23
```

**Comment by rwslippey** [comment]
Ahh, Okay... Didn't know they did that..... shows you how long it's been since I've been into a new Pi, but I guess that's what happens when they're impossible for find for a year or more.

Thanks!

**Comment by rywolf** [comment]
Can you pre-configure the user for future builds..  Its a bit tricky to setup the user now..
