### ISSUE TITLE
BMD ATEM 1 M/E AUX Switching Incorrect on AUX 2 and 3

### ISSUE THREAD

**Issue by SerialForBreakfast** [bitfocus/companion#248]
**Describe the bug**
When switching with an ATEM 1 M/E Production Switcher
Using the “atem: Set AUX bus” command, switching Inputs to the Aux 1 bus works properly.
When switching AUX 2 or 3, the routes are performed on the AUX 1 bus and 2 and 3 remain unchanged.

**To Reproduce**
1. Create BMD Atem Instance
2. Add button to "Set AUX Bus"
3. Select AUX Output 2 and Input 2
4. Test/Press the button

**Expected behavior**
AUX Output 2 should change to Input 2. 

**Observed behavior**
AUX Output 1 is changed to Input 2

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: OSX 10.13.6
 - Browser Chrome Version 69.0.3497.100 (Official Build) (64-bit)

**Additional context**

**Comment by haakonnessjoen** [comment]
This is fixed in daily builds version at builds.bitfocus.io/companion/
