### ISSUE TITLE
Set a variable on a specific step

### ISSUE THREAD

**Issue by d7launganivpn** [bitfocus/companion#2481]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

The ability to change a variable in a step with custom value and control when that action runs with a delay.

### Usecases

My use case is to be able to reset the state of a button after a specific amount of time after the button is pressed.

I have a variable that holds the button state . The issue is after 5 seconds after the button is pressed I want to reset the state of it aka change the value of the variable that represent's the button state.

The problem is the only way to change a variable (from what I understand and checked) is by using a connection that has a function that allows you to change the variable based on that connection. There is no generic way to modify variables in a step with a delay.

**Comment by Julusian** [comment]
I am not entirely sure what you are wanting to do, but custom variables might be able to do it?

**Comment by Julusian** [comment]
like this?
![image](https://github.com/bitfocus/companion/assets/1327476/583a78c5-efa8-47f1-b109-4633caf7f1a9)

**Comment by Julusian** [comment]
no problem :)
