### ISSUE TITLE
[BUG] Set serialnumber to page "Back" can stop working

### ISSUE THREAD

**Issue by tikatoo** [bitfocus/companion#2484]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

At certain points, the _internal: Surface: Set serialnumber to page_ action, when set to go to page _Back_, will not perform the action. This does not affect navigating to a specific page, and as a workaround, I can temporarily modify those actions to go to the page I want (then change back for later). Also, if I can navigate to a button configured with _internal: System: Restart companion_, the _Back_ actions will work again for some time (though if my only path there involves a _Back_ action, this obviously isn't as straight-forward).

### Steps To Reproduce

1. Configure a button with the action _internal: Surface: Set serialnumber to page_, with destination page _Back_
    - Note: I've only tried this with the _Surface / controller_ option set to _Current surface_.
2. Wait for some internal condition (my uneducated guess: fill up an internal history buffer).
3. Navigate from some other page to the page used in step 1.
4. Press the button configured in step 1.
5. Observe that the page does not change.

### Expected Behavior

At step 4, the surface should navigate to the page that was active at the start of step 3.

### Environment (please complete the following information)

```markdown
- OS: Debian Bullseye
- Browser: Firefox
- Companion Version: 3.0.0-rc1+5909-v3-0.0-rc1-725c3583
```

**Comment by Julusian** [comment]
your suspicion was correct, when the history buffer filled up it would be counting off by one, causing it to not find a page to navigate to. 
This is now fixed
