### ISSUE TITLE
support other keyboard(with LCD buttons)but not stream deck

### ISSUE THREAD

**Issue by VincentTop1** [bitfocus/companion#2485]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

how can companion support other customes keyboard(with LCD buttons) like streamdeck but not?
is there any configertion entrance in there?

**Comment by dnmeid** [comment]
Is this a feature request or a simple question?
Companion does support Infinitton iDisplay, Loupdecks and Razer Stream Controller besides Elgato Streamdecks and Pedal. You do not need to configure something for them.

**Comment by dnmeid** [comment]
Closing this issue as there is no answer from original poster.
