### ISSUE TITLE
Allow variables for "Use another buttons style" Page and Button options

### ISSUE THREAD

**Issue by drakz-AU** [bitfocus/companion#2486]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Can we please allow the use of variables for the 'Page' and 'Button' options for the "internal: Button: Use another buttons style" feedback.

### Usecases

I am trying to build 'submenu' buttons on part of a page. So pressing one button would update other buttons on a page to perform different actions, without taking me to a completely different page for the submenu.

Currently I can change the action that a button will perform by changing the step that the button is at, but I cannot significantly change the look of the button. Ideally I would like to set up my 'submenus' on a different page and then pull the buttons from there. This way I could build several submenus on a single hidden page.
However as there is only one feedback step per button, and 'Use another buttons style' does not allow variables, this is not currently possible (that I am aware of, maybe I'm going about it wrong?)

There are some other issues open that could possibly help to achieve my goal. Particularly [2206](https://github.com/bitfocus/companion/issues/2206), also [2414](https://github.com/bitfocus/companion/issues/2414), [2367](https://github.com/bitfocus/companion/issues/2367), and [2294](https://github.com/bitfocus/companion/issues/2294) that I have found so far.

**Comment by Julusian** [comment]
This is possible in 3.2 (current beta builds)
