### ISSUE TITLE
Request: "on condition becoming false" trigger

### ISSUE THREAD

**Issue by odedd** [bitfocus/companion#2487]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

A "on condition becoming false" trigger would be very helpful for performing actions when a condition stops being true.

### Usecases

**Menu system**

There are numerous scenarios, but here's a very useful one that I think could benefit lots of users:

I have two Stream Decks. One of them has a row of buttons that change pages on the other one, acting as a "menu" of sorts.
I want to highlight the currently active page by changing the corresponding's "menu" button's background color.
This can be achieved by a trigger:
```
on condition becoming true -> 
internal: Surface: When on the selected page -> 
internal: Button: Set background color -> "highlighted" color
```

That's great. However, I need to change the color back to its original state when I'm moving to another page.
I could do it with each page resetting all of the menu's colors, but that would be tedious and shouldn't be necessary.

Instead, something like that would be great:
```
on condition becoming FALSE
-> internal: Surface: When on the selected page 
-> internal: Button: Set background color -> "regular" color
```

**Comment by Julusian** [comment]
This was implemented a while ago in the experimental builds, but never made it to the betas for some reason.
It will be in the 5971 build

**Comment by pxalb** [comment]
@Julusian thank you for your explanation.

Actually, I can select this feedback "internal: Surface: When on the selected page" but only for physical surfaces that are connected. It would be useful to select surface by index as it happens in some press actions like "internal: Surface: Set by index to page" because if I change the physical surface, the feedback keeps working for any other

Thanks for your support!

**Comment by magdatev** [comment]
@Julusian have you found a solution? Im missing this feature too. Im using satellites only...

**Comment by dnmeid** [comment]
This issue is completed and closed and your follow-up is not a reason to reopen it. Please open a new issue if you have any further requests not related to "on condition becoming false" trigger.
