### ISSUE TITLE
Javascript error while attempting to launch Beta on fresh Windows 10 install

### ISSUE THREAD

**Issue by alomanto** [bitfocus/companion#2489]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am installing the current available Companion Beta (3.0.0+5967) on a fresh Windows 10 install (10.0.19045 / 22H2) with up-to-date windows updates. Companion installs without error, but when I launch it, I get the following error:

![image](https://github.com/bitfocus/companion/assets/20320269/217d69ef-a6de-4511-a32e-9fa1b4d8f2e0)

A Javascript error occured in the main process

Uncaught Exception:
Error: Cannot find module '../lib/Data/Paths.cjs'
Require stack:
- C:\Program Files\Companion\resources\app.asar\main.js

### Steps To Reproduce

1. Install Companion Beta 3.0.0+5967
2. Launch Companion Beta
3. Receive Error

### Expected Behavior

The expected behavior is that Companion launches without error.

### Environment (please complete the following information)

```markdown
- OS: Windows 10 22H2 10.0.19045
- Browser: Firefox 114.0.1
- Companion Version: 3.0.0+5967
```

### Additional context

I tried installing the Production / Non-Beta version, and it installs/launches without error.

**Comment by Julusian** [comment]
Thanks for reporting.

This is fixed in beta 5968
