### ISSUE TITLE
Feature Request: Turn all Icons 90°

### ISSUE THREAD

**Issue by Jockgerman** [bitfocus/companion#249]
**Describe the feature**
Turn Icons 90°, 270°

**Is this platform dependent (windows, mac, ..)?**
no

**Usecases**
Livecore:  For the memorys I would like to use my stream decks vertical to have more rows instead of more columns.

**Comment by haakonnessjoen** [comment]
Fixed in e2276da. (but only 90 right now, mostly to satisfy the infinitton device)
