### ISSUE TITLE
Admin UI Password Reset

### ISSUE THREAD

**Issue by bryce-seifert** [bitfocus/companion#2492]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

- Ability to easily reset password for the admin UI

I'm not sure what the best route is, but I think anything that can be simpler than having to direct to the config folder and search the file. I'm wondering if it could simply be a url, to direct people to x.x.x.x:8080/resetpassword given how low-security this authentication method is already. Or by having the user press a specific button on a connected surface?
Or if it needs to be something more complex, like linking accounts with the Bitfocus site. But that feels like a large undertaking for something that is mostly a deterrent than a security feature.

### Usecases

- If the user forgets the password
- The password is somehow set via a bug that is seen relatively regularly

**Comment by dnmeid** [comment]
I think best place would be somewhere at the launcher window, then you would at least need direct access to the host computer.
Definitely not a remote operation.
