### ISSUE TITLE
Trigger conditions logic for multiple conditions (And/Or)

### ISSUE THREAD

**Issue by odedd** [bitfocus/companion#2495]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

When using multiple conditions, users should be allowed to select whether the conditions are strung together via "and" or "or" conditions.
Ideally, there should also be bracketing implementation for the most flexibility,
eg. ```(cond1 AND cond2) or cond3```

Conditions are currently connected via "AND" which is not useful in some instances.
For example:
```On condition becoming true -> When surface X is on page Y (AND) When surface X is on page Z```
Will never fire, obviously. And "OR" condition will solve that.

[Here's a screenshot of this type of system](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.noodlesoft.com%2Fmanual%2Fhazel%2Fadvanced-topics%2Fsyncing-folders%2F&psig=AOvVaw1tvhkdvXM6Z6YovMd7cVGa&ust=1687512510614000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCPjP2Y_I1v8CFQAAAAAdAAAAABAJ) in action from the mac desktop app Hazel.

### Usecases

When designing a menu system with button highlights, some buttons need to be highlighted when one of several conditions apply. This can be done using multiple conditions, but would be greatly simplified with a selection of the logic.

**Comment by Julusian** [comment]
This is something we want to do, but it isnt being worked on yet.

The Conditions are using the feedback system so this is the same as https://github.com/bitfocus/companion/issues/372
