### ISSUE TITLE
[BUG] Acces on others device

### ISSUE THREAD

**Issue by lucasglq** [bitfocus/companion#2497]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am writing to report a bug I encountered in the Companion app, specifically related to the remote control feature. Ever since version 2.4.2, I have been unable to access the app's controls from another device, but still able to acces on the server device.

### Steps To Reproduce

1- Ensure both devices are connected to the same network.
2- Launch the Companion app on the primary device (Device A).
3- Open the app on the secondary device (Device B) and attempt to establish a remote connection to Device A.
4- Device B successfully detects Device A on the network, but when attempting to establish the connection, it fails consistently.

### Environment (please complete the following information)

```markdown
- OS: Win10, iOS 16.5
- Browser:Firefox, Chrome and others
- Companion Version: 3.0.0 and up
```

**Comment by dnmeid** [comment]
You have to select the correct listen interface for Companion's webserver.
By default Companion listens to 127.0.0.1 or localhost. That means all traffic from a remote machine will be ignored.
You can either switch the interface to your external IP address, but then you have to use the external address also to access Companion from the local machine. Or you switch the interface to 0.0.0.0, then Companion listens on all interfaces and you can access it with localhost and the external IP.

**Comment by dnmeid** [comment]
There are many possible reasons for network connection problems, it is completely out of reach to do a complete problem analysis here.
You should try to use different ports, maybe this helps. There can also be problems with some windows services, routing problems (e.g wrong ARP resolution)...
Try it on a different machine.
If nothing helps, network problems can often be traced with tools like Wireshark.
