### ISSUE TITLE
Feature Request: Millumin 2 

### ISSUE THREAD

**Issue by Deanbau** [bitfocus/companion#25]
Control of Millumin via OSC

https://github.com/anome/millumin-dev-kit/wiki/OSC-documentation

**Comment by Deanbau** [comment]
**Suggested controls**

/millumin/action/launchOrStopColumn [index or "name"]
/millumin/action/launchColumn [index or "name"]
/millumin/action/stopColumn

/millumin/action/launchPreviousColumn
/millumin/action/launchNextColumn

/millumin/action/playTimeline
/millumin/action/pauseTimeline
/millumin/action/playOrPauseTimeline
/millumin/action/goToTimelineSegment ["name"]

/millumin/selectedLayer/media/normalizedTime [0.9] (jump to the last 10% of the media)

/millumin/selectedLayer/startMedia to restart current media
/millumin/selectedLayer/startMedia [7] to start media at 7th column
/millumin/selectedLayer/startMedia ["Movie.mov"] to start media named "Movie.mov"
/millumin/selectedLayer/pauseMedia to pause current media
/millumin/selectedLayer/startOrPauseMedia to start/pause current media
/millumin/selectedLayer/stopMedia to stop current media

**Feedback from Millumin**

/millumin/board/launchedColumn [index,"name"] (last argument is absent if column has no name)
/millumin/board/stoppedColumn [index,"name"] (last argument is absent if the column has no name)

/millumin/selectedLayer/media/time (Returns as two strings, current time and total media time)

**Comment by willosof** [comment]
Dont we have this now? What's missing @PerRoine ? You have dropdowns and input fields now on actions, so it would be easy to implement the names etc.

**Comment by PerRoine** [comment]
I will Improve on the module coming week, have just been to busy and to damed hot lately,

**Comment by PerRoine** [comment]
Have made all the suggested actions but need to test properly, closing the issue for now

**Comment by Deanbau** [comment]
There's a few issues with the media control.

> Media can be targeted directly by their name, or by identifying the layer first :

> /millumin/Movie.mov/... to target the media named "Movie.mov"

Therefore all media commands need to ask for the movie name.  (There really should be a way to sl

Unsure if 

`/millumin/Movie.mov/startOrPauseMedia`

Will work.. 

Alternatively - this command could be used to select a layer before performing an action

`/millumin/layer:myLayerName/selected [1] to select layer named "myLayerName"`
