### ISSUE TITLE
Internal Variable for each button

### ISSUE THREAD

**Issue by jluc101** [bitfocus/companion#2500]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Just like the $(internal:page_number_1_name) Page Names...Internal Variables for each button would allow these variables or a collection of button variables to be used in expressions. 

### Usecases

This would allow for Group targeting of buttons for "Set Current Step" expressions along with all other situations where a button press is allowed to make changes to other buttons.

**Comment by Julusian** [comment]
There are already variables for these, of the format `b_text_${page}_${bank}`. They arent shown in the suggestions, as it would add an extra 3000 variables to the list and the ui can get a bit grumpy about it

**Comment by jluc101** [comment]
Would this allow for a list of buttons to be used in an expression? if so give me an example of how that would be written in expression form. Even if it's for buttons/bans 1, 2, & 3.

**Comment by mideka** [comment]
> 
Really? Cannot find that. Could you explain?
