### ISSUE TITLE
Internal variables for instance/connection states

### ISSUE THREAD

**Issue by josephdadams** [bitfocus/companion#2507]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Create internal variables for instances total, total disabled, total ok, total error, total warning

### Usecases

So we can show this data on buttons or use it to send to other programs as needed

**Comment by Julusian** [comment]
We already have these variables 
![image](https://github.com/bitfocus/companion/assets/1327476/7194fc35-00e4-4fa5-bc0b-b74eb253068b)
which looks like half of the ones you want
