### ISSUE TITLE
[BUG] Ember+ listener control lost in V3

### ISSUE THREAD

**Issue by griffon56** [bitfocus/companion#2508]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Since I moved to V3, I cannot change state or label of Ember+ listener  anymore.

I tested with [Ember+ viewer ](https://github.com/Lawo/ember-plus/releases) to connect to port 9092. The Ember tree is discovered correctly and reflects the state and label of each button.
But when i tried to change state or label from the external ember + client such as [Ember+ viewer](https://github.com/Lawo/ember-plus/releases), the change is not reflected. I get following errors :
when changing state --> "Cannot read properties of undefined (reading 'action')"
when changing label --> "Cannot read properties of undefined (reading '15')" 15 reflects the page number where the change was requested

![image (1)](https://github.com/bitfocus/companion/assets/25333002/14e379f0-2a53-4168-9656-d9add3622367)
![image](https://github.com/bitfocus/companion/assets/25333002/e19be4dc-1359-4a4e-8a01-7d4494bb3733)

### Environment (please complete the following information)

```markdown
- OS: Windows 10
- Browser: Chrome
- Companion Version: V3.0.0-rc1
```

**Comment by Julusian** [comment]
This appears to have been missed during the large rewrites of 3.0, but the emitting of data was not.
This is fixed in beta 6002

**Comment by griffon56** [comment]
Many thanks for your quick feedback!
Indeed, installing beta 6003 fixed the issue =D
