### ISSUE TITLE
Allen & Heath Colour Feedback Companion Issue [BUG]

### ISSUE THREAD

**Issue by YvonneMV** [bitfocus/companion#2513]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I believe this is a 3.0 bug because the behavior is as expected while I am editing the key - if the input is in a muted state and I change the feedback color, the key will immediately change to the new feedback color; and if the input is in an unmuted state, the key **will  immediately return to the default key color as expected**.  

The issue is beyond this (after changing the feedbacks formatting), the key's color change will trigger when the mute is activated as expected, however it will not return to the default actions key color/formatting when the input is unmuted.  This was the functionality in previous versions of Companion.  

I have observed this behavior for Input, Mute Groups, Aux.  I believe the issue affects all Colour Feedback functionality.

I have of course reported this bug in the A&H SQ module, but it seems they have not released a new version in well over a year. It truly seems this is bug related to the new version of Companion especially since it does in fact function as expected while in the editing state.  Also, if I disable the connection and reenable, the button color will reflect the proper state once the connection is reestablished.

### Steps To Reproduce

1. Set up colour feedback for SQ input that differs from default formatting for the key.
2. Trigger mute for selected input.
3. Observe color/formatting change of key.
4. Trigger unmute for selected input.
5. Observe that key no longer returns to the default state as it has in previous Companion versions.

### Expected Behavior

When muting mute group or selected input (depending on which feedback you chose), the key background/foreground change to the formatting set in feedbacks.  When the group or input is unmuted, the key background/foreground changes to the formatting on the Action tab.

### Environment (please complete the following information)

```markdown
- OS:Win10
- Browser:Chrome 114.0.5735.199
- Companion Version:3.0.0-rc2+5989-stable-4d17e724
```

**Comment by Julusian** [comment]
I've taken a stab at this, as there was some of what looked like incorrect usage that could explain this.
If beta 6020 doesnt fix it, then I don't know what the problem could be.
Various modules have been broken by the new implemention of the old module api, as it was so loosely defined with numerous edge cases making it incredibly hard to recreate without breaking things.
