### ISSUE TITLE
[BUG] starting v3.0.0-rc2 with only `--admin-interface` errors out because it conflicts with admin-address

### ISSUE THREAD

**Issue by fkusei** [bitfocus/companion#2514]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm starting companion using `node /opt/bitfocus-companion/main.js --admin-interface eno1 --config-dir /var/opt/bitfocus-companion`. This leads to the following error:
```
Tue 2023-07-04 10:42:01 UTC systemd[1]: Starting Bitfocus Companion...
Tue 2023-07-04 10:42:01 UTC systemd[1]: Started Bitfocus Companion.
Tue 2023-07-04 10:42:03 UTC node[97374]: 2023-07-04T10:42:03.913Z info Log/Controller Application starting
Tue 2023-07-04 10:42:03 UTC node[97374]: Only one of admin-interface and admin-address can be specified
Tue 2023-07-04 10:42:03 UTC systemd[1]: bitfocus-companion.service: Main process exited, code=exited, status=1/FAILURE
Tue 2023-07-04 10:42:03 UTC systemd[1]: bitfocus-companion.service: Failed with result 'exit-code'.
```

I believe this is caused by the default value for `--admin-address`, so it is always set.

### Expected Behavior

`--admin-interface` works as intended

### Environment (please complete the following information)

```markdown
- Ubuntu 20.04 x86
- Nodejs 18.16.1
```

**Comment by Julusian** [comment]
This is fixed in beta 6019
