### ISSUE TITLE
FUNCTION REQUEST: Add a random number generator function to the expression options.

### ISSUE THREAD

**Issue by Nolanova** [bitfocus/companion#2515]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

The new expression system in the 3.0 RC is a very nice addition to increase scripting potential. It would be nice to have a random number generator as one of the numerical functions in order to select a button from a set of options randomly.

I believe this would work well with the new options to select button presses internally based on custom variable values.

My design thought on this is a very basic pseudorandom number generator where you can define the minimum and maximum. 

### Usecases

Show Cue Systems - Looking to design a system to randomly select a track to play from a selection of tracks. The software doesn't do this natively, so having to create a semi-work-around in Companion with incrementing custom variables to move through different tracks. It works well enough, but is not totally "random" and loops through predictably.

**Comment by Julusian** [comment]
This is now in beta as `randomInt(min, max)`
