### ISSUE TITLE
[BUG] STREAM DECK not usable in V3.0

### ISSUE THREAD

**Issue by MOSDEV82** [bitfocus/companion#2526]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After connecting and rescanning it shows me this error in console log:
error Surface/Controller Found "elgato-streamdeck" device, but no access. Please quit any other applications using the device, and try again.
scanForLoupedeck false

There is no other application using this stream deck. I switched back to previous version - all is well...

### Environment (please complete the following information)

```markdown
- OS: Debian trixie/sid, Kernel 6.0.0-6-amd64
- Browser: Chromium
- Companion Version: 3.0+6049-stable
```

**Comment by Julusian** [comment]
3.0 needs different udev rules to 2.4, perhaps that wasnt done when you updated?
https://github.com/bitfocus/companion/blob/master/assets/linux/50-companion.rules

**Comment by MOSDEV82** [comment]
Ah thanks, now it is working fine!
