### ISSUE TITLE
[BUG] Ternary doesn't work in button text

### ISSUE THREAD

**Issue by BryanCrotaz** [bitfocus/companion#2527]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Button text: 
`($(internal:custom_countdown_hours) < 10) ? 0$(internal:custom_countdown_hours) : $(internal:custom_countdown_hours)`

Shows the expression text, not the evaluated value

### Steps To Reproduce

Add a custom variable `abc` with a value of 7
Add a button with text `($(internal:custom_countdown_hours) < 10) ? 0$(internal:custom_countdown_hours) : $(internal:custom_countdown_hours)`

### Expected Behavior

Should display `07`

### Environment (please complete the following information)

```markdown
- OS: Windows 10
- Browser: Chrome
- Companion Version: 3.99.0+6162
```

### Additional context

Using example from docs

**Comment by Julusian** [comment]
Have you clicked the button to make the text field be in expression mode? It showing the raw text suggests it is still in text mode

Unrelated to your issue, but there is a syntax error in your expression. `0$(internal:custom_countdown_hours)` won't evaluate. you should replace that with either `concat(0, $(internal:custom_countdown_hours))` or `` `0${$(internal:custom_countdown_hours)}` ``
