### ISSUE TITLE
Export Module Logs

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#2529]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

There needs to be an export log function for the Module logs, and the "Export Support Bundle" action should also export the module logs.

### Usecases

For troubleshooting modules.

**Comment by Julusian** [comment]
This won't be possible to do through the "Export Support Bundle", but in each of the module log pages there could be an export button to export the logs shown there.
These module logs are intentionally not cached/stored by the backend, to avoid the memory cost when they arent useful 99% of the time

**Comment by MeestorX** [comment]
Understood. If it could just export whatever is shown when the module log is open, that would be fine. i.e. no storage of the module log needed except when that module log page is open.
It's just that copy/paste from a web page doesn't work well.

**Comment by MeestorX** [comment]
And really, for developers, the regular log is the one that's not useful 99% of the time. :-)
