### ISSUE TITLE
Vmix shortcut recall

### ISSUE THREAD

**Issue by Guillemete** [bitfocus/companion#253]
**Describe the feature**
Recall shorcuts in Vmix. 

**Is this platform dependent (windows, mac, ..)?**

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along

**Usecases**
In vmix, you can create shortcuts to star/stop timer, advance PPT, change the timer countdwon "live", change an aux output. Would be handy to simply recall directly from the stream deck

**Comment by willosof** [comment]
This issue was moved to bitfocus/companion-module-studiocoast-vmix#1
