### ISSUE TITLE
Feeback on Buttons style change

### ISSUE THREAD

**Issue by digitalmomente** [bitfocus/companion#2539]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Remote triggering is a great way to control the companion from another Control surface than from a Stream Deck.
I love it!

What I'm missing is a way to get informed, when Buttons style has been changed.
For example if the Buttons gets a new color or text.

The concept could be the same as for the remote triggering. For example in OSC

`/style/bgcolor/<page>/<button> <red 0-255> <green 0-255> <blue 0-255>`

or

`/style/text/<page>/<button> <text>`

### Usecases

Imagine using the companion to control a Vision mixer.
The Mixer plugin provides feedback for the buttons and can change their color, for example, when a source is activated.

I don't control the Companion via a Stream Deck but from a separate Control surface using remote triggering.
That works great.

But I don't get any feedback on my separate Control surface if a source is active on the Vision mixer.
That's what I'm missing so much.

**Comment by dnmeid** [comment]
I think all this direct changes to buttons are a not the best concept and they are heavily misused for purposes they never had been made for. So it is natural that people lack some functionality with this concept of programming, just because it is not appropriate.
If your mixer connection does provide boolean feedback, you can use that feedback in triggers. If your mixer connection uses advanced feedback just to change background colors, you should ask at this connection to provide boolean feedbacks. Advanced feedbacks are only needed when you want to present text from device or draw images.

**Comment by Julusian** [comment]
> Remote triggering is a great way to control the companion from another Control surface than from a Stream Deck.

Have you considered the [Satellite API](https://github.com/bitfocus/companion/wiki/Satellite-API)? It is designed to handle this kind of feedback as a way of attaching surfaces remotely.

**Comment by digitalmomente** [comment]
Thank you Julian, I've looked at the Satelite API, but I'd really like to use my own interface.
Thank you Dorian, I understand your objection. 

For example, look at the feedback definition from an Atem mixer.
This feedback only controls the Stream Deck and changes the Background color of the Button.
Is there a way to share this feedback?
Perhaps with a general action that can be defined and triggered.
I'm not really want to do the same with my Button, but getting informed would be great.
For example with an OSC-Message as action.

<img width="505" alt="Screenshot 2023-08-02 at 15 58 44" src="https://github.com/bitfocus/companion/assets/34488506/cf5685da-4649-4f64-a1f3-f71081ae6f78">

**Comment by dnmeid** [comment]
<img width="503" alt="image" src="https://github.com/bitfocus/companion/assets/8548888/315b6c4d-dc41-414b-8e91-2bda7e380fd8">

**Comment by digitalmomente** [comment]
Oh wow! This is exactly what I was looking for. Maybe a bit hidden, but totally logical... after I got it. You guys are great and have a great product! This can close my request, because you have already implemented the function I was looking for.
Thank you for your support and the quick help.
