### ISSUE TITLE
Highlight a selection in Triggers / Connections

### ISSUE THREAD

**Issue by Fire739** [bitfocus/companion#2541]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Once you select a trigger or Connection it would be highlighted, So you have a quick visual that is the one you are working on. 

### Usecases

For me its all about the visual and identifying quickly that i am on the correct trigger or Connection 
![Companion](https://github.com/bitfocus/companion/assets/121846683/5486f372-83c5-4646-8015-b438704d9cd9)

**Comment by Julusian** [comment]
This is partially a duplicate of #2385, but also covers connections so I shall leave this open

**Comment by Julusian** [comment]
This will be in the beta builds shortly
