### ISSUE TITLE
[BUG] Time trigger value validation.

### ISSUE THREAD

**Issue by urbanvisuals** [bitfocus/companion#2544]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It's possible to enter odd values into the time field of a time based trigger. 

![COMPANION ](https://github.com/bitfocus/companion/assets/2680423/9756b4d8-4d9a-4c25-9b20-cb8e7eddb18d)

I was trying to set up a trigger to fire at 3am, but it doesn't seem to trigger. Upon further testing I realized you can enter many odd values into the time field.

### Expected Behavior

The time field should validate to a proper time base value such act 12:05am, or something like that.  Or have something in a help icon to tell you what the format needs to be in?  

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by urbanvisuals** [comment]
Should the triggers work with time of day? What is the format of the time value I should enter into the field in the UI?

**Comment by Julusian** [comment]
It is expecting the format `hh:mm:ss`. this is shown when the field is empty.

But it is supposed to be highlighting red when the value is invalid, and could be made into an interactive picker

**Comment by urbanvisuals** [comment]
Thanks,

I haven't been able to get it to trigger on any time value. I can trigger the action with the every x seconds event, and it tells me when it last was triggered, but any time value in the time of day doesn't work for me. For example, I was trying today with 12:48:00 and it would not trigger.

**Comment by Julusian** [comment]
Strange, I have just checked and it did fire just for me with `22:54:03`, so it looks like it is working.
Could this be a timezone issue? I think people have said that the time variables aren't in their local timezone, perhaps that is messing this up too?
