### ISSUE TITLE
'Invert' checkbox as default for all boolean feedback definitions

### ISSUE THREAD

**Issue by leonreucher** [bitfocus/companion#2547]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

For the modules I developed I added an option to invert the boolean value in all boolean feedback definitions. Probably it would be a nice idea, to implement this feature for all feedbacks which are boolean based?

![Bildschirmfoto 2023-08-10 um 23 35 59](https://github.com/bitfocus/companion/assets/19686873/f79ea121-aaa8-403d-bcba-d565f3542143)

### Usecases

Invert the logic for already designed buttons, without having the need to change the design.

**Comment by Julusian** [comment]
This is now in the beta builds. See #2549 for details on how it works, it has also been added to the module docs https://github.com/bitfocus/companion-module-base/wiki/Feedbacks#inverting-boolean-feedbacks
