### ISSUE TITLE
BUG: Importing should indicate progress

### ISSUE THREAD

**Issue by haakonnessjoen** [bitfocus/companion#255]
When importing, the gui should indicate whether it is done importing or not. Right now page imports are really turn-off. And full page imports "suddenly" reloads your browser, after a while. We must indicate that it is working, at least. Maybe even a progress bar, if the core developer is in the good mood.

**Comment by Julusian** [comment]
This doesnt show progress, but it does show a fullscreen message on every client.
I am calling this good enough
