### ISSUE TITLE
[BUG] Deleting trigger condition confirmation displays wrong

### ISSUE THREAD

**Issue by urbanvisuals** [bitfocus/companion#2550]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This seems pretty minor, but when deleting a condition on the Triggers page, the confirmation dialog that pops up says Delete Feedback. 

### Steps To Reproduce

Go to Triggers, 
Create a Condition
Hit the trash button to delete the condition.
The "Delete Feedback" dialog pops up

![deletefeedback](https://github.com/bitfocus/companion/assets/2680423/c7b21edd-a868-4bff-8463-027b346e73eb)

### Expected Behavior

I imagine this should say "Delete Condition" instead.

### Environment (please complete the following information)

```markdown
- OS: Mac Browser - Companion on Pi
- Browser: Safari
- Companion Version: 3.0.0
```

**Comment by Julusian** [comment]
This is fixed in beta and will be in the next release
