### ISSUE TITLE
[BUG] Not changing bind port

### ISSUE THREAD

**Issue by mrhhats** [bitfocus/companion#2552]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi there, installed latest stable and upgraded from 2.x - web port changed to 8000. I set it manually to 80 via the config.json file and restart it. No change as it still is listening on port 8000.

Windows 10 Pro is the host OS.

Before the upgrade I could run on port 80.

### Steps To Reproduce

1 upgrade from working 2.x version
2 change admin port to 80
3 view the port remains 8000

Doesn't matter what interface I make it listen to

<img width="1070" alt="image" src="https://github.com/bitfocus/companion/assets/111146190/5ffbb0e1-9300-4c87-a0a4-75716e147a63">

### Expected Behavior

If port 80 is defined in the config file, the web interface should load on that port.

### Environment (please complete the following information)

```markdown
- OS: Windows 10 pro
- Browser: Chrome latest
- Companion Version: 3.00 stable 6049
```

**Comment by Julusian** [comment]
It was never supposed to let you use a port below 1024, doing so is likely to run into permissions issues.
When the port configuration option was added, it was coded to reject those ports. You found a workaround by changing the config file directly, but this was never supposed to work. 
The change which introduced this limitation: changehttps://github.com/bitfocus/companion/commit/39abee9dac3aa127da50e2b28b182b2ad7f50e73#diff-e07d531ac040ce3f40e0ce632ac2a059d7cd60f20e61f78268ac3be015b3b28fR62

As this is behaving as originally intended, I am closing this as wont fix
