### ISSUE TITLE
add function "split" to variable expressions

### ISSUE THREAD

**Issue by Fred-DTV** [bitfocus/companion#2559]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I am receiving an array of numbers as a variable from obs and was trying to split them into single variables with the js split function, but the companion log says that this function is not yet implemented.

Would be great to see this added.

### Usecases

see above

**Comment by Julusian** [comment]
I'm not sure if the expression syntax currently allows for arrays at all. That will need to be verified/implemented at the same time as doing this

**Comment by Fred-DTV** [comment]
Thanks :)

**Comment by Julusian** [comment]
This is now possible in the betas

**Comment by Coupe70** [comment]
Sorry for trying it in this old post, but maybe I can reach out to the experts here...
I have a hard time finding out how to use arrays in Companion as there is no documentation or example.
I know how to use 'split' in a programming language, but when I try split("one#two#three", "#") in Companion 
my custom variable just contains the string "one,two,three" afterwards. So yes, it splits, but I don't get an array
to access the single elements.
How do I set up an array in Companion (and split to it) and how do I access an element of an array afterwards?
Probably the latter will work as I would expect as soon as I have a proper array...
