### ISSUE TITLE
Allow all interfaces in 'yarn dev' mode

### ISSUE THREAD

**Issue by istnv** [bitfocus/companion#2563]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Change the `--admin-interface` option in `package.json` to `0.0.0.0` or allow the address to be set via an environment variable.

### Usecases

 I do some of my development remotely, and need to adjust the primary `package.json` file to change the `--admin-interface` to `0.0.0.0` so I can access the GUI. Whenever I update from the git repository, I have to stash and re-apply this change.

**Comment by Julusian** [comment]
I've reshuffled things a bit, so that the `yarn dev:inner` command doesn't set `--admin-address 127.0.0.1`, allowing you to specfiy it yourself. Feel free to open a pr which adds another `yarn dev:something` command to be a preset of what you need, the existing ones were based upon my needs
