### ISSUE TITLE
[BUG] Trigger incorrectly firing 

### ISSUE THREAD

**Issue by TPaulManohar** [bitfocus/companion#2566]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When we enable the trigger, it starts the actions are working as excepted. When we disable the trigger we noticed that this trigger will occasionally fires the buttons in unwired format.

**How our trigger works**
Events - On any Button Press
Actions - internal: button: Trigger Press

I'm not sure where we can get the triggers logs.

### Steps To Reproduce

Unclear. Seems to happen randomly.

### Expected Behavior

Actions should not fire when the trigger has disabled.

### Environment (please complete the following information)

```markdown
- OS: Windows 10
- Browser: Microsoft Edge Version 116.0.1938.69 (Official build) (64-bit)
- Companion Version:  3.0.1 (3.0.1+6068-stable-a05a9c89)
```

### Additional context

Trigger also fires multiple time even the trigger has enable. For that reason Reaper is going to stop the sequence.

**Comment by Julusian** [comment]
Could you try and figure out a STR?
I have tried to reproduce this but have been unsuccessful. I can't see how this could be happening in the code, so without a STR this is a bit stuck

**Comment by Julusian** [comment]
This is lacking information necessary to investigate further
