### ISSUE TITLE
[BUG]Surface not being detected

### ISSUE THREAD

**Issue by satonosuke22** [bitfocus/companion#2567]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

streamdeck device is not detected. I have tried opening the streamdeck controller from Elgato, and here it was responsive. I then killed the Elgato app, and opened the Companion app, and still didnt find my device. The device is however detected by the computer. I did also try scanning the USB ports.

### Environment (please complete the following information)

```markdown
- OS:MAC OS Ventura 13.5.1
- Browser:safari 16.6
- Companion Version: 3.0.1
```

**Comment by Julusian** [comment]
What type of stremdeck is it?
What is the usb product id reported in system information?

**Comment by satonosuke22** [comment]
> What type of stremdeck is it?
Strem Deck 2

> What is the usb product id reported in system information?
0x0fd9  (Elgato Systems GmbH)

**Comment by satonosuke22** [comment]
When I have streamdeck open and open up bitfocus the buttons from bitfocus will show up but they won’t register any presses. I check surfaces in bitfocus and it looks like it doesn’t see the streamdeck only “Elgato emulator” and “Elgato plug-in.” So I close the streamdeck app and rescan USB’s and the streamdeck now shows up. However if I open up the streamdeck app the streamdeck now doesn’t show up on the configuration app it says “no device registered” so I can’t load in any profiles.

**Comment by satonosuke22** [comment]
This issue is resolved
It was a mistake in the initial GUI settings.
