### ISSUE TITLE
Progress Bar/Volume Indicator

### ISSUE THREAD

**Issue by joshnortheimer** [bitfocus/companion#2572]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I'd love to see a progress bar feedback function, which could be accomplished one of three ways:

1) a feedback that progressively changes the background color, left to right, based on a variable, a minimum, and a maximum. so, if the minimum is entered as '0', and the maximum is entered as '100', and the variable value is currently 33, the left third of the background color layer changes color, based on a color selector in the feedback.
![progress-bar-provided](https://github.com/bitfocus/companion/assets/42381830/7768b638-cdb5-4790-9405-9302559ad675)
 then, we can use a PNG file as a foreground layer to stylize the progress bar.
![demo](https://github.com/bitfocus/companion/assets/42381830/e47ecfa2-dc2d-4201-be70-85d68942989c)

![companion progress bar](https://github.com/bitfocus/companion/assets/42381830/e5f215a9-f3bb-4a7f-a21b-e4ea20d35c15)

2) a feedback that allows loading of a series of PNG files, and asks for a variable. if the value of the variable is '10', for example, then the feedback will load 10.png to display on the button. there could also be a field for <,>,=, for when to change the image.

3) a custom progress bar button type built in to companion that asks for variable to track, min, and max, and draws a predefined progress bar on the button, with little to no customization options.
![companion progress button](https://github.com/bitfocus/companion/assets/42381830/09fe3d3b-131d-4704-accc-25c4b4c476d5)

I'd prefer option 1, as it's less effort for the end user, but I'm sure it's more work on the back end creating the feature.

### Usecases

use cases would be

1) displaying fader level when mixing audio, in a sound mixer module, or audio levels on a switcher. (linking the tracked value to a variable in an external instance)
2) displaying a progress bar (IE time played vs total time in clip for VLC, Hyperdeck, ProPresenter, etc.)

**Comment by dnmeid** [comment]
This request is already part of the graphics overhaul project https://github.com/orgs/bitfocus/projects/4/views/1
I close it because of duplicate
