### ISSUE TITLE
Issue Connecting Companion to a new port[BUG]

### ISSUE THREAD

**Issue by PlutoniumVoid** [bitfocus/companion#2574]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi, I have started having an issue with the companion app and vmix.
The app tells me it has connected like normal to vmix, however when I try to send an input to it through the stream deck I get a 
"instance(vmix): Function socket err: connect ECONNREFUSED 172.25.27.9:8099." error, and the button doesn't work.

![Capturar](https://github.com/bitfocus/companion/assets/102997597/9fcb307e-9027-44bc-822e-2cc8430b952d)
[logbitcompanion.txt](https://github.com/bitfocus/companion/files/12595579/logbitcompanion.txt)

### Environment (please complete the following information)

```markdown
- Windows 10 Version 22H2:
- Chrome:
--3.0.1+6068-stable-a05a9c89:


### Additional context

_No response_

**Comment by Julusian** [comment]
the module needs to be connected to the TCP port not the web api.
Disable the web api and try again. You will get better help for this on the facebook group or slack
