### ISSUE TITLE
support variables in internal shell action

### ISSUE THREAD

**Issue by MauriceD1999** [bitfocus/companion#2578]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Hi there,

I am currently trying to run a PS script from within companion and use an internal companion variable in this script. I tried setting the variable within the path of the “run shell path (local)” action, but had no luck so far:

Variant 1: with a variable within the path

PowerShell $triggertime = 'XX'; C:\script.ps1 works,
PowerShell $triggertime = $(internal:custom_triggertime); C:\script.ps1 does not work

Variant 2: with a parameter within the path

PowerShell -File “C:\script.ps1” -customVariable [XX] works,
PowerShell -File “C:\script.ps1” -customVariable [$(internal:custom_triggertime)] does not work

--> The variable is used to calculate a pause time within the script and I would like to set this time in companion

Is it currently possible/would it be possible to implement the use of internal variables in the shell path (e.g., for defining a variable in the shell?)

thank you very much for reading and maybe for leaving a suggestion!

### Usecases

powershell scripts
run shell path (local)
use internal variables system wide

**Comment by Julusian** [comment]
variables are supported here already

**Comment by Gabe-LS** [comment]
This is the only way I found to use a variable with two values in it in a shell command.

1. set a temp variable to the value I want to use
2. use the temp value with the shell comand

<img width="1540" height="1008" alt="Image" src="https://github.com/user-attachments/assets/e96cc959-fd99-49a6-b635-c7c8f8551056" />
