### ISSUE TITLE
BUG: Import should handle existing instances better

### ISSUE THREAD

**Issue by haakonnessjoen** [bitfocus/companion#258]
This is two bugs.

## Bug one

If you add a single page from a full page import and select to create a new instance for the required instance. The instance dropdown is not updated for the next import, if you plan on importing more pages. This would lead in a lot of duplicate instances.

## Bug two

If the ID of the instance is not 100% the same, it will not recognize the same configuration of an existing instance. It should compare instance configuration, and automatically suggest the equally configured instance.

**Comment by Julusian** [comment]
This has been done in develop as part of a large fixup and overhaul of some of the importing logic and flow
