### ISSUE TITLE
Add "Duplicate Step" button

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion#2584]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Sometimes I have long sequences of Actions within a Step. However, I then need to make an almost identical sequence from scratch for each step. 

Actions can be easily duplicated, but Steps cannot. 

Requesting the ability to be able to duplicate a Step. This would create a duplicate of the Actions contained with the current step.

Thanks!

<img width="655" alt="Screenshot 2023-09-20 at 7 43 58 PM" src="https://github.com/bitfocus/companion/assets/76959770/96a51dcc-7a01-47ae-b9fc-38ecc903c145">

**Comment by andik2000** [comment]
I reale would love to see this feature. If you have a complex action set, it is very frustrating to add all actions for every step just for changing one parameter. Also a big risk for doing errors in your set.

**Comment by Julusian** [comment]
Question is, where should that button go when there is only one step?

**Comment by davidjoshuaford** [comment]
A few suggestions -

For placement, either add a new tab alongside the "+ Add step" tab that says "+ Duplicate step":

<img width="640" alt="Screenshot 2024-09-08 at 7 40 16 PM" src="https://github.com/user-attachments/assets/d0ff763a-e3ce-4cd2-98a3-2181751476dc">

Or preferably, remove the "+ Add step" tab completely, and add the "Duplicate" and "Add" symbols at the end of the row in keeping with the style of the actions like so: 

![Screenshot 2024-09-08 at 7 42 26 PM (1)](https://github.com/user-attachments/assets/053084b4-40c9-4e1a-9312-33f989fc63db)

This would have the added benefit of avoiding accidentally pressing "+ Add step" when trying to select the Feedback tab instead. 

Also, I suggest that when the Step is duplicated, place the duplicate at the end of all the existing steps, and not directly adjacent. This will prevent buttons with many existing steps getting out of sequence. 

Perhaps the duplicated step could even be automatically custom named "1 Copy", and if duplicated more times, "1 Copy 2" etc. Open to feedback on that.

**Comment by ukiews** [comment]
2nd option seems best

**Comment by davidjoshuaford** [comment]
Thanks @Julusian – looking good, just a note that the duplicate icon doesn't appear to work when there's only 1 step, but the duplicate icon works when there's multiple steps. 

The Add Step icon works for both the first step and multiple steps.
