### ISSUE TITLE
[BUG] Companion Crash at sunrise/sunset trigger event

### ISSUE THREAD

**Issue by arenard-pixap** [bitfocus/companion#2585]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The application crashes when a sunrise or sunset event is triggered.
The application then restarts automatically so I can not find any logs.
I've tried different types of action, but the bug remains the same, and when I test the action of this trigger, everything works fine.
Even if you don't set any action, the bug occurs.
The bug remains the same with positive or negative offset (I can't test without any offset).

I've tried on all Companion versions since 3.0.0 and I find the same bug on all of them.
I tried with a PC running Windows 11 and a MacBook running MacOS Ventura 13.5.2 and the problem occurs on both systems.

<img width="1800" alt="Capture d’écran 2023-09-21 à 12 08 12" src="https://github.com/bitfocus/companion/assets/69593707/38646912-a4be-4eae-b357-35934ecf6d9b">

### Steps To Reproduce

1. Go to Triggers tab
2. Create a new trigger
3. Add an "On Sunrise/Sunset" event
4. Set your location by filling in the latitude and longitude
5. Set this event in order it will be fired in the next minute using the offset
6. Wait until the event will be fired

<img width="1534" alt="Capture d’écran 2023-09-21 à 12 27 33" src="https://github.com/bitfocus/companion/assets/69593707/bb202074-22c5-4cc9-8578-9ea58b18c2b7">

<img width="1532" alt="Capture d’écran 2023-09-21 à 12 36 44" src="https://github.com/bitfocus/companion/assets/69593707/6b357317-48b2-4cab-bc5a-159d8147f5f4">

### Expected Behavior

The trigger might be activate without any crash

### Environment (please complete the following information)

```markdown
- OS: Windows 11 and MacOS Ventura 13.5.2
- Browser: Google Chrome
- Companion Version: 3.0.1+6068-stable-a05a9c89
```

**Comment by Julusian** [comment]
Thanks for reporting this. It is fixed in beta 6205

**Comment by arenard-pixap** [comment]
Thanks Julusian !
