### ISSUE TITLE
[Request] Ability to edit action "headline" to make custom notes

### ISSUE THREAD

**Issue by Coupe70** [bitfocus/companion#2587]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

In native Streamdeck software I can label actions, but I can't find a way to do this in Companion. I have a lot of non-preset actions (or whatever, the attached picture is just an example), but they only show me the module & function in the "headline" and I can't change this to a note what exactly is happening inside. Even when I extend the action I only see my cryptic http calls (like 127.0.0.1:8088/API/?Function=SetText&Input=877bb3e7-58bd-46a1-85ce-0d673aec6bf5&SelectedName=Headline&Value=Hello) which is not very convenient to keep track of what's happening. Maybe I'm missing something as this seems to be such an essential feature.
What I see now:
![grafik](https://github.com/bitfocus/companion/assets/70244400/7ea45aa3-7cfb-41e6-ae21-752f0a4c6632)
Example of what I would like to see after editing the headlines 
![grafik](https://github.com/bitfocus/companion/assets/70244400/e18ded34-a98e-4aee-b93c-e3140d225eee)
I wouldn't mind if the dialed in delay was shown automatically, too, but I could also just type it in to have it in the headline.
The name of the module and the selected function is still important and should a) be the default content of the headline when creating an action and b) even after editing the headline always be shown when extending an action:
![grafik](https://github.com/bitfocus/companion/assets/70244400/ab305a2b-fe0d-43ac-834d-213ed476bed0)

### Usecases

- Keeping track of actions, events, conditions.
- Keeping up with native Streamdeck software ;-)

**Comment by Julusian** [comment]
This would be pretty quick to do, but the thing blocking me is figuring out where to put the text edit field.

I would like for this field to be a multiline field, as others are asking for the ability to write longer notes on buttons and their actions.  So it feels like it would make sense to have a multiline field, but to only show the first line in the collapsed view.

I think it will want to be wider than the delay field, so I don't think it can go over there, but I dont want to add it above and make the whole block taller.  
Perhaps it could be put where the `http: GET` is in that screenshot, with a drag handle to make it taller?

Or, it could be done as 2 fields. A single line 'headline' field where `http: GET` is (pushing that downwards to be above the delay field). With a multiline 'notes' block below the delay.

**Comment by RickDDD** [comment]
Personally I would already be happy if the "http GET" (what I call the headline) would be editable. I could keep "http GET" if it is important to me and add notes, or just erase it to have more room for other notes. 
Actually this headline already provides room for 2 lines of notes as you can see in the "internal" action - if the content is too long for one line, it becomes a 2-line-headline.
Additional room for notes in the maximized view of the action might be useful here and there, my absolute priority would be to change the headline to something more informative when the action is minimized.

**Comment by Julusian** [comment]
I've made a start on this, but I need some help figuring out how it should look. Any input on this would be appreciated, I feel a bit stuck currently

Collapsed is fine:
![image](https://github.com/bitfocus/companion/assets/1327476/5db421c3-abe8-4458-a887-8a5c4fc1e528)
![image](https://github.com/bitfocus/companion/assets/1327476/21be0693-a1f9-4a6e-9130-65b3c54fb4e2)

I think this is ok, when a headline is set. But I am worried that the type of action is being a bit squished. 
![image](https://github.com/bitfocus/companion/assets/1327476/09bf3ce6-8ddf-4dab-9246-23ab4ca11bfc)

But I don't like the repetition here
![image](https://github.com/bitfocus/companion/assets/1327476/afd2b431-011e-4c68-91ef-91b000cf37db)
Or the empty field here
![image](https://github.com/bitfocus/companion/assets/1327476/c65f97e8-f063-44ae-91e5-4eb1571d5a8b)

I suppose there is also no description of what the field is for, should the empty state show that?
![image](https://github.com/bitfocus/companion/assets/1327476/6dffb291-ad2b-44d1-91d6-6928dc623d03)

When the action has a description as well as a name (both come from the action definition, not user fields) looks fine too: 
![image](https://github.com/bitfocus/companion/assets/1327476/65cce6c0-ad02-4a3b-be14-d9ef6be323f4)

**Comment by dnmeid** [comment]
What about the following suggestion: using the original item name with the existing layout at first, but with a little edit toggle icon. If you toggle edit on, you'll get the multiline edit, if you toggle it off you see only the first line.
If the user changes the first line, it will be like renaming. When he wants to just write notes to an action he can do in the following lines. It's up to the user to leave the multiline open or not and we should store this. The original name of the item doesn't need to be shown elsewhere. It's up to the user to keep it or to overwrite it. We can implement that the edit will automatically fall back to the default name when cleared completely, same logic like the page names.

**Comment by Coupe70** [comment]
@Julusian Thank you so much for working on this!

First of all I would go with @dnmeid on this:

> We can implement that the edit will automatically fall back to the default name when cleared completely, same logic like the page names.

This would solve the "what to do with an empty state?" and when the default name is back in the text box, it does not have to be shown below - so no repetition.

**Comment by Julusian** [comment]
I'm not keen on not showing the original name of the action/feedback. I expect that will add friction for users who want to know what name they should search for to add the same action to another button.

Additionally, we do show the 'description' from actions/feedbacks on the left below the name currently (many actions/feedbacks havent defined one). A better example than the action I was using earlier is:
![image](https://github.com/bitfocus/companion/assets/1327476/cf8a00b8-dfe4-4ff6-8cfd-79581626d8a4)

Showing that description without the name feels weird, and I think will be confusing as the description may not fully make sense without the name.

Maybe an edit pencil would help here though? Toggle on editable name mode to swap out the fixed name for an editable field and the ui will move the original name. Then drag the input box to be taller to turn it into more notes.  
Delete everything from the input field and it will switch back to default name mode, and go back to the current layout

**Comment by Coupe70** [comment]
I'm not sure if this is a misunderstanding. I'll try to explain.

So this is the normal state like you posted it
(original name in the headline, description in the expanded view):

![284058387-cf8a00b8-dfe4-4ff6-8cfd-79581626d8a4](https://github.com/bitfocus/companion/assets/70244400/57ea50ac-7200-439b-8f4e-0653f17f6d32)

If you edit the headline the original name will still be there, but it moves down into the expanded view, above the description:

![grafik](https://github.com/bitfocus/companion/assets/70244400/509cf30b-2d0b-4454-85aa-d7e70e2fabcf)

If you decide to erase your custom text from the headline, the original name will move up to the headline again and will be visible in the collapsed view like before.

**Comment by Julusian** [comment]
@Coupe70 yes that is what I am thinking

**Comment by Julusian** [comment]
This is now in the betas
