### ISSUE TITLE
[BUG] Docker:latest

### ISSUE THREAD

**Issue by Serph91P** [bitfocus/companion#2599]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Like it says in the initial description of the bug report I should pull the latest release. But using the latest tag with docker pulls version 2.4 and not 3.x. Any reason that you have to use a specific tag to get the latest version?

### Steps To Reproduce

install docker from ghcr.io/bitfocus/companion/companion
with latest tag

### Expected Behavior

the latest docker gets pulled and not an old version

### Environment (please complete the following information)

```markdown
- OS: Docker
- Browser: Firefox
- Companion Version: 2.x eg 3.x
```

**Comment by Julusian** [comment]
I have updated the latest tag manually now.

Hopefully I have also fixed the build process to automatically update it for the next release. Please do let me know if it doesnt update automatically again

**Comment by ukiews** [comment]
@Julusian Is there a reason the tag has changed to 'main' with the _latest_ image?
https://github.com/bitfocus/companion/pkgs/container/companion%2Fcompanion/807628169?tag=4.3.0-9193-main-61afe1a684

**Comment by Julusian** [comment]
main is pointing to the beta builds.
it does appear that 4.3.0 docker image failed to build though, which is why latest hasnt updated

**Comment by Julusian** [comment]
@ukiews image is tagged now

[latest](https://github.com/orgs/bitfocus/packages/container/companion%2Fcompanion/810043308?tag=latest)
[4.3.0-9183-stable-d468191b7b](https://github.com/orgs/bitfocus/packages/container/companion%2Fcompanion/810043308?tag=4.3.0-9183-stable-d468191b7b)
[v4.3.0](https://github.com/orgs/bitfocus/packages/container/companion%2Fcompanion/810043308?tag=v4.3.0)
