### ISSUE TITLE
[BUG] Module Logs not showing Info & Debug Messages

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#2600]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In version 3.2.0+6244-beta, module logs aren't showing Info & Debug messages. Console messages ARE being shown, don't know if Warning and Errors are or not as I don't have any of those errors ATM.

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version: 3.2.0+6244-beta
```

**Comment by Julusian** [comment]
Hopefully 6246 is better

**Comment by MeestorX** [comment]
Standing by to test.

**Comment by MeestorX** [comment]
Fixed!
