### ISSUE TITLE
[BUG] subscribeActions() broken

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#2601]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Somewhere around 3.2.0+6247, subscribeActions() stopped working.

### Expected Behavior

Works in 6246

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version: 3.2.0+6247 (or 6248 maybe)
```

**Comment by MeestorX** [comment]
Seems to be working again in 6249.

**Comment by Julusian** [comment]
Nothing has changed (other than some modules) since 6247 where you suspect it was introduced.
Could this be a race condition and so it only happens sometimes, or error in your testing?

![image](https://github.com/bitfocus/companion/assets/1327476/4294345b-0f9d-4734-b8bf-b61cb91b4c11)

**Comment by MeestorX** [comment]
Very possibly. Weirdly, I was seeing the subscriptions not being called, went back to a previous version and it worked, ran the later version and didn't, so I figured something had to have changed. Must have just been coincidental!
