### ISSUE TITLE
[BUG] X-keys feedback colours not working

### ISSUE THREAD

**Issue by BenJamesAndo** [bitfocus/companion#2602]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In version `3.0.1 stable` of Companion setting a feedback Background colour of either red or blue would cause the corresponding button LED to light up. In my case I have a XK-8 Stick so it would only ever be blue as red is not supported in this model.
Now in version `3.1.1 stable` no feedback LED's light up, despite having the exact same settings. The XK-8 still works, including the `Illuminate pressed buttons` settings such that when I tap the button the LED briefly flashes. I've tested on `3.2.0 6249 beta` and the bug persists of no feedback LED.

Looking at the logs in `3.0.1 stable`  I get `Surface/USB/xkeys/xkeys:1130-1: device added successfully` but in `3.1.1 stable` I get `Surface/USB/xkeys/xkeys:1130-1: uncaughtException: TypeError: this.ipcWrapper.xkeysSubscribePages is not a function` After that's there's no more logs about xkeys. But in `3.0.1 stable` it continues with logs such as `Surface/USB/xkeys/xkeys:1130-1: graphics_set_bank_bg received in xkeys 0, 0, r:0, b:0`

### Environment (please complete the following information)

```markdown
- OS: Windows 11
- Browser: Chrome 117
- Companion Version: 3.1.1 stable
```

**Comment by Julusian** [comment]
This is fixed in beta 6151 and will be in v3.1.2 when that gets released
