### ISSUE TITLE
Add Custom Names to Step Tabs

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion#2605]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I have some buttons that have many Steps – it is difficult to recall the sequence of events when they are just numbered.

It would be helpful to be able to add a custom name to each tab number so that parameters that have been built in the past are easy to understand when you come back to the button later on. 

Bonus if these custom names were searchable and could be referenced/ triggered. 

<img width="443" alt="Screenshot 2023-10-15 at 11 59 54 AM" src="https://github.com/bitfocus/companion/assets/76959770/535abeee-689f-40b0-8c0a-15f1cf2d64f7">

**Comment by Stagge** [comment]
Hi,

We are a group of 5 students at KTH whom would like to solve this issue as part of a course in Software Engineering!

@Pqformeln @FelixSjogren @Stagge @isadorawinter @BDidace
