### ISSUE TITLE
[BUG] [MINOR] [area/gui] Required resolution for PNG under Button Feedback doesn't update to larger size

### ISSUE THREAD

**Issue by leo-nightfever** [bitfocus/companion#2606]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The normal PNG "Upload"-button shows the correct required resolution between 72x58px and 72x72px. The "Upload"-button under Feedbacks doesn't.

**Correct:**
![image](https://github.com/bitfocus/companion/assets/136072322/e3c887ee-6b4d-4510-95fd-8c6688b3f22b)

**Incorrect:**
![image](https://github.com/bitfocus/companion/assets/136072322/ac46d1a2-1f77-4773-8be3-63053b6dfca1)

### Steps To Reproduce

1. Add a button
2. Set its _Topbar_-property to "Hidden"
3. Create a feedback for it
4. Add "PNG" under _Change style properties_
5. Observer the issue

### Environment (please complete the following information)

```markdown
- OS:Win10
- Browser:Firefox 118.0.2
- Companion Version:3.99.0+6414
```

**Comment by Julusian** [comment]
These numbers aren't very relevant anymore with the new drawing, so I have removed them which avoids them being incorrect like this.
In beta 6503
