### ISSUE TITLE
[BUG] HTTPS Web Server Does Not Start on Stored Port Number When Launching Companion

### ISSUE THREAD

**Issue by nriebesehl-pega** [bitfocus/companion#2610]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

We have the HTTP Web Server enabled and the HTTPS Port setting set to 8990 instead of the default of 8443. This value is correctly stored in the configuration, but when launching or re-launching Companion, the HTTPS Web Server reverts back to binding to port 8443, requiring us to change it back each time we launch Companion.

### Steps To Reproduce

1. Enable the HTTPS Web Server setting and enter a port number 8990 and not 8443 into the HTTPS Port field. Specify certificate files.
3. Navigate to https://<hostname>:8990 in a browser and verify the Companion page loads.
4. Quit Companion
5. Relaunch Companion.
6. Navigate to https://<hostname>:8990 and observe page timeout
7. Navigate to the management interface on the server at https://<hostname>:8000 and adjust the HTTPS Port value back to 8990
8. Confirm Companion now loads at https://<hostname>:8990

### Expected Behavior

We expect to be able to set the HTTPS Port value in the settings, and after closing/opening Companion, navigate directly to https://<hostname>:8990 and see the HTTPS server is binding to the specified port.

### Environment (please complete the following information)

```markdown
- OS: Windows 11
- Browser: 117.0.5938.63
- Companion Version: 3.1.1+6229-stable-4593dd7f
```

**Comment by Julusian** [comment]
This looks to have been broken for a while, perhaps as far back as 3.0.0

This is fixed in the betas, and will be in a 3.1.2 release when that is done
