### ISSUE TITLE
[BUG] PNG is no longer resized in Companion v3.2.0+6432

### ISSUE THREAD

**Issue by LikeThisReview** [bitfocus/companion#2617]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I add a PNG (288x288) to a button it is no longer scaled in  in Companion v3.2.0+6432

### Steps To Reproduce

1. Create an icon which is larger than 72x72 (I use 288x288 as exported from Stream Deck icon tool); Save as PNG
2. Import the PNG as the default PNG for a text box
3. You will notice that only a small part of the PNG is displayed on the button

### Expected Behavior

Ico is scaled to 72x72 (as before)

### Environment (please complete the following information)

```markdown
- OS:Mac
- Browser: Safari
- Companion Version: v3.2.0+6432
```

### Additional context

-

**Comment by Julusian** [comment]
3.0:
![image](https://github.com/bitfocus/companion/assets/1327476/c72f2e53-c9e8-417b-a4a6-b4872c55fc3b)

beta:
![image](https://github.com/bitfocus/companion/assets/1327476/c2ee3178-ac73-4405-a59f-c03740562c88)

**Comment by Julusian** [comment]
Its not 100% the same, but is close enough and I would argue is more correct than before:
![image](https://github.com/bitfocus/companion/assets/1327476/05f82c42-9f44-43f2-8529-6516ce175801)

The one difference is that there used to be an inconsistency in the scaling. If an image was square or wider than it was tall, it would not be scaled down to make it visible beneath the top bar. But if the image was taller than it was wide, then it would be.  
best demonstrated by this:
![image](https://github.com/bitfocus/companion/assets/1327476/2f536853-0ef3-484b-bf06-854c19913cf8)

which now does:
![image](https://github.com/bitfocus/companion/assets/1327476/f0599309-42ea-4e85-8e87-d72d21bbe636)

**Comment by LikeThisReview** [comment]
Julian, Thanks for the swift update. Adding a new 288x288 icon is now OK,
however the existing icons are all blown up. Hope you can fix that.
Regards, Nico Wasmus (LikeThisReview)

[image: existing icons are incorrect.png]

Op ma 23 okt 2023 om 00:00 schreef Julian Waller ***@***.***>:

**Comment by LikeThisReview** [comment]
Julian, All existing 288x288 icons are OK, it is only the smaller existing
icons I have (for my dials) which are resized now. I have 288 × 99 pixels
icons. When I add it as a new PNG it is OK, only issue with existing ones.
Regards, Nico

 [image: image.png]


Op ma 23 okt 2023 om 12:33 schreef Nico Wasmus ***@***.***>:

**Comment by Julusian** [comment]
Attaching images doesn't seem to work via email.

Could you try again and possibly provide a page export I can use to test with?

**Comment by LikeThisReview** [comment]
Julian, Retest in 3.2.0+6436 is unsuccessful (existing 288x99 PNGs are not
scaled correctly). See attached exported page (uncompressed).

Thanks.

Op ma 23 okt 2023 om 12:49 schreef Julian Waller ***@***.***>:

**Comment by Julusian** [comment]
Your attachment hasnt come through, it looks like they also don't work from
email

**Comment by LikeThisReview** [comment]
[Nicos-Mac-Studio.local_pag
![NW icon 6b Dark Grey](https:/
![icon NW dial Reel-Scene-Take 1a](https://github.com/bitfocus/companion/assets/112906760/54282684-b340-4854-aad1-0de19cf35f83)
/github.com/bitfocus/companion/assets/112906760/7af94301-f7b6-44a2-9bb9-c9a8344fe621)
e42_20231024-1011.companionconfig.zip](https://github.com/bitfocus/co
![NW icon 7 BLACK](https://github.com/bitfocus/companion/assets/112906760/23b58834-94cf-4156-a230-b231f829f8eb)
mpanion/files/13113393/Nicos-Mac-Studio.local_page42_20231024-1011.companionconfig.zip)

**Comment by Julusian** [comment]
ah ok, it was a problem with the maths for very small images.
6437 is fixed

![image](https://github.com/bitfocus/companion/assets/1327476/0261247d-e0f3-4d60-9fd3-796a0f8e194e)

**Comment by LikeThisReview** [comment]
Yes, it is fixed (test in 6438). Many thanks!

Op di 24 okt 2023 om 19:26 schreef Julian Waller ***@***.***>:
