### ISSUE TITLE
Change Action Learn button timeout

### ISSUE THREAD

**Issue by leonreucher** [bitfocus/companion#2619]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

At the moment there is a fixed timeout defined for the "Learn" button on actions. It would be great if this limit could be either set higher, or the actions could define a timeout value by their self for the "Learn" functionality. 

### Usecases

I am developing a module for the BroadLink RM4 Pro, which is a device which can learn and send out RF codes. The learning process takes around 20 seconds. Atm I need to user another action only for learning RF commands - it would be nice, if there would be a solution for the short timeout, so I can remove the second function and use the native "Learn" button inside the "Send RF Command" action.

**Comment by dnmeid** [comment]
Haven't looked at the learn code recently but I think there is no timeout defined from core or the base module. You can decide what the learn button does in the callback. If there are timeouts, then it it is likely somewhere else, maybe in node. I use learn in the AWJ module so that you first have to do your operation and then push the learn button and it will immediately reflect the last operation.

**Comment by leonreucher** [comment]
"currently that is a hardcoded timeout, so if it takes over I think 5s it will fail.
It was written assuming the learning would be from known state and would be instant, but it probably could be adapted to allow for longer timeouts, and provide some kind of 'locking' (so that the user clicking the button 5 times during that 10s wait doesnt start it running again and again)" from @Julusian

**Comment by Julusian** [comment]
This is implemented and will be possible once https://github.com/bitfocus/companion-module-base/pull/66 is released

**Comment by Julusian** [comment]
This is supported in the next beta build

**Comment by mrhhats** [comment]
Hi all, just wanted to ask about getting this module for my RM4? I try to access the page on bitfocus and it errors out.

Running latest bitfocus companion right now - 3.2.2 stable.

Can anyone help please?!

<img width="1189" alt="image" src="https://github.com/bitfocus/companion/assets/111146190/fcadd7b2-9f0a-4087-8458-1a691544d52f">


<img width="1189" alt="image" src="https://github.com/bitfocus/companion/assets/111146190/0dd909c4-ccd0-41d2-855a-c350224eeb93">

**Comment by leonreucher** [comment]
The module is not yet included in the latest release. Please download the latest beta version of Companion to use the module. @mrhhats

**Comment by Julusian** [comment]
@leonreucher That issue with the website is because in some places the module is called `broadlink-remote` and in others it is called `broadlink-rm4pro`. It would be a good idea to unify those to avoid issues such as this

**Comment by mrhhats** [comment]
Thank you both for replying! @leonreucher  so we are talking about beta 3.3.0?

**Comment by leonreucher** [comment]
@Julusian thanks for the hint - I will make the required changes once I find some spare time.

**Comment by leonreucher** [comment]
> Thank you both for replying! @leonreucher so we are talking about beta 3.3.0?

Yes, exactly.

**Comment by mrhhats** [comment]
Hi again, was wondering if anyone had any updates? latest beta build and still getting Connection Failure
No device found
