### ISSUE TITLE
[BUG] After updating Bitfocus doesn't start

### ISSUE THREAD

**Issue by sharadagg** [bitfocus/companion#2623]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I updated to the latest 3.1.1 after seeing the message that a stable version is available. After that am unable to start.
1. First it gives an error another version of companion was recently run and the config changes I made there will not be available.
2. On clicking continue it still anywat gives an error and fails to start.

Downgraded to 3.1.0 - same issue

![image](https://github.com/bitfocus/companion/assets/81471321/0f3b37b9-6d65-4ad2-bea0-401a8a596af8)

I am on Windows server datacenter 2019 edition.

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by sharadagg** [comment]
Here is the screenshot of the 1st error I get after downgrading. Second error is the same as before
![image](https://github.com/bitfocus/companion/assets/81471321/3603bd3f-a66c-4ae8-a29f-4730cd888a9f)

**Comment by ksiwak7** [comment]
> ### Is this a bug in companion itself or a module?
> * [x]  I believe this to be a bug in companion
> 
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> I updated to the latest 3.1.1 after seeing the message that a stable version is available. After that am unable to start.
> 
> 1. First it gives an error another version of companion was recently run and the config changes I made there will not be available.
> 2. On clicking continue it still anywat gives an error and fails to start.
> 
> Downgraded to 3.1.0 - same issue
> 
> ![image](https://user-images.githubusercontent.com/81471321/278414966-0f3b37b9-6d65-4ad2-bea0-401a8a596af8.png)
> 
> I am on Windows server datacenter 2019 edition.
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Expected Behavior
> _No response_
> 
> ### Environment (please complete the following information)
> ```
> - OS:
> - Browser:
> - Companion Version:
> ```
> 
> ### Additional context
> _No response_

I had the same problem! Here is how I fixed it - 

Step 1 - Open folder and type into the search C:\Users\ksiwa\AppData\Roaming\companion
Step 2 - Locate Folder (v3.1) and Delete it. 

After that I was able launch Companion and it will remake the v3.1 file afterwards to replace the one you deleted.

**Comment by Julusian** [comment]
There is already a fix being worked on for this, and it will be fixed in 3.1.2

**Comment by krocheck** [comment]
v3.1.2 is published
