### ISSUE TITLE
[BUG] Web Buttons not displaying correctly

### ISSUE THREAD

**Issue by joshnortheimer** [bitfocus/companion#2628]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Bug Discovered by doing the following: In web controls,  Essentially, the hidden pages are still taking up space, just not visible.

### Steps To Reproduce

Click "web buttons" in side bar of companion. 
click gear icon, 
change the page range to any single page other than 1, or any combination of pages that doesn't include 1. 
it will hide the non-selected pages, but you have to scroll down to their position on the page, past a bunch of blank space, unless you "show page headings".

### Expected Behavior

I expected the visible pages to be at the top of the page, and not have to scroll. It worked fine until i upgraded companion to yesterday's betas. before that, the beta i was using was maybe a month old?

page worked correctly in beta companion-win64-3.2.0+6241-beta-be0b70bd
broken in:
companion-win64-3.2.0+6446-beta-feed26fe
companion-win64-3.2.0+6457-beta-dc4d6046

### Environment (please complete the following information)

```markdown
- OS: Windows 10
- Browser: Chrome
- Companion Version:

page worked correctly in beta companion-win64-3.2.0+6241-beta-be0b70bd

broken in:
companion-win64-3.2.0+6446-beta-feed26fe
companion-win64-3.2.0+6457-beta-dc4d6046
```

**Comment by Julusian** [comment]
This is fixed in beta 6491
