### ISSUE TITLE
[BUG] Trigger - Events - Variable to watch not updated

### ISSUE THREAD

**Issue by LikeThisReview** [bitfocus/companion#2629]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Trigger - Events - Variable to watch not updated when connection name has changed. 

### Steps To Reproduce

1. Set up a trigger with in Events - variable to watch use a connection variable (for example tcp-hypd: tcp Response) 
2. Change label connection "tcp-hypd" (for example) in to "tcp-hypdR"
3.  Check if the variable name in the trigger Events has changed

### Expected Behavior

"tcp-hypd" (for example) in Variable to watch in Trigger Events should change in to "tcp-hypdR" when the Connection name is changed from "tcp-hypd" in to "tcp-hypdR

### Environment (please complete the following information)

```markdown
- OS: latest Mas OS
- Browser: Safari
- Companion Version: 3.2.0 + 6439
```

**Comment by Julusian** [comment]
Fixed in beta 6492
