### ISSUE TITLE
Novastar vx4s tcp control

### ISSUE THREAD

**Issue by Roeland22896** [bitfocus/companion#263]
Add novastar control to streamdeck for controlling intensity levels, test patterns, inputs switchen, black-out. 
This especialy for controlling multiple novastar processors.

**Comment by dnmeid** [comment]
Roeland22896 do you have any documentation of the control protocol? Please add a link to it.

**Comment by Roeland22896** [comment]
Yes,

This is the PDF with the TCP controls


Op 1 okt. 2018, om 13:48 heeft dnmeid <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Roeland22896 do you have any documentation of the control protocol? Please add a link to it.

**Comment by haakonnessjoen** [comment]
Where is the pdf? Try replying on github, instead of via mail :)

**Comment by Roeland22896** [comment]
[VX4S command protocol.pdf](https://github.com/bitfocus/companion/files/2435786/VX4S.command.protocol.pdf)

Hope this is better :)

**Comment by jacksonhart1** [comment]
Any luck on this? I would really like this function to work. Thanks!

**Comment by josephdadams** [comment]
I have two Novastar VX4S's and would be happy to help test anything if needed.

**Comment by josephdadams** [comment]
Closing because this module repo exists. It needs testing...
