### ISSUE TITLE
Pictures in Help of modules are not displayed

### ISSUE THREAD

**Issue by sstaub** [bitfocus/companion#2631]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Most of the Help files for the modules have pictures included. This are no more visible, they was in former versions.
Personally I see the problem in QLAB and ETC EOS modules but this happens with all modules.
When you open the HELP.md on GitHub repository it looks as expected.

### Steps To Reproduce

1. Open GUI in browser
2. Go to the connection tab
3. Click on the "?" button to open the help file
-> no pics are visible

### Expected Behavior

The included pictures must visible, without the help files are hard to understand.

### Environment (please complete the following information)

```markdown
- OS:macOS Sonoma
- Browser:Safari 17.1
- Companion Version: 3.2.0 (3.2.0+6438-beta-e50aaf5f)
```

**Comment by Julusian** [comment]
This is fixed in beta 6491

**Comment by sstaub** [comment]
Thank you :-)
