### ISSUE TITLE
Preserve Logs

### ISSUE THREAD

**Issue by otelom** [bitfocus/companion#2632]
### Describe the feature

I think it would be nice to preserve logs after companion restarts.
We already have a "Clear log" button so if we want we can clear.
But when I tried to report a bug the other day, I went for the logs and was surprised by a blank page... this happened because I restarted companion in an attempt to debug an issue and that cost me my logs.

Are these logs saved anywhere when they disappear?

Also, what is the support bundle? What does it contain and where and with whom should we share it?

**Comment by Julusian** [comment]
The logs are written to disk, inside a `logs` folder next to the db and other config files.

The support bundle, is a copy of these logs, your full config and some other details about your machine. It says to be careful when sharing it, as if you have any api keys or passwords set in companion, they will be included in the bundle, and even if you remove the api key or password first, it is likely to be present in the log file or the db backups which get included.

I am not sure it is worthwhile loading the last log lines back into companion, as that will involve reading in the whole log file which can be hundreds of mb in size, resulting in slowing down companion at startup

**Comment by otelom** [comment]
Ok, it's good that the logs are stored, I didn't know that. In that case I also agree that it is not necessary to load them back into companion. We could, however, add a note, a button or some sort of info telling the user that the logs are available anyhow because the way it is, it appears there's nothing to export.
