### ISSUE TITLE
[BUG] Variable values persist even after variable is "destroyed" using setVariableDefinitions.

### ISSUE THREAD

**Issue by gdudik** [bitfocus/companion#2638]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you create a variable using setVariableDefinitions, and then assign a value to it, the value persists even if you do a new setVariableDefinitions that doesn't include the variable originally defined.

The variable doesn't appear in the list of variables for the module, but it still has a value if you attempt to use it.

### Steps To Reproduce

1. Create two variables setVariableDefinitions
2. Assign values to those variables
3. Assign the value of one variable to a button label.
4. Run a new setVariableDefinitions that doesn't contain the variable that the button label is assigned to.

Result: The button label persists with the original variable value instead of reverting to $NA or similar.

### Expected Behavior

Variable values should revert to undefined or $NA when the variable is not listed in a setVariableDefinitions call.

Variables not shown in the list of module variables should not have values.

### Environment (please complete the following information)

```markdown
- OS: Mac OS 13.3
- Browser: Chrome
- Companion Version: 3.1.2
```

**Comment by Julusian** [comment]
This is a bug in https://github.com/bitfocus/companion-module-base, it will be fixed in the next release of that (v1.7.0), but will only apply to modules once they upgrade the version of the lib that they use.
