### ISSUE TITLE
Vmix 21 - command toggle overlay not working

### ISSUE THREAD

**Issue by Carlofornasari** [bitfocus/companion#264]
**Make sure you're on the latest bleeding edge build** (remove this section from the bug report)
*Before you report a bug, make sure you're not reporting something that have been fixed in the master branch by downloading a "latest" build from https://builds.bitfocus.io/companion/*

**Describe the bug**

command "studiocoast-vmix: Set Overlay on Preview" does not work
command "studiocoast-vmix: Set Overlay on Program" does not work
All other functions work normally.

**To Reproduce**

1. Add Vmix as instance.
2 Click on a empty button to add a new button.
3 in the "Key down/on actions" section, click on dropdown menu, select "studiocoast-vmix: Set Overlay on Program"
4 Enter input number into field 
5 Select overlay number 1
6 add label to button.
7 Press button to activate "set overlay to program"

**Expected behavior**

The input selected should be played on overlay channel 1, which does not happen.

**Screenshots**

**Desktop (please complete the following information):**
Windows 10
Microsoft Edge

**Additional context**

**Comment by elmills** [comment]
I can confirm that I am experiencing the same bug.  

Using Vmix 21.0.0.58 (latest build) and when using the Vmix Web Controller and direct API access (http://127.0.0.1:8088/API/?Function=OverlayInput1&Input=2) the functionality worked as well, so I dont think it is an issue within the Vmix software itself.

**Comment by elmills** [comment]
I tested using the generic POST option with http://127.0.0.1:8088/API/?Function=OverlayInput1&Input=3 and it worked without issue.  I didn't see anything obvious in the configuration files in github, but still trying to figure out how they work.

![2018-11-20 17_12_48-companion admin](https://user-images.githubusercontent.com/9019827/48806183-8d7a4080-ece7-11e8-8f5a-c9ccec21a683.png)

**Comment by casbizz** [comment]
I had the same problem and now use the custom action: OverlayInput1 Input=3

**Comment by sytem** [comment]
I have no build-environment set up so I cant test this, but is there second whitespace in file ( https://github.com/bitfocus/companion-module-studiocoast-vmix/blob/ef45b63f60b9a0e9439db313d0c5b371d34e5553/index.js ) on line 394 and 398 ? Between word "FUNCTION" and actual command coming from opt.overlayId.

I can also confirm that with manual command, it works as it should. I have not yet tested if it also breaks with additional space

**Comment by sytem** [comment]
Now I have Vmix running, I can confirm that adding space before custom command breaks it. So Removing two whitespaces should fix this
