### ISSUE TITLE
[BUG] Can't set custom variable from OSC remote

### ISSUE THREAD

**Issue by yrphilippe** [bitfocus/companion#2641]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi, 
I can't modify value of custom variable from an OSC Client (in my case MaxMSP) with the command:
 /custom-variable/<name> <value>
Moreover, nothing appears in the Log tab.
However, if I try other commands like :
/press/bank/<page>/<button> <1>
it works as expected and I can see the command in the Log tab
Thanks for your suggestions

### Steps To Reproduce

1. Create a custom variable (in my case "focus1") - set it to 0.5
2. Create a button with the expression $(internal:custom_focus1) : the button displays 0.5
3. Try to modify it from an OSC client (in my case MaxMSP) withe the command : /custom-variable/focus1 0.6 : nothing happens
Moreover, nothing appears in the Log tab

### Expected Behavior

I'd like to modify the value of the custom variable and visualize it

### Environment (please complete the following information)

```markdown
- OS: 13.6
- Browser: Firefox 119.0
- Companion Version: 3.1.2 (MacOS Intel)
```

**Comment by Julusian** [comment]
There is a mistake in the docs, the path you should use is `/custom-variable/focus1/value`.
I've updated the docs in beta

**Comment by yrphilippe** [comment]
Thank you Julusian, it just works!
