### ISSUE TITLE
[BUG] LCD "buttons" on SD+ not aligned

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#2652]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The LCD buttons on the SD+ are not aligned with the hardware buttons or knobs. They are too close together.

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by Julusian** [comment]
I agree that the spacing is visually off, but it is mathematically correct.
The lcd strip is 800px wide, with each image being drawn at 100px wide, so we pad each end by 50px, and have a 100px gap between each.

To make it visually correct, it needs to have approximately a 25px padding either end, and a gap of 116.667px between each image. (from a quick attempt, I wont push that until I can make sure it is correct) So I guess it solves the problem, but once we can use to the full 200px per 'button', it will appear misaligned again

**Comment by MeestorX** [comment]
Such is the life of supporting manufacturers poor design mistakes!

**Comment by MeestorX** [comment]
Confirmed fixed in 3.2.0+6544 Beta.

Thank you!!
