### ISSUE TITLE
[BUG] Emulator and Web Buttons have limited zoom

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#2656]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When you open the web buttons or Emulator page, if you resize the browser window, below about 1000 pixels width, the buttons get smaller down to the minimum browser width. Above around 1000 pixels wide, the buttons do not get larger, just more space is added to the sides.
The buttons should continue to grow up to whatever width the browser page is expanded to, they shouldn't stop at an arbitrary size.

### Steps To Reproduce

Click on Web Buttons
Start resizing the browser
After a certain width (I'm guessing around 1000px) the buttons no longer get any larger

### Expected Behavior

Buttons should continue to get larger no matter how big the browser window gets

### Environment (please complete the following information)

```markdown
- OS: Sonoma
- Browser: Safari
- Companion Version: 3.2.0+6544-beta
```

**Comment by MeestorX** [comment]
Looks like the culprit is in the CSS:
```
.page-tablet .container-fluid, .page-tablet .container-sm, .page-tablet .container-md, .page-tablet .container-lg, .page-tablet .container-xl, .page-tablet .container-xxl {
    **_max-width:1200px;_**
    height: 100%;
    margin: 0 auto;
}
```
Removing `max-width` fixes the issue.

**Comment by Julusian** [comment]
While removing that line does make it be full width, #2659 before more prominent/common

**Comment by MeestorX** [comment]
Not sure what you're saying.

**Comment by Julusian** [comment]
a9f640f0a8c2c33ac1ba6bc4484ef0ef09d4d1d9
