### ISSUE TITLE
Import / export instanance to CSV

### ISSUE THREAD

**Issue by hadphild** [bitfocus/companion#266]
The ability to create a list of all your kit with static IP address and add them all in one quick import.

**Comment by dnmeid** [comment]
Hello hadphild,
sorry if I may dissapoint you again, but can you please explain how this should be beneficial to the average user. The effort of making a CSV file with the correct module-names and ip-adresses would be at least as big as just adding them in the web GUI. And then you wouldn't have the other configuration options, that needs to be set at each instance and are different from module to module.
Most Companion users are only controlling very few devices.
