### ISSUE TITLE
Missing internal: app_exit

### ISSUE THREAD

**Issue by PhilVale** [bitfocus/companion#2664]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using Companion 3.1.2 we seem toi have lost the internal: app_exit action which closed down Companion. This made it a lot easier for untrained users to shut down rather than having to find the icon in the System Tray and quit from there.

Was this dropped for a good reason or has it been lost or replaced by something else. I can't immediatly see a replacement action.

### Expected Behavior

That Companion would shut down

### Environment (please complete the following information)

```markdown
- OS:Windows 10
- Browser: Edge
- Companion Version: 3.1.2
```

**Comment by Julusian** [comment]
This got removed at some point before 3.0.0-rc1. I dont remember why that was.

I am not a fan of that being an action, but I suppose it may as well return. This is done in the betas now

**Comment by PhilVale** [comment]
Thanks Julian,

I'm not totally unsympathetic with your view on this but it does have a use in an environment where you are using non technical operatives. For us it shuts down the whole streaming/service subsystem of which or StreamDeck is an integral part. It then also means that untrained operators can't just come in and press buttons in an attempt to getting something working and mess things up. Sure I could look at locking down the deck and dimming the lights or switching to blank holding pages, but I wanted to see if this feature was taken away or I had just missed it.

Once again, thanks for reinstating and I'll hangon and wait for it to flow through from the Beta releases.
