### ISSUE TITLE
[BUG] isVisible in Feedbacks is inverted

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#2667]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In 3.2.0+6560 the isVisible() property of Feedbacks (and maybe Actions) is inverted. When used in Config fields it's still correct.

### Environment (please complete the following information)

```markdown
- OS: Sonoma
- Browser: Safari
- Companion Version: 3.2.0+6560
```

### Additional context

Works properly in 3.2.0+6546 so this is a new bug.

**Comment by Julusian** [comment]
Fixed in 6563
