### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TigerAudio** [bitfocus/companion#2672]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am trying to use feedback to reference a button state.  $(this:page)/3/0 and $(this:page)/3/$(this:column) and 1/3/0 all show the referenced button in the feedback and register the click, however only 1/3/0 triggers the feedback response.  I thnk this is a bug.

### Steps To Reproduce

Create a feedback any any button to change the color of the text.  Make the text change color with another button goes to step 2.  Use the terms $(this:page)/3/0 and $(this:page)/3/$(this:column) and 1/3/0 one at a time, where you are referencing the bottom row button (row 3), and that button has 2 steps, and when you push it, it goes to step two.

### Expected Behavior

If you use 1/3/0 the expected bahavior is to change the text color, and it works.
If you use $(this:page)/3/0 or $(this:page)/3/$(this:column), expected behavior is to change the text color but it does not work.

In all 3 cases in the UI, the button referenced shows next to the feedback.  The feedback simply will not trigger.

### Environment (please complete the following information)

```markdown
- OS:10.15/ Win 11
- Browser:Safari/ Chrome
- Companion Version: latest beta build as of Dec 6, 2023, but this has been a problem for a while.
```

**Comment by MeestorX** [comment]
Can confirm. $(this:xxx) is broken.
[Video](https://www.dropbox.com/scl/fi/7v9hyv8e92ygeyko64a0v/Button-Variables-not-working.mp4?rlkey=yza2cfpil2mfkhvjhedfjhk2c&dl=0)

**Comment by MeestorX** [comment]
Still broken in 3.2.0+6575-beta

**Comment by Julusian** [comment]
Right, this was broken for only some feedbacks, but not the one that I tried earlier
It is fixed now
