### ISSUE TITLE
[BUG] COMPANION IS LOCKED  3.1.2 

### ISSUE THREAD

**Issue by jacobbpeak** [bitfocus/companion#2674]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I type in the password the screen changes to a grey screen and I can't access any modules

### Expected Behavior

To be able to use the app and configure the companion 

### Environment (please complete the following information)

```markdown
- OS: Win 11
- Browser: Chrome/Opera
- Companion Version: 3.1.2
```

### Additional context

![image](https://github.com/bitfocus/companion/assets/153790467/97d18b6a-e8b0-4f08-87ef-ceeaa22cfbf9)
![image](https://github.com/bitfocus/companion/assets/153790467/beefa85b-4ef3-4906-b335-35a53815e8a1)

**Comment by Julusian** [comment]
Is there anything in the browser console? It sounds like something errored and the page crashed
Right click on the page and click inspect. Choose the console tab.

**Comment by Julusian** [comment]
This sounds like it could be an actual bug, but without more information to work from and no luck reproducing it there isnt anything we can do to fix it
