### ISSUE TITLE
[BUG] Can't run .sh file from companion on Raspberry Pi 5

### ISSUE THREAD

**Issue by Cas104010** [bitfocus/companion#2675]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi, I am completely new to Raspberry Pi and CLI.  I am trying to make a soundboard with a stream deck and a Raspberry Pi running companion and MPlayer. The companion software is up and running, and I can play audio with MPlayer with the command: mplayer /home/pi/documents/gameover.wav. I just needed something to link the two together and, in companion, thought the closest thing to do that is the "internal: system: run shell path (local)"-command. So I made a .sh file called: "gameover.sh" containing "#!/bin/bash" and the command to play the audio. (I also made it executable with chmod). In the terminal, running it works fine (sh /home/pi/documents/gameover.sh), however, I can't get companion to trigger this .sh file.

I have tried all kinds of variation with sudo, sh, trying to run the mplayer command straight from companion, and I get a different error code depending on the variation.

/home/pi/documents/gameover.sh gives: 
Internal/System: Shell command failed. Guru meditation: Internal/System: Shell command failed. Guru meditation: {"code":126,"killed":false,"signal":null,"cmd":"/home/pi/documents/gameover.sh"}

sudo /home/pi/documents/gameover.sh gives: 
Internal/System: Shell command failed. Guru meditation: 
{"code":1,"killed":false,"signal":null,"cmd":"sudo /home/pi/documents/gameover.sh"}

sh /home/pi/documents/gameover.sh gives:
Internal/System: Shell command failed. Guru meditation: {"code":2,"killed":false,"signal":null,"cmd":"sh /home/pi/documents/gameover.sh"}

I have also tried another command: sudo /sbin/reboot . Which does reboot the RasPi. I don't know if that helps, but it might.

### Steps To Reproduce

1. Install companion os on raspberry pi.
2. Download MPlayer: sudo apt install mplayer -y
3. Create directory "documents" in /home/pi
4. Put audio files in documents folder.
5. Create new file with script to run the command for mplayer to play audio file: (while in documents directory) sudo nano gameover.sh. In this file put: #!/bin/bash and on a new line mplayer/home/pi/documents/gameover.wav  . 
6. Then in companion, make a button with the run shell path command, and in the path entry, type: /home/pi/documents/gameover.sh

### Expected Behavior

Companion should trigger the .sh script, which triggers mplayer to play the gameover.wav audio file

### Environment (please complete the following information)

```markdown
- OS: Debian DNU/Linux 12 (bookwworm)
- Companion Version: 3.1.2 (3.1.2+6243-stable-05c37a10)
```

**Comment by Julusian** [comment]
perhaps it is a permissions issue?
Companion is being run as a user called `companion`. Does that user have permissions to read the full path to the script? (I am particularly wondering about the pi user folder). Did the chmod add execute permissions for everyone or just the user?

**Comment by Cas104010** [comment]
Thank you very much for your reply. I have moved all files to /home/pi in order to eliminate any issues with the "documents" folder I made. I have looked into permissions but haven't got any step further, unfortunately. When typing: `cd ..` and then `ls -l`. I now see `drwxryxryx 7 pi` in front of the "pi" folder. Then going back into root file with `cd ~` and typing `ls -l` shows `-rwxr-xr-x 1 root root` in front of gameover.sh and the same but with `pi pi` in front of gameover.wav.

Running the command from companion gives me the following error in companion: `Internal/System: Shell command failed. Guru meditation: {"code":1,"killed":false,"signal":null,"cmd":"/home/pi/gameover.sh"}`

**Comment by Cas104010** [comment]
So I have been trying some more things together with chatGPT. I changed something with the permissions with the following command: `sudo chmod +x /home/pi/gameover.sh`. Which made it possible to trigger the audio from companion. The weird thing is that I now can also just trigger audio straight from companion with `mplayer /home/pi/gameover.wav`.

This did lead me to another issue where the timeout in companion would quit the audio. After some more trying things with chatGPT, it suggested to output the logs to a txt file with the following code:

`#!/bin/bash
mplayer /home/pi/AM.mp3 >> /home/pi/audio_log.txt`

This completely fixed the 20-second timeout problem I had for some reason and I still have no idea why...
