### ISSUE TITLE
[BUG]Documentation Sidebar wrong location of burger

### ISSUE THREAD

**Issue by pcolot01** [bitfocus/companion#2677]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The "burger" location is wrong
In place of :

  Sidebar

  You can collapse the sidebar by clicking the "burger" icon on the **left** of Companion logo

Read:

  Sidebar

  You can collapse the sidebar by clicking the "burger" icon on the **right** of Companion logo

### Steps To Reproduce

Open documentation server:port/getting-started

### Expected Behavior

Correct location

### Environment (please complete the following information)

```markdown
- OS: 10 
- Browser: Chrome Version 120.0.6099.71 (Build officiel) (64 bits)
- Companion Version: v3.1.2+6243-stable-05c37a10
```

**Comment by Julusian** [comment]
Thanks! this is now fixed in the beta builds
