### ISSUE TITLE
[BUG] Cant select options in dropdown/multidown down actions or feedbacks

### ISSUE THREAD

**Issue by phillipivan** [bitfocus/companion#2680]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I can not select anything for from the populated dropdown options in either actions or feedback. Regardless of what I select, it returns to the default selection. Similarly for multidropdown. 
Dropdowns in connections->config work ok.

The behavior is consistent across different modules, both ones I've written and others (such as Yamaha RCP).

I hadn't encountered this behavior prior to today, which makes me think its particular to new beta builds.

...have tried rebooting computer. Tried rolling back to 6602 and that didn't help.

### Steps To Reproduce

In the latest beta.
Create an action with a dropdown option. 
Try to change from the default option.

### Expected Behavior

Allows selecting of option(s) from dropdown in actions & feedbacks.

### Environment (please complete the following information)

```markdown
- OS: Windows 10.0.19044
- Browser: Chrome 118.0.5993.71
- Companion Version: 3.2.0 Beta 6604
- Companion Version: 3.2.0 Beta 6602
```

**Comment by phillipivan** [comment]
It seems the same is true for checkboxes.

**Comment by phillipivan** [comment]
Rolling by to 3.2.0 Beta 6596 and the issue is resolved, so it seems to have cropped up since then.

**Comment by Julusian** [comment]
This is fixed in build 6605
