### ISSUE TITLE
[BUG] Action Recorder shows no instances in latest Beta

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#2682]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In 3.2.0-6610-beta, there are no instances in the Action Recorder Connection dropdown.
Works fine in 3.2.0-6583-beta

### Steps To Reproduce

Go to Action Recorder
Click on "Connections"
Dropdown is blank

### Expected Behavior

Should show a list of modules to use for the Action Recorder

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by jwetzell** [comment]
This commit is what broke the action recorder dropdown.

https://github.com/bitfocus/companion/commit/e4db885d933f68a9f73f1aa22915fef684ae8ac3

**Comment by Julusian** [comment]
Thanks for the info 6612 should fix this then

**Comment by jwetzell** [comment]
@Julusian was just about to elaborate. That was quick!
