### ISSUE TITLE
[BUG] CompanionPI after upgrade from 2.4.* to 3.1.2 not running

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion#2685]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

* I upgraded CompanionPI from version 2.4.2 to 3.1.2
* I didn't see any error during the update process.
* The computer's IP address is still the same 192.168.19.104.
* Companion not responding 192.168.19.104:8000 after restarting Raspberry PI.
* I tried restarting repeatedly and it didn't help.

I do not know, what to do. Please help.

### Steps To Reproduce

Run update from 2.4.2 to 3.1.2

### Expected Behavior

Raspberry Pi 4 on 8GB RAM
Clean installation with last updates.

### Environment (please complete the following information)

```markdown
- OS: Raspberry Pi 4 on 8GB RAM. Clean installation with last updates.
- Browser: Chrome
- Companion Version: update from 2.4.2 to 3.1.2
```

**Comment by Suenee** [comment]
After some tests and restarts, I decided to make full reinstall of RaspberryPi with last version of ING. You need save your configuration and let's do it.
If will someone find more sofisticated way, it will be fine...

**Comment by Julusian** [comment]
I don't know what to do about this. I was able to update a fresh install of 2.2.3 straight to 3.1.2 without issue, I also then tried the latest 3.2 beta. 

Perhaps it is something in your config that is causing the issue?

As only you appear to have encountered this issue, and you are happy to reinstall a fresh image I am unsure if it is worth spending any more time to try and reproduce this.

**Comment by Julusian** [comment]
Closing as I think this is related to the users config, and without a copy of that there isnt anything more that can be done
