### ISSUE TITLE
[BUG] Trigger press and release if variable meets condition - No release

### ISSUE THREAD

**Issue by luddibro** [bitfocus/companion#2686]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Button on Page 1 set to: internal: Button: Trigger press and release if variable meets condition
If variable meets condition, button triggers the correct button on page 2, which is set to: Press: PTZ-Camera: Pan/Tilt - Up Left, Release:  PTZ-Camera: Pan/Tilt - Stop.
When I press the Button on Page 1, the Camera moves correctly, but keeps moving when I release the button. The related button on page 2 works perfectly.

### Expected Behavior

Button on Page 1 should work exactly like on Page 2
### Environment (please complete the following information)

```markdown
- OS: Windows 10
- Browser: Opera
- Companion Version: 3.1.2.
```

**Comment by Julusian** [comment]
`internal: Button: Trigger press and release if variable meets condition` will not do what you want here. when you press the button it will be executing the press actions of the other button, and 20ms later triggering the release actions of the other button.

If you look at your button on page 1, you will have added an action under the 'press actions' heading, but not under the 'release actions' heading, so it wont be doing anything when released.

Closing as there is no bug here
