### ISSUE TITLE
Upcoming development workflow change with the release of v3.2

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion#2691]
Coinciding with the release of v3.2, we intend to do some git branch reshuffling.

## The plan

* rename `master` to `main`, to match current git recommendations for branch naming
* move development of beta releases to the `main` branch
* remove the then unused `beta` branch

## Impact to users

This will only impact anyone running companion from source.

Once the change has been made, you will need to update your local clone to be using the correct branch. Subscribe to notifications on the right to be notified by github once the change has been made (this issue will be closed).  

Detailed steps on what you will need to do to your clone will be provided closer to when the changes are made.

## Why?

We find that contributors don't know what branch to target with a PR, as github defaults to targetting the default branch (currently `master`, the default will become `main`).
Additionally, current development is a bit hidden away on a branch, which makes it harder to see what is happening without knowing where to look.
We already have these `stable-3.1` and similar branches where releases are prepared, with `master` being used as a marker to the latest release. But this can be discovered either on the website, looking at the git tags, or the github releases.

From what I remember, development was moved to beta from master because of concern about companionpi users updating with a git pull and pulling in whatever was in master. But the images havent worked this way since well before 3.0, and it is no longer recommended to run from source outside of development.

By not using the default branch, we are missing out on some nice github functionality too, like issues not being closed when merging linked PRs, and dependabot only being able to open security fix PRs for the default branch.

**Comment by Julusian** [comment]
For updating your local clone of this, if you are on the master or beta branch already you can run `git pull` followed by `git checkout main` to switch. You should then run `git branch -D master` or `git branch -D beta` to delete the old unused branch.

If you are using your own branch, then continue as usual, and you can pull in changes from `main` instead of `beta` like you usually do

**Comment by pabloko** [comment]
this is very much needed!
great work guys!!💪💪💪
