### ISSUE TITLE
Allow surface index in surface page change commands

### ISSUE THREAD

**Issue by stuartpinfold** [bitfocus/companion#2694]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

On the internal - set surface to page commands, we can use variables to decide the page to go to, but the affected surface has to be selected from a list or a number entered. One cannot use variables for the surface selection.

It would be great if we could use variables (surface name or sequence number) to choose which surface the page should be displayed on. 

### Usecases

We have a "master" vMix project and Companion config which we use for all our productions. This involves 3 Streamdecks, called Left, Middle and Right. However, each job goes out with 3 random Streamdecks grabbed from the warehouse from our stock of dozens of them. We the have to spend time in the Companion project re-setting all the "change page" commands to use the collection of Streamdecks.

If it was possible to use a variable to set the surface, we could have a page on Streamdeck where we set three variables with either 1, 2 or 3. So, for example, Middle=1, Left=3, Right=2. Then use that variable to change the page via the sequence number.

**Comment by Julusian** [comment]
This is already possible in the betas:
![image](https://github.com/bitfocus/companion/assets/1327476/0363b983-da69-42b4-ad89-acd926302c80)

**Comment by stuartpinfold** [comment]
Hmm, it doesn't seem to work for the surface number which is what I need (#1, #2, #3, etc). It does work with the full name but then I'd still need to go in and change the variable-setting buttons to use the names of the connected surfaces.

I've tried using "#1" and "1" as the variable value, but neither seems to work - only the full name of the surface ("streamdeckABCDEFGHIJ436457" etc)

Is this possible?

**Comment by Julusian** [comment]
Oh yeah it doesnt handle doing it by index, I forget that index is a thing for surfaces as it has always felt so brittle to me.
It could be added though

Would the new surface groups functionality help you at all here? That is intended both as a way to group surfaces (not what you want) and as a way of making surface ids stable when swapping out a streamdeck

**Comment by stuartpinfold** [comment]
The brittleness of the index numbers is exactly what we'd solve by being able to set whether it's number 1, 2 or 3 on the Left; 1, 2 or 3 in the Middle; and 1, 2 or 3 on the Right. If for some reason the index numbers change we can just go in and tell the config that Left is now 2.

Anything involving surface IDs wouldn't work for what we need - only index numbers where we can quickly hit 1, 2 or 3 against the three variables for Left, Middle and Right.

**Comment by Julusian** [comment]
> Anything involving surface IDs wouldn't work for what we need - only index numbers where we can quickly hit 1, 2 or 3 against the three variables for Left, Middle and Right.

but you could create a group called 'left', a group called 'middle' and a group called 'right'. your actions/feedbacks/variables would then reference those groups. and in the surfaces tab you can assign each streamdeck to one of those groups.
then if you swap out or remove a streamdeck, the others wont be affected, as they will still belong to the same group as before. at most you will need to assign the new/replacement streamdeck to one of the existing groups

**Comment by stuartpinfold** [comment]
The idea is for the user to never have to look at Companion - index numbers would be really ideal.

**Comment by Julusian** [comment]
> The idea is for the user to never have to look at Companion - index numbers would be really ideal.

They only would need to do so when swapping/rearranging the streamdecks. Which they would almost certainly need to do either even if doing it by index.

Im not saying this wont/shouldnt be done, I just struggle to see the value in the index system since groups were added, so I am trying to understand if there are scenarios I haven't thought of where the index system is actually superior

**Comment by stuartpinfold** [comment]
> They only would need to do so when swapping/rearranging the streamdecks. Which they would almost certainly need to do either even if doing it by index. 

Not necessarily. Grab three random Streamdecks from from the 50 in the warehouse, plug them into the USB hub of a random vMix machine. Place the 3 Streamdecks in any order (L, M, R) on the desk. Boot up the machine, Companion loads automatically. It automatically detects the three Streamdecks and assigns them random index numbers. The save file is programmed to open at the "Streamdeck selection" page. 

All our operator needs to do is hit 1, 2 or 3 next to Left, Right and Middle on that startup page to set the variables - they don't need to load the GUI, know the device IDs or worry about anything else. There is an "identify" button also next to the selections which flash the brightness of Streamdeck at index 1, 2 and 3.

So, push "Identify 1" and the middle one flashes. Press 1 next to Middle.
Push "identify 2" and the right one flashes. Press 2 next to Right.
Then by process of elimination, press 3 next to Left.

Show is ready to go.

**Comment by Julusian** [comment]
> All our operator needs to do is hit 1, 2 or 3 next to Left, Right and Middle on that startup page to set the variables

Ah, that is the bit I was missing. I don't have an equivalent flow for this with groups currently.

**Comment by stuartpinfold** [comment]
But just being able to use the index number on the "set surface to page" functions would be enough - we can already use the device ID or *select* the index number from a dropdown, but can't use the index number as free text or a variable.

**Comment by Julusian** [comment]
This is now in the betas for the `Set by index to page` action.

I also realised another flow that I think would solve your problem;
It sounds like serialnumbers would work, but there was no way to easily assign them to variables, which stopped you from doing the assignment on the streamdecks. Internal actions now have access to `$(this:surface_id)`, so this might now be possible. Using similar buttons, you could have buttons which would store that value to a custom variable, which could then be used by the change page actions.
And this will probably also make it possible to do some more complex stuff using expressions, such as a 'return to start' button, which will send to a different page depending on whether the current surface_id matches your left, right or center variables). That won't be trivial or clean to write, but should be doable
