### ISSUE TITLE
[BUG] Button Text size does not import from config

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion#2695]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Tried the latest beta for the first time in a while and importing a full config does not import or keep the button text size.  Have tons of two line text buttons and all are midsized and look to need to be updated individually.  Coming from 3.1.2 Stable.

### Steps To Reproduce

Import a full config from 3.1.2
See that button texts all return the AUTO rather than a set size.  Auto causes misformatting

### Expected Behavior

Text sizes to import correctly

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by Julusian** [comment]
I'm not seeing this. Can you provide an export of a page to test with?

**Comment by obcocav** [comment]
@Julusian .  Sorry for the long delay replying!  Sending a config file now.  Also I attempted an install at my main system and pages were all mixed up. with buttons doubled and layouts mixed up.  For instance row 1 of buttons appeared on row 1 and 3 of a 15 key deck on one page.  Let me know how else I can help.  Thank you!!

**Comment by obcocav** [comment]
[COMPANIONSERVER_custom-config_20240128-1509.companionconfig.pdf](https://github.com/bitfocus/companion/files/14077716/COMPANIONSERVER_custom-config_20240128-1509.companionconfig.pdf)

@Julusian. Tried emailing but did not go through.  Here it is with extension changed to PDF to upload.

**Comment by Julusian** [comment]
@obcocav I'm not seeing the importing error here. Various buttons are importing sizes, and the other ones I have checked did have auto previously.
There are differences in font sizes compared to 3.1.2, could that be what you are seeing?

**Comment by obcocav** [comment]
This seems to have been solved by using a 3rd party uninstalled to clean the registry and files from the previous companion install.

**Comment by Julusian** [comment]
> This seems to have been solved by using a 3rd party uninstalled to clean the registry and files from the previous companion install.

I can't explain why that would help. Did it manage to wipe away your config? If so, then maybe there were some 'controls' which had been lost and so were fighting others? But Im pretty sure at startup we do a check for those to discard them and I don't know how that could result in the drawing colliding, as those stuck controls are stuck because they don't belong anywhere

**Comment by Julusian** [comment]
I'm going to close this, as it sounds like it only affected you and you found a solution (even though I can't explain why it helped)
