### ISSUE TITLE
[BUG] Companion 3.1.2

### ISSUE THREAD

**Issue by MattersShay** [bitfocus/companion#2701]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I had companion 2.2.0 n a linux Machine, we have upgraded to Windows 11 and we have downloaded companion 3.1.2
I thought but transferring the log from Companion Linux to  Companion Windows a lot of my connections are broken. 
I have troubleshooted everywhere I could. But I can't seem to figure out what the problem is. 
Any help would be great. 
I would even download companion 2.2.0 for windows but it's not available. 

Please help 
![Projectors ](https://github.com/bitfocus/companion/assets/157190289/085fd9b6-ff0f-4e2b-b8ae-ddd484c76927)
The projectors on 2.2.0 never get disconnected, but they are not stable on the latest version. 
![BirdDog](https://github.com/bitfocus/companion/assets/157190289/fecdfeae-e856-46f7-9d15-9d6f858816d5)
Same issue happens here with the birddogs. 

![Screenshot 2024-01-19 192830](https://github.com/bitfocus/companion/assets/157190289/cfecda4d-a48d-4e5e-a37b-142acde8e3a3)
Everything works on this version
![Screenshot 2024-01-19 192908](https://github.com/bitfocus/companion/assets/157190289/4f9d13f1-fecf-4a22-87e5-64cad82a13ef)

### Environment (please complete the following information)

```markdown
- OS: Windows 
- Browser: Chrome 
- Companion Version: 3.2.1
```

**Comment by Julusian** [comment]
Im going to close this, as I don't think there is anything in the core of companion that can be done to resolve this.

It looks like you have gotten some help on slack, and you could also try the github repository for each of the modules that are being problematic. (eg https://github.com/bitfocus/companion-module-renewedvision-propresenter) as the module authors will be able to give better help than the core developers.
