### ISSUE TITLE
Dowload from www is previous version companion-win64-3.1.2+624 

### ISSUE THREAD

**Issue by trebor-56** [bitfocus/companion#2709]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Website maynot be updated yet ?
Downloaded 3.2 comes up as companion-win64-3.1.2+6243-stable-05c37a10
thank you

### Usecases

Dowload issue

**Comment by trebor-56** [comment]
Dload again now correct version.
thanks

**Comment by Julusian** [comment]
yeah, it takes a little time for all the builds to appear.

it does indicate that some are older than others, in this screenshot, just one hasnt been updated
![image](https://github.com/bitfocus/companion/assets/1327476/d685d05a-c1b8-41a9-9a7e-6584f4f1d05b)
