### ISSUE TITLE
[BUG] Still showing Companion buttons after app Quit

### ISSUE THREAD

**Issue by jgclark** [bitfocus/companion#2720]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I quit Companion, the buttons are still showing on my Streamdeck 15, and I can still move between different pages, for example.
When I then start Elgato Stream Deck app, it cannot take over and show its profile.

The odd thing is that I can see all 4 processes that start with names "Companion" do stop.

Existing issue https://github.com/bitfocus/companion/issues/2650 might or might not be related.

### Steps To Reproduce

1. Companion is running
2. Stop Companion via menubar or window
3. Wait.  Start Elgato Stream Deck
4. Companion buttons are still showing, and I can't get Elgato buttons to become active. This requires a reboot.

### Expected Behavior

When I quit Companion from menu bar or window, the buttons stop showing.
And I can then run Elgato Stream Deck app and it show its buttons.

### Environment (please complete the following information)

```markdown
- OS: macOS 13.6.2
- Browser: Orion 0.99.126.4.1
- Companion Version: 3.3.0-6693main
```

**Comment by Julusian** [comment]
I've found that (on linux) using alt+f4 to exit companion would have this behaviour, but not when using the quit button. I've pushed a fix for that, maybe it helps in your case? 
Its in the 6738 beta build

**Comment by jgclark** [comment]
Thanks. I've now tried that beta, and it does now work OK on macOS. Good work!

**Comment by Julusian** [comment]
Perfect.
This will be in the next patch release
