### ISSUE TITLE
[BUG] Imported config from 3.1.2 to 3.2.0 on Windows results in misplaced and doubled buttons

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion#2724]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I import my full config from 3.1.2 to 3.2.0 I end up with pages that have buttons repeated graphically but not functionally.  For instance I have a page where row 3 buttons DO what they are supposed to do but graphically they are drawn as repeats of row 1.  I have completely uninstalled and reinstalled with same issue.  This does NOT occur on other PCs when I try this.  I also get a notice when starting Companion that a new version was installed and that the config will not be used until that version is reinstalled?  Any ideas?

### Steps To Reproduce

1. install 3.2.0
2. see page with repeated buttons

### Expected Behavior

config work as expected

### Environment (please complete the following information)

```markdown
win 11 - OS:
edge - Browser:
3.2.0 - Companion Version:
```

**Comment by obcocav** [comment]
ETA.  the buttons "flicker" all the time as well even when no actions are happening.

**Comment by obcocav** [comment]
It looks like the flicker is intermittent and mostly on buttons that are displaying clock in the HH:MM:SS format.  Flickers each redraw of the SS.  This did not use to be the case.

**Comment by Julusian** [comment]
Are they flickering in the ui, or just the streamdeck?
Importing your config from #2695, I don't see this issue in the webui

**Comment by obcocav** [comment]
It appears to flicker on the UI and the decks themselves. Seems it’s only noticeable on the button showing time.Sent from my iPhoneOn Jan 30, 2024, at 14:50, Julian Waller ***@***.***> wrote:﻿
Are they flickering in the ui, or just the streamdeck?
Importing your config from #2695, I don't see this issue in the webui

**Comment by Julusian** [comment]
Perhaps this was the same bug as another issue, where the main process of companion wasnt always exiting when the launcher was closed.
If so, a restart of the machine would resolve it. And a fix for that bug is in 3.2.2

**Comment by Julusian** [comment]
Without a way to reproduce or more reports, I don't see how to progress on this.
Hopefully it was fixed by the other fixes in 3.2.2 or restarting the pc. If not then comment here and reopening this can be considered
