### ISSUE TITLE
Companion plugin in elgato stream deck not updated by bitfocus 

### ISSUE THREAD

**Issue by Michelmj** [bitfocus/companion#2728]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I was trying to get bitfocus companion on elgato stream deck, but it only installs the 2.2.0 version. The companion plugin only goes up to 2.2.0 whereas bitfocus companion says, the plugin has to be at least 2.4.0, yet companion has not been updated in elgato stream deck even though it says the latest release says it is updated.
![IMG_0952](https://github.com/bitfocus/companion/assets/38635668/9f7765ad-f06a-45e9-ba72-00a52e4ded55)
 Can bitfocus fix this issue please?

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by Julusian** [comment]
This is saying that v2.2.0 of the plugin requires Companion to be running 2.4.0 or newer.

The v2.2.0 of the plugin works fine with the latest release of Companion, there has been no reason to make any updates to the plugin

**Comment by Michelmj** [comment]
Hi Bitfocus/Companion,

Is there something I am missing? I installed the latest companion which I
believe is 3.2.0 or something like that, but it won't let connect at all.

**Comment by Julusian** [comment]
Did you disable this setting in companion?
![image](https://github.com/bitfocus/companion/assets/1327476/88c3fe2d-24e0-40fb-8329-7e2319c61ff7)

**Comment by Michelmj** [comment]
I'm at work now, but I will check it when I get home.
Thanks

**Comment by Michelmj** [comment]
I just checked everything, and it is turned on. I restarted companion
multiple times and I am still getting the same error message on my stream
deck.

**Comment by mctie89** [comment]
Same issue for me. I have companion running on a pi and a stream deck+ on my pc and receive the same error. Cannot get it to connect. I have tried several versions of companionpi back to 3.0.0 and nothing. I have also tested not using elgato software, but instead companion satellite and that works. But I would rather control my pc and stream deck with Elgato's software and add Companion button using the plugin to control other items in the home like home assistant. But no success getting the plugin to work. Any suggestions? A checkbox I'm missing or setting? To confirm, I have "disabled connected streamdecks" thus enabling the use of the plugin in companion, but still nothing shows up in the surfaces tab.

**Comment by Julusian** [comment]
@mctie89 the plugin doesnt support connecting to companion on another machine, so it wont work in your setup.
Well, it technically does work, but you have to edit the plugin code to be connecting to the correct ip address, and this change often gets lost

**Comment by Julusian** [comment]
@Michelmj that setting I showed should be set to off (as shown in the screenshot)
I don't know why else it wouldnt be working

**Comment by mctie89** [comment]
> @mctie89 the plugin doesnt support connecting to companion on another machine, so it wont work in your setup. Well, it technically does work, but you have to edit the plugin code to be connecting to the correct ip address, and this change often gets lost

Ah, thank you. That helps to know.
