### ISSUE TITLE
Feature Request: Cue Stack

### ISSUE THREAD

**Issue by KarstenTWolf** [bitfocus/companion#273]
**Describe the feature**
Buttons have cue stacks.

Have a 'wait for next button press' delay checkmark option for items in the button list. This changes the button into a cue stack. Steps will run with their selected delays unless a 'abort previous step delays' option is checked on a subsequent step.
Cue stacks should 'loop' and have a small step counter that shows in the upper right corner of the button. The next step can be manually reset or change via the GUI, the next step should be graphically indicated. So the button readout could be "CURRENT/TOTAL -> NEXT" (ie: 5/10 -> 7)

- Consideration could be given to having an optional 'release' trigger per step, but I think the feature could be implemented without this.

- Timed delays could be disabled altogether for ease of implementation, and/or the cancel timer option disregarded. Feature would still be useful with or without. 

**Example:**

Two actions under the 'down' key, are listed. The second item has a delay of 5000ms. They are graphically indicated as being 'step 1'.
The third item has 'wait for user action' checked under delay. This item is graphically indicated as being 'step 2'. The checkmark for 'abort previous step delays' has been checked. 

The first time the button is pressed, the first two actions trigger. The counter in the upper right of the button increments from 1/2 to 2/2. 

The second button press triggers the third item. The counter loops back to 1/2. If the button is pressed before the delay timer of the previous step completes, the step with the timer is cancelled. 

In the GUI, the user can change the next step to manually be one or two.

**Comment by Julusian** [comment]
I believe this is solved with the #1630 in 2.3/3.0
