### ISSUE TITLE
[BUG] - Companion is locked

### ISSUE THREAD

**Issue by glwheeler** [bitfocus/companion#2732]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![Screenshot 2024-02-04 151118-Companion is locked](https://github.com/bitfocus/companion/assets/15280275/9b1a5dd6-a371-47c2-9be2-35ccfadb3e1d)

### Environment (please complete the following information)

```markdown
- OS: Windows 11
- Browser: Edge
- Companion Version: 3.2.0+6663
```

**Comment by Julusian** [comment]
https://github.com/bitfocus/companion/issues/2393#issuecomment-1483900433
