### ISSUE TITLE
uncaught exception

### ISSUE THREAD

**Issue by Turnipisum** [bitfocus/companion#274]
![img_20181005_084211](https://user-images.githubusercontent.com/23130067/46571716-f6913900-c971-11e8-8fc6-db5d16e460f9.jpg)

**Comment by Trgrm** [comment]
<img width="424" alt="skjermbilde 2018-10-08 kl 01 08 17" src="https://user-images.githubusercontent.com/32874251/46588094-ae1f6b80-ca96-11e8-93fa-c4d633394ea1.png">
I have this message on one of my mac`s. I have updated and re-installed without any luck.

**Comment by willosof** [comment]
Have you tried installing the latest developer version?

**Comment by willosof** [comment]
Next time you catch a bug like that, always try the latest developer release before reporting it. Or, at a bare minimum provide which version you're running 👍

**Comment by willosof** [comment]
Cannot reproduce
