### ISSUE TITLE
Ross Talk Listener not translating properly in 3.3.0

### ISSUE THREAD

**Issue by mattwhitsett** [bitfocus/companion#2742]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Sending Ross Talk CCs (ex. 6:18) from dashboard, these triggers have worked fine in the past but ever since the button labeling changed the ccs are not triggering the same buttons.
![Image 2-12-24 at 9 39 AM](https://github.com/bitfocus/companion/assets/149319933/f3d68b0d-735a-4cfc-b232-2b3fb5a6c192)
![Screen Shot 2024-02-12 at 9 36 30 AM](https://github.com/bitfocus/companion/assets/149319933/67dcba80-f9bc-4292-823a-3c39b28f02ed)
![Screen Shot 2024-02-12 at 9 37 19 AM](https://github.com/bitfocus/companion/assets/149319933/31c45572-8e2d-4133-9a33-3a97fea08032)

### Steps To Reproduce

Send CC to companion, check logs to see which button was pressed and released

### Expected Behavior

In past versions the 6:18 cc was translated to press what is now labeled 6/2/1, instead its being translated as 6/1/2.

### Environment (please complete the following information)

```markdown
- OS: Catalina
- Browser: Chrome
- Companion Version: 3.3.0+6715
```

**Comment by krocheck** [comment]
@Julusian this does look like the X and Y are reversed.  I can go ahead with the fix but can't directly test.

**Comment by Julusian** [comment]
It looks like just the logging has the numbers inverted, but not the logic that fires the press.

@mattwhitsett can you confirm whether it is just a logging issue, or is it a behaviour thing as well? 
If it is behaviour too, is that definitely swapped, or offset or something?

**Comment by krocheck** [comment]
> It looks like just the logging has the numbers inverted, but not the logic that fires the press.
Yeah, I see that now.  Honed in on the logging more than the actual execution.

**Comment by mattwhitsett** [comment]
Originally thought it was behavior, but after looking into it more it does seem to be functioning properly, just a logging issue.

**Comment by mattwhitsett** [comment]
Did some testing, it seems to be functioning properly. Just a logging issue, not a behavior issue @Julusian

**Comment by Julusian** [comment]
nice!
I've pushed a fix for the logging
