### ISSUE TITLE
Module for Encore and FSN

### ISSUE THREAD

**Issue by DiViPro01** [bitfocus/companion#275]
Could you please add some support for the old encore and FSN systems?
Just recalling presets would be great

**Comment by willosof** [comment]
Do you have access to the documentation for the protocol? :)

**Comment by willosof** [comment]
Duplicates #230 ish

**Comment by DiViPro01** [comment]
Yes, actually, it is via telnet commands that you can send these commands.
I will send a copy of the syntax when I am behind a computer

Op zo 7 okt. 2018 16:05 schreef William Viker <notifications@github.com>:

**Comment by willosof** [comment]
Finished and available in latest developer build :)

**Comment by DiViPro01** [comment]
Wauw

Op zo 7 okt. 2018 16:59 schreef William Viker <notifications@github.com>:

**Comment by fusionstream** [comment]
There appears to only be 2 commands available. Take, and recall preset. It might make sense for an Encore but not so much for the FSN. Possible to include "Custom commands" in the module?

**Comment by fusionstream** [comment]
> 
> 
> There appears to only be 2 commands available. Take, and recall preset. It might make sense for an Encore but not so much for the FSN. Possible to include "Custom commands" in the module?

Created a new issue in the Encore module repo itself
https://github.com/bitfocus/companion-module-barco-encore/issues/1#issue-382490814
