### ISSUE TITLE
loss of config

### ISSUE THREAD

**Issue by Ulwell** [bitfocus/companion#2755]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Every month or so I lose the configuration and have to reimport it. Is this a common issue?

### Expected Behavior

Configuration to stay stable!

### Environment (please complete the following information)

```markdown
- OS: Win 10
- Browser: Chrome
- Companion Version:latest stable version
```

**Comment by willosof** [comment]
Umm. Sounds like you may have some kind of cleanup software running monthly?

**Comment by Ulwell** [comment]
It's not that regular, the month is just an average, but I will have a look at that. Thanks.

**Comment by Julusian** [comment]
I know we used to have issues a year or so back with the config file getting corrupt a lot for some reason, but reports of that have stopped.

Could you confirm the version number you are running?

**Comment by Julusian** [comment]
There isn't enough information here to act upon
