### ISSUE TITLE
[BUG] TRIGGERS

### ISSUE THREAD

**Issue by BarbeRousseDeVicto** [bitfocus/companion#2757]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In Triggers, when you add the Action "internal: Button: Set current step" The icon of the button doesn't appear. This fonction work great in Button but not in Triggers

### Expected Behavior

<img width="1683" alt="image" src="https://github.com/bitfocus/companion/assets/145688850/a3b89e16-c1d3-4aac-ba4b-a452dca066eb">

### Environment (please complete the following information)

```markdown
- OS: W10
- Browser: CHROME
- Companion Version: 3.2.1 (3.2.1+6676-stable-fa981d25)
```

**Comment by Julusian** [comment]
This is now fixed in beta and will need in the next patch release
