### ISSUE TITLE
[BUG] RossTalk Listener Silently Ignores Button Press Commands

### ISSUE THREAD

**Issue by zmcandee** [bitfocus/companion#2758]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Versions after 3.1.0 do not respond to button press commands on the RossTalk listener.  Intentionally using a malformed string does trigger `Invalid incoming RossTalk command: ${data}` but a properly formed string that worked in 3.1.0 fails in later versions and never prints `Push button ${pageNumber}/${xy[0]}/${xy[1]}`.

### Steps To Reproduce

1. Enable RossTalk listener
2. Use an external program to send a `CC 1:1` command (I use ProPresenter 7)
3. Check companion logs for `1/0/0` button presses

### Expected Behavior

Button `1/0/0` actuates for 20ms

### Environment (please complete the following information)

```markdown
- OS: MacOS
- Browser: Chrome
- Companion Version: >3.1.0
```

### Additional context

Both new setups and setups upgraded from a working 3.1.0 fail.

**Comment by Julusian** [comment]
This is now fixed in beta and will be in the next patch release

**Comment by zmcandee** [comment]
Thanks for the quick update!   Would you mind changing the warning to `Invalid incoming RossTalk button reference: ${bank}`? Repeated messages make debugging more of a chore. https://github.com/bitfocus/companion/blob/edb8f1a6489cda80cd676d717a5557f232364945/lib/Service/Rosstalk.js#L71
