### ISSUE TITLE
Latest 3.3.0 beta [4670f7f9201ffd7c736e07c5bd3d9433139791c8] on macOS not launching [BUG]

### ISSUE THREAD

**Issue by tpk001** [bitfocus/companion#2761]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The latest 3.3.0 (21 Feb 2024)
The installer downloaded shows and app called "companion-launcher.app" not "Companion.app"
When you start the "companion-launcher.app" nothing happens.

### Steps To Reproduce

1. Download the latest 3.3.0 (21 Feb 2024) beta [4670f7f9201ffd7c736e07c5bd3d9433139791c8]
2. Open the .dmg
3. Copy the included companion-launcher.app to /Applications
4. Open companion-launcher.app

### Expected Behavior

Expecting Companion.app and start correctly.

### Environment (please complete the following information)

```markdown
- OS:macOS 13.6.4
- Browser: NA
- Companion Version: 3.3.0 Beta [4670f7f9201ffd7c736e07c5bd3d9433139791c8]
```

### Additional context

If you load the companion-launcher binary. The terminal shows this error:

```/Applications/companion-launcher.app/Contents/MacOS/companion-launcher ; exit;
[0221/131456.434787:FATAL:electron_main_delegate_mac.mm(67)] Unable to find helper app
Trace/BPT trap: 5
```

**Comment by Julusian** [comment]
Thanks for reporting.
This is working now
