### ISSUE TITLE
[BUG] Latest 3.99.0+6793 experimental on macOS not launching [BUG

### ISSUE THREAD

**Issue by MESSaROUND84** [bitfocus/companion#2764]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The latest experimental version 3.99.0+6793 (22 Feb 2024)
The installer downloaded shows and app called "companion-launcher.app" not "Companion.app"
When you start the "companion-launcher.app" nothing happens.

### Steps To Reproduce

Download the latest 3.99.0+6793 (22 Feb 2024)
Open the .dmg
Copy the included companion-launcher.app to /Applications
Open companion-launcher.app

### Expected Behavior

Was expecting a companion.app (not companion-launcher.app) and that it would open and work.

### Environment (please complete the following information)

```markdown
- OS:Ventura 13.6.4 (22G513)
- Browser: Safari, Chrome
- Companion Version: 3.99.0+6793
```

**Comment by Julusian** [comment]
Probably the same as https://github.com/bitfocus/companion/issues/2761
Itll be fixed once that gets merged up to develop

**Comment by MESSaROUND84** [comment]
Thanks, yes probably the same. The 3.3.0 works fine again it's just the experimental version that still has this issue.

**Comment by Julusian** [comment]
A fixed version is building now
