### ISSUE TITLE
[BUG] TCP / HTTP remote control no longer working after update to 3.2.1

### ISSUE THREAD

**Issue by raugert** [bitfocus/companion#2768]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

TCP Remote triggering no longer working after update to 3.2.1. Tried with new commands and depricated commands. I get a message received acknowledged,  but button doesn't execute the command.
HTTP triggering works the first time the request is sent but then no longer works ?

I see the entry in the companion log. I am using my own TCP client app for testing purposes. I have also tried with "PacketSender" app and got the same result. The objective is to update my "vMix Panel Builder" app to comply with the latest companion command updates..

### Environment (please complete the following information)

```markdown
- OS: MAC Sonoma 14.2
- Browser: 
- Companion Version: 3.2.1
```

**Comment by Julusian** [comment]
Are you sending a newline after each TCP command?
I have just checked and the TCP api is working fine for me, tested with telnet on the command line.

And I can't explain the http not working for you, I use that daily without issue. I was using the old api on 3.2.1 until yesterday when I updated the external tool to the new api

**Comment by raugert** [comment]
Yes, I forgot the newline after the TCP command. SORRY MY BAD :(  It works now...  but the behaviour is somewhat different than version 2.4.2 ! This is what threw me...

If I send a "Location x/x/x DOWN" command in version 3.2.2, I can only tigger the button once. It appears that it ignores subsequent "Down" commands until an "UP" command is sent to that button. This was not the case in 2.4.2. Sending an "UP" command after a "DOWN" command was not necessary.  It took a while to figure this out, but now that I know the behaviour I can program things accordingly.

Using the Location x/x/x PRESS work fine as it actually sends both the "DOWN" and "UP" commands at the same time.

After all, this is not really a Bug but a change in behaviour from previous version.
