### ISSUE TITLE
Double sending OSC

### ISSUE THREAD

**Issue by Tbukaj** [bitfocus/companion#2769]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello guys,

I have an problem with double sending osc on Mac mini m2 - 13.2.1

I tried:
Clear app data
Install the newest version 
copy config to other pc(windows - all right)

The problem appeared overnight.

best,
Kuba

### Environment (please complete the following information)

```markdown
- OS:Mac 13.2.1 Mac mini m2 
- Browser: chrome
- Companion Version: 3.1.1 and 3.2.2
```

**Comment by Julusian** [comment]
How are you sending this osc? the generic-osc module, a different module?

Does it behave after restarting your computer?

**Comment by Julusian** [comment]
There isn't enough information here to act upon
