### ISSUE TITLE
Feature Request: VMix

### ISSUE THREAD

**Issue by Keksstar** [bitfocus/companion#277]
**Describe the feature**
Control of VMix Software

**Is this platform dependent (windows, mac, ..)?**
Windows

**If documentation is required to implement, do you know where to find it?**
https://www.vmix.com/help20/index.htm?WebScripting.html
either use the Web API or the TCP API (TCP is better I think)

**Comment by PerRoine** [comment]
vMix is supported in the developer builds https://builds.bitfocus.io/companion/ 
There are som bugs in there witch we will sort out shortly
