### ISSUE TITLE
Companion Pi should not recommend notifications of new stable releases for regular Companion

### ISSUE THREAD

**Issue by scotttroyer** [bitfocus/companion#2771]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the Companion Pi web GUI there is notification of a new stable release 3.2.2, however that release is only available for the regular version of Companion, not for the Pi version.

This is similar to previous issues, but there are no open issues presently. 

### Expected Behavior

Notifications should be dependent on the installation type. 

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by Julusian** [comment]
It is possible to use the update script to update companion pi to 3.2.2

And there is now an image for it, I forgot to run the script to produce the build
