### ISSUE TITLE
[BUG] Trigger Condition Invert Not Working

### ISSUE THREAD

**Issue by ahfauth** [bitfocus/companion#2773]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Is the "Invert" checkbox supposed to work as a NOT conditional?

It looks like the "Invert" checkbox doesnt work at all.

### Steps To Reproduce

1) Create a new trigger

2) Set on Events "On condition becoming true"

3) Create a condition "obs: Scene in Program"

4) Check the Invert checkbox and select a Scene from OBS.

5) Test by not being on that scene selected and see if the trigger triggers the actions. For me it is not working.

### Environment (please complete the following information)

```markdown
- OS:Linux x64 Ubuntu 22.04
- Browser: Brave / Konqueror
- Companion Version: 3.2.2 Stable
```

**Comment by Julusian** [comment]
Thanks for reporting. This is working in the next beta build
