### ISSUE TITLE
[BUG] Hidden list items when <select> is at the bottom of the screen

### ISSUE THREAD

**Issue by chris-79** [bitfocus/companion#2774]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`<select>` items are mostly hidden when they are at the bottom of the page. UI does not scroll to reveal them; only shrinking the font size makes them visible, using `⌘ -`

Screen Recording:
https://scrshot.chris79.com/SDvmzfHgQjGKnjYbFyQv

### Steps To Reproduce

1. Go to a page where the selector is the last item on the page. I used Triggers
2. Type something to start the filtering
3. Observe only a single item in the list of selections

(See Screen Recording, above)

### Expected Behavior

The selector listing should not drop below the bottom of the page/screen

### Environment (please complete the following information)

```markdown
- OS: macOS 14.3.1 23D60 arm64
- Browser: Brave v1.63.162
- Companion Version: 3.2.2 (3.2.2+6688-stable-7417d2a0)
```

**Comment by Julusian** [comment]
I've applied the patches from https://github.com/JedWatson/react-select/pull/5827 and https://github.com/JedWatson/react-select/pull/5716 and this seems to be behaving better.

This is in the next beta build
