### ISSUE TITLE
[BUG] Keywords not used for search when adding module

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#2775]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In `manifest.json` there are `products` and `keywords` sections.
Keeping `products` short makes things cleaner in the GUI when looking at presets and things.
The list of supported devices or types of devices can be listed in the `keywords` section, but the entries this section don't look like they are being searched in the `add connection` search. 

### Expected Behavior

The search should not only look at module names, it should look at keywords too. (I mean, they are called "keywords", right?) ;-)

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

### Additional context

It LOOKS like it should be searching the keywords, but it doesn't...
https://github.com/bitfocus/companion/blob/6402fb9111c9ba579140a169d5408640f133a79d/webui/src/Connections/AddConnection.tsx#L82-L87

Is this the same properties as in `manifest.json`? e.g. in that file the property is `products` not `product`

**Comment by jswalden** [comment]
https://github.com/bitfocus/companion-module-base/wiki/manifest.json says "Keywords to allow users to more easily find your module by searching", so yeah, seems pretty clear this is expected to work.  I'll verify it doesn't -- searching for "Camera" doesn't bring up the PTZOptics Visca module that has that string in keywords.

**Comment by peternewman** [comment]
It's also broken in the same way on the connections webpage:
https://bitfocus.io/connections

**Comment by Julusian** [comment]
this is fixed now
@willosof can you look into this for the website?

**Comment by MeestorX** [comment]
If you're editing the website anyway, you might want to fix the sorting.
