### ISSUE TITLE
Barco Encore not using the right port

### ISSUE THREAD

**Issue by bramsteenbrugge** [bitfocus/companion#278]
**Describe the bug**
When adding the Encore instance, I get a "Network error: connect ETIMEDOUT" every minute or so.
I can't control the Encore. The status is stuck on "connecting".

**To Reproduce**
Try connecting to a Barco Encore Controller.

**Expected behavior**
Connection OK

**Screenshots**
/

**Desktop (please complete the following information):**
 - OS: MacOS 10.14 (18A391)
 - Browser: Safari 12.0 (14606.1.36.1.9)

**Additional context**
It looks like Companion is trying to connect to the Barco Encore via port 9878. If I use Octopus the default port for connecting to an Encore is 3000. Octopus connects without a problem.

**Comment by willosof** [comment]
Oh.. I'll make the port optional, and set it default to 3000

**Comment by willosof** [comment]
Resolved in ba14234

**Comment by DiViPro01** [comment]
Finally got time to test. The module is not working.
Using the same computer and octopus, everything works fine. using telnet to send the commands, also everything works fine.
Companion succeeds in making a connection, but not in sending the right commands
