### ISSUE TITLE
[BUG] Requires Administrator rights on windows 10

### ISSUE THREAD

**Issue by swamiforlife2** [bitfocus/companion#2794]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On Windows 10 Companion is requiring administrator rights to run the program. 
Is there any to make it work as a standard user?

### Environment (please complete the following information)

```markdown
- OS: Windows 10
- Browser:
- Companion Version:
```

**Comment by dnmeid** [comment]
It does not, maybe you have some policies requiring it.
