### ISSUE TITLE
24.03.14 17:50:30 Instance/Modules: Error loading module from "D:\ssh_woker\com-kommander\companion-module-kommander": Error: Manifest incorrectly references template module 'companion-module-your-module-name'[BUG]

### ISSUE THREAD

**Issue by howcoder** [bitfocus/companion#2799]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I developed my own module based on websocket module, which can be used normally in 3.0.0, but cannot be used in 3.2.2 (3.2.2+6688-stable-7417d2a0). The error is as follows: 24.03.14 17:50:30 Instance/Modules: Error loading module from "D:\ssh_woker\com-kommander\companion-module-kommander": Error: Manifest incorrectly references template module 'companion-module-your-module-name'

### Environment (please complete the following information)

```markdown
- OS:Windows 10
- Browser:Edge
- Companion Version:3.2.2 (3.2.2+6688-stable-7417d2a0)
```

**Comment by Julusian** [comment]
It says the problem in the log snippet you posted:
```
Manifest incorrectly references template module 'companion-module-your-module-name'
```

This was made stricter in 3.2 as it was found that some modules included in the build still included these template values.
