### ISSUE TITLE
Run application directly from source

### ISSUE THREAD

**Issue by ettr** [bitfocus/companion#28]
Hey everyone,
is there a possiblity to run the app directly from the sourcecode?
I tried with npm start but this only runs the empty sceleton.
![screenshot 2018-05-26 um 15 22 41](https://user-images.githubusercontent.com/4245752/40576536-a850e25e-60f8-11e8-8acd-688c08dfd5ee.png)
Would be nice to be able to add some features & contribute to the very nice app.

**Comment by ettr** [comment]
thanks. I would like to but the slack link seems to be broken. I get a message telling me the link is not active anymore...

**Comment by willosof** [comment]
https://join.slack.com/t/bitfocusio/shared_invite/enQtMzY5NTQ2OTA1MjAzLTE3NTQ5NjYyNGVlYTk4ZGYwNTcxZjE4NjEyYzc1N2U2ZjkxOTAyMDFkZDU1MTAzMWYzYzdiY2UxMWJkMGU2MzI

:)
