### ISSUE TITLE
Buttons show active after OSC button press

### ISSUE THREAD

**Issue by cxselph** [bitfocus/companion#280]
Companion-82f0eab

**Describe the bug**
After sending an OSC button press, the button seems to be stuck as if you hold a button down without a release. The latch option is not turned on.

**Expected behavior**
Expect the yellow active state to go away like regular buttons do with a single press.

**Screenshots**
<img width="1191" alt="screen shot 2018-10-09 at 9 39 08 am" src="https://user-images.githubusercontent.com/14942903/46673393-ad2a2f00-cba7-11e8-9e83-60d0c3569729.png">

**Desktop (please complete the following information):**
OSX - 10.12.6
Chrome - Version 69.0.3497.100 (Official Build) (64-bit)

**Additional context**
The OSC button presses don't show up in the log like regular ones do.

**Comment by haakonnessjoen** [comment]
What is configured on the buttons?

**Comment by cxselph** [comment]
I just used presets for setting inputs on preview. I originally saw the issue using osc to trigger my tascam recorders and thought I would see if it did the same thing with another module.

**Comment by cxselph** [comment]
It does it on any button that I trigger regardless of module. I have tried it on my production setup and a clean companion setup, etc... with the same results.

**Comment by cxselph** [comment]
If I physically push the actual button, the yellow active goes away. Thankfully it hasn't affected functionality.

**Comment by haakonnessjoen** [comment]
Ah, you mean remote OSC controlling a button? I am sorry, I misunderstood what you were trying to do.

If you send OSC without arguments, it should work, if not, it is a bug. But if you send int argument, it should be 1 for "Down", and 0 for "Up" on the button.

**Comment by cxselph** [comment]
Yep. Remote controlling. I just send OSC message /press/bank/1/1 just like the hint in the app.

**Comment by willosof** [comment]
Yes, this is actually a feature. But I realize we need that optional for each button :)

**Comment by haakonnessjoen** [comment]
As I have talked about earlier I think it should "trigger" if you call the osc without arguments, but do up/down on 0/1. I can make a fix for it, unless you have something against it @willosof

**Comment by haakonnessjoen** [comment]
In d6d51f4 I have fixed so no argument will trigger the button. But integer argument 1 or 0 will hold the button.
