### ISSUE TITLE
Variable for position of 'this button'

### ISSUE THREAD

**Issue by Coupe70** [bitfocus/companion#2803]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

A variable 'this button' that contains the position of the button the variable is used in (page/row/column).
Or, if this might be not easy to define, a variable 'pressed button' that contains the position of the pressed button.
There are pulldown menus where you can select "This Button" as target, so it seems the information is available, just not exposed as variable for further use.

### Usecases

My use case would be to access the text of a button for further use which is possible as e.g. 
`internal:b_text_2_3_1`, but only with an absolute address.
So this button can't easily be duplicated or moved without breaking the functionality.
That's why I would like to see something like `internal:b_text_$(this_button)` or `internal:b_text_$(pressed_button)`
I'm pretty sure there are other use cases where it's handy to know WHERE a pressed button is.
Not sure about a good format for this variable as in some places `page/row/column` is needed, in my use case it would be `page_row_column`.
So maybe it would be better and more versatile to split it into $this_page, $this_row and $this_column?

**Comment by MarekPro1** [comment]
Same, I want to use variable $(this:page) and row and column in other use cases so it must be a number not "/NA" like it's writing me nowa, I want to send some generic osc that contains the variable of this button and shows as a number.

**Comment by Julusian** [comment]
In 3.3, the `$(this:....` variables are available in a few more places, such as in button text. 
The places this is available will continue to grow over time, and will be indicated by this icon:
![Screenshot from 2024-03-16 11-23-02](https://github.com/bitfocus/companion/assets/1327476/8dd8547d-e586-4716-b803-2cba7ed6906e)

I don't think this needs to be kept open, I don't think it is asking for anything more than is supported today

**Comment by MarekPro1** [comment]
So it will be supported in generic osc?

**Comment by Coupe70** [comment]
@Julusian 
Can these "this" values somehow be grabbed with a "on any button press" trigger?
Seems they are not available in "Custom Variable: Set with expression" and "Custom Variable: Store variable value" as trigger action...
