### ISSUE TITLE
Move "variables" to top level

### ISSUE THREAD

**Issue by mark-epstein** [bitfocus/companion#2810]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

"Variables" would become a top-level menu choice like "Connections," "Buttons," etc.

### Usecases

Variables apply to more things than just buttons, namely triggers and log entries. It doesn't seem right that the variables are 'buried' in the button section.

**Comment by dnmeid** [comment]
@mark-epstein take a look at the tree layout in #2387 
That is what we plan for the future, would that solve your request?

**Comment by mark-epstein** [comment]
Wow that's a lot to read! I will give a preliminary answer so you don't
think I'm ignoring you but it's going to take me several days at least - I
can only dedicate a little bit of time each day to this hobby - to read
through the post and all the comments.

I do very much like what you've done with the menus except please give the
top level icons and a way to collapse them down to just the icons. Real
estate is particularly valuable and I never seem to have enough

But I don't think this quite answers my feature request. I see the
variables associated with the Atem are under that menu item and that's
excellent, but I was aiming for having custom variables at a top level, or
at least not buried under "buttons" because custom variables apply in other
places.

Also I'd prefer if "favourite" were spelled "favorite" 😉 Just kidding of
course, I'm perfectly content living with the language style of the person
doing the work.
