### ISSUE TITLE
Allow changing of browser page/tab title

### ISSUE THREAD

**Issue by jpkelly** [bitfocus/companion#2813]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Allow the browser page/tab title of the admin UI to be edited via the admin UI.
Perhaps use the hostname of the machine companion is running on and/or make the title editable.

### Usecases

In a situation where multiple instances of companion admin are open in different tabs this would make identifying the desired instance easier.

**Comment by Julusian** [comment]
Related to #2498
