### ISSUE TITLE
RAW HEX UDP/TCP command

### ISSUE THREAD

**Issue by ashrafkawasmi** [bitfocus/companion#2814]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

send hex commands to devices 

i tried it with udp/tcp generic with th format
x??x??x??x??

it does not work

**Comment by istnv** [comment]
Try `%` instead of `x`:
`%a0%0a%0d`

**Comment by ashrafkawasmi** [comment]
thanks
working

**Comment by ashrafkawasmi** [comment]
great
