### ISSUE TITLE
[Request] Make entries in connection list fixed height

### ISSUE THREAD

**Issue by lfrisk** [bitfocus/companion#2816]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On the connections page, when one or more connections are either disconnected, error or warning status, the message displayed often resizes the page as it cycles through the text that it is displaying and makes it challenging to click on other instances to edit or make changes.

### Steps To Reproduce

Disconnect a device

### Expected Behavior

Error messages should display in their own line and not push the remaining connections down on the screen, then move them back up. I would suggest adding additional text lines per each instance that can be expanded or contracted manually 

### Environment (please complete the following information)

```markdown
- OS:ALL
- Browser:All
- Companion Version: v3+ (without doing research I am guessing that v3 is when the status previews were added to the connections page (formerly instances), on macOS, Windows and CompanionPi
```

**Comment by mark-epstein** [comment]
FWIW I agree that the constant moving of the page is very annoying. This is true on the horizontal axis as well.

My suggestion would be to populate the status column with only
- green check (connection OK)
- yellow ! triangle (warning)
- red X (connection disabled or status is changing rapidly)

and have the corresponding icon be a hyperlink to more information, maybe a log history only pertaining to that module
