### ISSUE TITLE
[BUG] pages dont load on iOS 12.5.7

### ISSUE THREAD

**Issue by ExnihiloMedia** [bitfocus/companion#2818]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using Companion 3.2.2 (just upgraded from 3.1.2) pages can't be loaded on iOS 12.5.7. Javascript is on in the browser, but Companion doesn't think so. Pages load with a <noscript> error. If this is the price of progress, cool. Just thought I'd report in case it was not intended.

```
<body>
		<noscript>You need to enable JavaScript to run Companion.</noscript>
		<div id="root"></div>
</body>
```

### Steps To Reproduce

Load any Companion page on iOS 12.5.7. Blank page is displayed.

### Expected Behavior

Pages loaded fine in 3.1.2.

### Environment (please complete the following information)

```markdown
- OS:iOS 12.5.7
- Browser:Safari, Chrome
- Companion Version: 3.2.2
```

**Comment by Julusian** [comment]
I can fix this without much difficulty, but it appears to have some rendering issues that make it hard to use. 

So this will work in the betas now.
