### ISSUE TITLE
Module Request: IP CCU

### ISSUE THREAD

**Issue by monoxane** [bitfocus/companion#282]
**Describe the feature**
Iris and white balance for cameras and CCU hardware that supports IP control

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
Will depend on hardware or camera implementation 

**Usecases**
CCU panels are expensive, stream decks are cheap, people don't like spending money, also lets you iris a group of cameras at once.

**Comment by Keksstar** [comment]
And there are A LOT of different CCU protocols..... Sony, Panasonic, JVC, Hitachi, Marshall, etc..... I think you should specify this a little bit more :)

**Comment by monoxane** [comment]
Yea I know there's a lot of them, this is more a task so when I finish my backlog of modules I'll implement some.

**Comment by willosof** [comment]
Closing this until we have a bit more specific ticket :)

**Comment by ZouchaR** [comment]
I would like to be able to network Sony HXC-100 series cameras and send RECALL SCENE commands to specific cameras via network and Stream Deck.  
[4431827021.pdf](https://github.com/bitfocus/companion/files/3500028/4431827021.pdf)
