### ISSUE TITLE
GET value of a custom-variable via new HTTP API

### ISSUE THREAD

**Issue by LHasenbein** [bitfocus/companion#2820]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have tested the Experimental 3.99.0+6806. I want to GET the value of a custom-variable via HTTP API like it's described in the doc. I've tried it with Javascript and php. I always get an html page back:

<!doctype html>
<html lang=\"en\">
	<head>
		<meta charset=\"utf-8\" />

		<link href=\"/img/icons/256x256.png\" rel=\"shortcut icon\" />

		<link rel=\"manifest\" href=\"/manifest.json\" />
		
		<meta name=\"theme-color\" content=\"#000000\" />
		
		<link rel=\"apple-touch-icon\" sizes=\"16x16\" href=\"/img/icons/16x16.png\" />
		<link rel=\"apple-touch-icon\" sizes=\"32x32\" href=\"/img/icons/32x32.png\" />
		<link rel=\"apple-touch-icon\" sizes=\"48x48\" href=\"/img/icons/48x48.png\" />
		<link rel=\"apple-touch-icon\" sizes=\"128x128\" href=\"/img/icons/128x128.png\" />
		<link rel=\"apple-touch-icon\" sizes=\"256x256\" href=\"/img/icons/256x256.png\" />

		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0 , maximum-scale=1.0, user-scalable=0\" />
		<meta name=\"language\" content=\"en\" />
		<meta name=\"google\" content=\"notranslate\" />

		<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />
		<meta http-equiv=\"Content-Language\" content=\"en\" />

		<meta name=\"theme-color\" content=\"#000000\" />
		<meta name=\"description\" content=\"Bitfocus Companion - Admin\" />
		<title>Bitfocus Companion - Admin</title>
		<script type=\"module\" crossorigin src=\"/assets/index-CbmXG7xe.js\"></script>
		<link rel=\"stylesheet\" crossorigin href=\"/assets/index-TlWH-Hzx.css\">
	</head>

	<body>
		<noscript>You need to enable JavaScript to run Companion.</noscript>
		<div id=\"root\"></div>
	</body>
</html>

Maybe it's my fault. But I tried it as described in the documentation.

### Environment (please complete the following information)

```markdown
- OS: macOS 13.6.4
- Browser: Safari 17.3.1 / Chrome 123.0.6312.87
- Companion Version: 3.99.0+6806
```

**Comment by dnmeid** [comment]
Please give the complete HTTP request you have used.

**Comment by LHasenbein** [comment]
@dnmeid 

<script>
const url = 'http://localhost:8888/api/custom-variable/timecode/value';

fetch(url)
    .then(response => {
        if (!response.ok) {
            throw new Error('Netzwerkantwort war nicht ok');
        }
        return response.text();
    })
    .then(data => {
        console.log('Antwort:', data);
    })
    .catch(error => {
        console.error('Fehler beim Abrufen der Daten:', error);
    });
</script>

**Comment by dnmeid** [comment]
I can reproduce this bug.

**Comment by dnmeid** [comment]
We have a default route which serves the home page if no other route is matched. https://github.com/bitfocus/companion/blob/a0ad601263b9600fad18a0dff2d4b5d947e18b37/companion/lib/UI/Express.js#L139
The error seems to be that this route is matched before the the api route can match. I don't know why this is happening. All legacy api routes are matched before the default route and all http POST routes are matched before the default route.
The route in question is the only GET route for the new api.

**Comment by dnmeid** [comment]
Ok, the reason is, that the new api routes are included here https://github.com/bitfocus/companion/blob/a0ad601263b9600fad18a0dff2d4b5d947e18b37/companion/lib/Service/Controller.js#L42 after the routes of the web ui.
The default route of the web ui only handles get methods, so all post requests of the new api are fulfilled but the default get will match before any api get route can match.
@Julusian you did the way of binding the new api router. Is there any reason for that or can we change it to the same way the legacy api is included?

**Comment by dnmeid** [comment]
Ah, I see the tests are failing. Didn't remember that there are unit tests for the api and they are broken now.
