### ISSUE TITLE
Custom Variable within a Button

### ISSUE THREAD

**Issue by josh-justjosh** [bitfocus/companion#2827]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

At present there can be a lot of repetition within the creation of buttons. I'd like to have the ability to have input fields that can then be used throughout a button's actions and feedbacks. Perhaps within the button editor, there would be a place to input the variable. Potentially reusing the existing Custom Variables UI either in the top area of the button editor (see mock up below) or as a tab with Actions and Feedbacks.

![In Head](https://github.com/bitfocus/companion/assets/54246291/464b8919-fc0d-4909-ba3b-00b044de4720)

This kind of links with https://github.com/bitfocus/companion/issues/1909 where people are suggesting introducing variables of the button being accessed as $(button:variable)

Obviously, a current workaround is to just create custom variables in the existing variables interface. However, that creates a lot of clutter and isn't as streamlined as being linked specifically to the button

### Usecases

I primarily use companion with vMix. When programming buttons, I will often start with one and copy and paste it to create buttons for different inputs. I will often be setting the input number in the button's text, one or two actions and then one or two feedbacks. When copying this button for different vMix inputs, each of these fields needs updated. It'd be useful to have the ability to just have one place per button to change a variable that all the fields referred to.

**Comment by dnmeid** [comment]
Although this request is not 100% the same as #1909, I think it is close enough. Especially if you see that the comments there already suggest extending local variables to be also settable and being variables not just reflecting other state.
So I'm closing this as a duplicate and would encourage you to rather add requests for extended functionality to #1909.

**Comment by josh-justjosh** [comment]
Thanks for your comments, I'll throw a summary in #1909 for easier reference
