### ISSUE TITLE
Trigger via OSC sets the button in a state "yellow" but no press

### ISSUE THREAD

**Issue by JeffreyDavidsz** [bitfocus/companion#283]
I'm sending OSC from qlab 
/press/bank/2/1
The button "lights" up yellow bar on top. But I need to manually press the button for action to happen.

Could this be an adjustment comming from the up/down keypress?

**Comment by cxselph** [comment]
Have you tried tbe latest build? Similar issue was fixed in 280 using OSC and qlab

**Comment by willosof** [comment]
Duplicate of #280

**Comment by willosof** [comment]
Or. I might have been too fast on that one.

**Comment by JeffreyDavidsz** [comment]
check latest build works! thanks guys, still figuring out how to control streamdeck from EMT (only sends UDP instead of OSC, need some header info I guess)

**Comment by willosof** [comment]
Seems to have magically fixed itself. Closing.
