### ISSUE TITLE
[BUG] Some buttons don't draw

### ISSUE THREAD

**Issue by AHub88** [bitfocus/companion#2832]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

I have updated from 3.1.2 to 3.2.2.

Everything is normal up to page 8. 
From page Nr. 8 onwards, ALL buttons have disappeared.

BUT only the labels are missing. 
The Press Actions are still there.

![Clipboard_04-10-2024_03](https://github.com/bitfocus/companion/assets/99470230/18508b0a-70f1-4114-8c86-c53560621e3b)

Can you please help me?

Andi

### Environment (please complete the following information)

```markdown
- Companion Version: 3.2.2 and 3.3.0
```

**Comment by AHub88** [comment]
A downgrade solved the problem (temporarly).
But I would still like to solve the problem.

**Comment by Julusian** [comment]
I remember someone else having this issue, which was concluded to be the graphics rendering 'crashing' when encountering certain unicode characters in the text.

I have a feeling a fix wasn't found for this yet, they solved it by removing the problematic unicode characters and restarting companion. The proper fix could be #2785, which needs more testing

**Comment by AHub88** [comment]
THX, yes it was a unicode character.
After a restart the problem was solved.

**Comment by Julusian** [comment]
This is fixed in the 3.4 beta builds

**Comment by Julusian** [comment]
This is resolved in the latest release (v3.4.0)
