### ISSUE TITLE
Push&rotate action

### ISSUE THREAD

**Issue by markusnygard** [bitfocus/companion#2836]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

With Loupedeck Live (and possible Streamdeck+) I would be able to use the knobs with PTZ-kameras. And since there isnt a funtion in the controllers to stop action when you stop rotating the next best thing is that a function is working when push&rotate and release action is stop.

### Usecases

Module sony visca:
functions where it would be useful: pan, tilt, zoom, focus, iris, shutter, white balance etc:
example: focus: you add a combined action rotate left and push to be focus near, when the knob is realesed  there is a function focus stop

**Comment by dnmeid** [comment]
You can program stuff like this today with existing functionality. E.g use push to switch to step 2 and release to step 1. Then use your desired rotary actions only on step 2.
