### ISSUE TITLE
[BUG] XAIR 18 - after re-powering the connection is lost

### ISSUE THREAD

**Issue by babarblanco** [bitfocus/companion#2839]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After re-powering the Pi, companion cant reconnect to Behringer XR 18 and to my sonos. I use 11 devices. Apart from XR18 and Sonos are all other from Blackmagic.
I can reconnect the devices by simply click on them in the connection tap and save without any changes. they appear instantly.

### Steps To Reproduce

1. turn off power (companion)
2. turn on power
3. 

### Environment (please complete the following information)

```markdown
- OS: Pi
- Browser: (it is not a browser issue)
- Companion Version: 3.2.2 + 6688
```

**Comment by Julusian** [comment]
This sounds like issues with some modules not with companion itself.
Please open issues in the repositories of the modules with issues.
