### ISSUE TITLE
Analog Way - Midra. Freeze Screen (all layers)

### ISSUE THREAD

**Issue by Akibakki** [bitfocus/companion#285]
Hi.

If you use the AW Gateway, so that you can connect companion and RCS2, the Un-Freeze Screen does not work if you used RCS2 to Freeze Screen. You have to first Freeze and then Un-Freeze.
Seems the companion toggles which command to send.

Companion v1.1.1 installed on windows 10 64bit

**Comment by dnmeid** [comment]
This is the normal behaviour of the device.
From the manual: 
Freeze all layers of a single screen, coherence is not maintained with FREEZE_ALL command
