### ISSUE TITLE
Improve UI by truncating long variables

### ISSUE THREAD

**Issue by phuvf** [bitfocus/companion#2852]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

**A small UI improvement:**

When variables are short, the variable page looks fine - but once a big block of text is assigned to a variable things get difficult to read.

It'd be nice to truncate variables at a fixed length, perhaps with an accordion element to show the full value if required.

Here's an example of it working OK:

![image](https://github.com/bitfocus/companion/assets/3513020/1622efa7-2a9e-488c-9f0b-3a375b0c6d99)

And with long text causing layout issues:

![image](https://github.com/bitfocus/companion/assets/3513020/3393bab2-c2ec-4100-9eea-1e1210ccbebc)

### Usecases

Would help when working with variables, as when programming, the variable name is often more important than the content.

**Comment by Julusian** [comment]
Resolved by #3016

**Comment by phuvf** [comment]
This commit #3016 does achieve a tidying-up of long variable UI elements, but does this at the expense of being able to view and copy the full variable value, which can be useful during dev/test work.

Separately, there's also some ambiguity in the copy action, which currently copies the variable name, despite being placed next to the variable value.

I suggest some like the attached, which keeps the truncated variable value as a default with the option to display the full value via the "More" link (this can just be a bit of JS UI manipulation).

I've also added an additional copy link so it's clear whether the user is grabbing the variable name or variable value.

I'd make these changes myself, but my react knowledge is pretty poor.

![image](https://github.com/user-attachments/assets/ca8c9be8-4347-408c-93f7-5e9d5173dd03)

**Comment by greyshirtguy** [comment]
yay! Companion 3.4 has all your suggestions @phuvf 
![image](https://github.com/user-attachments/assets/54cccddc-00e6-41aa-b8f7-0c04e60aa9e3)
