### ISSUE TITLE
Web buttons 

### ISSUE THREAD

**Issue by Akibakki** [bitfocus/companion#286]
Hi

The buttons in the web view do not scale the text correctly, if the button uses auto font size. 

and 

Instance feedback from BMD-Videohub (Change background color) does not affect the Web-buttons.

Companion v1.1.1 on Windows 10 64bit

**Comment by haakonnessjoen** [comment]
The web-buttons are really more at a "Alpha" stage, than "Beta" which it says in the menu. So that is correct, it is just not done yet. It will probably not be included in 1.2.0 release, I'm afraid.

**Comment by willosof** [comment]
This is an unfinished and frankly unusable system as of yet like @haakonnessjoen says, I'm closing this ticket until we have something proper to show you guys :) Web buttons have also been removed from the menu.
