### ISSUE TITLE
[BUG] Connection with ShowCockpit

### ISSUE THREAD

**Issue by basicriska** [bitfocus/companion#2864]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm trying to link companion with showcockpit, so that I can use a midi controller to trigger buttons in companion. However when I try to connect, I get a warning saying:
`24.05.14 16:55:51 UI/Handler: Error in client handler 'pages:subscribe': TypeError: n is not a function TypeError: n is not a function
    at C:\Program Files\Companion\resources\main.js:2:3043326
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

And this warning when disconnecting showcockpit:
`24.05.14 16:55:51 UI/Handler: Error in client handler 'pages:unsubscribe': TypeError: n is not a function TypeError: n is not a function
    at C:\Program Files\Companion\resources\main.js:2:3043326
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

Does anyone know how I can fix this, or has anyone seen a post about this issue before?

### Expected Behavior

I expected the log to say something about the fact that it's connected, and the ability to acctually trigger something from showcockpit

### Environment (please complete the following information)

```markdown
- OS: Windows 11
- Browser: Chrome
- Companion Version: 3.2.2 (3.2.2+6688-stable-7417d2a0)
```

**Comment by Julusian** [comment]
Repeated from slack:
> What this error is saying is that when a client (in this case showcockpit) send a pages:subscribe message, it was not formed correctly and did not provide a function to send the response to.
So it looks like showcockpit is doing something wrong, and you will have to ask them about this issue
