### ISSUE TITLE
[BUG] Stream Deck Disconnecting On New Models

### ISSUE THREAD

**Issue by aluis02** [bitfocus/companion#2874]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When trying to connect companion to a Stream Deck XL through a KVM it is not connecting. Have tried directly to the computer and it works, but through KVM it will connect and disconnect continually (does not stay connected for more than a second). Was tested with an older version of Stream Deck XL and worked fine through KVM.

### Steps To Reproduce

1. Stream Deck XL is connected to KVM via USB-C to USB-A.
2. Start Bitfocus Companion (v3.0.0)
Stream Deck XL Firmware Version: 2.01.002

### Expected Behavior

Stream Deck is expected to connect to Companion without disconnects.

### Environment (please complete the following information)

```markdown
- OS: Mac OS (Version 14.4.1)
- Browser: Safari (Version 17.4.1)
- Companion Version: (v3.3.0)
```

**Comment by Julusian** [comment]
My first guess would be that this is a power issue, with the KVM not providing the streamdeck enough power to operate

**Comment by aluis02** [comment]
I have tried using a power supply with the KVM and still got disconnects. I plugged in an older Stream Deck and it worked fine, so I'm assuming it has something to do with the firmware of the stream deck.

**Comment by Julusian** [comment]
They may have changed something in newer firmware, but I'm hoping they haven't as I don't have a recent XL to use to figure out the change.

Could you double check that the streamdeck works if connected directly, instead of via the KVM. Just to rule out that as being an issue.
Is there anything in the companion log about this streamdeck?

Otherwise, yeah it could be something firmware, but I don't know how to debug that right now

**Comment by Julusian** [comment]
As there aren't more reports of this, it very much sounds like an issue with your particular environment/hardware.
So unfortunately I don't think there is anything we can do besides the usual debugging ideas.
