### ISSUE TITLE
internal: Button: Trigger press and release reffred FROM TEXT including STEP

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion#2878]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Now is possible to locate button by address like "35/0/6". When this button has multiple steps I would like call its inlcuding a STEP number: "35/0/6.2"

Mockup: 
![image](https://github.com/bitfocus/companion/assets/22023099/0d3bcff7-c5ab-4c1b-b260-4ab3da4d61f2)

It will call the button 35/0/6 and run STEP 2

It is simple shortcut for two commands:
![image](https://github.com/bitfocus/companion/assets/22023099/62472c18-d667-47cc-a342-5ffea6130c23)

### Usecases

Simplifies calling buttons with multiple steps

**Comment by dnmeid** [comment]
This would be misleading.
1. You don't know if just the actions of the named step are triggered or if the button is also set to that step.
2. The name of the yction would need to be "Button and optional step: Trigger press and release"
As there is an eisting action to switch to a step, your usecase can be achieved with two actions which each have a well defined narrow scope.
