### ISSUE TITLE
Spyder ASC Command

### ISSUE THREAD

**Issue by troyliptakgrilli** [bitfocus/companion#288]
Hello, bitfocus team! 

My name is Troy Liptak-Grilli and I am a video engineer who does light programming and development. I am on a show with Joe Cassara and he's got companion and a Spyder X80 and the ASC command is not working properly. I actually built my own hardware based controller that controls (among other things) Spyder and I used ASC as the Christie equivalent as "take" as well. I downloaded the spyder module of companion to take a look and unfortunately I am ignorant to Github and cannot figure out how to download everything, modify code, and then test it. However, looking at the code, I could make suggestions based on my working code from my controller box. 

First off, I've never utilized any additional variables with the ASC command. I believe the average Spyder operator wouldn't want to specify those variables and to simplify the code and get it working I would remove all variables to the command. Secondly, I noticed you were also sending a carriage return which is unnecessary. The command (formatted for Python) that I use is:
spyder\0\0\0\0ASC
That's it! Just the command, no spaces, no carriage return. So I believe if you deleted everything except setting the "cmd" variable and ditched the carriage return when you send the command, that should fix it.
We'll be in the room with the x80 for the rest of today, I wish I could modify companion myself to test this but alas I cannot figure it out. If You have any advice on how I might modify and test on-site I would love to hear! This is a wonderful software you've developed and I would love to help if at all possible.

**Comment by willosof** [comment]
https://github.com/bitfocus/companion/wiki/Module-Development

Join us on slack :-)

**Comment by haakonnessjoen** [comment]
I am not the author of the spyder module, nor have I ever touched a spyder. But I see you are mentioning that ASC does not need arguments. But that is also supported in the module. If you do not fill out the cueNum parameter (or it is set to 0), it sends just spyder\0\0\0\0ASC. No spaces.

I guess the carriage return is only needed for serial communication, but I would think it wouldn't care about it, as people have used this module without problems? We could try to remove it, if you mean that this fixes a problem.

**Comment by haakonnessjoen** [comment]
Removed carriage return in latest build. Please test if this helps :) Remember to set Cue number to 0 which will make it not send argument.

**Comment by willosof** [comment]
Any update on this? An I close the ticket?

**Comment by dnmeid** [comment]
Last time I worked with the X80, the ASC command did work as intended.
