### ISSUE TITLE
[BUG] Companion HTTPS Web Server

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion#2884]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

HTTPS is not running

### Steps To Reproduce

1. Goto: Settings
2. Find: HTTPS Web Server
3. Set: Common Name = universe.maya.mic (my local domain, that is working well)
4. Certificate Expiry Days: 365
5. Press: GENERATE
6. HTTP Web Server = ENABLED
7. Restart Companion
8. go to http://universe.maya.mic:8000/ is still working
9. go to https://universe.maya.mic:8443/ it is not working. Borwser says, that connection is not seruce
![image](https://github.com/bitfocus/companion/assets/22023099/d8d97712-b66f-4f17-a919-484d5aa92de8)
![image](https://github.com/bitfocus/companion/assets/22023099/4d698c3f-afe5-4d55-a242-4c70e735426a)

### Expected Behavior

Set correct IP in your DNS for domain UNIVERSE.MAYA.MIC or change domain to your own.

### Environment (please complete the following information)

```markdown
- OS: Win10 last update
- Browser: Ochrome last update
- Companion Version: 3.3.0
```

**Comment by Julusian** [comment]
This is expected. Your browser will not trust this generated certificate unless you manually install it in a way that it will be able to load/trust.
