### ISSUE TITLE
Logarithmic Functions in Expressions

### ISSUE THREAD

**Issue by michaelbaae** [bitfocus/companion#2907]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

To be able to do log(x) with expressions.

### Usecases

In cases where you send manual values to a device like MIDI pitch control (0 to 16383), OSC and would like to calculate the logarithmic db value from the linear value.

**Comment by Julusian** [comment]
`log` and `log10` have been added in the beta builds
