### ISSUE TITLE
Inherit long push and release by action "internal: Button: Trigger press and release"

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion#2912]
### Is this a feature relevant to companion itself, and not a module?

- [x] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

How to pass information about a long press of a button? Two solutions:
1. the button itself would have the property "INHERIT LONG PUSH/RELEASE" if there was some function INTERNAL: BUTTON: TIRGGER* among the actions
2. the INTERNAL: BUTTON: TIRGGER* action itself would have an "INHERIT LONG PUSH/RELEASE" switch.

In both cases, activating this option should disable the features associated with DURATION GROUP.

### Usecases

I use the STREAM DECK PEDAL, to which I dynamically enter a button (page/row/col) to press from the options on the STREAM DECK.

If the target button supports DURATION GROUP, then dynamic button assignment works only for short press and ignores long press.

**Comment by Julusian** [comment]
I'm not following what you are asking for here.
Are you saying that the `INTERNAL: BUTTON: TIRGGER* ` action that is run when you press the pedal isn't executing long presses as you expect. Or are you saying that it is and you don't want it to be.

If the first, it looks to be working for me if I set a `internal: Button: Trigger press` in the press actions and a `internal: Button: Trigger release` in the release actions

**Comment by Suenee** [comment]
> I'm not following what you are asking for here. Are you saying that the `INTERNAL: BUTTON: TIRGGER* ` action that is run when you press the pedal isn't executing long presses as you expect.

Yes I expect, that it will run LONG PRESSES, but it is not.

---
My left pedal is set on this button,
![image](https://github.com/bitfocus/companion/assets/22023099/18b62b4b-2878-4c88-8be1-7509b680f31a)

 that is forwarding action on ATEM. Short release means just preview (it works fine). Held for 500ms actions means program (it does not work).
![image](https://github.com/bitfocus/companion/assets/22023099/866561f8-d6ee-4dab-8a6b-f74235378dca)

**Comment by Julusian** [comment]
right yeah so you need to set it up so that the pedal uses separate actions for the press and release
![image](https://github.com/bitfocus/companion/assets/1327476/eaa18041-bdb9-4cec-bfbb-8c4e1dbd3986)

Maybe we could make it be propogated 'automatically' but I don't think that would be simple to do so I don't think is worth the effort when you can already get the same behaviour by adding a release action
