### ISSUE TITLE
Rotate surface independenly of buttons

### ISSUE THREAD

**Issue by slords** [bitfocus/companion#2914]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

It would be nice to have separate rotation controls for the surface and the buttons.  Then you could have a surface take whatever section of the grid it wanted in any orientation but keep the button rotation in an orientation that makes sense for that surface.

### Usecases

I'd like to combine a streamdeck xl and a normal streamdeck in a layout that has the XL in the upper left and the normal in the upper right but rotated 90 degrees.  I'd also like to keep the normal streamdeck in the horizontal layout.  If I use rotate then it gives me the button placement correctly but all the button labels are rotated 90 degrees and I have to turn the streamdeck vertical in order to read the labels correctly.

**Comment by Julusian** [comment]
I'm not sure I follow what you are asking for.
Could you provide a photo/mock up showing how you want to have your streamdecks arranged, and what regions of the grid they should occupy.

We already have 2 rotation modes, the old one which rotated just the buttons (which I am tempted to remove one day), and the new one which rotates everything.

**Comment by slords** [comment]
<img width="943" alt="Screenshot 2024-06-14 at 8 56 01 AM" src="https://github.com/bitfocus/companion/assets/140670/5c1468c6-aac9-4723-b7ee-7c93e269d9a5">
<img width="1403" alt="Screenshot 2024-06-14 at 8 56 15 AM" src="https://github.com/bitfocus/companion/assets/140670/65d149fc-4df6-479b-a41e-65aade492ef4">
<img width="500" alt="Screenshot 2024-06-14 at 8 56 39 AM" src="https://github.com/bitfocus/companion/assets/140670/d5fe4d0e-15d2-453b-8a7e-ff62ba7430d1">
<img width="498" alt="Screenshot 2024-06-14 at 8 56 57 AM" src="https://github.com/bitfocus/companion/assets/140670/ecda7f0e-0766-4d8c-b52e-6214116925b4">
![PXL_20240614_145726875 MP](https://github.com/bitfocus/companion/assets/140670/32a6a0a2-e0de-4a61-b5db-9a211d9a129b)

**Comment by slords** [comment]
![PXL_20240614_145726875 MP](https://github.com/bitfocus/companion/assets/140670/6b8bf0fb-5853-40d8-8542-68036a0b7a28)

**Comment by slords** [comment]
The emulator displays what I'm wanting to see.  The streamdeck has the buttons rotated.

**Comment by dnmeid** [comment]
I see what you want to do, but I don't see why that would be useful. The button layout now is only rotated in the editing grid. Is there a reason you want it that way in opposite of just having the 5x3 stream deck unrotated and making the grid two colums larger?
A actual working solution would be to make the grid 5 columns wider, then set up your real buttons in the way you have drawn and besides that add "recerence buttons" in the unrotated layout. The reference button just points to the actual button and mimics the style. The real stream deck would be offset to the reference buttons.

**Comment by Julusian** [comment]
I'm going to close this, as I think this is still lacking a justification on why this should be done.
The current rotation modes are designed to make it easy to figure out which button is which when put on a streamdeck, and this is proposing a harder to understand mode. As we want to avoid making things overly complex for users, we don't see the benefit to supporting this
