### ISSUE TITLE
[BUG] Navigate back in group not working correctly

### ISSUE THREAD

**Issue by slords** [bitfocus/companion#2915]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you have a group with multiple surfaces and try and navigate through multiple levels of pages the Surface: Set to page going back a page doesn't work if using both surfaces to navigate.

### Steps To Reproduce

1. Create group with multiple surfaces
2. Create buttons with Surface: Set to page going to different pages (1->2, 2->3, 2->4, 3->5, 4->6)
3. On each of the sub-pages place a Surface: Set to page with current surface and back

Navigation using a single surface at a time works like it should.  However, if you navigate from 1->2 using one surface and then 2->3 on a second surface then the back behaves differently on each surface.  One will take you back to the first page and the other will take you back to the previous page.  

Also if I change the back to reference the group name instead of current surface nothing happens.  I can see the current page variable changes to the previous page but the surfaces don't update where they are pointing.

### Expected Behavior

Surface: Set to page pointing to back will work correctly for the group regardless of which surface is used to navigate back.

Surface: Set to page set to back and referencing a group name will change the surfaces in that group.

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by Julusian** [comment]
Thanks for reporting, this is fixed in the next beta
