### ISSUE TITLE
Ability to record a delay time within the Action Recorder

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#2929]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

As per https://github.com/bitfocus/companion/issues/2926#issue-2366845303
Please add the ability to include a delay value for each action recorded within the Action Recorder.

### Usecases

A highly-requested feature from users of my modules is the ability to do slow changes, cross-fades and so on. The best way to implement this would be with the recording of the delays between actions. With the generic MIDI module, this "learn over time" ability that's already part of all DAW software, is expected by users, and most are surprised when they find it's not possible.

**Comment by Julusian** [comment]
I was about to add this, but am wondering if it will behave sensibly given that a button could be in relative delays mode or not.

**Comment by MeestorX** [comment]
I think it's pretty safe ATM, considering only a few modules support the action recorder. I would say just add the delay value for now, not worrying about whether it's relative or not ATM.
A further enhancement would be to allow the actions to be added to a preset, then all settings could potentially be available, including relative/absolute delays. TBH, I'm not really a fan of only being able to add actions to an existing button.

**Comment by Julusian** [comment]
Yeah I've done this and added in the jsdoc typings a warning about the interpretation being inconsistent.
For now my recommendation is to produce relative delays and expect users to switch to relative delays. That will fit better into the future when we can interpret this consistently, and will be easier to generate (for absolute, what should the start point be, considering the user can clear the recorded list arbitrarily)

**Comment by MeestorX** [comment]
Nice! I look forward to giving it a whirl. TY!

**Comment by MeestorX** [comment]
Ok, I finally found some time to work on my code and give this a try. However, I can't seem to add `delay` as a parameter.
How do I implement this?
```
	addToActionRecording(deltaTime: number, msg: MidiMessage): void {
		const args = { ...msg.args, useVariables: false }
		if (args.channel !== undefined) args.channel++
		if (args.number !== undefined) args.number++
		this.recordAction(
			{
				actionId: msg.id,
				options: args,
			},
			`${msg.id} ${this.getValFromMsg(msg).key}` // uniqueId to stop duplicates?
		)
	}
}
```

**Comment by MeestorX** [comment]
@Julusian

**Comment by Julusian** [comment]
@MeestorX it should be in
```
		this.recordAction(
			{
				actionId: msg.id,
				options: args,
				delay: 12345
			},
			`${msg.id} ${this.getValFromMsg(msg).key}` // uniqueId to stop duplicates?
		)
```
Youll need to be using v1.9.0-3 of the module-base library

**Comment by MeestorX** [comment]
So, "@companion-module/base": "~1.9.0" or "@companion-module/base": "^1.9.0"?

**Comment by Julusian** [comment]
Either.
I've just published 1.9.0 of that library, it may not have found it with those before

**Comment by MeestorX** [comment]
@Julusian

**Comment by Julusian** [comment]
![image](https://github.com/user-attachments/assets/2f60caea-6a88-4594-9b39-544dfdea7ed6)
this is my test module code, and I'm getting a stream of random delay values

**Comment by MeestorX** [comment]
Thank you for checking.

Updated to the latest beta and now it's working. I thought updating module/base would be all that was needed, but I guess it needed a main Companion update too.
Sorry about that!

**Comment by MeestorX** [comment]
Would it be possible to add a toggle switch on the Recorder page to enable/disable delay capture? It would make more sense than having it as part of the module config. Then a boolean can be part of `recordAction()` like:
```
this.recordAction(includeDelay,
{
  actionId: msg.id,
  options: args,
  delay: (includeDelay) ? deltaTime : 0,
},
uniqueId
)
```
Or something like that...
