### ISSUE TITLE
Allow Action Step Name and Action/Feedback Headline to be defined in Presets

### ISSUE THREAD

**Issue by phillipivan** [bitfocus/companion#2931]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

At the moment it seems neither the Action Step Name, nor the Action or Feedback Headline can be defined in presets.

As discussed here:
https://bitfocusio.slack.com/archives/CFG7HAN5N/p1719306298683009?thread_ts=1719299390.113979&cid=CFG7HAN5N

### Usecases

Better labeling of preset actions to make them more user friendly.

**Comment by Julusian** [comment]
This is done in the betas

**Comment by phillipivan** [comment]
@Julusian unless I am missing something, it looks like the linked commit addresses the action/feedback headline, but not the action step name. Is that correct?
