### ISSUE TITLE
Ability to run programs/scripts on Windows to trigger macros

### ISSUE THREAD

**Issue by cerspense** [bitfocus/companion#294]
It would be very useful to be able to have a button trigger a certain program/script to run on the host computer. 

This way, users could extend the functionality of Companion using programs like AutoHotKey or other custom programs to perform sophisticated macros and integrate with unsupported hardware. Using macros, you can execute hotkeys and series of hotkeys to extend the functionality of media server applications and make it easier to navigate gui's, set up shows and create content.

**Comment by willosof** [comment]
We will always require a helper application and never bind any functionality to the computer running the companion daemon. For now, octopus helper is the one people use, and we may make our own one day with more functionality.
