### ISSUE TITLE
PPT Remote Show Control - Problem with filenames an directory names

### ISSUE THREAD

**Issue by robertskiba** [bitfocus/companion#295]
**Describe the bug**
In the module "PPT Remote Show Control", there's a possible problem with files and directory names if they contain special characters (like german umlauts) or spaces. I don't know if it is a problem of the module or of the PPT Remote software on the powerpoint side.

**To Reproduce**
1. Use any command in the module e.g. to remotely open a PPT presentation. The presentation name or the complete directory name need to have spaces or special characters to reproduce the problem. 

**Expected behavior**
The filename and directory tree name should not affect the possibility to open PPT files remotely.

**Comment by DaveShep** [comment]
Issue is with Remote Show Control. Have changed to UTF8 to correctly support non ASCII chars for you European types out there. Couldn't see an issue with spaces in file name or directory name. Will post again when patch is available (or will announce in slack if this get closed).

**Comment by DaveShep** [comment]
Patch is live http://www.irisdown.co.uk/rsc.html
Feedback welcome

**Comment by robertskiba** [comment]
Thänks däve for the prömpt pätch! 🤣

**Comment by haakonnessjoen** [comment]
@robertskiba could you test this, and close the issue if it works?

**Comment by robertskiba** [comment]
@haakonnessjoen 

Yes, just tried it and I  can confirm that everything works fine now with the current version of PPT Remote Show Control. So it doesn't seem to have been a problem of companion.
