### ISSUE TITLE
Installation as non-admin

### ISSUE THREAD

**Issue by DavidTNguyen** [bitfocus/companion#2953]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

My company doesn't grant local admin right (LAR) on their issued Windows 10/11 machines. I'd like to be able to install Companion in user mode while retain full functionality. Is it possible? 

### Usecases

My company doesn't grant local admin right (LAR) on their issued Windows 10/11 machines. I'd like to be able to install Companion in user mode while retain full functionality. Is it possible?

**Comment by Julusian** [comment]
This might work in the latest beta build (7118), but the installer still wants to install a vcruntime, which I think needs admin privileges to do. I am not 100% sure if we still need that though, or if this will be a problem for you.

**Comment by Julusian** [comment]
I believe this is now possible with the beta builds
