### ISSUE TITLE
Contour ShuttleXpress - Improve integration

### ISSUE THREAD

**Issue by yasdfgr** [bitfocus/companion#2956]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I own a Contour ShuttleXpress and tryed to use in Companion.
I imported the page template (provided in companion getting started) and first the mapping was wrong.
So i looked at the log and modified the page slightly. And thats whats working now.

![i_view64_k3wCw4G9Vi](https://github.com/user-attachments/assets/a63bf4d8-b724-4f2e-aa75-74ff38a0cb64)

In the log i can see, that i get a event on every hardware input, but the shuttle ring does not work on page.
[CompanionPi_companion_log_20240718-0933.csv](https://github.com/user-attachments/files/16281014/CompanionPi_companion_log_20240718-0933.csv)

Only to get sure, that i understood it:
Is there a fixed mapping between hardware inputs and buttons on a page?
Maybe the mapping in the file ConturShuttle.js should be improved. 

```
const contourShuttleXpressInfo = {
	// Treat as:
	// 3 buttons
	// button, two encoders (jog and shuttle), button
	// Map the encoders in the same position (but a different row) for consistency and compatibility
	totalCols: 4,
	totalRows: 2,

	// TODO(Someone with hardware): This mapping is guesswork and hasn't been tested
	encoders: [5, 6],
	buttons: [4, 0, 1, 2, 7],
}
```

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version: 3.3.1 (3.3.1+7000-stable-bf9ef50e)
```

**Comment by Julusian** [comment]
There is a bug in the logging of rotary events, the log says 1/2/1 but it is supposed to say 1/1/2
If you try moving your shuttle button there, does that work?

**Comment by Julusian** [comment]
I am pretty sure that my comment above will resolve your issue.
Let me know if not and this can be reopened

**Comment by yasdfgr** [comment]
Yes, that was helping - event is fired on button 1/1/2.
