### ISSUE TITLE
[BUG] Triggers wont (Append to existing)

### ISSUE THREAD

**Issue by samuel2nd** [bitfocus/companion#2959]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm not positive this is a bug or miss understanding, could be a feature request.
I have a set of triggers in my config that I have exported, I would like to import (append to existing) them to a new existing connection. when performed i get (import failed : Trigger already exist.) i do not want to lose the triggers to their current connection, just duplicate them all to a new connection without having to do them individually. 

### Steps To Reproduce

1.export triggers. 2.import triggers 3.change connection under select connection. 4 select import (Append to existing.

### Environment (please complete the following information)

```markdown
- OS: Windows
- Browser: chrome
- Companion Version: 3.3.1
```

**Comment by Julusian** [comment]
This is fixed in the next beta build
