### ISSUE TITLE
Change Blackmagic SmartScope display modes

### ISSUE THREAD

**Issue by sondrearnsethjacobsen** [bitfocus/companion#296]
**Describe the feature**
As of now the Blackmagic SmartScope code only allows for adjusting the monitor's brightness, contrast, saturation and tally light. I would like to see the ability to be able to change the monitor's display modes, such as wave, scope, RGB parade, audio meter and so on, just like the software allows. Being able to swap between the monitor's display modes is regardless a no-brainer function to have.

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**

**Usecases**
A multicamera shader would appreciate this function greatly if a SmartScope Duo is the only monitor  that is set up at the shading position.

**Comment by haakonnessjoen** [comment]
This action is automatically added if you select SmartScope Duo as the device model when setting up the instance.

**Comment by sondrearnsethjacobsen** [comment]
Would you look at that. Wasn't able to see that because the options apparently ended up in the bottom of the list.
![skjermbilde 2018-10-17 kl 23 23 17](https://user-images.githubusercontent.com/44243573/47117406-884b5100-d264-11e8-88f7-8c11965cefc3.jpg)

**Comment by willosof** [comment]
This continues in #354

**Comment by tkausen** [comment]
Was there an update to this function with the current release?  Mine comes up a little different:
<img width="939" alt="Screen Shot 2020-01-02 at 7 46 29 PM" src="https://user-images.githubusercontent.com/59323477/71706559-9bc7d680-2d9a-11ea-81da-34464aca0a30.png">

**Comment by josephdadams** [comment]
@tkausen I don't see any recent updates to the smartview module. Are you using a SmartView or a SmartScope model screen? This looks like just a Smartview.

**Comment by krocheck** [comment]
And I have a major update to this module (including feedback/variables) that's been sitting partially debugged for about 6 months. 🤦‍♂

**Comment by tkausen** [comment]
Smartscope Duo 4K

**Comment by tkausen** [comment]
@josephdadams i believe both models show up as one choice.  In this thread, the selection was proceeded with OBR4 and I assumed that might be from an older version

**Comment by tkausen** [comment]
@josephdadams @krocheck thanks for looking.  Any help would be appreciated.
