### ISSUE TITLE
Module Request: Metus Ingest

### ISSUE THREAD

**Issue by ashjmckenzie** [bitfocus/companion#297]
Hi, I'm requesting support for Metus Ingest Network Recorder

Its telnet, pretty much a clone of the hyperdeck, but will need a port number added to the configure.

- https://metuskb.atlassian.net/wiki/spaces/INGEST/pages/5275821/INGEST+API+-+Socket+Commands

- http://www.metus.com/metus-ingest/

I've had a go via PuTTY and it works fine

These would be the most helpful commands, they are case sensitive. The commands without variables command multiple recorders at once.

Load [file name]
Start
Start [encoder name]
Stop
Stop [encoder name]
Split
Split [encoder name]

Thank you

**Comment by haakonnessjoen** [comment]
Would it be possible to get access to a device for testing? I am thinking we could do feedback too. So that buttons could change colors if the encoder is running or not, etc.

**Comment by ashjmckenzie** [comment]
Yup I can organise a team viewer remote session, feedback would be amazing

**Comment by ashjmckenzie** [comment]
Yup our Metus is licenced to 4 Encoders:

List Command

![list](https://user-images.githubusercontent.com/44249301/48021877-8bb86500-e19e-11e8-861a-396ca71092d1.JPG)

**Comment by willosof** [comment]
I think you also can download trial versions of that software @haakonnessjoen :) So it should be easy.

**Comment by JeffreyDavidsz** [comment]
After some nice help from Metus, I could finish the basic module. It's in the latest build

**Comment by ashjmckenzie** [comment]
@JeffreyDavidsz Thanks so much for this, would it be possible to add a single encoder stop command, alike the single encoder start command already present ?

**Comment by JeffreyDavidsz** [comment]
Done it's in the latest 2.0 build
