### ISSUE TITLE
[BUG] Comanion Emulator does not support Multitouch

### ISSUE THREAD

**Issue by JohannesRegneri** [bitfocus/companion#2970]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Companion Emulator does not support Multitouch. 
Webbuttons on the other hand do.  

### Environment (please complete the following information)

```markdown
- OS: Windows 10
- Browser: Firefox, Chrome
- Companion Version: 3.3.1+7001
```

**Comment by MeestorX** [comment]
WAG, but have you tried enabling `Use TouchBackend for Drag and Drop` in Companion settings? I don't know that it would make any difference, but maybe??

**Comment by Julusian** [comment]
This is now supported in the betas, and will be in the next release

**Comment by JohannesRegneri** [comment]
Thanks a lot!
