### ISSUE TITLE
[BUG] Yarn build fails with "Workspaces can only be enabled in private projects"

### ISSUE THREAD

**Issue by IcedQuinn** [bitfocus/companion#2972]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Yarn seems to have set up some kind of restriction to building projects.

> error Workspaces can only be enabled in private projects.

I was ab

### Steps To Reproduce

1. Check out the repo
2. Try to build it (ex. `tools/yarn.sh`)

### Expected Behavior

it should build ;)

### Environment (please complete the following information)

```markdown
- OS: Void Linux
- Browser: N/A
- Companion Version: `main`
- Yarn: 1.22.19
```

### Additional context

I was able to get around this by adding `private: true,` to the `package.json` file at the top level of the repository.

**Comment by Julusian** [comment]
How did you install `yarn`? 
We use yarn v4, which I thought 1.22 would automatically invoke for you, but it appears to not be for you causing this error

**Comment by IcedQuinn** [comment]
> How did you install yarn?

System package manager (Void Linux.)

**Comment by Julusian** [comment]
I think you will need to install it via the officially documented route, as we require v4, it won't work properly/correctly with v1 
https://yarnpkg.com/getting-started/install
