### ISSUE TITLE
[BUG] [BETA] Feedback only applies to last created button when multiple feedsbacks use same variable

### ISSUE THREAD

**Issue by FraVae** [bitfocus/companion#2975]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Feedback only applies to last created button when multiple feedsbacks use same (custom) variable

Initial state after starting companion:
![1](https://github.com/user-attachments/assets/b3c2a148-7dc0-4d45-941f-df70ce9547b0)

State after altering some variables (buttons with same name are copied)
![2](https://github.com/user-attachments/assets/9732888e-25fd-4114-85d7-815892913060)

### Steps To Reproduce

1. Create custom variable
2. Create a button that has feedback to that variable
3. Copy that button, or create a new button with feedback that looks for the same variable
4. Change the custom variable and watch only the last created button change
5. Works with all variables

### Expected Behavior

Expected 2 identical buttons to react the same

### Environment (please complete the following information)

```markdown
- OS: Win10
- Browser: Firefox
- Companion Version: [BETA] v3.4.0+7177-main-4c7698c9
```

**Comment by Julusian** [comment]
I happened to find and fix a bug just before you opened this. That bug was copying a button would result in broken feedbacks on either the original or copied button.
This sounds like the same thing you have seen, could you re-test after re-copying the button in beta 7180 or later?

**Comment by FraVae** [comment]
"Old" buttons still act the same, but issue is fixed after coping the button with working feedback in beta 7180! Thx :)
