### ISSUE TITLE
PJLink Module: Possibility to define password

### ISSUE THREAD

**Issue by robertskiba** [bitfocus/companion#298]
Add the option to define a password to control projectors via PJLINK-protocol

**If documentation is required to implement, do you know where to find it?**
The documentation, how to login into PJLINK-Projector with password should be findable in the protocol description..

**Usecases**
At the moment, PJLINK-module is only usable if the password for PJLINK is empty. For example, with Panasonic-Projectors the PJLINK-Password is the same as the web control password is, so currently, you have to empty the web password what can be a security issue. It would be nice if I could define the password in the module settings.

**Comment by willosof** [comment]
@haakonnessjoen rewrote that 9 days ago in https://github.com/bitfocus/companion-module-pjlink/commit/d0793a87a7e2b6baafa47cb6e8ae0e00777371c6
