### ISSUE TITLE
Evaluating and using the function in the button name

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion#2984]
Allow to use a function or complex expression in the button name. It would be interpreted and the result would be displayed. Currently, when I write a function in the name of the button, it is not executed and is written as text. Button name variables work of course.

**Comment by Julusian** [comment]
click the `A` to the right of the textbox to switch it to expression mode
![image](https://github.com/user-attachments/assets/f7844435-0d9a-48f5-8eb4-8fe94b9a05d6)
![image](https://github.com/user-attachments/assets/343ea467-0c24-4d5b-994f-57f82cdec9d0)

**Comment by Suenee** [comment]
thank you very much for the explanation. I didn't think to click on it :-)
