### ISSUE TITLE
[BUG] "Got variable definitions with invalid ids" is only shown in the core Companion log, not my Connection's log

### ISSUE THREAD

**Issue by peternewman** [bitfocus/companion#2988]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Warning "Got variable definitions with invalid ids" thrown from Instance/Wrapper/<my instance> is only shown in the core Companion log, not my Connection's log.

### Steps To Reproduce

1. Add a variable with an invalid ID
2. Nothing shows in the Connection's log to that effect
3. Find that it is reported in the core Companion log

### Expected Behavior

Bug/feature, it would be nice if it was shown in/mirrored in the Connection's log too

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:develop
```

**Comment by Julusian** [comment]
It should be included there now

**Comment by peternewman** [comment]
Awesome thanks @julusian!
