### ISSUE TITLE
Click on Page number to return to Main Page

### ISSUE THREAD

**Issue by brunofarre** [bitfocus/companion#299]
**Describe the feature**
Clicking on page Number (Center Left Button) bring you back to Main Page (Page 1)
even better would be in settings, being able to select page number as Main

**Is this platform dependent (windows, mac, ..)?**
All Platforms

**If documentation is required to implement, do you know where to find it?**
N/A

**Usercases**
All my main button are on Page 1, easy return to them with 1 click

**Comment by josephdadams** [comment]
With 2.0, you can choose to add page buttons if you want, and you can add a button action to change the surface to another’s page. So this is done if you are using 2.0 :)
