### ISSUE TITLE
Request: New position and/or shortcut for 'test' button

### ISSUE THREAD

**Issue by Coupe70** [bitfocus/companion#2992]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Whenever I'm editing buttons with several actions I have to scroll back up to the top each time I want to click the 'test' button.
Would it be possible to move the 'test' button to the left side of the screen to have it accessible anytime?
Second best option would be to at least have a second 'test' button at the bottom, below the actions.
And/or would it be possible to give it a keyboard shortcut (t ?) ?
![grafik](https://github.com/user-attachments/assets/f39c6126-27a4-4e1f-b6d7-f66c21af82ea)

### Usecases

Convenient testing when no hardware surface is available.

**Comment by dnmeid** [comment]
I would rather not move the test button to the grid. In future it will be possible to select more than one button and then you can't associate the test button to a button.

Are you aware of the hot press functionality? Shift+Click button

**Comment by Coupe70** [comment]
Actually NO, I wasn't aware of the hot press functionality. Thanks for that!
Much better than the test button in many cases.
So from that point of view I don't need the test button at all anymore.

But: I still need it when it comes to triggers and there is the same problem - I have to scroll all the way up on the right side to get to the test button and I would prefer to have it on the left side. Or maybe at the very top where the non-moving tabs are.

And speaking of selecting multiple buttons in the future: What will be displayed on the right side when selecting more than one button? Probably nothing? So no test button at all. So I would again expect it to be on the left side (or the vcery top) and trigger all selected buttons which I can't do by Shift+Click.

**Comment by dnmeid** [comment]
I don't think we want to introduce a way to fire hundreds of buttons with one click.
Overall I can imagine that another key shortcut like ctrl-t would be a nice addition and that can work for buttons or triggers or even for presets or single actions.

**Comment by Coupe70** [comment]
I'm sure a (one-handed) key shortcut would suffice, although the question stays the
same: What would a "Test"-shortcut that fires a selected button logically do when 
multiple buttons are selected? Probably fire them.
But I agree that there is probably no real use case for that special case and it's
not the reason why I was asking for a better access to "Test".

**Comment by dnmeid** [comment]
> [@dnmeid](https://github.com/dnmeid) you mention selecting multiple buttons is coming - will that enable multiple cut/copy/paste, or even drag and drop?

Yes, that is the plan.

**Comment by davidjoshuaford** [comment]
@dnmeid that will literally transform my life!

It would also be amazing to be able to have two panes open along side each other to drag buttons between pages… currently there are so many key presses to individually copy multiple buttons between pages

**Comment by gbdlin** [comment]
I'm pretty sure you can click on a button with shift key held down to test it.

**Comment by Coupe70** [comment]
> I'm pretty sure you can click on a button with shift key held down to test it.

Thanks, didn't know about that.
Problem solved.
