### ISSUE TITLE
[BUG]Expressions not evaluating correctly since beta 7203

### ISSUE THREAD

**Issue by ChrisSW58** [bitfocus/companion#2994]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Expressions eg ($(internal:custom_Preset_Copy_From_Step)==12) ? ($(internal:custom_User_1_Page)+20) : ($(internal:custom_User_1_Page)) are not evaluating properly. Were working correctly in beta version 7203

### Steps To Reproduce

See example above or any equivalent eg ($(internal:custom_Copy_FROM_User) !=1) && ($(internal:custom_User_1_Name)!="")

### Expected Behavior

True or false evaluated correctly

### Environment (please complete the following information)

```markdown
- OS:MACOS
- Browser:Safari
- Companion Version: 7212

Have reverted to 7203 again which is operating correctly.
```

**Comment by Julusian** [comment]
can you provide some example values of those variables when it isnt working?
I am trying some things, and not seeing anything wrong

**Comment by ChrisSW58** [comment]
Probably easier if I give you the config file - attached. Look at the triggers starting with COPY_ those all work fine in 7203 - in later versions they are all equating to True. 
[Chriss-iMac-2.local_custom-config_20240820-1106.companionconfig.zip](https://github.com/user-attachments/files/16679819/Chriss-iMac-2.local_custom-config_20240820-1106.companionconfig.zip)

**Comment by ChrisSW58** [comment]
If you want to see it in operation, download H2R and import this CSV file. Initialise the system and then preset copy preset on the first page. Only those users contained in the Config file should be enabled.
[Config File.csv](https://github.com/user-attachments/files/16679962/Config.File.csv)

**Comment by Julusian** [comment]
One issue is that variables with falsey (empty string, 0, false) values are being incorrectly converted to `$NA`.
Could that explain everything, or is there something else?

**Comment by ChrisSW58** [comment]
Could be - did that change in later betas? Interestingly, the comparison for empty string works in "Button: Set current step if variable meets condition" where the condition = "" (field left blank) Assuming this to be the case, what should I be comparing to, to be on the safe side?

**Comment by Julusian** [comment]
Yeah, `Button: Set current step if variable meets condition` wouldnt have been affected as its not expression based

Don't change anything, the 7214 beta build has a fix for that issue

**Comment by ChrisSW58** [comment]
Fantastic many thanks! Very much appreciated
