### ISSUE TITLE
Highlight module label in Presets Tab

### ISSUE THREAD

**Issue by phillipivan** [bitfocus/companion#2999]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

In the Presets tab, each connection is listed by its module type, and then in brackets its module label.
With many modules, and especially with many modules of the same type, this is quite hard to read. Especially so if the module lists a large number of products, all of which are listed.

This would be easier to read and navigate, if the Module Label was in Large text, and the Module type was in a smaller font and just listed using the short name, rather than Manufacturer and Products.

For instance in this screen shot there are multiples of several module types, but the most real estate is given to the module type, and not the critical distinguishing detail (the module label)... Or ditch the module type entirely, I don't find it useful at all.

![image](https://github.com/user-attachments/assets/a18f5954-4e7d-43c9-836b-4350de3c5bb6)

### Usecases

Ease of use when working with large configurations.

**Comment by phillipivan** [comment]
Secondarily, the ordering seems to just be the order of module initialization. It would be nice if it was alphabetical, or in the same order as the connections tab.

**Comment by Julusian** [comment]
This should all be resolved now
