### ISSUE TITLE
[BUG] HTTP - API Calls not working.

### ISSUE THREAD

**Issue by TPaulManohar** [bitfocus/companion#3006]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We are trying to use the HTTP request API calls, But there is no response when we ran through browser.

http://hostaddress:8000/press/bank/1/1 
https://hostaddress:8000/press/bank/1/1

### Steps To Reproduce

http://hostaddress:8000/press/bank/1/1 
https://hostaddress:8000/press/bank/1/1

### Environment (please complete the following information)

```markdown
- OS:Windows 10
- Browser: Brave
- Companion Version:3.3.1
```

**Comment by Julusian** [comment]
Have you enabled both the `HTTP API` and `Deprecated HTTP API` in the settings?

**Comment by TPaulManohar** [comment]
Yes, Enabled both. But didn't worked.

**Comment by istnv** [comment]
Most browsers send a GET request, not POST

**Comment by TPaulManohar** [comment]
@istnv Then am I doing wrong. Simply I pasted on search bar of the browser and press enter.

I tried on safari browser.

http://hostaddress:8000/press/bank/1/1

There is no triggered action we found.

**Comment by Julusian** [comment]
@istnv for these deprecated endpoints, GET is correct.

I don't know why its not working though, I can do the same and the browser says `ok` and it triggers the buttons

**Comment by istnv** [comment]
Chrome (Win10) -> Companion (Linux): works as expected
Chrome(Mac) -> Companion: works
Safari(Mac) -> Companion: works

**Comment by TPaulManohar** [comment]
I will check once again, and get back to here.

**Comment by Julusian** [comment]
@DubbingBrothersFrance your problem is easy, you are making a http request to the tcp port.
you should be using the same port number as the web interface

**Comment by thedist** [comment]
16759 is the default TCP port used by Companion, you should NOT be making HTTP requests to it, and if you set Companion to try and run the webserver of that same port, then that'll be a conflict.

You should be sending the CURL request, or however you choose to make the HTTP request, to whichever port the Companion web server is running on, eg I have Companions Web UI on 8000, so I would make HTTP requests to port 8000.

**Comment by Julusian** [comment]
@TPaulManohar any update on whether this is working for you?

**Comment by TPaulManohar** [comment]
@Julusian I'm wondering right now that how it is working as excepted.

Anyways it working now.
