### ISSUE TITLE
[BUG] Set Raw Value results in an error in the Log

### ISSUE THREAD

**Issue by LikeThisReview** [bitfocus/companion#3008]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Action "Set Raw Value" results in an error in the Log: 
Internal/Variables: Failed to execute expression "": Error: Unknown node "Compound"

The result of the action is OK though (the value is assigned to the custom variable)

### Steps To Reproduce

1. Create a button with Action Set Raw Value 2. Press the button 3. Check the Log

### Expected Behavior

No error in the log

### Environment (please complete the following information)

```markdown
- OS: Mac OS latest
- Browser: Safari
- Companion Version: v3.3.1 stable
```

**Comment by Julusian** [comment]
This sounds to me like it isn't the action causing this, but somewhere using the variable which is failing.
I think that to be able to make any progress on this, I need to see the expression that is failing, it is definitely tripping up the parser in a way which I haven't expected

**Comment by Julusian** [comment]
With that prefix in the log, that indicates the error came from the feedback `Variable: Check boolean expression`, so check for one of those which could be the one failing

**Comment by LikeThisReview** [comment]
Julian, I’m terribly sorry for not documenting this issue in more detail.
Can’t recall where I was working on and can’t reproduce it anymore. Will
keep an eye on the log.
Regards, Nico

**Comment by Julusian** [comment]
Closing this until it can be reproduced
