### ISSUE TITLE
[BUG] Safari: Corruption of Page drop down dialog when button clicked on screen

### ISSUE THREAD

**Issue by ChrisSW58** [bitfocus/companion#3009]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Corruption of drop down menu. Menu works until a button is clicked, when corruption occurs.
<img width="701" alt="Drop down not working" src="https://github.com/user-attachments/assets/9ba1c6b0-0a2a-41a6-a0e7-0a11065c3bff">
<img width="709" alt="Dropdown working" src="https://github.com/user-attachments/assets/817d76e7-4926-4d73-97e7-f588c2815cc4">

### Steps To Reproduce

1. Start GUI
2. Select a page from drop down menu
3. Click any button on the page
4. Return to drop down menu

### Expected Behavior

Corruption not occurring!

### Environment (please complete the following information)

```markdown
- OS:MacOS
- Browser:Safari
- Companion Version:latest beta 7239 but has been present for most of the beta versions
```

**Comment by Julusian** [comment]
Can you check what the version number is of your macos and safari? I am not able to reproduce this on my mac (safari 17.6, macos I told to update before I checked)

**Comment by ChrisSW58** [comment]
Hi there - yes, I should have said - apologies. MacOS Sequoia 15.1 Beta which has Safari 18.1.... I would expect this to be live as of next week.

**Comment by Julusian** [comment]
I'm not able to reproduce this in the 15.0 beta either. So I'm going to leave this until 15.1 is nearer release, in case it goes away by itself

**Comment by ChrisSW58** [comment]
Thanks anyway - here’s hoping :)

**Comment by Julusian** [comment]
@ChrisSW58 is this still a problem? I am still unable to reproduce on 15.2

**Comment by ChrisSW58** [comment]
No this was resolved a time ago - many thanks.
