### ISSUE TITLE
PJ LINK Projector with rz970 Projectors

### ISSUE THREAD

**Issue by jenton93** [bitfocus/companion#301]
**Make sure you're on the latest bleeding edge build** (remove this section from the bug report)
*Before you report a bug, make sure you're not reporting something that have been fixed in the master branch by downloading a "latest" build from https://builds.bitfocus.io/companion/*

**Describe the bug**

**To Reproduce**
All the options like projector off and on do not work

**Expected behavior**
NA

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version 1.1.1

**Additional context**
I believe there are lots of different login details. how do i found these and change them as required

**Comment by willosof** [comment]
Related to #298.
