### ISSUE TITLE
Audacity

### ISSUE THREAD

**Issue by antlear** [bitfocus/companion#302]
**Describe the feature**
The option to control Audacity, Stop, play, record

**Is this platform dependent (windows, mac, ..)?**
windows, mac et

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along

**Usecases**
I use this to record seminars and sessions and would mean it can be in the background / on another pc out the way

**Comment by haakonnessjoen** [comment]
Unless you know something I don't; audacity has no network control. So it would need to be controlled by a general keystrokes. Look at one of the modules capable of this using third party software. Such as Octopus Listener. Link inside the module description in companion. Please reopen if there is some kind of documented network control for audacity at some time.
