### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Oscperetc** [bitfocus/companion#3020]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

PURTROPPO NON RIESCO AD ACCEDERE MI DICE Companion is locked HO PROVATO A CERCARE IL FIL DB O USER ADMIN MA NULLA.

### Environment (please complete the following information)

```markdown
- OS:WINDOWS 11
- Browser:EDGE
- Companion Version:3.2/3.3/3.4
```

**Comment by Julusian** [comment]
This is mentioned many times in other issues and on facebook https://github.com/bitfocus/companion/issues/2393#issuecomment-1483900433
