### ISSUE TITLE
[BUG] In setting Show the Topbar is inverted.

### ISSUE THREAD

**Issue by ChrisSW58** [bitfocus/companion#3022]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In settings "Show the topbar on each button. This can be overridden per-button" - when set to on, top bar is off, and when set to off, top bar is shown. Has occurred in the past recent 24 hours of beta releases approximately.

### Expected Behavior

Button is inverted, or text needs to be corrected. Occurring in largest betas.

### Environment (please complete the following information)

```markdown
- OS:Windows & Mac
- Browser: Chrome & Safari
- Companion Version: latest beta 7271
```

**Comment by Julusian** [comment]
oops, thats what I get for refactoring the userconfig pages to be less repetetive :facepalm:
fixed now
