### ISSUE TITLE
[BUG] UNRAID APP - Failed to create config directory. 

### ISSUE THREAD

**Issue by mscrnt** [bitfocus/companion#3029]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The container fails when I try to start the unraid app. I see this in the logs.

`Failed to create config directory. Do you have the correct permissions?`
`2024-09-10T22:13:27.769Z info Log/Controller Application starting `

### Steps To Reproduce

1. Install `Bitfocus Companion` from the community app store.
2. Make sure all fields are filled out correctly and click done.
3. Wait for the app to download and start the container automatically.
4. Notice the app doesn't start.
5. View logs and see error message.

### Expected Behavior

App should start without any additional steps. 

### Environment (please complete the following information)

```markdown
- OS: UNRAID
- Browser: Chrome
- Companion Version: Latest (3.4?)
```

### Additional context

When running the container in interactive mode, I see the companion folder is created and seems to have the correct usergroup.

**Comment by GameSofter** [comment]
This can stay closed, I just wanted to add that the fix for this is in the docker setup. Add `--user 99:100` to the "Extra Parameters" box.
