### ISSUE TITLE
Qlab module Stop function

### ISSUE THREAD

**Issue by JeffreyDavidsz** [bitfocus/companion#303]
Stop function for qlab is actualy a hard panic. Probably a typo?
"/cue/stop" Should do the trick. But I'm not sure.
Stop function should do the same as pressing [s], it stops just that cue

**Comment by willosof** [comment]
Stop sends /stop. There should maybe be another function making a specific cue stop?

**Comment by JeffreyDavidsz** [comment]
For a specific cue to stop the syntax is /cue/#/panic. Where # is the cue number. I'll check if the /panic alone will do the job.
/cue/#/start would be a good extra. This way you always start the right cue.

**Comment by JeffreyDavidsz** [comment]
Start cue is in there, stop and panic is clear
