### ISSUE TITLE
Uptime Internal Variable

### ISSUE THREAD

**Issue by phillipivan** [bitfocus/companion#3032]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

A new uptime internal variable. Increamenting in 1 second intervals whenever companion is running.

### Usecases

As a sanity check to validate that Companion or the Host hasn't crashed and recovered when unattended.

**Comment by peternewman** [comment]
Would start time be less intensive/disruptive but almost as useful?

**Comment by phillipivan** [comment]
Perhaps? I wonder if an expression could turn that into an up time?

We currently use my own generic-hostinfo module to do something similar, but its using the module uptime as a defacto companion uptime. This is just displayed on a page only available to the tech team (not the operators) as a sanity check that the system has been well behaved. It has helped us identify some overnight system reboots that might have otherwise gone unnoticed.

**Comment by Julusian** [comment]
`$(internal:uptime)` has been added. It's very simple to implement, as we already have the structure in place for the other clock based variables.
This looks like it should tick in sync with the clock variables, so should work together nicely if you want to do anything fancy with it

**Comment by phillipivan** [comment]
Thanks @Julusian!
