### ISSUE TITLE
artnet to companion

### ISSUE THREAD

**Issue by milansebregts** [bitfocus/companion#3039]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

can you send an artnet address to companion and then I mean that I create an address and then I can link it to a button in companion so that your companion gives a trigger instead of sending a trigger from companion to artnet or a light table

**Comment by Julusian** [comment]
There is an artnet listener in companion, and some same fixture profiles available in the settings tab.
It uses 3 channels with a customisable start address:
1) page number
2) button number (using old 1-32 numbering scheme)
3) button down when > 128, up when > 10
