### ISSUE TITLE
Serial module system

### ISSUE THREAD

**Issue by haakonnessjoen** [bitfocus/companion#304]
We should develop a serial module wrapper, just like the udp and tcp stacks in Companion. So that any device that can be controlled by RS232/422/485, can use both internal serial ports, and also any instantiated network serial ports that we add support for.

**Comment by mattrog** [comment]
This is something that we are looking for - at the moment we are looking to have another bit of software configured that can be triggered externally just to do the serial commands - With so much stuff that can be triggered by serial commands this would be REALLY helpful...

**Comment by josephdadams** [comment]
@mattrog have you looked at the GlobalCache iTach products?

**Comment by mattrog** [comment]
> @mattrog have you looked at the GlobalCache iTach products?

I thought I had - but dismissed them as they were £300+ - obviously googled the wrong thing - ta very much !!

**Comment by josephdadams** [comment]
They’re controllable in Companion!

**Comment by istnv** [comment]
I have a couple of serial-only devices to added to my companion control.
I just picked up a couple of these:
https://www.amazon.com/USR-TCP232-302-Serial-Ethernet-Converter-Support/dp/B01GPGPEBM

**Comment by vibinc901** [comment]
I’ve tried the Global Cache IP2SL module, but I don’t know if Companion is sending out ASCII or hex. I’m assuming ASCII because the commands don’t work through Companion, but do work using my USB to serial cable.

**Comment by mattrog** [comment]
Just bought one of the IP2SL boxes ... hope they do actually work ... Any ideas if other serial boxes work - like this one? https://www.amazon.co.uk/StarTech-Serial-Ethernet-Converter-Device-Black/dp/B00LJEQLR2

**Comment by josephdadams** [comment]
@vibinc901 would you mind making an issue request for the IP2SL module repository directly to see if @cxselph can help you?

https://github.com/bitfocus/companion-module-globalcache-itac-sl/issues

**Comment by PerRoine** [comment]
I'm developing a module right now for the Dsan limitimer where i use the ip2sl box and it works fine 
the existing module for the box terminates each command with CRLF wich might be an issue we could possibly make end of line termination a instance config item or a action option

**Comment by cxselph** [comment]
@PerRoine I just added options for line termination in the IP2SL module for greater flexibility. You can choose between CR, LF, or CRLF now. That may help those that are having some trouble. Can you have a look and push the changes to core if all is good? I tested mine with all three options and it is working fine here.
