### ISSUE TITLE
[BUG] 3.4.0 does not open on MacBook Pro Intel i7 running Catalina 10.15.7

### ISSUE THREAD

**Issue by larryseyer** [bitfocus/companion#3041]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It simply will not open.

Reverted back to 3.3.1  which works.

### Expected Behavior

It should run... but it does not start.

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by Julusian** [comment]
This is a known issue #3036

**Comment by Julusian** [comment]
@larryseyer could you give https://builds.julusian.dev/companion-builds/companion-mac-x64-skia-recompile.dmg a try?
You will need to hold alt, right click then click open on both the dmg and companion for it to launch as it is not fully signed.

If this runs, then I can tidy up the fix and get it into the builds. I don't have a mac that can run 10.15 to try it with myself, so I am hoping this will work

**Comment by BasilChessman** [comment]
@Julusian  I just tried the build you posted in the link above but had no luck.  I got the same unable to start error.
