### ISSUE TITLE
[BUG] Beta 3.5 Config Import fails when pages don't exist

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion#3043]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Importing a previous configuration fails in 3.5 with the error message that pages need to be created before they can be imported to. 

I also tried creating 99 pages, but the import still failed and ended only with Page 1

I like that new installations default to only 1 page and that new pages can be added as needed. However, when Importing previous configurations, it would be good if those pages (including blank pages between pages with buttons on them) are generated by the import. Hence pages retain their original page number (for the full import behavior). 

Since it looks like we are moving away from static page numbers, and will probably rely more on unique page names to reference surface jumps, it would be helpful during import to have a list of checkboxes beside pages to choose which pages we want to import, and those pages cascade to the minimum number of pages required.

Also the import process could be improved to drag buttons from a config import into Companion, similar to how Preset buttons can be dragged into Companion pages. 

### Environment (please complete the following information)

```markdown
- OS: Mac M1
- Browser: Chrome
- Companion Version: 3.5.0-7406
```

**Comment by LYMPIA** [comment]
I've encountered the exact same problem while importing a previous config on a new beta or experimental release.
Only one page (the first) is being shown/available after the full import process.

But when I reinstall the 3.4.1 stable version (or any previous 3.4 versions) all my pages become available again.
The same issue was encountered also with the experimental release.

I've also tried a possible workaround : importing a fully functionnal configuration with a previous release (ie. 3.4.1) and install any 3.5 version on top. Alas, it dosn't work at all and the same issue occured : only one page (the first) is being shown on the button page. No other pages are available at all. No error message is displayed while importing full config.

Hope this will help...

**Comment by ChrisSW58** [comment]
Whilst this may be connected to #3061 the upshot is that once you attempt a clean import, you are unable to do anything. You lose all pages (except for page 1) and all code has naturally gone as well. It successfully stops all development occurring in 3.5. Is therefore a fix for this coming along anytime soon? many thanks.

**Comment by Julusian** [comment]
this is fixed now

**Comment by ChrisSW58** [comment]
Fantastic! Very many thanks - much appreciated
