### ISSUE TITLE
Modify page down button: Press & Hold to go to first page

### ISSUE THREAD

**Issue by leonreucher** [bitfocus/companion#3057]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Just a thought: it would be nice that if the page down button was pressed for 1000ms, that the StreamDeck would jump directly to the first page. Probably this feature can be configured in the Companion Settings afterwards, to disable it.

I know that I can just build this button myself directly in Companion - but I would like to see this integrated in the native navigation buttons.

**Comment by istnv** [comment]
The Page Number (label) button is a <home> key that does that.

**Comment by leonreucher** [comment]
Thanks - didn't know that...
