### ISSUE TITLE
[BUG] Button Trigger over HTTP does not work or example would be good

### ISSUE THREAD

**Issue by MrTeslaM3** [bitfocus/companion#3059]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey there, I cannot trigger a button over a http. 
In the doc it is described by "/api/location/page/row/button/press" before it was "/press/bank/page/button" but this already does not work.

Have anyone an example or is it a bug. Thank you

### Steps To Reproduce

Use a tool wich triggers http recast (here Apple Automator). Try to trigger a button over a http request.

Bevor the last big update it works by the "old" command above.

### Expected Behavior

Trigger the button I would trigger. Like I would Trigger Button 4 on Row 3 at Page 1

### Environment (please complete the following information)

```markdown
- OS: Mac OS
- Browser: Safari
- Companion Version: 3.4 and 3.4.1
```

**Comment by Julusian** [comment]
Are you sending a POST request, or a GET request?
The old api used GET requests, the new one requires POST

The old api is still there, but it has to be enabled separately to the new api

**Comment by Terbiii** [comment]
@Julusian I also had the problem, and changing the request to POST is fixing the issue.
Thanks

**Comment by MrTeslaM3** [comment]
Thanks for the POST hint. 

I tried "curl -X POST 127.0.0.1:8888/api/location/11/0/0/press" but it still does not works. Anything wrong or did I have to activate another thing?

**Comment by MrTeslaM3** [comment]
Ok sorry. On my system I had another local IP and forgot a 10.
Think its to late. So everything ist fine
