### ISSUE TITLE
Encore module

### ISSUE THREAD

**Issue by DiViPro01** [bitfocus/companion#306]
Finally got time to test. The module is not working.
Using the same computer and octopus, everything works fine. using telnet to send the commands, also everything works fine.
Companion succeeds in making a connection, but not in sending the right commands.
Using wireshark, I see that octopus sends commands like

PRESET R 3, while companion sends

PRESET -r 3. Maybe this could be the issue?

**Comment by willosof** [comment]
Whaa.. The documentation says -r. Will investigate!

**Comment by willosof** [comment]
Should work now. I used 
http://www.avsystem.it/files/files_download/00101.pdf as a reference. 
Barco seems to have changed their mind about this protocol at some point.
