### ISSUE TITLE
"replace current configuration" missing

### ISSUE THREAD

**Issue by marrba** [bitfocus/companion#3061]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I am unable to find the "replace current configuration" button after attempting to import a file from "A2Z productions" YouTube channel as outlined in their video: https://www.youtube.com/watch?v=-pRQKAqDPMg. I have installed both companion v3.4.1 and the beta 3.5.0+.... I have my ATEM Mini Extreme ISO connected to the same network with a LAN line. 
<img width="867" alt="2024-09-29 Atem Mini Extreme ISO connected Capture" src="https://github.com/user-attachments/assets/27b60b3e-0794-44dd-89e7-747634fbc757">
<img width="1696" alt="2024-09-29 bitfocus website products to downloads Capture" src="https://github.com/user-attachments/assets/c6573f58-758d-4c58-8210-fca5442c0418">
<img width="871" alt="2024-09-29 Buttons Capture" src="https://github.com/user-attachments/assets/f387fe09-92e5-4a1d-99a5-4ccc442bff17">
<img width="879" alt="2024-09-29 Import Export Configuration Capture" src="https://github.com/user-attachments/assets/fc491566-9f5d-4fb0-90cf-f236559f6cb9">
<img width="876" alt="2024-09-29 Import failed Full import failed with Page must be created before it can be imported to Capture" src="https://github.com/user-attachments/assets/43818d34-d945-47f3-a9df-72bc3239b3a7">

How can I upload the companion file, .companionconfig, in order to update my stream deck with those preprogrammed macros?

**Comment by Julusian** [comment]
In 3.5 based on your last screenshot, you are seeing the bug https://github.com/bitfocus/companion/issues/3043
I'm not aware of any reason it wouldn't work in 3.4. My only thought is that the video you linked is rather old, so the naming of buttons and things has changed since it was made. The 'Reset and Import' button is the new name of the 'replace current configuration' button

**Comment by marrba** [comment]
Thanks for the prompt response!

I have never worked with companion, stream deck, of blackmagic atem, so any advice on how to proceed is appreciated.

I have started the process about a week ago. The ATEM was bought about 2 weeks ago. Everything is new. I had a hard time getting my atem to be recognized by companion, until I hard wired it to the network. This is frustrating.

I have uninstalled both versions of companion. My stream deck is plugged in via USB, however the application remains off. There is a comment somewhere that this would not work if the stream deck application is on.

What do you recommend I do?

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by marrba** [comment]
Hello again!

My last email was probably lost to the ma y emails you probably receive on a daily basis. I would like to know how to solve my issue, so please let me know what I can do. I have copy and pasted my last email here for your convenience.

Thanks for the prompt response!

I have never worked with companion, stream deck, of blackmagic atem, so any advice on how to proceed is appreciated.

I have started the process about a week ago. The ATEM was bought about 2 weeks ago. Everything is new. I had a hard time getting my atem to be recognized by companion, until I hard wired it to the network. This is frustrating.

I have uninstalled both versions of companion. My stream deck is plugged in via USB, however the application remains off. There is a comment somewhere that this would not work if the stream deck application is on.

What do you recommend I do?
Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Julusian** [comment]
Importing configs into the 3.5 betas is known to be broken currently, so that not working is expected.
But it should work in 3.4.1, so try again with that, and remember that the linked video is 3 years old, so the ui doesn't match perfectly to that video. 
If it doesn't work, then we will need a copy of the file so that we can fix the import. It doesn't need to be shared publicly.
