### ISSUE TITLE
[BUG] 3.4.1 can't delete connection

### ISSUE THREAD

**Issue by Coupe70** [bitfocus/companion#3068]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When clicking the 3-dot-menu of a connection and selecting delete, the "are you sure?" dialog pops up for just a split second and disappears again, making it impossible to select 'yes'.
I was able to delete a connection by a well-timed ['select delete'->press enter] though, so the dialog is indeed functional, it just disappears very quickly on its own.

### Steps To Reproduce

see above

### Expected Behavior

"are you sure?" dialog waiting for yes/no input.

### Environment (please complete the following information)

```markdown
- OS: Windows 10
- Browser: Firefox
- Companion Version: 3.4.1
```

**Comment by Coupe70** [comment]
I was able to get persistent "are you sure?" dialogs for the 2 upper connections in the list.
This seems to work for a small area at the top, no matter which connections I move there by scrolling (when having many connections).
![grafik](https://github.com/user-attachments/assets/238deb68-262a-4093-af21-472ee9250e52)

**Comment by Julusian** [comment]
This is a known bug #2965
