### ISSUE TITLE
Added functionality for CASPAR CG

### ISSUE THREAD

**Issue by DiViPro01** [bitfocus/companion#307]
If you use the standard client of CasparCG, you get a library, containing all the media located in the media folder of the server.
That makes it really easy to choose the right media.
With companion, you have to type in the name of the media. That is a lot of work, and prone to make mistakes.

I guess it is possible by OSC, but I dont know the details about this.

**Comment by willosof** [comment]
@haakonnessjoen will probably do this in a jiffy ;)

**Comment by DiViPro01** [comment]
Thanks guys! Tested it out, works like a charm
