### ISSUE TITLE
Pasting the same function over all 100 pages at once

### ISSUE THREAD

**Issue by dashford123** [bitfocus/companion#3071]
### Is this a feature relevant to companion itself, and not a module?

- [x] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

I would like the ability to paste the same button over all 100 pages,

### Usecases

 i know this may seem niche, but when i got my new streamdeck plus i didnt like navigating the pages the default way, i wanted to turn a dial and scroll through the pages that way, and maybe add a home button. to make the scroll feature work i had to manually copy it to all 100 pages

**Comment by dnmeid** [comment]
I'd say that is a feature request that will never make it in the software.
1. in the near future there will be a variable number of pages and pages can be reordered
2. this would be a super bad design with a lot of potential mishaps

I fully can understand the need for some better workflows for mass editing of buttons, Companion is still really bad here.
But ultimately you have to think of what you really want to do. You do not want to copy one button to 100 pages, you want to have a customized navigation on every page.
We are thinking of introducing windows (read #2387). With that system you could have a window with just your navigation dial and put that on top. Below is a a second window that is the target of the navigation dial. Problem solved.
You can think of it like a "sticky button" or "permanent button" (also already requested here #27).

So If you agree that either #2387 or #27 would solve your problem better, I'd encourage you to close this issue in favour of one of those.

**Comment by dashford123** [comment]
Issue 27 will fix for sure. I hope to see it soon as my dial does not work unless pasted to every page, as if a scroll to far I can't go back to the previous page
