### ISSUE TITLE
Support Ajazz and similar stream deck clones

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion#3072]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

There has recently been a flood of stream deck clone devices which ship with software called 'stream dock'.

These panels could be something for Companion to support

**Comment by Julusian** [comment]
After an prototype of an implementation to get the surfaces working, I personally don't think that Companion should support them, for UX reasons.

The ajazz one I tried (15 key + a lcd strip on the right), is not hard to get working in code, but the hardware is lacking in functionality. The key issue is that when you press a button, it only tells us when it is released, nothing when pressed, just released.

Which as people by default add and expect behaviours on key down will be weird/unnatural. And then using this means that all the things you can do with a proper streamdeck where pressing the button does something, it maybe does something while you are holding, then something when releasing (which could vary depending on how long you hold for) will be impossible with these ajazz ones.

So these will give an inferior user experience, which will cause confusion for users. Both because they don't behave the same as an elgato streamdeck, and differently to how the ui in companion implies they should. Which is going to cause more questions from users on why things dont behave correctly, and user frustration when they learn that this behaviour is not fixable and is a limitation of the cheap hardware.

If anyone is able to counter these findings and finds that some of these do in fact produce down and up events, then please do reply here, I am happy to reconsider if my concerns can be avoided

**Comment by slawekmarczak** [comment]
I have Elgato Strem Deck XL and also AJAZZ AKP03E and just tested this behavior on AKP03E.
it looks like it is opposite than described. Action is taken at the moment of button press (button down). 
Not sure if there is any action/signal over USB when releasing the button, on UI and on the button itself no any reaction is visible.

**Comment by lukasMega** [comment]
How can I implement support for [Mirabox](https://github.com/bitfocus/companion-module-requests/issues/1494#issuecomment-2579992300) (similar Stream Deck clone with 15 buttons)?
Is there a documentation how to do it?

**Comment by Julusian** [comment]
There isn't any documentation on this. For an idea of what it involves, https://github.com/bitfocus/companion/pull/2944 was what it took to add another device recently.  

That one doesn't do any drawing to the device though, but should give an idea of the scale of the code needed. https://github.com/bitfocus/companion/blob/main/companion/lib/Surface/USB/Infinitton.ts is another 5x3 streamdeck clone. it is unknown if it still works, but could be a simple reference for the drawing logic.

To do this, you would be best to start with using the  https://github.com/rigor789/mirabox-streamdock-node/tree/main library that you found, but that library needs some work to make me happy with including it.
Most notably:
* The library still look to be in the 'experiment' stage. As such it has a bunch of 'junk' code for testing
* It is using a usb library rather than a hid library to talk to the device, despite acknowledging it is a usb device
* `jimp` should be replaced with `@julusian/jpeg-turbo` to minimise cpu cost
Maybe more, thats enough for a 5 minute skim of the library.

**Comment by lukasMega** [comment]
Thank you @Julusian! I appreciate your detailed response.
I will look at it sometime, maybe next month, currently I'm quite busy.

**Comment by rionhunter** [comment]
it must have both down and up given the timer functionality - you hold to reset it
