### ISSUE TITLE
[BUG] Option to disable "Resize grid to fit" warning

### ISSUE THREAD

**Issue by phillipkliewer** [bitfocus/companion#3079]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

On the buttons tab, the "Resize grid to fit" warning appears even if all of the emulators/stream decks are offset to fit within the boundaries.
There is no option to disable this warning and it takes up too much screen space, making the editing difficult.

![Image](https://github.com/user-attachments/assets/71fabe77-725b-4203-bf2f-f08bdcd1447d)

### Steps To Reproduce

Increase min row/column above 0
Set offsets in emulators/streamdecks to above 0
Warning still appears with no way to close it

### Expected Behavior

Make companion smart enough to know if offsets in emulators/streamdecks are actually out of bounds before giving the warning
OR
Make option to disable warning

### Environment (please complete the following information)

- OS:
- Browser:
- Companion Version:

**Comment by Julusian** [comment]
There is a bug here in that it wasn't correctly considering the position of the surfaces when doing the bounds checks. As you have changed the minimum row/column to be 1, this meant it got confused with that and would insist on growing it back out to 0/0.

I have a fix for this in the betas. If there is a 3.4.3 it will be there too.

Additionally, in the betas it is now possible to dismiss this hint, which will stop it showing until it is enabled again in the settings.
