### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by meonlylouder** [bitfocus/companion#3081]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

The latest two versions of Companion (3.4.2 and 3.4.1) cause Contour Shuttle ProV2 not to register any button presses with macOS (14.x and 15.x). When I quit Companion, my Shuttle ProV2 works as designed. Every time Companion is open, my Shuttle ProV2 does not work. I know their USB protocols are deprecated and they haven't updated their software since 2021 (it's still in "beta" for Mac). But there are no other control devices that fulfill me needs for editing like the Shuttle ProV2. I also opened a support ticket with Contour.

I've tried uninstalling and reinstalling both Companion and the Shuttle control software+drivers, as well as updating to macOS 15 today. The issue persists and I continue to have to quit Companion to use my Shuttle ProV2 for editing work.

### Steps To Reproduce

1. Open Contour Shuttle Settings app and press buttons on my Shuttle ProV2 controller. No response in any apps.
2. Quit Companion and buttons on Shuttle ProV2 now respond in all apps.

### Expected Behavior

In the past I have been able to have Companion running while also using my Shuttle ProV2. This changed with update 3.4.1 (I think).

### Environment (please complete the following information)

- OS: macOS 15.0.1 and 14.x
- Browser: Safari, Chrome, and Edge
- Companion Version: 3.4.2 and 3.4.1

**Comment by krocheck** [comment]
@meonlylouder can you verify that Contour Shuttle support in Companion is disabled in settings?  I'm assuming you want to use it with the profiles built in the Contour software instead of it being mapped in Companion.  If that setting is disabled then it should be working as you expect.  I had a Shuttle v2 around my place somewhere once upon a time, so if necessary I can do more validation on this after your update.
![Image](https://github.com/user-attachments/assets/b91a124d-7d18-4793-ac3c-c083dd573f78)

**Comment by meonlylouder** [comment]
That did the trick! Problem solved.

I don't know if I happened to try enabling it when I was setting up a new workflow for a gig a couple weeks ago. If I did, I would not have flipped that toggle if it had warned me that the Shuttle Settings profiles would no longer work.

I wasted so much time this week troubleshooting this and trying to get work done without my Shuttle ProV2...
