### ISSUE TITLE
Settings option for "Enabling connected Streamdecks" confusing or bug

### ISSUE THREAD

**Issue by DrEVILish** [bitfocus/companion#3091]
### Is this a feature relevant to companion itself, and not a module?

- [x] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the feature

In the settings page the option for "Enabling connected Streamdecks" is very confusing, enabling this toggle actually disables connected streamdecks. Enabling the option enables the "Elgato Streamdeck Plugin". On MacOS 14.3.1, Companion v3.4.2 (arm64).

I do not have any Elgato Software installed on this machine. To get Companion to use my directly attached StreamDeck I have to have the toggle "disabled".

"Enable connected Streamdecks
When disabled support for the Elgato software Plugin will be enabled
(Requires Companion restart)"

The wording is either very confusing, and not clear even for very technically experienced person or this is a Bug in the configuration.

**Comment by Julusian** [comment]
yeah this got accidentally inverted during some refactoring.. this is fixed in the betas and will be in the next release (either 3.5.0 or 3.4.3)
