### ISSUE TITLE
[BUG] Cannot run local shell script when hosting Companion on RPi - permission issue error 126

### ISSUE THREAD

**Issue by spacebearco** [bitfocus/companion#3095]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I am running the latest version of Companion 3.4.2 on a Raspberry Pi 4.

I have Companion running on one pi and I have Satellite Companion running on a second pi; both headless.

I wrote a shutdown bash script and made the file executable on the Satellite Pi. I can run this successfully through the terminal.

I generated an SSH key to enable passwordless entry from the Companion Pi to the Satellite Pi. This was also successful.

I wrote a second script in /home/pi on the Companion Pi that would SSH into the Satellite Pi and execute the shutdown script. (Maybe this is a very roundabout way to do this but it made sense to me.)

I can successfully run the script within the terminal to shutdown the satellite pi from the companion pi.

When I try to run this script from companion via the internal: run local shell script, it does not work. I tried everything. I consistently get Code 126. I have made it all executable and I have given it as many permissions as I possibly could. Ultimately I got it to run the script by using the Generic:SSH connection. I will use this for now, but I could not figure out why I could not use the Internal:Run Local Shell Script.

### Steps To Reproduce

SSH into Satellite Pi

Create shutdown script: sudo nano /home/pi/shutdown.sh

Add the line to the shell script: _sudo shutdown -h now_

Make it executable: sudo chmod +x /home/pi/shutdown.sh

SSH into Companion Pi

Create an SSH Key: ssh-keygen -t rsa -b 4096
Copy that key to Satellite: ssh-copy-id pi@raspberry_pi_ip

Confirm passwordless entry

Create shutdown satellite pi script: sudo nano /home/pi/shutdown_satellite.sh

Add lines to the shell script:
_#!/bin/bash/
#!/usr/bin/env bash
echo "Shutting down satellites..."

ssh pi@ip_of_pi 'bash /home/pi/shutdown_pi.sh'_ 

Make it executable: sudo chmod +x /home/pi/shutdown_satellite.sh

Test script: bash /home/pi/shutdown_satellite.sh (This should shut down just the satellite pi)

Make a button in companion

Add Internal:Run Local Shell Script

Add bash /home/pi/shutdown_satellite.sh

Run button

### Expected Behavior

Runs shell script on companion successfully

### Environment (please complete the following information)

- OS:RPi OS Lite 64 Bit
- Browser:Safari Version 18.0 (19619.1.26.111.10, 19619)
- Companion Version: 3.4.2

**Comment by Julusian** [comment]
This behaviour is expected. Companion is running as the `companion` user, which by default doesn't have read/execute access to the `pi` user's home folder. 
You either need to give it that permission yourself, or put the scripts somewhere where they can be accessed. (`/opt/` is a candidate)

Feel free to suggest where/how we can communicate this limitation better, it is a question that comes up every now and then

**Comment by spacebearco** [comment]
This makes complete sense. I know code 126 references permission issues, but I thought I had given all users access to the file. I didn’t think about giving it access to the whole folder path as well. Thank you!
