### ISSUE TITLE
Streamdeck Plus Support Full Width Screen Changes

### ISSUE THREAD

**Issue by DrEVILish** [bitfocus/companion#3098]
### Is this a feature relevant to companion itself, and not a module?

- [x] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the feature

On the Streamdeck Plus (SDP) has in the 3rd row of the companion grid, a 4 wide touch window.
I use this for giving me Timecode/Countdowns etc.
It would be nice to either set the screen that 1 button is the full width, or the ability to have the entire rows background change upon feedback. i.e. Countdown reaches alert state 1 sets the background to Yellow, and alert state 2 sets the background to Red, I can do this with each button individually, but they still appear as square boxes.

### Usecases

The expanded 1x4-sided button would benefit things like IP addresses and long-form content like filenames and paths. This as a per-page option would be very helpful.
BMD Hyperdecks
PresentationTools / CueTimer

**Comment by SetMonkey13** [comment]
+1
Would be useful for QLab cue names as well as EOS Cue Labels.  Even it if wasnt a 1x4, having the text be wider like the native StreamDeck app does with that row would be nice.

**Comment by peternewman** [comment]
I think some of this overlaps with https://github.com/bitfocus/companion/discussions/2387 and probably similar to https://github.com/bitfocus/companion/issues/2854 .

**Comment by DrEVILish** [comment]
Didn't read the whole of 2387 but yes 2854 similar to, looks good.

**Comment by dnmeid** [comment]
> Didn't read the whole of 2387 but yes 2854 similar to, looks good.

OK, then I close this as being a duplicate.
