### ISSUE TITLE
[BUG] Companion 3.5 betas not launching following commit 8d559c9

### ISSUE THREAD

**Issue by hussra** [bitfocus/companion#3105]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I found the latest 3.5 betas not launching on my CompanionPi test installation, and noted similar reports in the Facebook group.

After trying multiple specific betas, the last which launches is https://s3.bitfocus.io/builds/companion/companion-linux-arm64-3.5.0+7479-main-c08c991b.tar.gz and the first which fails is https://s3.bitfocus.io/builds/companion/companion-linux-arm64-3.5.0+7480-main-8d559c95.tar.gz

This seems to point to commit 8d559c9 "feat: add segfault handler library". Checking in /var/log/daemon.log I found the attached entries, which appear to corroborate this.[daemon.log](https://github.com/user-attachments/files/17524105/daemon.log)

### Steps To Reproduce

On a CompanionPi, update to latest beta.
Companion fails to launch.
View error message in /var/log/daemon.log

### Environment (please complete the following information)

- OS: Raspberry Pi OS
- Browser: N/A
- Companion Version: 3.5.0 builds 7480-7491

**Comment by hussra** [comment]
[daemon.log](https://github.com/user-attachments/files/17524109/daemon.log)

**Comment by PhillPower** [comment]
This also occurs on macOS Sonoma 14.7
![Image](https://github.com/user-attachments/assets/72dea530-c0a2-4384-aa1c-1f53ccba2bb7)

**Comment by hussra** [comment]
Windows beta builds are OK (tested v3.5.0+7493-main-462c8ef7 just now.

The same build dies on Raspberry Pi with the same error as before in daemon.log:

> Error: Cannot find module './bin-aarch64/segfault'

**Comment by Julusian** [comment]
I can confirm that the pi ones are working again, and launch on macos
