### ISSUE TITLE
[BUG] Arrow up/down keys don't move cursor between lines in multiline expressions

### ISSUE THREAD

**Issue by dnmeid** [bitfocus/companion#3106]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Arrow up/down keys don't move cursor between lines in multiline expressions.
I think the keys are bound to the selector for variables. If the cursor is within a variable the dropdown opens and you can use arrow up/down to select different variables.
Arrow up/down should at least change lines when the cursor is not inside of a $()-variable, but maybe it would be even better to have up/down all the time change the line if the focus is in the expression field and only change the selection in the dropdown when the dropdown gets the focus (maybe tab can be used for switching the focus when cursor is inside a variable) 

### Environment (please complete the following information)

- OS: Win 11
- Browser: Firefox 131
- Companion Version:3.5.0+7486

**Comment by Julusian** [comment]
fixed
