### ISSUE TITLE
[BUG] Problem with undefined elements of arrays read from user variables in expressions

### ISSUE THREAD

**Issue by dnmeid** [bitfocus/companion#3108]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Expressions do support the usage of arrays like `let arr = [3,4,5]; arr[1]` or `$(internal:custom_array)[1]`.
When I access an existing member of the array both versions work.
When I access an out of bounds index, the array declared in the expression correctly returnes `undefined`. E.g. `let arr = [3,4,5]; arr[42]` results in undefined.
When I do the same with an array stored in a variable, like `$(internal:custom_array)[42]`, and this is the only statement the button also shows the text "undefined", but it seems not to be `undefined`.
`$(internal:custom_array)[42] === undefined` results in `false`
```
let arr = $(internal:custom_array)
arr[42] === undefined
```
results in `true`

### Expected Behavior

`$(internal:custom_array)[42] === undefined` should results in `true` if the array stored in $(internal:custom_array) has no element stored at position 42.

### Environment (please complete the following information)

- OS: Win11
- Browser: Firefox 131
- Companion Version: 3.5.0+7501

**Comment by Julusian** [comment]
fixed
