### ISSUE TITLE
[BUG] Connections context menu button not working on MacOS Safari

### ISSUE THREAD

**Issue by leonreucher** [bitfocus/companion#3109]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

In the connections list, the button on the right with the three dots (for showing logs, etc.) is not working - the context menu is not showing when using Safari - Chrome is working fine.

![Image](https://github.com/user-attachments/assets/e4fd9569-930a-4c7c-92f0-905f66492fc7)

### Environment (please complete the following information)

- OS: MacOS
- Browser: Safari
- Companion Version: 3.5.0+7500

**Comment by Julusian** [comment]
What version of macos and safari?

**Comment by Julusian** [comment]
Oh, I can reproduce this with macos 15 and 18.0.1
It worked fine in 3.5.0+7486-main-abb30808

**Comment by Julusian** [comment]
This is fixed now

I suspect there are more issues lurking from the change that caused this, but the change had to be done at some point
