### ISSUE TITLE
Offline Programming / Simulate Connections/Instances

### ISSUE THREAD

**Issue by jackcrombie** [bitfocus/companion#311]
To allow offline programming of some modules, the ability to simulate a connected device would be very helpful. This wouldn't be practical for all, but something like a BMD Video Hub, or ATEM, it would allow you to specify which model you will connect, and program buttons appropriately.

Allowing a user to select 1ME, 2ME, TVS, 4K Production Studio would allow you to program more than 8 inputs, Auto/Take buttons for ME2-4.

With routers, specifying the size 12x12, 16x16, 16x32, etc would be enough to assist with offline programming of these devices too.

**Comment by jackcrombie** [comment]
I'm sure there are other use cases, but this is the one I'm faced with tonight 😉

**Comment by willosof** [comment]
Sorry, that would need us to make a simulator app for every single thing we support, this won't happen. Unless you're paying :)
