### ISSUE TITLE
[BUG] Atem Micro Panel not detected by CompanionPi, while it works on Apple Silicon Mac and Windows

### ISSUE THREAD

**Issue by Marlow925** [bitfocus/companion#3111]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When plugging an Atem Micro Panel into a RasPi 4 running CompanionPi, the underlying Linux distribution does detect it.

Excerpt from dmesg:
[ 425.007073] usb 1-1.1: new full-speed USB device number 3 using xhci_hcd
[  425.114659] usb 1-1.1: New USB device found, idVendor=1edb, idProduct=bef0, bcdDevice= 1.00
[  425.114676] usb 1-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  425.114680] usb 1-1.1: Product: ATEM Micro Panel
[  425.114684] usb 1-1.1: Manufacturer: Blackmagic Design
[  425.114687] usb 1-1.1: SerialNumber: DE059BC79A0A4DCDACBA7D8F07A015BF
[  425.132241] hid-generic 0003:1EDB:BEF0.0001: hiddev96,hidraw0: USB HID v1.10 Device [Blackmagic Design ATEM Micro Panel] on usb-0000:01:00.0-1.1/input2

However a USB rescan does not show it as an option.

And yes, I have made sure, that "Enable connected Blackmagic Atem Micro Panel" in Settings is toggled on.

### Steps To Reproduce

1. Plug in Atem Micro Panel
2. Go to "Settings" and ensure that "Enable connected Blackmagic Atem Micro Panel" is toggled on
3. Go to "Surfaces" and click "Rescan USB"

The Atem Micro Panel will not show up.

### Expected Behavior

1. Plug in Atem Micro Panel
2. Go to "Settings" and ensure that "Enable connected Blackmagic Atem Micro Panel" is toggled on
3. Go to "Surfaces" and click "Rescan USB"

The Atem Micro Panel should show up. It does so on Companion for Apple Silicon Mac and Windows.

### Environment (please complete the following information)

- OS: Windows 10
- Browser: Chrome 130.0.6723.70 (Official Build) (64-bit)
- Companion Version: 3.4.2

**Comment by Julusian** [comment]
This is fixed in v3.4.3 (building now)
