### ISSUE TITLE
[BUG] Additional config fields on existing connections

### ISSUE THREAD

**Issue by peternewman** [bitfocus/companion#3114]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I guess this may fall in a grey area between bug and feature request...

### Steps To Reproduce

1. Create a connection for a module
2. Modify the module's code to add another config field
3. Create a second connection for the module
4. Note how the following is true
5. a - The original connection doesn't have the field
    b - The new connection does have the field

### Expected Behavior

Both connections have the field/behave the same.

### Environment (please complete the following information)

- OS:
- Browser:
- Companion Version:

### Additional context

As I see it, a field can be in a few states:

1. Non-existent in the hash
2. Existing but undefined
3. Empty
4. Populated with the default value
5. Explicitly set to another value

It would be nice if we ended up in the same state regardless of connection creation versus update of the module.

Maybe I'm actually asking for a feature request of a generic upgrade script which adds any missing new fields I've added?

**Comment by thedist** [comment]
Unless I'm misunderstanding your issue, this is what Upgrade Scripts are for.

For example in Step 2 where you make changes to the config fields or add new ones, you should also be creating an Upgrade Script that will upgrade any existing connections to have those new fields with some value, delete old fields, or modify existing fields in some way.

Alternatively if you don't use an Upgrade Script that ensures all fields would exist and be valid, you would need to develop your module in a way to handle a config value potentially being undefined, or something other than intended.

**Comment by peternewman** [comment]
I was really just proposing a helper function, I guess for use in an upgrade script, or one that runs by default or something. Maybe it should just be something in companion-module-base?

Maybe I've just been lucky, but all the stuff I've added to modules so far has just been additional e.g. adding a port in case someone wants to override it, or adding some polling and a configurable window for that.

From what I can tell you can't set a field to undefined from the config window, so even if it started off as such, you wouldn't ever be able to get it back to that state.

It just seems like a simple upgrade script can be reasonably error-prone and could instead be wrapped up into a helper function for the script where I just need to list the names of new fields. or maybe a version that just calls that for all config fields. It seems like I need to do the following:

1. Confirm the field doesn't exist/isn't defined
2. Extract its default value from the config part (if present)
3. Set the value to its default
4. Repeat for any other new fields

Which feels like it's got a few potential edge cases in terms of type comparisons and falseness etc. Whereas a helper function could ensure something that's clean and works is written once and used by most people in 95% of situations. Plus it feels to me like these upgrade functions are quite a faff to test, unless I've missed some trick.

**Comment by thedist** [comment]
> It just seems like a simple upgrade script can be reasonably error-prone

What part of upgrade scripts are you struggling with that results in these errors? Perhaps the issue is not something that should be solved by automatic upgrades (because of the issues with such a feature as previously stated), but perhaps if people are struggling with an upgrade script perhaps a more appropriate feature request would be to help with those pain points because upgrade scripts should be fairly straightforward and most errors that I've seen modules encounter are from modules doing updates without also writing any upgrade script.
