### ISSUE TITLE
[BUG] Drag and drop button actions in Duration Group on MacOS

### ISSUE THREAD

**Issue by ChrisSW58** [bitfocus/companion#3115]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

On Sequoia it is not possible to drag and drop a button action in the duration group using either Safari or Chrome. Nothing happens.

### Steps To Reproduce

1. Create a duration group for a button with 2 or more actions
2. Attempt to move one of the actions higher or lower in the sequence

### Expected Behavior

As with the normal button actions, you should be able to drag and drop an action to a new location in the sequence

### Environment (please complete the following information)

- OS:MacOS Sequoia 15.1
- Browser: Safari and Chrome
- Companion Version: All

**Comment by Julusian** [comment]
I think I've gotten to the bottom of this

**Comment by ChrisSW58** [comment]
> I think I've gotten to the bottom of this

Fantastic. Well done!

**Comment by ChrisSW58** [comment]
@Julusian - Julian, any idea what 3.5.0 beta release this will appear in? Just tested 7523 and it's still not working in it.....

**Comment by Julusian** [comment]
Its in 7521, so that 7523 should work. 

Can you record a video of what you are doing that triggers this? Maybe doing something I didn't test?

**Comment by ChrisSW58** [comment]
[Screen Recording 2024-10-30 at 6.29.00 pm.mov.zip](https://github.com/user-attachments/files/17577429/Screen.Recording.2024-10-30.at.6.29.00.pm.mov.zip)

**Comment by Julusian** [comment]
Oh, so its when they are collapsed, the drag handle simply isn't behaving correctly..

For reference the bugs I found and fixed yesterday were:
* When dragging an action between the groups, other actions could follow the one being dragged
* When dragging an action between groups, it would sometimes refuse to drop into a group. (eg picking up from down, hovering over up worked ok, back to down wouldn't drop)

**Comment by ChrisSW58** [comment]
Sorry I wasn’t more precise - and it sounds like you e corrected a load of minor faults!

**Comment by ChrisSW58** [comment]
Congratulations - fantastic detective work!
