### ISSUE TITLE
[BUG] Rotate right actions can't be fired from a trigger

### ISSUE THREAD

**Issue by SetMonkey13** [bitfocus/companion#3118]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When making a trigger, and setting the internal: Button: Trigger rotate right, the rotate right doesn't execute when the Trigger/Schedule happens.  All the other actions happen except for the rotate commands.

### Expected Behavior

It should rotate so that the task associated with the know happens.

### Environment (please complete the following information)

- OS: Windows 10
- Browser: Chrome
- Companion Version: 3.4.2

**Comment by dnmeid** [comment]
I just tried and it works without problems, maybe you have some wrong settings.
