### ISSUE TITLE
Pre and Post scripting

### ISSUE THREAD

**Issue by Bobby-McGonigle** [bitfocus/companion#3120]
### Is this a feature relevant to companion itself, and not a module?

- [x] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the feature

Hello

Working with variables, I often have to find a way to parse information or do a bit of math here and there manually depending on the button press.

Like in Postman, it would be great if we had pre and post scripting capabilities to manipulate data in some fashion.

This could be it's own standalone module in theory and add them in as a part of a sequence or press/release actions, but I think it could be very useful

A small code editor that's able to access variables both read and write

### Usecases

- Parse responses from HTTP Environments
- Increment and Decrement Values
- Process Data from 1 module to be ready fro another
- Dynamically build UI elements based on XYZ changes in an environment

**Comment by Julusian** [comment]
This sounds like something already doable with expressions?

Doing things after other actions is not very reliable currently due to the execution order, we are already considering changing that behaviour #2882

And it will be nicer once #1909 is done too.

Does that cover everything?

**Comment by Julusian** [comment]
As summarised in my comment above, this is either covered by other issues, or needs further clarification on what it is asking for

**Comment by willtom65** [comment]
I wonder if there might be mileage in adding a full user accessible scripting environment. Perhaps enable /disable in the settings a scripting tab so it isn't confusing for more basic users.

I'm imagining an internal action called run script, or run function or something, with a drop down showing named custom scripts that have been created by the user. Along with a data field in case you need to pass data to them.

Within the scripting tab, either a text based IDE to run custom javascript routines, allowing for more logic and flow control than the expressions available in the main buttons. Or perhaps looking at QSYS block controller for inspiration of a drag/drop scripting environment.

Each script should be able to trigger actions/receive feedback from any modules loaded into companion, and access any variables of the main system as global variables. Maybe local variables should be allowed for indexing a for loop etc but these variables would not be available in the main part of companion. Perhaps http requests/sending generic tcp/udp etc could be allowed from scripting, or perhaps those ought to stay within a dedicated module.

Just a consideration anyway. I have recently found a couple of instances where I need more logic than companion allows and have to write an external routine in QSYS or visual studio which I then trigger from a module action from companion

**Comment by thedist** [comment]
With that level of scripting you're pretty much at the point where it would just be easier to develop your own module. For example one of the things I do both for my local setup and any event I work is have a my own utilities module that I just put in the companion module dev folder, and it provides me all the functionality I need for my specific workflow tasks, as some general use tooling.

**Comment by Julusian** [comment]
In 4.0 there will be an if-statement action, so we are going down the route of building-block programming.

I am hesistant to add code like scripting, simply because it doesn't fit into how we lifecycle actions and feedbacks. especially for feedbacks where we tell the module what feedback instances we have and their options, and let them report back the value whenever it changes. this doesnt nicely fit into a code flow
