### ISSUE TITLE
[BUG] Variable comparison not operating in trigger

### ISSUE THREAD

**Issue by ChrisSW58** [bitfocus/companion#3124]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

![Image](https://github.com/user-attachments/assets/fc73577b-9530-490f-8c8f-1dc16e343078)
 This trigger works as expected in 3.4.2. In 3.5.0 beta version 7529 the trigger does not fire.

### Steps To Reproduce

Store current minute
Compare current minute to stored minute
When not =, action trigger

### Expected Behavior

Trigger should operate every minute

### Environment (please complete the following information)

- OS:Mac OS Sonoma
- Browser: Safari
- Companion Version: 3.5.0 beta version 7529

**Comment by dnmeid** [comment]
I just checked this with the current beta and for me the trigger works as expected. (it does show a different version string because I'm running from git main branch)
![Image](https://github.com/user-attachments/assets/959a840c-a9a9-4017-b9a9-69df977bd11f)

**Comment by ChrisSW58** [comment]
I will accept it's closed and have coded around it but  it does not explain why the same code runs correctly on 3.4.3 and not the beta. It may come back from someone else.

**Comment by dnmeid** [comment]
It does run correctly on the beta as well.

**Comment by Julusian** [comment]
@ChrisSW58 could you provide an export of a broken trigger?
That will help ensure we are testing the same thing you are seeing

**Comment by ChrisSW58** [comment]
@Julusian  - here's the config file. the same config works on 3.4.3, and doesn't on 3.5.0 beta 7529. Top right on page 1 you see the time. Works fine when started.(The triggers are to convert from 4 digit 24 hour to 3/4 night with am/pm). The trigger which does not fire is the one called 'Time-Minute Change'. I've recoded it and it's working, but this is the code which doesn't, so something odd is happening between the 2 releases. Thanks Julian.

[Chris-iMac.local_custom-config_20241027-0917.companionconfig.zip](https://github.com/user-attachments/files/17608672/Chris-iMac.local_custom-config_20241027-0917.companionconfig.zip)
