### ISSUE TITLE
[BUG] 3.5.0+7549 When upgrading to Beta all pages of buttons disappear

### ISSUE THREAD

**Issue by ericbusby77** [bitfocus/companion#3129]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When I upgrade from 3.4.3 to 3.5.0+7549 (latest beta) on my Raspberry Pi Companion instance, all the pages disappear except the first one. When I downgrade back to 3.4.3, thaey all come back.

### Steps To Reproduce

Run sudo companion-update
Select Latest Beta
Check web interface and find 1 page of buttons
Run Sido companion-update again
Select Latest Stable
Check web interface and find all 99 pages back

### Expected Behavior

I would expect the 60+ pages of buttons to remain after the upgrade. Especially since downgrading brings them back

### Environment (please complete the following information)

- OS:Debian 11 (Bullseye)
- Browser:Safari
- Companion Version:3.4.3 and 3.5.0+7549

### Additional context

The installation is a clean install of Debian via the  Raspberry PI Imager then installed Companion and the settings were restored from a backup, if that matters.

**Comment by krocheck** [comment]
@ericbusby77 would you be able to provide me your 3.4.x db file or the export/backup.  I'd like to probe the upgrade process.

**Comment by ericbusby77** [comment]
@krocheck [CompanionPi_custom-config_20241105-1309.companionconfig.zip](https://github.com/user-attachments/files/17637302/CompanionPi_custom-config_20241105-1309.companionconfig.zip)

**Comment by Julusian** [comment]
Did that one page of buttons match what you were expecting?
I am wondering if you have done is:
* launch 3.5 beta, creating a 3.5 config
* launch 3.4.3, creating and building a config
* launch 3.5 beta again, reusing the earlier 3.5 config

We do this because when going from 3.5 -> 3.4 we can't carry the config across, so this makes the behaviour consistent in both directions. desktop companion will show a warning, but there isnt a suitable way to do this on pi

**Comment by ericbusby77** [comment]
@Julusian  Yes, that first page of buttons looks correct. 

That seems like a plausible explanation for what I'm seeing. I tried to run 3.5 first, found it wouldn't import the buttons (a bug that has been fixed, I believe), then downgraded to 3.4 and imported the config. Now when I try to upgrade, it looks like the old layout from when it wouldn't import the configured pages correctly.  How do I delete the old 3.5 config in my Pi install? Is that all I need to do, then I can upgrade from 3.4 and it will create the new config?

**Comment by ericbusby77** [comment]
I re-read your message and then exported from 3.4 and upgraded to 3.5 and re-imported. Seems to all be working as expected now.

**Comment by Julusian** [comment]
Cool, sounds like everything is working as intended then.

>  How do I delete the old 3.5 config in my Pi install? Is that all I need to do, then I can upgrade from 3.4 and it will create the new config?

Yes, deleting the existing 3.5 config will cause it to reupgrade from 3.4. Its stored at `/home/companion/.config/companion-nodejs/v3.5`
