### ISSUE TITLE
Enable/Disable actions in triggers and buttons as actions

### ISSUE THREAD

**Issue by aiverse** [bitfocus/companion#3135]
### Is this a feature relevant to companion itself, and not a module?

- [x] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the feature

Enable acting on toggles of actions in buttons and triggers via the internal actions of companion. (basically, make a button act on the little slider behind each action to turn it on and off)

### Usecases

This would avoid having to build the same trigger twice except for a single difference, and thus would eliminate having to maintain two almost identical triggers, which can be challenging once they grow in complexity. The same argument can be made for complex button actions, and would keep the amount of variables and variable checks down to a manageable level.

**Comment by Julusian** [comment]
We intend to handle this with https://github.com/bitfocus/companion/issues/1052
It's partner https://github.com/bitfocus/companion/issues/372 was tackled in 3.4, I am hoping to start looking at #1052 soon

**Comment by aiverse** [comment]
oh amazing, thank you.
i shall sit on my stack of copy/pasted triggers and patiently wait :D
