### ISSUE TITLE
[BUG] Companion changing network hostname on Mac OS

### ISSUE THREAD

**Issue by Lukeb873** [bitfocus/companion#3139]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Since updating Companion to 3.4.3 and satellite to v1.10.0 I'm having an issue where companion is force changing the network hostname of our Mac devices. It's not changing the device name, but it is changing the network hostname. This is an issue as a few of our computer run pro presenter with NDI output. We have to re adjust the input signal every time because of this. I believe this to be an issue with satellite and not the main companion module, because it is not happening to the computer acting as the "server" only the satellite. But because they where updated at the same time, I can't say which issue it's on. I've tried to attach an image of the exact error I get. 

![Image](https://github.com/user-attachments/assets/152bb1ad-6c5a-42c5-8172-0c51e0cc18ae)

### Environment (please complete the following information)

```markdown
- OS: Mac OS Sonoma 14.5 on M2 Pro 16GB for Satellite; Ventura 13.2.1 on M2 Pro 32GB for Companion Server
- Browser: FireFox
- Companion Version: V1.10 Satellite
```

**Comment by Julusian** [comment]
> Since updating Companion to 3.4.3 and satellite to v1.10.0

What versions where you using before?

How often is this happening?

You could try going into the satellite settings and disabling `MDNS Announce`. If it is satellite causing it, then disabling that should stop it happening

**Comment by Lukeb873** [comment]
Hey Julian,

I honestly can’t remember what version we were using before. We don’t update super crazy often, so I typically don’t keep track of the old installations.

I’ve mainly noticed it on restart of the machine. I’m sure if I quit satellite and re-opened it, I would get the same error.

Turning of MDNS Announce has seemed to fix it. Was this added in? if so, what exactly is the point of it and what am I losing by having it off?

I updated our youth room and had this issue, but really didn’t think much of it because it was only the network hostname and not the device name. That machine only outputs SDI, but when I updated our auditorium machine that outputs SDI and NDI, it became a larger issue due to us having to rescan NDI inputs and reassign it to our media server every time the CG’s name changed because of companion.

Thank you!

Luke Bower
Production Year Long Intern /// The Crossing
thecrossing.church<https://thecrossing.church>

From: Julian Waller ***@***.***>
Date: Wednesday, November 13, 2024 at 4:13 AM
To: bitfocus/companion ***@***.***>
Cc: Luke Bower ***@***.***>, Author ***@***.***>
Subject: Re: [bitfocus/companion] [BUG] Companion changing network hostname on Mac OS (Issue #3139)

Since updating Companion to 3.4.3 and satellite to v1.10.0

What versions where you using before?

How often is this happening?

You could try going into the satellite settings and disabling MDNS Announce. If it is satellite causing it, then disabling that should stop it happening

**Comment by dtrench** [comment]
Just experienced this on site. Companion v4.2.6, Satellite v2.8.0, MacOS 15.7.4. New setup using NDI Plugin for AfterEffects. All working fine until Satellite is launched and then the hostname error appears. Sometimes the number will jump up by a few dozen and need re-assigning on the NDI receiver. Have disabled MDNS based on this post and will continue to monitor.
