### ISSUE TITLE
Grouping of multiple Stream Decks when used with Elgato Stream Deck software

### ISSUE THREAD

**Issue by Marlow925** [bitfocus/companion#3140]
### Is this a feature relevant to companion itself, and not a module?

- [x] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the feature

The grouping of multiple Streamdecks (where you can offset a second, third and fourth Stream Deck and they switch pages together), that was introduced in Companion 3.2, doesn't work when using Companion in conjunction with the official Elgato Stream Deck software.

The limitation being, that the Elgato software only reports one Streamdeck.

This could however be achieved, if more buttons were added to the Elgato Streamdeck Plugin. So buttons 33 through 64 for example, or more.

Or maybe the offset (H/V) could be configured in the individual button.

**Comment by Julusian** [comment]
> This could however be achieved, if more buttons were added to the Elgato Streamdeck Plugin. So buttons 33 through 64 for example, or more.

The plugin was updated in May 2024 (coinciding with 3.3.0 of companion) to support the new coordinate based button numbers, and in doing so allows this.
