### ISSUE TITLE
CompanionPi triggers not working

### ISSUE THREAD

**Issue by austgresh** [bitfocus/companion#3141]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I have found similar issues but nothing that has led me to a solution.  

Background/set-up; I have several studios in a school set up with a computer that instructors log into and a projector that projects the computer screen on the wall.  I have streamdecks connected to a RaspberryPi that is running Bitfocus Companion.  This way the stream deck always works even if no one is logged into the computer.  I use it to control turning the projector on/off and move a camera in the room.  The projectors, computer, RaspberryPi, and cameras are all plugged into the same network via ethernet cables to the wall ports.  This all works fine but I have come in on a Monday and found the projectors running meaning they have just been on all weekend while no one was here.  In order to save the projector lifespan, I am trying to get the streamdecks/companion to automatically send an off signal each night at around 11:00pm.  

I already have an "off" button that will turn the projector off.  I tried to set up a trigger that will press the "off" button via 'time of day' type.  I also created a button to the side that displays the internal time (which is several hours off my current time zone).  I set up 24 identical triggers except the time adjusts by 1 hour and 1 min for each one.  Meaning it should trigger at what the SD thinks is 01:01:00 then at 02:02:00 and so on.  IE; regardless what timezone it thinks it is in, one of the triggers should go of over the course of 24 minutes.  I even set all the triggers to run daily in case it is on the wrong day somehow.  I turned the projector on before the first trigger should run and sat there for 26 minutes, nothing.  

I am currently running version 2.2.0 because I first flashed the CompanionPi a while back.  I haven't had any problems with any other button functions when you operate the SD in the studios.  

Because I am running these on a RaspPi and they are not hooked up to a central server or computer (basically operating like a very versatile touch panel control in each room that isn't Crestron), I can't just run a script on my computer to send an off signal or anything like that (at least not that I can think of).  

Am I missing anything with the triggers not working or is there a different way I can achieve this goal to turn off the projectors at night?

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by Julusian** [comment]
2.2.0 is well over 2 years old by now, it was released in march 2022 with a majority of the code having been rewritten since then.
I do remember that the time of day triggers in versions prior to 3.0 would sometimes not fire due to the clock skipping a second.
Beyond that I honestly don't have any ideas here, I have no memory of how the code worked. It is also worth noting that 2.2.0 was the first release that included triggers.

The only advise I can give is to see if it works any better in the latest version

**Comment by austgresh** [comment]
@Julusian Thank you for the information.  Realizing just how out of date the other SDs are and that it was the first version that included the triggers motivated me to move forward with the updates.  The good news is that in my experimenting with one SD with the new version I found out that not only was I able to do what I wanted to trigger a projector off based on time of day but I could have one SD that triggered all projectors in the building.  So not only did it end up working much easier than I even thought, but I only really needed to update one SD.  I will still go through and update all of them but now I have more time to do that.
