### ISSUE TITLE
[BUG] Companion crash on clicking Developer Settings multiple times

### ISSUE THREAD

**Issue by ChrisSW58** [bitfocus/companion#3151]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

If you click on the Companion window, Developer Settings 4 times, Companion crashes stating "Unable to start - Companion is unable to start". in a dialog box.

Interestingly in beta 7569, it crashes with only 3 clicks!

### Steps To Reproduce

1. Click on Show/Hide window to show the Companion Window
2. Click on the Developer Setting cogwheel 4 times
3. Companion app crashes as stated above

### Expected Behavior

No crash!

### Environment (please complete the following information)

```markdown
- OS:Mac OS Sequoia
- Browser: Safari 18.2
- Companion Version:3.5.0 beta version 7574
```

**Comment by haakonnessjoen** [comment]
@Julusian maybe add a delay before  it can be clicked again? If I guess the reason for this bug correctly :P

**Comment by ChrisSW58** [comment]
It's not a major issue but I thought I would raise it in case it is symptomatic of more basis memory management problems or something.

**Comment by Julusian** [comment]
either a delay, or simply resetting `restartCounter` to 0 would do it.

I think its simply not tracking that the restart performed when clicking the developer button was an intentional restart, so it gets interpreted as a crash.
