### ISSUE TITLE
Request: Documentation of trigger events

### ISSUE THREAD

**Issue by Coupe70** [bitfocus/companion#3153]
### Is this a feature relevant to companion itself, and not a module?

- [x] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the feature

Very tiny request:
The 'getting started' documentation of triggers (getting-started#3_config/triggers/trigger_setup.md)
should clearly mention that trigger events follow OR logic (not AND logic) / each single event in the list runs the rest of the trigger (-> conditions -> actions).

**Comment by Coupe70** [comment]
`This defines when the trigger to be executed`

Well, what can I say?
I wouldn't post here if this would have been a clear 'OR' for me.

**Comment by Julusian** [comment]
Hopefully this is better:
```
This defines when the trigger will be executed.  
  The trigger will be executed when any of these events occur.  
  Common events are **Time interval** and **On variable change**
```
