### ISSUE TITLE
[BUG] raspberry shows system time, not local time

### ISSUE THREAD

**Issue by fbosman** [bitfocus/companion#3156]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

the internal veriables of the raspberry installation can also show the time of day. They reflect the system time, not the local time

### Steps To Reproduce

show internal variables on a pi installation

### Expected Behavior

show the local time, or add additional variables with the local time

### Environment (please complete the following information)

```markdown
- OS:
- Browser:
- Companion Version:
```

**Comment by thedist** [comment]
If you open the 'Getting Started' page in the Companion Web UI, go to `Secondary admin controls > Expressions > Functions` in the menu, and then scroll down there's several Time related Expression functions that will allow you to convert the time given by the Companion system, into whatever format or offset you need.
