### ISSUE TITLE
New Trigger  Condition "internal: Variable: On Value Change"

### ISSUE THREAD

**Issue by phillipivan** [bitfocus/companion#3157]
### Is this a feature relevant to companion itself, and not a module?

- [x] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the feature

A new trigger condition that is momentarily true when a selected variable changes value.
There are ways to achieve this at present but they are not very efficient (Comparing two variables, with the "Against" variable being a custom variable that is updated with an action in the same trigger to the value of the "Compare" variable).

### Usecases

Basic logic building block.

**Comment by thedist** [comment]
Can you please expand on your feature request, you haven't actually given a proper use case as to what you're actually trying to achieve, why you can't use the on variable change event? how long you expect `momentarily` to be? Do you want it to be just long enough for 1 trigger to evaluate the condition? What if multiple triggers are using that, should it be momentarily true for all of them, or just one, and if one, which? What event do you plan to use that would take advantage of this condition in a way that the condition is momentarily 'true' at the precise point in the NodeJS event loop after the original event is triggered?

**Comment by Velikyi** [comment]
Why can't you just do "on variable change"? If you need something to be true momentarily when it's triggered, that would be best achieved in the logic of the action and not in the logic of the trigger (e.g. delays and resets)

**Comment by phillipivan** [comment]
Thank you @Velikyi  I was looking for it in conditions rather than events.
