### ISSUE TITLE
Trigger remote Companion buttons without Satellite

### ISSUE THREAD

**Issue by bramsteenbrugge2** [bitfocus/companion#3158]
### Is this a feature relevant to companion itself, and not a module?

- [x] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the feature

Add connections to other instances of Companion on the network, to retrieve certain buttons of those Companion instances.A bit like Companion Satellite, but with more control and customization.

I haven't found a way to do this, so please correct me if I'm wrong if this already exists.

### Usecases

Say I have a production with multiple rooms, and each room and their director have their own Companion setup. In the MCR, there's another Companion running with the video routing setup. The director's Companion does not have access to the video router itself. They should be able to copy 'remote buttons' from the MCR's Companion instance, so they can trigger some routing themselves if they want to. When they trigger the buttons on their local Companion, they effectively trigger a button on the MCR Companion.

**Comment by josephdadams** [comment]
Bitfocus Companion Cloud. It does this perfectly.

**Comment by bramsteenbrugge2** [comment]
Sorry, I was talking about a local network, assuming we don't have access to internet connection, only locally.

**Comment by bramsteenbrugge2** [comment]
Not sure if this can be reopened agaiin, given this new information?

**Comment by thedist** [comment]
Is there a reason you can't use a single Companion server that is utilized by each room, rather than using multiple Companion servers?

**Comment by bramsteenbrugge2** [comment]
Yes several reasons, most of them are related to network access and security issues. 
Also, a centralized approach has a single point of failure, which would mean if our single Companion server goes down, the entire conference stops.

I don't think implementing this is a bad idea, the idea of borrowing buttons from other Companion servers might be really helpful in lots of situations, and the fact you'll be implementing this in Companion Cloud shows you guys somewhat agree. But the biggest issue with Cloud is I'd have to rely on internet connectivity, which is a big no-no in some productions where network security won't allow access to the internet.

If there was a way to run the Companion Cloud service on-premise, this issue would be resolved.

**Comment by thedist** [comment]
If the Companion servers being run in each room don't have access to control the video router in the MCR for 'network access and security issues' reasons, then wont accessing buttons on the Companion server running in the MCR to in turn control the video router essentially be circumventing those network/security restrictions that are intended to be in place? As if you can access a remote Companion server from each room then you can access everything that it can access as Companion exposes those connections to whoever connects to it.

Additionally to the issue of a single point of failure, if the Companion server in the MCR goes down then once again all other rooms will lose access to the video router.

**Comment by bramsteenbrugge2** [comment]
The examples I'm giving are what they are - examples. I'm not saying that this is the exact setup we are using and that these are the exact network security rules that are implemented, because doing that would mean I'd have to write an entire essay on our practices and on those of the network admins, which they also probably wouldn't appreciate. 

To try to counter your absolutely valid point, let's say the fact that the network rules that are in place have nothing to do with the av setup and that they have an accidental effect of not being able to reach the video router and we'd need to bypass this by sending commands to the MCR Companion server. Let's also say the network admins give us a go to do this.
You can talk about the fact that this would be poor network design, but again, I'm talking examples, even though this is something that might happen in the real world because of a plethora of reasons, constraints, stability issues, or even plain time shortage.

And indeed, if the MCR Companion server goes down, we'd have no more way of routing video, but at least the director is still able to control his own room. 

Let's actually take this to make an example of a totally different scenario. We might have 2 companion servers, a main and a backup, having the exact same configuration except for the fact the backup doesn't have it's instances enabled. Our user Companion triggers them both with 1 button, and if the main goes down for whatever reason, the backup will be under the same button (after enabling the instances, which surely could be automated if main doesn't respond after x amount of ping or some other solution - you get my point).

Another example delves into the QOL of the user. Let's say there are 10 rooms with all completely different setups, the only thing they have in common is having to have access to the video router inside the MCR. This would mean we'd have to set up the video router instance 10 times, and configure the specific buttons 10 times (as each room will need to do it's own, different video routing). With the feature I'm requesting, they can just copy their buttons from the MCR Companion that had to be set up only 1 time. Yes, you could argue to set up all buttons on one companion and import these pages to the 10 different Companion configs and then manually delete the ones you don't need and reorder them to fit the workflow of that specific room, but that would still be less handy than to send a remote button press, in my opinion.

What everything comes down to, is the fact that I'd like to see a Companion Cloud feature on the local network level/peer-to-peer Companion integration. I'm sure there are way more usecases for this than mine alone. 
What I and many others absolutely love about Companion is the flexibility it gives us. This feature would, in my eyes, expand the flexibility enormously, even if my examples aren't the strongest. 
I'd hoped you guys would see the same benefits.

**Comment by josephdadams** [comment]
I re opened - I recall this being requested before so if I can find that issue number i will tag one of them as a duplicate and close it then.

**Comment by Julusian** [comment]
@josephdadams perhaps https://github.com/bitfocus/companion-module-requests/issues/304, which has also been closed because of cloud?

**Comment by dnmeid** [comment]
Yes, I'd say this is a valid request and it is best covered by a module. A module to interact with a different Companion on the local network. Maybe this will use a combination of Satellite protocol and other API to access buttons and variables.
The best place for this request would be in the https://github.com/bitfocus/companion-module-requests
The https://github.com/bitfocus/companion-module-requests/issues/304 has been closed because it was in the scope of cloud, but this one is about local network. So please open a request there

**Comment by bramsteenbrugge2** [comment]
@dnmeid thanks, i posted in https://github.com/bitfocus/companion-module-requests/issues/1692#issue-2687677017
