### ISSUE TITLE
GrandMa Module

### ISSUE THREAD

**Issue by ashjmckenzie** [bitfocus/companion#316]
Could we clone the GranaMa module and add a port number to the configuration and then we would have a generic telnet module?

**Comment by haakonnessjoen** [comment]
The reason we do not have a generic telnet or tcp module is to get people request the devices instead. That way we can make modules that makes it easier for new users to control their equipment, and also we can do more. Like feedbacks (changing colors of buttons from what is happening on the devices, etc). What device do you want to control with telnet?

**Comment by ashjmckenzie** [comment]
Truthfully, I've already filed a request for the Application https://github.com/bitfocus/companion/issues/297 I was just trying to get something to help my limp through.  Appericate all the devolopment!
