### ISSUE TITLE
[BUG] Trigger "Custom Variable: Set with expression" allows use of $(this:...) variables, but they have no value ($NA)

### ISSUE THREAD

**Issue by MattRogish** [bitfocus/companion#3161]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Triggers allow the use of $(this:..) variables when setting another variable, except they're always blank. This behavior makes sense (because how would they be set?) but is confusing that I have access to those variables.

Note that even if pressing a button initiated this trigger the values are still blank (which could be a bug, maybe, but I don't know if that's supposed to "work" or not).

### Steps To Reproduce

1. Create a trigger to "Custom Variable: Set with expression". 
2. Type` $(this...)` and autocomplete shows you can refer to the various `$(this:...) `variables (Column, Row, Step, etc) 
3. When the trigger runs the values for these are all $NA

### Expected Behavior

If I cannot use these variables, please remove them from autocomplete. If there is a particular way I can use them, please include that somewhere handy to avoid confusion.

### Environment (please complete the following information)

```markdown
- OS: MacOS 15.1.1
- Browser: Safari 18.1.1
- Companion Version: 3.4.3
```

**Comment by Julusian** [comment]
This should be better in the betas
