### ISSUE TITLE
Allow more bottons on the touch screen of the Stream Deck + (Plus)

### ISSUE THREAD

**Issue by jtjart** [bitfocus/companion#3168]
### Is this a feature relevant to companion itself, and not a module?

- [x] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the feature

While configuring my Stream Deck +, I noticed that there are spaces between the four available buttons on the touch screen. These spaces are approximately the same size as the buttons themselves.

Would it be possible to utilize these three spaces to create a row of seven buttons on the touch screen?

**Comment by Julusian** [comment]
Unfortonately the answer here is no.

With the way we currently do it, everything maps through to the grid nicely, if we were to change that it wouldn't be nice to figure out how they translate to the grid, as we would need to not change the position of the current 4 to avoid breaking user configs.

Long term, there is a plan to support drawing at different aspect ratios, which will mean we can draw to the full size of the lcd without needing to squeeze in more buttons.
