### ISSUE TITLE
Please add Atem DSK Toggle command "cut" and "auto"

### ISSUE THREAD

**Issue by mindandvision** [bitfocus/companion#317]
**Describe the feature**
Please add a command to cut the DSKs of the ATEM switchers to on or off.  We need also the option to "auto" on or off the DSKs. It would be great if there would also be a feedback of the DSK state that you can chose to display the button state.

**Is this platform dependent (windows, mac, ..)?**
No. Not platform dependent.

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along

**Usecases**
In simply any usecase where you would use the switcher, you would also use the DSKs to display lower 3rds or logobugs or anything else. It's an important feature for any serious production.

**Comment by phelfenbein** [comment]
Your timing is interesting.  This is a feature I've been looking into as well.  As it happens the underlying ATEM communication code fully supports DSKs, as well as a few other things that Companion has yet to implement.  I downloaded the v1.1.1-fix source earlier this week and got DSK control working on my Stream Deck, so I know it can be done.  I didn't figure out how to make a button toggle, currently my implementation requires separate on-air and off-air buttons.  Auto self-resets on the ATEM, so it works like a toggle.  

Sometime this weekend I can make a branch of companion-module-atem and upload my changes.  I'm trying to figure out how to compile it so I can install my version on our production laptop.  I'm also planning to contribute DSK switching to the master branch for inclusion in the next release.

**Comment by mindandvision** [comment]
What I mean by "toggle" is the ability to use the "cut" and "Auto" button for the 2 DSKs. That is basically a toggle function. And I need a feedback option to display the state of the DSK by changing the button color on the Stream Deck.

Cheers

**Comment by cxselph** [comment]
You can do npm run dist to compile a copy of your version of the app in the electron-output folder. If you are happy with everything, I would fork the https://github.com/bitfocus/companion-module-atem repository and submit a pull request with your changes.

**Comment by jerriley** [comment]
Is this fixed in a downloadable version of Companion? If so, which version? (1.4? 2?)
