### ISSUE TITLE
[BUG] `yarn test` since the switch to `vitest` no longer ignores any folders/symlinks added to `module-local-dev/`

### ISSUE THREAD

**Issue by jswalden** [bitfocus/companion#3171]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Running tests for #3170 reports, for me, 42 failing tests -- because I've added ptzoptics-visca and allenheath-sq modules in `module-local-dev/` and I get a bunch of tests failing for "Error: Do not import `@jest/globals` outside of the Jest test environment".

I looked briefly at 9a788033f681def15769734154d73b14d7757f9f which swapped from jest to vitest, and it looks like that swap lost an exclusion of files in `module-local-dev/`.  I assume there's some way to do the same with vitest, that's simply missing now, but I don't know it to write the fix.

### Environment (please complete the following information)

```markdown

```

**Comment by Julusian** [comment]
I've stopped putting my dev modules in that dir, so managed to not notice 😅 
This is fixed now
