### ISSUE TITLE
[BUG] Rotary encoders not working with Elgato plug-in enabled

### ISSUE THREAD

**Issue by fganzevoort** [bitfocus/companion#3178]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Once in 'mixed mode' with the Elgato plug-in enabled (no direct connection to the streamdeck) the rotary encoders do not work on the StreamDeck+ for the rotaries assigned to Companion. 

### Steps To Reproduce

1. Make a rotate action in Companion and assign to an encoder on the Streamdeck+
2. Disable the direct connection to StreamDeck in settings
3. Use the Companion Plug-in in the Elgato StreamDesk app (I'm using 6.8.0) to assign a companion button (i.e. row 2, column 0)
4. Check if the right text appear on the screen 
5. Find that press actions work, rotary actions do not

### Expected Behavior

I expect the rotary actions which are set in the rotate left, and rotate right actions in Companion would work

### Environment (please complete the following information)

```markdown
- OS: MacOS 15.2
- Browser: Safari
- Companion Version: 3.4.3
```

**Comment by Julusian** [comment]
This is working fine in my testing.

What version of the plugin are you using?

**Comment by fganzevoort** [comment]
Hi,

Thank you for looking into this issue. I am seeing version number 3.0.0 installed at the moment, but since I use auto-update I cannot verify it was this version of the plug-in when I tested. Unfortunately I am away from my device, so I cannot test if the issue is persistent.

I will let you know once I am back in the office.

Best,


Floriaan Ganzevoort


a: 	Commelinstraat 232
	1093 VD  Amsterdam
t:	06-43879099

**Comment by fganzevoort** [comment]
Hi,

I am seeing my mistake now. I had to pick row number 3 instead of 2 in the Elgato app -> Companion plug-in  to activate the encoders. In Companion though the actual actions are assigned to row 2.

Best,


Floriaan Ganzevoort


a: 	Commelinstraat 232
	1093 VD  Amsterdam
t:	06-43879099

**Comment by Julusian** [comment]
Ah yes. Thats an easy and understandable mistake.

Its an unfortonate consequence where in the elgato softare the two can't be unpaired, so it simply can't match what we do in compnaion
