### ISSUE TITLE
[BUG] Trigger with conditions is not firing as expected.

### ISSUE THREAD

**Issue by javapgmr** [bitfocus/companion#3186]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

It appears that the triggers are broken in the most current betas.  I have been trying to write a trigger that fires every five minutes if a button hasn't been pressed during that time and if I press a button, reset the timer to 0 and start the timer over.  The trigger conditions below do not ever fire even though the variable change happens every minute (using the generic stopwatch module).  I posted this on the Companion Facebook page and a fellow user validated that this works using the latest stable release.   I am using the v3.5.0+7649 beta.

[Image](https://github.com/user-attachments/assets/8c857dd2-d182-4e2a-b1ab-dc5602230888)

### Steps To Reproduce

Create a trigger using the generic-stopwatch to start a stopwatch, monitor the minutes only value, set a condition to watch the value and when it becomes greater than 4, fire an action to stop and restart the timer.

![Image](https://github.com/user-attachments/assets/dff915b5-673e-48c4-92bc-3376c3825a5f)

### Expected Behavior

Trigger should fire when conditions are met.

### Environment (please complete the following information)

```markdown
- OS: Windows
- Browser: Chrome
- Companion Version: v3.5.0+7649-main-b97f6e34
```

**Comment by javapgmr** [comment]
Sorry, I showed it with one of the events disabled.  With both enabled, it fires every minute.  With the variable change event on the time disabled, it never fires, and with the "on condition becoming true" disabled, it still fired every minute. 

![Image](https://github.com/user-attachments/assets/27625941-1f65-4417-9ac4-1ba8c13736da)

**Comment by MeestorX** [comment]
Correct me if I'm wrong, but your trigger is set to fire every minute after 4 minutes, and I assume that's what it's doing? If you'd like it to fire once every 5 minutes, you'll want to have a formula more like this. (On condition becoming true is not needed).
![Image](https://github.com/user-attachments/assets/82b7947e-fd4d-4b74-92bb-152167c492bd)

**Comment by Julusian** [comment]
Does it work better/worse if you remove (not just disable) the 'on condition becoming true' event?
It looks like [this block](https://github.com/bitfocus/companion/blob/main/companion/lib/Controls/ControlTypes/Triggers/Trigger.ts#L357-L361) of code is flawed, and could be causing at least some of what you are seeing..
That code is ignoring the condition for any execution of the trigger if any of the events are 'on condition becoming true', even if the source of the event was something like 'on variable change'

**Comment by Julusian** [comment]
I've changed how that behaves in the next beta, let me know if it resolves this

**Comment by javapgmr** [comment]
I tested with the "v3.5.0+7656-main-04e8d566" version and in the "On Condition becoming true" and the trigger continued to work as expected.  I believe it is fixed from my perspective.  Thank you!!
