### ISSUE TITLE
[BUG] Expression evaluation not setting button step

### ISSUE THREAD

**Issue by ChrisSW58** [bitfocus/companion#3190]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

The internal Set current step if expression is true was working in 3.4.3, but not in v3.5.0+7656. See attached for expression. The expression evaluates as true when tested alone, but it does not trigger until > rather than =. Expression attached. (Note: This is a config import from 3.4.3 - changing the variable definition to the new format as of 3.5.0 does not make any difference.)

### Steps To Reproduce

1. Increment a variable and compare to an upper limit variable to set step on button
2. Button Step does not change on == comparison

### Expected Behavior

Button Step change on == being true

### Environment (please complete the following information)

```markdown
- OS:MacOS latest version 15.2
- Browser: Safari
- Companion Version:3.5.0+7656
```

### Additional context

<img width="747" alt="Image" src="https://github.com/user-attachments/assets/2b7c524c-20cc-41de-a5f6-c6c4e84e8fea" />

**Comment by Julusian** [comment]
This was an unintentional side effect of #3163 
It is fixed, but the fix looks a little brittle so the bug could reappear at some point

**Comment by ChrisSW58** [comment]
Hi Julian - thanks for the prompt response...a similar issue seems to happen with the 'internal: Button: Set current step if variable meets condition' if you compare 2 variables.
