### ISSUE TITLE
[BUG] Companion modules fail to reconnect

### ISSUE THREAD

**Issue by AJolly** [bitfocus/companion#3191]
### Is this a bug in companion itself or a module?

- [x] I believe this to be a bug in companion

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Companion connections will frequently lose connection, and  fail to reconnect or restart themselves.

![Image](https://github.com/user-attachments/assets/1cc02c75-90c6-4314-a9f7-216bedb8ec49)

 I've been running into this a lot frequently, I mostly noticed it on homeassistant-server, but its impacting http as well.

### Steps To Reproduce

Unsure - possibly due to machine standby?

### Expected Behavior

I expect connections to automatically retry and reconnect  if the connection is lost.

### Environment (please complete the following information)

```markdown
- OS: Win 11
- Browser: All
- Companion Version: Tried in 3.5.0 7656 as well as 3.4.3
```

### Additional context

Debug log: [SkylakeX_2024-12-27-0027_companion_log.csv](https://github.com/user-attachments/files/18257995/SkylakeX_2024-12-27-0027_companion_log.csv)

**Comment by Julusian** [comment]
This isn't really a bug in companion itself, but those modules.

It is known that the homeassistant module doesn't do reconnecting very well https://github.com/bitfocus/companion-module-homeassistant-server/issues/8
The generic-http module doesn't have a persisnent connection though, but I think it sets the status to warning like this when a request fails. So this doesn't sound like a bug to me, but perhaps a request being made after resuming from standby before networking is ready in your os?

I am closing this as there is nothing to do here in companion itself
