### ISSUE TITLE
Backgroundcolor emulator

### ISSUE THREAD

**Issue by casbizz** [bitfocus/companion#321]
Is it possible to set the emulator background to black or a custom color

**Is this platform dependent (windows, mac, ..)?**
NO

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along

**Usecases**
If you not have a streamdeck but use the emulator on your touchscreen of ipad -pc - tablet - phone
![2018-11-05](https://user-images.githubusercontent.com/40021129/47983016-3151d280-e0d2-11e8-8920-608edce3a9fa.png)

**Comment by goblynn93** [comment]
Please! Or at least really dark grey? Thanks!

**Comment by willosof** [comment]
A proper web emulator is very close, hang tight :)
