### ISSUE TITLE
Page Button on Stream Deck

### ISSUE THREAD

**Issue by colmans27** [bitfocus/companion#322]
Hi,

it would be great to have a function on the unused page button of my Stream Deck.
What's about a kind of "Home button" e.g. to jump to a page with a menu of my devices…

Regards, colmans

**Comment by colmans27** [comment]
what's about to link the page button to a page called "0" and a toggle function between the last visited page on the stream deck and this page "0"?

**Comment by josephdadams** [comment]
Closing this as nopagebuttons (2.0) branch is in the works, and there's also already an action in 1.3 bleeds/1.4 that allows you to change the page of the deck via an internal action.
