### ISSUE TITLE
Generic feedback

### ISSUE THREAD

**Issue by theslainman** [bitfocus/companion#326]
**Describe the feature**
Group buttons into feedback groups separated by a unique ID like a number or text string and trigger feedback change on the last button pressed in the group and reset all other buttons in the same group when button is pressed.

**Is this platform dependent (windows, mac, ..)?**
no

**If documentation is required to implement, do you know where to find it?**
Not applicable

**Usecases**
To keep track of what button you last pressed in the group and make use of the feedback feature when modules or equipment doesn't support feedback.

**Comment by willosof** [comment]
Not a bad idea. But I don't know how we would make it intuitive enough?

**Comment by dnmeid** [comment]
Maybe the Companion module can help out. Lets say you have buttons a,b and c. If you add actions at a to change its own appearance and "release" b and c.
It is more work to set up with many buttons, but it is easy to understand and consistent.

**Comment by josephdadams** [comment]
This and #792 are really the same thing so I'll close this one.
