### ISSUE TITLE
Change Port not working

### ISSUE THREAD

**Issue by EndZz-** [bitfocus/companion#327]
I had an issue where I needed to change the port because I was already using a service that used 8000. From the launch of the app the change port option doesn't work. To resolve I needed to navigate to C:\Users\USERNAME\AppData\Roaming\Companion and edit the Config file.

**Comment by haakonnessjoen** [comment]
Did you change the port number, and click the "change port" button? It should be possible to click the launch GUI immediately. I cannot reproduce this bug in mac. I do not have a windows installation to test with right now.

**Comment by EndZz-** [comment]
Yes I did, the button, doesn't seem to be a button. I tried the enter key, tried switching Network Interfaces, and relaunching, nothing seemed to change the port to the new one I designated in the box. i am running Windows 10 x64, I also tried compatibility mode for Win 7 as a test.

**Comment by mrowwy** [comment]
You can also fix this by tabbing to the change port button and hitting enter. For whatever reason it seems to not work from mouse events.

**Comment by willosof** [comment]
So, where are we with this one?

**Comment by willosof** [comment]
Allright, I'll test this with a windows machine one day and see if I can fix it.
