### ISSUE TITLE
Feature Request: Swap Action Instance in-place

### ISSUE THREAD

**Issue by MrLazerface** [bitfocus/companion#329]
**Describe the feature**
I would love the ability to keep the options of a specific command, but change the instance it is applied to. Even better would be to isolate the drop down list to instances that match the option set.

**Usecases**
When building buttons for controlling projectors, I have the same set of 3-4 buttons that I want for every projector. However, projector counts change per show, so some days its as easy as 3 separate instances, other days its 15+. This would save me time by letting me copy buttons and then changing which projector it is assigned to without scrolling thru a list of 100s of commands, then setting the options over again, then deleting the old instance. Rinse and repeat that 10+ times and it becomes an hour long tedious process, whereas it could be as easy as 5-10 minutes.

**Comment by willosof** [comment]
I guess this would be a preset issue instead. If we make presets on everything, the problem disappears. This is an issue for the specific projector modules, not the companion core :)
