### ISSUE TITLE
Build number display

### ISSUE THREAD

**Issue by jpkelly** [bitfocus/companion#335]
Add build number to Admin page.

**Comment by AlexWHughes** [comment]
It appears at the top of all the companion pages doesn't it?

**Comment by jpkelly** [comment]
The version # does but not the build #.

**Comment by jpkelly** [comment]
![image](https://user-images.githubusercontent.com/1377670/48983345-89ad3c00-f0a2-11e8-9bcb-a1c09c10123a.png)

**Comment by jpkelly** [comment]
on latest mac build from here.
https://builds.bitfocus.io/companion/companion-1.1.1-nopagebuttons-85ae8c1-osx.zip
I see build number in the GUI window but in the admin page it just says  "version"

**Comment by willosof** [comment]
Huh. Woot.

**Comment by jpkelly** [comment]
Weird. I have only built on armv7l. (Which did not show build # when I updated.) If I update on armv7l should I see the build number in the admin?

**Comment by willosof** [comment]
AAAAH, you're building your own release? Then you need to run ./tools/build_writefile.sh

**Comment by jpkelly** [comment]
> AAAAH, you're building your own release? Then you need to run ./tools/build_writefile.sh

bingo!
![image](https://user-images.githubusercontent.com/1377670/48984076-fc6ee500-f0ab-11e8-9818-d84ee1ae4357.png)

I have been updating with
```
./tools/update.sh
 npm run rpidist
```
What exactly does ./tools/build_writefile.sh do ?

**Comment by jpkelly** [comment]
BTW thank you for addressing this issue and for all the great work on this project!
