### ISSUE TITLE
Blackmagic Atem 2

### ISSUE THREAD

**Issue by studiovideo54** [bitfocus/companion#336]
**Describe the feature**
I need a instance for Blackmagic Atem 2 for a 6 aux and more video input
**Is this platform dependent (windows, mac, ..)?**
Mac

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by cxselph** [comment]
That support is in the current dev builds. Have you tried that yet? I use it with the 4ME Atem and it works great and has all 6 auxes.

**Comment by studiovideo54** [comment]
Hi many thanks for our attention, in the edit buttom option i have ME 1 with only 3 aux.

**Comment by cxselph** [comment]
The current stable version does not have the options you are looking for. Try downloading the latest dev from here and try. https://builds.bitfocus.io/companion/

**Comment by studiovideo54** [comment]
hi i have try last version with many new function but i have only 3 aux!

**Comment by cxselph** [comment]
That may be a bug then.

**Comment by haakonnessjoen** [comment]
I will check the code!

**Comment by haakonnessjoen** [comment]
The code seems to agree with you. Atem 2M/E has 6 aux busses. It should really work. What browser are you using to control companion? If you are not, could you try to use Chrome? Or reload the browser on the admin interface after adding the atem instance, and try again.

**Comment by cxselph** [comment]
Just to verify, are you able to control me1 and the 3 auxes without any problems?

**Comment by studiovideo54** [comment]
Hi many thanks with last version now all working
