### ISSUE TITLE
Feature Request - Keyboard Shortcuts

### ISSUE THREAD

**Issue by romanivich** [bitfocus/companion#342]
Im trying to find a way for Companion to Trigger Keyboard shortcuts. For example Control + P, or Command + B. Something along those lines. This is for use on a Mac so the use of the command key would be vital.

Its for a offline piece of Lighting software and uses lots of keyboard shortcuts. The workflow would dramatically improve if I could record all these shortcuts to my stream deck via companion. This would also dramatically increase the functionality of applications this software can be used with, along with the Mac OSX Itself.

Many thanks :)

**Comment by AlexWHughes** [comment]
For now couldn't you use the existing streamdeck software to do exactly that?

I'm not just here to shoot down your feature requests I promise

**Comment by willosof** [comment]
Octopus Listener is the only way to do this today. Add a Octopus Listener instance, and you'll get the download link in the instance config :)

We will probably make our own listener application at some point, but in a distant future. And, there's already tickets for that. (that's why I'm closing this one :)

**Comment by colourbars** [comment]
I'm really sad that the topic has been closed already. The hotkey features provided by Octopus are very, very limited. Not Even a Copy-Paste action can be performed. It might seem like an unnecessary thing to ask for in the first place, but it really is very useful. When you setup up shows, whether it is on a media server or for power point, photo or video editing; creating short cuts improve the work flow tremendously. All these tasks are performed by AV technicians on a daily basis. Making it possible only on the machine where the stream deck is connected to, would be a wonderful start, and maybe even enough. I know it is a free software and already a game changer. I just think "use Octopus" might not be the best final answer.

**Comment by AlexWHughes** [comment]
Why not just use the standard streamdeck software if you want the copy and
paste functionality?

**Comment by colourbars** [comment]
Because companion and the standard software do not run simultaneously. It would be an ongoing install/uninstall cycle. The standard software is also painful to setup compared to companion.

**Comment by alatteri** [comment]
I need this for Linux.

**Comment by Enerccio** [comment]
why was this closed when there is much need for this? Especially on platforms where standard software is not available?

**Comment by monoxane** [comment]
Its closed because its technically complex to implement both cross platform and with Companion's centralised architecture. If you are after keypresses take a look at VICREO or Octopus, both of these are controllable by Companion and have been designed to work effectively with it on both the companion computer and across the network.

**Comment by colourbars** [comment]
With VICREO support (2.0 at the moment) the solution is pretty much there.

Enerccio <notifications@github.com> schrieb am Mo. 12. Aug. 2019 um 09:11:

**Comment by Enerccio** [comment]
> Its closed because its technically complex to implement both cross platform and with Companion's centralised architecture. If you are after keypresses take a look at [VICREO](https://jeffreydavidsz.github.io/VICREO-Listener/) or Octopus, both of these are controllable by Companion and have been designed to work effectively with it on both the companion computer and across the network.
> 
> (Edited because I can never remember all the different markdown implementations)

I checked both and unless I am mistaken, none of those solutions work under linux...

**Comment by JeffreyDavidsz** [comment]
Still need to build under Linux.... Maybe this holiday :-)

**Comment by Enerccio** [comment]
Honestly though, I'll just make uinput one, that is rather simple thing to do just for linux

**Comment by Martinsoundguy** [comment]
I would actually love it if it would be possible to add hotkeys to the companion software.
I'm using OSC to controle Qlab, but it would be very handy to use some hot keys as well while setting up the show file.

**Comment by colourbars** [comment]
You can do it with VICREO in 2.0

Martinsoundguy <notifications@github.com> schrieb am Mi. 14. Aug. 2019 um
19:02:

**Comment by Enerccio** [comment]
https://github.com/Enerccio/companion-modules-os-keyboard I made linux uinput version, but technically could be done for windows as well and added together

**Comment by alatteri** [comment]
> https://github.com/Enerccio/companion-modules-os-keyboard I made linux uinput version, but technically could be done for windows as well and added together

Does this work only on the local machine that Companion is running on, or can it trigger keyboard events on a remote machine?

**Comment by Enerccio** [comment]
> > https://github.com/Enerccio/companion-modules-os-keyboard I made linux uinput version, but technically could be done for windows as well and added together
> 
> Does this work only on the local machine that Companion is running on, or can it trigger keyboard events on a remote machine?

only locally

**Comment by JeffreyDavidsz** [comment]
For remote you can use VICREO-Hotkey. This is for the moment only windows and OSX

**Comment by aral** [comment]
@Enerccio Thank you for making the local keyboard module for Linux. I just added it to my local dev install of Companion (cloned your repo into _module-local-dev/_ and I can see it in the web interface but when I go to add it, I get a `Failed: TimeoutError: Timed out after 5s` error. Nothing in the logs otherwise. Any ideas? Is there something I need to do first e.g., some dependency I need to install?

(Running it on Pop!_OS, an Ubuntu derivative on a Dell XPS 13 Developer Edition).

**Comment by bafplus** [comment]
Even tho its closed, but for future refferance:

You can use "xdotools" in linux and call it directly from within Companion.

- In terminal "sudo apt install xdotool"
- Make a button and use internal "Run shell path (local)"
- Under "Path (supports variables in path)" use the cli command as examples below.

Examples:

Ctrl C: "xdotool key ctrl+c"
Ctrl Alt Del: "xdotool key ctrl+alt+del"
Type Hello World: "xdotool key shift+h e l l o space shift+W o r l d"

More info: https://linuxhint.com/xdotool_stimulate_mouse_clicks_and_keystrokes/
