### ISSUE TITLE
BMD Hyperdeck connection failed

### ISSUE THREAD

**Issue by Magi1053** [bitfocus/companion#344]
**Describe the bug**
I have a BMD Switcher, Video Hub and Hyperdeck. I've added connections for all 3 of them into Companion, and the Switcher and Video Hub work perfectly. The Hyperdeck seems to be erroring out though. I tried to find some error logs in `%appdata%` but the logs folder was empty. I've verified the IP address of the Hyperdeck, and verified that the Hyperdeck is controllable directly through my BMD ATEM software.

**Screenshots**
![image](https://user-images.githubusercontent.com/1045179/48679815-3eeb6b80-eb5a-11e8-9919-974a8ed72990.png)

**Desktop:**
 - OS: Windows 10 x64
 - Browser: Chrome
 - Version 1.1.0 and 1.1.1 Bleeding

**Comment by haakonnessjoen** [comment]
Does it not say anything in the log window on the right side? Anyways. This module is so simple, that if it errors out, it is most likely a network issue. Like wrong ip, unreachable subnet, or even physical network issue.

**Comment by jesperstarkar** [comment]
So it is, only a single connection at the time.

**Comment by PerRoine** [comment]
I Can confirm this Hyperdeck only accepts one connection at the time so it's either Atem or Companion not both disconect all other equipment trying to connect or it will be connection problems and a roll of the dice to which device get's the connection.

**Comment by Magi1053** [comment]
Thank you, I have confirmed that was the issue.
