### ISSUE TITLE
Feature Request: sub-selection instances for actions

### ISSUE THREAD

**Issue by wvanmaris** [bitfocus/companion#346]

**Comment by JeffreyDavidsz** [comment]
Looks for some modules a sub selection is needed to make the list of actions a bit shorter. So maybe we need to put a standard to this, max of 5 actions as main choices, for example

**Comment by mfoulks3200** [comment]
How about just a dropdown with every instance registered, then under that as a second level, every action associated with that instance?

**Comment by josephdadams** [comment]
Duplicate with #510 , will close this issue because the detail in #510 is better.
