### ISSUE TITLE
Make sure action list is sorted

### ISSUE THREAD

**Issue by willosof** [bitfocus/companion#354]
Relates to the problem appearing in #296

**Comment by krocheck** [comment]
Question ... do we want these sorted alphabetically?

**Comment by willosof** [comment]
Yes!

**Comment by dnmeid** [comment]
WHAT? I usually do sort the actions in my modules according to importance, relevance and how they relate to each other. E.g. Take first or "Testpattern on/off" and then immediately "Select Testpattern". If you sort it alphabetically you destroy this. I really would prefer to have the order set by the module programmer. If he decides that alphabetically is good, he can set the actions up in alphabetical order in the module.

**Comment by JeffreyDavidsz** [comment]
No no please don't, I agree with Dorian

**Comment by krocheck** [comment]
I should have elaborated my question.  I agree that modules often list them in a logical order, so alphabetical doesn't make sense.

**Comment by willosof** [comment]
Oh wow, I just realize that I've misunderstood this entire thread. I totally agree with you guys on this, and I thought we were talking about the manufacturer and product list.. I don't really know how this happened :P
