### ISSUE TITLE
Add OSC Control to Page Selection

### ISSUE THREAD

**Issue by Keksstar** [bitfocus/companion#357]
The titel nearly says it all.
Every button on the Streamdeck can be controlled in the latest builds... except the page up and down button or actual page.
But be great if there are OSC commands for this as well. So with this buttons could be build to jump to certain pages. This would allow grouping for commands.

**Comment by haakonnessjoen** [comment]
That could be arranged. How would you choose which stream deck to control the page on?

Maybe something like /surface/ABCD12345/page_up, where ABCD12345 is the serial number of the controller? And of course a /surface/ABCD12345/goto_page with the page number as integer argument.

What do you mean grouping for commands? There is already possible to change pages on any connected stream deck from a bank you know :)

**Comment by Keksstar** [comment]
Would be great if these button could also send out OSCcommands, so then it would be very easy to hook up different Streamdecks together. (sorry, "grouping" was the wrong name fot that)

**Comment by dnmeid** [comment]
You can already do this by setting up some buttons who change pages and trigger them with OSC. Do we still need to be able to call the page buttons directly? Especially if the existance of the page buttons and pages is going to change?
