### ISSUE TITLE
Feature Requests - Delay action - Reset Timer

### ISSUE THREAD

**Issue by strangemark75** [bitfocus/companion#359]
Hi 

A feature request for the delay on the timer.
If you were able to add a reset timer as part of that function key.

This would allow you to make a never ending loop if wanted to automate a cycle.

I had an instance recently, 3 inputs into a matrix and 3 outputs.
Every 15 minutes, they wanted to change the input to the different designated outputs.
You would be able to do this cycle once currently in Companion. But if you could reset the timer after 45 minutes, this would be never ending cycle.
What would also be useful is to have an option on the delay units, at the moment it is only ms. 
If you are having long delays into minutes, it becomes a high number. 
Not a huge issue, but would be good to have a visual representation that you can recognise quickly.

Many thanks

Mark

**Comment by josephdadams** [comment]
This relates to #389, a scheduling functionality. Closing this one.
