### ISSUE TITLE
Page limit

### ISSUE THREAD

**Issue by hadphild** [bitfocus/companion#361]
Can you limit the amount of pages? 

So start with only 1 page and then you can add pages as you go.

**Comment by robertskiba** [comment]
That is a really good idea. I was also thinking about that. What would you think about if there was an option to skip completely unused pages automatically when using the page+/page- buttons? Or an option to define what page range should be accessible on the stream deck. 

Sometimes it's quite handy if you could skip directly from page 10 to page 1 if everything over page 10 is unused...

**Comment by Deanbau** [comment]
How about a "enabled" toggle for each page ?

**Comment by willosof** [comment]
@Deanbau that's a nice idea! i think this will work with the nopagebuttons branch coming as well. noted.

**Comment by hadphild** [comment]
With the No Page version could you assign a Streamdeck to a Page. So if you have 3 SD's you can have only that page attached to one.

**Comment by Wilmshurst** [comment]
definitely a needed feature in a volunteer orientated environment, where users like to explore too much

**Comment by josephdadams** [comment]
Closing, we closed #640 for the same reason. You can do this in 2.0 by removing the page up or down navigation buttons on the "last" page.
