### ISSUE TITLE
MIDI out

### ISSUE THREAD

**Issue by zntgrg** [bitfocus/companion#365]
A simple MIDI output to trigger the vast amount of supporting hardware and software like digital mixers, controllers and  DAWs.

It should be platform indepedent as long as someone uses virtual ports like LoopMidi or Bome: there are web browsers native implementation too. Direct connection with hardware midi port should be platform dependent.

Midi strings could be formed easily by the user in its  raw format, without implementing every aspect of midi standard.

As an example, a digital mixer could change scene remotely with a simple "C0 00" sent on his midi port.
Or a DAW like Ableton could mute/unmute or play with custom midi commands.
Finally, Vmix could also receive and send feedback midi signals.

**Comment by casbizz** [comment]
+1 That would be great

**Comment by crazycowprod** [comment]
Please oh please this ^^^  If companion outputs MIDI i can rule the world!

**Comment by startmedia001** [comment]
+1
That would be really great!

**Comment by EnerGiehl** [comment]
+1

**Comment by nickgnat** [comment]
+1, I really need this.

**Comment by cxselph** [comment]
The midi module has been requested for some time now. It is on the to do list. It is right there with the generic TCP/UDP module, applescript, etc... The devs want to get modules for programs and equipment first to keep things simple and keep people from having to program manually, etc. They will come in due time.

**Comment by richiebellis** [comment]
+1 for this would save me running an additional 3rd party app. Please

**Comment by willosof** [comment]
work is being done on this subject. give me some time, and it will come! :)

**Comment by willosof** [comment]
Relates to #113

**Comment by mtnAVman** [comment]
+1 
Looking forward to the implementation of MIDI in companion!

**Comment by josephdadams** [comment]
You guys can sort of use MIDI Relay for this, or an OSC to MIDI bridge, just nothing directly Companion yet. Closing it though because there is another request for this already (in the companion-module-requests repo).

**Comment by nahrwoldinternet** [comment]
+1 for all the things MIDI, especially Ableton (or you could do an Ableton module, as I'm assuming many people would like this specifically for ableton)

**Comment by Montezuma-69** [comment]
No midi, no companion. Ive got a midi plugin for the Original streamdeck software now.

**Comment by nottooloud** [comment]
> Closing it though because there is another request for this already (in the companion-module-requests repo)

I'm not seeing that request in [github module requests](https://github.com/bitfocus/companion/projects/6).
Perhaps I'm looking in the wrong place?

Many programs have Learn MIDI functions, and this would give access to all of them without writing a separate module for each. My own desired application is controlling Mixing Station Pro, which is a 3rd party digital mixer controller that runs on Macs, PC, and Linux (as well as iOS and Android). It can operate Behringer's X32, X-Air, and Wing, Allen and Heath's GLD, SQ, and Qu, and Soundcraft's Si series. Once it learns a given controller, it can apply that to any of the mixers.

**Comment by josephdadams** [comment]
@nottooloud https://github.com/bitfocus/companion-module-requests/issues/81

**Comment by Regemark** [comment]
+1

**Comment by GDSteelers** [comment]
+1. Please

**Comment by ivan-ef** [comment]
For those who are looking for midi, you can try to use elgato native midi plugin and add companion buttons with elgato companion plugin.

**Comment by nahrwoldinternet** [comment]
Tech Ministry's MIDI relay works great, and now the Renewed Vision ProPresenter plugin also has MIDI in button press capability that should for more than just ProPresenter, as well.

**Comment by AndrewIAm** [comment]
+1. The whole world is waiting for this miracle))
