### ISSUE TITLE
Make Latch checkbox larger

### ISSUE THREAD

**Issue by DaveShep** [bitfocus/companion#366]
v1.2.0 85393af-1109

Latch (toggle) checkbox on Button Configuration page is very small

**Screenshots**
https://imgur.com/n10Mo3t

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Browser: Chrome 70.0.3538.110

**Comment by willosof** [comment]
![image](https://user-images.githubusercontent.com/426386/49700055-e992ff00-fbd9-11e8-8354-37b98ac65a77.png)
