### ISSUE TITLE
Change Button and text color based on button up or down

### ISSUE THREAD

**Issue by ibmcclain** [bitfocus/companion#367]
**Describe the feature**
Would love to have a difference color background for a buttons up/down state and also different text for each state.

**Usecases**
This way for feedback on some things, a user could have computers or devices send OSC to companion to help manage the states of things.  Any server or computer that can output custom OSC can probably be paired with control messages.  So if I'm controlling projectors from my media server in larger programmed shows, I can control my media server and projectors, and have the media server tell the streamdeck what state the projectors/ or devices are in.

I would use this on every show I program and I bet every media server programmer for large shows would die for this :)

**Comment by BasilChessman** [comment]
I 2nd the vote for different colors/text/PNG for latched button state!

**Comment by willosof** [comment]
You can now solve this with internal actions.
