### ISSUE TITLE
Feature Request: Quick jump to any page

### ISSUE THREAD

**Issue by Deanbau** [bitfocus/companion#37]
Ability to jump to any page with ease.

Long method - 

When the user presses the page button, all bank (position 1 to 11) buttons get replaced with quick keys that jump to each page. This action is a toggle.

1.1 button gets replaced with "1-10"
1.2 button gets replaced with "11-19"
1.3 button gets replaced with "21-29"
...
1.10 button gets replaced with "91-99"

When the user hits one of those buttons, the whole display gets replaced (for example - after 1.3 being hit)

1.1 button gets replace with "21"
1.2 button gets replace with "22"
1.3 button gets replace with "23"
...
1.9 button gets replace with "29"

I see this being useful for events like sports presentation, where quick playback to a random clip is required at short notice.

Short method-

Ability to create a button that jumps to a specific page.

**Comment by willosof** [comment]
We did the short one. For now!
