### ISSUE TITLE
Add Feedback Logic

### ISSUE THREAD

**Issue by krocheck** [bitfocus/companion#372]
**Describe the feature**
Give the ability to have AND conditions to create additional states.  As a result, need to be able to set priority order of feedbacks.

**Is this platform dependent (windows, mac, ..)?**
No

**Usecases**
Was on a show where I was controlling a Videohub upstream of an ATEM.  I wanted to be able to have my source buttons be a lighter shade of their background when they were routed into their respective feed and display standard pgm/pvw style feedback when appropriate.  I would have to build 3 'sets' of feedback (lower the number, higher the priority):

1. The in/out route AND source PGM (red BG)
2. The in/out route AND source PVW (green BG)
3. The in/out route (light purple BG)
- No feedback (purple BG)

Of course this is a nice to have, but I ended up deciding which buttons were more important to show the route feedback vs. pgm/pvw feedback.  Worked, but not as clean as it could have been.

Thanks,
Keith

**Comment by Suenee** [comment]
+1
More ideas for feedbacks #2233
