### ISSUE TITLE
Home Button/Page# Button

### ISSUE THREAD

**Issue by BasilChessman** [bitfocus/companion#375]
**Describe the feature**
The Page# button on the left would also serve as a home button to take the user back to page 1.

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
No

**Usecases**
With more and more applications being supported, more and more pages are being programmed.  It would be possible to program a home button on every page, but with only 12 usable buttons, efficiency is key.   Since the page# indicator button doesn't really do anything, it would be fantastic to also act as a home button.  Many users have an applications menu setup on the first page.  A button to bring users directly back to that page without sacrificing one of the programmable 12 would be a great asset.

**Comment by startmedia001** [comment]
I just wanted to post the same feature request. Thumbs up! 👍

**Comment by BasilChessman** [comment]
I like all of those additional suggestions.  I would really like the option to remove the prebuilt functionality of those buttons and use them for whatever I want.

**Comment by willosof** [comment]
@SteveTherrien fixed this recently. But it will be overwritten by the nopagebuttons branch later on. Available for now!
