### ISSUE TITLE
Feature request ProVideo Player 2 

### ISSUE THREAD

**Issue by studiovideo54** [bitfocus/companion#382]
**Describe the feature**
I need a preset for a Renewed ProVideo player 2 

**Is this platform dependent (windows, mac, ..)?**
Mac

**If documentation is required to implement, do you know where to find it?**
Add key mapping for remote a software

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by tvtwidget** [comment]
There is a ProVideo Player 3. I am unable to get this to function With My ProVideo Player 2 which is what brought me to this post. I am running PvP on a PC. I would like to be able to select playlist, Layer, and clip.

**Comment by chrisrouse** [comment]
The "easiest" solutions for a PVP 2 module would either be MIDI or supporting the custom key mapping. MIDI would need to support note and intensity. Key mapping would need to be a basic controller to send single letters. You can create custom mapping in PVP2 to assign letters to clear commands, selecting playlists, selecting layers, and selecting cues within a playlist. It does not have a robust API like PVP3. I'm attempting to get the Custom Control working with UDP, but it's causing a crash every time I send a value, so I've reached out to one of my contacts at Renewed Vision for some more info. I wrote the PVP2 user guide, but the modules section was horribly ignored, so there's no useful documentation for that part.

**Comment by tvtwidget** [comment]
Thank you!

**Comment by chrisrouse** [comment]
This can be implemented immediately if you install Octopus Listener from http://noismada.com/. You will then use the Octopus Listener instance. The IP address will be your computer's IP. Use the Hot(Single) Key setting for Octopus Listener. You will need to use the Key Mapping feature in PVP2 **first** before you assign the keys in Companion. Once you've got everything mapped, create your buttons in Companion and it should work for you. There does seem to be a slight delay using this method, but it's better than nothing.

**Comment by tvtwidget** [comment]
works like a champ!

**Comment by willosof** [comment]
Issue closable? or what happened here?

**Comment by chrisrouse** [comment]
@willosof Yes, this one can be closed. PVP 2 has been a closed project since May 2017. I don't see a need to spend much time trying to create a module for it since it has been replaced by PVP3.

**Comment by krasa95** [comment]
You can also control PVP2 via Grass Valley AMP protocol. There are play, stop and go to clip options. Using this protocol you can control PVP2 also if the application is in background.

**Comment by tvtwidget** [comment]
Thank you!On Mar 6, 2019 12:15, krasa95 <notifications@github.com> wrote:You can also control PVP2 via Grass Valley AMP protocol. There are play, stop and go to clip options. Using this protocol you can control PVP2 also if the application is in background.
