### ISSUE TITLE
Epiphan Pearl 2

### ISSUE THREAD

**Issue by Rahulhasmail** [bitfocus/companion#385]
**Start Stop Recording/Streaming & Layout switching**
this feature/control will help to stat stop recording & Streaming over internet(Facebook/Youtube)
also layout switching between the presets

**this is web/Browser based platform and easily controlled via Web UI**

https://www.epiphan.com/userguides/pearl/Content/UserGuides/Streaming/maintenance/thirdPartyConfig/man_br_3rdParty_controlling_with_http.htm

**Comment by TakeMeNL** [comment]
Duplicate #388
