### ISSUE TITLE
Request:Keyboard  keystroke input

### ISSUE THREAD

**Issue by Croonquist** [bitfocus/companion#387]
This would be quite useful for PowerPoint remotes. To enable/disable remote I on main and backup machine depending on which is live on PGM. 
And for when you have multiple computers you want to control simultaneously from a master cue/ Perfect Cue remote system.

**Comment by BasilChessman** [comment]
Yes, please!

**Comment by BasilChessman** [comment]
Does anyone know if this is in development?  If it's not, can anyone suggest a way to have a Perfect Cue button press trigger a Companion button press?

**Comment by willosof** [comment]
People use octopus listener for this today. And, later this year there will probably a companion-listener as well.

**Comment by BasilChessman** [comment]
> People use octopus listener for this today.

Perhaps I am misunderstanding, but how would Octopus listener be used to execute a Companion button press?  I can currently do the opposite (have Companion send a keystroke via octopus).  The end goal is to have a keyboard key press trigger a companion button.

**Comment by josephdadams** [comment]
Duplicate of #204. Closing.
