### ISSUE TITLE
Module request: Epiphan Pearl 2

### ISSUE THREAD

**Issue by perkiness** [bitfocus/companion#388]
Support for Epiphan Pearl 2 / Pearl Mini.
It uses http commands (described in the user guide) which I couldn't get to work through a generic http instance.
Simple commands like start streaming/recording, change layout in a channel, switch output.

**Comment by Rahulhasmail** [comment]
You may refer below link for HTTP control codes 
https://www.epiphan.com/userguides/pearl/Content/UserGuides/Streaming/maintenance/thirdPartyConfig/man_br_3rdParty_controlling_with_http.htm

**Comment by TakeMeNL** [comment]
So i have a "beta" build on my own repo, maybe moving that one the the Bitfocus one to continue development there?

**Comment by JeffreyDavidsz** [comment]
Great I'll do that for you

**Comment by JeffreyDavidsz** [comment]
@TakeMeNL is the current module in the bitfocus repo working/tested?

**Comment by TakeMeNL** [comment]
So i don't have a Pearl available to test on.
Because the endpoint i use are in the Live environment and there is zero documentation about that.
Next week will be very quite for me and i have the change to grab the Pearl to get all endpoints with there needed data.

For now the only thing that will work is changing channel layouts. The base is there

**Comment by pacman160** [comment]
How is this sitting? Have about 12 of these in inventory I would like control.

**Comment by JeffreyDavidsz** [comment]
I saw some commits coming by, but not quite sure if it's ready to test, @TakeMeNL how far are you?

**Comment by MarcHagen** [comment]
Hi there!
So yes basic functions like start/stop recording/streaming, change channel layout are done.
Also active channel feedback is done.
I just have to add the feedback for streaming/recording.

And if there are specific functions/feature's that are missing let me know.

**Comment by pavelkudelin** [comment]
@MarcHagen  I'll be able to test tomorrow and write about the results. I have Epiphan Pearl 1. They have the same API

**Comment by pavelkudelin** [comment]
@MarcHagen  Would you please write briefly how to install the module? I can't understand

**Comment by JeffreyDavidsz** [comment]
I'll upgrade the module tonight, on the road now

**Comment by JeffreyDavidsz** [comment]
Module is being build right now. Thanks @MarcHagen for your work. Please test the latest build, where the module will be included

**Comment by pavelkudelin** [comment]
tested the module. 
- Layout switching works 
- Recording is activated after double-clicking. Nothing happens after the first command. 
- special thanks for processing the recording feedback
- processing of the "Change colors on chanel layout change" event causes an error (screenshot). And it is not removed anymore. Even the program rearrangement does not help. 
![2019-08-19 20 30 00](https://user-images.githubusercontent.com/54240249/63330963-5f409480-c33d-11e9-8a69-913e2f32c9b8.png)

**Comment by Rahulhasmail** [comment]
Hi,
Great News...!
Thank you...!

Please help me to Deploy/Use this with pearl 2
Start/Stop Recording

Thanks & Regards
Rahul Chawda

**Comment by MarcHagen** [comment]
> tested the module.
> 
> * Layout switching works
> * Recording is activated after double-clicking. Nothing happens after the first command.
> * special thanks for processing the recording feedback
> * processing of the "Change colors on chanel layout change" event causes an error (screenshot). And it is not removed anymore. Even the program rearrangement does not help.
>   ![2019-08-19 20 30 00](https://user-images.githubusercontent.com/54240249/63330963-5f409480-c33d-11e9-8a69-913e2f32c9b8.png)

Hi there nice catch, im on the road atm. I will fix it tonight.

**Comment by Rahulhasmail** [comment]
Greetings!

Bit Focus Companion 1.4 Released, but this Plugin for Pearl is not a part
of it,

how you can help us to deliver this, its a request
if anything required we can discuss on phone


Thanks &  Regards
Rahul
9970955256

**Comment by JeffreyDavidsz** [comment]
The module is part of the V2.0. You can download that at builds.bitfocus.io/companion

**Comment by Rahulhasmail** [comment]
Hi Jeffrey Davidsz
Greetings!

hope you are doing well..!
we hope situation will get normal soon

further asking help for Module request: Epiphan Pearl 2 (#388)
covid pandemic has triggered delays to regular work, may also delayed
release of companion 2
in spite if you can help for pearl 2 Module which can be used with Wget
codes or any other we can use your module with Companion1.4
thanks & Regards
Rahul

**Comment by josephdadams** [comment]
Just use Companion 2.0. You’ll get the module you want and it will work fine.

**Comment by Rahulhasmail** [comment]
Hi,
JosephThank you for your reply....!
hope you are doing well...!

as Companion 2.0 is beta i am afraid to use this in production
environment...! because i cannot able to export commands/pages from one
page to another PC/MAC using export on Companion 1.4 it only exports png
not backend commands.

also Companion 2.0 installed when layout for 15 key selected it misses keys
and does not go with actual stream deck keys

i feel there must be an option to select stream deck size
6, 15 32 before starting to create keys /or export/ import

i have also made beautiful pages for irisdown timer, Panasonic PTZ Camera,
ATEM television Studio HD and few more

please also suggest how i can contribute...!!

Many Thanks...!

**Comment by JeffreyDavidsz** [comment]
Hi Rahul,

The module is not coming into 1.4. 2.0 is stable to run shows with. That being said it would suggest this;

Download 2.0 and start from scratch. There are many improvements in the beta releases. Make sure you test your programs, but you'll find it will all work nicely.

It will take you maybe an hour to reprogram the deck button, but it's worth it!
