### ISSUE TITLE
Module Request: Panasonic PTZ Cameras

### ISSUE THREAD

**Issue by Deanbau** [bitfocus/companion#39]
Control of Panasonic PTZ cameras via HTTP Protocol (See [this manual](https://eww.pass.panasonic.co.jp/pro-av/support/content/guide/DEF/HE50_120_IP/HDIntegratedCamera_InterfaceSpecifications-V1.05E.pdf))

Features could include

- Pan (Left, Right)
- Tilt (Up, Down)
- P/T Speed
- Zoom (In,Out,Speed)
- Focus (In, Out)
- Iris (Open, Close)
- Preset (Recall, Store)
- Scene (Recall, Store)
- Tally (On, Off)
- Gain 
- OSD Menu toggle and commands

Feedback

- Last recalled preset number

**Comment by jab595** [comment]
Just following this up.... Can I help at all?

**Comment by willosof** [comment]
Hi, you could find the exact URLs to request for each command:) then maybe I’m able to implement it during the weekend!

**Comment by haakonnessjoen** [comment]
I think I have the manual, give me to sec and I'll send it to you @willosof

**Comment by haakonnessjoen** [comment]
[HDIntegratedCamera_InterfaceSpecifications-V1.03E.pdf](https://github.com/bitfocus/companion/files/2495278/HDIntegratedCamera_InterfaceSpecifications-V1.03E.pdf)

Did you want to write the module @jab595 ?

**Comment by craftbyte** [comment]
Check out krooklab/panasonic-camera-controller on GitHub for a sample implementation. May make it easier to develop/add the lib.

**Comment by RizoWBD** [comment]
[aw-he130_ip_control_specification_aw-he40_aw-ue70.pdf](https://github.com/bitfocus/companion/files/2785018/aw-he130_ip_control_specification_aw-he40_aw-ue70.pdf)

I found a more recent documentation, if this can help :)

**Comment by haakonnessjoen** [comment]
Added in dbb764e8

**Comment by dbvdeo** [comment]
AW-UE150 adding "UHD Crop" functionality to the module would be great

**Comment by premultiply** [comment]
@dbvdeo You can add a feature request here: https://github.com/bitfocus/companion-module-panasonic-cameras/issues
I will add the required function to the upcoming Panasonic Cameras Module. It will replace the PTZ module once it is finished.
