### ISSUE TITLE
Remaining time and clip name feedback 

### ISSUE THREAD

**Issue by Croonquist** [bitfocus/companion#390]
Request 

Regarding PlaybackPro, Qlab, Mitti:

It would be great to be able to display Remaining time and clip name on the keys. Just like the countdown  timer feedback.
I know that at least PlaybackPro does support that in its protocol.

Thanks

**Comment by josephdadams** [comment]
Closing this. @Croonquist if you still want these features, please request them individually in their respective repositories. :)
