### ISSUE TITLE
Auto Cut on ATEM freezes halfway

### ISSUE THREAD

**Issue by chberge** [bitfocus/companion#392]
When using the AUTO-function for crossfading between two pictures on the ATEM, the transition will freeze halfway if you change the preview-picture too fast. 

**To Reproduce**
1. Add an Auto-cut to a Companion-button
2. Set an ATEM input to program
3. Set an ATEM input to preview (another than the one in preview)
4. Press the AUTO-button on Companion
5. Before its done, change input on Preview, and it will freeze the transition, leaving two pictures on top of each other

MacOSX Moajave, 10.14.1
Companion 1.2.0

**Comment by haakonnessjoen** [comment]
This is a ATEM "feature". We only tell it to auto-cut. And it is doing all the work itself. If the same does not happen on a atem surface, they must have written code explicitly to disable the buttons while it is transitioning. But I would be very surprised if that is the case.

**Comment by scoobiekw** [comment]
Recall a preset in the middle of an autotrans on an E2 and you'll see what you thought was going to preview right to screen. Even expensive switchers can be misused.

**Comment by haakonnessjoen** [comment]
Wontfix, not our issue. Blackmagic must fix this :)
