### ISSUE TITLE
Highend Systems Hog OSC mappings wrong

### ISSUE THREAD

**Issue by MichaelMayli** [bitfocus/companion#393]
Hi guys

Please check the implementation again.

Following commands are sending the wrong OSC string.

Halt List or Scene/Macro does GO
Resume List or Scene/Macro does GO
Release List does GO List 0
Release Scene/Macro sends Go on Scene/Macro

Please find attached the PDF with the OSC mappings.

Thanks in advance!

Do not hesitate to get in contact with me, if you have any further questions!

Cheers Michael Mayli

[Hog OSC.pdf](https://github.com/bitfocus/companion/files/2655540/Hog.OSC.pdf)

**Comment by krocheck** [comment]
Michael, I'm sure the guys will chime in, but thread #198 is the implementation/test thread for Hog4.  I suspect they'll roll this thread into there.

I haven't had a chance to do my own testing yet, but looking at the source code I believe your reports of command mis-match are correct.

**Comment by krocheck** [comment]
@MichaelMayli the latest dev build (1178) has bug fixes for these issues.  It was tested on Hog4 PC but if you have an opportunity to test it, please report your results to #198.
