### ISSUE TITLE
Additional OSC mappings for Highend Systems Hog

### ISSUE THREAD

**Issue by MichaelMayli** [bitfocus/companion#394]
Hi guys,

Could you please implement following commands in the Hog Instance?

Go, Pause, Back, Flash and H keys.

Companion + key up and down action will do great for the OSC Button up and down option will

See attached pdf on page 3 for the mappings

Thanks in advance!

Cheers Michael Mayli

**Comment by krocheck** [comment]
@MichaelMayli the latest dev build (1178) has many additional commands as well as presets (since most of these require up/down press actions).  It was tested on Hog4 PC but if you have an opportunity to test it, please report your results to #198.

**Comment by krocheck** [comment]
Update: please direct issues to https://github.com/bitfocus/companion-module-highend-hog4/issues
