### ISSUE TITLE
Streamdeck not recognised on Raspberry

### ISSUE THREAD

**Issue by MichaelMayli** [bitfocus/companion#395]
Hi guys,

I have some issues connecting my stream deck to my raspberry pi 3 B

I am running the latest version of raspian stretch with desktop and followed the instruction for the install here on GitHub for companion.
Autostart, the Companion interface and everything else runs fine, the app always disconnects the stream decks because it is already in use.

I have attached 3 pics.

I am pretty new to all the stuff and I am running out of ideas.

Can you please help me out?!

Cheers Michael Mayli

![img_3588](https://user-images.githubusercontent.com/45675150/49621964-eaecdd80-f9c7-11e8-99f7-3e3b57c2891b.jpg)
![img_3589](https://user-images.githubusercontent.com/45675150/49621967-ec1e0a80-f9c7-11e8-8051-deecd95919a6.jpg)
![img_3592](https://user-images.githubusercontent.com/45675150/49621969-ee806480-f9c7-11e8-8030-5ebcb4adae69.jpg)

**Comment by haakonnessjoen** [comment]
Read the part about raspberry pi here:

https://docs.bitfocus.io/companion/installation

**Comment by MichaelMayli** [comment]
Hi Hakon,

Thank you so much for the quick response.

Up and running, just have an error message EONENT. (See attached pic)

Got an idea?

Thanks in advance!

Cheers Michael Mayli




Ing. Michael Mayler
Lichtdesign - Operating
Heidengasse 6
9020 Klagenfurt am Wörthersee
Austria
tel.: +43 664 / 49 38 142
mail: maylerm@gmx.at

**Comment by haakonnessjoen** [comment]
See below what? I think you need to log in to github to write your issues if you are including screenshots. Not just answer the mails.

Some latency is expected, since it is a raspberry after all. But if you are not doing it, you should be sure to turn off X-Windows on the raspberry and any other "big" applications, and try to run it using the ./headless.js file.
