### ISSUE TITLE
Feature Request: Basic logic implementation

### ISSUE THREAD

**Issue by BasilChessman** [bitfocus/companion#396]
**Describe the feature**
Add IF, THEN, AND, etc. to Companion functionality

**Is this platform dependent (windows, mac, ..)?**
no

**If documentation is required to implement, do you know where to find it?**
no

**Usecases**
A simple example would be a "shift" button.  **IF** this button is pressed and held, **THEN** the 2nd button would perform action XY,  **ELSE** the 2nd button performs X.

**Comment by BasilChessman** [comment]
Variables would be nice also. ;)

**Comment by willosof** [comment]
Unless someone else than me or håkon implements this, this won't be implemented/maintained in companion due to conflicting interests. (We'll make paid software to do this)

**Comment by jpooley-hearst** [comment]
Bump, please add logic to execute a certain action only if a certain key is activated.

**Comment by Julusian** [comment]
Duplicate of #1052
