### ISSUE TITLE
Page Up icon bug

### ISSUE THREAD

**Issue by davidadevore** [bitfocus/companion#403]
**Describe the bug**
Using Build 1.2.0 (nopagebuttons-d6d3a4e-1147) Whenever adding pages, the top left button icon changes to the page up icon, but does not change the function of the button. 

**To Reproduce**
1. Add bunch of buttons on page 1 with page up/down buttons somewhere other than default
2. Add a page with new buttons
3. Button 1 will magically have a page up icon, but without changing function from what is set (aka, not page up). I've seen this happen to button 1 on multiple pages.

**Comment by haakonnessjoen** [comment]
Please do not report bugs on the nopagebuttons branch. This is not ready for use at all.
