### ISSUE TITLE
Move the pages to the righthand side

### ISSUE THREAD

**Issue by hadphild** [bitfocus/companion#405]
**Describe the feature**
Move the Buttons from the left handside to the right handside per streamdeck connected. 
This will allow you to put 2 decks together and not have the pages in the middle. 

Also Being able to ID the Streamdeck with a Colour. in the Page Button. 

**Is this platform dependent (windows, mac, ..)?**
NA

**If documentation is required to implement, do you know where to find it?**
NA

**Usecases**
If you have a two Streamdecks the you can have the pages on the outside

**Comment by willosof** [comment]
This won't be an issue in the future, after implementing the nopagebuttons branch, giving your the opportunity to move the buttons where you want them to be, individually.
