### ISSUE TITLE
Module Request: AJA Kumo Router Control

### ISSUE THREAD

**Issue by scoobiekw** [bitfocus/companion#407]
**Describe the feature**
Control AJA Routers using the Supported GVG Native Protocol.

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
Page 44 of Kumo manual lists supported NP commands.
https://www.aja.com/assets/support/files/4276/en/AJA_KUMO_Manual_v4.3.pdf

GVG Native Protocol docs
http://grassvalley.jp/pdf/RoutingProductsProtocolManual_2.pdf

**Usecases**
I work with multiple companies that own or rent KUMO routers, and adding Companion control would  be nifty.

**Comment by edinc90** [comment]
I got this to work via HTTP GET, not GVG protocol.

The syntax is as follows: <ip address>/config?action=set&configid=0&paramid=eParamID_XPT_Destination[DST 1-64]_Status&value=[SRC 1-64]

Where [DST 1-64] is the destination ID starting from 1 and up to the maximum output count of the Kumo (16, 32 or 64 depending on model,) and [SRC 1-64] is source ID starting from 1 up to the maximum count.

**Comment by scoobiekw** [comment]
Nice. Easy to build a module with that string

**Comment by JeffreyDavidsz** [comment]
Build a module based on HTTP GET. @edinc90 I also put the salvo in it. First time I'm using this thing, haven't tested the salvo (could not find the option for it). Build will be ready in 15 minutes or so.
