### ISSUE TITLE
Oauth support for device configuration

### ISSUE THREAD

**Issue by baltedewit** [bitfocus/companion#408]
**Describe the feature**
Some "devices" are really just services (e.g. spotify), in order to interface with these services we need some way to authenticate ourselves and our user to the service. Most services use Oauth for third party controls.

**Is this platform dependent (windows, mac, ..)?**
Nop.

**If documentation is required to implement, do you know where to find it?**
Could probably just use this package: https://www.npmjs.com/package/simple-oauth2
Device module would need to specify the tokenHost / path
Callback url would need to contain a deviceId, then we would save the token as a hidden config field
I'm not entirely certain how to deal with the service secret, might have to take a look at how other open source projects deal with that.

**Usecases**
#92

**Comment by willosof** [comment]
I'm really tempted to just close this issue, but if you like; please elaborate. 
Which modules would benefit from this? The spotify usecase is also a weird example. In the case of spotify we would need to control the spotify application with a listener application that would control it via applescript and similar ways on windows, and not the _service_?

**Comment by willosof** [comment]
If you have a solution and a plan for it, sure - go for it! :) I'm excited to see what you come up with. What I meant was that neither me or Håkon would prioritize fixing this unless there was a demand for it. Thus seeing it as a dead ticket that might as well be closed, but that changes if you want to contribute. 👍
