### ISSUE TITLE
Latch/Toggle Button Color Options

### ISSUE THREAD

**Issue by howlingwolf487** [bitfocus/companion#412]
Currently, the Latch/Toggle check box only affects the function of the button and not it's overall visual status.

I would like to see the ability added to change color based on Key Down/On and Key Up/Off status.

**Comment by krocheck** [comment]
@willosof could we put a  nested array in companion-module-bitfocus-companion to track the button states, invoke callbacks in lib/action to update those with changes, and expose a feedback via the module for button up/down state?

**Comment by willosof** [comment]
You can do this with internal actions now. Relates to #495 and #367. f078ab9

**Comment by AwesomeTaylor** [comment]
I'm sorry if this is the wrong place to comment, but can anyone explain how to do this? I've been looking and haven't found the option to allow it.

**Comment by howlingwolf487** [comment]
Agreed! How do we accomplish this with internal actions?

 - Jordan

**Comment by AwesomeTaylor** [comment]
I figured it out, you need to download the latest release.

**Comment by howlingwolf487** [comment]
Makes sense; thought I had it, lol. All these updates are great, but difficult to keep track of.

 - Jordan

**Comment by racezx812** [comment]
@AwesomeTaylor how did you do it? Could you please explain. Thanks
