### ISSUE TITLE
Module Request: StageTimer2

### ISSUE THREAD

**Issue by JeffreyDavidsz** [bitfocus/companion#413]
It seems that stagetimer2 supports OSC, who has some time? Want to do an other module first

**Comment by krocheck** [comment]
Do you have a link to the manual with the OSC spec?  My quick Google turned up nothing of value.

**Comment by JeffreyDavidsz** [comment]
Nope just saw it on the companion Facebook. Including commands

**Comment by krocheck** [comment]
Its a relatively easy spec in general.  Two questions that I end up having for the parameters are:
1. Do the numbers, specifically H M S, require double digits or is normal formatting OK (1 vs. 01)?
2. Do the strings require any escaping or encapsulation outside of what is normally expected for OSC strings?

The numbers are easy to just program double digits and assume it will work.  The strings concern me, but beyond that I could whip this up pretty quick.  But someone would need to test.

**Comment by krocheck** [comment]
Sounds good.  Are you going to implement timer 1/2 as a dropdown within the various commands?

**Comment by JeffreyDavidsz** [comment]
Yes was my idea also

**Comment by JeffreyDavidsz** [comment]
Module is ready @willosof  you can close this issue. Tnx
