### ISSUE TITLE
Custom design web control

### ISSUE THREAD

**Issue by mrfipe** [bitfocus/companion#416]
Hello, 

Is it possible to configure or custom made the webpage for web control? 

Best Regards
Filipe

**Comment by haakonnessjoen** [comment]
You can control which pages it should show by adding ?pages=2,33,22 etc. So the url would be http://127.0.0.1:8000/tablet.html?pages=2,33,22

Then it would only show the buttons for pages 2, 33 and 22.

But please send questions to the facebook group or the slack channel. This issue tracker is for bug reports or feature requests :)

**Comment by willosof** [comment]
I think the issue starter is probably thinking of colors and arrangements?

**Comment by mrfipe** [comment]
here is the answer 

<html>
<head>
<title>My Great Page</title>
<script language="JavaScript">
function press(button)
{
httpObj = new XMLHttpRequest();
httpObj.open("GET","http://127.0.0.1:8000/press/bank/"+button,true);
httpObj.send();
}
</script>
</head>

<body>
<button onclick='press("4/6")'>Click me: 6</button>
<button onclick='press("4/12")'>Click me: 12</button>
</body>
</html>
