### ISSUE TITLE
Module Request: JustMacros Integration 

### ISSUE THREAD

**Issue by Sam-D03** [bitfocus/companion#420]
**Describe the feature**
Allows Companion to trigger macros (lua scripts) within the broadcast automation software 'JustMacros'.

**Is this platform dependent (windows, mac, ..)?**
JustMacros is a Windows only application.

**If documentation is required to implement, do you know where to find it?**
I believe that JustMacros can accept HTTP Post commands, but am unsure of the protocol. It uses port 39812 to accept http.

**Usecases**
-Just Macros allows extremely complex scripting of Blackmagic hardware.
-Just Macros can only currently be executed using XKeys panels.
-Just Macros can save 'snapshots' of blackmagic hardware, that can then be recalled in macros.
-If Companion could execute JustMacros macros, it would allow the Stream Deck to work with JustMacros.

**Comment by spiritimk** [comment]
JustMacros has a webserver running on port 39812.
Single calls or entire scripts can be triggered by GET requests at that port in the following format:

**Single call**
http://ip.of.just.macros:39812/EXECUTELUA:FunctionName(param,param,...);
_Example: http://ip.of.just.macros:39812/EXECUTELUA:ATEMMixerAUXSetInput(1,3,8);_

**Script Trigger**
http://ip.of.just.macros:39812/EXECUTESCRIPT:SavedScriptName

**Comment by krocheck** [comment]
@Sam-D03 or @spiritimk I have a module in progress.  ScriptExecute is working because I can see output within JM, but I am having trouble getting the generic FunctionName() execution to work.  I'm trying to just execute them within JM as a start and I either get an error printout telling the correct usage or no output, which I assume means I provided valid input.  But I tried an ME cut and didn't see the switcher execute that.  So if I have an ATEM 2 ME, can you give me an example function with parameters I can plug in to test?

**Comment by Sam-D03** [comment]
@krocheck Dude thank you so much for working on this! This is big for many advance users of ATEM's - especially in esports. An example of performing a cut on an ATEM that is connected to JustMacros:

`ATEMMixerMECut ( 1, 1 );`

Those parameters are: Which ATEM is this command for if you've added more than one ATEM to justmacros, then which ME on the atem are you performing the cut on. So the above command is ATEM 1, ME 1 - perform a cut.

**Comment by krocheck** [comment]
Got it ... I was forgetting the ; when trying on the JM console.  All good.  We'll get this rolled in.

**Comment by krocheck** [comment]
This is available in current build 1217 and higher.  We don't recommend using current builds in show critical situations, however, they are available for testing new functionality.

**Comment by Sam-D03** [comment]
> This is available in current build 1217 and higher. We don't recommend using current builds in show critical situations, however, they are available for testing new functionality.

Hey @krocheck - Thanks so much for implementing this - was using it loads with the build you suggested! Noticed the JustMacros module isn't in the latest release though? Should it be?

Thanks!

**Comment by krocheck** [comment]
@Sam-D03 there hasn't been a release since the module was added.  Look for it to be in v1.4.0 when that comes out.
