### ISSUE TITLE
Pro Presenter - windows

### ISSUE THREAD

**Issue by anthth** [bitfocus/companion#422]
I was trying to use the pro presenter module with pro presenter on a windows machine.  and it would not work. It said it was connected but not control
Companion was running on a windows machine as well

**Comment by SteveTherrien** [comment]
The latest [stable build](https://builds.bitfocus.io/companion/stable/) of Companion doesn't work with ProPresenter for Windows, however that was fixed on December 11 and any [bleeding edge build](https://bitfocus.io/companion/) after then should work.

**Comment by anthth** [comment]
Thanks
