### ISSUE TITLE
Used Button Colour

### ISSUE THREAD

**Issue by hadphild** [bitfocus/companion#427]
**Describe the feature**
Unused Buttons have as default Background colour and default for used buttons.

**Is this platform dependent (windows, mac, ..)?**
Easy to select

**Usecases**
Ease of use

**Comment by willosof** [comment]
used? like, for fireworks? :p

**Comment by hadphild** [comment]
As is if a Button has action assigned but no PNG or Text then it goes grey (Or Random Colour of programmers choosing)

**Comment by josephdadams** [comment]
Duplicate of #613
