### ISSUE TITLE
Able to create duplicate 'Internal' instances but cannot delete them

### ISSUE THREAD

**Issue by krocheck** [bitfocus/companion#430]
**Describe the bug**
A user is able to add additional instance of "Bitfocus Companion", however since that module is filtered from the Instance list there's no way to remove it once added.  Issue being users may inadvertently add it thinking the module allows remote control of another Companion server.

**To Reproduce**
1. Go to the Instance tab
2. Add a 'Bitfocus Companion' instance
3. Go to a button and add an action
4. The "internal" actions will be doubled up under an instance called "companion"
5. Return to the Instance tab, no 'companion' instance will be listed

**Expected behavior**
Should not be able to add an additional instance of this internal module

**Screenshots**
![image](https://user-images.githubusercontent.com/749812/50851771-54ec0000-1343-11e9-813e-cfa29a88448c.png)
![image1](https://user-images.githubusercontent.com/749812/50851775-574e5a00-1343-11e9-8ab8-551f0b6ea2b5.png)

**Comment by krocheck** [comment]
I've checked.  The module is properly filtered out of the manufacturer and categories dropdowns.  It is only present via the search to add function.

**Comment by willosof** [comment]
I believe this was fixed by @krocheck in commit 3741b88
