### ISSUE TITLE
Model Request: Kramer VS-84H Matrix

### ISSUE THREAD

**Issue by graphicsop** [bitfocus/companion#433]
Salvos for Kramer VS-84H Matrix would be great please. 

Product manual:
https://k.kramerav.com/downloads/manuals/vs-84hn_rev_12.pdf

Many thanks!

**Comment by SteveTherrien** [comment]
I'm currently writing a module for Kramer video matrixes using their older Kramer Protocol 2000 (I only have access to a [VS-66HDCP](https://k.kramerav.com/downloads/manuals/vs-66hdcp.pdf), which doesn't support the newer Protocol 3000).

The good news is it looks like newer matrixes can be switched to work with either the older Protocol 2000 or Protocol 3000 (see section 8 in your matrix's manual), so this should be an option for you once I get this module finished.

**Comment by graphicsop** [comment]
Great.
Thanks very much Steve.

**Comment by willosof** [comment]
@SteveTherrien just added (347eeb8) a kramer-matrix module now that is ready for testing. Available in build 1222 :)
