### ISSUE TITLE
Surface "Extend" Mode

### ISSUE THREAD

**Issue by thereisnoh** [bitfocus/companion#438]
**Describe the feature**
A clear and concise description of what the feature does

Have the ability to "Extend" (like the way a computers second display might) the buttons of stream deck surface [x] to surface [y]. The surface settings page would have a dropdown selection displaying other connected stream decks saying "Extend this surface [x] to [y]".
Then each button layout page could have a checkbox for "Extended buttons" and the number of stream decks in that page. For example, the main stream deck retains navigation buttons and buttons x.1->x.12. With the checkbox ticked and 1 stream deck added buttons x.15->x.27 appear on the extended surface [y] when surface [x] is on said page. When surface [x] is not a page with an extension, surface [y] can be on any non extended page.

**Is this platform dependent (windows, mac, ..)?**
Explain

No

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

Maximizes number of buttons and ease of use when using more than one stream deck in tandem. Navigation being linked retained on one stream deck when pages require it or letting the second be free to navigate when it is not needed for the extended buttons also increases flexibility and usefulness .

**Comment by willosof** [comment]
This will have a solution when the nopagebuttons branch is released. Then you can do whatever you like :)

**Comment by josephdadams** [comment]
Closing because once nopagebuttons branch (2.0) is released, you can do this if you want. This seems niche to keep open as an issue for all.
