### ISSUE TITLE
Module repository request: ASI-SYNC

### ISSUE THREAD

**Issue by dajeinc** [bitfocus/companion#439]
I hope this is the right place. I am following the module development guide and am at:
"Now, you need to ask the core developers to create a repository for your module, and wait for them to create the module repository."

IT does not say how to contact the developers so here I am :-)

**Describe the feature** (ill describe the module i am building)
We have a software that controls presentation files for live events. It runs on four different computers and is called ASI Sync. The module I am creating will control certain functions of the software using the stream deck and companion software from one central location.

my repository is https://github.com/dajeinc/companion.git

my contact is dhunter@brightwebsystems.com

Thank you

**Comment by willosof** [comment]
Sorry about that, please follow this link to enter our slack chat :-)

https://join.slack.com/t/bitfocusio/shared_invite/enQtMzY5NTQ2OTA1MjAzLTE3NTQ5NjYyNGVlYTk4ZGYwNTcxZjE4NjEyYzc1N2U2ZjkxOTAyMDFkZDU1MTAzMWYzYzdiY2UxMWJkMGU2MzI
