### ISSUE TITLE
play icon after hibernation?

### ISSUE THREAD

**Issue by mrowwy** [bitfocus/companion#445]
Repeating JS errors on any action after I re-scan/detect my StreamDeck after my computer wakes from hybernation.

Restarting Companion resolves the issue.

![image](https://user-images.githubusercontent.com/1996611/51339241-c8c39200-1a40-11e9-985e-f9e14b0160a1.png)

**Desktop (please complete the following information):**
 -Win10 x64
 - Vivaldi
 - 1.1, 1.2, 1.3

**Comment by haakonnessjoen** [comment]
Is this reproducible every time?

**Comment by mrowwy** [comment]
Indeed. Every time I hibernate my laptop I can also confirm that this happens if the USB is unplugged and replugged it will cause the same or similar error.

**Comment by haakonnessjoen** [comment]
Hi,

I have made some changes. Could you test if this version works any better?

https://builds.bitfocus.io/companion/branch/companion-1.3.0-fix-445-abd33b7-win64.exe

**Comment by mrowwy** [comment]
![image](https://user-images.githubusercontent.com/1996611/51493838-6e417300-1d6b-11e9-937d-2e4b6d99ad74.png)

Still the same issue on USB unplug/replug.

**Comment by mrowwy** [comment]
It does appear that the issue with hibernating is resolved, though it shows the "Play" icon (Triangle with Circle) until I press one of the stream deck button when it comes back from hibernation.

**Comment by josephdadams** [comment]
@mrowwy are you still experiencing this issue or can we close it?
