### ISSUE TITLE
Docs for module development should include complete example package.json

### ISSUE THREAD

**Issue by tfe** [bitfocus/companion#447]
When working on a new module, it's hard to determine which attributes of the `package.json` file are used by the app. Specifically at first I didn't know I needed to include `shortname` and `keywords` attributes.

There is an [example `package.json` in the docs](https://docs.bitfocus.io/companion/development/modules#what-makes-up-a-module) but it doesn't include these required-ish fields.

It would be nice to list which fields are required/expected by Companion in the docs and/or include them in the example code snippet.

I'd be happy to modify the docs if someone could give me a canonical list of the attributes. These are the ones I know about right now:

- `name`
- `description`
- `manufacturer`
- `product`
- `shortname`
- `keywords`

**Comment by krocheck** [comment]
I was thinking about this earlier.  I might suggest we create a 'companion-module-sample' repo and just have a solid base module with a lot of inline comments.  The developer docs are still needed, but I think that would give a better canvas to start then people grabbing other modules as a base.  Sometimes that's appropriate, but it would be better to have a base and copy/paste over from other modules the things you want (or just to have the clean structured slate to start your own thing).

**Comment by tfe** [comment]
Ah yes this would be way better! Showing rather than telling is always better.

It'd be even better if the example were somehow already included in the project so you don't have to know about git submodules to get started. They could just rename the sample module and have it show up immediately without any git submodule gymnastics. Not sure if this is architecturally possible? I haven't used submodules very much so it was unfamiliar to me.

**Comment by krocheck** [comment]
@willosof do you want me to a sample repo going?  Do we maybe want to do both es5 and es6 samples?

**Comment by willosof** [comment]
Sure! Should we implement it as a normal module, and just make core skip it when loading? Or should it be a wiki only project?

**Comment by krocheck** [comment]
Code project(s) but not included in the core.

**Comment by tfe** [comment]
Two ideas on this:

1. I think a separate repo makes sense as something that could be cloned by itself to start a new module, but is then easy to push back up into the official repo once it has been created, i.e. it should be in the same form that a module repo should eventually look like.

2. What would be even better is a `bootstrap.sh` script that is smart enough to 1) clone the above repo, 2) set it up as a submodule (or whatever necessary magic) so that it Just Works™ when running `npm run start`.

Maybe for bonus points, interactively prompt for the module name and use that to name the folder it clones into (or set up the submodule; still not clear on how this part works).

**Comment by Julusian** [comment]
The wiki has a complete package.json now https://github.com/bitfocus/companion/wiki/package.json
