### ISSUE TITLE
`rest_get` should support HTTP basic auth or accept custom request headers

### ISSUE THREAD

**Issue by tfe** [bitfocus/companion#448]
**Describe the feature**
Sometimes it may be necessary to use custom request headers in an HTTP GET request. Specifically, some devices require the use of HTTP basic auth.

We could either support that use case directly, or it'd be more flexible to accept any custom headers to include with the request, allowing the caller to build their own auth header or whatever else they need.

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
Docs for the HTTP client in use: https://github.com/aacerox/node-rest-client

**Usecases**
Some devices require HTTP basic auth to access their APIs, e.g. the [Matrox Monarch](ftp://ftp.matrox.com/pub/video/doc/Matrox%20Monarch%20HDX%20Dev%20Tools%20Reference%20guide_v.1.1.5.pdf).

**Comment by jasplund** [comment]
Hi
Is there any progress on this? :)
Me and my friend is trying to control a Axis PTZ IP camera using their REST API and it works fine if setting the camera to accept anonymous controlling but that is not very secure. Basic authentication will do the trick :)

**Comment by smayberry** [comment]
Based on the responses when I previously asked about rest_get it sounds like it's sort of dated and not likely to get much attention. My suggestion would be to just use your library of choice (e.g. node-fetch if you want my opinion). Here's a link to the Slack thread: https://bitfocusio.slack.com/archives/CFG7HAN5N/p1575946293368300?thread_ts=1575946293.368300&cid=CFG7HAN5N

**Comment by Julusian** [comment]
rest_get has for a while supported passing extra headers, but I would recommend using an alternate library such as [got](https://www.npmjs.com/package/got) or [node-fetch](https://www.npmjs.com/package/node-fetch) instead
