### ISSUE TITLE
Docs for module development should include notes about `debug` and `log` functions

### ISSUE THREAD

**Issue by tfe** [bitfocus/companion#449]
It'd be helpful to note the availability of basic dev infrastructure features and utils that are available when working on a module, e.g. the `debug` and `log` functions.

Specifically it'd be good to include:
- where the output from each goes (debug to the console, log to the GUI) so one knows where to look
- arguments they take (e.g. can't pass a raw object, I think? needs to be stringified)
- appropriate times to use them (e.g. `info` vs `error`) and how they appear in the GUI (e.g. errors in red)
- established conventions, e.g. modules generally should only log errors to the UI, not info-level statements

**Comment by Julusian** [comment]
This task is rather old, and while still valid this has already been documented for the new module api in 3.0.
As such, I don't think it worth us trying to update the documentation for 2.x, as a lot of it looks like it needs an overhaul to me
