### ISSUE TITLE
PVP 3 - Add support for Target Sets

### ISSUE THREAD

**Issue by chrisrouse** [bitfocus/companion#459]
I added this as a bug to the module, but it seems this is the better place to request it. https://github.com/bitfocus/companion-module-pvp/issues/6

I worked out the code needed for this, but I can't figure out how to setup the project correctly on my computer to be able to make a pull request successfully, so someone else will need to verify the code in their project and then push it.

Code to add support for Target Sets. Current limitation is that it only selects by Name or UUID, not by index. I've filed a bug report with Renewed Vision about this. 

https://gist.github.com/chrisrouse/911369e55b0c3314d323cebe92f1cfe2

**Comment by SteveTherrien** [comment]
Thanks for the code, I'll start giving the PVP module some attention shortly.

**Comment by chrisrouse** [comment]
Excellent! I can help with testing along the way as well.
