### ISSUE TITLE
Improved keyboard hotkeys / shortcuts

### ISSUE THREAD

**Issue by Tracehunter** [bitfocus/companion#464]
Hey,
First I'd like to say good job so far ! This project look real promising !

**Describe the feature**
Improved module for hotkeys / key strokes
Octopus Listener is a start, but sadly it seems modifiers keys doesn't work.
Also, it doesn't support key down/up state.

It'd be really great being able to do something like this :
Key : Ctrl - Down - Delay 0ms
Key : C - Delay 10ms
Key : Ctrl - Up - Delay 20ms

**Is this platform dependent (windows, mac, ..)?**
Nope

**Usecases**
As a web developper, I feel like this has a real potential for integration in a daily workflow. I'd really want to run specific macros using Companion !

This is already doable using a physical stream deck, but I think it'd be so great being able to use a tablet / 2-in-1 instead of a stream deck !

**Comment by JeffreyDavidsz** [comment]
Hi @tracehunter the octopus listener is unfortunately not supported by the author. If started to write my own program. It's ready for testing but not completely finished. At the moment it's for windows, maybe you can try it? Search for the VICREO hotkey module in companion. The link for download is in de help section (download the icon also at the moment or it might fail on you)

**Comment by JeffreyDavidsz** [comment]
@tracehunter the MAC version is ready also check it out and make sure you install the latest version: https://github.com/JeffreyDavidsz/VICREO-Listener/releases
You can set the key down and key up in companion

**Comment by Tracehunter** [comment]
@JeffreyDavidsz Hey Jeffrey, sounds promising ! However, can't find  VICREO hotkey module in companion... Any idea ?

**Comment by JeffreyDavidsz** [comment]
@Tracehunter are you running a latest build or the official 1.3.0? It's not in there yet. you can find the latest builds on https://builds.bitfocus.io/companion/
I'm updating a release within the hour of the listener, which fixes some OSX stuff:
https://github.com/JeffreyDavidsz/VICREO-Listener/releases

**Comment by willosof** [comment]
Should this ticket be open, though?

**Comment by JeffreyDavidsz** [comment]
We can close this, requested functionality is in the module VICREO-Hotkey

**Comment by pepeflores2003** [comment]
I cannot see Vicreo-HotKey on the list of modules supported on Companion I'm afraid.
Can someone explain how on Earth can we send hot keys to multiple computers using Companion and Vicreo then?
Cheers

**Comment by JeffreyDavidsz** [comment]
Did you download 1.4?

**Comment by pepeflores2003** [comment]
Hey, many thanks for your response!I'm trying to figure out all this out..I have downloaded Vicreo from here:VICREO Listener

| 
| 
|  | 
VICREO Listener


 |

 |

 |




and then the companion-vicreo hotkey module from here:bitfocus/companion-module-vicreo-hotkey

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
bitfocus/companion-module-vicreo-hotkey

Contribute to bitfocus/companion-module-vicreo-hotkey development by creating an account on GitHub.
 |

 |

 |



For my initial test I'm trying to send a meesage from my windows pc to my mac mini with Companion and control powerpoint on the mac
But I can't figure out how i do have to install the vicreo hotkey module for companion or where exactly..
Can you explain a bit hot to set this up?
Many thanks,
p.



    On Monday, 16 September 2019, 19:59:53 BST, Jeffrey Davidsz <notifications@github.com> wrote:  
 
 
Did you download 1.4?

**Comment by josephdadams** [comment]
@pepeflores2003 no need to download Companion module code directly. If you’re using Companion 1.4, you have what you need for the client side. Then, simply download Vicreo Hotkey onto the computer you wish to execute hotkeys or key presses. This computer will run the Vicreo software and listen for commands from Companion. In Companion, configure the Vicreo Hotkey instance using the IP address of the computer running the Vicreo listener program. You can do this for as many computers as you like, just use multiple instances. If you don’t see the Vicreo Hotkey module in Companion, try using the search feature.

**Comment by pepeflores2003** [comment]
Jeez.. much appreciated for your help
I think Companion 1.4 must have been released very recently because I was totally convinced of running the very latest version of Companion.. but I was totally WRONG!
Apologies for the stupid error
It works like a treat.. boom shakalaka!  🤠
I'm in.. 
Thanks!

**Comment by liquidsky1001** [comment]
Hi, maybe add keyboard shortcuts directly in companion like its is in the stream deck software? Is that a possibility? 

Greets

**Comment by josephdadams** [comment]
What keyboard shortcuts did you have in mind?

**Comment by liquidsky1001** [comment]
Any that is on the PC keyboard... A function in companion “add keyboard shortcut” and than learn by pressing the keyboard button to add witch shortcut needs to have the function in companion.

**Comment by josephdadams** [comment]
Capturing the key press across all platforms would be the challenge. And not really possible on headless installs. What about using a key capture program for your specific OS that can then send HTTP, OSC, TCP, etc. that triggers Companion to press a button?

**Comment by liquidsky1001** [comment]
now im using companion-module-vicreo-hotkey but have a install issue on some PC for viceroy...
so i tought it might me much easier like the way like the stream deck software. They have also e menu to choose the shortcut.
![stream deck](https://user-images.githubusercontent.com/61633404/75613939-638f0b00-5b33-11ea-9f07-9dfd297f07d6.png)

**Comment by JeffreyDavidsz** [comment]
I could make a local vicreo module, it would send hotkey's on the machine where companion is running

**Comment by liquidsky1001** [comment]
that looks nice!

**Comment by rdcsg** [comment]
Hi! @JeffreyDavidsz in your documentation (https://www.vicreo-listener.com) you say to send objects. Is that what I should send in Companion? I've created a button in Companion on one computer in the local network and via the listener I can see the output coming from it, independently if it is `right` or `{ "key":"right", "type":"press", "password":"" }` the listener says `KPRESSright`or `KPRESS{ "key":"right", "type":"press", "password":"" }`.

My question is: what can I do with this? How do I have Keynote or Powerpoint step forward as if it would be a `right`key press?

**Comment by JeffreyDavidsz** [comment]
@rdcsg I don't really understand your question. It seems you are not using the VICREO-Hotkey module in Companion? That will create the commands for you. If you receive it on the Listener but nothing hapens make sure the program in in the foreground. On windows do a restart first after install and on OSX make sure that the right rights have been given to the program

**Comment by rdcsg** [comment]
Hi Jeffrey, and thank you for the quick reply. =)

I am sorry if I am failing at being clear. =)

Here is an image from Companion from "the first" computer when the listener app is running on "the second" computer. 
<img width="651" alt="image" src="https://user-images.githubusercontent.com/19893753/135673375-c1407482-27c2-40a0-baa5-73320330f062.png">

The button commands look like this, three different buttons respectively:
<img width="642" alt="image" src="https://user-images.githubusercontent.com/19893753/135673679-b4a84ac0-c75c-40d1-8664-100b1022091d.png">

<img width="632" alt="image" src="https://user-images.githubusercontent.com/19893753/135673705-ea20cc8a-0d8b-4d95-ac15-cbf9a4bc1d2a.png">

<img width="636" alt="image" src="https://user-images.githubusercontent.com/19893753/135673751-01b0f1f5-83f5-4e7b-9327-529c36ada2e6.png">


Clearly I am missing something crucial and I am having a hard time understanding what that is.

Many thanks for taking the time! =)

**Comment by JeffreyDavidsz** [comment]
Ok remove all three commands, and use special key. From the dropdown select arrow right. Key press is for pressing down only
