### ISSUE TITLE
Prefix variable in HTTP instance settings

### ISSUE THREAD

**Issue by DeeJayMX** [bitfocus/companion#468]
HTTP Instance Settings
Just add a variable that can be set in the settings of an HTTP instance like the IP or the prefixe of the request or post in the button.

for a request (get or post) like "http://2.0.0.10/?TestSurface"

In the instance settings you have:
INSTANCE HTTP -> prefix Variable like "http://2.0.0.10/" set in.

and in the button settings of the http instance you use the already set prefix like
BUTTON key option -> "{InstancePrefix}?TestSurface"

Platform independent

-------------------------

More Powerful request:
It could be easier if you can put the Prefix and suffix 'preset' for each action of the HTTP instance,
like a general prefix for the entire instance like "http://2.0.0.10/" as prefix
and preset action with name and suffix that you find in the button dropdown action settings.

So you set as a general settings in the instance:
"http://2.0.0.10/"

and you add preset actions in the instance settings with a name:

action name   -  action suffix
"Test Surface" - "?TestSurface"
"Test Clock"    - "?TestClock"
"Test Clock 10 Min" - "?TestClock&Time=10"

![image](https://user-images.githubusercontent.com/36418772/51933657-1ad1c380-2402-11e9-99ca-7c230880adb3.png)

And after you find your actions already set in the button settings:

![image](https://user-images.githubusercontent.com/36418772/51931048-3a65ed80-23fc-11e9-9e30-4388289e82e9.png)

All this could really speed up developpment of customise interface with custom machine or equipement.

**Comment by DeeJayMX** [comment]
I forgot the choice of Get and Post type of request to choose in HTTP Configuration settings

**Comment by willosof** [comment]
Yeah, this will be a bit too advanced for our current module API :( But it's a great idea! I'll keep it in mind for the future. In the meanwhile, I think I'll make a simplified version first.

**Comment by DeeJayMX** [comment]
Yeah Thanks for the assignement !

**Comment by krocheck** [comment]
@DeeJayMX the 'prefix' field has been added in the latest build, however, it is called 'Base URL'.  That language seemed to make more sense for what it does.

**Comment by DeeJayMX** [comment]
Yeahh Thanks you so much !!!
