### ISSUE TITLE
Feature request:  blink(1)

### ISSUE THREAD

**Issue by terriblefox** [bitfocus/companion#469]
**Describe the feature**
blink(1) is the world’s best indicator light, designed to give you glanceable notice of anything on your computer or the internet.

blink(1) makes it easy to connect any data source in the cloud or on your computer to a full-color RGB LED so you can know what’s happening without checking any windows, going to any websites or typing any commands.  blink(1) mk2 improves upon the original blink(1) with better functionality and great new features.

blink(1) packs three dimensions of information (color, brightness and pattern) into a single tiny package that fits into any USB port on nearly every device. It makes it incredibly easy to connect any data source in the cloud or on your computer to a full-color RGB LED so you can know what’s happening without checking any windows, going to any websites or typing any commands.

We designed blink(1) in the spirit of our favorite old school Unix tools and we tried hard to make it simple, flexible, and robust.

https://blink1.thingm.com

**Is this platform dependent (windows, mac, ..)?**

We endeavor to make all blink(1) source and APIs work on these platforms:

Mac OS X 10.7+ (10.6 in many cases)
Windows 7+ (XP in some cases)
Linux Ubuntu (and other Linuxes and *nixes like FreeBSD)
We come from a Unix background, so most of our tools work on Mac & Linux first.

We currently have APIs for:

C / C++ / Objective-C / Qt
Java
Processing
Python
Node.js
.NET
Ruby
Go
Linux kernel
and more added continually

**If documentation is required to implement, do you know where to find it?**

http://blink1.thingm.com/libraries/

**Usecases**

Add status lights for everything... status indication computer tally light .... cam status... mood status 😊
![blink1mk2_lifestyle_coffee_3-slider-1170x500 2x](https://user-images.githubusercontent.com/43913179/52067705-78d5e680-257b-11e9-9cc9-98487e155539.jpeg)
![blink1mk2-cloud-slider-1170x500 2x](https://user-images.githubusercontent.com/43913179/52067706-78d5e680-257b-11e9-9058-f552aa4fbc53.jpg)

**Comment by WXsniper** [comment]
Would this be better served as a feedback destination, or generally as a module? I'm not sure if there's a distinction though.

**Comment by JeffreyDavidsz** [comment]
Hey @terriblefox I've written the module with 2 actions and a custom action. Hopefully I will receive the blink(1) soon to do some tests. Thanks for the library link!

**Comment by haakonnessjoen** [comment]
Added in 44ec03e
