### ISSUE TITLE
Errors to log file on raspberry pi/ linux

### ISSUE THREAD

**Issue by Turnipisum** [bitfocus/companion#470]
On raspberry pi builds can we get errors like "net interface not found" etc. sent to log file rather than spamming console.

**Comment by sphlabs** [comment]
Depending on how you are launching Companion, you can direct all console and error messages to a file by appending `&> [log file name]` to the headless.js command. e.g. my companionLaunch.sh (run as a service) is:

`sudo -u pi /home/pi/companion/headless.js eth0 8000 &> companion.log`

**Comment by willosof** [comment]
Fixed.
