### ISSUE TITLE
Support for ProTally 

### ISSUE THREAD

**Issue by Deanbau** [bitfocus/companion#472]
**Describe the feature**
Support for josephdadams/ProTally -  https://github.com/josephdadams/ProTally

**Is this platform dependent (windows, mac, ..)?**
Mac/Win builds - NodeJs based

**If documentation is required to implement, do you know where to find it?**

> Generic TSL 3.1 Device
Your TSL device should send data in this format:

```
{
    address: 90,
    brightness: 3,
    tally4: 0,
    tally3: 0,
    tally2: 0,
    tally1: 0,
    label: '      LABEL     '
}
```

                   
**Usecases**
Protally currently supports 

> Ross Carbonite
> Ross Carbonite Black
> Ross Carbonite Black Solo
> Ross Graphite
> Blackmagic ATEM
> OBS Studio

Natively - Companion control required for all other switchers

**Comment by josephdadams** [comment]
I am the author of ProTally, so let me know how I can help.

**Comment by Deanbau** [comment]
The best wat you could be help would be to develop a module - 
More info : https://github.com/bitfocus/companion/blob/master/DEVELOPER.md

**Comment by willosof** [comment]
I see you're using my module in ProTally ;D (tsl-umd)

**Comment by willosof** [comment]
Joseph, please join us on slack :) https://join.slack.com/t/bitfocusio/shared_invite/enQtMzY5NTQ2OTA1MjAzLTE3NTQ5NjYyNGVlYTk4ZGYwNTcxZjE4NjEyYzc1N2U2ZjkxOTAyMDFkZDU1MTAzMWYzYzdiY2UxMWJkMGU2MzI

**Comment by josephdadams** [comment]
@Deanbau there’s now a Companion module for ProTally. Enjoy!

**Comment by CoBot3000** [comment]
Hey, sorry if this reopens the thread. 

So at the moment I have seen that companion can receive tallies from the Blackmagic switchers and them live to the Stream Deck. So Program bus goes red when selected and the preview bus green. 

Now, I was wondering if this thread is talking about that feature but for Ross Switches? We are using a few Ross switches with companions scattered around and it would just be awesome if we had tallies to tell us what is currently selected, especially when a key is on or off.

If this isn't the right thread then I will just open a new one :)

**Comment by josephdadams** [comment]
@CoBot3000 I just wrote a tsl umd listener module for Companion and submitted it yesterday. It will do exactly what you want.
