### ISSUE TITLE
Support for RossTalk triggers

### ISSUE THREAD

**Issue by monoxane** [bitfocus/companion#474]
**Describe the feature**
To be able to trigger Companion with RossTalk CC bank triggers and have an assignable Next trigger to use with the RollClip button on carbonite surfaces

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
http://help.rossvideo.com/carbonite-device/Topics/Devices/RossTalk/RossTalk.html#RossTalk

**Usecases**
So people can fire anything from a carbonite surface (Wanna roll QLab off the carbonite surface? Sure!)

**Comment by JeffreyDavidsz** [comment]
I don't have a Ross switcher at hand, but I'm seeing a custom option in the manual (Ross talk controll). Did you try that already? You can send a string TCP to companion to trigger a button. See below the actions at any button for the right syntax

**Comment by monoxane** [comment]
the custom control in the manual is the RossTaslk standard CC string, not an arbitrary tcp string that can be set by the user, its `CC <bank>:<control>` and nothing else, it would be easily worked into companion to trigger the page and button numbers

**Comment by JeffreyDavidsz** [comment]
@monoxane all right, so say you want page 3 button 4 pressed, what is the exact TCP string is being send?

**Comment by krocheck** [comment]
@monoxane you might not be able to answer this, but the 'Generic Device' protocol is stating that custom control is the full string "Custom Control" where-as for all the switchers the actual command string is "CC".  Any sense which is correct here?

**Comment by krocheck** [comment]
Nevermind all ... Ross Support said its the "CC b:cc" format.

**Comment by monoxane** [comment]
> @monoxane all right, so say you want page 3 button 4 pressed, what is the exact TCP string is being send?

for that the exact string being sent from the carbonite would be `CC 3:4` from what I can tell

**Comment by krocheck** [comment]
I had a thread with a Ross tech today and he said it is "CC xyy" where x is the bank (page for Companion) and yy is the number (bank # for Companion).  He said there isn't a semicolon.  The above example would be CC 304.

**Comment by JeffreyDavidsz** [comment]
Ok my idea was to add it to server_tcp so no extra listener connection is needed, agree?

**Comment by monoxane** [comment]
> I had a thread with a Ross tech today and he said it is "CC xyy" where x is the bank (page for Companion) and yy is the number (bank # for Companion). He said there isn't a semicolon. The above example would be CC 304.

Interesting, just a tad different to the way they do the rest of the commands.

> Ok my idea was to add it to server_tcp so no extra listener connection is needed, agree?

yeap absolutely my thought too

**Comment by monoxane** [comment]
#649 Opened to add them

**Comment by onfire4g05** [comment]
I think this can be closed since #1176 is merged.
