### ISSUE TITLE
Module request: Clock 8001 module

### ISSUE THREAD

**Issue by depili** [bitfocus/companion#476]
**Describe the feature**
SVV and Assembly organizing have created a osc controlled stage timer for raspberry pi, which displays the time in either hdmi out or on a led matrix driven by the raspberry pi. It's repository is at https://gitlab.com/Depili/clock-8001

This is a request for adding a module to companion for controlling the timer. The initial module implementation is at https://github.com/iskcrew/companion-module-clock-8001 and includes osc commands to the clock and provides feedback from the messages sent by the clock.

**Is this platform dependent (windows, mac, ..)?**
The module shouldn't be platform-dependent, the clock itself has been designed to run on a raspberry pi, but the hdmi output version can be adapted to other platforms where SDL support exists.

**If documentation is required to implement, do you know where to find it?**
The clock osc messages have been documented in it's repository.

**Usecases**
Mainly used as a stage timer and production clock. Has timer, time of day, text message and tally support from mitti/millumin.

**Known issues with the module**
Currently the clock sends utf8 encoded strings in it's feedback for the "tally" text and companion uses utf16 so special characters are broken.

**Comment by haakonnessjoen** [comment]
I've created a companion module repo for it at companion-module-depili-clock-8001 and added depili as maintainer.

The module needs to change its name in package.json to "depili-clock-80001" before it can be fully added to companion. Since we need to have the name of the vendor in the module name as well as the product name. (new rules)

**Comment by depili** [comment]
package.json updated and pushed to the new repository.

**Comment by haakonnessjoen** [comment]
Added in 87c8025
