### ISSUE TITLE
headless.js corrupts the config files if it dies due to errors during the bootup process

### ISSUE THREAD

**Issue by depili** [bitfocus/companion#479]
**Describe the bug**
This came up with #478 

If corrupted environment (or even just ctrl-c during the bootup process) kills the headless mode it corrupts the configuration files and further startup attempts result in
```
i@raspberrypi:~/src/companion $ ./headless.js wlan0
  app configuration directory /home/pi +0ms
  app mkdirp /home/pi/companion/ null +20ms
  config config construct(): catch err SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at new config (/home/pi/src/companion/bitfocus-libs/config.js:53:21)
    at new exports (/home/pi/src/companion/bitfocus-libs/config.js:5:9)
    at /home/pi/src/companion/app.js:41:13
    at /home/pi/src/companion/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:153:5) +0ms
  config ERRCODE: undefined +6ms
/home/pi/src/companion/bitfocus-libs/config.js:69
		if (err) throw err;
		         ^

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at new config (/home/pi/src/companion/bitfocus-libs/config.js:53:21)
    at new exports (/home/pi/src/companion/bitfocus-libs/config.js:5:9)
    at /home/pi/src/companion/app.js:41:13
    at /home/pi/src/companion/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:153:5)
```

**To Reproduce**
1. Replicate #478 
2. ./headless.js wlan0
3. See it crash due to missing usb-hid support
4. Fix the environment
5. Try to start headless mode again

**Expected behavior**
A clean exit in all situations that doesn't corrupt the configuration files and block further start attempts.

**Comment by depili** [comment]
This also happens after the stream deck updating stops working and the ./headless.js is killed by ctrl-c

**Comment by haakonnessjoen** [comment]
Thanks for the report! This was actually fixed upstream (bitfocus-libs) earlier today. Will update companion tomorrow!

**Comment by josephdadams** [comment]
@haakonnessjoen can you confirm this was fixed - can we close this?

**Comment by depili** [comment]
At least the companion 2.0 doesn't seem to corrupt the config anymore. It
also properly saves buttons created from presets even when the user
doesn't modify anything, which was another previous issue.

(If you only had buttons from presets the actions on the buttons wouldn't
get saved, having even one button with manually edited/added action caused
all buttons to save correctly, even the ones from presets)
