### ISSUE TITLE
Feature request: Logging of actions in GUI

### ISSUE THREAD

**Issue by Deanbau** [bitfocus/companion#48]
Would be neat to get some sort feedback in GUI after a button is pressed, along with timestamp!

Suggestion:

```
17:47:09 Page 1 Bank 1 pressed - mitti1:Play
17:48:01 Page 1 Bank 2 pressed- qlab:NextCue

```

**Comment by willosof** [comment]
This is now implemented, and it's up to the modules to make logging!
