### ISSUE TITLE
after importing config files some buttons do not show the actions in the config file 

### ISSUE THREAD

**Issue by Fader-Monkey** [bitfocus/companion#480]
*Before you report a bug, make sure you're not reporting something that have been fixed in the master branch by downloading a "latest" build from https://builds.bitfocus.io/companion/*

after importing config files some buttons do not show the actions in the config file. After the config file is loaded the buttons work as normal but when I go in to edit them there are no commands displayed. After I log out and back in the actions no longer work at all. It seems to be hit or miss with some of the instances, but the Spyder instance is constantly a problem   

1. Reset Full Configuration
2. Replace Full Configuration (Rail013119full-config.companionconfig)have had problems with others but for testing this is what I am on now
3. Edit Button 1.1
4. notice no actions (sometimes if you Disable and enable the instance they come back) (button still executes action but you cannot see the action in the edit tab) 
5. after log out and back in button no longer work.

[Rail013119full-config.companionconfig.zip](https://github.com/bitfocus/companion/files/2832899/Rail013119full-config.companionconfig.zip)

![after import full config](https://user-images.githubusercontent.com/47360319/52286998-ed6ba500-292e-11e9-9810-592467cb37c1.png)
![after import individual page](https://user-images.githubusercontent.com/47360319/52286999-ee043b80-292e-11e9-865f-a80ffc7f45a6.png)
![screen shot 2019-02-05 at 10 15 45 am](https://user-images.githubusercontent.com/47360319/52287052-07a58300-292f-11e9-8f03-179213495569.png)

 - OS: Mac Os 10.14.3
 - Browser Chrome
 - Version 1.3.0 (87c8025-1247)

I have always had problems with companion after log in and log out. that may be a separate issue I can add later

**Comment by DeeJayMX** [comment]
Same here, when I change the machine !
The button are here but the action not.

**Comment by haakonnessjoen** [comment]
Could you attach such a config file?

**Comment by JackTraore** [comment]
I'm having the same issue.

1.40 on a Window PC - buttons and instances come over but not actions. Button presses do nothing. 


[STREAMDECK_full-config_20190918-1445.zip](https://github.com/bitfocus/companion/files/3628303/STREAMDECK_full-config_20190918-1445.zip)

**Comment by willosof** [comment]
Thanks for the file. We've gotten similar reports on this without attached configs, and we'll release a fix in a matter of days if we can reproduce the error with your config :)

**Comment by Julusian** [comment]
Im pretty sure this has been fixed
