### ISSUE TITLE
Auto Rescan for Panels

### ISSUE THREAD

**Issue by hadphild** [bitfocus/companion#481]
**Describe the feature**
Auto Rescan for panels

**Is this platform dependent (windows, mac, ..)?**
NA

**If documentation is required to implement, do you know where to find it?**
NA

**Usecases**
If a USB Hub PSU looses power and you need to rescan when power comes back up. Can you Rescan every 1 min so these re-appear again

**Comment by haakonnessjoen** [comment]
It should be configurable in that case, since people use the scan function of companion to control whether you connect it to companion or the stream deck app

**Comment by hadphild** [comment]
We are using Companion to do a Basic install. I am running a 50m USB 2. If power is lost at the other end really want a it to boot back up and add its self back to the system.

**Comment by depili** [comment]
Would also be really nice for headless where currently you have no indication for lost stream deck and no way to re-add it except restarting.

**Comment by haakonnessjoen** [comment]
I will look at this soon. As a configurable option.

But @depili, even if it is headless, you can still control it via the web interface, so there is more ways to re-add it than restarting :)

**Comment by PerRoine** [comment]
Is the scan still a blokking action Håkon ? I know it was but has that been resolved ?

**Comment by depili** [comment]
Using the web interface would require hooking another computer to the same
private network in addition to the clocks and raspberry pi control panels,
which is way less than ideal.

**Comment by alatteri** [comment]
I +1 this issue.  Needs to be either a continuous auto-scan if communication to a panel is lost, or some configurable interval.

**Comment by DeeJayMX** [comment]
If you can expose a full simple url to trig a rescan, it could be scriptable by Windows itself with the device disconnect / reconnect event.

I saw that it's a web socket command that trig the rescan, I don't know how to connect and send webmessage by my automation system but I can trig simple URL.

My only way to do it right now is to close the app and restart it on disconnection / connection...

Not really bad but not really good...

**Comment by llamafilm** [comment]
Another use case for this:  I have Companion running on multiple computers which are all on a networked KVM.  So each time I switch the KVM to a different host, I have to re-scan USB.  It would be great to recognize a new device automatically.

**Comment by Julusian** [comment]
This will be in 3.0

**Comment by john-bednar** [comment]
@hadphild @dszoka not sure what are the planned changes in 3.0 or if that will help, but we have created auto surface rescan for companion-pi - https://github.com/bitfocus/companion-pi/pull/4
