### ISSUE TITLE
Module request: RadioDJ

### ISSUE THREAD

**Issue by fheinonen** [bitfocus/companion#483]
**Describe the feature**
RadioDJ has a REST server plugin which would be nice to control with Companion.  Generic HTTP POST and GET don't work with Companion, but using a browser to trigger works.

**Is this platform dependent (windows, mac, ..)?**
windows

**If documentation is required to implement, do you know where to find it?**
Link to REST server plugins forum post.
https://www.radiodj.ro/community/index.php?topic=6155.0
The plugin can be found in the disabled plugins folder of RadioDJ installed files.
**Usecases**
This would make triggering songs remotely a breeze.

**Comment by krocheck** [comment]
I'll take this one.

**Comment by krocheck** [comment]
@fheinonen I'm curious why you say GET requests using the Generic HTTP module don't work.

If you take URL that works in the browser and paste it into a GET action that should be the same thing.

**Comment by fheinonen** [comment]
The error I get crashes Companion, when I try to do a GET request. I don't have currently access to this machine, but I can get the error message if needed.

**Comment by haakonnessjoen** [comment]
@fheinonen that would be very nice yes. If companion crashes we need to fix it :)

**Comment by fheinonen** [comment]
I got things mixed up. GET works fine with latest stable and triggers RadioDJ. Using POST crashes Companion. 
![post_crash](https://user-images.githubusercontent.com/43732976/52518788-22db0000-2c59-11e9-9299-13d2235334db.jpg)

**Comment by krocheck** [comment]
@fheinonen could you please provide the input you're using for the POST when you get this crash.  You can obscure things like the IP and password if you like.

**Comment by krocheck** [comment]
@fheinonen the current build has an initial control module for RadioDJ (https://builds.bitfocus.io/companion/)  It is implemented based on the specification and is untested at this point.  When you have time, if you could please download and test all the actions we would appreciate it.  Please report back here with any issues or comments.

**Comment by fheinonen** [comment]
@krocheck Here's the POST command I used:
`http://127.0.0.1:7000/opt?auth=changeme&command=PlaycartByNumber&arg=1`

**Comment by fheinonen** [comment]
@krocheck Here are the results from the module testing, these were the errors, crashes and other notable problems:

PausePlayer doesn't work in browser, or not sure how to test in browser.

StopPlayer crashes, works in browser.
![stopplayer](https://user-images.githubusercontent.com/43732976/52585299-12837a80-2e3d-11e9-86a6-86320d6354fe.gif)

RestartPlayer crashes, works in browser.
![restartplayer](https://user-images.githubusercontent.com/43732976/52585317-19aa8880-2e3d-11e9-8f90-a8a2cb6218ab.gif)

PlayFromIntro crashes, not sure how to test in browser.
![playfromintro](https://user-images.githubusercontent.com/43732976/52585337-2333f080-2e3d-11e9-853e-93f0a310b633.gif)

ClearPlaylist crashes, works in  browser.
![clearplaylist](https://user-images.githubusercontent.com/43732976/52585345-2929d180-2e3d-11e9-9415-20e4df7e855b.gif)

ShowMessage doesn't work in browser.

**Comment by krocheck** [comment]
@fheinonen I made a change that should help with the crashes.  Please give the latest build a test.

**Comment by fheinonen** [comment]
@krocheck Yes, the crashes are fixed now, great. The other problems still stand, but seems like these are not related to Companion.

**Comment by krocheck** [comment]
@fheinonen yes my main objective was to get the exceptions suppressed, so we can check that off the list.  I'd recommend posting on the RadioDJ forums and seeing if there's a more recent spec they can provide.  The initial post is from 2014 and unclear when that post was last updated.  My experience from a past life implementing RadioDJ and navigating that space is that Marius does what he wants to do (and thinks best for the project), but he's never open sourced it and the community has little insight into the underlying code.  If I could inspect the API code (even the documentation was out of date) I could figure out what's going on, but without that this is rather difficult.

So getting a refresh of that documentation from Marius or simply noting what you see working vs. not over there may be of help to getting this done.

**Comment by krocheck** [comment]
@fheinonen since no new information has surfaced, I'm going to close this out.  If there's bugs you think we can flush out or more info about the API surfaces, feel free to open up an issue at the module's repo: https://github.com/bitfocus/companion-module-radiodj-rest/issues
