### ISSUE TITLE
Display the command being sent

### ISSUE THREAD

**Issue by hadphild** [bitfocus/companion#491]
**Describe the feature**
Display the command being sent

**Is this platform dependent (windows, mac, ..)?**
NA

**If documentation is required to implement, do you know where to find it?**
NA

**Usecases**
Displaying in Under the Button what command is being sent could help debug and improve modules to be checked with documentation.

**Comment by JeffreyDavidsz** [comment]
If there is a command that doesn't work please file an issue. People who use a developers environment can "debug" commands into a console. I don't think it's ok to display this for everyone.

**Comment by josephdadams** [comment]
Closing because displaying the commands is really not something non-developers would want to see, and @JeffreyDavidsz pointed out, developers can see it in the console if needed.
