### ISSUE TITLE
Barco FSN Implementation

### ISSUE THREAD

**Issue by SerialForBreakfast** [bitfocus/companion#493]
**Describe the feature**
Add a module for control of the Barco FSN.  I tested that Memory(Preset) recall works using the existing Barco Encore Preset Recall with no modifications.  Additional Protocol Specifications attached below. 

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
[FSN-150 Controller Protocol Specification.pdf](https://github.com/bitfocus/companion/files/2858670/FSN-150.Controller.Protocol.Specification.pdf)

**Usecases**
Its a great switcher for a lot of applications and Companion's basic preset recall implementation for Encore works with FSN.  Many operators don't know that you can control Memory Recall in FSN using Encore commands.  The FSN control surface is know to lock up under some circumstances, and external control via Companion would be valuable.

**Comment by JeffreyDavidsz** [comment]
What is it that you would like to add? Reading the spec you provided, there are only 2 commands. These are already supported by the encore module.

**Comment by willosof** [comment]
Let's close this one until @SerialForBreakfast wakes up and tells us otherwise!
