### ISSUE TITLE
Feature request: input data validation

### ISSUE THREAD

**Issue by dnmeid** [bitfocus/companion#50]
When offering an input field there should be a standardized way of validating user submitted data. Maybe an additional format property which contains a regexp. User data will be checked against the regexp and the text stays red while not matching (or some different warning sign)

**Comment by haakonnessjoen** [comment]
Fixed by 4fa8d78

**Comment by Deanbau** [comment]
IP's and port numbers need to be validated too

**Comment by haakonnessjoen** [comment]
They are
