### ISSUE TITLE
BUG: Importing via Replace Current Configuration gives non functional instances

### ISSUE THREAD

**Issue by richardgatarski** [bitfocus/companion#500]
Perhaps related only to vMix and Generic http: When importing a configuration using Replace Current Configuration neither of those two instances function. Status column remains blank, and Edit results in a Javascript error. Resetting configuration, and then importing as an Individual page (have only one) works fine.
- OS: Win10
- Browser Chrome
- Version 1.3.0 (1a7592b-1203)

**Comment by Fader-Monkey** [comment]
have same problem with christe Spyder on mac and raspi

**Comment by josephdadams** [comment]
This really sounds like a duplicate of #546.

**Comment by willosof** [comment]
Can't reproduce in 2.0.0-801d658-1986.

**Comment by Julusian** [comment]
I am pretty sure this is working now in recent versions
