### ISSUE TITLE
Roland V-1SDI control

### ISSUE THREAD

**Issue by stroemlund** [bitfocus/companion#501]
Wouldn't it be possible to control this over USB-Midi if the mixer where connected to the same PC as the stream deck?

I that case could we maybe integrate the Midi controls over USB for this to work?

**Comment by dnmeid** [comment]
Midi itself and Midi over USB are topics completely independent from the Roland V-1SDI or any other specific device. Midi is already requested and will be included sometimes in the future.
So this is kind of duplicate of #365
