### ISSUE TITLE
Group actions

### ISSUE THREAD

**Issue by stroemlund** [bitfocus/companion#502]
On our XR audio mixer in order to make a fade down for example we need to set the fader position with a given delay on each position. Going over your macro for debugging you get a lot of funcitons in there. Is it possible to make a group function so that we could mark all the fader actions and group them into a folder called fade up or fade down in order to keep the overview of the macro once they get rather complicated?

**Comment by dnmeid** [comment]
Hi stroemlund,
I don't know if I get you right. Can you please describe the requested feature again using the Companion terminology. E.g. we don't have a macro, so I don't know what you are refering to.

**Comment by josephdadams** [comment]
Closing due to not enough information and questions not answered. @stroemlund , if you can add more info, re-open the issue and do so, please.
