### ISSUE TITLE
Autohotkey

### ISSUE THREAD

**Issue by Marcus-Bernhardt** [bitfocus/companion#503]
how could we use a software like autohttkey with companion? Is there a software that does the same like autohotkey but has a restful API that can be triggered with companion? Companion works for us realy great, but we have some programs that we can not control via restful API

**Comment by JeffreyDavidsz** [comment]
If you are looking for a hotkey module/software, check vicreo-hotkey module (download is in the help section of the module). This emulates keyboard presses. It can also launch files like .bat or .sh or anything else

**Comment by Marcus-Bernhardt** [comment]
This works great! thank you!
