### ISSUE TITLE
Module Request: Extron IPL T PCS4

### ISSUE THREAD

**Issue by prb284** [bitfocus/companion#507]
I'd like to request the ability to control an Extron IPL T PCS4. 

Attached is the documentation on the unit. 

[68-738-07_IPL_T_PCS4_UG_B.pdf](https://github.com/bitfocus/companion/files/2902079/68-738-07_IPL_T_PCS4_UG_B.pdf)

**Comment by dnmeid** [comment]
FYI: Extron IPL T PCS4 is a ethernet controllable power switch with four outlets.

**Comment by JeffreyDavidsz** [comment]
@prb284 Which commands would you like to see? It's Extron so many are availible ;-)

**Comment by prb284** [comment]
I'd love to have the ability to switch specific switches on and off, and if status feedback is available, that would be great as well.

**Comment by JeffreyDavidsz** [comment]
I put in the module, please check if this works, there is a prefix in the commands which I'm not sure if its correct. I'll close this for now. When there is an issue please make a new one at the module
