### ISSUE TITLE
Feature request: plugin-system for drivers

### ISSUE THREAD

**Issue by dnmeid** [bitfocus/companion#51]
Drivers controlling "instances" or remote devices (there should be a user friendly name) should be usable with a plugin-system. So plugins can be maintained and distributed independent from core. Plugins should have versioning too.

**Comment by haakonnessjoen** [comment]
Partially implemented in 1cb418d, more to follow.

**Comment by dnmeid** [comment]
next piece implemented in fd69fef5c0db32fd4e6acc29654f4201769741c0
we're getting closer

**Comment by willosof** [comment]
I think we can close this. We've moved the modules out of core ;)
