### ISSUE TITLE
"Internal: Button Press" doesn't appear to work

### ISSUE THREAD

**Issue by chrisrouse** [bitfocus/companion#512]
Using 1.3.0 (1546115-1286) on Mac running 10.14.4.

Selecting Internal: Button Press doesn't seem to trigger the selected button. I'm assuming that "Bank #" is a 1:1 with each button on the StreamDeck with "Page 1" being "Bank 1" and then counting left to right.

I have button 1.4 (Bank 5?) set to send a clear command to PVP. The button works when pressed directly. If I try to use an internal button to trigger this button, nothing happens.

**Comment by Wilmshurst** [comment]
I have the same issue, i tried the press action, release action, and etc. none of them worked.

**Comment by Wilmshurst** [comment]
side note is there an internal command to unlatch a key.

i understand that i could send a toggle action, however im thinking of making a single key to unlatch any potentially latched actions, without setting off any that are currently off.

**Comment by willosof** [comment]
So, when did this stop working? 🤔

**Comment by chrisrouse** [comment]
@willosof Not sure. We just noticed it last week during some testing. It’s also not working in the current bleeding edge (as of 3/4).

**Comment by willosof** [comment]
Fixed. Sorry about that! My bad.

**Comment by DanDoidge** [comment]
Good evening.  I am also trying to create a "Global Unlatch" command to release any or all latched buttons.  
I have tried using the Internal Button Release command on version 1.4.0 (backport-b402e70-1559)and version 2.0.0 (12/03/19 build), but I am not successful.  
Is it possible to create a Global Unlatch?
Thank you.
