### ISSUE TITLE
Web Buttons page unable to scroll in android chrom

### ISSUE THREAD

**Issue by mrcwatling** [bitfocus/companion#514]
Hi, 

I don't have an elgato stream deck at the moment and was testing with the Web buttons on an android tablet running chrome, When the page appears the scroll bar is missing and I am unable to move down to see the other pages. I also tried the samsung browser that was on my tablet and it had the same issue.

This works OK on chrome on the windows 10 (scroll bar appears) but just not android. 

Wondering if this will be fixed? I noticed that there are a number of other request for android apps and you talked about possible rewrites of this but just trying to get a time frame that I can look at this again.

**Comment by willosof** [comment]
Fixed
