### ISSUE TITLE
Digital Projection Not Working

### ISSUE THREAD

**Issue by Cmillets** [bitfocus/companion#517]
**Desktop (please complete the following information):**
 - OS: [MacOS 10.14]
 - Browser [Chrome]
 - Version [V 1.3.0 (75c3cd1-1292)]
 
The Projectors(which are IP based) are not responding on the stream deck. The projectors ARE working through the DP web portal so the problem is not on that end. On the "Connections / Instances" tab the two projects show "status OK" so Im not sure what the problem is. I am running several other applications through companion(on the same Network) and there are ALL working just fine.
![screen shot 2019-03-02 at 3 48 00 pm](https://user-images.githubusercontent.com/48162499/53687444-af318d80-3d02-11e9-8772-408c8a8abd42.png)
![screen shot 2019-03-02 at 3 48 17 pm](https://user-images.githubusercontent.com/48162499/53687445-af318d80-3d02-11e9-9e61-3d99f6c948d2.png)
![screen shot 2019-03-02 at 3 48 36 pm](https://user-images.githubusercontent.com/48162499/53687446-af318d80-3d02-11e9-83dc-6e537aaa6a3a.png)

**Comment by haakonnessjoen** [comment]
Which projector models have you tested with?

**Comment by theapplepastor** [comment]
My 2x DP HiLite Laser's do NOT work with this either "DP WUXGA Laser 3D" they don't respond to ANY commands sent via companion

**Comment by ZeeshanMarwat** [comment]
same here can any body reply to this?
