### ISSUE TITLE
Internal instance can be disabled via itself (locking yourself out)

### ISSUE THREAD

**Issue by Cmillets** [bitfocus/companion#519]
I have disabled internal Instances 
Then thought I re-enabled it (but did not)
I then deleted the button that toggled it
Now i can't get internal commands!

Please help
(Not my brightest moment)

**Comment by willosof** [comment]
wow, that's an issue we've never encountered :p you could edit it manually in your config. what operating system are you on?

**Comment by willosof** [comment]
So, if you 
1) close companion (and the launcher)
2) find ~/Library/Application support/companion/db
3) search for "label":"internal"
![image](https://user-images.githubusercontent.com/426386/53769849-62ee7500-3edd-11e9-97bf-33a5cbab47d7.png)
4) right after that you got enabled:false, change that to true
5) save the file
6) start companion.

if you cant figure it out, delete your db (it will reset your entire config)

**Comment by willosof** [comment]
Bug fixed
