### ISSUE TITLE
Bug: Launcher does not scroll log automatically

### ISSUE THREAD

**Issue by haakonnessjoen** [bitfocus/companion#52]
**Describe the bug**
When the log entries fill up the textarea on the launcher, the textarea does not scroll down to keep the latest entry visible.

**To Reproduce**
1. Start Companion
2. Click on a streamdeck button enough to fill the log

**Expected behavior**
The textarea should scroll down with the text to show latest entry at the bottom.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Version 1.0.11

**Comment by willosof** [comment]
Wrong ticket mentioned above. Ment for #54

**Comment by haakonnessjoen** [comment]
I've also been able to reproduce this on OS X, if the log entry is more than 1 line long. For example if you push a button, and an error is given, the log window stops automatically scrolling down.

**Comment by willosof** [comment]
Yeah, well. the skeleton-log is supposed to only mention http server problems, etc. Not anything app-related. We'll implement #48 and then we've pretty much avoided this problem ;)

**Comment by willosof** [comment]
Launcher log removed for the time being.
