### ISSUE TITLE
Feature Request: Teradek Vidiu

### ISSUE THREAD

**Issue by tonygp22** [bitfocus/companion#523]
**Describe the feature**
To control features of the Teradek Vidiu. Ability to start and stop the stream specifically.

**Is this platform dependent (windows, mac, ..)?**
No it's it's own device.

**If documentation is required to implement, do you know where to find it?**
https://d1xl95ab8ijfds.cloudfront.net/Public/VidiU/Docs/Teradek_VidiU_Reference_Guide_v3_1117.pdf

**Usecases**
The Vidiu has very small buttons which make it difficult especially in low lighting to press and not make a mistake, it would be great to be able to control with a stream deck.

**Comment by jrmilt** [comment]
Also looking for this feature

**Comment by josephdadams** [comment]
I looked at this with Tony this week. We looked at the web page interface and what the client-side JS is doing with requests to the server side. Once logged in, the VidiU uses session-based authentication for the rest of the authenticated requests. If you're logged in and have the session info, you can start/stop broadcasts easily via a URL request to the CGI. So this will probably require using a library to track that session information and return it on subsequent requests.

**Comment by josephdadams** [comment]
This module has been created and tested and is awaiting a repo made so it can be included in a build!

**Comment by jrmilt** [comment]
Awesome! Thanks so much! Can’t wait to try it out :)

**Comment by josephdadams** [comment]
@jrmilt Do you have a dev environment set up where you can try it out? If not, it will hopefully get pulled into the core soon and added to a build.

**Comment by jrmilt** [comment]
@joephdadams I’m not knowledgeable on all the dev stuff so I’ll just have to wait for the build

**Comment by josephdadams** [comment]
@jrmilt it’s in a build now!

**Comment by jrmilt** [comment]
@josephdadams Thank you! I was able to test it out and works perfectly, but I am getting an error pop up from time to time as attached.
<img width="427" alt="Screen Shot 2019-04-20 at 11 33 14 pm" src="https://user-images.githubusercontent.com/6515511/56644288-c2d3f180-66be-11e9-8d50-c5a849cc483e.png">

**Comment by josephdadams** [comment]
@jrmilt Thanks for testing! Does it still work even though you get the error?

**Comment by jrmilt** [comment]
Yeah still works perfectly

**Comment by josephdadams** [comment]
@jrmilt I've pushed a bug fix that should help with this error. I'll ask for it to be upgraded in the core and put in a build so you can test it again. I'll update you when it's ready. Thanks!

**Comment by ciuchs** [comment]
Quick Question, Where do you find the password for this?

**Comment by josephdadams** [comment]
@tonygp22 can you answer this? I don’t know the vidiu interface very well.

**Comment by tonygp22** [comment]
@ciuchs You can set the password by using the web interface for the Vidiu. Just type the IP address of the vidiu into a browser then go to settings then system and you'll be able to set the password. Hope that helps!

**Comment by josephdadams** [comment]
Closing as this module is in the core and working well!
