### ISSUE TITLE
Adding instance

### ISSUE THREAD

**Issue by okarlsen** [bitfocus/companion#525]
**Describe the bug**
When I want to add a new instance in the gui on my MacBook Pro (Retina, 13-inch, Mid 2014) the end of the list is outside of the screen. Scrolling does not help.

**To Reproduce**
Open the gui on a MacBook Pro (Retina, 13-inch, Mid 2014).
Have tested in chrome and safari. Same behavior.

**Expected behavior**
Be able to scroll down the list of manufacturers.

**Screenshots**
<img width="1440" alt="screenshot 2019-03-07 at 14 36 41" src="https://user-images.githubusercontent.com/48322189/53960390-7c164200-40e6-11e9-8c79-d46498a779d7.png">

<img width="1440" alt="screenshot 2019-03-07 at 14 35 08" src="https://user-images.githubusercontent.com/48322189/53960320-46715900-40e6-11e9-8379-aa0aec5fc2a5.png">

**Desktop (please complete the following information):**
 - OS: Mojave
 - Browser chrome and safari
 - Version 1.3.0 (b629ffe-1307)

**Comment by willosof** [comment]
Good oold.

Duplicates #265 
Duplicates #122
