### ISSUE TITLE
Web buttons (Touch Monitor Scrolling)

### ISSUE THREAD

**Issue by 7sorkr** [bitfocus/companion#527]
Web Button
Touch monitor
Touch scrolling (Not)

**Comment by josephdadams** [comment]
Closing. Provide more detail and re-open.

**Comment by rkrossi** [comment]
Having the same issue
Companion 3.1.2 + 6243 stable - windows
Web Buttons on tablet (ios and android), the scroll dont work (you need to go really in the edge of the screen to be able to scroll)

**Comment by Julusian** [comment]
This would have been reintroduced with the fix for https://github.com/bitfocus/companion/issues/2656
@MeestorX This is why the web buttons wasnt ever full width of the page

**Comment by rkrossi** [comment]
probably, but the fact the buttons get bigger, there is no space on the sides, and since you cant "touch and scroll" on the top of button (only on the side) you get stuck and not being able to scroll the page (for instance, I have multiple pages and in this scenario the next page button dont work and the scroll on mobile neither)

**Comment by MeestorX** [comment]
Well, the ability to scale the Web buttons to any size is huge and I sure don't want that to go away.
Is there a video of the issue as I don't understand what problem you're experiencing. 
You can have space at the bottom and top of the window (or on the sides) by making the window taller or wider than the button layout.

**Comment by rkrossi** [comment]
https://github.com/bitfocus/companion/assets/9115045/3e0efb82-ea95-4599-8884-05e5ed17814f

please, take a look

**Comment by MeestorX** [comment]
Just tested on my iPhone, and you do need to go to the edge, but it doesn't seem too hard. Isn't there a mode though where you see just one page and use the page up/down buttons like the SD?

https://github.com/bitfocus/companion/assets/29129658/761206f2-9f68-4868-a10c-fe1e75455b71

**Comment by rkrossi** [comment]
yeah, you are right about not being hard but I work with some people that cant figure out this...
the page up/down buttons don't work too... and we have a lot of buttons to have all in the same page (and as I said before, need some clarification because people that will operate this has almost zero tech knowledge)

**Comment by MeestorX** [comment]
Interesting. That view does seem kinda buggy, doesn't go full screen.
I just use the Emulator, page buttons work there. Would that work for you?
Is there an advantage to the Tablet View over the Emulator?

**Comment by rkrossi** [comment]
ok... the emulator seens to work but.... if i use page up/page down it goes to a page without content (and not for the next page). since i am really new on this, am I missing some setting?

**Comment by MeestorX** [comment]
It should just match what a SD does. There are settings under the Surfaces tab.

**Comment by rkrossi** [comment]
exactly, I thought the same but for some reason, dont match....
If I add an emulator, and them I go to the page, I can see the first block (page) but If I click on PAGE DOWN it goes to an empty page

but..... if I click PAGE UP, it goes to the right page! hahaha

**Comment by rkrossi** [comment]
ok, so for some reason the "flipping" was inverted, all good now. I believe emulator is the best solution
