### ISSUE TITLE
support for Avolites Titan consoles (via HTTP)

### ISSUE THREAD

**Issue by PeterMaes** [bitfocus/companion#531]
Request for light consoles Avolites TItan (PC demo software , or the real consoles like Quartz / TigerTouch / Arena / Sapphire Touch) They all run the same Titan software. There is an API available. 
I have done some experiments and it works via standard HTTP requests, so it is already usable in Companion. The API is very extensive, so only a limited amount of commands should be implemented.
I am currently investigating how to implement a user friendly control as you can access faders and buttons in several ways.

**Is this platform dependent (windows, mac, ..)?**
NOT platform dependent

**If documentation is required to implement, do you know where to find it?**
https://www.avolites.com/webapi
https://www.avolites.de/en/support-downloads/web-api-demo#english

**Usecases**
The Avolites Titan lightconsoles are great.
The only way to trigger them remotely is via MIDI (hardware).
It would be nice to have control over the lights via Companion to integrate them in a show.

**Comment by PeterMaes** [comment]
[IPaddress]:4430/titan/script/Playbacks/FirePlaybackAtLevel?userNumber=#&level=$&bool=false
this is the easy way of getting control over all programmed playbacks.
Alll playbacksl get a unique usernumber when created. 
# is the unique user number for a playback 
$ is the value (from 0 to 1, in 0.001 steps)

**Comment by mbs4298** [comment]
I am interested in this but the other direction. With the current ArtNet option is there a way to trigger the companion buttons from an Avolites console?

**Comment by josephdadams** [comment]
Closing this because there's an Avolites Titan module now.
