### ISSUE TITLE
Internal Feedback

### ISSUE THREAD

**Issue by BasilChessman** [bitfocus/companion#532]
**Describe the feature**
Ability to receive feedback based on internal sates of Companion

**Is this platform dependent (windows, mac, ..)?**
no

**If documentation is required to implement, do you know where to find it?**
nope

**Usecases**
I use Companion toggle buttons to enable and disable different instances.   The button might be in its latched state (instance enabled) but in fact, the instance might have been disabled elsewhere.  If I could get feedback from Companion on the actual state of the instance, that would be fantastic.   Being able to assign a color to the instance state would be even better (eg., green for enabled and red for disabled).

**Comment by Julusian** [comment]
This has been done
