### ISSUE TITLE
Feature Request: Use feedback to push other buttons

### ISSUE THREAD

**Issue by RaulDuke77** [bitfocus/companion#534]
**Describe the feature**
Use the Atem feedback to control other functions when using Blackmagic Control Panel.

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
Companion intern

**Usecases**
Use the great functions of Companion when Atem is controlled by original Blackmagic Control Panel.
Example:
Input 4 in Preview recall Panasonic PTZ Preset 1
Input 5 in Preview recall Panasonic PTZ Preset 2
Input 6 on Preview cue Clip 1 in Mitti
Input 6 on Program play Clip 1 in Mitti

**Comment by studiovideo54** [comment]
Hi i need a preset for Data video ptz camera

**Comment by josephdadams** [comment]
Duplicate with #651. Closing this one as the other has more info.
