### ISSUE TITLE
Request: Page button is implemented on one button

### ISSUE THREAD

**Issue by doaremeng** [bitfocus/companion#537]
**Describe the feature**
A total of 15 buttons per page, very precious, is it possible to provide a multi-function button, display page number, control page turning, you can set it yourself, such as short press is page +, long press is page -, double click is back to the first One page...

**Usecases**
such as short press is page +, long press is page -, double click is back to the first One page...
I don't know if it can be realized technically.
Thank You!

**Comment by willosof** [comment]
This ish will be available when the nopagebuttons comes around. No ETA. (Maybe, just maybe around easter!). Let's try that first, and then we'll see if we need to reopen the ticket again.
