### ISSUE TITLE
headless.js and interface filtering

### ISSUE THREAD

**Issue by depili** [bitfocus/companion#538]
**Describe the bug**
I am working on an embedded headless companion package. For that I am starting the headless mode with systemd after network interfaces are configured. But headless.js only allows use of interfaces where the actual physical link is up. So a interface that has been configured with a static address and is shown on `ifconfig` can't be used for headless companion unless a cable is plugged in.

**To Reproduce**
1. Unplug cable from eth0
2. configure the eth0 with static ipv4 address
3. launch `headless.js`
4. See that eth0 is not listed as usable interface
5. launch `headless.js eth0`
6. See the error message `Interface not found!`

**Expected behavior**
I would expect a configured interface without the cable plugged in to still be usable.

**Desktop (please complete the following information):**
 - OS: linux / Ubuntu 16.04
 - Browser firefox
 - Version b61a536

**Comment by depili** [comment]
Butchering the os.getinterfaces code out of headless.js and just specifying the address that I want to use ends up working, even if the address belongs to an interface without the physical link up currently.

Since headless is meant for setups where it would be brought up on boot-time and the physical network link might be still down I would propose that instead of giving a interface name headless.js would take the address and the port as parameters.

**Comment by depili** [comment]
This is an example for using the address only, it lacks any kind of ip address validation:
```js
#!/usr/bin/env node
var main = require('./app.js');
var fs = require("fs");
var path = require("path");
var system = main();

function packageinfo() {
	var self = this;
	var fileContents = fs.readFileSync(__dirname + '/package.json');
	var object = JSON.parse(fileContents);
	return object;
};

var build = fs.readFileSync(__dirname + "/BUILD").toString().trim();
var pkg = packageinfo();

if (process.argv.length < 3) {
	console.log("Usage: ./headless.js <address> [port]");
	console.log("");
	console.log("Example: ./headless.js 192.168.81.1");
	process.exit(1);
}

system.emit('skeleton-info', 'appVersion', pkg.version );
system.emit('skeleton-info', 'appBuild', build.trim() );
system.emit('skeleton-info', 'appName', pkg.description);
system.emit('skeleton-info', 'configDir', process.env[(process.platform == 'win32') ? 'USERPROFILE' : 'HOME'] );

var port = '8000';

if (process.argv[3] != null) {
	port = process.argv[3];
}

setTimeout(function () {
	system.emit('skeleton-bind-ip', process.argv[2]);
	system.emit('skeleton-bind-port', port);
	system.emit('skeleton-ready');
}, 1000);
```

**Comment by alatteri** [comment]
> For that I am starting the headless mode with systemd

Can you provide your systemD file and steps to setup?  Would be very helpful to others setting up headless pi.

**Comment by depili** [comment]
The systemd unit is:
```
[Unit]
Description=Bitfocus Companion
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=pi
WorkingDirectory=/home/pi/src/companion
ExecStart=/home/pi/src/companion/headless_ip.js 192.168.81.1
Restart=on-failure
KillSignal=SIGINT
TimeoutStopSec=60

[Install]
WantedBy=multi-user.target

```

Note that you need to use the butchered headless.js from above for
reliability, as the interface physical link might not be up yet.

**Comment by willosof** [comment]
@haakonnessjoen i think you made the headless.js if I don't remember wrong? Maybe you can decide on what to include/change here :)

**Comment by jarodwsams** [comment]
@depili Sorry I'm quite late to the conversation, but I had a thought. If Companion itself is mobile, being used in this venue or that venue depending on need, then the IP address wouldn't necessarily be the same from one boot to the next. You could add an input prompt into headless to ask for the IP address to bind to, but the user might not know at boot time what IP address to use. I think it might be better if somehow headless could simply be forced to bind to the desired interface without checking for an active connection, and just bind to * on that interface.

Thoughts?

**Comment by depili** [comment]
Simply bind to 0.0.0.0 in that case (which you can't do without modifying
the current code...)

-- 
This message may contain traces of Truth.

**Comment by depili** [comment]
Having a input box would completely defeat the headless functionality, as
you would need to attach a keyboard and display to the computer, binding
to all interfaces and using iptables to filter the ones you don't want to
serve out is the solution.

The companion binding to a single interface is also quite false promise,
since most sockets will still listen on all interfaces, only the web
interface isn't available.

**Comment by jarodwsams** [comment]
You're absolutely right about the input box. I blame the fact that I was still waking up when I was typing that.

**Comment by jarodwsams** [comment]
@depili I just dropped your modified headless.js on my CompanionPi rig to confirm Companion will "detect" the active network connection post-boot. If it works the way we've talked about, then I'll be adding this modified headless.js (and your systemd unit file, because it's better than mine) to the CompanionPi image.

**Comment by depili** [comment]
And in case it helps here is a script I have used to provision headless
companion on raspberry pi 4 starting from the rasbian lite images:
https://gist.github.com/depili/17235ae0d4d05e8f9b5f268e49c09b47

It installs companion and it's dependencies, creates a way to set the
network configuration up from the boot partition and a systemd service
for companion that halts the machine on companion exit (so you can cleanly
shutdown the system from a companion button that has the internal "exit
companion" action mapped to it)

The image also is built to act as a network bridge, having the internet
from an usb wired dongle and internal network on the rpi ethernet, such
that it can provide ntp time to attached clock-8001 stage timers.

**Comment by jarodwsams** [comment]
My hat's off to you, good sir. That's quite the script. I had been thinking about muddling my way through putting together something similar (much simpler) until I decided to do the CompanionPi images.

Would you mind if I linked to that script of yours from the "Manual Installation" part of the Pi documentation, just as an example of another way to get it done for more advanced users? Obviously they'd need to be able to make their own adjustments to the file to fit their own needs, so that's not a "for everyone" kind of file.

**Comment by depili** [comment]
Sure, go ahead

**Comment by JeffreyDavidsz** [comment]
I'm going to close this, when needed feel free to reopen
