### ISSUE TITLE
Is there a way to get the bound companion address from a module?

### ISSUE THREAD

**Issue by depili** [bitfocus/companion#539]
Being able to bind listeners, like osc, to the same address as the companion web gui is bound to would allow listening on only the wanted network instead of all networks by binding the listener to 0.0.0.0

This is needed when companion is running on a device, that also bridges internet to a local network and thus it is inadvisable to listen on the internet facing connection.

**Comment by haakonnessjoen** [comment]
If your device is bridging internet, you should probably have configured a firewall facing the WAN interface anyways. Not sure if this should be companion's job.

**Comment by depili** [comment]
Then again if you would like to communicate api urls to a foreign device
from a module you would need to ip also for reporting such api endpoints.

Companion already has the ip address it uses to bind it's network
listeners somewhere, shouldn't be hard to expose that as a constant to
modules?

Currently this leads to strangeness where some stuff is received on all
interfaces and some not.

**Comment by willosof** [comment]
I hear you, but it's a RRRREALLY boring thing to fix, so, unless we throw money on it, I think it will be pretty low on the priority list. How badly do you need it?

**Comment by Julusian** [comment]
I dont think this is something we should do.
The webui is by default bound to localhost, meaning that any module following that will likely not have he desired result.

Or in future, the module may not have access to the same interface (maybe they are in different docker containers?)

I think a better strategy is that if a module feels the need to bind to a specific interface, then it should be a field in the instance config
