### ISSUE TITLE
Module Request: Roland VP-42H support

### ISSUE THREAD

**Issue by Kuufi** [bitfocus/companion#542]
Module for VP-42H Video Processor

This module should give full control over **presets, scenes switching** and inputs. 

This platform is web based, connects via IP, controlled over web interface or Telnet

Documentation: [Manual](https://static.roland.com/assets/media/pdf/XS-42H_VP-42H_reference_eng01_W.pdf). More info about commands on page 25-26

Main usecase is making a simpler way to control it, since web interface is hard to use and doing scene changes by physical buttons on the device is confusing.  Most of other Roland hardware has proper utility kind of interface, but sadly this one does not. Only web based system for remote control.
It would be mainly used on live productions, event productions, screen visual productions.

If there is any chance you guys would take on this device, I would gladly be willing to help out beta testing with 2 of those devices.

**Comment by josephdadams** [comment]
I can write this.

**Comment by JeffreyDavidsz** [comment]
@josephdadams have fun!

**Comment by josephdadams** [comment]
@Kuufi there are two new modules now, one for the VP-42H and one for the XS-42H. Can you test either?

**Comment by Kuufi** [comment]
Yeah, there are 2 different modules on market. I own 2 Vp-42h modules, sadly no XS-42h. If you need, I can test stuff out on VP-42h.

**Comment by josephdadams** [comment]
Test what you can. Thanks!

**Comment by josephdadams** [comment]
@Kuufi did you test?

**Comment by Kuufi** [comment]
> @Kuufi did you test?

No sorry, haven't got the time yet (crazy weeks behind), hopefully, will get time this weekend. Can you point me out where I can find this module or in what build this is for testing?

**Comment by josephdadams** [comment]
@jeffreydavidsz can you push this module to a build for @kuufi?

**Comment by JeffreyDavidsz** [comment]
Build is cooking

**Comment by josephdadams** [comment]
@Kuufi can you download the latest build from builds.bitfocus.io? Let me know when you’ve tested. Thanks!

**Comment by josephdadams** [comment]
@Kuufi how did testing go?

**Comment by josephdadams** [comment]
Closing. This is included in the core now. If anyone has issues with using it, they can submit a bug request.
