### ISSUE TITLE
request for eventmaster module; freeze destinations

### ISSUE THREAD

**Issue by JeffreyDavidsz** [bitfocus/companion#543]
Besides sources, also freeze destinations

**Comment by willosof** [comment]
Will this be ready for 1.4.0? :D

**Comment by JeffreyDavidsz** [comment]
Depending when we go to 1.4.0 ;-) Code is ready needs some testing. I can do it on a live machine next week, maybe someone can test it sooner?

**Comment by MrLazerface** [comment]
I've tested this on a live box (S3-4K) running latest official firmware (6.2) and it works as intended.

**Comment by JeffreyDavidsz** [comment]
@MrLazerface thx for testing!
