### ISSUE TITLE
Module request: extron dxp matrix switcher

### ISSUE THREAD

**Issue by swikanth** [bitfocus/companion#545]
Add new equipment request for adding "extron dxp HDMI matrix switcher" would be nice.it has lot of preset options if brought in companion would be easy and a nice addition.
I has ip control so it is possible to do I guess.

**Comment by ATSvax** [comment]
I'd love to see extron matrix support too!

**Comment by sjtinsley83** [comment]
Extron kit on Companion would be very useful!

**Comment by JeffreyDavidsz** [comment]
Please provide some documentation

**Comment by swikanth** [comment]
https://www.extron.com/mobile/products/product.aspx?id=dxphd4kplus#downloads

**Comment by sjtinsley83** [comment]
https://www.extron.com/company/article.aspx?id=tech92

**Command to switch is IN*OUT!**
Example 2*4! which is Out4 gets In2

**Comment by swikanth** [comment]
So how do you turn commands into companion app?

**Comment by sjtinsley83** [comment]
That's what I was hoping someone may be able to help....
I guess the Blackmagic Videohub Matrix module could be tweaked with these commands?

**Comment by swikanth** [comment]
Idk...need someone make to make the module...basic commands would be enough

**Comment by ATSvax** [comment]
Not sure modding the bm videohub would help its probably completely different set of TCP commands though yes, similar goals. I'm no programming guru but I usually find the crestron programming manual to be the most helpful when hacking together my own macros since it shows the raw tcp strings required for control.

**Comment by ATSvax** [comment]
![dxpcommands](https://user-images.githubusercontent.com/47121735/56222862-987c9700-6021-11e9-8427-b74e60f492ba.PNG)
Actually it seems really simple on the command front. I'll dig around to try to find more commands though

**Comment by ATSvax** [comment]
pages 50-71 are the relevant ones
[dxp_dvi.pdf](https://github.com/bitfocus/companion/files/3085692/dxp_dvi.pdf)

**Comment by ATSvax** [comment]
![ipcommands](https://user-images.githubusercontent.com/47121735/56223824-594f4580-6023-11e9-9192-17b714d19e58.PNG)

**Comment by JeffreyDavidsz** [comment]
I'll trow in a module, hang on

**Comment by JeffreyDavidsz** [comment]
https://github.com/JeffreyDavidsz/companion-module-extron-dxp this is the base. Which command would you like to add? I'm assuming telnet port 23 to the matrix

**Comment by sjtinsley83** [comment]
Hi Jeff,

Yes it is port 23.

I think ideally it needs to work similarly to the Blackmagic Video Hub matrix module.
Basic use: INPUT > OUTPUT, TAKE!
Example 2*4! which is Out4 gets In2

If you want to take it a stage further you could get it to detect how many Inputs & Outputs, but initially, you could assume 16 x 16?

Then getting some feedback, but I guess getting basic working, for now, would be good.

**Comment by ATSvax** [comment]
![dxpcom2](https://user-images.githubusercontent.com/47121735/56236165-ce2f7900-603d-11e9-8471-88f9df00cbe5.PNG)
on further thought this is probably the most relevant page for our needs, basic matrix assignment and execution

**Comment by sjtinsley83** [comment]
@JeffreyDavidsz How do we know when this gets built into a bleeding edge release?

**Comment by haakonnessjoen** [comment]
@JeffreyDavidsz You should use a module that uses telnet as base. F.ex grandma2 or dcs.

**Comment by JeffreyDavidsz** [comment]
When you are on slack you'll see it passing by, in this case I'll update here. I'll add some command today and create a build

**Comment by JeffreyDavidsz** [comment]
Build is ready there was an error on a other module, but with the latest build you should have it in. Let me know if this works.

**Comment by EventReplay** [comment]
@JeffreyDavidsz almost. Route sends "undefined*undefined!" dosn't seem to be picking up the in and out selected.

also should
cmd = opt.input +'*'+ opt.output +'!';
really be
cmd = opt.input +'*'+ opt.output + opt.type;
to work correctly if you choose to only switch say audio

The login would need to be looked at for gui status updates as I don't think it sends any prompt if no password it set.

Hope thats helpfull

**Comment by JeffreyDavidsz** [comment]
@EventReplay tnx for testing. I've updated the actions to include id's. please test again, when new build is ready (should appear within 15min)

**Comment by EventReplay** [comment]
@JeffreyDavidsz  commands are now being sent correctly.
route to output type is working, but you haven't changed to all outputs (opt.type)

I don't have access to hardware at this time to confirm 100% working but looks good.

**Comment by JeffreyDavidsz** [comment]
Did that now, have fun!

**Comment by EventReplay** [comment]
For Information.
1. Ensure no password it set.
2. There will still be an issue with gui status as the Login format is for the dcs.
The Extron will never send "ShellApp waiting for input" for status OK.
(I would test "Extron Electronics DXP")
3. Extron telnet connection has a timeout default 5mins

Note: This module is using Extron SIS commands which is standard for most Extron hardware and could be used as a starting point for other hardware.

**Comment by EventReplay** [comment]
I've tested changes using Hercules and "Extron Electronics DXP" seems to work as expected.
I have create a fork of module and made changes to login which I think will log an error if a password is set, plus added recall preset and run bespoke command. These could be implimented once confirmation the module is working fine on hardware.

**Comment by JeffreyDavidsz** [comment]
Nice work! Just do a pull request when you've tested it

**Comment by EventReplay** [comment]
Confirmed current master working on hardware as I would expect, pull request made.

**Comment by EventReplay** [comment]
@JeffreyDavidsz a belated Thank-You!

I have made another pull request for DXP which adds saving a preset.

I have also created a module for the SMX Matrix based on this module as I have permanent access to hardware, code hear:
https://github.com/EventReplay/module-extron-smx
if worthy of inclusion.

**Comment by JeffreyDavidsz** [comment]
@EventReplay your pull request is in. extron-smx also

**Comment by ethan-tripp** [comment]
Is there any way to get a heartbeat function on the DXP to avoid the timeout every 5 min? There was a closed thread on the SMX module about this, but didn't know if it could be recreated in the DXP module.

**Comment by EventReplay** [comment]
@ethan-tripp I have done a pull request to add heartbeat for DXP but I've not pushed to have it actioned as I don't have access to hardware for test.

It is however working fine for SMX.

**Comment by ethan-tripp** [comment]
Nice. Would it be possible for me to help test it out for you on my unit?

**Comment by EventReplay** [comment]
@ethan-tripp the pull request has been actioned and should be included in the lastest bleeding edge build.
Can you please report back at your earliest convience that it is working all OK.

Many Thanks

**Comment by ethan-tripp** [comment]
Confirmed heartbeat function working! Will keep testing it out throughout the day. Thanks a lot for pushing this out so quickly.

**Comment by ethan-tripp** [comment]
@EventReplay Confirmed heartbeat function working! Will keep testing it out throughout the day. Thanks a lot for pushing this out so quickly.

**Comment by EventReplay** [comment]
@ethan-tripp Many Thanks for confirmation.
This issue is closed so please create a new issue if you encounter any other problems.
