### ISSUE TITLE
The internal commands for changing pages etc. for all the key presses are not showing.

### ISSUE THREAD

**Issue by BLACKOUTLIGHTING** [bitfocus/companion#549]
The internal commands for changing pages etc. for all the key presses are not showing.

**To Reproduce**
1. Go to Companion GUI
2. Click on Buttons
3. Click on A button
4. Click Add key down/on action
5. Voilas no Internal commands

![Schermafbeelding 2019-03-20 om 09 19 25](https://user-images.githubusercontent.com/48750579/54669299-524f1900-4af1-11e9-85b4-52faffda467d.png)

![Schermafbeelding 2019-03-20 om 09 20 29](https://user-images.githubusercontent.com/48750579/54669446-aa861b00-4af1-11e9-9b7b-c4f821fb78e8.png)

![Schermafbeelding 2019-03-20 om 09 22 47](https://user-images.githubusercontent.com/48750579/54669474-c093db80-4af1-11e9-9ca6-c356d2208a6d.png)

**Comment by josephdadams** [comment]
@BLACKOUTLIGHTING are you still having this issue or can we close this?

**Comment by BLACKOUTLIGHTING** [comment]
You can close this. Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: Joseph Adams <notifications@github.com> Datum: 22-08-19  20:56  (GMT+01:00) Aan: bitfocus/companion <companion@noreply.github.com> Cc: BLACKOUTLIGHTING <Houben.wesley@gmail.com>, Mention <mention@noreply.github.com> Onderwerp: Re: [bitfocus/companion] The internal commands for changing pages etc. for all the key presses are not showing. (#549) @BLACKOUTLIGHTING are you still having this issue or can we close this?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bitfocus/companion/issues/549?email_source=notifications\u0026email_token=ALT5743A3FFGGKKAKNENQMTQF3OO3A5CNFSM4G725CV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD46BWPA#issuecomment-524032828",
"url": "https://github.com/bitfocus/companion/issues/549?email_source=notifications\u0026email_token=ALT5743A3FFGGKKAKNENQMTQF3OO3A5CNFSM4G725CV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD46BWPA#issuecomment-524032828",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
