### ISSUE TITLE
Avolites to control Companion

### ISSUE THREAD

**Issue by mbs4298** [bitfocus/companion#552]
**Describe the feature**
A clear and concise description of what the feature does

I would like to be able to program Companion commands into cues on an Avolites console over ArtNet. That way I would basically have a mini media server where I can switch graphics, play music and videos through the lighting cues.

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by josephdadams** [comment]
Closing this because you can control Companion with Artnet. @mbs4298 re-open if that doesn't meet your needs.
