### ISSUE TITLE
add date & timestamp to Configuration export filenames.

### ISSUE THREAD

**Issue by alatteri** [bitfocus/companion#553]
**Describe the feature**
A clear and concise description of what the feature does
currently exporting a configuration results in a static filename.  I like to backup my configs on a regular basis.  Would be very nice to have the date & timestamp in the filename so I can keep incremental backups of the configs.
**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**

**Usecases**
Keeping incremental backups of configs.

**Comment by willosof** [comment]
Nice one!

**Comment by alatteri** [comment]
adding hostname in there would be great too.

**Comment by krocheck** [comment]
This has been added
