### ISSUE TITLE
Please support some tools....

### ISSUE THREAD

**Issue by houtacheng** [bitfocus/companion#556]
1.Remote BTT
https://www.folivora.ai/

https://docs.bettertouchtool.net/docs/webserver.html

2.WAVES
https://www.waves.com/

3.HASS
https://www.home-assistant.io/

**Comment by JeffreyDavidsz** [comment]
@houtacheng it would be helpful to specify which commands need to be added per tool. Just displaying a website will take developers a lot of time to search for it

**Comment by willosof** [comment]
One specific software/hardware per ticket, and please provide more information than a website. And, give it a proper title, please :)
