### ISSUE TITLE
Support alpha in Colorpicker for modules

### ISSUE THREAD

**Issue by florisporro** [bitfocus/companion#558]
The colorpicker action option type is great for quickly selecting a color, but its behavior is a little unpredictable.

**Issue 1: output format of color values**

It's unclear to me what output format this is. If I pass 'rgb(255,255,0)' in the input field, '16776960' is provided to the action.

#FF8000 is returned as '16744448'.

Ideally, output format would be an international standard format such as RGBA.

**Issue 2: input field has gray background**

This is a UI problem, but grayed out input fields are interpreted by users as read-only or disabled. The input field is actually editable and the UI should reflect this.

**Issue 3: there is no alpha slider**

This would be simple to add, as Spectrum already supports the feature:
[http://bgrins.github.io/spectrum/#options-showAlpha](http://bgrins.github.io/spectrum/#options-showAlpha)

![Screenshot 2019-03-25 at 11 03 39](https://user-images.githubusercontent.com/5805436/54910952-abea8580-4eed-11e9-81c6-6b1e90c23694.png)

**Comment by haakonnessjoen** [comment]
The output format is 24 bit RGB. So basically same as html. You can convert it to hex with something like: ("00000" + number.toString('hex')).substr(-6);

**Comment by haakonnessjoen** [comment]
In regards to visual style, grayness etc. Is this something you could have looked at for us? :)

**Comment by florisporro** [comment]
The 24-bit RGB format is not something I've encountered before, I can also not find any online tools to convert to-and-from this color format. Can you point me in the direction of some docs or examples where this color format is used in HTML?

This color format will also preclude the option for an alpha channel since we're short 8 bits to add it in.

If you're open to changing the output format I can do a PR to switch to RGBA and fix the UI issues.

**Comment by haakonnessjoen** [comment]
I did tell you how to convert to html format. Just add an '#' in front of the result of the command I gave you. To convert it the other way, simply remove the # and parseInt('aabbcc', 16); The color picker is mainly used for controlling colors of buttons in companion (image data), hence html colors is not used.

Supporting alpha channels in the color picker would have to be encoded as ARGB for sending to companion, until companion supports that. (which would need a bit of new code).

**Comment by florisporro** [comment]
Gotcha, I think given this information the UI styling is currently accurate, since the input field will accept color formats that are not supported, like RGBA or HSLA.

If I find the time I might look into changing this, but sounds like it's more involved than I first thought. For the purpose of the module I'm working on passing-through CSS color values as strings is probably the better option.

**Comment by Julusian** [comment]
This has been implemented and will most likely be in 3.1, or a release soon after
