### ISSUE TITLE
Lamp Off confirmation/double-click

### ISSUE THREAD

**Issue by calwalker1** [bitfocus/companion#564]
Hey guys. Love this product, just started using it for controlling projection in theatre shows.

**Describe the feature**
Currently I am reluctant to add any 'show stopping' button functionality in companion (such as lamp-off projector) as there's no way for Companion to confirm that you want this to proceed. It would be good if you could tick a box on the button configuration which says "Requires confirmation". When this is ticked, pressing the button does nothing unless you hold it for an amount of time such as... 5 seconds).

**Is this platform dependent (windows, mac, ..)?**
Not platform dependant

**If documentation is required to implement, do you know where to find it?**
N/A. Change to Companion functionality, not how it interacts with other tools

**Usecases**
A system technician is scrolling through companion pages and accidentally presses one of the lamp off buttons, the projectors turn off immediately. These can take anywhere up to 5 minutes to be available again due to cooling time and lamp-on time, confirmation may have prevented this.

A system technician is powering down their system at the end of the night. They press the lamp off button briefly, nothing happens. They hold the button for 5 seconds, the projectors lamp off.

**Comment by JeffreyDavidsz** [comment]
This can be done by adding a 3 seconds delay on the button down. On the button up you can do a abort all delayed actions.
