### ISSUE TITLE
TCP Connection Error

### ISSUE THREAD

**Issue by daniel3p4u** [bitfocus/companion#566]
Hi, first of all, thank you for developing that great piece of software! Each new release offers new possibilities :)
Today I've tried the "companion-Arduino" sketch on my Arduino Uno with Ethernet Shield (W5100). The OSC Sketch works great for me but unfortunately, the TCP remote doesn't. I've checked the network traffic from my arduino to companion. The Arduino sends the commands but companion doesn't react. The only thing is the "TCP Server: Client connected: ::ffff:192.168.20.80:49153" message in the log. Also, I get the attached error message. 
[Companion_error.zip](https://github.com/bitfocus/companion-arduino/files/2845687/Companion_error.zip)
![companion_error](https://user-images.githubusercontent.com/20013009/52487862-dcd15e00-2bbe-11e9-8ca9-e02a248dcbfd.PNG)
I'm running Companion v1.3.0 and companion-Arduino 1.2.0
Do you have any advice to fix the problem?
Using the OSC feature is not possible since I want to use another ethernet chip (W5500) in the future.

**Comment by rwebber** [comment]
I am also getting this error sending TCP messages from Isadora.
a quick search online seems to indicate that an 'error' listener needs to be added. (i'm not a node dev otherwise I would jump in)
