### ISSUE TITLE
X32 DCA mute and fader do not react

### ISSUE THREAD

**Issue by CactusMcCoy** [bitfocus/companion#568]
On my X32, DCAs fader and mutes do not react to "mute", "unmute" or "set fader level".

**To Reproduce**
1. Add "Set fader level", "mute" or "unmute"
2. Set "Type" to "DCA 1-8", enter a DCA # from 1 to 8 
3. Add value for "Set fader level" or choose "mute" or "unmute"
4. Press "Test actions" or physical button on StreamDeck
5. No reaction

**Expected behavior**
Fader is supposed to move to given value, mute buttons are supposed to change to specified state.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Opera
 - Version Companion v1.3.0 (1a7592b-1203)

**Additional context**
basic setup seems correct, as all other commands from Companion are accepted and executed by the console with the exception of the known "load snippet"-issue.
 
edit: removen unrelated text.

**Comment by PerRoine** [comment]
This was fixed in a developer build 6 days ago
https://builds.bitfocus.io/companion/

**Comment by CactusMcCoy** [comment]
Ah thank you. New to GitHub and still finding my way around here.
