### ISSUE TITLE
Enhancement: Pin Code unlocks all surfaces option

### ISSUE THREAD

**Issue by MrLazerface** [bitfocus/companion#569]
**Describe the feature**
Add a toggle option to the settings page that would allow pin code unlocking to apply to all connected stream decks, or if not toggled on would allow individual stream deck locks (as it currently functions).

**Usecases**
For companion users using multiple stream decks, having a single lock button and using a single stream deck to unlock all connected stream decks would make them operate more like a traditional lighting/audio console lock function.

**Comment by mfoulks3200** [comment]
Feature added in pull #572 , [Pull #4](https://github.com/bitfocus/companion-module-bitfocus-companion/pull/4) in the internal module to add related actions.
