### ISSUE TITLE
Enhancement: Grouping of Surfaces for internal actions

### ISSUE THREAD

**Issue by MrLazerface** [bitfocus/companion#570]
**Describe the feature**
The ability to assign both physical surfaces (stream decks) and virtual surfaces (web interface, emulator) to groups so that internal actions apply to all surfaces within a group.

**Usecases**
Have 2+ stream decks for one operator that would lock simultaneously and unlock as a group, while also having one stream deck that can lockout via timeout (for client use/etc.). 
Having the ability to lockout the tablet/web buttons would also be handy (to prevent unauthorized use on the network).
Another option would be to allow multiple surfaces in a group to change pages together using the stock page select buttons on any deck in the group.

A further enhancement would allow you to designate one 'Master' deck in a group that would have page buttons, and 'Slave' decks without page buttons that would respond to the master's page button presses.

**Comment by mfoulks3200** [comment]
This feature would require a fair bit of reworking, does anyone else have any comments/suggestions?

**Comment by Julusian** [comment]
This is now possible in the 3.2 betas
