### ISSUE TITLE
Adobe Premiere Hotkeys (Software) Request

### ISSUE THREAD

**Issue by cpw10101** [bitfocus/companion#576]
This would add a list of commonly used keyboard shortcuts for adobe premiere, (I'm currently using CS6) to help expediate editing and having direct access to things like razor at edit line, unlink clip and ripple delete would be very useful.

I don't think this would be platform dependent as premiere was originally a mac program, but I don't know for sure.

Thank You
Chris

**Comment by JeffreyDavidsz** [comment]
@cpw10101 please provide a list with the keys you would like to see. I can build it in the VICREO-Hotkey module (you can already create the keys for yourself of course with the module)

**Comment by JeffreyDavidsz** [comment]
Do you have a list?

**Comment by cpw10101** [comment]
Hi, Thanks so much for your response,
 
I jumped the gun a little on my request I think, after working more with the
stream desk surface I discovered that I can set the system up to do almost
everything that I wanted it to.
If I discover enough things that require higher level macros to accomplish
then I might generate a list, but currently I can't think of enough things
to justify your continued attention.
 
Once again Thanks Very Much,
Chris Walker

  _____

**Comment by JeffreyDavidsz** [comment]
No problem, closing this
