### ISSUE TITLE
Two Button Press to Action

### ISSUE THREAD

**Issue by hadphild** [bitfocus/companion#578]
Having to press the Page button and other button to action. This would allow a fail safe if its action to do test patterns or turn projectors off.

**Comment by JeffreyDavidsz** [comment]
There is a solution for this: make an action with 3sec delay on the down, on the up abort all delayed actions. This way you need to press the button for at least 3 seconds before the actions happens. When you release before 3sec the action will not run. Page buttons can be set to not display somewhere in the future

**Comment by JeffreyDavidsz** [comment]
Will this work for you? Then I can close this issue

**Comment by josephdadams** [comment]
Closing.
