### ISSUE TITLE
shortcut for wysiwyg cast software

### ISSUE THREAD

**Issue by lamlight** [bitfocus/companion#581]
**Describe the feature**
Cast wysiwyg is a lighting design software
https://cast-soft.com/wysiwyg-lighting-design/

**Is this platform dependent (windows, mac, ..)?**
windows

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along
![tool wysiwyg](https://user-images.githubusercontent.com/49071380/55242415-7d4a1300-523d-11e9-81aa-94680f1cb8e0.PNG)
and shortcut hotkey
**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

when you draw the plans, you must constantly click on the buttons (for example in the attached photo) and it is very repetitive.
It would be very useful for us to be able to use a shortcut in toogle
For example, locking the X Y Z axis is something I do thousands of times when I draw.
Each time click on X to lock the X and reclick on X to unlock it.
![wysiwyg ortho](https://user-images.githubusercontent.com/49071380/55243389-6b696f80-523f-11e9-9bb7-8acb342aeb41.PNG)

Thank you!

Xavier

**Comment by willosof** [comment]
Not network controllable. You can do this from the original streamdeck software.
