### ISSUE TITLE
Bug: hitting buttons on one page also hits button on previous page

### ISSUE THREAD

**Issue by JatheJester** [bitfocus/companion#587]
So I have actions mapped to pages 1 and 2 and when I push a button on page 2 it performs the action mapped to that and the action mapped to the button in the same position on the previous page. 

I have found a interim fix, I just use the odd numbered pages because the bug only seems to only trigger the previous pages button and having that blank page acts as a buffer. 

In spite of this, I would like to see if anyone has had this issue or possibly know how to fix it.

**Comment by willosof** [comment]
Say whaaaat? In latest builds also?

**Comment by haakonnessjoen** [comment]
You are probably running windows with both companion and stream deck application running at the same time. There is currently an issue where both applications get access to the usb device at once.

Please try to start companion before you connect the stream deck, to see if this is in fact your issue.

**Comment by JatheJester** [comment]
I disconnected and reconnected the stream deck and have not had the issue again over multiple tries to re-create the original instance.  So i guess its not a true bug, just a quirk lol

**Comment by JatheJester** [comment]
And to answer the earlier question: 1.3.0(1a7592b-1203), Windows 10 pro, was using the Hog profile. The button on page 1 was a master go and the button on page 2 was a clear command

**Comment by josephdadams** [comment]
Closing. If you're still experiencing this, re-open and add details. Thanks!
