### ISSUE TITLE
Request: Support for removing page buttons

### ISSUE THREAD

**Issue by johnmortensen** [bitfocus/companion#592]
**Describe the feature**
A clear and concise description of what the feature does

**Is this platform dependent (windows, mac, ..)?**
Explain

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by johnmortensen** [comment]
Would love to be able to remove the Page Up/Down Page number buttons.  As an ATEM user those extra assignable buttons are all need!  I know you are working on it!  Thanks for a terrific product.  Will be donating!

**Comment by josephdadams** [comment]
Closing as this is part of the nopagebuttons branch and is the most requested thing. When 2.0 comes out, this will be fixed.
