### ISSUE TITLE
Module request: Opticis  OMM-1000

### ISSUE THREAD

**Issue by selli106** [bitfocus/companion#593]
Control over matrix in and out control

The OMM-1000 modular matrix could be operated with various interfaces such as key button inputs,
command input through RS-232 and TCP/IP, Web control through TCP/IP and PC program through
RS-232 and UDP. All functions are executed on a basis of a serial command input, but the graphic
interfaces on the Web or the PC program make more efficient way to operate the OMM-1000 modular
matrix.

having the stream deck able to control a omm1000 would let me  set vision routing for different room configurations  easily and integrating this with control of the sound desk i could turn my ballroom from one to three rooms with one button

**Comment by JeffreyDavidsz** [comment]
Please provide protocol information, which commands you would like to see and working examples if possible

**Comment by selli106** [comment]
[User_manual_OMM-1000_V1.5_150507.pdf](https://github.com/bitfocus/companion/files/3051070/User_manual_OMM-1000_V1.5_150507.pdf)
 Sorry  I am quite new to this i have attached the user manual for reference but i belive the information for that is in chapter 6 
--The OMM-1000 modular matrix could be operated with various interfaces such as key button inputs,
command input through RS-232 and TCP/IP, Web control through TCP/IP and PC program through
RS-232 and UDP. All functions are executed on a basis of a serial command input, but the graphic
interfaces on the Web or the PC program make more efficient way to operate the OMM-1000 modular
matrix.
Command input operation is accomplished through RS-232 or TCP/IP. 

as for commands pretty all that would be useful would be link commands and maybe input and output status which the manual says is possible could work as a variable similar to the countdown timer example
thanks for your quick reply to sorry if im not very helpful

**Comment by selli106** [comment]
Found a different manual and it says in this one Command input(such as hyper terminal by RS-232 and Telnet by ICP/IP 
The command inputs are composed of a string of ASCII codes and its basic structure it 
Command  + Delimiter ('=') + Data + Delimiter ('^' or ',' or '_') +Data + End ('!')

**Comment by JeffreyDavidsz** [comment]
Initial module is ready, I'll put it in the core when repo is set up

**Comment by JeffreyDavidsz** [comment]
Its in build Build #935

**Comment by JeffreyDavidsz** [comment]
@selli106 did you test?

**Comment by selli106** [comment]
Not yet sorry won't get chance till next week most likely will let you know
how it goes

**Comment by selli106** [comment]
I've tested the module and everything seems to work great except it never
changed the status even when it was working it said initialising or install
I will try set it up again to be more specific
Great work !

**Comment by selli106** [comment]
It's stopped working status is going from connecting to initialising to
error and back to connecting and is now not controlling the device I can
still control the device on its web interface though i will keep
troubleshooting to see if it works again

**Comment by selli106** [comment]
I've rebooted everything and now it works again but is stuck on
initializing again sorry for the spam

**Comment by JeffreyDavidsz** [comment]
No problem, would it be possible to telnet the device? So I can see what the response is when connected?

**Comment by selli106** [comment]
How would I do that

**Comment by JeffreyDavidsz** [comment]
if you have telnet installed on windows `o 192.168.xxx.xxx` filling the correct IP of course. Then you would hopefully see something like ==Welcome.
Just make a screenshot and put it here

**Comment by JeffreyDavidsz** [comment]
Meanwhile, I'll strip the login section
