### ISSUE TITLE
"Set surface to page" action triggers "up action" on wrong button

### ISSUE THREAD

**Issue by SteveTherrien** [bitfocus/companion#595]
**Describe the bug**
I don't know if this is related to #587, but `internal: Set surface to page` triggers "key up" on the destination page's button.

**To Reproduce**
- Create a button (1.1) with the down action of `internal: Set surface to page` of the current device to go to page 2.
- Press button 1.1
- The log will show that button 1.1 is pressed, but 2.1 is released
```
07. 18:49:57 device(...): Button 2.1 released
07. 18:49:57 device(...): Button 1.1 pressed
```

This will trigger the key up action of button 2.1 **and** also the key up action of button 1.1 even though 1.1's up action isn't logged.

**Expected behavior**
Only the key up action of button pressed (1.1) will be triggered.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4
 - Browser: Chrome
 - Version 73

**Additional context**
Problems happens both with a Stream Deck attached and just with the emulator, but not in the tablet view.

See attached config: [bug.companionconfig.txt](https://github.com/bitfocus/companion/files/3052400/bug.companionconfig.txt)

- Button 1.1
  - Down action: `Set surface to page 2`
  - Up action: Set button 2.2 BG color to red
- Button 2.1
  - Up action: Set button 2.3 BG color to blue

Pressing 1.1 sets 2.2 to red and 2.3 to blue.

**Comment by officialmattsnyder** [comment]
I'm also experiencing this. Although, I'm not experiencing the "key up" action on the original button that Steve is.
 So...
If button 1.1's down action is "Set surface to page 2"
Pressing that button results in: 

button 1.1 pressed
button 2.1 released

and button 1.1 shows as being "latched" and cannot be unlatched.

Basically, the "set surface to page" renders that button un-releasable.

**Comment by SteveTherrien** [comment]
That does sound related @officialmattsnyder.

It turns out this problem was foreseen when the `set_page` action was [first developed](https://github.com/bitfocus/companion-module-bitfocus-companion/blob/d291bdd50817a5b03ffd97186122ea29d619a139/index.js#L443):
```
 // TODO: Somehow handle the futile "action_release" of the same button on the new page 
```

`set_page` knows the default key-up event will be run against the button on the wrong page, so it creates a second key-up event against the original button. Both key-up events then run.

The cleanest way I've been able to work around this is to make the "set_page" action issue a new event which tells the surface to disregard the next specific key press (bank/key/surface/direction combination).

The log will still show "Button 1.1 pressed / Button 2.1 released" because those entries are inserted by the code monitoring the surface, but the wrong key-up event is now ignored and that button's actions won't fire.

It requires changes to two files:
- [lib/module/bitfocus-companion/index.js](https://github.com/SteveTherrien/companion-module-bitfocus-companion/commit/9eef31ea08f6f6e6ac65a4832396df874bbe552c#diff-168726dbe96b3ce427e7fedce31bb0bc)
- [lib/action.js](https://github.com/SteveTherrien/companion/commit/15622fdb70bbdcfaa0d653c1741c78857b14eaa8#diff-302698e425c4ce1f39a1180e6a80e686)

It feels like a messy solution (which is why this isn't in a pull request), and a proper fix would probably require a refactor of how `lib/device.js` handles pages.

**Comment by haakonnessjoen** [comment]
Yes, it's a know issue. And at some point, some other code has made it so that the visually "latched" fix no longer works. So you see that they are latched now.

One easy fix, could be to add an array/object to the device handler code, for it to monitor what buttons that are currently held down, and which bank they currently belonged to at the time of pressing down. So that when there is a release action on that button, it uses the stored bank info, instead of checking the current bank on that button.

**Comment by fibertoad** [comment]
A simple fix for this is to set the 'internal: Set surface to page' to the Key up action instead of the key down action.

**Comment by timt-111** [comment]
Just a thought -- and I have no clue where this stuff lives in the code, but would it not be a simple solution to check the button state before executing a 'release' action?
if our button is currently in a 'pressed' state:
    do the release function
else:
    nothing to see here, move along

**Comment by josephdadams** [comment]
Is this related to #769 ?

**Comment by officialmattsnyder** [comment]
> Is this related to #769 ?

Yep. I vaguely remembered this thread existing when I made #769, but couldn't find it so I dropped the new one. Feel free to close #769 - although the Java error might be helpful to have in this thread since it hasn't been mentioned.

**Comment by josephdadams** [comment]
@istnv can we close this?

**Comment by istnv** [comment]
Yes.
