### ISSUE TITLE
Module request: Barco DP4K

### ISSUE THREAD

**Issue by JeffreyDavidsz** [bitfocus/companion#598]
Module for DP2K and DP4K

**Comment by alatteri** [comment]
I'm at NAB, let me know if you want me to talk to Barco.

**Comment by JeffreyDavidsz** [comment]
Waiting for Barco at the moment

**Comment by alatteri** [comment]
I'm guessing Barco never came thru?

**Comment by JeffreyDavidsz** [comment]
Nope not yet, but I'm not giving up

**Comment by JeffreyDavidsz** [comment]
[Communication-Protocol_TDE4313_01_ReferenceGuide.pdf](https://github.com/bitfocus/companion/files/3106753/Communication-Protocol_TDE4313_01_ReferenceGuide.pdf)

**Comment by JeffreyDavidsz** [comment]
Coming there... :-)

**Comment by alatteri** [comment]
@JeffreyDavidsz   Amazing.

**Comment by JeffreyDavidsz** [comment]
@alatteri the module is in now, please test and file an issue again when something is needed

**Comment by JeffreyDavidsz** [comment]
@alatteri forgot to mention, when these commands doesn't work try the new one in the hdx module. The shutter for example is the same. But in the modules the way we send them is different and I need to know which one is the correct one

**Comment by alatteri** [comment]
OK..I'll try to test today, if not tomorrow.

**Comment by JeffreyDavidsz** [comment]
@alatteri yesterday I've pushed an update in the barco-dp module. the shutter command is send to way's I expect 1 to work (you might need to use a remote to shutter or unshutter first)

**Comment by alatteri** [comment]
This was solved with the barco-dp module.  Issue can be closed.
