### ISSUE TITLE
Blackmagic ATEM: Custom OSC Commands

### ISSUE THREAD

**Issue by Paradox32** [bitfocus/companion#604]
**Describe the feature**
Would like to be able to type in my own ATEM OSC commands( addresses) so that I can further customize operation to the ATEM. So the dropdown action would be "Send Custom Command" with just an empty text box to enter the OSC command (example: /atem/mplayer/2/clip/1) and then the same ability for feedback.

**Is this platform dependent (windows, mac, ..)?**
NO, this would work on all platforms.

**Usecases**
I'm currently using MIDI controllers connected to Mac using OSCulator software to communicate to ATEM and able to send any recognized OSC command, but I do not see a way to do this with Companion/Stream Deck.
 -For instance: If I could simply send the following commands:

-Set Media Player $i source to Clip $x /atem/mplayer/$i/clip/$x
Where $i can be 1 or 2, and $x can be 1 or 2 depending on the capability of your ATEM switcher. e.g. /atem/mplayer/2/clip/1
-Set Media Player $i source to Still $x /atem/mplayer/$i/still/$x
Where $i can be 1 or 2, and $x can be 1-20 depending on the capability of your ATEM switcher. e.g. /atem/mplayer/1/still/5

Many other commands that are available on other software platforms to communicate to ATEM.

**Comment by JeffreyDavidsz** [comment]
Could you use the generic OSC module for that?

**Comment by Paradox32** [comment]
I'm new to all this stuff.. where is the generic OSCemote module located, I can test it out.

**Comment by JeffreyDavidsz** [comment]
Just search for osc on the instance tab. I'll close this for now

**Comment by Paradox32** [comment]
I found the OSC generic module and played around.  

One small issue I saw is that it asks for a port number, but when adding a knob device (Blackmagic ATEM) the port is input automatically but not shown to the user. 

The other issue is the feedback actions seems limited.

**Comment by Paradox32** [comment]
I also noticed no toggle option

**Comment by Paradox32** [comment]
I couldn’t find where to ask this so I’ll do it in here: 

Is anyone still actively working on adding functionality for the Blackmagic ATEM module? If so where, and how can I contribute? There are quite a few commands not available that have known OSC commands.

**Comment by krocheck** [comment]
@Paradox32 the code for ATEM is here: https://github.com/bitfocus/companion-module-atem/issues

You can submit pull requests or tickets for features there.  Sometimes features needed are not implemented in the upstream atem-connection library and we have to add functionality there first.
