### ISSUE TITLE
Remove Top Button Number Label

### ISSUE THREAD

**Issue by Paradox32** [bitfocus/companion#605]
**Describe the feature**
Allow for removing of the button labels at the top (1.1, 1.2, 1.3...) and utilize the full space fo the button display. If this were done then it would be nice to be able to also use the fullsized square aspect icons that Stream Deck is capable of using natively.

**Is this platform dependent (windows, mac, ..)?**
NO, this would work on all platforms.

**Usecases**
The button screens would be fully utalized instead of there bing a top label/status area. I'm controlling a Blackmagic ATEM and using feedback for all buttons, so the top area in unnecessary and makes the icons out of square aspect.

**Comment by willosof** [comment]
This space is very important for letting the user know if the button and their linked instances works like expected and if they are currently running / have delayed actions. We have a play symbol and warning symbols appearing there (and more planned in the future)

**Comment by Paradox32** [comment]
Thank you for responding, and thank you for such an amazing application.

I think it's a great option to have this area and have thought up some great uses... but I think for many people's purposes you can simply have the background color and text colors change to indicate the same information, making the added area unnecessary .. For instance my entire key changes from black/green/red to denote off/preview/program.

**Comment by alisomay** [comment]
I would like to add information here if somebody needs the functionality of companion badly and really need to remove the top bar.  
I wouldn't recommend it because you will be modifying the source and it will be overwritten with updates but there might be use cases for it.  
I needed it what I did is :
I have pulled the repo, 
Find the files,
lib/graphics.js and lib/image.js
If you check these files for ~10 mins you will find the places which draws the top-bar and clips the PNG image. 
Comment them out and rebuild the app. 
Works fine.

**Comment by leighhunt** [comment]
Hi Alisomay.
Could I ask how you went about rebuilding the app? I am on Mac and have only previously built apps using Xcode.
Many thanks in advance.

**Comment by robynjayqueerie** [comment]
If I can add my bit here.
The Elgato keys (in my opinion) do end up looking clearer and basically better because they do not have the top bar.  Also their icon generator program is so much faster than having to create a specific size for the Companion icon. I have not found a real use for the Companion top bar yet even though the Companion is easier to use and more advanced.
Is there a possibility that Bitfocus could create an option in the preferences which removes it for those of use who don't want it? I would be happy to drop $100 in the hat as my contribution towards that, anyone else out there who feels so inclined? That way updates won't overwrite any compile I or others might make to remove the bar. Just offering.
Thanks for a great product.

**Comment by JoshWobbles** [comment]
I can see why some actions need the top bar, but make it a option to disable it on buttons that we don't need it for. There is absolutely NO reasonable argument for why they need to be forced on on every single button...

**Comment by davidnero** [comment]
I'd like to add my vote for the option to turn the top bar off. I think it's a great help for setup and debugging, but in production I (personally) find it to be a negative since it limits space on the buttons for text and/or icons.

**Comment by b1ink0818** [comment]
Agreed. The option to toggle the bar would be great.

**Comment by JeffreyDavidsz** [comment]
I'm ok with looking into the toggle option. This is not just 10min work as the whole drawing of the button needs to be checked in different states (and I need to figure stuff out of course). @robynjayqueerie if you are still willing to put a bounty on it, it would be very nice.
I'll create something for that on bounty source or so.

**Comment by robynjayqueerie** [comment]
@JeffreyDavidsz certainly am, being Australian I was thinking $AUS but am willing to raise that to $US if we can't find any other donors. Thanks.

**Comment by JeffreyDavidsz** [comment]
Great, I'll look I to it. Here the link to post the bounty, maybe others can join in:
https://www.bountysource.com/issues/72800299-remove-top-button-number-label

**Comment by robynjayqueerie** [comment]
Right, I have put my US$100 in the hat

**Comment by JeffreyDavidsz** [comment]
Thank you, maybe some others would like to chip in. I'll start on it

**Comment by JeffreyDavidsz** [comment]
All right, lets try it out? It's in the latest build

**Comment by robynjayqueerie** [comment]
by the latest build you mean the Bleeding edge builds?

**Comment by JeffreyDavidsz** [comment]
Yep

**Comment by robynjayqueerie** [comment]
I am downloading companion-2.1.2-f4bcaf3-win64? Ran it and did not find a way of getting rid of the top line, not in preferences or on the button page itself. How do we do it?

**Comment by JeffreyDavidsz** [comment]
Look for it in Settings > remove topbar

**Comment by robynjayqueerie** [comment]
Not there, I will reinstall it again

**Comment by JeffreyDavidsz** [comment]
Thats not a nightly build, click on the link BETA

**Comment by robynjayqueerie** [comment]
Where do I find that Beta link, can't see it anywhere

**Comment by JeffreyDavidsz** [comment]
[https://bitfocus.io/companion/download/builds/](https://bitfocus.io/companion/download/builds/)

**Comment by robynjayqueerie** [comment]
Ah sweet music

**Comment by robynjayqueerie** [comment]
That seems to work well, only have the emulator here, will try with the real thing tomorrow. Only comment is that above the Browse button it still says 72x58 PNG but it loads a 72x72 fine and it looks good

**Comment by robynjayqueerie** [comment]
Having that extra space makes the buttons so much more visual, a great job

**Comment by robynjayqueerie** [comment]
When you press the button the top label appears briefly while the button is held down, at least on the emulator.

**Comment by robynjayqueerie** [comment]
@JeffreyDavidsz I have tried the build with a real StreamDeck and it is OK. I will keep a look out for any issues and report them here. Thanks again

**Comment by JeffreyDavidsz** [comment]
Yes so some choices I made. The yellow bar is a reverence that you have presses. I like to see that it actually works. The PNG for upload had a limit of 58 changed that to 72, for obvious reasons. Wasn't sure about changing the text because for the old way you don't want it clipping. Thank you for the support, I'll close this now.

**Comment by robynjayqueerie** [comment]
Is this patch going to find its way into the mainstream download at some point or are we stuck with just the version you have created here?
Thanks

**Comment by Julusian** [comment]
@robynjayqueerie it will remain in just the beta builds until 2.2 is released, which there is no concrete timeframe on currently

**Comment by JoshWobbles** [comment]
> Yes so some choices I made. The yellow bar is a reverence that you have presses. I like to see that it actually works. The PNG for upload had a limit of 58 changed that to 72, for obvious reasons. Wasn't sure about changing the text because for the old way you don't want it clipping. Thank you for the support, I'll close this now.

If you are going to hard code a visual cue of a press how about something a little less asymmetrical and that wont overlay a significant portion of 72x72 image buttons.  Possible alternatives would be a 2px border around the entire button, or the button graphic shrinking 4px or so to visualize a "press" type of effect.

**Comment by istnv** [comment]
I haven't had the chance to try this update. Does the Red/Yellow square still show in the corner for instance issues? Otherwise, the 2px border idea would work for that.

**Comment by Julusian** [comment]
@JeffreyDavidsz the yellow bar is being drawn underneath text and pngs. I would expect it to be drawn on top

**Comment by JeffreyDavidsz** [comment]
New request #1479
