### ISSUE TITLE
Icon Size to 288x288 or 72x72

### ISSUE THREAD

**Issue by Paradox32** [bitfocus/companion#606]
**Describe the feature**
Allow using of full-sized square aspect icons at 288x288 (Elgato's icon creator size) or 72x72. This would mean removing the top key number/status area also.

**Is this platform dependent (windows, mac, ..)?**
This is specific to the Stream Deck and not platform specific.

**Usecases**
I am currently using the Elgato Stream Deck online icon creator to make icons that are downloaded at 288x288, then I must crop and downsize them manually to 72x58 to meet Companion's requirements. I'd rather be able to keep the full resolution that the Stream Deck is capable of, and keep the square aspect and removing the top key number/status currently shown at the top of each button.

**Comment by willosof** [comment]
Duplicates #605
