### ISSUE TITLE
Blackmagic ATEM Port?

### ISSUE THREAD

**Issue by Paradox32** [bitfocus/companion#609]
I'm trying to use the Generic OSC module to connect to a Blackmagic ATEM 1 M/E. I'm able to use the preset module to communicate but need the generic module to use some commands that aren't available.. What port do I need to use in the generic osc module to communicate? (it's built into the atem module but doesn't show the port number).

**Comment by krocheck** [comment]
ATEMs don't use OSC, so I'm a little confused by this line of questioning.

**Comment by Paradox32** [comment]
What protocol do you have them set to use? I’ve been using several other pieces of software that all say they are sending/receiving OSC “messages” to the ATEM.

For example I’m using atemOSC and OSCulator together to nap midi controllers to the ATEM. In my setup I’m using OSCulator to map the midi key/note to an OSC message (ex: /atem/preview/1) which sends that command to atemOSC which is communicating with the ATEM.

**Comment by krocheck** [comment]
atemOSC is an OSC bridge.  It converts native ATEM protocol to friendlier OSC.  Unless you use our Generic OSC module to talk to your atemOSC insurance, there's no way to send OSC commands direct to an ATEM.  What commands do you need that there ATEM module doesn't support? I can get them in the queue.

**Comment by Paradox32** [comment]
I swear I've learned more in the just past couple of days on this forum than I have in 3 weeks of actual use of the ATEM with other applications and forums.. so THANK YOU!

I suppose I can continue to use atemOSC as a bridge and have the Companion Generic OSC Module talk to it, I tried this earlier today but couldn't get it to communicate. I was a little unsure of what syntax to use though, the default string in the box is '/osc/' so i tried: '/osc/atem/preview/1' and also '/atem/preview1' with no luck, but maybe I have a port setting or something else set wrong? Also, the feedback system on the generic module is probably way over my head to get working for the operation I'm wanting, so hopefully many more commands can be implemented in the ATEM module.

I am basically wanting to create my own fully custom broadcast control panel using multiple stream decks.. so honestly I could see myself using almost all of the available ATEM commands, I currently use the following with my midi controller that I'd like to port over to the Stream Deck:



Toggle Upstream Keyer 1 /atem/usk/1 (up to /atem/usk/4)
Prepare Upstream Keyer 1 /atem/nextusk/1 (up to /atem/nextusk/4)
Auto Toggle On Air Downstreamkeyer 1 /atem/dsk/1 (up to /atem/dsk/4,)
Force On Air Downstreamkeyer 1 /atem/dsk/on-air/1 <0|1> (up to /atem/dsk/4)
>>Where <0|1> is an int-value of 0 (disabled) or 1 (enabled)
Toggle Tie Downstreamkeyer 1 /atem/dsk/tie/1 (up to /atem/dsk/tie/4)
Force Tie Downstreamkeyer 1 /atem/dsk/set-tie/1 <0|1> (up to /atem/dsk/4)
>>Where <0|1> is an int-value of 0 (disabled) or 1 (enabled)
Cut Toggle Downstreamkeyer 1 /atem/dsk/toggle/1 (up to /atem/dsk/toggle/
Set Media Player # source to Clip # /atem/mplayer/#/clip/#
>>e.g. /atem/mplayer/1/clip/1 (up to /atem/mplayer/1/clip/2)
>>e.g. /atem/mplayer/2/clip/1 (up to /atem/mplayer/2/clip/2)
Set Media Player # source to Still # /atem/mplayer/#/still/#
>>e.g. /atem/mplayer/1/still/1 (up to /atem/mplayer/1/still/20, depends on your ATEM switcher)
>>e.g. /atem/mplayer/2/still/1 (up to /atem/mplayer/2/still/20, depends on your ATEM switcher)
SuperSource:
Toggle SuperSource Box # enabled /atem/supersource/#/enabled <0|1>
>>Where <0|1> is an int-value of 0 (disabled) or 1 (enabled)
Set SuperSource Box # source to input # /atem/supersource/#/source #
>>Where #610  is a valid program source. Check the Help Menu for the correct values.

There are many more including audio controls for ON/OFF, AFV  and the list goes on and on.. maybe one could look at the source code for atemOSC?

**Comment by krocheck** [comment]
atemOSC uses the Blackmagic SDK given they're programming in Objective-C.  Blackmagic as of yet doesn't provide a Node SDK, so the atem-connection library we use is reverse engineered by a few software teams that utilize that library for projects.

The audio features were recently added to atem-connection, so its on my list to get them into Companion soon.  'Toggle Upstream Keyer', 'Auto Toggle On Air Downstreamkeyer', and 'Force On Air Downstreamkeyer' are currently supported.  'Prepare Upstream Keyer' is technically a transition modifier.  I'm still investigating the best method for implementing those with our panels.

In terms of setting up atemOSC, is that on the same computer that you're running Companion?  In that case set the "OSC IP Address" in atemOSC to 127.0.0.1 and the same in the Companion Generic OSC instance.  Also, match up the 'OSC Incoming Port' with the port in Companion. After that, the commands as shown in the atemOSC manual should work.  In that respect, I'd recommend you use the 'manual' that in the README at GitHub rather then the website, which appears to be out of date.  https://github.com/danielbuechele/atemOSC
