### ISSUE TITLE
Three additional (central) commands for the vMix module

### ISSUE THREAD

**Issue by richardgatarski** [bitfocus/companion#611]
**Describe the feature**
I believe that many users (like me) prefer to setup the functionality of vMix inside vMix using its Shortcuts. One major reason is that, as has been [pointed out in the Companion user group](https://www.facebook.com/groups/companion/permalink/2237618966456441/?comment_id=2237620919789579&comment_tracking=%7B%22tn%22%3A%22R%22%7D), there are tons of functions/commands. And more are likely to be added in future versions of vMix. Hence it is practically impossible to have all commands supported in a Companion module.

After a lot of experiments one of my conclusions is that adding three commands (aka vMix Shortcuts) to Companion's vmix module would come in very handy. These (and their values) are:
KeyPress (Key), ScriptStart (Script Name), ScriptStop (Script Name), and ScriptStopAll).

To be honest, it is already possible to use these commands with the currently available "Run custom command". It would just be easier and cleaner.

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
vMix Help: [Shortcut function reference](https://www.vmix.com/help22/ShortcutFunctionReference.html)

**Usecases**
See the description above.

**Comment by JeffreyDavidsz** [comment]
Check build 52d5a4e and see if this works for you

**Comment by richardgatarski** [comment]
Thanks! Close, but I miss the cigar ;)
The Script stuff works, but not KeyPress. Sorry, I'm not a programmer and certainly not a githubber. But looking into the code I think you might have forgotten the case 'keyPress' part.

Sidequestion: is it bad behavior to here also (sort of "while you're at the code") ask for a port number  in addition to IP address when the vMix instance is added? (default is 8088, but that can be changed in vMix's settings). If I'm bad, slap my fingers and I'll open up a separate issue.

**Comment by JeffreyDavidsz** [comment]
@richardgatarski I forgot KeyPress, its in now. The port option is unfortunately a no go. This will create an open TCP module.

**Comment by richardgatarski** [comment]
Wonderful – tested and works, thanks again!

At least we can live w/o the port option.

 

Från: Jeffrey Davidsz <notifications@github.com> 
Skickat: den 16 april 2019 20:05
Till: bitfocus/companion <companion@noreply.github.com>
Kopia: richardgatarski <richard.gatarski@westreamu.se>; Mention <mention@noreply.github.com>
Ämne: Re: [bitfocus/companion] Three additional (central) commands for the vMix module (#611)

 

@richardgatarski <https://github.com/richardgatarski>  I forgot KeyPress, its in now. The port option is unfortunately a no go. This will create an open TCP module.
