### ISSUE TITLE
Raspberry: not able to run 1.3

### ISSUE THREAD

**Issue by Nojbi2000** [bitfocus/companion#612]
I did the installation on clear Raspberry as per your instruction.
After build i'm not able to run Companion and instead I got this error (please see attached)

1. Install Raspbian on Raspberry 3B+
2. Install Companion (as per your manual)
3. Start raspi desktop
4. Run Companion
5. After click on icon you get this error

Does anyone of you had success by installing on Raspi 3B+?
If yes, could you share build? 
Thank you
Jan

 
![IMG_8467](https://user-images.githubusercontent.com/49650744/56144690-25344000-5fa3-11e9-9d29-a9045e0c1c5a.jpg)

**Comment by theColourSpace** [comment]
The headless version will work, but it seems to have issues with the streamdeck disconnecting.

**Comment by JeffreyDavidsz** [comment]
I've heard that power consumption is high sometimes, you could try a powered USB hub for the disconnecting part.

**Comment by JeffreyDavidsz** [comment]
Run 'node headless.js' it will display the available network interfaces for you. Then you can try for example 'node headless.js eth0'

**Comment by Nojbi2000** [comment]
Hello, no success :(
power is not the issue. Version 1.2 works. Companion does not work even without Streamdeck

**So I tried:**

pi@raspberrypi:~/companion $ ./headless.js
Usage: ./headless.js <device> [port]

Available Interfaces:
lo 127.0.0.1
eth0 192.168.2.100

**then:**

pi@raspberrypi:~/companion $ ./headless.js eth0
  app configuration directory /home/pi +0ms
  app mkdirp /home/pi/companion/ null +19ms
  config config construct(): catch err SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at new config (/home/pi/companion/bitfocus-libs/config.js:53:21)
    at new exports (/home/pi/companion/bitfocus-libs/config.js:5:9)
    at /home/pi/companion/app.js:47:13
    at /home/pi/companion/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:153:5) +0ms
  config ERRCODE: undefined +6ms
/home/pi/companion/bitfocus-libs/config.js:69
		if (err) throw err;
		         ^

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at new config (/home/pi/companion/bitfocus-libs/config.js:53:21)
    at new exports (/home/pi/companion/bitfocus-libs/config.js:5:9)
    at /home/pi/companion/app.js:47:13
    at /home/pi/companion/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:153:5)
pi@raspberrypi:~/companion $ 

**any suggestions?**

**Comment by haakonnessjoen** [comment]
Try rm /home/pi/companion/config and then try again

**Comment by jarodwsams** [comment]
I got Companion running using headless.js by mashing together a couple different sets of instructions (documentation/raspberrypi.md and developer.md, along with steps from the Installation wiki page). See below. It runs, but I now have the issue with Companion losing its connection to the Deck periodically (different issue, so not going into detail about that here).

```Get Raspbian up and running
sudo apt update && sudo apt-get upgrade
sudo apt install libgusb-dev npm
sudo nano /etc/udev/rules.d/50-companion.rules
	SUBSYSTEM=="input", GROUP="input", MODE="0666"
	SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", MODE:="666", GROUP="plugdev"
	KERNEL=="hidraw", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", MODE:="666", GROUP="plugdev"
	SUBSYSTEM=="usb", ATTRS{idVendor}=="ffff", ATTRS{idProduct}=="1f40", MODE:="666", GROUP="plugdev"
	KERNEL=="hidraw", ATTRS{idVendor}=="ffff", ATTRS{idProduct}=="1f40", MODE:="666", GROUP="plugdev"
sudo reboot now
apt-get install nodejs git build-essential libudev-dev libusb-1.0-0-dev
sudo npm install n -g
sudo npm install yarn -g
sudo n 8.12.0
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
git clone https://github.com/bitfocus/companion.git
cd companion
./tools/update.sh
npm run rpidist
cp ~/.config/companion/db ~/companion/
sudo nano /etc/rc.local
Add this to the bottom of the flie, before the current last line
	/home/pi/companion/headless.js eth0
sudo reboot now

**Comment by jarodwsams** [comment]
@Nojbi2000 Were you able to get Companion running? Can we close this issue or are you still having problems getting 1.3 to run on your Pi?

**Comment by Nojbi2000** [comment]
Hello,
I made it work but on raspi is very slow and sometime it does not react when I press.
How does it work for you?
Jan

**Comment by jarodwsams** [comment]
I've upgraded to a Pi 4, 2GB variant. It's working pretty well. I have to make sure I reboot the Pi about once a week, but past that it's pretty solid, all things considered.

Since it's functional for you at this point, would you mind clicking the "Close" button so we know the issue has been resolved? You should see it right next to the green "Comment" button below the reply box.

**Comment by Nojbi2000** [comment]
Thanks for help, works now.
