### ISSUE TITLE
Barco Event Master Feature Request

### ISSUE THREAD

**Issue by Godamus2000** [bitfocus/companion#615]
It would be great if you could add the ability to Recall a Preset by number and also add "Recall Previous Preset" and "Recall Current" preset.

**Comment by JeffreyDavidsz** [comment]
I'm changing the sorting of the presets to hopefully match the E2/S3 list. And displaying the number with it. Recall Previous and Recall Current are not in the JSON API. I might be able to build it in the Eventmaster XML module
