### ISSUE TITLE
Octopus Listener PPT Start presentation executes wrong action

### ISSUE THREAD

**Issue by matt-hand** [bitfocus/companion#616]
Greetings,

When you start a presentation using octopuslistener: PPT Start presentation the presentation will start in a full screen windowed presentation and not with the presenter view. I believe it should be starting in the presenter view. Here is a link to a video demonstrating what happens vs what should be happening. https://hihproductions.d.pr/f1se3r

**Comment by JeffreyDavidsz** [comment]
Unfortunately that module does what it does. The author of the octopus listener does not maintain the program. If you are using PPT on a PC I would recommend Irisdown plug-in for PowerPoint. Or VICREO-Hotkey (keyboard emulator) module (both windows and OSX)

**Comment by matt-hand** [comment]
Thank you so much!
