### ISSUE TITLE
BUG: Importing requires re-starting Companion

### ISSUE THREAD

**Issue by richardgatarski** [bitfocus/companion#618]
Importing (with build 8f4539c) and Replacing the full configuration does not immediately work. The instances are added, but not working. Closing the Companion app and starting it again fixes everything. Tested on Win 10 with both Chrome and Edge. vMix and XR instances.

**Comment by josephdadams** [comment]
@richardgatarski are you still having this problem if you use one of the latest 2.0 releases?

**Comment by richardgatarski** [comment]
Sorry for late response. Still some issues, did a small test with companion-2.0.0-00e63de-1990-win64
Importing with replace current configuration shows the instance for vMix, but "Status" is blank.
Clicking Edit gives Javascript error.
If I then click Disable followed by Enable it works just fine.
![jserror](https://user-images.githubusercontent.com/47746293/72205433-3e5f1400-3483-11ea-9ea3-bfc97546695e.JPG)

**Comment by Julusian** [comment]
I believe this works better now
