### ISSUE TITLE
Octopus Preset Recall

### ISSUE THREAD

**Issue by IanTGreenwood** [bitfocus/companion#62]
**Describe the feature**

Since many of us bought our Stream Decks for use with Octopus, would it be possible to add Octopus control?  

**Is this platform dependent (windows, mac, ..)?**

Octupus is Mac only.

**If documentation is required to implement, do you know where to find it?**

The TCP syntax is:

Oct,RPreset,1%0D

Where 1 is the Preset being recalled.

**Usecases**

Octopus preset recall would open up StreamDeck control of the many devices that Octopus can natively control, as well as its scripting functions.

**Comment by willosof** [comment]
Port number? Tcp? Udp? Is recall the only thing we can/want to do? Is there any feedback? Any documentation you can attach?

**Comment by willosof** [comment]
But, uh. Oct,RPreset,1\r ? Not Oct,RPreset,1\n ?

Or Oct,RPreset,1%0D\r\n ? ;p 

\x0A vs \x0D

**Comment by IanTGreenwood** [comment]
It is TCP and the default port is 9090, but it is configurable.

The only feedback that Octopus seems to have currently is just an acknowledgement that the command has been received.

e.g. 
ACK:Oct,RPreset,PRESETNUMBER%0D 
where PRESETNUMBER = the number of the Preset recalled (integer)

There are many other commands, but there is no documentation that I am aware of.  Its just a matter of creating a preset and checking the debug window to see what commands are sent.

But I think that recalling Presets is mostly what is needed.  

The only other thing I might find useful (off the top of my head)  would be the ability to Enable/Disable devices.  This would be most useful with a "toggle" style button though.  The syntax is:

Enable:
Oct,EDevice,DEVICEID%0D
Disable:
Oct,DDevice,DEVICEID%0D

where DEVICEID= the device id # (integer)

I'll ask around to see if there are any other commands that would be useful for those that do more advanced things with Octopus.

Let me know if you have any further questions,

Ian

**Comment by IanTGreenwood** [comment]
@willosof I don't understand your question.

Also, I don't understand how to quote a comment on github. :)

> But, uh. Oct,RPreset,1\r ? Not Oct,RPreset,1\n ?

Or Oct,RPreset,1%0D\r\n ? ;p

\x0A vs \x0D

**Comment by willosof** [comment]
Don't worry about it @IanTGreenwood :) @haakonnessjoen just found out. Will implement!

**Comment by willosof** [comment]
This depends on #69

**Comment by IanTGreenwood** [comment]
I just realized that in Octopus if you delete a preset, it shifts all of the preset numbers above the one you deleted.

e.g.
You have presets 1, 2, 3, 4
Delete preset 2.
3 becomes 2 and 4 becomes 3.

That might be a bit dangerous. :S However, It would still be handy if you're doing something on the fly, and don't have time to add an OSC trigger to the preset in octopus.

**Comment by willosof** [comment]
That sucks. Oh well, not our problem. But we should probably let the user know.. 😆

**Comment by willosof** [comment]
Is there a way to list out preset names and id's from octopus? Weird if it isn't any uuid on the presets

**Comment by IanTGreenwood** [comment]
> Is there a way to list out preset names and id's from octopus? Weird if it isn't any uuid on the presets

Short of parsing from the config file (XML), I don't think so.

**Comment by haakonnessjoen** [comment]
Is there a list of OSC commands available on octopus?

**Comment by IanTGreenwood** [comment]
> Is there a list of OSC commands available on octopus?

AFAIK there aren't any dedicated OSC commands, but you can assign whatever OSC message you want to a preset, in the same way you would assign a keyboard shortcut or MIDI note.  This would be the safer way as OSC trigger isn't dependant on the actual preset number.  However, this can be a little cumbersome.

**Comment by PerRoine** [comment]
This module has been made and tested closing this for now, if anyone needs mor Actions please raise a new feature request
