### ISSUE TITLE
More functionality for Brightsign module

### ISSUE THREAD

**Issue by cdmlehigh** [bitfocus/companion#620]
**Describe the feature**
Hello- I'm hoping that somebody might be able to help with adding some more functionality to the "BrightSign" Module.

Somebody was kind enough to create a module that has some basic commands (pause, resume, etc...), however one of the features that's great about these players is the ability to create interactive presentations that are controlled by custom UDP triggers (ie whatever string you choose).

Would it be possible to add a "custom command" option to the existing module, where I could enter my own text string as an option for the command?

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
I don't think any extra documentation is required, as the request builds on existing functionality

**Comment by JeffreyDavidsz** [comment]
It's in one of the latest builds now

**Comment by cdmlehigh** [comment]
works great, thank you!

**Comment by Sz-Mes** [comment]
Sorry for asking, I`m an absolute beginner in using stream deck and would like to control brightsign players as described by cdmlehigh.
where do I find the module you mentioned?
Thanks in advance.

**Comment by JeffreyDavidsz** [comment]
Download a latest build @ builds.bitfocus.io

**Comment by Sz-Mes** [comment]
Hi Jeffrey,

 

thank you, it works.

 

Von: Jeffrey Davidsz <notifications@github.com> 
Gesendet: Montag, 29. April 2019 11:47
An: bitfocus/companion <companion@noreply.github.com>
Cc: Sz-Mes <stefan.zach@mes-24.de>; Comment <comment@noreply.github.com>
Betreff: Re: [bitfocus/companion] More functionality for Brightsign module (#620)

 

Download a latest build @ builds.bitfocus.io

**Comment by Sz-Mes** [comment]
Hi Jeffrey,

another stupid question: how do I setup the udp port to send the messages to?

 

Von: Jeffrey Davidsz <notifications@github.com> 
Gesendet: Montag, 29. April 2019 11:47
An: bitfocus/companion <companion@noreply.github.com>
Cc: Sz-Mes <stefan.zach@mes-24.de>; Comment <comment@noreply.github.com>
Betreff: Re: [bitfocus/companion] More functionality for Brightsign module (#620)

 

Download a latest build @ builds.bitfocus.io

**Comment by JeffreyDavidsz** [comment]
The port is fixed: 21075 this because of the custom command

**Comment by Sz-Mes** [comment]
great, thanks!

 

Von: Jeffrey Davidsz <notifications@github.com> 
Gesendet: Dienstag, 30. April 2019 18:33
An: bitfocus/companion <companion@noreply.github.com>
Cc: Sz-Mes <stefan.zach@mes-24.de>; Comment <comment@noreply.github.com>
Betreff: Re: [bitfocus/companion] More functionality for Brightsign module (#620)

 

The port is fixed: 21075 this because of the custom command

**Comment by JeffreyDavidsz** [comment]
@cdmlehigh & @Sz-Mes  I'm running a test on a XD1030 but somehow it doesm't work directly. Do the commands work out of the box, or do I need to apply a script first. Can it work without adding the UDP events? 
I've already changed the fixed port to flexible just to test with port 5000. But no luck. How did you setup?
