### ISSUE TITLE
Tablet view improvements

### ISSUE THREAD

**Issue by chrisrouse** [bitfocus/companion#621]
The tablet view is helpful, but needs some work on it to be even better. I don't know which of these are even possible and I haven't taken the time to try to figure out the rendering of this page yet.

1. If you tap a button while scrolling (touch and scroll and then release your finger), it will trigger the button.

2 Improve the font rendering to be sharper.

3. Escape line returns using \n show that in the page name rather than ignoring it or replacing it with a space.

4. Need a little more margin on the left side for scrolling.

**Comment by Julusian** [comment]
I think that some of this has been done, or is done in the other tablet views.
There is another issue to consolidate the tablet views, which this also falls under
