### ISSUE TITLE
Import Page doesn't work

### ISSUE THREAD

**Issue by chrisrouse** [bitfocus/companion#623]
When importing a configuration you have an option to select a page to import and replace, but it's impossible to select anything other than Page 1.

**Comment by chrisrouse** [comment]
So it seems like it is picking the page you can import to replace based on a random attached Stream Deck. It would be nice to just be able to select which page you want to replace since you can choose when one to import.

**Comment by haakonnessjoen** [comment]
Sorry if it is not obvisous. But it imports to the currently open page in admin.
