### ISSUE TITLE
RossTalk Dashboard GPI should be alphanumeric

### ISSUE THREAD

**Issue by chrisrouse** [bitfocus/companion#624]
You can send an alphanumeric string to RossTalk for Dashboard that includes non-numeric characters. So instead of just sending "1" you could send "Change 1" and it should work. Right now it seems the RossTalk module only supports numeric GPI formatted for XPression and Carbonite.

**Comment by josephdadams** [comment]
Seconded. Also, the port should be user assignable, as it is also assignable in Dashboard. It can still default to 7788.

**Comment by josephdadams** [comment]
This seems fixed with the "Trigger GPI By Name" action. The port is also assignable. Closing.
