### ISSUE TITLE
Websockets Sender

### ISSUE THREAD

**Issue by DeeJayMX** [bitfocus/companion#625]
**Describe the feature**
Instance that could send Websockets messages

**Is this platform dependent ?**
No

**If documentation is required to https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications

**Usecases**
It could be really useful for connecting to automation system like eventghost, like the websocket plugin in OBS, like home automation system (Domoticz, fibaro...)
Lot of IoT working on Web messages...

I know that Companion know how to receive WebMessages but what about to send ?

Thanks for all the good work !

**Comment by haakonnessjoen** [comment]
We would rather have modules for all of those, than just make a generic websocket module. There is already a module for obs-websocket, etc.

Please request modules for the systems you would want, or create the modules yourself, and push to us :)

**Comment by johncoles** [comment]
While I agree for making modules it would be nice for some systems that I have written for our own use to just have a quick websocket module that could be used in the same way that there is the generic HTTP.

**Comment by DeeJayMX** [comment]
+1

**Comment by josephdadams** [comment]
Closing this since generic modules aren't preferred.

**Comment by ryantheleach** [comment]
> here is already a module for obs-websocket, etc.

Can OBS be added to the readme then? I thought it didn't support it, until I searched through the issues before requesting OBS specfically.
