### ISSUE TITLE
Button Layout page drop down jump menu

### ISSUE THREAD

**Issue by thereisnoh** [bitfocus/companion#628]
Instead of having a just (Page #) next to the text box to edit the page name on the button layout editor page, make that (Page #) a drop down menu that will jump to the desired page when selected instead of having to click the blue left or right arrows up to 50 times to get to a page you want to edit.

**Comment by jackcrombie** [comment]
Yep. This or have a text box we can type the page number into and hit enter to jump to a page number for programming keys. PLEASE!!! :)

**Comment by bryce-seifert** [comment]
I can see the value of possibly having both. Page number is helpful if you know where you need to go, drop down with the names of pages would be helpful if you have a lot of pages and need to search by name.

**Comment by bryce-seifert** [comment]
@jackcrombie @thereisnoh The "type the page number" version of this has been implemented with https://github.com/bitfocus/companion/commit/dd03d8afea5a34c17d607f61a262002513605575

**Comment by Julusian** [comment]
This is in 3.0
