### ISSUE TITLE
Action to change button background image.

### ISSUE THREAD

**Issue by theColourSpace** [bitfocus/companion#630]
Would love to be able to update the button background image as part of an action. So basically be able to set a trigger than replaced the button background with one at a defined location when triggered. Obviously the image would need to be in a path accessible to the host system.

**Comment by dnmeid** [comment]
We once discussed a different approach. To give the buttons "states". That means you can have state 0 with image, color text and so on and state 1 with a different image and text and even more states as you need. Then feedbacks or the internal module could just change the state to alter the complete look of the button. I think this is the most elegant solution.

**Comment by theColourSpace** [comment]
Yes but that wouldn't allow you to use an external script to dynamically update the button's background. For example, have a video player load a clip, grab a still from the clip and then use that image as the clips thumbnail.

**Comment by dnmeid** [comment]
Please don't mix up to many different functions. Dynamic images is another topic. The solution for this will need a different and more complex approach because of our image cache generation. Dynamic images are a topic every once in a while but I don't feel they have high priority. State based change of the button look will do for the majority of usecases.

**Comment by haakonnessjoen** [comment]
Just to be clear. The feedback system is perfectly capable of dynamically changing the background image of a button, using png data uri encoded as base64. But this only helps if you are developing a module for companion. Changing background from external scripts is not supported right now. But I think it is better for this to be done by modules anyways. So more people can enjoy such features.

**Comment by Julusian** [comment]
This can be achieved in 2.2 by using a custom variable and a feedback checking the value of that variable:
![image](https://user-images.githubusercontent.com/1327476/155630938-e0ec469d-892c-45cd-b2c0-ff4ef59c620c.png)
