### ISSUE TITLE
Module Request: Denon bd500mkII blueray player

### ISSUE THREAD

**Issue by hollywood138** [bitfocus/companion#631]
**Describe the feature**
I would like to control the shutter on barco projector and play/pause on denon bd500mkII

**Comment by JeffreyDavidsz** [comment]
For the Barco HDF try the HDX module (in the latest build). For the Denon please provide API

**Comment by hollywood138** [comment]
How do I update the build? Im currently using v1.3.0 (1a7592b-1203) . 

The only way I know how to control the Denon BlueRay player is with serial codes. please see attached 

[DN-500BD_MKII_Protocol_Guide_1.0.pdf](https://github.com/bitfocus/companion/files/3136393/DN-500BD_MKII_Protocol_Guide_1.0.pdf)

**Comment by JeffreyDavidsz** [comment]
Latest builds are at builds.bitfocus.io

**Comment by hollywood138** [comment]
Thank you!!! I got it all working you're amazing!
