### ISSUE TITLE
Blackmagic Videohub Routing shows no destination

### ISSUE THREAD

**Issue by officialmattsnyder** [bitfocus/companion#632]
**Describe the bug**
When using Blackmagic VideoHub module (specifically with a 12x12), the "route" action does not show any options in the "destination" dropdown menu.

**To Reproduce**
1. Create a button for the "route" option
2. Note Destination Line

**Expected behavior**
There should be options populating the destination menu.

**Screenshots**
![Screen Shot 2019-05-01 at 10 55 34 AM](https://user-images.githubusercontent.com/50146619/57023547-55651b00-6c00-11e9-971e-c88be5ee03d9.png)

**Desktop (please complete the following information):**
 - OS: OSX 10.12.6
 - Browser Chrome 73.0.3683.103

**Comment by krocheck** [comment]
@officialmattsnyder what version/build are you running?

**Comment by officialmattsnyder** [comment]
@krocheck 1.3, but I don’t remember off the top of my head so that may be inaccurate.

I have noticed that the action behaves “correctly” when I actually am connected to the hub. But when I’m working off site and can’t connect to the hub, the destination drop down doesn’t populate (the input does though).

**Comment by krocheck** [comment]
@officialmattsnyder if you could test against the latest build that would help me.  We did a number of internal changes to the module and I believe this is already resolved.

https://builds.bitfocus.io/companion/

**Comment by josephdadams** [comment]
Closing this as we are pretty sure this is resolved. @officialmattsnyder , if you're not satisfied, we can re-open and move this to the videohub repo for tracking.
