### ISSUE TITLE
Module Request: Draco Tera KVM

### ISSUE THREAD

**Issue by sjtinsley83** [bitfocus/companion#633]
I have a Draco Tera KVM Matrix and would like to control it via Companion.

I have tracked down the manual and it looks fairly straight forward.

*PDF file removed by demand from manufacturer*

All the commands are in hex.

**Example:**
Set CPU device (CpuID = 1012) connection to CON device (ConID = 3017)
`0x1B 0x5B 0x49 0x09 0x00 0xC9 0x0B 0xF4 0x03`

Would someone help me with a starting point for this module?

**Comment by JeffreyDavidsz** [comment]
Starting point would be the [wiki ](https://github.com/bitfocus/companion/wiki) to install a developer environment. Then pick one of the smaller TCP modules like barco-hdx, copy that to a new draco-tera-kvm folder, remove all unwanted actions/commands and start playing testing.

**Comment by sjtinsley83** [comment]
Hi @JeffreyDavidsz,
I have the start of my module. I have tested, and so far so good.
Would you be able to create the repository for my module: draco-tera-kvm

**Comment by JeffreyDavidsz** [comment]
Check, will pass it on

**Comment by sjtinsley83** [comment]
I have made some changes here:
https://github.com/sjtinsley83/companion-module-draco-tera

I want to add to the master but I don't know how. Can someone help?

**Comment by JeffreyDavidsz** [comment]
You can do a new pull request to submit your code

**Comment by sjtinsley83** [comment]
It appears they are the same. I'm not sure how to checkout the branch.
