### ISSUE TITLE
Module request: ZEN NDI Router

### ISSUE THREAD

**Issue by willosof** [bitfocus/companion#634]
http://www.zenvideo.co.uk/Download/ZEN_NDI_Router_protocol.pdf

ZEN NDI Router support :)

**Comment by EventReplay** [comment]
I thought i'd try to make a basic start, Great little program.
https://github.com/EventReplay/module-zen-ndirouter

This I think will only work for the 1.3 beta version which has the control protocol.

**Comment by EventReplay** [comment]
@willosof basic ndirouter module included in latest bleeding edge.
Would welcome feedback.

I have been in contact with Martin @ Zenvideo who has offered help if required.

**Comment by EventReplay** [comment]
Martin @ Zenvideo has run tests and seems happy enough to make a facebook anouncement about it!
Well Happy!

This issue can be closed.

**Comment by josephdadams** [comment]
Closing because this module exists and people seem happy.
