### ISSUE TITLE
[User settings] Skip/hide empty pages

### ISSUE THREAD

**Issue by Wiethoofd** [bitfocus/companion#640]
**Describe the feature**
Prevents the user to navigate to _empty_ pages where no buttons have been assigned.

**Usecases**
If you only have one or a few pages worth of buttons the Page Up/Down might cause you to end up on an empty page and require you to keep pressing to go back or forward to a page where you have buttons set up. (or in the current 1.3.0 build pressing the page number to go back to the first page #410)

An option in the user settings to skip empty pages or only add them when a button is assigned on it should be able to prevent cycling through these useless/empty pages. (#361)

Additionally in the Tablet view hiding or enabling/disabling the empty pages could prevent a lot of scrolling, this should perhaps be an optional setting in case empty pages were added to prevent accidental presses when navigating between pages or to separate the button groups/pages in their own sections.

**Comment by josephdadams** [comment]
+1. This would be really nice as a preference setting to automatically skip blank pages.

**Comment by willosof** [comment]
Not an issue anymore. Just remove the first page down button and the last page up button.

**Comment by McHauge** [comment]
Hey, got a similar idea for a feature.

An option to limit the available pages based on the stream deck id, and an auto rollover if you hit max/min. 
An example of this could be if you are using 2 or more stream decks for different roles, and want to prevent acidently messing with the wrong pages. 

I might want to limit the producer to say page 10-19 for macros and relevant keys in production and the technician using page 0-9 for controlling the video hub and routing of the production.

atm. I would use an empty page as a separator, but the ability to rollover is missing atm, so when you in the example hit page up while on page 9 it would go to page 1 again, and the same on the other deck. And together with this the option to set what page is the default for a given device.
