### ISSUE TITLE
copy commands from 1 instance to another or master -slave setting

### ISSUE THREAD

**Issue by Sullyy** [bitfocus/companion#642]
the possibility copy the commands sent to an instance to another similar instance. ex: 2 resolume, 1 is backup- i need to copy all the commands from the main to the backup resolume.
Or the possibility to set 1 instance as slave to another an it to automatically take the commands sent to the main

**Comment by rywolf** [comment]
Yes.. could we please have backup or multiple instances at the instance level. 
It would sure simplify programming for a lot of things vs replicating the same action multiple times on one button.

**Comment by simongroom112** [comment]
was there an update to this/did it ever get implemented?
