### ISSUE TITLE
Companion never finds stream deck.

### ISSUE THREAD

**Issue by dc-eicx** [bitfocus/companion#644]
I had Companion working great last week.  Then some weird stuff started happening with my computer.  I uninstalled a bunch of programs including Companion.  After I got the computer back to normal I reinstalled Companion.  Unfortunately, now Companion can't find the stream deck.

Let's say I had a brand new clean install of Windows 10, what exactly is the procedure?  Should I install Node or does Companion do that OR do I only need Node if I am building interface modules.

Please be specific - assume I am on the slow side!

**Comment by willosof** [comment]
Companion shouldn't require any other installations or drivers than itself. Do you have another physical streamdeck to test with?

**Comment by dc-eicx** [comment]
I have a couple of stream decks and they both work fine with factory software.  They do come up as Stream Deck 3 and Stream Deck4 in the factory application.  Any idea how to wipe out those and have a single Stream Deck be identified as Stream Deck 1.  I have removed and reinstalled everything a couple of times.

**Comment by silid** [comment]
You might want to try this tool to remove non present devices https://www.uwe-sieber.de/misc_tools_e.html

**Comment by josephdadams** [comment]
This seems to be an isolated issue and not something everyone is experiencing. I am closing this issue as it is now 3 months+ old and stale. @dc-eicx , if it's still happening, please re-open. Thanks!
