### ISSUE TITLE
Bug when launching two instances or port currently in use

### ISSUE THREAD

**Issue by Deanbau** [bitfocus/companion#65]
**Describe the bug**
Error when launching two copies of Companion

**To Reproduce**
Launch two instances of Companion

**Expected behavior**
An pretty error box

**Screenshots**

![image](https://user-images.githubusercontent.com/39572328/40951075-7b106f92-6843-11e8-94a1-4d90f48acb3e.png)

**Comment by willosof** [comment]
Maybe @haakonnessjoen wants to figure out how to make file locks on the config file? And then quit gracefully/silently if there is locks applied on config and db?

**Comment by willosof** [comment]
Two instances would fuck up the db/config system anyways.
