### ISSUE TITLE
ATEM 2M/E All Aux and M/E 2?

### ISSUE THREAD

**Issue by KameraOWL** [bitfocus/companion#650]
I am trying to switch not only on M/E 1 but also on M/E 2 but cannot find any solution for this? Also, how can I use AUX 1-6 and not only Aux 1-3? I'm using 1.3.0 release on mac. 

Thanks!!

**Comment by JeffreyDavidsz** [comment]
Lot of extra's in latest builds, please try that first and see if you are still missing stuff.
