### ISSUE TITLE
Feedback triggers other button actions

### ISSUE THREAD

**Issue by Keksstar** [bitfocus/companion#651]
It would be great if the instance feedback of the ATEM could be used to trigger buttons in Companion.

Example: Video Op is switching on the ATEM as normal. Companion takes the signal and triggers buttons (on page 99 ;-) )which could then trigger all the Tally Apps, TSL, or even Remotecam presets, etc.

**Comment by krocheck** [comment]
This would require an 'automation' type framework.  We're not setup for that currently, but I'll leave this open should that be added in the future.

**Comment by Keksstar** [comment]
I don´t think so... cause it already can change the color on buttons, so it should be very easy that it presses a button instead of changing the color

**Comment by krocheck** [comment]
@Keksstar you are always welcome to submit a pull request with the code for features you want to see in the software. 😉

**Comment by josephdadams** [comment]
@Keksstar take a look at this repo, I implemented feedback actions for it: https://github.com/bitfocus/companion-module-techministry-umdlistener

You can execute a button press when the feedback criteria is met.

**Comment by Keksstar** [comment]
Can´t find it in the latest build?

**Comment by josephdadams** [comment]
https://github.com/bitfocus/companion-module-techministry-umdlistener

**Comment by Keksstar** [comment]
Yeah, but is it already in the latest Companion build? I‘m no programmer... I have no clue how I could test your work :)

**Comment by tim-barr** [comment]
Is there any update on this?  If there is a new way to trigger other buttons based on Feedback, I would appreciate direction.  I am looking to trigger actions based on Program/Preview status on particular inputs to an Atem.  Thanks

**Comment by Keksstar** [comment]
> 
> 
> https://github.com/bitfocus/companion-module-techministry-umdlistener

That´s not implemented yet in the latest builds, correct?

**Comment by josephdadams** [comment]
It’s not but once the scheduler/trigger gets put in, you’ll be able to do things like “when this variable equals this value, press this button” and won’t need a module like this.

**Comment by eazuka** [comment]
> It’s not but once the scheduler/trigger gets put in, you’ll be able to do things like “when this variable equals this value, press this button” and won’t need a module like this.

@josephdadams thanks for your module, just for clarity, is the  scheduler/trigger your module or a feature to be release as part of Companion core?

**Comment by josephdadams** [comment]
No it’s not my work. @onfire4g05 developed the triggers feature

**Comment by onfire4g05** [comment]
> > It’s not but once the scheduler/trigger gets put in, you’ll be able to do things like “when this variable equals this value, press this button” and won’t need a module like this.
> 
> @josephdadams thanks for your module, just for clarity, is the scheduler/trigger your module or a feature to be release as part of Companion core?

You can actually test it out in the latest betas.

**Comment by Gartom** [comment]
This seems interesting.
How do I activate or use the scheduler/trigger functionality?

**Comment by onfire4g05** [comment]
In the beta, go to the Triggers tab. You can then create triggers based on variables, time of day, etc.

**Comment by tim-barr** [comment]
Justin, I've installed the Beta Build 2.2.0 (build 3271) and have switched my Tally controls to the new Triggers method.  However, I can't get the one where I have Program, Preview, and Neither to work.  It is the only one with != testing.  What am I missing?  Also, what order do triggers run, if there are two that might be true?
![image](https://user-images.githubusercontent.com/69765329/115895519-86ac0680-a428-11eb-8825-daae50d2e194.png)

**Comment by onfire4g05** [comment]
#1577 fixes this, it's a bug I just patched yesterday. In the current betas, only a single condition works.

**Comment by tim-barr** [comment]
Thanks Justin.  When do you think #1577 will be available via Beta Builds?
Also, are the tests/actions executed in order?  If so, It might be nice to be able to move them around and/or add delays.

**Comment by paulfehr90** [comment]
This sounds like a specific problem, but I'm trying to use triggers when a downstream key is onair on a atem.  There isn't a variable for that, but there is feedback available on a button.  Is there any way around this?  
Or like possibly including variables of colors of buttons?  if button 1.1 is #ff0000 then do this.  That would also solve my problem.

**Comment by Julusian** [comment]
#1604 will allow for this to be done, for modules that have updated feedbacks to be of the new flow.
