### ISSUE TITLE
New Instance Internal Module

### ISSUE THREAD

**Issue by skermanator** [bitfocus/companion#656]
**Describe the feature**
Make Internal Module a separate instance. 
This would allow for the user to add more than 1x instances and the ability to disable certain internal commands depending where it is assigned 

**Is this platform dependent (windows, mac, ..)?**
No

**Usecases**
Allowing to stack multiple internal push keys but having them assigned to different instances. 
Allowing you enable and disable the push keys. 
This would allow you to clone a routing change in a video hub via push key commands, but the ability to separate when needed by disabling the internal command

**Comment by willosof** [comment]
I think this needs to be solved another way.. Rather with conditions for actions :)
