### ISSUE TITLE
Single Page Mode

### ISSUE THREAD

**Issue by dwriggles** [bitfocus/companion#660]
**Describe the feature**
The ability to enable single page mode would eliminate the the page up/down/id buttons and allow them to be assignable just like the other buttons. 

**Is this platform dependent (windows, mac, ..)?**
NO

**If documentation is required to implement, do you know where to find it?**
N/A

**Usecases**
This would prevent users from changing pages when there is only one page being used. This provides for a simpler interface for inexperienced users. 

This increases the number of available buttons on a single page for small applications. that do not require multiple pages.

**Comment by dnmeid** [comment]
Closing this because it is a duplicate. Actually it is one of the most requested features and is planned for the mid future.
