### ISSUE TITLE
Yamaha QL1 Control

### ISSUE THREAD

**Issue by PitMan71** [bitfocus/companion#661]
**Describe the bug**
The control feature "Recall Scene" in the Yamaha QL instance is not working. I do however have other features working such as input level so I know I am connecting to the device. Anyway, to solve the issue I have tried both bank options and nothing works.... Not sure what I am doing incorrectly.
ALSO, Is there a way to control mix levels? 

**To Reproduce**
Steps to reproduce the behavior
Just add the feature "Recall Scene" add Scene Number and select bank.

**Expected behavior**
I expected the scene to change... when activating nothing happens.

**Screenshots**

**Desktop (please complete the following information):**
 - Sierra 10.12.1
 - Safari
 - 10.0.1

**Additional context**
- Also using a stream deck.

Thanks
Shane

**Comment by davebedson** [comment]
Hey Shane,
Did you get this working? 
If so do you know how?

I'm having the same issue,

Cheers
Dave

**Comment by PitMan71** [comment]
I didn’t get it working. It appears that there is a bug in the coding. In fact, it has the correct info when you load into companion but displaying the incorrect control options which is for a TF console if that makes sense.
