### ISSUE TITLE
Request For Ability To Alter Images on Buttons

### ISSUE THREAD

**Issue by Hantoo** [bitfocus/companion#664]
**Describe the feature**
When a button is clicked to allow an pre-determined macro to be run which would allow for images on other buttons to be changed.
It would be nice to tell it which buttons to effect as it would be nice to have program and preview buttons on one page.
For example,
If I had 4 program buttons to change the program output on the Blackmagic Atem Vision, then whichever one is active I want to be Red. If I click the 3rd program output button then I want that to turn red and the rest to change to either a different image or colour to show that its not active. 

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
Internal Companion 

**Usecases**
For example,
If I had 4 program buttons to change the program output on the Blackmagic Atem Vision, then whichever one is active I want to be Red. If I click the 3rd program output button then I want that to turn red and the rest to change to either a different image or colour to show that its not active.

**Comment by haakonnessjoen** [comment]
Answered in #665
