### ISSUE TITLE
[Request] Hide commands within the Instance config

### ISSUE THREAD

**Issue by KarstenTWolf** [bitfocus/companion#667]
**Describe the feature**
Within the Instance page there should be a check box menu to hide commands from the buttons config dropdown. This shouldn't disable the command, just hide it from the menu. 

Within modules there should be an option to have certain commands default to being hidden. 

**Usecases**
Lots of times I'm only really looking for 2-3 commands per instance. While I appreciate the functionality, scrolling through everything to get to the one command I'll need on the 4th graphics machine is annoying. Or there's certain commands that I will only use for one key in a setup, after which the option is just clutter in the menu.

**Comment by willosof** [comment]
Nice! I like this very much :)

**Comment by Julusian** [comment]
I feel like this is no longer necessary, with https://github.com/bitfocus/companion/pull/2014 being an alternate solution.

If there is still demand for hiding actions/feedbacks from the search results or this modal, then this can be reopened
