### ISSUE TITLE
Javascript error on launch win 10 version 1.3 chrome

### ISSUE THREAD

**Issue by pmrct** [bitfocus/companion#668]
**Describe the bug**
JavaScript error in the main process

**Screenshots**

![Capture (2)](https://user-images.githubusercontent.com/51098141/58440024-5bd29f80-80a5-11e9-8158-25e685628fd9.PNG)

**Desktop (please complete the following information):**
 - OS: wiin 10
 - Browser: chrome
 - Version: 1.3.0 (1a7592b-1203)

**Comment by pmrct** [comment]
![Capture (2)](https://user-images.githubusercontent.com/51098141/58439921-e36bde80-80a4-11e9-9843-3851b5e83231.PNG)

**Comment by haakonnessjoen** [comment]
Try deleting %APPDATA%\companion\db

**Comment by josephdadams** [comment]
@pmrct are you still getting this error in the latest release?

**Comment by josephdadams** [comment]
Closing. @pmrct if you experience the error in one of the latest releases, you can re open this.
