### ISSUE TITLE
Companion profile “bleeds through” native Stream Deck profile using Elgato software

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion#669]
**Describe the bug**
When using the companion plugin, and features from the native stream deck software, the companion buttons show through the native buttons when pushed and perform both actions.  This can be fixed and work as expected by unplugging and replugging the streamdeck.  On restart, problem is back.

**To Reproduce**
Any time the companion plugin is used in conjunction with stream deck software.

**Expected behavior**

After repluging stream deck it works as expected with no buttons or actions bleeding through.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser IE
 - Version 1.3.0

**Additional context**

**Comment by IceFlom** [comment]
I have the same problem, it's unusable this way. I want to use the streamdeck application and some actions from companion, but companion overtakes the whole streamdeck.
Unplugging streamdeck device, start companion and replugging the device on every restart is not really a solution.
Would be better to have an option in companion to tell it not to use the hardware streamdeck, even when it's detected. Is that possible?

**Comment by JeffreyDavidsz** [comment]
I'm missing some information about the plug-in and or restart of the Streamdeck software. The plug-in is especially made for these use cases but only works on the smaller Streamdeck not xl.

**Comment by IceFlom** [comment]
I'm using the normal streamdeck (not xl, not mini). Plugin is installed:
![companion_plugin_installed](https://user-images.githubusercontent.com/13588486/62164689-32402980-b31d-11e9-9dc2-ad86e5dd06ef.png)
and it's available in the menu:
![available_in_menu](https://user-images.githubusercontent.com/13588486/62164802-61569b00-b31d-11e9-961e-cc41d56db116.png)
As soon as I try to use it, it tells me that it needs a locally running companion:
![needs_local_installation](https://user-images.githubusercontent.com/13588486/62164933-9bc03800-b31d-11e9-920c-0df55ac5003a.png)
But when I start companion, it changes all my buttons, some of them will be refreshed by streamdeck application immediately. All buttons do have two functions now (original streamdeck and companion), they seems to "fight" for the buttons.
Link to a video, which shows what's happening if I start companion: https://1drv.ms/v/s!Au5SpxAVNDcijZgkqsSidJU4e5vJrg 

Streamdeck software version is: 4.3.1.11285
Firmware-Version: 1.0.170133

**Comment by JeffreyDavidsz** [comment]
Thanks for the info, did you try the other way around? First start Companion and then start Streamdeck app?

**Comment by IceFlom** [comment]
Yeah, it's the same behavior. I see the companion buttons, streamdeck app will overwrite the buttons, but companion seems to be active in the background. If I press for example the bottom left button, it will execute the streamdeck action, but also the page down action from companion. The page down action overwrites the buttons again.

Companion started:
![companion_started](https://user-images.githubusercontent.com/13588486/62166697-c1e7d700-b321-11e9-8c2a-ba6d0edfb914.png)
Streamdeck app started:
![streamdeck_app_started](https://user-images.githubusercontent.com/13588486/62166714-cad8a880-b321-11e9-9456-1ce0dc266b18.png)
Pressed button on the bottom left:
![pressed_bottom_left_button](https://user-images.githubusercontent.com/13588486/62166727-d3c97a00-b321-11e9-8921-d4cf02388733.png)

**Comment by koben307** [comment]
Hey! I have the same issue and can't find any solution. Please help! :)

**Comment by Julusian** [comment]
@koben307 quit and restart companion

**Comment by koben307** [comment]
I did that a hundred times. I reinstalled companion and stream deck.

**Comment by Julusian** [comment]
try plugging in the streamdeck after companion is running. and dont tell companion to scan for usb devices

**Comment by koben307** [comment]
Thanks, seems do be working. Don't know, how it ´first appeared, but I am happy its ok now.

**Comment by koben307** [comment]
Hi again. Have to repeat it after restart. Its a workaround, but no solution.
