### ISSUE TITLE
New Module Repository Request :: generic-os

### ISSUE THREAD

**Issue by jeffmikels** [bitfocus/companion#675]
Please create a repository for my **generic-os** module.

**Describe the feature**
I have written a module called generic-os that allows the user to attach a streamdeck button to any system command.

**Is this platform dependent (windows, mac, ..)?**
No, it uses node's builtin child_process module.

**If documentation is required to implement, do you know where to find it?**
It's self-explanatory and as easy to use as the Generic HTTP module.

**Usecases**
With this module, a single streamdeck button can be programmed to accomplish any sort of task on the local computer. Now, streamdeck can launch shell scripts, open a browser, run applescripts, etc.

**Comment by JeffreyDavidsz** [comment]
Hi Jeff, thanks for your work I'll create a repo for you
