### ISSUE TITLE
CORE(cb) error on Companion Start-up

### ISSUE THREAD

**Issue by jarodwsams** [bitfocus/companion#679]
**Describe the bug**
Every time Companion initializes (i.e. rebooting the pi) I get an error in the Companion logs.
`05. 19:39:50 CORE(cb): db.tmp->db failed: Error: ENOENT: no such file or directory, rename 'undefined/companion//db.tmp' -> 'undefined/companion//db'`

**To Reproduce**
1. SSH into raspbery pi running Companion
2. `sudo reboot now`
3. Observe the error in the Companion log after startup

**Expected behavior**
Companion should launch without db errors when the `db` file clearly exists

**Screenshots**
<img width="659" alt="Screen Shot 2019-06-05 at 7 28 17 PM" src="https://user-images.githubusercontent.com/22972834/58999310-cfbe2780-87ca-11e9-8340-90e12e91c059.png">

**Desktop (please complete the following information):**
 - OS: Raspian Stretch
 - Browser: Chrome
 - Version: Companion v1.3

**Additional context**
I'm running Companion via headless.js, launched from /etc/rc.local
`/home/pi/companion/headless.js eth0`
Installation Steps
```Get Raspbian up and running
sudo apt update && sudo apt-get upgrade
sudo apt install libgusb-dev npm
sudo nano /etc/udev/rules.d/50-companion.rules
	SUBSYSTEM=="input", GROUP="input", MODE="0666"
	SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", MODE:="666", GROUP="plugdev"
	KERNEL=="hidraw", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", MODE:="666", GROUP="plugdev"
	SUBSYSTEM=="usb", ATTRS{idVendor}=="ffff", ATTRS{idProduct}=="1f40", MODE:="666", GROUP="plugdev"
	KERNEL=="hidraw", ATTRS{idVendor}=="ffff", ATTRS{idProduct}=="1f40", MODE:="666", GROUP="plugdev"
sudo reboot now
apt-get install nodejs git build-essential libudev-dev libusb-1.0-0-dev
sudo npm install n -g
sudo npm install yarn -g
sudo n 8.12.0
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
git clone https://github.com/bitfocus/companion.git
cd companion
./tools/update.sh
npm run rpidist
cp ~/.config/companion/db ~/companion/
sudo nano /etc/rc.local
Add this to the bottom of the file
	/home/pi/companion/headless.js eth0
In the terminal, run `npm start --prefix /home/pi/companion`
Set the GUI to the eth0 IP address and change the port number to 8000
sudo reboot now

**Comment by jarodwsams** [comment]
I'm trying the following to see if I can resolve:

```bash
./tools/update.sh
./tools/build_writefile.sh
npm run rpidist
```

**Comment by haakonnessjoen** [comment]
Hi, this is a known bug. It is just a temporary bug that happens when companion is too busy doing other stuff some times when saving the config. It's a tiny emberrasing timing issue that has come back after last fix of it ;P I will look at it!

**Comment by WNTLtd** [comment]
I'm still getting this bug - 
![Screenshot 2020-04-28 at 11 31 46](https://user-images.githubusercontent.com/52933483/80477521-f7b6fc00-8943-11ea-85c3-fc16ffb2bf3b.png)

**Comment by jarodwsams** [comment]
> I'm still getting this bug -
> ![Screenshot 2020-04-28 at 11 31 46](https://user-images.githubusercontent.com/52933483/80477521-f7b6fc00-8943-11ea-85c3-fc16ffb2bf3b.png)
> Using 2.0.0 ([e5637c1](https://github.com/bitfocus/companion/commit/e5637c1c74f50c7ea347398914ce85f2efb69c3e)-2282)

Does Companion function after that error happens?

**Comment by WNTLtd** [comment]
Yeah - all still works - just thought I'd let you know.
