### ISSUE TITLE
streamdeck XL support

### ISSUE THREAD

**Issue by theaterservice** [bitfocus/companion#680]
My streamdeck XL is not recognized with a usb rescan
The buttons apear in the streamdeck app on a 5x3 matrix as if it is a normal streamdeck

**Desktop (please complete the following information):**
windows 10 pro

**Comment by haakonnessjoen** [comment]
The XL will be supported in Companion 2.0 which is due to be released very soon!

**Comment by theaterservice** [comment]
Thx for the info. 
Would like to know if ‘soon’ is within one week. Otherwise i have to find another solution for the implematation of th xl in my festival lighting setup. 

Where can i request specific highend hog4 osc commands?

Grtz,
Pepijn

**Comment by haakonnessjoen** [comment]
You can do testing with 2.0.0-alpha from https://builds.bitfocus.io/companion/
