### ISSUE TITLE
Change in/output selection of other buttons after pressing

### ISSUE THREAD

**Issue by RVMediaCode** [bitfocus/companion#681]
**Describe the feature**
It would be great if it is possible to remap the source / destination of a button after pressing a button. So if 1 press destination 1, i go to a next page with my sources and all the buttons have as destination 1. Otherwise you need to make multiple pages per destination to be able to route your signals. 99 pages sounds a lot in 'normal'use but it's hard on a 40x40 router or 72x72

**Is this platform dependent (windows, mac, ..)?**
I think it's only dependent on your code and not the code of blackmagic

**If documentation is required to implement, do you know where to find it?**
Your own knowledge of this beautiful kind of software ! 

**Usecases**
To replace the basic routing of blackmagic. i can display my multiviewer outputs on a single page of the streamdeck xl. after clicking on it i'm able to select my assigned sources to route to that output. the sources are always the same on the button but it has different destinations every time.

**Comment by haakonnessjoen** [comment]
This is actually supported in the latest builds, if I understood your request correctly.

**Comment by rickverwaal** [comment]
> This is actually supported in the latest builds, if I understood your request correctly.

For the same button it's supported and works perfect! but it would be nice if I can update other buttons as well. so if I click button one there is some action and will also change the input of another button.

**Comment by haakonnessjoen** [comment]
We support having input and output buttons separately. So you click on a output, and then it shows you on the input buttons which input that is active on that output, and you can click on any input to change the routing of the last selected output.

Is this not what you want? Its just like any routing panel with input and outpt buttons separated.

**Comment by rickverwaal** [comment]
> We support having input and output buttons separately. So you click on a output, and then it shows you on the input buttons which input that is active on that output, and you can click on any input to change the routing of the last selected output.
> 
> Is this not what you want? Its just like any routing panel with input and outpt buttons separated.

Yes ! 

But also to have a 'virtual' source in companion.
I have 2 videohub routers (ASI and SDI). i would like to have a page per feed where a can define the most used handlings. The feed is going into router 1 and need to be switched to an output of that router to the device who's handeling the conversion. The output of that device is an input on router 2. after that i want to be able to send this signal to a monitor, audio meters etc with pre-configured buttons but the source of that buttons need to be changed based on which output device i have selected on router 1. 

In a short way:
if i make a crosspoint on router 1 to send a signal (feed 1) to output 10 ( also decoding device 10 ) i want as source of my button 'Send to monitor' input 10 ( the output of decoding device) on router 2. But when i send the signal to decoding device 11, the input of the 'Send to monitor' button needs to be input 11. Like a dynamic update of your buttons based on previous actions. 

Hope i've explained it better now :)

**Comment by krocheck** [comment]
Yeah, I'm still not following this.  I apologize!

**Comment by RVMediaCode** [comment]
We use 2 BM VideoHubs ( 1x ASI and 1x SDI )

we have an asi signal as input 1 on router 1. when I have multiple buttons ( input 1 to destination 1, input 1 to destination 2, etc.. ) and I press button in 1 to out 10, the signal is going to another device via output 10 of that router.

The output of that device is going to input 10 on my second router. ( this is the video router ).
I want to make a button that sends the signal to our monitor and audio meter ( in this case that will be input 10 ( the processed output ) to out 1 on the SECOND router ). 

But when I send the signal to OUT 11 on the FIRST router, the signal processed by another device between the router and will be inserted as IN 11 on my SECOND router.

When I do this, I want the same 'Audio / video Monitor button' to use input 11 to out 1 ( the monitor ) on my SECOND monitor and not the 'input 10 to output 1 ( on the second router)' like I used before.

So when pressing the button to make a cross point on my first router, I want to edit the source of the 'send to monitor' depending on my selection. a dynamic source/destination button and able to use a 'action' to change the source/destination of an other button.

**Comment by krocheck** [comment]
Ok.  I don't think this is going to be possible with the current structures:

1) This requires interaction between 2 instances
2) This requires an action to modify the options of an action in a bank
OR
We would need to have if-else logic capabilities when programming banks

All of these we're not setup for at the moment.  This is less of a Videohub specific request and more for the above core features.

**Comment by Julusian** [comment]
I think that with customvariables this could now be done with a minor change in the videohub module.
each of the buttons that perform the routing on the first router could also set a custom variable to that output number.
Then the 'send to monitor' button could use that variable (once the videohub module supports reading from variables) as the source to route to output 1.

Closing this as I think this is something for the videohub module. If you are still interested in the feature please open an issue there
