### ISSUE TITLE
[Request] Blackmagic Videohub | Implementation of a take button

### ISSUE THREAD

**Issue by RVMediaCode** [bitfocus/companion#682]
**Describe the feature**
as a addon on my previous request ( new option of video routing ) i would like to see a take button to prevent switching wrong signals to outputs. Make it a bit monkey proof to do another action to confirm your routing.

**Is this platform dependent (windows, mac, ..)?**
Think it's all in your own code ?

**Usecases**
To add another step when switching the video matrix.

**Comment by krocheck** [comment]
Potentially ... but there are 2 behaviors we could move towards:
1) BMD method of only one route in 'take queue' and defining a different route clears the previous
2) Big-iron router method of allowing multiple route changes to be stacked in the 'take queue', effectively an on-the-fly salvo.

**Comment by RVMediaCode** [comment]
It doesn't have to be a queue. after pressing a button with source/destination it would be nice as a 'security monkey proof layer' to have a 'take' button as the actual routing.

**Comment by krocheck** [comment]
![image](https://user-images.githubusercontent.com/749812/59470272-d0734100-8dfc-11e9-9996-e0a4bb8af894.png)

This has not been added to the alpha 2.0.0 yet, but it is implemented and tested.
