### ISSUE TITLE
Rendering on XL scales poorly

### ISSUE THREAD

**Issue by willosof** [bitfocus/companion#687]
Håkon has a plan to improve this

**Comment by silid** [comment]
This is looking much better in 2.0.0 (b6fc4d5) - has it been fixed?

**Comment by haakonnessjoen** [comment]
Only temporary. The current solution cannot be used because of licensing issues.

**Comment by mikekoenigs** [comment]
https://drive.google.com/file/d/10O_vs6ASmy2PY4IDfn2b8IRzkaYxTGTT/view?usp=drivesdk

I'm using StreamDeck XL and companion v1.4 and v2.0 latest beta.
Rendering has been screwed up for the month I've been using the product.

Any news on when this might be fixed?
Attached is a screen shot showing both StreamDeck and Companion.

Version 1.4 doesn't allow me to configure the entire XL workspace.
I'm assuming everyone already knows that...
Haven't managed to wade through all the pages of bugs.

**Comment by Julusian** [comment]
@mikekoenigs your problem is that the plugin does not support the 2.0 builds yet (see https://github.com/bitfocus/companion/issues/688), and is not related to this issue

**Comment by Julusian** [comment]
@haakonnessjoen is there a plan for what to use instead of sharp?

sharp is causing an issue https://github.com/bitfocus/companion/issues/958, but I don't want to write a fix until the scaling library is changed as simply changing that could resolve it

**Comment by haakonnessjoen** [comment]
Not figured out what to do yet. So unless we find a nice lib, I will probably either do the ugly upscale, or center-crop it, like I did on the mini earlier.

But I am open for tips. I am afraid doing real/pretty upscaling would be too cpu intensive to do in js. Maybe we need to do a simple c binding module with a somewhat optimized image scaler. Or find a c/c++ library that has the right license, and make a module for that.

**Comment by silid** [comment]
What is the licensing issue? There are other Apache Licence components included.

**Comment by haakonnessjoen** [comment]
libvips used by sharp is lgpl, and hence cannot be included in companion binaries

**Comment by Julusian** [comment]
yeah. sharp really does not make it obvious that its internals are lgpl. Its not really a problem in normal node though as it all contained within a sharp.node file on disk. But electon bundles that up, making compliance harder.

one thought I had yesterday is that for the opensource companion, the binaries could be distributed under lgpl/gpl. I think there simply has to be a reasonable way to get the sourcecode to be compliant with that.
That wont work for any closed source companion builds/forks though, but I don't know if that will be a problem for 2.0?

Otherwise, a simple c++ scaling library might be the way to go.

**Comment by jackcrombie** [comment]
Has anyone tried prioritising the XL res and rendering for that, and seeing how the previous scaling method transfers to the 15 button SD?

**Comment by Julusian** [comment]
@jackcrombie I think the previous algorithm was to double some pixels, which if done the way you propose would result in pixels being skipped instead which would make some lines disappear and likely result in something unreadable.

**Comment by willosof** [comment]
What do we do about this if we want to release this week?

**Comment by Turnipisum** [comment]
Can this not be put on bountysource?

**Comment by haakonnessjoen** [comment]
Or do as julian proposed about companion binaries.

**Comment by silid** [comment]
Is shipping in an Electron binary really that different to bundling in a self extracting zip?
The sharp binary is extracted from an archive when used - it isn't compiled into the running application.

**Comment by Julusian** [comment]
@silid I don't feel I understand the requirements of the licenses well enough for that, but  as the sharp.node and various dlls are in fact preserved inside the asar, I suppose it becomes a question of if them being embedded there adding another hurdle to modify is ok. I would assume so, as that is just how electron works so is a pretty common thing, and the tools to open it up and make changes are readily available.

Other than that it would appear to simply require some visible acknowledgement of the lgpl component and its license.
So I don't think the licensing of companion needs to change in any way (ignore what I suggested before about distributing under lgpl/gpl), just some visibly acknowledgement of sharp.
