### ISSUE TITLE
Stream Deck plugin and its support needs to be updated in 2.0

### ISSUE THREAD

**Issue by willosof** [bitfocus/companion#688]

**Comment by haakonnessjoen** [comment]
90% done

**Comment by jwbosch** [comment]
> 90% done

That's half a year gone by. For future purpose map the buttons in x,y matrix style instead of numbering through. Making the keymap transparant for different SD versions (and compatible for a XXL version ;-)).

**Comment by haakonnessjoen** [comment]
Just for historic reasons: This is working in the current version of Companion and stream deck plugin.
