### ISSUE TITLE
RPi: Cannot install after install commands changed

### ISSUE THREAD

**Issue by jarodwsams** [bitfocus/companion#689]
**Describe the bug**
Testing the installation of 1.3 as part of updating documentation/raspberrypi.md installation instructions. Was advised that some of the commands had been updated from npm to yarn. After this change, I am unable to build Companion.

Error text attached.
[yarn_rpidist_logging.txt](https://github.com/bitfocus/companion/files/3270454/yarn_rpidist_logging.txt)

**To Reproduce**
1. Go to https://github.com/jarodwsams/companion/blob/master/documentation/raspberrypi.md and follow the installation instructions up to item 7 in the "Common Installation Steps" section.
2. Execute the following commands:
```bash
git clone https://github.com/bitfocus/companion.git
cd companion
yarn update
```
3. Run `yarn rpidist`
4. Observe error on build.

**Expected behavior**
Companion should be built without error using the `yarn rpidist` command

**Screenshots**
![2019-06-09-221743_1920x1080_scrot](https://user-images.githubusercontent.com/22972834/59170526-b25bc700-8b04-11e9-9691-f3d91e73f958.png)
![2019-06-09-221822_1920x1080_scrot](https://user-images.githubusercontent.com/22972834/59170530-b4258a80-8b04-11e9-92e5-0381ab8addba.png)

**Desktop (please complete the following information):**
 - OS: Raspbian OS
 - Browser: N/A
 - Version: Companion 1.3

**Additional context**
I tried running the older `npm run rpidist` to see if that would work, but it did not. I received a similar error.

**Comment by haakonnessjoen** [comment]
Try `sudo apt install libudev-dev` before building companion

**Comment by jarodwsams** [comment]
> Try `sudo apt install libudev-dev` before building companion

Trying it now. Will confirm soon as it's done.

**Comment by jarodwsams** [comment]
Also, libudev-dev should've already been installed per the installation steps (https://github.com/jarodwsams/companion/blob/master/documentation/raspberrypi.md). I'm trying it all over from scratch; perhaps I missed a step somewhere.

**Comment by jarodwsams** [comment]
Confirming libudev-dev is installed with version 232-25+deb9u11
Moving on to `yarn rpidist`

**Comment by jarodwsams** [comment]
![2019-06-10-095523_1920x1080_scrot](https://user-images.githubusercontent.com/22972834/59204670-bb7d8000-8b66-11e9-8864-0e3d645ea438.png)

![2019-06-10-095535_1920x1080_scrot](https://user-images.githubusercontent.com/22972834/59204675-bcaead00-8b66-11e9-8294-b7a1caf25875.png)

**Comment by jarodwsams** [comment]
Just saw a line in that output about CMAKE not being installed. Installed and trying again.

**Comment by jarodwsams** [comment]
Built completed without error. Adding `cmake` to the required packages in the updated installation instructions. Closing this issue.
