### ISSUE TITLE
Support for Waves Emotion LV1 Software

### ISSUE THREAD

**Issue by johnwjames** [bitfocus/companion#690]
I would love to use the stream deck to control mute group and user define buttons.

**Is this platform dependent. No

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by JeffreyDavidsz** [comment]
When you can provide some more information (as requested in the template, feel free to issue a request again
