### ISSUE TITLE
Changing between V2 and 1.3 causes configuration issues on standard Streamdeck

### ISSUE THREAD

**Issue by matt-hand** [bitfocus/companion#693]
Just ran the newest bleeding edge build on my standard Streamdeck and it caused buttons to shift into the wrong spots. Went back to the 1.3 bleeding edge build and problem is not remedied. Need to go back and remap buttons in order to fix the situation and found that it may be best to stay on 2.0 to make buttons function.

Understand this is bleeding edge so may be resolved in final.

**Comment by haakonnessjoen** [comment]
Make sure you back up your db file before running 2.0.0-alpha. It will rearrange your buttons to fit the new 32 keys layout.

If your buttons are not the places they should be, I would think you are using the stream deck native application. And that plugin is not upgraded for 2.0 yet.

OR is this issue present in plain companion with standard stream deck connected directly to companion? Maybe you could show some screen shots before/after, etc?

**Comment by matt-hand** [comment]
Will take a look tomorrow. I am on location later today and will try with a new install. Thanks for the fantastic work on this.
