### ISSUE TITLE
[Request] Resolume Avenue

### ISSUE THREAD

**Issue by EnerGiehl** [bitfocus/companion#696]
**Describe the feature**
To Control Resolume Avenue with Companion/Streamdeck. Should be the same as the Arena Module?!

**Is this platform dependent (windows, mac, ..)?**
No

**Usecases**
Instead of buying a Midi contol. You Couleur also think about previewing the Videoclips on Streamdeck Buttons 🤔

**Comment by JeffreyDavidsz** [comment]
Do you have controlling info? When you do please create an issue
