### ISSUE TITLE
Allen and heath Dlive 

### ISSUE THREAD

**Issue by benbenbenben4-boop** [bitfocus/companion#698]
**Describe the feature**
Audio mixing console

**Is this platform dependent (windows, mac, ..)?**
nope its not dependant on windows,mac or pi

**If documentation is required to implement, do you know where to find it?**
https://www.allen-heath.com/media/dLive-MIDI-TCP-Protocol-1.50.pdf

**Usecases**
the smallest console is perfect for flying, but it means you have a lack of buttons that are normally on the consoles surface

**Comment by JeffreyDavidsz** [comment]
There is a Dlive module, just not been able to test it against a mixer
