### ISSUE TITLE
Companion 2.0 button Bug

### ISSUE THREAD

**Issue by RayVerProductions** [bitfocus/companion#704]
Hello,

I used companion 2.0 with a 15 button streamdeck parrallel with an 32 button one and tested some things at a job with a Ascender 32 4k and panasonic Camera's.
What I found out is that the following buttons (2.4-2.12-2.20) sometimes get active or losing their commands on the 32 button streamdeck. But on the 15 button one it is still working. I moved these programmed buttons towards other places where I can see them as well on the 15 button streamdeck and the problem is gone. So it looks likes that vertical row is giving some weird problems.

**Comment by haakonnessjoen** [comment]
There was another user that had similar problems. But he could replicate the problems also in stream deck application, without companion. So it might be a hardware problem.

Could you check if this is the case with yours too?

**Comment by nurvee** [comment]
This is a hardware issue. I have the exact same problem. The buttons are always in the state of being pressed down.  I contacted Elgato and after a day of sending them proof of the problem, they’re sending me a replacement XL.  Hope this helps.

**Comment by RayVerProductions** [comment]
I checked it with the Elgato software and as you said, the problem with that row of buttons is also there. So I need to get in contact with Elgato to replace mine Streamdeck.
@ Nurvee, did you call or Email Elgato about this? Or did you contact Corsair? 
Do you have contact details for me? THNX

**Comment by nurvee** [comment]
Each support ticket came from these emails:
support@elgato.desk-mail.com
desk@elgato.com

The support team is on Pacific Time, FYI.

**Comment by haakonnessjoen** [comment]
Hardware issue
