### ISSUE TITLE
JavaScript Error loading 2.0.0 1639 on OSX

### ISSUE THREAD

**Issue by AZJAYNES** [bitfocus/companion#705]
- OS: OSx 10.14.5
 - Version: companion-2.0.0-2fd9064-1639-osx.zip

tried opening latest bata and its throwing a java error 
![Screen Shot 2019-06-14 at 10 18 14 PM](https://user-images.githubusercontent.com/51722071/59545884-5376c300-8ef3-11e9-8962-00995e0dd13f.png)

**Comment by RVMediaCode** [comment]
Any Update about this issue ? i have it also on the latest versions.

**Comment by willosof** [comment]
Fixed in #ee7c35f

**Comment by willosof** [comment]
Build 1649 works :)
