### ISSUE TITLE
Button Appears Latched in 2.0

### ISSUE THREAD

**Issue by DiakonTV** [bitfocus/companion#706]
Companion 2.0 Build 1609

**Describe the bug**
When a button is created on the Stream Deck XL, it show a latched state, yellow bar at the top of the button when pushed.  Stays "latched" once pushed additional times.  Latch box is not checked.

Entering a delay of 100 MS or more, corrects the issue.

**To Reproduce**
Create button in Companion 2.0 Build 1609.  

**Expected behavior**
Button will not latch when pushed.

**Screenshots**
<img width="484" alt="Screen Shot 2019-06-15 at 2 58 01 PM" src="https://user-images.githubusercontent.com/50000729/59555278-faa03c80-8f7d-11e9-9069-7a19899e62b9.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.5
 - Browser Safari Version 12.1.1 (14607.2.6.1.1)

**Comment by haakonnessjoen** [comment]
Would the mentioned buttons have "change page" actions?

**Comment by DiakonTV** [comment]
Yes they would...

**Comment by haakonnessjoen** [comment]
Duplicate of #595 
We will fix this soon
