### ISSUE TITLE
QLab Module: Add option for specifying workspace

### ISSUE THREAD

**Issue by SoundGuyAndy** [bitfocus/companion#709]
The current implementation for commands in the QLab module use the default addressing of commands to the frontmost workspace in QLab. It would be useful if an option to address messages explicitly to a specific workspace were available. If enabled, it would simply prepend the existing command with:

/workspace/{WORKSPACE ID}

So, for example, instead of a Start command for cue 1 sending:
/cue/1/start

If the option were selected and, say, "My_Workspace.qlab4" were entered as the workspace to target, it would send:
/workspace/My_Workspace.qlab4/cue/1/start

I could see this implemented either on a per-action basis or, simply, as an option on the instance itself, and could easily argue for the merits of either way. Personally, I think doing it on the instance would be a lot simpler both on the implementation and use sides,  since you'd just need to add multiple instances for multiple workspaces, rather than having to enter a workspace for every single action you want to target a specific workspace.

**Comment by PerRoine** [comment]
I have implemented this on a pr instance basis now. will add a few presets before i release
