### ISSUE TITLE
Duplicate action

### ISSUE THREAD

**Issue by scoobiekw** [bitfocus/companion#712]
**Describe the feature**
When editing a button it would be helpful to make a copy of an action. 

**Usecases**
Creating router salvos would be easy if I could hit a copy button next to delete that duplicated that action. Then I would just need to edit it.

On large shows with many instances this can be tedious.

**Comment by josephdadams** [comment]
+1 on this.

**Comment by willosof** [comment]
A copy button alongside the delete button?

**Comment by josephdadams** [comment]
Yep. It would be really nice. :)

**Comment by DachsbauTV** [comment]
absolutely +1
and If possible I think it should be a copy/paste function instead of a duplicate, so you could even copy actions across buttons

**Comment by Julusian** [comment]
This will be possible in v3
#2127
