### ISSUE TITLE
Blackmagic Design Atem Instance Missing in 2.0.0 (8f6cb5e)

### ISSUE THREAD

**Issue by stuartdowdell** [bitfocus/companion#716]
**Describe the bug**
Blackmagic Design Atem instance is missing in version 2.0.0 (8f6cb5e)

**Screenshots**
Attached 

**Desktop (please complete the following information):**
 - OS: Mac 10.12.6
 - Browser Safari 12.0.3
 
<img width="1252" alt="Untitled" src="https://user-images.githubusercontent.com/52112494/59968359-94448c80-9530-11e9-82f6-1d61ad0994e6.png">

**Additional context**
Reverted to earlier 1.3 version, added ATEM instance , opened V2 but received Javascript error

**Comment by church-production** [comment]
Same problem here. 
As well on Mac but using chrome. 
Is there a known reason?

**Comment by krocheck** [comment]
Its a known issue, but hasn't been looked into thoroughly yet.  There's 9 modules that aren't loading due to dependency issues but it only presents in the distribution builds.

**Comment by matt-hand** [comment]
Greetings!

I just wanted to check in on the status on this as I would like to do some testing, but need ATEM support.

**Comment by krocheck** [comment]
Fixed
