### ISSUE TITLE
Kramer VS4x4HFS

### ISSUE THREAD

**Issue by simongroom112** [bitfocus/companion#720]
support for this Kramer switcher/matrix

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along
https://cdn.kramerav.com/web/downloads/manuals/vsm-4x4hfs.pdf
PROTOCOL 3000

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

Production switching

**Comment by EventReplay** [comment]
I'm familiar with the kramer protocol and more than happy to help with this.

I have created a basic test that appears to be sending correct commands but I do not have access to kramer hardware using P3000 to do any proper testing.

**Comment by simongroom112** [comment]
Thank you, 

How can I access this to test? I don’t have access to the equipment anymore but will do in the near future and will be able to test then  

Kind Regards
Simon Groom

**Comment by EventReplay** [comment]
At this stage you would probably have to create dev enviroment.
https://github.com/bitfocus/companion/wiki/Module-Development

If you are able to achieve this I will make files available on github, If not it would need to be accepted for inclusion in bleeding edge builds.

**Comment by EventReplay** [comment]
@simongroom112  I've contacted the creator of the existing companion kramer matrix module, he's been working on adding P3000 protocols to this module.

Testing has been completed and hopefully should be added to bleeding edge builds shortly.

**Comment by EventReplay** [comment]
Thanks to @Steve Therrien I can confirm the updated kramer matrix module is now included in the current bleeding edge builds.
Standard disclaimer this is an alpha and not recomended for a production enviroment!

You would need to use UDP protocol and the #ROUTE command.
It would be nice if you could give some user feedback as this model is a little different from a basic matrix.

**Comment by josephdadams** [comment]
Closing this as the module exists. Submit bug requests to that module repo directly as needed.
