### ISSUE TITLE
Companion Uninstalls itself when i open web gui.

### ISSUE THREAD

**Issue by Wilmshurst** [bitfocus/companion#721]
Hi Guys, i've had this bug for a while now.

i have confirmed this bug on 2 separate laptops, both running Win10 x64 Pro.
i even have a clean install of windows doing it straight away.

**Describe the bug**
Companion will launch, and i bind it to my interface (typically Ethernet).
I then click "Launch GUI"
Firefox opens (my default browser), and gets almost fully loaded.
then it will either freeze, or go grey with the window saying "Huston we have a problem".
from here i can refresh and or close and try to reopen companion.
The desktop shortcut then says that the file is missing

**To Reproduce**
1. Go to 'Companion'
2. Click on 'the icon'
3. Click Launch Gui
4. See it fail to load and crash.
5. Double click Companion again and it will say its uninstalled.

**Expected behavior**
The web interface should open

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10 x64 Pro
 - Browser: Firefox
 - Version: 67.0.4 (64-bit)

**Additional context**
I have this issue with version 1.3

I have recorded the process... its an mp4, and i zipped it up for upload here,

[companion bug.zip](https://github.com/bitfocus/companion/files/3332116/companion.bug.zip)

Interestingly enough i can re-install the software and use it on my streamdeck, so long as i dont ever try and open the web interface.

i wanted to post this issue months ago, but i waited till i could test on a fresh re-install of windows....

**Comment by Wilmshurst** [comment]
I have confirmed that i experience the same issue on version 1.2

i also was running netstat to see what ports were in use, while opening companion, i don't reliably see any port binding from companion.

i have tried Chrome and Edge also, the issue persists.

**Comment by Wilmshurst** [comment]
Update: it looks like Trend Micro worry free business is killing it,....

**Comment by Wilmshurst** [comment]
update.... despite white-listing everything everything relevant to companion, trend keeps flagging "Unauthorised file encryption" 

i white listed the exe, and the directories and etc....

This is a company laptop, and even our system admin cant get through trend, and 

and trend keeps deleting (renaming and removing- to quarantine it) it.

![behaviour monitoring](https://user-images.githubusercontent.com/48145340/60224593-6d86ad00-98c6-11e9-8dbb-265ddab81ed5.png)
![Uploading virus-malware.png…]()

**Comment by haakonnessjoen** [comment]
Hi, this is a "false positive" from the virus scanner. We are in the process of setting up "signing" of the executables, which will in theory solve this issue.

**Comment by Wilmshurst** [comment]
That would be amazing.

**Comment by haakonnessjoen** [comment]
In the mean time, you could help by following this:

https://success.trendmicro.com/solution/1115860-reporting-a-false-positive-issue-in-worry-free-business-security-wfbs#collapseTwo

You might not need to do the whole "decrypt with vsencode" part, if you just give them the url to download companion.

**Comment by haakonnessjoen** [comment]
Virus scanner false positives. Will be fixed when we start signing builds.
