### ISSUE TITLE
Ability to remove pages feature

### ISSUE THREAD

**Issue by jibberjabberish** [bitfocus/companion#723]
The default pages functionality is nice and all, but honestly, I would really like the ability to get rid of them and just use all of my buttons. I have a scenario where someone on stage will need to flip inputs (Blackmagic ATEM TVS) live (a Stream Deck will be connected to his laptop at the podium). I do not want him to accidentally flip to another page and get flustered on stage. Short of a full-on scripting system, the ability to just disable the default buttons would be good.

**Comment by scoobiekw** [comment]
V 2.0 allows you to clear page navigation buttons. or put them elsewhere.

**Comment by haakonnessjoen** [comment]
This is already solved in current development releases.
