### ISSUE TITLE
PVP3: Play/Pause Layer 

### ISSUE THREAD

**Issue by ajkazmie** [bitfocus/companion#724]
**Describe the feature**

Would it be possible to add a feature to PVP3 commands that would Play/Pause a layer?

**Is this platform dependent (windows, mac, ..)?**
mac

**If documentation is required to implement, do you know where to find it?**
N/A

**Usecases**
I need to be able to play/pause a certain layer with the push of a button.

**Comment by SteveTherrien** [comment]
PVP's API doesn't have a way of controlling a layer like that, so it's not something we can add to the module.

**Comment by ajkazmie** [comment]
Thanks for confirming, I'll move on to plan B.
