### ISSUE TITLE
Misspelling on buttons layout page

### ISSUE THREAD

**Issue by gabe927** [bitfocus/companion#735]
![image](https://user-images.githubusercontent.com/19437854/61249091-74187f80-a722-11e9-9d2a-7ce755fa7caa.png)
This is on the bleeding release for v2.0.
Pretty sure it's supposed to say "click"
Thanks!

P.S.  Love the program!  Been using it a lot for productions

**Comment by krocheck** [comment]
Fixed.  Glad you love it!
