### ISSUE TITLE
Module Request: Dataton Watchout Display Cluster

### ISSUE THREAD

**Issue by newgeppetto1966** [bitfocus/companion#738]
I would like to have the possibility to controll watchout display directly with companion.
this is possible with some command od WATCHOUT PRODUCER  but with port 3039.

FOR EXEMPLE TO RUN TIMELINE IN PRODUCTION IS:
run " IP PRODUCTION "  port 3040

For display IS:
run " IP DISPLAY " port 3040

Thanks

Paolino

**Describe the feature**
A clear and concise description of what the feature does

**Is this platform dependent (windows, mac, ..)?**
Explain

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by dnmeid** [comment]
The protocols for Watchout production and display cluster are quite similar with only a few differences. I put this request on my todos, but it will only be available in the 2.0 branch.

**Comment by matmar78** [comment]
hi, is it possible to add the display cluster control in a v1.4 release?

**Comment by JeffreyDavidsz** [comment]
If its not fully tested in 2.0. It will not be in 1.4, We want to make that one as stable as posible

**Comment by dnmeid** [comment]
done in 3366cfb8453f414ae20e9d9ff11931d2a53ebd68
