### ISSUE TITLE
Teamspeak

### ISSUE THREAD

**Issue by JKsmarthome** [bitfocus/companion#744]
**Describe the feature**
A clear and concise description of what the feature does

**Is this platform dependent (windows, mac, ..)?**
Explain

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by willosof** [comment]
Not enough information.

**Comment by ljjlong** [comment]
Hi Willosof,

Here is more information what we like to see. My college (JKsmarthome) has unfortunately no time for to give a reaction.

Teamspeak is a server based encrypted communication platform what also include a intercom like function. There is a app for Android and IOS what works as a client. Also serval client's applications for windows, mac linux. It is network based and works also over the internet. It is possible to run TeamSpeak on your own server (free) our on a external server (paid).

We like to see a client integration in Bitfocus companion for the intercom functions. So we can build our own intercom pannel with push to talk buttons. And volume changes for master audio level control and channel audio level control on the audio output. on an supported control surface. 

If this get intergraded in bitfocus companion we want build serval unit's with a raspberry pi, stream deck, and a USB headset. So we can use it in our multicam control room as intercom.

You can find more about TeamSpeak on https://www.teamspeak.com/en/
and on https://www.teamspeak.com/en/more/developers/ you can find the developer SDK

**Comment by Keksstar** [comment]
Should be opened again. Great idea :-)

**Comment by McHauge** [comment]
gues it got closed since the request, was not filled in, but what you are asking for is a TeamSpeak module to directly intergrade the main functions in companion, right?

**Comment by josephdadams** [comment]
It was closed because there are multiple requests for this. Go to the requests repo and go look at issues 72 and 73. Closing this again.
