### ISSUE TITLE
Internal Action: Button Release

### ISSUE THREAD

**Issue by IanTGreenwood** [bitfocus/companion#745]
**Describe the bug**
The internal button release action is either not working, or not working as I would expect.

i'm trying to make it untoggle a latched button when pressing another button. the button press action will toggle the button on/off, but i that doesn't exactly do what I want.

**To Reproduce**

1. Create a button 'A' with "latch" option set.
2. Create Button 'B' with internal action: button release targeting Button 'A' on current surface.
3. press button 'A' to unlatch it

**Expected behavior**
Button 'A' should unlatch.

If i set button 'b' to internal action: button press, it will unlatch a currently latched button.  but if the button was unlatched, button 'b' will latch it.

**Screenshots**
![image](https://user-images.githubusercontent.com/39915150/61670246-dc71de80-ac97-11e9-9ea3-4783e531f28d.png)

**Desktop (please complete the following information):**
 - Raspberry Pi 4 (Raspbian Buster)
 - Browser Chrome
 - Version [e.g. 22] = 2.0a updated 7/22/19 - unsure of build number.

**Additional context**

**Comment by josephdadams** [comment]
@istnv can this be closed?

**Comment by istnv** [comment]
@josephdadams yes
