### ISSUE TITLE
Enhancement: Instance configuration textfields should reflekt default value attribute

### ISSUE THREAD

**Issue by dnmeid** [bitfocus/companion#76]
Also in the instance/module configuration it should be possible to provide a default value in input textfields when creating a new instance.

**Comment by dnmeid** [comment]
How is this related? #76 is about the default value shown in a textfield, #49 is about tooltips shown additional to any input field when hovering over it.

**Comment by willosof** [comment]
Tooltips is not related. But default value and placeholder value is more or less the same!

**Comment by willosof** [comment]
@haakonnessjoen mentioned placeholder in #49, thats why I made a relating comment ;)

**Comment by dnmeid** [comment]
This has been fixed some time ago, I don't know exactly when but it is working now.
