### ISSUE TITLE
Certificate error on Companion start

### ISSUE THREAD

**Issue by jarodwsams** [bitfocus/companion#765]
**Describe the bug**
When starting Companion using headless.js, the console displays the error message
```problem with request: certificate is expired```

**To Reproduce**
1. On a linux-based build, add headless.js [interface] to your rc.local
2. Reboot the computer to trigger rc.local
3. See error

**Expected behavior**
Companion should start without any certificate errors

**Screenshots**
![IMG_20190801_201224](https://user-images.githubusercontent.com/22972834/62337099-d13d6080-b498-11e9-8e3b-2d29b3aa5f4c.jpg)

**Desktop (please complete the following information):**
 - OS: Raspbian Buster (Raspberry Pi 3 B+)
 - Browser: n/a
 - Version: browser version n/a

**Additional context**
 - Others have reported the same issue in the Companion Facebook group: https://www.facebook.com/groups/companion/permalink/2326980760853594/

**Comment by haakonnessjoen** [comment]
I will fix this. But this is just a warning. Companion works fine if you ignore the message for now.

**Comment by willosof** [comment]
Fixed, håkon?

**Comment by JeffreyDavidsz** [comment]
Haven't seen this anymore, did you fixed it @haakonnessjoen ?

**Comment by haakonnessjoen** [comment]
This was fixed!

**Comment by N8866U** [comment]
I'm having this problem right now, could this affect vireo listener commands?

**Comment by JeffreyDavidsz** [comment]
@N8866U nope it's the upgrade site that is not accessable

**Comment by willosof** [comment]
Update server?

**Comment by N8866U** [comment]
As soon as I start to app the first thing it prints in terminal is "problem with request: certificate has expired". 
I can also only send shell commands through vicreo hotkey listener. No other commands get sent.
