### ISSUE TITLE
Javascript error in the main process.

### ISSUE THREAD

**Issue by dv1sual** [bitfocus/companion#767]
Got this issue while opening two instances of Companion at the same time.

![Capture2](https://user-images.githubusercontent.com/53606943/62363071-4c912780-b516-11e9-9a38-c89c2225581c.JPG)

Companion Version: 2.0.0(172f989)

Steps to repro:

1. open an instance of Companion on localhost
2. I've connected OSC only on port 7401
3. open a second instance of it
4. you should get the notification

Running on Windows 10 Home Edition x64
Version: 10.0.17134

Java Version: 8 update 181 (build 1.8.0_181-b13)

**Comment by JeffreyDavidsz** [comment]
Just to be clear are you opening a second Companion? If you need an extra connection for the same instance like generic OSC, do that in the same Companion. The error should be saying something else though

**Comment by dv1sual** [comment]
I’ve opened companion for the second time for mistake, wasn’t intended. Nothing else except the screenshot appears. I already had two instance of OSC in the same companion.

**Comment by JeffreyDavidsz** [comment]
Thanks for the clarification. A message with "don't open more than once" should be better

**Comment by dv1sual** [comment]
Haha yes for sure!

**Comment by willosof** [comment]
I thought @haakonnessjoen made something that prevents companion from being opened twice?

**Comment by dv1sual** [comment]
Don't think it's related to this, but now when I start Companion (same version of this ticket) I can't see the window and in the task manager, I've  got 4 instances.

![Capture2](https://user-images.githubusercontent.com/53606943/63800869-fa6dd700-c906-11e9-9f49-c027fb913f4b.JPG)

**Comment by willosof** [comment]
Those are probably the forks for 
1) Main process
2) timer fix
3) device: emulator
4) device: your streamdeck?

@haakonnessjoen ??

**Comment by haakonnessjoen** [comment]
What william says is right. Also, electron has checks that should prevent more than one (actual) instance to run. I haven't tested this in windows lately. But I would have to do some testing.

But as far as the 4 instances in task manager, it sounds about right. If you disconnect/connect a stream deck device, the amount if instances in task manager should grow/shrink accordingly.

If the window is gone, try to look for the companion logo in your tray bar. It might just be hidden to the tray.

**Comment by dv1sual** [comment]
Hi @haakonnessjoen sorry for the delay and thanks for the help.
I've forgotten to check in the tray, so there is :)
For the 4 instances good to know, they are 4 even if I don't have anything plugged in.

**Comment by josephdadams** [comment]
@dv1sual are you still having this problem with the latest releases of 2.0?

**Comment by dv1sual** [comment]
Hi Joseph,

i didn't try yet, but i will do and let you know.
Thanks for checking!

*Luca Manzoni*
*IT. +39 3498987730*
*UK. +44 (0)7470882153*
*mail.  luca@lucamanzoni.com <luca@lucamanzoni.com>*
*__________________________*

__________________________

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Any review, retransmission, dissemination or other use of, or
taking of any action in reliance upon, this information by persons or
entities other than the intended recipient is prohibited. If you received
this in error, please contact the sender and delete the material from any
computer.

**Comment by dv1sual** [comment]
Hi Joseph,

the problem is still present in 2.0.0-afa5d3a-2004 release. I got a window
to say that there is another instance opened, and to close it before
running another one, but then the window with the JavaScript error came
after.
Please have a look at the file attached.
[image: Capture1.JPG]



*Luca Manzoni*
*IT. +39 3498987730*
*UK. +44 (0)7470882153*
*mail.  luca@lucamanzoni.com <luca@lucamanzoni.com>*
*__________________________*

__________________________

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Any review, retransmission, dissemination or other use of, or
taking of any action in reliance upon, this information by persons or
entities other than the intended recipient is prohibited. If you received
this in error, please contact the sender and delete the material from any
computer.

**Comment by josephdadams** [comment]
@dv1sual are you still experiencing this in the latest releases (either official release or betas)?
