### ISSUE TITLE
"Set Surface to Page" not functioning correctly. (In both 1.4 and 2.0)

### ISSUE THREAD

**Issue by officialmattsnyder** [bitfocus/companion#769]
**Describe the bug**
A "Set Surface to Page" action on key down will trigger the key up action of the corresponding button on the destination page. Set surface to page on key up will result in a Java error which crashes the program.

**To Reproduce**
1. Assign a button (e.g. 1.3) to perform a "Set Surface to Page" action on key down.
2. Assign the same button (e.g. 2.3) on the destination page a key up action.
3. Click on button 1.3 to set the surface to a new page
4. Button 2.3's key up action will trigger.

Alternatively:
1. Assign a button (e.g. 1.3) to perform a "Set Surface to Page" action on key up.
2. Click on button 1.3 to set the surface to a new page.
3. A Java error will occur.

**Expected behavior**
I would expect either of these to result in the surface being set to the specified page with no actions being triggered on the new page.

**Screenshots**
<img width="423" alt="Screen Shot 2019-08-01 at 12 38 08 PM" src="https://user-images.githubusercontent.com/50146619/62389972-304db480-b52f-11e9-9728-a891f341d9db.PNG">

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.5 (also on 10.14.6)
 - Browser: Chrome

**Additional context**
In previous versions (most 1.3 releases) Set Surface to Page on Key Up would function properly. But Set Surface to Page on Key down would leave the example button 1.3 latched and also trigger the up action on the new page. The latching seems to have been fixed, but the triggering on the new page has not.

**Comment by dnmeid** [comment]
I think the solution can be to add a new marker to all banks/buttons. After a page change all buttons are marked as fresh. A key up event for a fresh putton is not operated. A key down event is operated and the fresh marker is cleared. Care should be taken to distinguish between key down/up and bank press/release. Only key up of physical buttons should be ignored, not bank release commands received by OSC or TCP or whatsoever.

**Comment by josephdadams** [comment]
@istnv can we close this also?

**Comment by istnv** [comment]
Yes.
