### ISSUE TITLE
Request: Toggle buttons receiving a 'release' event turns off the button and triggers release actions.

### ISSUE THREAD

**Issue by Jehar** [bitfocus/companion#775]
**Observation**
Toggle buttons have press actions and release actions. However, using a release event on a toggle button in the on state has no effect. Toggles currently only change state on every other press event.

**Expectation**
When a toggle button receives a release event, the toggle switches to the released state and performs any release actions. This will allow other buttons to objectively set the state of the toggle button.

**Comment by PTGitHubber** [comment]
This was possibly put into the wrong request type. As it is possibly something wrong with the way that we expect things to be working with the software, you might get more traction on this by submitting it as a bug report instead of a feature request.

I did find the same thing as you. When setting an internal action button to release a toggle button, the internal button does not affect the toggled button in any way. Tested with a Toggle to Arm/Disarm cues in QLab and an internal button set to release said Toggle.

**Comment by willosof** [comment]
So, you only want the actions to be sent if it's latched, right? And no actions when you release a unlatched button?

**Comment by dnmeid** [comment]
I hated this toggle functionality from the first day it was there. It is a dirty hack and it was clear that it would cause lot of problems and support issues. To support propper toggle functionality we need much more. A first step would be to separate physical button press from bank state.
Then the usual interaction between a button and a toggle bank would be:
- Button press activates bank when off, next button release does nothing
- Button release deactivates bank when on
- API "down" activates bank when off
- API "up" deactivates bank when on
The down or up actions should only be fired if the bank really changes its state.

**Comment by istnv** [comment]
Wish me luck, I'm diving into this one. It looks like the same bug that causes #745.
@dnmeid has the right idea, and should result in physical or API actions working as expected.

Current flow ignores the release on latching buttons, using only the press action to toggle on/off.  "Push on" then "Push off" seems to work as expected, but it ends up ignoring button-release actions from the API.

I need this, for example, an 8 channel audio mixer: create 8 latch buttons, one 'solo' for each channel. (this could also be a channel 'hilite' on a light board)
An extra button to 'clear solos'  should unlatch those buttons currently 'down' without affecting those that aren't.

**Comment by josephdadams** [comment]
@istnv can this be closed?

**Comment by istnv** [comment]
@josephdadams yes
