### ISSUE TITLE
Remove Up and Down arrows

### ISSUE THREAD

**Issue by CoBot3000** [bitfocus/companion#777]
**Describe the feature**
Being able to use the stream deck with only one page would be helpful.
So being able to reclaim those three buttons that are being used for pages up, down and name. 
- People, during setup, can go to settings and turn off arrows.  (in result gain 3 programmable buttons)
- Instead of having only 12 programmable buttons we will now have 15. 

**Is this platform dependent (windows, mac, ..)?**
No

**Usecases**
When you only one to use one page with all its buttons this is very helpful. We don't want to use 2 pages to do something we can do on one page. 

Due to volunteers using this equipment. Having other random buttons like arrows is just a distraction and un-unnecessary

**Comment by scoobiekw** [comment]
This is a feature of the 2.0 release in currently alpha.

**Comment by CoBot3000** [comment]
Ah awesome.. Well I guess we just wait then :) 
Any idea the ETA? 

Thanks for your reply

**Comment by dnmeid** [comment]
Closing this one because there are just too many issues asking exact the same and it is already done.
