### ISSUE TITLE
Visual Guide in GUI for Different StreamDeck Models

### ISSUE THREAD

**Issue by PTGitHubber** [bitfocus/companion#782]
**Describe the feature**
A simple rectangle around the buttons used by each of the smaller StreamDeck models when programming in Companion v2.0 or higher, as a reminder of button limitations when programming for StreamDeck Mini or the original StreamDeck

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
I am unaware of any documentation for this.

**Usecases**
I believe that this would be helpful for those new to programming in Companion, as they would be able to see the constraints of the device that they are programming for.

It would also help those with multiple StreamDeck versions, to serve as a reminder of the constraints of each version. Especially since in 2.0 and higher, we the ability to use the far left column as something other than page switching buttons, having that visual guide would be a great help.

The image is just a mock-up of what this could look like, with the constraints of the StreamDeck Mini shown on the regular size StreamDeck. I know that if the guide were in place with Companion 1.4 and below, the actual buttons in use for a StreamDeck mini would be only the top left 4, but this is just meant to serve as an example of the type of visual guide to which I'm referring.
![Screen Shot 2019-08-11 at 11 34 23](https://user-images.githubusercontent.com/40829374/62828635-aab4bd80-bc2e-11e9-8109-a0a2c5b30009.png)

**Comment by dnmeid** [comment]
I added a darker background color to show the different streamdeck sizes. Not the prettiest thing but functional.
