### ISSUE TITLE
Module Request: Worship Extreme

### ISSUE THREAD

**Issue by Jcaithness89** [bitfocus/companion#783]
**Describe the feature**
Map streamdeck keys to specific Cue in current Cue List

**Is this platform dependent (windows, mac, ..)?**
Yes, Worship Extreme works on Mac and Windows.

**If documentation is required to implement, do you know where to find it?**
https://www.worshipextreme.com/contact

**Usecases**
I am requesting this because this will allow to switch between cues and also switch lighting cue based on the button pressed.

**Comment by JeffreyDavidsz** [comment]
It would be helpful if there is a link to an API.

**Comment by Jcaithness89** [comment]
Hi Jeffrey,
I tried searching for it and I don't think the API is publicly available. If this is not possible without the API, that is fine. I am not familiar with how this works.

Thank you

**Comment by JeffreyDavidsz** [comment]
Well we need something to work from ;-) or it would be reversed engineering.
I'll close this topic. Feel free to open a new one when you have some info
