### ISSUE TITLE
stream deck xl

### ISSUE THREAD

**Issue by Dennisvanhoek** [bitfocus/companion#785]
We would like to control the ATEM 4ME with a stream deck XL
Now Streamdeck XL is not supported by companion. 

Stream deck XL has to control the ATEM system by companion with an independed platform like windows or MAC

 Because we need to have 19 buttons to control the AUX of the ATEM, we want to use the Streamdeck XL and not the Stream deck  regular. 
Hopefully anybody can help us with this feature request.

**Comment by McHauge** [comment]
As far as I know, if you look at the Companion 2.0.0 beta build. Then the stream deck XL is supported, but this is not recommended for production use just yet.

**Comment by monoxane** [comment]
Can you guys read and/or search a bit first? the XL is supported in the 2.0.0 beta and will be supported going forward, https://github.com/bitfocus/companion/issues/680
