### ISSUE TITLE
Companion Admin not pulling up on computers on same network

### ISSUE THREAD

**Issue by Cmillets** [bitfocus/companion#791]
Companion Admin will not pull up on my two OTHER macs(with google Chrome). Up until a few weeks ago I was able to pull up Companion Admin on different macs now I'm getting this message 

Error: ENOENT: no such file or directory, open '/var/folders/5_/4ttklpr961xcylymcc559qxw0000gn/T/.companion.bitfocus.no.CN8pAQ'

*Note I also attempted in Safari and was STILL unsuccessful 
![Screen Shot 2019-08-18 at 6 33 24 AM](https://user-images.githubusercontent.com/48162499/63223361-2dcf9980-c182-11e9-8694-86396a902abb.png)

**Comment by cxselph** [comment]
It will work again if you close and reopen companion. Its a known issue. This only seems to show up for people that like to leave it up 24/7 in a fixed install. I will close and open it once a week so It doesnt happen when I need it.

**Comment by JeffreyDavidsz** [comment]
Duplicate
