### ISSUE TITLE
1.4.0 blocker: Surfaces freezing when editing buttons (when multiple streamdecks connected)

### ISSUE THREAD

**Issue by willosof** [bitfocus/companion#797]
1. Connected two normal stream decks
2. use this config https://fil.email/VKd9vLd7 (lasts 1 week)
3. change the "VB 16/9 + go" button 
4. try to use the surfaces... change page or whatever.

W

**Comment by JeffreyDavidsz** [comment]
I've tested this with your config and a E2 connected. No issues with 2 desk's...

**Comment by haakonnessjoen** [comment]
Reopen if found reproducible
