### ISSUE TITLE
Bug: Shift + click does not work

### ISSUE THREAD

**Issue by haakonnessjoen** [bitfocus/companion#799]
Bug: Shift + click on buttons for running actions does not work in the new 2.0 UI.

**Comment by krocheck** [comment]
🤦‍♂ I noticed this but thought it was intentionally removed.  My bad.

**Comment by dnmeid** [comment]
William commented it out in 743898efdb9119e475798eec6d3ed1904806830e
I guess it is work in progress

**Comment by dnmeid** [comment]
I reenabeled hot-buttons in a5dc6b2e764126d3e9d0ed4e5bdc6a7df07e562d
Don't know if this introduces some other bugs, I just tested briefly. Please check and close issue if no problems found.
