### ISSUE TITLE
There should be a way to differentiate between multiple instances of the same module, in the action dropdown

### ISSUE THREAD

**Issue by PerRoine** [bitfocus/companion#81]
**Describe the feature**
automatic enumeration or label that is shown in the action dropdown in the button config 

**Usecases**
When using multiple instances of the same module, you need to know which one you are selecting the action for.
I.E  "Main" & "Backup" label of 2 instances of Qlab. As it is now there is no good way to know which is which

**Comment by willosof** [comment]
There already is. You name your instance, and it shows up in the action list. 
<img width="939" alt="screen shot 2018-06-10 at 21 34 06" src="https://user-images.githubusercontent.com/426386/41205568-0ddae79c-6cf6-11e8-8ce7-4ff5917f8c4a.png">

**Comment by willosof** [comment]
<img width="795" alt="screen shot 2018-06-10 at 21 35 18" src="https://user-images.githubusercontent.com/426386/41205574-33ca6252-6cf6-11e8-874d-bb0b547c1802.png">
<img width="616" alt="screen shot 2018-06-10 at 21 35 10" src="https://user-images.githubusercontent.com/426386/41205575-3771f366-6cf6-11e8-8027-37951f5fb01f.png">
