### ISSUE TITLE
Mixing Companion buttons on Stream Deck Causes issues

### ISSUE THREAD

**Issue by geekazine** [bitfocus/companion#821]
v. 1.4.0 - tried with 2.0.0 and it did the same thing
Windows version. 

I have a Stream Deck XL, which I use 1.4.0 on I set up the first 15 buttons to Companion, and the rest as local buttons to control my main machine. 

I was on travel this week, so I used my 15 button Stream Deck. I figured I could use the bottom row of the SD for Companion buttons, and the top 2 rows to control my main machine. With the bottom row, I could use page 99, which I didn't have anything assigned. 

However, Companion would go errant, changing buttons, and mix-matching the companion pages. One button could be 1.3, another could be 59.5. If I press the down button, all the buttons would randomly change again.

**Comment by pepeflores2003** [comment]
I have the same problem..

**Comment by JeffreyDavidsz** [comment]
Im closing this, use 2.0 with the xl and when using Streamdeck software at the same time, use the plug-in (which is not ready for the xl). If by accident other config work, you are lucky.
