### ISSUE TITLE
./tools/update.sh - Not wotking

### ISSUE THREAD

**Issue by McHauge** [bitfocus/companion#822]
**Describe the bug**
When i run ./tools/update.sh in WSL on Windows 10 it fails, not sure if this is a bug with companion or some change on m system (ie maybe a win update)

**To Reproduce**
Steps to reproduce the behaviour:
1. Set up win10 dev environment
2. Clone companion on C: drive
2. run ./tools/update.sh
3. receive error WSL

**Expected behavior**
For it to run and update all the submodules

**Screenshots**
![image](https://user-images.githubusercontent.com/31018035/65043541-5bfbf100-d95b-11e9-8f36-66d6f3310715.png)

**Desktop (please complete the following information):**
 - Windows 10 Enterprice, Version 1803, Build 17134.1006 
 - WSL - Ubuntu 18.04 LTS

**Additional context**
Worked a month ago, but a lot has changed in that time

**Comment by JeffreyDavidsz** [comment]
Strange, just did a `git fetch` `git pull` and then a `./tools/update.sh` besides I need to stash a lot ;-) it works.

**Comment by McHauge** [comment]
are you also on windows? because then it's properly my system and not companion

**Comment by JeffreyDavidsz** [comment]
Yep I am

**Comment by McHauge** [comment]
Hmm

**Comment by McHauge** [comment]
got it to work now, had a file that could not merge, but I can update and compile once again
