### ISSUE TITLE
Bug on toggles

### ISSUE THREAD

**Issue by darkalester80** [bitfocus/companion#827]
Setting up a toggle to mute channels on my behringer xr18 air using an elgato stream deck. My current issue is when I press the key on the stream deck it isn’t acting as a toggle just a normal key on press and key off on release, but the function works fine on the web layout and on the test function when setting up the button. It even works on the stream deck emulator just fine it toggles on and off with each press just doesn’t do it on an actual stream deck.

**Comment by josephdadams** [comment]
Are you talking about latches?

Also, is the Elgato stream deck software running?

**Comment by darkalester80** [comment]
Yes latches l, and yes my stream deck app is running with the plugin for companion installed on it.

**Comment by mwsimmonite** [comment]
Hi all,

I'm having the same issue, works in the web layout and emulator, but doesn't toggle on the streamdeck itself.

In the debug log, when I push on the emulator it shows the button being pressed and released once, when I push on the stream deck it counts 4 'pressed' followed by 2 'released'??

If there's anything else I can supply to help figure it out let me know.

Thanks
<img width="333" alt="Screenshot 2020-02-18 at 16 19 44" src="https://user-images.githubusercontent.com/44989573/74755072-7ae41380-526a-11ea-8d9c-51ce5ca33a1e.png">

**Comment by mwsimmonite** [comment]
I've tested this some more, and the latch/toggle issue isn't limited to Behringer Xair buttons. Even a button with no function other than to 'latch' doesn't work on the physical stream deck, with the log showing 4 presses and 2 releases. 

I'm currently testing the latest version of 2.0

**Comment by mwsimmonite** [comment]
This works as expected with stream deck XL on current V1.4, with only one button press and release. I'm on MacOSX 10.15.3.

<img width="807" alt="Screenshot 2020-02-18 at 16 38 22" src="https://user-images.githubusercontent.com/44989573/74756812-14acc000-526d-11ea-9cf0-c77237b44374.png">

**Comment by istnv** [comment]
The elgato driver has issues with 2.0. 
That's probably where the multiple press inputs are coming from.
My patches were tested with mutes on my X18, #995 fixes a coding error that slipped through the updates I submitted last month.

**Comment by haakonnessjoen** [comment]
This should be fixed by #995 .
If not, reopen this issue please.
