### ISSUE TITLE
Support for modules with build step

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion#837]
**Describe the feature**
All the modules are written in vanilla javascript. It would be nice to be able to use certain technologies (eg babel/typescript) to get access to newer language features.
It is possible right now, but it is a bit of a hack and suboptimal. 

**Solutions**
I have some ideas for strategies that support this workflow, each with its own positives and negatives.

1) No/minimal change. Right now it is possible to do the build via the postinstall script. The minimal change would continue to do this.
1) Modules commit built code.
	Instead of building via postinstall, it could be required that modules commit the built code into their repo. This is more effort for the developer, but as they chose to use that workflow they should accept this extra this step.
	As part of this, companion should start installing only production dependencies for modules (`yarn --production`), as a minor buildtime optimisation
1) Proper lifecycle.
	Companion could be made aware that some modules need compiling, and can do a `yarn build` for those modules. This should probably be enabled by a field in package.json or some other lightweight way of checking.
	Comapanion should then either to a `yarn install`, `yarn build` or a `yarn install --production` depending on whether the module needs building
1) Restructure modules.
	Another solution would be to change modules to be imported via npm. But this would be more work for every module developed, and would not benefit them.

My preferred method is 3). As a module developer, that is closer to best practise. But I can see 2) or 1) as being preferable to the core developers as there is nothing for you to have to look after.
4), is a more standard way of working, but changes workflow so is a larger discussion that can be done later.

I'm expecting some discussion on this, and can do the work to implement whichever is concluded

**Is this platform dependent (windows, mac, ..)?**
No

**Usecases**
Being able to write modules and use babel/typescript to transpile.
eg https://github.com/bitfocus/companion-module-atem

**Comment by Julusian** [comment]
I made a bad assumption when writing this (I was not able to check it before now), so the current situation isnt as bad as I was expecting (devDependencies do get stripped out during electron bundling). The description is updated to reflect that

**Comment by dnmeid** [comment]
I'd go with suggestion 3 too for now.
For Companion 3.0 the whole module system has to be overhauled and should be more pluggable.

**Comment by Julusian** [comment]
This has been tackled in https://github.com/bitfocus/companion/tree/develop, as part of the module-api overhaul, packaging overhaul, and modules being run in their own threads/processes
