### ISSUE TITLE
Module Request: AV Playback

### ISSUE THREAD

**Issue by MrLazerface** [bitfocus/companion#84]
Module to support AV Playback via UDP or TCP.
AV Playback is a windows based alternative to Playback Pro, and adds additional functionality and features.

Features could include:
-Transport Control (Play, Pause, and Stop commands)
-Loading clips
-Goto End Times (60/30/20/10 seconds from end)
-Temporary Loop and Hold controls
-Playlist selection for running multiple playlists on one machine

Feedback
-None, as there is no feedback sent from AV Playback

See [this pdf](https://1drv.ms/b/s!AqMTrvaRiFJK_UOUHMlBgKPJj6R3) for external device control parameters in AV Playback.

**Comment by willosof** [comment]
First of all - I love the username 😁And, thanks, I bet @PerRoine will implement this in a matter of days ;) seems simple and straight forward. It's a shame about the feedback though.

**Comment by PerRoine** [comment]
Original poster have tested and confirms that all actions behave like they were expected to
