### ISSUE TITLE
Internal clock is not accurate

### ISSUE THREAD

**Issue by dnmeid** [bitfocus/companion#845]
**Describe the bug**
The variable for the internal clock sometimes misses a second.

**To Reproduce**
Look at the variable long enough.

**Expected behavior**
the variable should run in sync with the system clock

**Additional context**
the internal companion clock is controlled by a timer with 1000ms, but the accuracy of a timer is not good enough for that, so tometimes the interval is longer, sometimes shorter.
Thisl leads to some seconds shown twice or some skipped.

Additionally I'd prefer three variables: one for the hours, one for the minutes, one for the seconds. Gives more flexibility to the user.

**Comment by Julusian** [comment]
In 3.0 the clock is running at every 500ms, so it shouldnt skip anymore
