### ISSUE TITLE
Wi-Fi disconnects Streamdeck

### ISSUE THREAD

**Issue by bryce-seifert** [bitfocus/companion#846]
**Describe the bug**
When a computer running Companion on a LAN is connected to a Streamdeck (via USB extender), having the the Wi-Fi on intermediately disconnects the Streamdeck requiring a rescan.

**To Reproduce**
1. Have Companion on a wired LAN with static IP
2. Join a Wi-Fi network via DHCP
3. Connect a Streamdeck
4. After a variable amount of time, the Streamdeck will disconnect

**Expected behavior**
The Streamdeck stays connected regardless of other networks

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox, Safari, Chrome
 - Version 1.4, 1.3

**Additional context**
The Streamdeck is connected via a USB extender. However, both with and without the extender it disconnects only when also on a Wi-Fi network. Disabling the Wi-Fi connecting solves the issue.

**Comment by JeffreyDavidsz** [comment]
Feel this is a hardware related issue of the Mac. Do you have an other Mac to test on? I use wired and wifi all the time on my PC. Lan for control and wifi to get internet, but I'm on windows...

**Comment by haakonnessjoen** [comment]
I have never had any issue with stream deck and wifi on my mac. I think this might be a hardware issue with your mac, or that the usb stack on your mac os install is broken. I have never seen any other reports of thiss issue either, so I think we could close this issue, unless we have a way to reproduce this problem.

**Comment by josephdadams** [comment]
This really does sound like a hardware problem for you, @bryce-seifert. It could even be your stream deck. Do you have another deck or another Mac you can test on to see if the problem follows?

**Comment by bryce-seifert** [comment]
I'm going to wipe the machine and see if it persists.

**Comment by josephdadams** [comment]
@bryce-seifert how'd it go?

**Comment by josephdadams** [comment]
Closing. @bryce-seifert if you can reproduce this issue on other machines or stream decks, we can reopen the issue.
