### ISSUE TITLE
Request - Timecode generation 

### ISSUE THREAD

**Issue by Deanbau** [bitfocus/companion#85]
It would be amazing if Companion could generate and play out (via usb interface??) SMPTE timecode via 

http://x42.github.io/libltc/

**Comment by nltio** [comment]
I would say that this is somewhat out of scope for software like this. Perhaps just use companion to control another app to generate the timecode. If you're on a mac, use QLab. There will probably be solutions for other platforms.

**Comment by Deanbau** [comment]
This has been pretty much covered by #131
