### ISSUE TITLE
Enhancement: Make user configuration dynamically generated

### ISSUE THREAD

**Issue by haakonnessjoen** [bitfocus/companion#86]
A the moment, it takes a lot of time to add configuration options for user settings. It should be dynamically generated, like instance config and bank config, to ease the developers jobs :)

**Comment by krocheck** [comment]
I feel like this is almost moot with the React UI

**Comment by Julusian** [comment]
I agree.
In fact before the react-ui the bank style properties were defined from the bakend like this, but I decided it was simpler to have them hardcoded in the ui, now that the ui code was easier to edit
