### ISSUE TITLE
Nickname a Surface

### ISSUE THREAD

**Issue by alatteri** [bitfocus/companion#860]
It would be very helpful to be able to give a nickname to a surface.  When you have multiple stream decks, it is not convenient to keep track of them via serial number, and what the default page is set too.

[Screen Shot 2019-10-13 at 5.36.18 PM.pdf](https://github.com/bitfocus/companion/files/3722663/Screen.Shot.2019-10-13.at.5.36.18.PM.pdf)

**Comment by Julusian** [comment]
This is implemented in 2.2
