### ISSUE TITLE
Adding Multiple actions fails

### ISSUE THREAD

**Issue by Turnipisum** [bitfocus/companion#862]
**Describe the bug**
There seems to be a bug when trying to add multi actions. 

**To Reproduce**
i have to click to different page or button and then back again to the button i was configuring to add another action.

**Expected behavior**
Create a extra action for background colour.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [2.00 baf06f4]

**Additional context**
Stream deck XL

**Comment by willosof** [comment]
How can I reproduce this? This works fine on my machine.
