### ISSUE TITLE
Button Color Feedback

### ISSUE THREAD

**Issue by christophstone** [bitfocus/companion#864]
We use a stream deck with Companion 1.4.0. We control a Blackmagic ATEM ME / 1 via Mac. Everything works brilliantly. The video mixer responds to StreamDeck and the StreamDeck buttons get their Color feedback (Preview/Program) from the ATEM. When restarting Companion, the Color Feedback is gone. Only when the buttons are newly pulled over from the preset the connection is back. I have already tried the version 2.0, without success.

**Comment by krocheck** [comment]
Just leaving a note for our guys to not transfer this to ATEM repo.  This needs to be investigated as a core issue.

**Comment by willosof** [comment]
We'll make sure this works when we design in v3. Keeping it open for the v3 planning:)

**Comment by Julusian** [comment]
I am pretty sure this is a solved issue with dragging a preset not triggering a save of the feedbacks
