### ISSUE TITLE
Module Request: Christie Spyder X20 & X80

### ISSUE THREAD

**Issue by Turnipisum** [bitfocus/companion#87]
**Describe the feature**
Christie Spyder X20 & X80 Support
**Is this platform dependent (windows, mac, ..)?**

**If documentation is required to implement, do you know where to find it?**
This is what i use from stream deck .sh script. "echo -e "spyder\x00\x00\x00\x00RSC 0 1 S" | nc -w1 -cu 10.10.10.10 11116"

Page 14 onwards for protocol info
[OPERATION MANUAL, SPYDER,  REV 1.5.pdf](https://github.com/bitfocus/companion/files/2098046/OPERATION.MANUAL.SPYDER.REV.1.5.pdf)

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by PerRoine** [comment]
Had a quick look at the manual, Spyder seems easy enough to support is there specific commands you would like ? i saw there is some layer manipulation that might not be to relevant to have the companion control. Also it seems like there is no feedback in the protocol so it
 will be a one way street

**Comment by Turnipisum** [comment]
Recall of Command Keys & Function keys, Freeze layer/source, mix backgrounds. would cover it i think @PerRoine

**Comment by PerRoine** [comment]
Per Røine [4:01 PM]
Ok i will throw together a quick module and we can add commands later if needed this manual actually describes some responses as well which we can use later (edited)

**Comment by Turnipisum** [comment]
PNG for button.
![spyder_button](https://user-images.githubusercontent.com/23130067/41356918-dad5316c-6f1c-11e8-9481-84d73dd82152.png)

**Comment by PerRoine** [comment]
[020-102207-01-Christie-LIT-MAN-REF-Spyder-Commands.pdf](https://github.com/bitfocus/companion/files/2102675/020-102207-01-Christie-LIT-MAN-REF-Spyder-Commands.pdf)
this is the latest and greatest Spyder command reference

**Comment by PerRoine** [comment]
Module is made but need to be tested, we dont have a spyder available so if original poster could test it would be great

**Comment by Hitower78** [comment]
Hi
Whats "Take" ? The Spyder has no take function.

**Comment by haakonnessjoen** [comment]
It is "Advance to next cue", which someone uses as a "TAKE" button. Maybe we should rename it.

**Comment by PerRoine** [comment]
Has this module been tested OK ??

**Comment by dnmeid** [comment]
I have used the module last week without problems, closing the issue now. Thank you Per.

**Comment by dkviz** [comment]
Hello Per, sorry if this the wrong place to post. New to GitHub.
Would it be possible to add Recall of Network Commands to X80 Module?
Thx,
Ken
