### ISSUE TITLE
Howto add an internal clock (time of day) and other functions?

### ISSUE THREAD

**Issue by JayPiEs** [bitfocus/companion#870]
Is there the possibility to have a clock (analog or digital) with the time of day from the system?

And are there more interactive internal functions?

Does a howto exist for those functions?

**Comment by josephdadams** [comment]
@JayPiEs these are the current internal actions available in Companion:

- Enable or disable instance
- Set surface to page
- Trigger a device to lockout immediately
- Trigger a device to unlock immediately
- Run shell path (local)
- Trigger all devices to lockout immediately
- Trigger all devices to unlock immediately
- Increment page number
- Decrement page number
- Button press and release
- Button Press
- Button Release
- Button Text Color
- Button Background Color
- Rescan USB for devices
- Abort all delayed actions
- Kill companion
- Restart companion

These are all relatively self explanatory, but if you need help using them, let us know.

The request for a clock has been asked for in issue #389 and #845.

**Comment by JeffreyDavidsz** [comment]
If I remember correctly, a variable has been added some time ago. Need to check where but system time should be there

**Comment by istnv** [comment]
I think the host clock is in $(internal:time_hms) and $(internal:time_hm)

**Comment by josephdadams** [comment]
Confirmed, as @istnv said, so I'll close this since it is now answered. @JayPiEs let us know if you need anything else.

**Comment by JayPiEs** [comment]
> I think the host clock is in $(internal:time_hms) and $(internal:time_hm)

That is great! thank you

is it also possible to have the time in analog clock?

**Comment by josephdadams** [comment]
Not at this time.
