### ISSUE TITLE
Does companion meant to be used along with Streamdeck original buttons?

### ISSUE THREAD

**Issue by latinlifestyle** [bitfocus/companion#874]
Hi Guys, 
Sorry for the question but I couldn't find a correct way to use a Companion. 

1- That supposed to be used along with original streamdeck buttons? Because I noticed once I start to use with the original button things start to get very buggy, buttons does't change the page or disappear for a while, and appears again once press the empty button.
How about the spotify, website, and other functionalities can have it all from companion, to be honest I prefer the streamdeck folder system but with BM Atem functionality. How to work this out?

2- there is anyway to work work with folder system instead of pages?

Thanks a lot
I Appreciated

**Comment by josephdadams** [comment]
Companion 2.0 has the option of no page buttons on the surface. The plugin that makes the two software programs work together better is currently being redeveloped for 2.0. That should help with some bugs.

As far as Spotify and other controls, there are some methods that enable you to do this within Companion, mostly through triggering scripts via helper software like Vicreo Listener or Qlab or Octopus.

Does that help answer your questions?

**Comment by latinlifestyle** [comment]
Thanks for your reply @josephdadams After couple of hours and gathering some info throughout the forum I make it work. But I hope the version 2.0 come out soon.
For those are a bit lost here couple of info and can correct me if I'm wrong.

Yes Companion and Stream deck can work together with some bugs.
1- When your buttons start to disappear unplug and plug the usb. (you have to every time it starts win)
2-Once you set the buttons on companion, you can use the Companion Plugin Button to display it on Stream deck app.
3 - You can use the stream deck default buttons normally and you can put over the page buttons to have more space.
4- You can´t move the companion buttons on stream deck first page, but you can still create folders for stream deck default buttons.

I also noticed latched (toggle) sometimes doesn't work on streamdeck, but on virtual test works fine.

Thanks hope that save some of you time.

**Comment by josephdadams** [comment]
Glad you figured out what works best for you! Stay tuned for the updated plugin release.

**Comment by Emulga** [comment]
Is there an ETA for V2? I'm really looking forward to use my Streamdeck with the original app. Thanks!
