### ISSUE TITLE
"Flip counting" and "Show +/-" options creates extra Page Up button

### ISSUE THREAD

**Issue by bryce-seifert** [bitfocus/companion#878]
**Describe the bug**
If you Page Up/ Page Down buttons are in a non-standard placement, toggling either "Flip counting" or "Show +/-" will override the upper left button with a "Page Up" button.

**To Reproduce**
–Move your "Page Up" button to a button that is not x.1
–Go to the settings and Enable (or Disable) either "Flip counting" or "Show +/-"
–Go back to your page, and you will notice an additional Up button in the x.1 position.

**Expected behavior**
Settings does not replace button or create new up button, but instead modifies the Up button in its current spot.

**Screenshots**
[Screen capture of issue in action.](https://www.dropbox.com/s/xv20l58f1nsfajl/Screen%20Recording%202019-11-02%20at%2012.46.11%20PM.mov?dl=0)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 13.0.2

**Additional context**
This happens both if button x.1 is empty or if it has another button in it's place. So it will override actual buttons with actions as well.

**Comment by dnmeid** [comment]
Thanks for the find and reporting it. This bug is now fixed in 170de1711ae1ffe03bd9bb54a7e743542887420d
