### ISSUE TITLE
Module Request: VLC

### ISSUE THREAD

**Issue by MrLazerface** [bitfocus/companion#88]
**Describe the feature**
Remote control of the free VLC media player. VLC supports JSON/HTTP commands.

**Is this platform dependent (windows, mac, ..)?**
There are both windows and mac versions of VLC. I believe they respond the same to remote commands.

**Features to Include**
-Basic transport controls (Play/Pause/Stop)
-Loop/repeat
-Previous/Next Clip
-Fullscreen

**If documentation is required to implement, do you know where to find it?**
Please see this webpage for guidelines: https://wiki.videolan.org/VLC_HTTP_requests/ 
Additionally, this attached text file also lists the commands.
[README.txt](https://github.com/bitfocus/companion/files/2099122/README.txt)

**Usecases**
From time to time, due to client budgets, we have to use VLC to play videos instead of a dedicated video player or media server.  Having remote control of VLC would aid in operator sanity, and would help to make VLC into a pseudo-pro playback software.

**Comment by willosof** [comment]
Wow, VLC, really? :) Not QLab or other software that is free to use with basic functionality? But, sure, shouldn't be a problem to do. 👍

**Comment by MrLazerface** [comment]
I would love to use the Mac-only free or inexpensive apps, however 85%+ of our rental laptop inventory is all windows based. That and I dislike the direction Apple is taking with the mac ecosystem since the death of Steve Jobs. But that's a whole different story.

**Comment by PerRoine** [comment]
OK I made it and I will never ever use it, I think. Next / Prev actually plays next and  previous.  In my version of vlc 3.0.3 the http interface used port 8080 the documentation suggested 9090 so i guess it's not consistent.
