### ISSUE TITLE
Stumpfl Wings/Pixera Control

### ISSUE THREAD

**Issue by pateboyd** [bitfocus/companion#881]
Requesting a module for Stumpfl Wings/Pixera. The module has been developed from a fork, but need to be added to the build.

Here is a link to the fork.
https://github.com/bitfocus/companion-module-avstumpfl-wingsviosorx

Can this be added asap?

**Comment by dnmeid** [comment]
Not likely. This module looks like a stub. Missing help file, many functions are not working.
There is a working Pixera module contained in Companion relying on the JSON-API.
Closing this issue now, if you really want to go ahead with that module based on UDP, please make an issue in the repo of companion-module-avstumpfl-wingsviosorx and not here. Also feel free to discuss in the module-developer slack.

**Comment by pateboyd** [comment]
Can you direct me to the pixels module. I cannot find it in 1.4.

**Comment by dnmeid** [comment]
If it is not in 1.4 it hasn't been backported, ask @JeffreyDavidsz about it.
Bug reports and feature requests always relate to the most recent version.

**Comment by JeffreyDavidsz** [comment]
I can backport the module into 1.4 no problem

**Comment by JeffreyDavidsz** [comment]
Its in now
