### ISSUE TITLE
"unary operator expected" error

### ISSUE THREAD

**Issue by BrentS** [bitfocus/companion#885]
Hello--

I'm a newbie trying to follow your raspberry pi instructions but get the following error on the step "sudo npm install n -g"

pi@raspberrypi:~ $ sudo npm install n -g
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
/usr/local/bin/n -> /usr/local/lib/node_modules/n/bin/n
+ n@6.1.0
added 1 package from 4 contributors in 2.733s

and then received the following on the build step:

pi@raspberrypi:~/companion $ ./tools/build_writefile.sh
./tools/build_writefile.sh: line 54: [: !=: unary operator expected

**Comment by Julusian** [comment]
What version are you trying to build?

The raspberry pi instructions used to include the following, but it didnt look relevant anymore:

---

**1.4 RC1 Note:** 1.4 RC1 was inadvertently created with a syntax error in the `tools/build_writefile.sh` file we'll reference below. You will need to make a manual correction.<br>
Open tools/build_writefile.sh in the text editor of your choice.<br>
On line 54, you need to enclose `$(get_git_branch)` in quotation marks, so the line looks like this:<br>
`if [ "$(get_git_branch)" != "master" ]; then`<br>
Save the file, and then proceed.<br>

**Comment by BrentS** [comment]
I was trying to build 1.3.  Is the 1.4 RC1 note applicable to that build as well?

I've been starting with clean installs direct from raspberry pi each time first trying Raspbian Buster Lite then trying Raspbian Buster with desktop yet it doesn't work all the way through as the instructions describe.  Probably me lol.

**Comment by Julusian** [comment]
It looks like that note does apply to 1.3
I removed it assuming that it didn't, so if it works after that then let me know and I shall update it and add it back.

**Comment by jarodwsams** [comment]
@BrentS You actually _want_ to install 1.4, not 1.3. You can do that by following the recently-updated instructions here: https://github.com/bitfocus/companion/wiki/Manual-Install-on-Raspberry-Pi

1.4 has been patched to correct that error.

**Comment by BrentS** [comment]
Thank you!  All is working now!
