### ISSUE TITLE
[Bug / Missing support] New HW revision of streamdeck 15

### ISSUE THREAD

**Issue by McHauge** [bitfocus/companion#886]
**Describe the bug**
Seems Elgato has come out with a new revision on the HW/firmware on the stream deck 15.
some users have reported no function at all with both V1.3, V1,4 and V2.0 build.
And after a closer look, they are all using new or close to new hardware (after Sep 2019). 
And the model number on the unit is now `20GAA9902` and not `20GAA9901` as it is for older models.

Also a new driver notation for the unit: 

> HID\VID_0FD9&PID_006D\7&284dfd8a&2&0000

**To Reproduce**
1. Buy new unit (new stock unit)
2. Plug into pc
3. Nothing ...

**Expected behaviour**
To work like older units

**Desktop (please complete the following information):**
 - OS: Testet on win 7, win 10
 - Companion V1.3, V1.4, V2.0

**Comment by McHauge** [comment]
a link to the only document on google confirming something with the model number from Sep. 3 2019:
[https://www.elgato.com/sites/default/files/inline-files/Elgato_Stream_Deck_Declaration_of_Conformity_20190903_0.pdf](url)

**Comment by Julusian** [comment]
Trying a quick hack to use the existing elgato driver in companion with the new device makes the device detected, but it does not appear to function at all.

**Comment by haakonnessjoen** [comment]
We have contact with Elgato and will fix this soon :)
