### ISSUE TITLE
Enhancement: Action Drop Down List

### ISSUE THREAD

**Issue by IanTGreenwood** [bitfocus/companion#89]
**Describe the feature**
As more and more devices become supported and and added to your config, the Action drop down list is going to get very large.  This becomes quite cumbersome to scroll through.  This could be alleviated by creating two pull down lists, one for the Instance, the other for the Action.  

Alternatively a "filter" field at the top of the list might work as well.  For example, type "Watchout" and it would only show the commands from the instances that have "Watchout" in the name. 

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
N/A

**Usecases**
See above.

**Comment by willosof** [comment]
Noted! This is already thought out in my head(tm), It will more or less become a search field with related hits. :)

**Comment by willosof** [comment]
This is not fixed, but in #287 you can now search for the module you like, making it easier to find stuff you know we support :)

**Comment by josephdadams** [comment]
Consider #667 when implementing a fix for this (also #510), a way to limit action choices by instance config could be nice to make the UI simpler when setting up buttons.

**Comment by dnmeid** [comment]
Since we now have a searchable dropdown for the actions, can we close this or does people still want to have hierarchical dropdowns?

**Comment by MeestorX** [comment]
I would still love to see hierarchal. Choose the type of action, and see the actions that are of that group. It could even become "smart" and have "most used" actions at the top.

**Comment by Julusian** [comment]
I think this is solved now with #2014
