### ISSUE TITLE
OSC Style not refreshing buttons

### ISSUE THREAD

**Issue by boydnijsten** [bitfocus/companion#893]
I'm experiencing an issue when adjusting the style (Color and text) of a button via OSC. The button itself doesn't get updated, but when I open the button editor, I can see the new text or color.

1. Send a OSC command to companion like /style/text/1/1 "HelloWorld"
2. The button doesn't seem updated
3. Edit button 1 on page 1 (in this case)
4. You can see the updated text

**System**
 - OS: MacOS 10.15
 - Browser: Safari
 - Version 2.0.0 60a2aa5

**Comment by josephdadams** [comment]
Pretty sure I have seen this too - the color doesn't adjust on the actual stream deck but does in the interface. I'll confirm.

**Comment by phuvf** [comment]
Yeap, I have the same issue.

If I send "/style/bgcolor/1/2 0 0 255" to a surface, nothing happens. However, the 'Edit button' > (background colour picker) interface updates correctly.

Neither the physical StreamDeck or the virtual buttons update.

As soon as I issue a press command (/press/bank/1/2) everything updates (in this case, to blue bg) correctly.

**System**

OS: Win 10
Browser: Chrome 78
Version 2.0.0 b6Fc4d5

**Comment by empyfree** [comment]
Would like to also confirm this.   

I've tested by sending /style/bgcolour and /style/text to various buttons (from Chamsys MagicQ) 

If I view the button in the admin console I can see that the details have changed, but they are not reflected on the Streamdeck (or web-buttons).

When I press the relevant button (on streamdeck or webconsole) the changes immediately refresh and "go live".   

I ideally want to be able to change the bgcolor of buttons as a simple feedback to show the state of my lighting cues in MagicQ

**Comment by robsumm** [comment]
Same issue trying to change style via osc from Qlab 
Sending /style/bgcolor/1/30 255 0 0
Nothing happens either on the streamdeck or the browser until the button is updated, I.e. is pressed or the dynamic content changes

Companion on Pi
Safari on OSX to program
Version 2.0

**Comment by Julusian** [comment]
https://github.com/bitfocus/companion/pull/972

**Comment by josephdadams** [comment]
@Julusian @thedist this is fixed now per the PR, yeah?

**Comment by ryanhowerton** [comment]
It seems that the /style/text address was fixed, but /style/bgcolor seems to still be broken.  I can change the text fine, but cannot change the color.

**Comment by robsumm** [comment]
Sorry for the delay only just had the chance to get my Raspberry connected to the internet to update the version, I have all the published OSC commands working from Qlab. I can set the text, text color and bgcolor and they change instantly and can also press buttons.
Thanks for you help.
Is there a way to change bank using osc?
Rob Summers
LST Services Ltd.
07973 225112


[cid:4FCE5A53-1754-4652-A71A-1AC380B09C33@lan]

Please consider the environment - do you really need to print this email?

This e-mail is private and confidential and it is for the intended recipient only. If you are not the intended recipient please notify the sender immediately. This email should not be relied upon without confirmation of its contents. LST Ltd disclaims all liability so far as permitted by law for any person acting, or refraining from acting, on such information.  Any disclosure, copying or distribution of this e-mail or its contents in any form is prohibited without the permission of the sender.

On 2 Mar 2020, at 18:29, ryanhowerton <notifications@github.com<mailto:notifications@github.com>> wrote:


It seems that the /style/text address was fixed, but /style/bgcolor seems to still be broken. I can change the text fine, but cannot change the color.

**Comment by RobertBurt** [comment]
Has anyone figured OSC feedback with /style/text or /style/bicolored ? Is the message supposed to be sent without arguments or as a float ?
