### ISSUE TITLE
Mitti Support Request

### ISSUE THREAD

**Issue by Deanbau** [bitfocus/companion#9]
Mitti support with following options (with OSC string)

- Play (/mitti/play)
- Toggle Play (/mitti/togglePlay)
- Stop (/mitti/stop)
- Panic (/mitt/panic)
- Rewind (/mitti/rewind)
- Jump (/mitti/jumpToNextCue + /mitti/jumpToPrevCue)
- Select - (/mitti/selectNextCue + /mitti/selectPrevCue)
- Goto (/mitti/goto10 + /mitti/goto20 + /mitti/goto30)

Read back on display as variables 

- /mitti/currentcuename
- /mitti/time 
- /mitti/cuetimeleft
- /mitti/toggleplay (0 for pause, 1 for play)

**Comment by Deanbau** [comment]
Entire command list

/mitti/1/audioOff: Turns Off Audio on the Cue. It does not require any value. Also available as UDP String command.

/mitti/1/audioOn: Turns On Audio on the Cue. It does not require any value. Also available as UDP String command.

/mitti/1/blue: Changes the blue of the Cue. Required value is a float (0.00 - 1.00).

/mitti/1/brightness: Changes the brightness of the Cue. Required value is a float (-1.00 - 1.00).

/mitti/1/contrast: Changes the contrast of the Cue. Required value is a float (-1.00 - 1.00).

/mitti/1/fadeInOff: Turns Off Fade In on the Cue. It does not require any value. Also available as UDP String command.

/mitti/1/fadeInOn: Turns On Fade In on the Cue. It does not require any value. Also available as UDP String command.

/mitti/1/fadeOutOff: Turns Off Fade Out on the Cue. It does not require any value. Also available as UDP String command.

/mitti/1/fadeOutOn: Turns On Fade Out on the Cue. It does not require any value. Also available as UDP String command.

/mitti/1/green: Changes the green of the Cue. Required value is a float (0.00 - 1.00).

/mitti/1/jump: Jumps to the beginning of the Cue. It does not require any value. Also available as UDP String command.

/mitti/1/loopOff: Turns Off Looping on the Cue. It does not require any value. Also available as UDP String command.

/mitti/1/loopOn: Turns On Looping on the Cue. It does not require any value. Also available as UDP String command.

/mitti/1/opacity: Changes the opacity of the Cue. Required value is a float (0.00 - 1.00).

/mitti/1/pan: Changes the pan of the Cue. Required value is a float (-1.00 - 1.00).

/mitti/1/pauseAtBeginningOff: Turns Off Pause-at-Beginning feature on the Cue. It does not require any value. Also available as UDP String command.

/mitti/1/pauseAtBeginningOn: Turns On Pause-at-Beginning feature on the Cue. It does not require any value. Also available as UDP String command.

/mitti/1/pauseAtEndOff: Turns Off Pause-at-End feature on the Cue. It does not require any value. Also available as UDP String command.

/mitti/1/pauseAtEndOn: Turns On Pause-at-End feature on the Cue. It does not require any value. Also available as UDP String command.

/mitti/1/red: Changes the red component of the Cue. Required value is a float (0.00 - 1.00).

/mitti/1/select: Selects the Cue. It does not require any value. Also available as UDP String command.

/mitti/1/toggleAudio: Toggle Audio On/Off on the Cue. Required value is an int (0 - 1).

/mitti/1/toggleFadeIn: Toggle Fade In On/Off on the Cue. Required value is an int (0 - 1).

/mitti/1/toggleFadeOut: Toggle Fade Out On/Off on the Cue. Required value is an int (0 - 1).

/mitti/1/toggleLoop: Toggle Looping On/Off on the Cue. Required value is an int (0 - 1).

/mitti/1/togglePauseAtBeginning: Toggle Pause-at-Beginning feature On/Off on the Cue. Required value is an int (0 - 1).

/mitti/1/togglePauseAtEnd: Toggle Pause-at-End feature On/Off on the Cue. Required value is an int (0 - 1).

/mitti/1/toggleTransition: Toggle Transition feature On/Off on the Cue. Required value is an int (0 - 1).

/mitti/1/toggleVideoFx: Toggle FX On/Off on the Cue. Required value is an int (0 - 1).

/mitti/1/transitionOff: Turns Off Transition feature on the Cue. It does not require any value. Also available as UDP String command.

/mitti/1/transitionOn: Turns On Transition feature on the Cue. It does not require any value. Also available as UDP String command.

/mitti/1/videoFxOff: Turns Off Video Effect on the Cue. It does not require any value. Also available as UDP String command.

/mitti/1/videoFxOn: Turns On Video Effect on the Cue. It does not require any value. Also available as UDP String command.

/mitti/1/volume: Changes the volume of the Cue. Required value is a float (0.00 - 2.00).



/mitti/2/audioOff: Turns Off Audio on the Cue. It does not require any value. Also available as UDP String command.

/mitti/2/audioOn: Turns On Audio on the Cue. It does not require any value. Also available as UDP String command.

/mitti/2/blue: Changes the blue of the Cue. Required value is a float (0.00 - 1.00).

/mitti/2/brightness: Changes the brightness of the Cue. Required value is a float (-1.00 - 1.00).

/mitti/2/contrast: Changes the contrast of the Cue. Required value is a float (-1.00 - 1.00).

/mitti/2/fadeInOff: Turns Off Fade In on the Cue. It does not require any value. Also available as UDP String command.

/mitti/2/fadeInOn: Turns On Fade In on the Cue. It does not require any value. Also available as UDP String command.

/mitti/2/fadeOutOff: Turns Off Fade Out on the Cue. It does not require any value. Also available as UDP String command.

/mitti/2/fadeOutOn: Turns On Fade Out on the Cue. It does not require any value. Also available as UDP String command.

/mitti/2/green: Changes the green of the Cue. Required value is a float (0.00 - 1.00).

/mitti/2/jump: Jumps to the beginning of the Cue. It does not require any value. Also available as UDP String command.

/mitti/2/loopOff: Turns Off Looping on the Cue. It does not require any value. Also available as UDP String command.

/mitti/2/loopOn: Turns On Looping on the Cue. It does not require any value. Also available as UDP String command.

/mitti/2/opacity: Changes the opacity of the Cue. Required value is a float (0.00 - 1.00).

/mitti/2/pan: Changes the pan of the Cue. Required value is a float (-1.00 - 1.00).

/mitti/2/pauseAtBeginningOff: Turns Off Pause-at-Beginning feature on the Cue. It does not require any value. Also available as UDP String command.

/mitti/2/pauseAtBeginningOn: Turns On Pause-at-Beginning feature on the Cue. It does not require any value. Also available as UDP String command.

/mitti/2/pauseAtEndOff: Turns Off Pause-at-End feature on the Cue. It does not require any value. Also available as UDP String command.

/mitti/2/pauseAtEndOn: Turns On Pause-at-End feature on the Cue. It does not require any value. Also available as UDP String command.

/mitti/2/red: Changes the red component of the Cue. Required value is a float (0.00 - 1.00).

/mitti/2/select: Selects the Cue. It does not require any value. Also available as UDP String command.

/mitti/2/toggleAudio: Toggle Audio On/Off on the Cue. Required value is an int (0 - 1).

/mitti/2/toggleFadeIn: Toggle Fade In On/Off on the Cue. Required value is an int (0 - 1).

/mitti/2/toggleFadeOut: Toggle Fade Out On/Off on the Cue. Required value is an int (0 - 1).

/mitti/2/toggleLoop: Toggle Looping On/Off on the Cue. Required value is an int (0 - 1).

/mitti/2/togglePauseAtBeginning: Toggle Pause-at-Beginning feature On/Off on the Cue. Required value is an int (0 - 1).

/mitti/2/togglePauseAtEnd: Toggle Pause-at-End feature On/Off on the Cue. Required value is an int (0 - 1).

/mitti/2/toggleTransition: Toggle Transition feature On/Off on the Cue. Required value is an int (0 - 1).

/mitti/2/toggleVideoFx: Toggle FX On/Off on the Cue. Required value is an int (0 - 1).

/mitti/2/transitionOff: Turns Off Transition feature on the Cue. It does not require any value. Also available as UDP String command.

/mitti/2/transitionOn: Turns On Transition feature on the Cue. It does not require any value. Also available as UDP String command.

/mitti/2/videoFxOff: Turns Off Video Effect on the Cue. It does not require any value. Also available as UDP String command.

/mitti/2/videoFxOn: Turns On Video Effect on the Cue. It does not require any value. Also available as UDP String command.

/mitti/2/volume: Changes the volume of the Cue. Required value is a float (0.00 - 2.00).



/mitti/goto10: Jumps to the last 10 seconds of the Current Cue. It does not require any value. Also available as UDP String command.

/mitti/goto20: Jumps to the last 20 seconds of the Current Cue. It does not require any value. Also available as UDP String command.

/mitti/goto30: Jumps to the last 30 seconds of the Current Cue. It does not require any value. Also available as UDP String command.

/mitti/jumpToCueWithName: Jumps to the first Cue with the same name as in the parameter. Required value is a string.

/mitti/jumpToNextCue: Jumps to the next Cue. It does not require any value. Also available as UDP String command.

/mitti/jumpToPrevCue: Jumps to the previous Cue. It does not require any value. Also available as UDP String command.

/mitti/locate: Locates to the timecode or seconds specified in the parameter. Required value is a string.

/mitti/loopOff: Turns off Playlist Looping It does not require any value. Also available as UDP String command.

/mitti/loopOn: Turns on Playlist Looping. It does not require any value. Also available as UDP String command.

/mitti/mainFader: Controls the Main Fader. Required value is a float (0.00 - 1.00).

/mitti/panic: Triggers the Panic mode. It does not require any value. Also available as UDP String command.

/mitti/play: Starts playback if not already started. It does not require any value. Also available as UDP String command.

/mitti/playhead: Sets the playhead of the current Cue - works only when the Playlist stopped. Required value is a float (0.00 - 1.00).

/mitti/playSelectedCue: Plays the selected Cue. It does not require any value. Also available as UDP String command.

/mitti/rewind: Rewinds the Current Cue. It does not require any value. Also available as UDP String command.

/mitti/selectCurrentCue: Selects the Current Cue. It does not require any value. Also available as UDP String command.

/mitti/selectNextCue: Selects the next Cue. It does not require any value. Also available as UDP String command.

/mitti/selectPrevCue: Selects the previous Cue. It does not require any value. Also available as UDP String command.

/mitti/stop: Stops playback if not already stopped. It does not require any value. Also available as UDP String command.

/mitti/toggleLoop: Toggle On/Off Playlist Looping. Required value is an int (0 - 1).

/mitti/togglePlay: Starts or stops playback. Required value is an int (0 - 1).

**Comment by willosof** [comment]
Done in 1.0.7

**Comment by willosof** [comment]
Feedback will come in 2.x.x :)
