### ISSUE TITLE
Slack link should be included in the README

### ISSUE THREAD

**Issue by jeffmikels** [bitfocus/companion#901]
The documentation for creating new modules refers to asking on slack for the module to be included in core; however, there is no link to the slack team, so there is no way for me to make that request.

I'm the creator of this module:

https://github.com/bitfocus/companion-module-generic-os

**Comment by McHauge** [comment]
Bitfocusio.slack.com

I will ad the link for it on wiki under the module dev

**Comment by willosof** [comment]
It needs to be the slack invite url.

**Comment by McHauge** [comment]
Added the invite link to the module dev, wiki page
