### ISSUE TITLE
Button Text Chinese support

### ISSUE THREAD

**Issue by lzx19951022** [bitfocus/companion#904]
**Describe the feature**
I have notice after I change the button style to text , if i key in English, it displays with no problem, but if I key in chinese, it will display nothing. I am a user of china and I think if the button text can support chinese display, it will help more people ,hope you guys can add this feature, thanks !
![QQ图片20191116112333](https://user-images.githubusercontent.com/35286852/68987360-1b89f800-0864-11ea-94cd-15d62d4dc399.png)

**Comment by houtacheng** [comment]
可以上傳有中文字的圖片當作按鈕背景作為替代

**Comment by dnmeid** [comment]
Hi lzx19951022,
I wrote most of the font handling stuff and unfortunately I have to tell you there is no chance of implementing chinese or other complex characters in the current system. At the moment we are using bitmap fonts, so adding those characters would increase the memory usage and loading time way too much.
This won't change in companion 2.x either but I hope that we'll be able to do a vector-based font system for Companion 3.

**Comment by josephdadams** [comment]
Closing since it’s a won’t fix. We can leave the label and look at it when we are working on 3.0.
