### ISSUE TITLE
Enhancement Request - Disable streamdeck/companion functions on computer locking

### ISSUE THREAD

**Issue by kd8ssq** [bitfocus/companion#907]
**PLEASE USE THIS PAGE IF YOU WANT SUPPORT FOR A NEW DEVICE**

https://github.com/bitfocus/companion-module-requests/issues/new

**Describe the feature**
Looking for a way to disable the streamdeck when the computer is locked.  This would obviously need to be optional because I can see cases where people would still want to be able to use companion even when the controlling computer is locked.  Right now even when the computer is locked, all functions of companion are still accessible and the streamdeck glows brightly in the dark room, calling for people to push buttons...

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
N/A

**Usecases**
We have two streamdecks in our sound booth and use them for everything from audio to live stream controls.  When we shut down the booth, everything is disabled except for the streamdecks which glow brightly and can still manipulate things even when the computer is locked.  I'm looking for something that would disable the functionality of the streamdeck until the computer is logged back into.

**Comment by Julusian** [comment]
electron has an event that would help here https://www.electronjs.org/docs/latest/api/power-monitor#event-lock-screen-macos-windows

**Comment by mark-epstein** [comment]
I'd suggest having the ability to execute a page flip. That allows you to permit the users to do some things that you might still want available during a locked condition, like turning lights on and off.

**Comment by Julusian** [comment]
Perhaps this is just a case of needing to add a trigger 'event' for the computer being locked/unlocked?
It will be more effort for users to setup, but behaviour can be customised a lot more than if we were to provide this as a builtin functionality

**Comment by mark-epstein** [comment]
>add a trigger 'event' for the computer being locked/unlocked
that would get my vote (if I had one, ha!)
I like the flexibility in this approach

**Comment by Julusian** [comment]
This is in beta 6172
