### ISSUE TITLE
TCP/UDP REMOTE CONTROL

### ISSUE THREAD

**Issue by Russell108** [bitfocus/companion#909]
Ok Thank you for wonderful packages
I have setup a latching button as on off
BANK-PRESS works fine using UDP in the sense it toggles the button state
But if the user press the button on then off and if the UDP user send a button press  to switch of
Then its switched on

It would be great if you would also support 
BANK-ON BANK-OFF as well as   BANK-DOWN BANK-UP

Best Russell

**Comment by josephdadams** [comment]
@istnv can we close this now?

**Comment by istnv** [comment]
@josephdadams Yes.
Now that BANK-DOWN and BANK-UP operate as expected, they are equivalent to ON and OFF.

**Comment by Russell108** [comment]
Thank you
