### ISSUE TITLE
äÄöÖüÜ not working on 7pt

### ISSUE THREAD

**Issue by jasonkuhr** [bitfocus/companion#910]
On the Button Labels äÄöÖüÜ is not working/showing on 7pt

**Comment by dnmeid** [comment]
That is right. The 7pt font is handcrafted to be as tiny as possible. The capital letters use all the 7 points in height and the small letters are using 6 points, so there is simply no space left for any extra accents or umlauts.
It's not a bug, it's a feature ;-)

**Comment by jasonkuhr** [comment]
But can you put an 'a' as an 'a' in it so if you write a long label that the Letter wont disappears. In my case the ä is missing. then it would be a feature and not a bug. ;-)
