### ISSUE TITLE
Move Button on his self deletes the Button

### ISSUE THREAD

**Issue by Hitower78** [bitfocus/companion#915]
Hi
In 2.0 (Beta 22bea6a and f03c82c) it happend to me, that i move a button on the same (old) position where he is coming from and then its gone (deleted)
e.g. from Button 3.18 to 3.18

It would be nice it would be not deleted

thanx

**Comment by krocheck** [comment]
Personally, I'd like to see us implement drag-and-drop move to get rid of this issue altogether.  It could happen 😄
