### ISSUE TITLE
Add instance menus appear off of the screen

### ISSUE THREAD

**Issue by candymanjl** [bitfocus/companion#916]
Hello!

New to Stream Deck and Companion.  Running my Stream Deck XL with Companion 2.0.0 (b6fc4d5).  I'm using Chrome Version 78.0.3904.108 (Official Build) (64-bit)
on MacOS 10.14.6.  Just getting things up and running.

While playing with what's possible, I noticed that when adding instances, the add by category or manufacturer menus continue down past the end of the page.  So you cannot see the rest of the list.  Listing by manufacturer only allows me to see down to Kramer for example.

Guessing the menu just needs to be able to scroll in order to browse all of the available options.

**Comment by josephdadams** [comment]
Related to #89 and #287. It is a bug and does need to be fixed.

**Comment by candymanjl** [comment]
Thanks!  Sorry, new to Github as well, not 100% how to find things that have been submitted already.

**Comment by josephdadams** [comment]
No worries! There are a lot of outstanding issues right now and it can be hard to know. I try to stay on top of what's submitted and either close complete duplicates or at least tag as related. I'll leave this open for now. It's been asked to be fixed several times, but the search function is used more, and it hasn't gotten priority to be fixed. Thanks for submitting a bug report!

**Comment by josephdadams** [comment]
I knew I had seen this before, it duplicates #362, so I'm going to close this.
