### ISSUE TITLE
Javascript error, osc won't work in 2.0.0-434b781-1929

### ISSUE THREAD

**Issue by richardhqi** [bitfocus/companion#918]
Hello all,
![Screenshot 2019-12-06 at 08 36 48](https://user-images.githubusercontent.com/58604640/70342548-1e945a80-180a-11ea-98a2-ff1e9ab674c9.png)
Launched companion on streamdeck this morning and every button press (linked to generic osc string actions) leads to an error message of this sort 'EHOSTUNREACH'

macos 10.14.6, companion 2.0.0-434b781-1929

**Comment by josephdadams** [comment]
@richardhqi are you using multiple OSC devices or instances? Or are they all referencing the same IP address? This looks more like an error related to that device/port being unreachable from the Companion computer.

**Comment by bryce-seifert** [comment]
This seems similar to [this issue](https://github.com/bitfocus/companion-module-mitti/issues/3) I was experiencing periodically. My question there was is there a way for OSC in Companion to catch this error instead of crashing the whole program?

**Comment by josephdadams** [comment]
@bryce-seifert it would have to be on a per-module basis (generic OSC module, mitti module, etc. anything that implements OSC). The error is because the remote OSC device is not available to Companion.

**Comment by bryce-seifert** [comment]
Understood. We can close this, I'll request it at the module level.
