### ISSUE TITLE
Missing modules in Raspberry Pi 4 Build

### ISSUE THREAD

**Issue by jackcrombie** [bitfocus/companion#920]
Building on Raspberry Pi:

pi@jack-rpi4-1:~/Projects/companion $ yarn update
yarn run v1.21.0
$ ./tools/update.sh
Already up to date.
Synchronizing submodule url for 'bitfocus-libs'
Synchronizing submodule url for 'bitfocus-skeleton'
Synchronizing submodule url for 'lib/module/7thsensedelta'
Synchronizing submodule url for 'lib/module/agf-characterworks'
Synchronizing submodule url for 'lib/module/aja-helo'
Synchronizing submodule url for 'lib/module/aja-kipro'
Synchronizing submodule url for 'lib/module/aja-kumo'
Synchronizing submodule url for 'lib/module/allenheath-dlive'
Synchronizing submodule url for 'lib/module/amp'
Synchronizing submodule url for 'lib/module/analogway-eks500'
Synchronizing submodule url for 'lib/module/analogway-livepremier'
Synchronizing submodule url for 'lib/module/analogway-midra'
Synchronizing submodule url for 'lib/module/analogway-picturall'
Synchronizing submodule url for 'lib/module/analogway-pls300'
Synchronizing submodule url for 'lib/module/analogway-vertige'
Synchronizing submodule url for 'lib/module/artnet'
Synchronizing submodule url for 'lib/module/atem'
Synchronizing submodule url for 'lib/module/audivero-unityintercom'
Synchronizing submodule url for 'lib/module/avolites-titan'
Synchronizing submodule url for 'lib/module/avplayback'
Synchronizing submodule url for 'lib/module/avproconnect-acmx1616-auhd'
Synchronizing submodule url for 'lib/module/avstumpfl-pixera'
Synchronizing submodule url for 'lib/module/barco-dp'
Synchronizing submodule url for 'lib/module/barco-encore'
Synchronizing submodule url for 'lib/module/barco-eventmaster-xml'
Synchronizing submodule url for 'lib/module/barco-hdx'
Synchronizing submodule url for 'lib/module/barco-matrixpro'
Synchronizing submodule url for 'lib/module/barco-pulse'
Synchronizing submodule url for 'lib/module/bitfocus-companion'
Synchronizing submodule url for 'lib/module/blackdiamondvideo-phantom800'
Synchronizing submodule url for 'lib/module/bmd-multiview16'
Synchronizing submodule url for 'lib/module/bmd-multiview4'
Synchronizing submodule url for 'lib/module/bmd-smartview'
Synchronizing submodule url for 'lib/module/bmd-teranex'
Synchronizing submodule url for 'lib/module/brightsign-player'
Synchronizing submodule url for 'lib/module/casparcg'
Synchronizing submodule url for 'lib/module/chamsys'
Synchronizing submodule url for 'lib/module/chamsys-magicqudp'
Synchronizing submodule url for 'lib/module/christie-pandorasbox'
Synchronizing submodule url for 'lib/module/christie-wd'
Synchronizing submodule url for 'lib/module/christiepj'
Synchronizing submodule url for 'lib/module/cockos-reaper'
Synchronizing submodule url for 'lib/module/dahuasecurity-ptz'
Synchronizing submodule url for 'lib/module/dalite-scb'
Synchronizing submodule url for 'lib/module/dcs'
Synchronizing submodule url for 'lib/module/denon-receiver'
Synchronizing submodule url for 'lib/module/depili-clock-8001'
Synchronizing submodule url for 'lib/module/dexon-dimax'
Synchronizing submodule url for 'lib/module/dexon-divip'
Synchronizing submodule url for 'lib/module/dexon-matrix'
Synchronizing submodule url for 'lib/module/disguise'
Synchronizing submodule url for 'lib/module/disguise-mtc'
Synchronizing submodule url for 'lib/module/dphighlight'
Synchronizing submodule url for 'lib/module/draco-tera'
Synchronizing submodule url for 'lib/module/epiphan-pearl'
Synchronizing submodule url for 'lib/module/etc-eos'
Synchronizing submodule url for 'lib/module/eventmaster'
Synchronizing submodule url for 'lib/module/extron-dxp'
Synchronizing submodule url for 'lib/module/extron-in1604'
Synchronizing submodule url for 'lib/module/extron-ipl-t-pcs4'
Synchronizing submodule url for 'lib/module/extron-smp111'
Synchronizing submodule url for 'lib/module/extron-smp351'
Synchronizing submodule url for 'lib/module/extron-smx'
Synchronizing submodule url for 'lib/module/faith-chapels-video-playout'
Synchronizing submodule url for 'lib/module/foscam-ptz'
Synchronizing submodule url for 'lib/module/generic-http'
Synchronizing submodule url for 'lib/module/globalcache-itac-cc'
Synchronizing submodule url for 'lib/module/globalcache-itac-ir'
Synchronizing submodule url for 'lib/module/globalcache-itac-sl'
Synchronizing submodule url for 'lib/module/grandma2'
Synchronizing submodule url for 'lib/module/highend-hog4'
Synchronizing submodule url for 'lib/module/hologfx-holographics'
Synchronizing submodule url for 'lib/module/horae'
Synchronizing submodule url for 'lib/module/hyperdeck'
Synchronizing submodule url for 'lib/module/imagepro'
Synchronizing submodule url for 'lib/module/interactive-technologies-cueserver'
Synchronizing submodule url for 'lib/module/irisdown-countdowntimer'
Synchronizing submodule url for 'lib/module/joy-playdeck'
Synchronizing submodule url for 'lib/module/justmacros-lua'
Synchronizing submodule url for 'lib/module/kramer-matrix'
Synchronizing submodule url for 'lib/module/kramer-vp727'
Synchronizing submodule url for 'lib/module/lightware2'
Synchronizing submodule url for 'lib/module/lightware3'
Synchronizing submodule url for 'lib/module/livecore'
Synchronizing submodule url for 'lib/module/livingasone-decoders'
Synchronizing submodule url for 'lib/module/matrox-monarch'
Synchronizing submodule url for 'lib/module/media-player-classic'
Synchronizing submodule url for 'lib/module/metus-ingest'
Synchronizing submodule url for 'lib/module/millumin'
Synchronizing submodule url for 'lib/module/mitti'
Synchronizing submodule url for 'lib/module/modulo'
Synchronizing submodule url for 'lib/module/motu-avb'
Synchronizing submodule url for 'lib/module/msc-router'
Synchronizing submodule url for 'lib/module/neodarque-stagetimer2'
Synchronizing submodule url for 'lib/module/nevion-mrp'
Synchronizing submodule url for 'lib/module/newbluefx-titler'
Synchronizing submodule url for 'lib/module/novastar-vx4s'
Synchronizing submodule url for 'lib/module/obs-studio'
Synchronizing submodule url for 'lib/module/obsidiancontrol-onyx'
Synchronizing submodule url for 'lib/module/octava-pro-dsx'
Synchronizing submodule url for 'lib/module/octopus'
Synchronizing submodule url for 'lib/module/octopusapp'
Synchronizing submodule url for 'lib/module/opticis-omm-1000'
Synchronizing submodule url for 'lib/module/optoma-z28s'
Synchronizing submodule url for 'lib/module/osc'
Synchronizing submodule url for 'lib/module/panasonic-avhs'
Synchronizing submodule url for 'lib/module/panasonic-ptz'
Synchronizing submodule url for 'lib/module/pds'
Synchronizing submodule url for 'lib/module/pixap-pixtimerpro'
Synchronizing submodule url for 'lib/module/pjlink'
Synchronizing submodule url for 'lib/module/planningcenter-serviceslive'
Synchronizing submodule url for 'lib/module/playbackproplus'
Synchronizing submodule url for 'lib/module/pptrsc'
Synchronizing submodule url for 'lib/module/ptzoptics-visca'
Synchronizing submodule url for 'lib/module/pvp'
Synchronizing submodule url for 'lib/module/qlab'
Synchronizing submodule url for 'lib/module/qlab-advance'
Synchronizing submodule url for 'lib/module/qsys-remote-control'
Synchronizing submodule url for 'lib/module/radiodj-rest'
Synchronizing submodule url for 'lib/module/renewedvision-propresenter'
Synchronizing submodule url for 'lib/module/resolume-arena'
Synchronizing submodule url for 'lib/module/roland-v600uhd'
Synchronizing submodule url for 'lib/module/roland-v60hd'
Synchronizing submodule url for 'lib/module/roland-vp42h'
Synchronizing submodule url for 'lib/module/roland-vr50hd-mk2'
Synchronizing submodule url for 'lib/module/roland-xs42h'
Synchronizing submodule url for 'lib/module/roland-xs62s'
Synchronizing submodule url for 'lib/module/roland-xs84h'
Synchronizing submodule url for 'lib/module/rosstalk'
Synchronizing submodule url for 'lib/module/sain-smart-relay'
Synchronizing submodule url for 'lib/module/scs'
Synchronizing submodule url for 'lib/module/sharp-tv'
Synchronizing submodule url for 'lib/module/shure-wireless'
Synchronizing submodule url for 'lib/module/slack-webhooks'
Synchronizing submodule url for 'lib/module/sonoran-coyote'
Synchronizing submodule url for 'lib/module/sony-visca'
Synchronizing submodule url for 'lib/module/sounddevices-pixnet'
Synchronizing submodule url for 'lib/module/spyder'
Synchronizing submodule url for 'lib/module/studiocoast-vmix'
Synchronizing submodule url for 'lib/module/tascamcd'
Synchronizing submodule url for 'lib/module/techministry-midirelay'
Synchronizing submodule url for 'lib/module/techministry-protally'
Synchronizing submodule url for 'lib/module/teradek-vidiu'
Synchronizing submodule url for 'lib/module/tesla-smart'
Synchronizing submodule url for 'lib/module/thingm-blink1'
Synchronizing submodule url for 'lib/module/tslproducts-umd'
Synchronizing submodule url for 'lib/module/vaddio-ptz'
Synchronizing submodule url for 'lib/module/vicreo-hotkey'
Synchronizing submodule url for 'lib/module/videohub'
Synchronizing submodule url for 'lib/module/vio'
Synchronizing submodule url for 'lib/module/vizio-smartcast'
Synchronizing submodule url for 'lib/module/vlc'
Synchronizing submodule url for 'lib/module/vyvphoton'
Synchronizing submodule url for 'lib/module/watchout-production'
Synchronizing submodule url for 'lib/module/wyrestorm-sw0402mv'
Synchronizing submodule url for 'lib/module/x32'
Synchronizing submodule url for 'lib/module/xair'
Synchronizing submodule url for 'lib/module/yamaha-scp'
Synchronizing submodule url for 'lib/module/zenvideo-ndirouter'
error: Server does not allow request for unadvertised object 3577e7ac1157af428a1d5d2d9e10b97d6ed394ec
Fetched in submodule path 'lib/module/qlab', but it did not contain 3577e7ac1157af428a1d5d2d9e10b97d6ed394ec. Direct fetching of that commit failed.
Core
[1/4] Resolving packages...
success Already up-to-date.

Bitfocus skeleton
[1/4] Resolving packages...
success Already up-to-date.

Module dependencies
lib/module/agf-characterworks/
[1/4] Resolving packages...
success Already up-to-date.

lib/module/artnet/
[1/4] Resolving packages...
success Already up-to-date.

lib/module/atem/
[1/4] Resolving packages...
success Already up-to-date.
$ yarn fix-types && yarn build
$ cp types/* ../../
$ trash dist && yarn build:main
$ tsc -p tsconfig.build.json

lib/module/dahuasecurity-ptz/
[1/4] Resolving packages...
success Already up-to-date.

lib/module/epiphan-pearl/
[1/4] Resolving packages...
success Already up-to-date.

lib/module/eventmaster/
[1/4] Resolving packages...
success Already up-to-date.

lib/module/foscam-ptz/
[1/4] Resolving packages...
success Already up-to-date.

lib/module/hologfx-holographics/
[1/4] Resolving packages...
success Already up-to-date.

lib/module/matrox-monarch/
[1/4] Resolving packages...
success Already up-to-date.

lib/module/neodarque-stagetimer2/
[1/4] Resolving packages...
success Already up-to-date.

lib/module/newbluefx-titler/
[1/4] Resolving packages...
success Already up-to-date.

lib/module/obs-studio/
[1/4] Resolving packages...
success Already up-to-date.

Done in 48.58s.

**Once built and run as Headed, many modules are still missing.**

Followed all instructions on wiki manual Raspberry Pi Install page:
https://github.com/bitfocus/companion/wiki/Manual-Install-on-Raspberry-Pi

@jarodwsams Assisted on Slack in #rpi

**Comment by jackcrombie** [comment]
yarn dev yields errors like this:
  lib/instance Error loading module x32 { Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/x32/package.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:538:29)
    at EventEmitter.<anonymous> (/home/pi/Projects/companion/lib/instance.js:154:26)
    at emitNone (events.js:106:13)
    at EventEmitter.emit (events.js:208:7)
    at /home/pi/Projects/companion/lib/instance.js:303:11
    at ChildProcess.cp.fork.on (/home/pi/Projects/companion/electron-timer-fix/index.js:93:5)
    at emitTwo (events.js:126:13)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/pi/Projects/companion/lib/module/x32/package.json' } +1ms

**Comment by jackcrombie** [comment]
web UI errors:
10. 01:07:06 module(zenvideo-ndirouter): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/zenvideo-ndirouter/package.json'
10. 01:07:06 module(yamaha-scp): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/yamaha-scp/package.json'
10. 01:07:06 module(xair): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/xair/package.json'
10. 01:07:06 module(x32): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/x32/package.json'
10. 01:07:06 module(wyrestorm-sw0402mv): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/wyrestorm-sw0402mv/package.json'
10. 01:07:06 module(watchout-production): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/watchout-production/package.json'
10. 01:07:06 module(vyvphoton): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/vyvphoton/package.json'
10. 01:07:06 module(vlc): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/vlc/package.json'
10. 01:07:06 module(vizio-smartcast): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/vizio-smartcast/package.json'
10. 01:07:06 module(vio): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/vio/package.json'
10. 01:07:06 module(videohub): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/videohub/package.json'
10. 01:07:06 module(vicreo-hotkey): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/vicreo-hotkey/package.json'
10. 01:07:06 module(vaddio-ptz): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/vaddio-ptz/package.json'
10. 01:07:06 module(tslproducts-umd): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/tslproducts-umd/package.json'
10. 01:07:06 module(thingm-blink1): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/thingm-blink1/package.json'
10. 01:07:06 module(tesla-smart): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/tesla-smart/package.json'
10. 01:07:06 module(teradek-vidiu): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/teradek-vidiu/package.json'
10. 01:07:06 module(techministry-protally): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/techministry-protally/package.json'
10. 01:07:06 module(techministry-midirelay): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/techministry-midirelay/package.json'
10. 01:07:06 module(tascamcd): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/tascamcd/package.json'
10. 01:07:06 module(studiocoast-vmix): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/studiocoast-vmix/package.json'
10. 01:07:06 module(spyder): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/spyder/package.json'
10. 01:07:06 module(sounddevices-pixnet): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/sounddevices-pixnet/package.json'
10. 01:07:06 module(sony-visca): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/sony-visca/package.json'
10. 01:07:06 module(sonoran-coyote): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/sonoran-coyote/package.json'
10. 01:07:06 module(slack-webhooks): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/slack-webhooks/package.json'
10. 01:07:06 module(shure-wireless): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/shure-wireless/package.json'
10. 01:07:06 module(sharp-tv): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/sharp-tv/package.json'
10. 01:07:06 module(scs): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/scs/package.json'
10. 01:07:06 module(sain-smart-relay): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/sain-smart-relay/package.json'
10. 01:07:06 module(rosstalk): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/rosstalk/package.json'
10. 01:07:06 module(roland-xs84h): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/roland-xs84h/package.json'
10. 01:07:06 module(roland-xs62s): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/roland-xs62s/package.json'
10. 01:07:06 module(roland-xs42h): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/roland-xs42h/package.json'
10. 01:07:06 module(roland-vr50hd-mk2): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/roland-vr50hd-mk2/package.json'
10. 01:07:06 module(roland-vp42h): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/roland-vp42h/package.json'
10. 01:07:06 module(roland-v60hd): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/roland-v60hd/package.json'
10. 01:07:06 module(roland-v600uhd): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/roland-v600uhd/package.json'
10. 01:07:06 module(resolume-arena): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/resolume-arena/package.json'
10. 01:07:06 module(renewedvision-propresenter): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/renewedvision-propresenter/package.json'
10. 01:07:06 module(radiodj-rest): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/radiodj-rest/package.json'
10. 01:07:06 module(qsys-remote-control): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/qsys-remote-control/package.json'
10. 01:07:06 module(qlab-advance): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/qlab-advance/package.json'
10. 01:07:06 module(qlab): Error loading module: Error: ENOENT: no such file or directory, open '/home/pi/Projects/companion/lib/module/qlab/package.json'
10. 01:07:02 module(bmd-multiview4): Error loading module: Error: Cannot find module '../videohub/internalAPI'
10. 01:07:02 module(bmd-multiview16): Error loading module: Error: Cannot find module '../videohub/index'

**Comment by haakonnessjoen** [comment]
Hi @jackcrombie,

Seems like there was an issue with the qlab module in github with reference to missing commits. But this has now been restored/fixed.

Please try again now.
