### ISSUE TITLE
Stream Deck App integration

### ISSUE THREAD

**Issue by AnthonyHunt1** [bitfocus/companion#928]
Button layout on the the 15 button Stream Deck is broken with the error message "USB(undefined): Found device, but no access. Please quit any other applications using the device, and try again." using Companion 2.0.0-28be5d2-1953 with Stream Deck v4.4.2 on Mac.

Steps to reproduce the behaviour:
1. Open Stream Deck App
2. Open Companion 4.4.2
3. Watch your hybrid layout die before your eyes

**Comment by JeffreyDavidsz** [comment]
Did you install the companion plug-in? You need it when you want both apps running at the same time

**Comment by AnthonyHunt1** [comment]
Yes. This is the same bug we talked about in the FaceBook group.  I added it here so it can be properly looked into.

I have reinstalled the plugin several times and tried a couple of versions.

**Comment by haakonnessjoen** [comment]
The plugin is not yet supported in companion 2.0

**Comment by AnthonyHunt1** [comment]
haakonnessjoen: I believe it was believed it had been fixed from the FB conversation I had; hence adding it.

Thanks,

Ant.

**Comment by josephdadams** [comment]
Duplicates #688
