### ISSUE TITLE
Typing cursor in button text input field jumps to end in Safari

### ISSUE THREAD

**Issue by bryce-seifert** [bitfocus/companion#937]
**Describe the bug**
Typing cursor in button text input field jumps to end in Safari when editing text in the middle.

**To Reproduce**
1. In *Safari*, select a button from the buttons page.
2. Type something in the text input field.
3. Click in the middle of what you just typed and attempt to type
4. Cursor will jump to end of text in input field.

**Expected behavior**
Cursor remains in place.

**Screenshots**
[Screencast of issue in action.](https://www.dropbox.com/s/td692bn6odawovk/companion_typing_error.mov?dl=0)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 13.0.4

**Additional context**
Tested in Chrome and Firefox, no issues.

**Comment by robsumm** [comment]
this is irritating when you want o edit multiple buttons
