### ISSUE TITLE
Surface not being detected

### ISSUE THREAD

**Issue by peterfra** [bitfocus/companion#940]
**Describe the bug**
When launching the GUI, my streamdeck device is not detected. I have tried opening the streamdeck controller from Elgato, and here it was responsive. I then killed the Elgato app, and opened the Companion app, and still didnt find my device. The device is however detected by the computer. I did also try scanning the USB ports.

The streamdeck is showing the Elgato logo, and pressing it, i come to a welcome page of elgatos.

**To Reproduce**
Guess it Will be hard to reproducere out of this computer, but if its any help, im running the grandma2 module

**Expected behavior**
Finding and showing streamdeck in GUI

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 1903

**aditional context**
Streamdeck is run with newest firmware

**Comment by peterfra** [comment]
👍

**Comment by josephdadams** [comment]
@peterfra if you recently purchased your elgato surface, a hardwire driver change was made and these surfaces do not work with the current 1.4 Companion release. Have you tried with version 2.0 alpha? This is most likely the problem. If you’re still experiencing an issue after trying version 2.0, comment back here and we can re open the issue.

**Comment by jerrypena1** [comment]
I had the exact same problem with a brand new stream deck running on a Mac. Installing the 2.0 version of companion fixed it for me.
