### ISSUE TITLE
Button layout in Stream Deck App "companion button" action doesn't work with XL

### ISSUE THREAD

**Issue by odedd** [bitfocus/companion#941]
**Description**
Stream Deck XL:
The layout in companion looks fine, and when run via the companion app the streamdeck layout is fine.
However, when running via the stream deck app, and using the Elgato Streamdeck Plugin, the layout is jumbled.

**Screenshots**
Should look like that:
<img width="774" alt="Screen Shot 2020-01-02 at 23 27 03" src="https://user-images.githubusercontent.com/15626083/71694320-75fcfa80-2db7-11ea-8a45-f467c66fefae.png">

But looks like that:
<img width="641" alt="Screen Shot 2020-01-02 at 23 25 57" src="https://user-images.githubusercontent.com/15626083/71694270-55cd3b80-2db7-11ea-821b-87bf059966e4.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Companion beta c3ae8e2692eb43a26f4af91edf5c0511b89c1c4e
 - Stream Deck app v4.4.2 (12189)
 - Stream Deck XL Firmware 1.00.006

**Comment by haakonnessjoen** [comment]
Known issue. #688

**Comment by haakonnessjoen** [comment]
Meanwhile, use companion directly to your XL without the stream deck application running for full functionality.
