### ISSUE TITLE
Adjust Streamdeck brightness from internal instance

### ISSUE THREAD

**Issue by bryce-seifert** [bitfocus/companion#943]
**Describe the feature**
You can currently adjust the brightness of the Streamdeck buttons from the admin web interface, but it would be nice to be able to program a value to a button using the internal instance.

**Is this platform dependent (windows, mac, ..)?**
No.

**Usecases**
–Situations where you are using the Streamdeck away from the computer and need to adjust brightness
–Quick way to put the Streamdeck to "sleep" without disconnecting it when not in use

**Comment by MarauderSeeker** [comment]
Has this been implemented?

**Comment by shaunar2006** [comment]
Are there any plans on this?? My streamdecks are on 24/7 and I’m starting to experience color and brightness issues with one of them. I want companion running all the time, but I don’t need the stream decks on all the time. 
I know brightness can be controlled in the GUI, but this needs to be volunteer friendly.
Please let me know if this will be available 
(Or a work around such as http request etc)

**Comment by WeslyG** [comment]
I am designing a brightness control system for my windows pc based on light sensors, and I really want to programmatically control the brightness of the steam deck. So that all monitors and the steam deck would synchronize their brightness with the external lighting. I will be very happy if this feature appears soon!

**Comment by kjetilpp** [comment]
This is a +1
Using Stream deck with PI, it's running 24/7, so would be nice if i can adjust the brightness or turn off brightness, like the Elgato sleep mode.

**Comment by Julusian** [comment]
This is now implemented

**Comment by shaunar2006** [comment]
I FOUND A BUG

setting the brightness of a satellite device does not work. Has no effect on the streamdeck. Works perfectly on the streamdeck that’s connected directly.

**Comment by Julusian** [comment]
> I FOUND A BUG setting the brightness of a satellite device does not work. Has no effect on the streamdeck. Works perfectly on the streamdeck that’s connected directly.

Good spot. This is fixed in the latest build

**Comment by shaunar2006** [comment]
Wow! Thanks so much! That was fast!
