### ISSUE TITLE
Module hologfx-holographics won’t  load

### ISSUE THREAD

**Issue by kutuz00** [bitfocus/companion#946]
instance(hologfx-holographics): Configured instance hologfx-holographics could not be loaded, unknown module

this is an error message I getting

**To Reproduce**
Starting app and this what showing up in log

**Expected behavior**
No error and ability to use this module

**Desktop (please complete the following information):**
 - OS: win10
 - Browser Firefox
 - Version latest

**Additional context**
Also module not in instance list

Regards

**Comment by JeffreyDavidsz** [comment]
Are you on 1.4? And did you try 2.0?

**Comment by kutuz00** [comment]
I am on 1.4. Tried 2.0 no issue with loading module. Just on 1.4. But 2.0 still in alpha

**Comment by josephdadams** [comment]
It’s probably because you configured the instance using 2.0 and it’s not available in 1.4 but they share the same config files.

**Comment by kutuz00** [comment]
In beginning I installed 1.4. And when I didn’t find this module I tried 2.0. 

hologfx-holographics saying they available in 1.4. Bitfocus product list confirm this. 
Again it’s was clean install of companion v1.4.

**Comment by josephdadams** [comment]
@kutuz00 it looks like you submitted this issue here and again in the hologfx repository. I'll close this one.
