### ISSUE TITLE
Add support for variables in action/feedback inputs

### ISSUE THREAD

**Issue by GeoDerp** [bitfocus/companion#960]
### Describe the feature
Allow the ability to use dynamic variables in other modules.

### Usecases
- For Timers from different modules 
- For Modules that use the same (input/output) names
- Pretty much a good method to use input data from one module to output data for another by pressing one button.

### Image Example
![Screen Shot 2020-01-10 at 4 25 56 pm](https://user-images.githubusercontent.com/18461782/72311960-6d20f880-36d6-11ea-9c22-063620f09d42.png)

*Example is using Qlab's Dynamic Variable (of time left in a video) to set the ProPresenter clock to the time remaining, and start it.*

*This is so the user doesn't have to fiddle around with the clock to get the precise time every time a Qlab video is playing (our Qlab videos all have different lengths)*

**Comment by krocheck** [comment]
This will have to be carefully thought through.  An on-the-fly change to config isn't supported and would require an additional tracking layer and firing mechanism.  Doable, but not simple.

**Comment by willosof** [comment]
Yeah, this is something we need to consider for the new design. Should be fairly easy to implement as long as we make a generic variable engine that everything needs to go through. :)

**Comment by willosof** [comment]
If it's a numeric input, we should support math as well :) `floor($(inst:var)/2)+1` etc.

**Comment by mcondie65** [comment]
Being able to do math's would be fantastic. 
You could add a command in the advance to specific slide secion `$(propresenter:total_slides)-$(propresenter:current_slide)` which would allow you to skip to the next section in your ProPresnter playlist

**Comment by Julusian** [comment]
This needs to be done per module, and there is another task to look at supporting expressions in these fields #2345
