### ISSUE TITLE
(BUG) Octopus Listener will not control PowerPoint on a PC

### ISSUE THREAD

**Issue by EllSeven** [bitfocus/companion#964]
I am attempting to send basic next slide and previous slide commands to PowerPoint on a PC but I can not get control. The status of the Octopus Listener is green and says OK.  I know all my ports are open. I have control via Octopus.

**Comment by Abecoders** [comment]
You can use Vicreo Listener instead as Octopus no longer support companion.

**Comment by JeffreyDavidsz** [comment]
Octopus listener only works with the paid version. Of octopus. Use VICREO-Hotkey or an old version of octopus listener
