### ISSUE TITLE
No connection and JS errors

### ISSUE THREAD

**Issue by jammin808** [bitfocus/companion#967]
I can't get a connection to the Stream Deck at all with Companion. Works fine with the Stream Deck application. Same issue on two laptops - i5 and i7 windows 10 machines.

Version: companion-1.4.0-b402e70-win64-signed
Latest firmware installed.

When I open Companion it doesn't list the Stream Deck as a surface (just the emulator). I have closed the Elgato application and restarted.

There is a Javascript error popup and sometimes it loses connection to it's own server.

![Companion JS Errorbmp](https://user-images.githubusercontent.com/1098369/72904347-a84ea780-3d26-11ea-9466-f52542098c2b.png)

What do I do?!?

**Comment by willosof** [comment]
Have you tried to remove the userfolder/your configuration? %APPDATA%/companion i think. Try removing the db file when companion is not running, and start it.

**Comment by jammin808** [comment]
Thanks for the quick response! Yes, I've tried deleting the db and db.bak files but it hasn't made a difference.

More errors...

![Companion JS Errorbmp 2](https://user-images.githubusercontent.com/1098369/72906138-a89c7200-3d29-11ea-886d-92bff93190a9.png)

**Comment by josephdadams** [comment]
If it’s a newly purchased stream deck, it may not be compatible with Companion 1.4. Try 2.0.

**Comment by jammin808** [comment]
It is and it seems it's not! 2.0 has worked :) You sir, are a true gent. But is this show ready / stable?

**Comment by josephdadams** [comment]
I use it regularly without issue. I would say just test it really well before you use it. It should be fine. There are some bugs related to importing/exporting and the internal actions to change surface pages, etc. , so maybe avoid those for now.

If that solves your issue, let’s close this. If not, let me know and we can keep working on it.

**Comment by jammin808** [comment]
Wise words, thanks. Only now it won't recognise commands to vlc on the same machine! Buttons work as I've tested on changing a value on the Stream Deck, but no vlc control at all!

**Comment by josephdadams** [comment]
What version of vlc?
