### ISSUE TITLE
[request] vMix Module - instance feedbacks

### ISSUE THREAD

**Issue by gabrielve1** [bitfocus/companion#970]
Hello there.

As for now **vMix module** is a very powerfull tool for Companion, but it lacks one feature, that renders it very problematic for controlling this software remotely - **FEEDBACKS**.

For starters it would be a powerfull addition if developers make feedbacks at least for vMix functions state (recording, external output, streaming, playlist etc.). 

There is a special section of API XML that provides that informations
Example (taken from my vMix just a moment ago, httlp://127.0.0.1:8088/API/):

```
<recording duration="515" filename1="C:\Users\user\Videos\capture - 23 January 2020 - 02-04-35 PM - 00000.mpg">True</recording>
<external>False</external>
<streaming channel1="True" channel2="True">True</streaming>
<playList>False</playList>
<multiCorder>False</multiCorder>
<fullscreen>False</fullscreen>

```

- Without feedbacks we can controll vMix of course, but if i would like to turn something on remotely i don't have a confirmation it worked.

- Also in my case for example, im controlling multiple vMix productions at once, located in many studios and other locations. This feature would really ease my work (and i think not only mine)

**Comment by cgarwood** [comment]
Can you post this over on the repo for the vMix module? https://github.com/bitfocus/companion-module-studiocoast-vmix/issues 👍

**Comment by gabrielve1** [comment]
will do

**Comment by josephdadams** [comment]
Closing this since it was requested over there
