### ISSUE TITLE
[BUG] Reset config wipes out navigation buttons

### ISSUE THREAD

**Issue by thereisnoh** [bitfocus/companion#971]
**Describe the bug**
When starting from reset fun configuration all navigation buttons are removed forcing the need to add them to every page.

**Expected behavior**
Navigation buttons previously were placed in their default location.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.15.2
 - Browser: safari
 - Companion Version: (2.0.0-26851f7-2021)

**Comment by Julusian** [comment]
fixed in 62b41a3b27a971aafc56228daab2cefc4633b2e5

**Comment by garyforster1** [comment]
Sorry to sound dumb. I did a reset config and ever since lost all navigation buttons and it won't send info to stream deck. 

This says it's solved it but how do I get this working?
