### ISSUE TITLE
Feature Request: Ability to rearrange existing pages

### ISSUE THREAD

**Issue by jarodwsams** [bitfocus/companion#976]
As a Companion user, I would like the ability to re-arrange pages of buttons that I've already programmed but maybe need/want in a different order.

This should be platform-agnostic.

Example Use Case:
I already have a fully-configured collection of pages, but then I add a new piece of equipment. For any number of reasons, I would like to have the control buttons for that new piece of gear closer to page 1. Ideally, I would be able to either: inject a new blank page between pages 1 and 2, or move another page to the number 2 spot (pushing the original page 2 to page 3, and so on).

**Comment by josephdadams** [comment]
This sounds like #610, but since yours is so much more thoughtfully written out, I'm going to close that one and keep this one. :)

**Comment by Hennyr** [comment]
Josephadams,
What is the status of issue/request #976?  I am looking for this feature. I am very pleased with companion.

**Comment by poucedeleon** [comment]
Joseph, you commented to the status of 976 "not Implemented", does that mean still being considered or the request was turned down?

**Comment by Julusian** [comment]
@poucedeleon it will be done, and is waiting for some larger work on being able to change the number of pages to be done

**Comment by metawops** [comment]
I'm also looking forward to this feature. Any news? Will it be implemented on the 2.x branch (which I'm still using) or will it be a feature of Companion 3.x? 😳 Thanks so much! 😊

**Comment by Julusian** [comment]
This will probably be in 3.1, and definitely wont be in an earlier release

**Comment by istnv** [comment]
You can also do a full export, import a single page with a different destination page.

**Comment by Julusian** [comment]
This is now in the betas
