### ISSUE TITLE
Feature Request: Jump to Page in button programmer

### ISSUE THREAD

**Issue by MrLazerface** [bitfocus/companion#979]
**Describe the feature**
The ability to jump to a specific page number when building and editing buttons. Instead of clicking a forward or back arrow 40-50 times to get to a specific page, can we enter the page number we want to go to? Maybe reuse the page number indicator as the jump-to button/field?

**Usecases**
I have pages that I don't want accessed by users normally, as they either contain buttons that get triggered by external OSC commands, or contain buttons that are show/career ending (projector lamp off, etc.). Making changes to these pages currently require me to mash my left click until i get to page 50 or 69, etc. before I can edit a button.

**Comment by josephdadams** [comment]
Duplicates #628 .
