### ISSUE TITLE
[BUG] Potential bug with electron-timer-fix when debugging under WSL & VSCode

### ISSUE THREAD

**Issue by thargy** [bitfocus/companion#980]
When debugging`headless.js` on node, from Visual Studio Code, running on WSL (Ubuntu on Windows 10), the initial timer is not firing when the debugger is attached on start, and so the headless server never starts up.

**To Reproduce**
1. Install WSL (Ubuntu) on Windows 10
2. Clone latest repo.
3. Setup VSCode to debug using following `launch.json`:
```js
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Headless",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}/headless.js",
            "args": ["lo", "8888"]
        }
    ]
}
```
4. Launch

**Expected behavior**
Expect headless server to start on port 8888 of localhost.

**Desktop**
 - OS: Windows 10
 - Browser: N/A
 - Companion Version: 2.0

**Additional context**
The above configuration runs node using the following options:
`node --inspect-brk=33969 headless.js lo 8888`

The function set to run on a timer on [line 74](https://github.com/bitfocus/companion/blob/952882b6e9af5fa238e61a59dc9a150826935ee3/headless.js#L74) of `headless.js` never fires.  The `setTimeout` [override](https://github.com/bitfocus/companion/blob/952882b6e9af5fa238e61a59dc9a150826935ee3/electron-timer-fix/index.js#L96-L100) defined in `electron-timer-fix` is called to set up the timer, pointing to it as a potential source of the problem.

**Workaround**
Note, running node using:
`node --inspect headless.js lo 8888`
and then waiting until the `Started` log appears, _before_ attaching, allows VSCode to attach to the running process and seems to debug correctly, suggesting this is possibly something to do with the initial timer only?  _However, as I am new to Companion I have not yet been able to verify if timers stop firing after the delayed attach._

Running without the `inspect` option(s) seems to allow Companion to run correctly (but of course debugger cannot then be attached).

**Comment by Julusian** [comment]
electron-timer-fix is no longer used
