### ISSUE TITLE
Option to hide status line

### ISSUE THREAD

**Issue by thargy** [bitfocus/companion#981]
**Describe the feature**
Add a new global configuration enumeration to hide the top status line (including button number) to make more space available for the button itself.  Allow override on a per-button basis.

- **Show**: Shows the status line (DEFAULT - current behavior)
- **Press**: Only shows the line whilst the button is 'pressed' (e.g. on toggle) - this is for completeness and may not be required if too complex to implement, particularly as it could cause layout issues.
- **Auto**: Only shows when there is a status/info to display on the line (currently I think this is only used by 'disconnected' warning box, but this future-proofs)
- **Hide**: Always hides the button.

**Optional**: Checkbox to show disconnection status, when true (DEFAULT - current behavior), status box will overwrite top corner of a button even when status line not shown.

**Is this platform-dependent (windows, mac, ..)?**: No.

**Usecases**:
This would allow page buttons to be replaced with some simple presets rather than being a special case.

The button numbers are redundant, particularly with the page number present, and don't always add anything useful, but take up space on the button.

**Comment by Nick512** [comment]
This would be so useful, it would make the deck look a lot better without the button header

**Comment by josephdadams** [comment]
#617 is related

**Comment by JoRaeBim** [comment]
I think that would be a very nice thing!! I just wanted to write an equal idea.

Can anybody show me where to find the genereation of the line and the number? So maybe i can do some coding on my own, to work this out.

Thank you :)

**Comment by pepelsbey** [comment]
Yes please.

In my case I don’t have anything to add to my Stream Deck to have a second page. But I can still see that it’s a Page 1, Button 1, which is rather useless and distracting.

**Comment by b1ink0818** [comment]
Having this option would really clean up the overall button layout.

**Comment by ingokunzi** [comment]
This would be a incredible nice feature.

**Comment by JeffreyDavidsz** [comment]
This is available in the beta's. You'll activate it in the settings menu
