### ISSUE TITLE
[BUG] New Streamdeck Revision 20GAA9902 - Not detected

### ISSUE THREAD

**Issue by imcsmall** [bitfocus/companion#983]
So I took delivery of a few new regular sized Streamdeck units yesterday, and I've been scratching my head ever since.

None of them are detected by Companion 1.4.0, W10 1903 and W10 1809. Streamdeck w/ model 20GAA9901 are detected just fine but it appears the units I've just received are 20GAA9902. None of them are detected by v1.4.0. 

They are detected by alpha v2.0 release, but as you also state, it's really not ready for production.

Any input here?

**Comment by imcsmall** [comment]
Duplicate, I'll close this.

**Comment by haakonnessjoen** [comment]
To be frank, 2.0 isn't that unstable. So if you test everything before show, you should be pretty safe.
