### ISSUE TITLE
Feature Request: Checkbox option on Launch Gui window to save log files

### ISSUE THREAD

**Issue by EventReplay** [bitfocus/companion#985]
If Web Gui crashes you have no clue what might have caused it, at least if the logs are saved someway easy accessable you might stand a chance of diagnosis.

**Comment by Julusian** [comment]
In 2.2.1 we are writing the log file to the config directory. I think it was being written before, but not sure where it would have ended up going to (it might have failed from not having permissions to write to the path it was trying)

As such I dont think we need an option for this anymore
