### ISSUE TITLE
[BUG] Preset default options not applied

### ISSUE THREAD

**Issue by thargy** [bitfocus/companion#990]
**Describe the bug**
When creating a button from a preset, any default values in options (on feedback and actions) are not set until the first time the button is edited.

**To Reproduce**
1. Create a preset which doesn't explicitly set default values.
2. Apply preset to a button.
3. Use button before editing, and defaults will not have been set on options.
4. Edit button, and defaults are immediately set.

**Expected behavior**
When presets are applied to a button, the default options should be respected.

**Desktop (please complete the following information):**
 - OS: All
 - Companion Version: 2.0

**Additional context**
Currently, I work around this issue by auto-creating a `defaultOptions` property on actions & feedback using [this method](https://github.com/bitfocus/companion-module-thelightingcontroller/blob/b4c3e8d08c27ce95d6d92606b9fd3b9378497492/index.js#L93-L113) and then applying the options received to feedback/actions over those defaults using [this method](https://github.com/bitfocus/companion-module-thelightingcontroller/blob/b4c3e8d08c27ce95d6d92606b9fd3b9378497492/index.js#L115-L130).  However, this is an unnecessary overhead if defaults are correctly applied.

**Comment by JeffreyDavidsz** [comment]
Nice catch, did you try other modules also? I've only heard about dropdowns before

**Comment by krocheck** [comment]
@thargy is this still an issue?  I did some testing and couldn't reproduce.  For other reasons I changed how the options save in #1058 and may have inadvertently fixed this.

**Comment by thargy** [comment]
Sorry, @krocheck I don't have a dev environment set up for this at the moment.

**Comment by Julusian** [comment]
I am not sure if this should be classed as a bug.
The default values are only used when creating a new feedback/action. If you are to add a new property to an action, and not ensure that is set on existing actions with an upgradeScript, then you would have the same issue.

More generally, companion is assuming that the presets contain fully filled out actions and feedbacks. I dont think this is a bad thing or bug.
Instead I would ask why do you not need to set an option in the preset? 
Even if I could omit some, I would still define every option on the preset, as it makes the result be very explicit.
