### ISSUE TITLE
[BUG] Presets do not update in browser until refresh

### ISSUE THREAD

**Issue by thargy** [bitfocus/companion#992]
**Describe the bug**
When updating presets with `_this.setPresetDefinitions(...)` at some point after initialisation (e.g. after receiving information from a connected party), the GUI's presets do not show the newly updated presets until a browser refresh is performed (e.g. F5).

**To Reproduce**
Example code [here](https://github.com/bitfocus/companion-module-thelightingcontroller/blob/02a4f8fcb4ba20089d0d4c4167de8901f6df3fa1/presets.js#L318-L321).

On fresh start-up the presets are empty until a GUI refresh is performed.

**Expected behavior**
The `_this.setPresetDefinitions(...)` call should trigger a refresh of the client presets automatically.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Companion Version 2.0

**Comment by MeestorX** [comment]
Confirmed as well. Is there a workaround currently?

**Comment by josephdadams** [comment]
F5 on the keyboard. 😂

**Comment by Julusian** [comment]
The new ui in 2.2 handles this fine
