### ISSUE TITLE
octopus listener

### ISSUE THREAD

**Issue by pedrag8** [bitfocus/companion#998]
Hi everybody
just want to ask how to use the octopus listener for remoting power point, or keynote.
I have installed the octopus listener, and added the instance to companion, the status is ok!
but no results when I am testing the buttons, I search all about on the net but don’t figure out with issue.
Of course, my power point is open and active when I am testing the buttons.
For sure I am missing something!
![pic 2](https://user-images.githubusercontent.com/48075710/74957181-7a34b400-5407-11ea-92b0-2e2a145d51aa.PNG)
![pic 1](https://user-images.githubusercontent.com/48075710/74957201-7ef96800-5407-11ea-9fa0-73008d03155a.png)

**Comment by JeffreyDavidsz** [comment]
Probably a version issue. When you download the newer version of the listener it will connect ok but none of the commands will work. When you move up to version 2.0 of companion (2.0 build in user area) you can choose for old and new). I'm going to close this, but feel free to ask again

**Comment by pedrag8** [comment]
Thanks ! I will try!

Il gio 20 feb 2020, 20:19 Jeffrey Davidsz <notifications@github.com> ha
scritto:
